package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class IRP_REP_PROCVOKey extends BaseVO {
    /**
     * This field corresponds to the database column IRP_REP_PROC.PROC_ID
     */
    private BigDecimal PROC_ID;

    /**
     * This field corresponds to the database column IRP_REP_PROC.REPORT_ID
     */
    private BigDecimal REPORT_ID;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_REP_PROC.PROC_ID
     *
     * @return the value of IRP_REP_PROC.PROC_ID
     */
    public BigDecimal getPROC_ID() {
        return PROC_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_REP_PROC.PROC_ID
     *
     * @param PROC_ID the value for IRP_REP_PROC.PROC_ID
     */
    public void setPROC_ID(BigDecimal PROC_ID) {
        this.PROC_ID = PROC_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_REP_PROC.REPORT_ID
     *
     * @return the value of IRP_REP_PROC.REPORT_ID
     */
    public BigDecimal getREPORT_ID() {
        return REPORT_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_REP_PROC.REPORT_ID
     *
     * @param REPORT_ID the value for IRP_REP_PROC.REPORT_ID
     */
    public void setREPORT_ID(BigDecimal REPORT_ID) {
        this.REPORT_ID = REPORT_ID;
    }
}