package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;

public class IRP_FCR_REPORTSVO extends BaseVO {
    /**
     * This field corresponds to the database column IRP_FCR_REPORTS.REPORT_TYPE
     */
    private String REPORT_TYPE;

    /**
     * This field corresponds to the database column IRP_FCR_REPORTS.GROUP_BY
     */
    private String GROUP_BY;

    /**
     * This field corresponds to the database column IRP_FCR_REPORTS.ROW_COLUMN
     */
    private String ROW_COLUMN;

    /**
     * This field corresponds to the database column IRP_FCR_REPORTS.CURRENCY_CALC
     */
    private String CURRENCY_CALC;

    /**
     * This field corresponds to the database column IRP_FCR_REPORTS.REPORT_PROG_REF
     */
    private String REPORT_PROG_REF;

    /**
     * This field corresponds to the database column IRP_FCR_REPORTS.APP_NAME
     */
    private String APP_NAME;
    
    /**
     * This field corresponds to the database column IRP_FCR_REPORTS.COL_TYPE
     */
    private String COL_TYPE;

    /**
     * This field corresponds to the database column IRP_FCR_REPORTS.FCR_REPORT_QUERY
     */
    private String FCR_REPORT_QUERY;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_FCR_REPORTS.REPORT_TYPE
     *
     * @return the value of IRP_FCR_REPORTS.REPORT_TYPE
     */
    public String getREPORT_TYPE() {
        return REPORT_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_FCR_REPORTS.REPORT_TYPE
     *
     * @param REPORT_TYPE the value for IRP_FCR_REPORTS.REPORT_TYPE
     */
    public void setREPORT_TYPE(String REPORT_TYPE) {
        this.REPORT_TYPE = REPORT_TYPE == null ? null : REPORT_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_FCR_REPORTS.GROUP_BY
     *
     * @return the value of IRP_FCR_REPORTS.GROUP_BY
     */
    public String getGROUP_BY() {
        return GROUP_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_FCR_REPORTS.GROUP_BY
     *
     * @param GROUP_BY the value for IRP_FCR_REPORTS.GROUP_BY
     */
    public void setGROUP_BY(String GROUP_BY) {
        this.GROUP_BY = GROUP_BY == null ? null : GROUP_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_FCR_REPORTS.ROW_COLUMN
     *
     * @return the value of IRP_FCR_REPORTS.ROW_COLUMN
     */
    public String getROW_COLUMN() {
        return ROW_COLUMN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_FCR_REPORTS.ROW_COLUMN
     *
     * @param ROW_COLUMN the value for IRP_FCR_REPORTS.ROW_COLUMN
     */
    public void setROW_COLUMN(String ROW_COLUMN) {
        this.ROW_COLUMN = ROW_COLUMN == null ? null : ROW_COLUMN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_FCR_REPORTS.CURRENCY_CALC
     *
     * @return the value of IRP_FCR_REPORTS.CURRENCY_CALC
     */
    public String getCURRENCY_CALC() {
        return CURRENCY_CALC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_FCR_REPORTS.CURRENCY_CALC
     *
     * @param CURRENCY_CALC the value for IRP_FCR_REPORTS.CURRENCY_CALC
     */
    public void setCURRENCY_CALC(String CURRENCY_CALC) {
        this.CURRENCY_CALC = CURRENCY_CALC == null ? null : CURRENCY_CALC.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_FCR_REPORTS.REPORT_PROG_REF
     *
     * @return the value of IRP_FCR_REPORTS.REPORT_PROG_REF
     */
    public String getREPORT_PROG_REF() {
        return REPORT_PROG_REF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_FCR_REPORTS.REPORT_PROG_REF
     *
     * @param REPORT_PROG_REF the value for IRP_FCR_REPORTS.REPORT_PROG_REF
     */
    public void setREPORT_PROG_REF(String REPORT_PROG_REF) {
        this.REPORT_PROG_REF = REPORT_PROG_REF == null ? null : REPORT_PROG_REF.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_FCR_REPORTS.APP_NAME
     *
     * @return the value of IRP_FCR_REPORTS.APP_NAME
     */
    public String getAPP_NAME() {
        return APP_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_FCR_REPORTS.APP_NAME
     *
     * @param APP_NAME the value for IRP_FCR_REPORTS.APP_NAME
     */
    public void setAPP_NAME(String APP_NAME) {
        this.APP_NAME = APP_NAME == null ? null : APP_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_FCR_REPORTS.COL_TYPE
     *
     * @return the value of IRP_FCR_REPORTS.COL_TYPE
     */
    public String getCOL_TYPE() {
        return COL_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_FCR_REPORTS.COL_TYPE
     *
     * @param COL_TYPE the value for IRP_FCR_REPORTS.COL_TYPE
     */
    public void setCOL_TYPE(String COL_TYPE) {
        this.COL_TYPE = COL_TYPE == null ? null : COL_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_FCR_REPORTS.FCR_REPORT_QUERY
     *
     * @return the value of IRP_FCR_REPORTS.FCR_REPORT_QUERY
     */
    public String getFCR_REPORT_QUERY() {
        return FCR_REPORT_QUERY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_FCR_REPORTS.FCR_REPORT_QUERY
     *
     * @param FCR_REPORT_QUERY the value for IRP_FCR_REPORTS.FCR_REPORT_QUERY
     */
    public void setFCR_REPORT_QUERY(String FCR_REPORT_QUERY) {
        this.FCR_REPORT_QUERY = FCR_REPORT_QUERY == null ? null : FCR_REPORT_QUERY.trim();
    }

}