package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class IRP_REP_PROC_PARAMSVO extends BaseVO {
    /**
     * This field corresponds to the database column IRP_REP_PROC_PARAMS.PARAM_NAME
     */
    private String PARAM_NAME;

    /**
     * This field corresponds to the database column IRP_REP_PROC_PARAMS.PROC_ID
     */
    private BigDecimal PROC_ID;

    /**
     * This field corresponds to the database column IRP_REP_PROC_PARAMS.REPORT_ID
     */
    private BigDecimal REPORT_ID;

    /**
     * This field corresponds to the database column IRP_REP_PROC_PARAMS.PARAM_ID
     */
    private BigDecimal PARAM_ID;

    /**
     * This field corresponds to the database column IRP_REP_PROC_PARAMS.PARAM_ORDER
     */
    private BigDecimal PARAM_ORDER;

    /**
     * This field corresponds to the database column IRP_REP_PROC_PARAMS.OUTPUT_PARAM_TYPE
     */
    private String OUTPUT_PARAM_TYPE;

    /**
     * This field corresponds to the database column IRP_REP_PROC_PARAMS.SUCCESS_VALUE
     */
    private String SUCCESS_VALUE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_REP_PROC_PARAMS.PARAM_NAME
     *
     * @return the value of IRP_REP_PROC_PARAMS.PARAM_NAME
     */
    public String getPARAM_NAME() {
        return PARAM_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_REP_PROC_PARAMS.PARAM_NAME
     *
     * @param PARAM_NAME the value for IRP_REP_PROC_PARAMS.PARAM_NAME
     */
    public void setPARAM_NAME(String PARAM_NAME) {
        this.PARAM_NAME = PARAM_NAME == null ? null : PARAM_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_REP_PROC_PARAMS.PROC_ID
     *
     * @return the value of IRP_REP_PROC_PARAMS.PROC_ID
     */
    public BigDecimal getPROC_ID() {
        return PROC_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_REP_PROC_PARAMS.PROC_ID
     *
     * @param PROC_ID the value for IRP_REP_PROC_PARAMS.PROC_ID
     */
    public void setPROC_ID(BigDecimal PROC_ID) {
        this.PROC_ID = PROC_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_REP_PROC_PARAMS.REPORT_ID
     *
     * @return the value of IRP_REP_PROC_PARAMS.REPORT_ID
     */
    public BigDecimal getREPORT_ID() {
        return REPORT_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_REP_PROC_PARAMS.REPORT_ID
     *
     * @param REPORT_ID the value for IRP_REP_PROC_PARAMS.REPORT_ID
     */
    public void setREPORT_ID(BigDecimal REPORT_ID) {
        this.REPORT_ID = REPORT_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_REP_PROC_PARAMS.PARAM_ID
     *
     * @return the value of IRP_REP_PROC_PARAMS.PARAM_ID
     */
    public BigDecimal getPARAM_ID() {
        return PARAM_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_REP_PROC_PARAMS.PARAM_ID
     *
     * @param PARAM_ID the value for IRP_REP_PROC_PARAMS.PARAM_ID
     */
    public void setPARAM_ID(BigDecimal PARAM_ID) {
        this.PARAM_ID = PARAM_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_REP_PROC_PARAMS.PARAM_ORDER
     *
     * @return the value of IRP_REP_PROC_PARAMS.PARAM_ORDER
     */
    public BigDecimal getPARAM_ORDER() {
        return PARAM_ORDER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_REP_PROC_PARAMS.PARAM_ORDER
     *
     * @param PARAM_ORDER the value for IRP_REP_PROC_PARAMS.PARAM_ORDER
     */
    public void setPARAM_ORDER(BigDecimal PARAM_ORDER) {
        this.PARAM_ORDER = PARAM_ORDER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_REP_PROC_PARAMS.OUTPUT_PARAM_TYPE
     *
     * @return the value of IRP_REP_PROC_PARAMS.OUTPUT_PARAM_TYPE
     */
    public String getOUTPUT_PARAM_TYPE() {
        return OUTPUT_PARAM_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_REP_PROC_PARAMS.OUTPUT_PARAM_TYPE
     *
     * @param OUTPUT_PARAM_TYPE the value for IRP_REP_PROC_PARAMS.OUTPUT_PARAM_TYPE
     */
    public void setOUTPUT_PARAM_TYPE(String OUTPUT_PARAM_TYPE) {
        this.OUTPUT_PARAM_TYPE = OUTPUT_PARAM_TYPE == null ? null : OUTPUT_PARAM_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_REP_PROC_PARAMS.SUCCESS_VALUE
     *
     * @return the value of IRP_REP_PROC_PARAMS.SUCCESS_VALUE
     */
    public String getSUCCESS_VALUE() {
        return SUCCESS_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_REP_PROC_PARAMS.SUCCESS_VALUE
     *
     * @param SUCCESS_VALUE the value for IRP_REP_PROC_PARAMS.SUCCESS_VALUE
     */
    public void setSUCCESS_VALUE(String SUCCESS_VALUE) {
        this.SUCCESS_VALUE = SUCCESS_VALUE == null ? null : SUCCESS_VALUE.trim();
    }
}