package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class IRP_HASH_TABLE_REPORTVO extends BaseVO {
    /**
     * This field corresponds to the database column IRP_HASH_TABLE_REPORT.HASH_TABLE_ID
     */
    private BigDecimal HASH_TABLE_ID;

    /**
     * This field corresponds to the database column IRP_HASH_TABLE_REPORT.REPORT_ID
     */
    private BigDecimal REPORT_ID;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_HASH_TABLE_REPORT.HASH_TABLE_ID
     *
     * @return the value of IRP_HASH_TABLE_REPORT.HASH_TABLE_ID
     */
    public BigDecimal getHASH_TABLE_ID() {
        return HASH_TABLE_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_HASH_TABLE_REPORT.HASH_TABLE_ID
     *
     * @param HASH_TABLE_ID the value for IRP_HASH_TABLE_REPORT.HASH_TABLE_ID
     */
    public void setHASH_TABLE_ID(BigDecimal HASH_TABLE_ID) {
        this.HASH_TABLE_ID = HASH_TABLE_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_HASH_TABLE_REPORT.REPORT_ID
     *
     * @return the value of IRP_HASH_TABLE_REPORT.REPORT_ID
     */
    public BigDecimal getREPORT_ID() {
        return REPORT_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_HASH_TABLE_REPORT.REPORT_ID
     *
     * @param REPORT_ID the value for IRP_HASH_TABLE_REPORT.REPORT_ID
     */
    public void setREPORT_ID(BigDecimal REPORT_ID) {
        this.REPORT_ID = REPORT_ID;
    }
}