package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class IRP_HASH_TABLEVO extends BaseVO {
    /**
     * This field corresponds to the database column IRP_HASH_TABLE.HASH_TABLE_ID
     */
    private BigDecimal HASH_TABLE_ID;

    /**
     * This field corresponds to the database column IRP_HASH_TABLE.HASH_TABLE_NAME
     */
    private String HASH_TABLE_NAME;

    /**
     * This field corresponds to the database column IRP_HASH_TABLE.HASH_TABLE_SCRIPT
     */
    private String HASH_TABLE_SCRIPT;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_HASH_TABLE.HASH_TABLE_ID
     *
     * @return the value of IRP_HASH_TABLE.HASH_TABLE_ID
     */
    public BigDecimal getHASH_TABLE_ID() {
        return HASH_TABLE_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_HASH_TABLE.HASH_TABLE_ID
     *
     * @param HASH_TABLE_ID the value for IRP_HASH_TABLE.HASH_TABLE_ID
     */
    public void setHASH_TABLE_ID(BigDecimal HASH_TABLE_ID) {
        this.HASH_TABLE_ID = HASH_TABLE_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_HASH_TABLE.HASH_TABLE_NAME
     *
     * @return the value of IRP_HASH_TABLE.HASH_TABLE_NAME
     */
    public String getHASH_TABLE_NAME() {
        return HASH_TABLE_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_HASH_TABLE.HASH_TABLE_NAME
     *
     * @param HASH_TABLE_NAME the value for IRP_HASH_TABLE.HASH_TABLE_NAME
     */
    public void setHASH_TABLE_NAME(String HASH_TABLE_NAME) {
        this.HASH_TABLE_NAME = HASH_TABLE_NAME == null ? null : HASH_TABLE_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_HASH_TABLE.HASH_TABLE_SCRIPT
     *
     * @return the value of IRP_HASH_TABLE.HASH_TABLE_SCRIPT
     */
    public String getHASH_TABLE_SCRIPT() {
        return HASH_TABLE_SCRIPT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_HASH_TABLE.HASH_TABLE_SCRIPT
     *
     * @param HASH_TABLE_SCRIPT the value for IRP_HASH_TABLE.HASH_TABLE_SCRIPT
     */
    public void setHASH_TABLE_SCRIPT(String HASH_TABLE_SCRIPT) {
        this.HASH_TABLE_SCRIPT = HASH_TABLE_SCRIPT == null ? null : HASH_TABLE_SCRIPT.trim();
    }
}