package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class IRP_REP_HYPERLINKSVO extends IRP_REP_HYPERLINKSVOKey {
    /**
     * This field corresponds to the database column IRP_REP_HYPERLINKS.LINKED_REPORT_ID
     */
    private BigDecimal LINKED_REPORT_ID;

    /**
     * This field corresponds to the database column IRP_REP_HYPERLINKS.ARGUMENT_TYPE
     */
    private BigDecimal ARGUMENT_TYPE;

    /**
     * This field corresponds to the database column IRP_REP_HYPERLINKS.VALUE_STATIC
     */
    private String VALUE_STATIC;

    /**
     * This field corresponds to the database column IRP_REP_HYPERLINKS.VALUE_SESSION
     */
    private String VALUE_SESSION;

    /**
     * This field corresponds to the database column IRP_REP_HYPERLINKS.VALUE_COLUMN
     */
    private String VALUE_COLUMN;

    /**
     * This field corresponds to the database column IRP_REP_HYPERLINKS.FIELD_INDEX
     */
    private BigDecimal FIELD_INDEX;

    /**
     * This field corresponds to the database column IRP_REP_HYPERLINKS.LINKED_FIELD_INDEX
     */
    private BigDecimal LINKED_FIELD_INDEX;

    /**
     * This field corresponds to the database column IRP_REP_HYPERLINKS.DATE_UPDATED
     */
    private Date DATE_UPDATED;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_REP_HYPERLINKS.LINKED_REPORT_ID
     *
     * @return the value of IRP_REP_HYPERLINKS.LINKED_REPORT_ID
     */
    public BigDecimal getLINKED_REPORT_ID() {
        return LINKED_REPORT_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_REP_HYPERLINKS.LINKED_REPORT_ID
     *
     * @param LINKED_REPORT_ID the value for IRP_REP_HYPERLINKS.LINKED_REPORT_ID
     */
    public void setLINKED_REPORT_ID(BigDecimal LINKED_REPORT_ID) {
        this.LINKED_REPORT_ID = LINKED_REPORT_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_REP_HYPERLINKS.ARGUMENT_TYPE
     *
     * @return the value of IRP_REP_HYPERLINKS.ARGUMENT_TYPE
     */
    public BigDecimal getARGUMENT_TYPE() {
        return ARGUMENT_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_REP_HYPERLINKS.ARGUMENT_TYPE
     *
     * @param ARGUMENT_TYPE the value for IRP_REP_HYPERLINKS.ARGUMENT_TYPE
     */
    public void setARGUMENT_TYPE(BigDecimal ARGUMENT_TYPE) {
        this.ARGUMENT_TYPE = ARGUMENT_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_REP_HYPERLINKS.VALUE_STATIC
     *
     * @return the value of IRP_REP_HYPERLINKS.VALUE_STATIC
     */
    public String getVALUE_STATIC() {
        return VALUE_STATIC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_REP_HYPERLINKS.VALUE_STATIC
     *
     * @param VALUE_STATIC the value for IRP_REP_HYPERLINKS.VALUE_STATIC
     */
    public void setVALUE_STATIC(String VALUE_STATIC) {
        this.VALUE_STATIC = VALUE_STATIC == null ? null : VALUE_STATIC.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_REP_HYPERLINKS.VALUE_SESSION
     *
     * @return the value of IRP_REP_HYPERLINKS.VALUE_SESSION
     */
    public String getVALUE_SESSION() {
        return VALUE_SESSION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_REP_HYPERLINKS.VALUE_SESSION
     *
     * @param VALUE_SESSION the value for IRP_REP_HYPERLINKS.VALUE_SESSION
     */
    public void setVALUE_SESSION(String VALUE_SESSION) {
        this.VALUE_SESSION = VALUE_SESSION == null ? null : VALUE_SESSION.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_REP_HYPERLINKS.VALUE_COLUMN
     *
     * @return the value of IRP_REP_HYPERLINKS.VALUE_COLUMN
     */
    public String getVALUE_COLUMN() {
        return VALUE_COLUMN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_REP_HYPERLINKS.VALUE_COLUMN
     *
     * @param VALUE_COLUMN the value for IRP_REP_HYPERLINKS.VALUE_COLUMN
     */
    public void setVALUE_COLUMN(String VALUE_COLUMN) {
        this.VALUE_COLUMN = VALUE_COLUMN == null ? null : VALUE_COLUMN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_REP_HYPERLINKS.FIELD_INDEX
     *
     * @return the value of IRP_REP_HYPERLINKS.FIELD_INDEX
     */
    public BigDecimal getFIELD_INDEX() {
        return FIELD_INDEX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_REP_HYPERLINKS.FIELD_INDEX
     *
     * @param FIELD_INDEX the value for IRP_REP_HYPERLINKS.FIELD_INDEX
     */
    public void setFIELD_INDEX(BigDecimal FIELD_INDEX) {
        this.FIELD_INDEX = FIELD_INDEX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_REP_HYPERLINKS.LINKED_FIELD_INDEX
     *
     * @return the value of IRP_REP_HYPERLINKS.LINKED_FIELD_INDEX
     */
    public BigDecimal getLINKED_FIELD_INDEX() {
        return LINKED_FIELD_INDEX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_REP_HYPERLINKS.LINKED_FIELD_INDEX
     *
     * @param LINKED_FIELD_INDEX the value for IRP_REP_HYPERLINKS.LINKED_FIELD_INDEX
     */
    public void setLINKED_FIELD_INDEX(BigDecimal LINKED_FIELD_INDEX) {
        this.LINKED_FIELD_INDEX = LINKED_FIELD_INDEX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IRP_REP_HYPERLINKS.DATE_UPDATED
     *
     * @return the value of IRP_REP_HYPERLINKS.DATE_UPDATED
     */
    public Date getDATE_UPDATED() {
        return DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IRP_REP_HYPERLINKS.DATE_UPDATED
     *
     * @param DATE_UPDATED the value for IRP_REP_HYPERLINKS.DATE_UPDATED
     */
    public void setDATE_UPDATED(Date DATE_UPDATED) {
        this.DATE_UPDATED = DATE_UPDATED;
    }
}