package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class ACC_CLUBBING_FIN_RATEVOKey extends BaseVO {
    /**
     * This field corresponds to the database column ACC_CLUBBING_FIN_RATE.CLUBBING_CODE
     */
    private BigDecimal CLUBBING_CODE;

    /**
     * This field corresponds to the database column ACC_CLUBBING_FIN_RATE.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column ACC_CLUBBING_FIN_RATE.LINE_NO
     */
    private BigDecimal LINE_NO;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACC_CLUBBING_FIN_RATE.CLUBBING_CODE
     *
     * @return the value of ACC_CLUBBING_FIN_RATE.CLUBBING_CODE
     */
    public BigDecimal getCLUBBING_CODE() {
        return CLUBBING_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACC_CLUBBING_FIN_RATE.CLUBBING_CODE
     *
     * @param CLUBBING_CODE the value for ACC_CLUBBING_FIN_RATE.CLUBBING_CODE
     */
    public void setCLUBBING_CODE(BigDecimal CLUBBING_CODE) {
        this.CLUBBING_CODE = CLUBBING_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACC_CLUBBING_FIN_RATE.COMP_CODE
     *
     * @return the value of ACC_CLUBBING_FIN_RATE.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACC_CLUBBING_FIN_RATE.COMP_CODE
     *
     * @param COMP_CODE the value for ACC_CLUBBING_FIN_RATE.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACC_CLUBBING_FIN_RATE.LINE_NO
     *
     * @return the value of ACC_CLUBBING_FIN_RATE.LINE_NO
     */
    public BigDecimal getLINE_NO() {
        return LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACC_CLUBBING_FIN_RATE.LINE_NO
     *
     * @param LINE_NO the value for ACC_CLUBBING_FIN_RATE.LINE_NO
     */
    public void setLINE_NO(BigDecimal LINE_NO) {
        this.LINE_NO = LINE_NO;
    }
}