package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class ACC_VATVO extends ACC_VATVOKey {
    /**
     * This field corresponds to the database column ACC_VAT.LONG_DESC_ENG
     */
    private String LONG_DESC_ENG;

    /**
     * This field corresponds to the database column ACC_VAT.BRIEF_DESC_ENG
     */
    private String BRIEF_DESC_ENG;

    /**
     * This field corresponds to the database column ACC_VAT.LONG_DESC_ARAB
     */
    private String LONG_DESC_ARAB;

    /**
     * This field corresponds to the database column ACC_VAT.BRIEF_DESC_ARAB
     */
    private String BRIEF_DESC_ARAB;

    /**
     * This field corresponds to the database column ACC_VAT.REFERENCE
     */
    private String REFERENCE;

    /**
     * This field corresponds to the database column ACC_VAT.VAT_PERCT
     */
    private BigDecimal VAT_PERCT;

    /**
     * This field corresponds to the database column ACC_VAT.SUPERIOR_MARGIN
     */
    private BigDecimal SUPERIOR_MARGIN;

    /**
     * This field corresponds to the database column ACC_VAT.INFERIOR_MARGIN
     */
    private BigDecimal INFERIOR_MARGIN;

    /**
     * This field corresponds to the database column ACC_VAT.CR_CY
     */
    private BigDecimal CR_CY;

    /**
     * This field corresponds to the database column ACC_VAT.CR_GL
     */
    private BigDecimal CR_GL;

    /**
     * This field corresponds to the database column ACC_VAT.CR_CIF
     */
    private BigDecimal CR_CIF;

    /**
     * This field corresponds to the database column ACC_VAT.CR_SL
     */
    private BigDecimal CR_SL;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACC_VAT.LONG_DESC_ENG
     *
     * @return the value of ACC_VAT.LONG_DESC_ENG
     */
    public String getLONG_DESC_ENG() {
        return LONG_DESC_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACC_VAT.LONG_DESC_ENG
     *
     * @param LONG_DESC_ENG the value for ACC_VAT.LONG_DESC_ENG
     */
    public void setLONG_DESC_ENG(String LONG_DESC_ENG) {
        this.LONG_DESC_ENG = LONG_DESC_ENG == null ? null : LONG_DESC_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACC_VAT.BRIEF_DESC_ENG
     *
     * @return the value of ACC_VAT.BRIEF_DESC_ENG
     */
    public String getBRIEF_DESC_ENG() {
        return BRIEF_DESC_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACC_VAT.BRIEF_DESC_ENG
     *
     * @param BRIEF_DESC_ENG the value for ACC_VAT.BRIEF_DESC_ENG
     */
    public void setBRIEF_DESC_ENG(String BRIEF_DESC_ENG) {
        this.BRIEF_DESC_ENG = BRIEF_DESC_ENG == null ? null : BRIEF_DESC_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACC_VAT.LONG_DESC_ARAB
     *
     * @return the value of ACC_VAT.LONG_DESC_ARAB
     */
    public String getLONG_DESC_ARAB() {
        return LONG_DESC_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACC_VAT.LONG_DESC_ARAB
     *
     * @param LONG_DESC_ARAB the value for ACC_VAT.LONG_DESC_ARAB
     */
    public void setLONG_DESC_ARAB(String LONG_DESC_ARAB) {
        this.LONG_DESC_ARAB = LONG_DESC_ARAB == null ? null : LONG_DESC_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACC_VAT.BRIEF_DESC_ARAB
     *
     * @return the value of ACC_VAT.BRIEF_DESC_ARAB
     */
    public String getBRIEF_DESC_ARAB() {
        return BRIEF_DESC_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACC_VAT.BRIEF_DESC_ARAB
     *
     * @param BRIEF_DESC_ARAB the value for ACC_VAT.BRIEF_DESC_ARAB
     */
    public void setBRIEF_DESC_ARAB(String BRIEF_DESC_ARAB) {
        this.BRIEF_DESC_ARAB = BRIEF_DESC_ARAB == null ? null : BRIEF_DESC_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACC_VAT.REFERENCE
     *
     * @return the value of ACC_VAT.REFERENCE
     */
    public String getREFERENCE() {
        return REFERENCE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACC_VAT.REFERENCE
     *
     * @param REFERENCE the value for ACC_VAT.REFERENCE
     */
    public void setREFERENCE(String REFERENCE) {
        this.REFERENCE = REFERENCE == null ? null : REFERENCE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACC_VAT.VAT_PERCT
     *
     * @return the value of ACC_VAT.VAT_PERCT
     */
    public BigDecimal getVAT_PERCT() {
        return VAT_PERCT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACC_VAT.VAT_PERCT
     *
     * @param VAT_PERCT the value for ACC_VAT.VAT_PERCT
     */
    public void setVAT_PERCT(BigDecimal VAT_PERCT) {
        this.VAT_PERCT = VAT_PERCT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACC_VAT.SUPERIOR_MARGIN
     *
     * @return the value of ACC_VAT.SUPERIOR_MARGIN
     */
    public BigDecimal getSUPERIOR_MARGIN() {
        return SUPERIOR_MARGIN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACC_VAT.SUPERIOR_MARGIN
     *
     * @param SUPERIOR_MARGIN the value for ACC_VAT.SUPERIOR_MARGIN
     */
    public void setSUPERIOR_MARGIN(BigDecimal SUPERIOR_MARGIN) {
        this.SUPERIOR_MARGIN = SUPERIOR_MARGIN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACC_VAT.INFERIOR_MARGIN
     *
     * @return the value of ACC_VAT.INFERIOR_MARGIN
     */
    public BigDecimal getINFERIOR_MARGIN() {
        return INFERIOR_MARGIN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACC_VAT.INFERIOR_MARGIN
     *
     * @param INFERIOR_MARGIN the value for ACC_VAT.INFERIOR_MARGIN
     */
    public void setINFERIOR_MARGIN(BigDecimal INFERIOR_MARGIN) {
        this.INFERIOR_MARGIN = INFERIOR_MARGIN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACC_VAT.CR_CY
     *
     * @return the value of ACC_VAT.CR_CY
     */
    public BigDecimal getCR_CY() {
        return CR_CY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACC_VAT.CR_CY
     *
     * @param CR_CY the value for ACC_VAT.CR_CY
     */
    public void setCR_CY(BigDecimal CR_CY) {
        this.CR_CY = CR_CY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACC_VAT.CR_GL
     *
     * @return the value of ACC_VAT.CR_GL
     */
    public BigDecimal getCR_GL() {
        return CR_GL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACC_VAT.CR_GL
     *
     * @param CR_GL the value for ACC_VAT.CR_GL
     */
    public void setCR_GL(BigDecimal CR_GL) {
        this.CR_GL = CR_GL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACC_VAT.CR_CIF
     *
     * @return the value of ACC_VAT.CR_CIF
     */
    public BigDecimal getCR_CIF() {
        return CR_CIF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACC_VAT.CR_CIF
     *
     * @param CR_CIF the value for ACC_VAT.CR_CIF
     */
    public void setCR_CIF(BigDecimal CR_CIF) {
        this.CR_CIF = CR_CIF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACC_VAT.CR_SL
     *
     * @return the value of ACC_VAT.CR_SL
     */
    public BigDecimal getCR_SL() {
        return CR_SL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACC_VAT.CR_SL
     *
     * @param CR_SL the value for ACC_VAT.CR_SL
     */
    public void setCR_SL(BigDecimal CR_SL) {
        this.CR_SL = CR_SL;
    }
}