package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class ACC_CLUBBING_GROUPVOKey extends BaseVO {
    /**
     * This field corresponds to the database column ACC_CLUBBING_GROUP.BRANCH_CODE
     */
    private BigDecimal BRANCH_CODE;

    /**
     * This field corresponds to the database column ACC_CLUBBING_GROUP.CLUBBING_CODE
     */
    private BigDecimal CLUBBING_CODE;

    /**
     * This field corresponds to the database column ACC_CLUBBING_GROUP.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACC_CLUBBING_GROUP.BRANCH_CODE
     *
     * @return the value of ACC_CLUBBING_GROUP.BRANCH_CODE
     */
    public BigDecimal getBRANCH_CODE() {
        return BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACC_CLUBBING_GROUP.BRANCH_CODE
     *
     * @param BRANCH_CODE the value for ACC_CLUBBING_GROUP.BRANCH_CODE
     */
    public void setBRANCH_CODE(BigDecimal BRANCH_CODE) {
        this.BRANCH_CODE = BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACC_CLUBBING_GROUP.CLUBBING_CODE
     *
     * @return the value of ACC_CLUBBING_GROUP.CLUBBING_CODE
     */
    public BigDecimal getCLUBBING_CODE() {
        return CLUBBING_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACC_CLUBBING_GROUP.CLUBBING_CODE
     *
     * @param CLUBBING_CODE the value for ACC_CLUBBING_GROUP.CLUBBING_CODE
     */
    public void setCLUBBING_CODE(BigDecimal CLUBBING_CODE) {
        this.CLUBBING_CODE = CLUBBING_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACC_CLUBBING_GROUP.COMP_CODE
     *
     * @return the value of ACC_CLUBBING_GROUP.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACC_CLUBBING_GROUP.COMP_CODE
     *
     * @param COMP_CODE the value for ACC_CLUBBING_GROUP.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }
}