package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class ACC_CLUBBING_FIN_RATEVO extends ACC_CLUBBING_FIN_RATEVOKey {
    /**
     * This field corresponds to the database column ACC_CLUBBING_FIN_RATE.BRANCH_CODE
     */
    private BigDecimal BRANCH_CODE;

    /**
     * This field corresponds to the database column ACC_CLUBBING_FIN_RATE.FR_GRP_DEPOSIT_BAL
     */
    private BigDecimal FR_GRP_DEPOSIT_BAL;

    /**
     * This field corresponds to the database column ACC_CLUBBING_FIN_RATE.TO_GRP_DEPOSIT_BAL
     */
    private BigDecimal TO_GRP_DEPOSIT_BAL;

    /**
     * This field corresponds to the database column ACC_CLUBBING_FIN_RATE.MARGIN_RATE
     */
    private BigDecimal MARGIN_RATE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACC_CLUBBING_FIN_RATE.BRANCH_CODE
     *
     * @return the value of ACC_CLUBBING_FIN_RATE.BRANCH_CODE
     */
    public BigDecimal getBRANCH_CODE() {
        return BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACC_CLUBBING_FIN_RATE.BRANCH_CODE
     *
     * @param BRANCH_CODE the value for ACC_CLUBBING_FIN_RATE.BRANCH_CODE
     */
    public void setBRANCH_CODE(BigDecimal BRANCH_CODE) {
        this.BRANCH_CODE = BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACC_CLUBBING_FIN_RATE.FR_GRP_DEPOSIT_BAL
     *
     * @return the value of ACC_CLUBBING_FIN_RATE.FR_GRP_DEPOSIT_BAL
     */
    public BigDecimal getFR_GRP_DEPOSIT_BAL() {
        return FR_GRP_DEPOSIT_BAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACC_CLUBBING_FIN_RATE.FR_GRP_DEPOSIT_BAL
     *
     * @param FR_GRP_DEPOSIT_BAL the value for ACC_CLUBBING_FIN_RATE.FR_GRP_DEPOSIT_BAL
     */
    public void setFR_GRP_DEPOSIT_BAL(BigDecimal FR_GRP_DEPOSIT_BAL) {
        this.FR_GRP_DEPOSIT_BAL = FR_GRP_DEPOSIT_BAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACC_CLUBBING_FIN_RATE.TO_GRP_DEPOSIT_BAL
     *
     * @return the value of ACC_CLUBBING_FIN_RATE.TO_GRP_DEPOSIT_BAL
     */
    public BigDecimal getTO_GRP_DEPOSIT_BAL() {
        return TO_GRP_DEPOSIT_BAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACC_CLUBBING_FIN_RATE.TO_GRP_DEPOSIT_BAL
     *
     * @param TO_GRP_DEPOSIT_BAL the value for ACC_CLUBBING_FIN_RATE.TO_GRP_DEPOSIT_BAL
     */
    public void setTO_GRP_DEPOSIT_BAL(BigDecimal TO_GRP_DEPOSIT_BAL) {
        this.TO_GRP_DEPOSIT_BAL = TO_GRP_DEPOSIT_BAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACC_CLUBBING_FIN_RATE.MARGIN_RATE
     *
     * @return the value of ACC_CLUBBING_FIN_RATE.MARGIN_RATE
     */
    public BigDecimal getMARGIN_RATE() {
        return MARGIN_RATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACC_CLUBBING_FIN_RATE.MARGIN_RATE
     *
     * @param MARGIN_RATE the value for ACC_CLUBBING_FIN_RATE.MARGIN_RATE
     */
    public void setMARGIN_RATE(BigDecimal MARGIN_RATE) {
        this.MARGIN_RATE = MARGIN_RATE;
    }
}