package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class ALL_ARGUMENTSVO extends BaseVO {
    /**
     * This field corresponds to the database column ALL_ARGUMENTS.OWNER
     */
    private String OWNER;

    /**
     * This field corresponds to the database column ALL_ARGUMENTS.OBJECT_NAME
     */
    private String OBJECT_NAME;

    /**
     * This field corresponds to the database column ALL_ARGUMENTS.PACKAGE_NAME
     */
    private String PACKAGE_NAME;

    /**
     * This field corresponds to the database column ALL_ARGUMENTS.OBJECT_ID
     */
    private BigDecimal OBJECT_ID;

    /**
     * This field corresponds to the database column ALL_ARGUMENTS.OVERLOAD
     */
    private String OVERLOAD;

    /**
     * This field corresponds to the database column ALL_ARGUMENTS.SUBPROGRAM_ID
     */
    private BigDecimal SUBPROGRAM_ID;

    /**
     * This field corresponds to the database column ALL_ARGUMENTS.ARGUMENT_NAME
     */
    private String ARGUMENT_NAME;

    /**
     * This field corresponds to the database column ALL_ARGUMENTS.POSITION
     */
    private BigDecimal POSITION;

    /**
     * This field corresponds to the database column ALL_ARGUMENTS.SEQUENCE
     */
    private BigDecimal SEQUENCE;

    /**
     * This field corresponds to the database column ALL_ARGUMENTS.DATA_LEVEL
     */
    private BigDecimal DATA_LEVEL;

    /**
     * This field corresponds to the database column ALL_ARGUMENTS.DATA_TYPE
     */
    private String DATA_TYPE;

    /**
     * This field corresponds to the database column ALL_ARGUMENTS.DEFAULTED
     */
    private String DEFAULTED;

    /**
     * This field corresponds to the database column ALL_ARGUMENTS.DEFAULT_LENGTH
     */
    private BigDecimal DEFAULT_LENGTH;

    /**
     * This field corresponds to the database column ALL_ARGUMENTS.IN_OUT
     */
    private String IN_OUT;

    /**
     * This field corresponds to the database column ALL_ARGUMENTS.DATA_LENGTH
     */
    private BigDecimal DATA_LENGTH;

    /**
     * This field corresponds to the database column ALL_ARGUMENTS.DATA_PRECISION
     */
    private BigDecimal DATA_PRECISION;

    /**
     * This field corresponds to the database column ALL_ARGUMENTS.DATA_SCALE
     */
    private BigDecimal DATA_SCALE;

    /**
     * This field corresponds to the database column ALL_ARGUMENTS.RADIX
     */
    private BigDecimal RADIX;

    /**
     * This field corresponds to the database column ALL_ARGUMENTS.CHARACTER_SET_NAME
     */
    private String CHARACTER_SET_NAME;

    /**
     * This field corresponds to the database column ALL_ARGUMENTS.TYPE_OWNER
     */
    private String TYPE_OWNER;

    /**
     * This field corresponds to the database column ALL_ARGUMENTS.TYPE_NAME
     */
    private String TYPE_NAME;

    /**
     * This field corresponds to the database column ALL_ARGUMENTS.TYPE_SUBNAME
     */
    private String TYPE_SUBNAME;

    /**
     * This field corresponds to the database column ALL_ARGUMENTS.TYPE_LINK
     */
    private String TYPE_LINK;

    /**
     * This field corresponds to the database column ALL_ARGUMENTS.PLS_TYPE
     */
    private String PLS_TYPE;

    /**
     * This field corresponds to the database column ALL_ARGUMENTS.CHAR_LENGTH
     */
    private BigDecimal CHAR_LENGTH;

    /**
     * This field corresponds to the database column ALL_ARGUMENTS.CHAR_USED
     */
    private String CHAR_USED;

    /**
     * This field corresponds to the database column ALL_ARGUMENTS.DEFAULT_VALUE
     */
    private String DEFAULT_VALUE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALL_ARGUMENTS.OWNER
     *
     * @return the value of ALL_ARGUMENTS.OWNER
     */
    public String getOWNER() {
        return OWNER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALL_ARGUMENTS.OWNER
     *
     * @param OWNER the value for ALL_ARGUMENTS.OWNER
     */
    public void setOWNER(String OWNER) {
        this.OWNER = OWNER == null ? null : OWNER.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALL_ARGUMENTS.OBJECT_NAME
     *
     * @return the value of ALL_ARGUMENTS.OBJECT_NAME
     */
    public String getOBJECT_NAME() {
        return OBJECT_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALL_ARGUMENTS.OBJECT_NAME
     *
     * @param OBJECT_NAME the value for ALL_ARGUMENTS.OBJECT_NAME
     */
    public void setOBJECT_NAME(String OBJECT_NAME) {
        this.OBJECT_NAME = OBJECT_NAME == null ? null : OBJECT_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALL_ARGUMENTS.PACKAGE_NAME
     *
     * @return the value of ALL_ARGUMENTS.PACKAGE_NAME
     */
    public String getPACKAGE_NAME() {
        return PACKAGE_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALL_ARGUMENTS.PACKAGE_NAME
     *
     * @param PACKAGE_NAME the value for ALL_ARGUMENTS.PACKAGE_NAME
     */
    public void setPACKAGE_NAME(String PACKAGE_NAME) {
        this.PACKAGE_NAME = PACKAGE_NAME == null ? null : PACKAGE_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALL_ARGUMENTS.OBJECT_ID
     *
     * @return the value of ALL_ARGUMENTS.OBJECT_ID
     */
    public BigDecimal getOBJECT_ID() {
        return OBJECT_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALL_ARGUMENTS.OBJECT_ID
     *
     * @param OBJECT_ID the value for ALL_ARGUMENTS.OBJECT_ID
     */
    public void setOBJECT_ID(BigDecimal OBJECT_ID) {
        this.OBJECT_ID = OBJECT_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALL_ARGUMENTS.OVERLOAD
     *
     * @return the value of ALL_ARGUMENTS.OVERLOAD
     */
    public String getOVERLOAD() {
        return OVERLOAD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALL_ARGUMENTS.OVERLOAD
     *
     * @param OVERLOAD the value for ALL_ARGUMENTS.OVERLOAD
     */
    public void setOVERLOAD(String OVERLOAD) {
        this.OVERLOAD = OVERLOAD == null ? null : OVERLOAD.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALL_ARGUMENTS.SUBPROGRAM_ID
     *
     * @return the value of ALL_ARGUMENTS.SUBPROGRAM_ID
     */
    public BigDecimal getSUBPROGRAM_ID() {
        return SUBPROGRAM_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALL_ARGUMENTS.SUBPROGRAM_ID
     *
     * @param SUBPROGRAM_ID the value for ALL_ARGUMENTS.SUBPROGRAM_ID
     */
    public void setSUBPROGRAM_ID(BigDecimal SUBPROGRAM_ID) {
        this.SUBPROGRAM_ID = SUBPROGRAM_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALL_ARGUMENTS.ARGUMENT_NAME
     *
     * @return the value of ALL_ARGUMENTS.ARGUMENT_NAME
     */
    public String getARGUMENT_NAME() {
        return ARGUMENT_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALL_ARGUMENTS.ARGUMENT_NAME
     *
     * @param ARGUMENT_NAME the value for ALL_ARGUMENTS.ARGUMENT_NAME
     */
    public void setARGUMENT_NAME(String ARGUMENT_NAME) {
        this.ARGUMENT_NAME = ARGUMENT_NAME == null ? null : ARGUMENT_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALL_ARGUMENTS.POSITION
     *
     * @return the value of ALL_ARGUMENTS.POSITION
     */
    public BigDecimal getPOSITION() {
        return POSITION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALL_ARGUMENTS.POSITION
     *
     * @param POSITION the value for ALL_ARGUMENTS.POSITION
     */
    public void setPOSITION(BigDecimal POSITION) {
        this.POSITION = POSITION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALL_ARGUMENTS.SEQUENCE
     *
     * @return the value of ALL_ARGUMENTS.SEQUENCE
     */
    public BigDecimal getSEQUENCE() {
        return SEQUENCE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALL_ARGUMENTS.SEQUENCE
     *
     * @param SEQUENCE the value for ALL_ARGUMENTS.SEQUENCE
     */
    public void setSEQUENCE(BigDecimal SEQUENCE) {
        this.SEQUENCE = SEQUENCE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALL_ARGUMENTS.DATA_LEVEL
     *
     * @return the value of ALL_ARGUMENTS.DATA_LEVEL
     */
    public BigDecimal getDATA_LEVEL() {
        return DATA_LEVEL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALL_ARGUMENTS.DATA_LEVEL
     *
     * @param DATA_LEVEL the value for ALL_ARGUMENTS.DATA_LEVEL
     */
    public void setDATA_LEVEL(BigDecimal DATA_LEVEL) {
        this.DATA_LEVEL = DATA_LEVEL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALL_ARGUMENTS.DATA_TYPE
     *
     * @return the value of ALL_ARGUMENTS.DATA_TYPE
     */
    public String getDATA_TYPE() {
        return DATA_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALL_ARGUMENTS.DATA_TYPE
     *
     * @param DATA_TYPE the value for ALL_ARGUMENTS.DATA_TYPE
     */
    public void setDATA_TYPE(String DATA_TYPE) {
        this.DATA_TYPE = DATA_TYPE == null ? null : DATA_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALL_ARGUMENTS.DEFAULTED
     *
     * @return the value of ALL_ARGUMENTS.DEFAULTED
     */
    public String getDEFAULTED() {
        return DEFAULTED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALL_ARGUMENTS.DEFAULTED
     *
     * @param DEFAULTED the value for ALL_ARGUMENTS.DEFAULTED
     */
    public void setDEFAULTED(String DEFAULTED) {
        this.DEFAULTED = DEFAULTED == null ? null : DEFAULTED.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALL_ARGUMENTS.DEFAULT_LENGTH
     *
     * @return the value of ALL_ARGUMENTS.DEFAULT_LENGTH
     */
    public BigDecimal getDEFAULT_LENGTH() {
        return DEFAULT_LENGTH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALL_ARGUMENTS.DEFAULT_LENGTH
     *
     * @param DEFAULT_LENGTH the value for ALL_ARGUMENTS.DEFAULT_LENGTH
     */
    public void setDEFAULT_LENGTH(BigDecimal DEFAULT_LENGTH) {
        this.DEFAULT_LENGTH = DEFAULT_LENGTH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALL_ARGUMENTS.IN_OUT
     *
     * @return the value of ALL_ARGUMENTS.IN_OUT
     */
    public String getIN_OUT() {
        return IN_OUT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALL_ARGUMENTS.IN_OUT
     *
     * @param IN_OUT the value for ALL_ARGUMENTS.IN_OUT
     */
    public void setIN_OUT(String IN_OUT) {
        this.IN_OUT = IN_OUT == null ? null : IN_OUT.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALL_ARGUMENTS.DATA_LENGTH
     *
     * @return the value of ALL_ARGUMENTS.DATA_LENGTH
     */
    public BigDecimal getDATA_LENGTH() {
        return DATA_LENGTH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALL_ARGUMENTS.DATA_LENGTH
     *
     * @param DATA_LENGTH the value for ALL_ARGUMENTS.DATA_LENGTH
     */
    public void setDATA_LENGTH(BigDecimal DATA_LENGTH) {
        this.DATA_LENGTH = DATA_LENGTH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALL_ARGUMENTS.DATA_PRECISION
     *
     * @return the value of ALL_ARGUMENTS.DATA_PRECISION
     */
    public BigDecimal getDATA_PRECISION() {
        return DATA_PRECISION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALL_ARGUMENTS.DATA_PRECISION
     *
     * @param DATA_PRECISION the value for ALL_ARGUMENTS.DATA_PRECISION
     */
    public void setDATA_PRECISION(BigDecimal DATA_PRECISION) {
        this.DATA_PRECISION = DATA_PRECISION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALL_ARGUMENTS.DATA_SCALE
     *
     * @return the value of ALL_ARGUMENTS.DATA_SCALE
     */
    public BigDecimal getDATA_SCALE() {
        return DATA_SCALE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALL_ARGUMENTS.DATA_SCALE
     *
     * @param DATA_SCALE the value for ALL_ARGUMENTS.DATA_SCALE
     */
    public void setDATA_SCALE(BigDecimal DATA_SCALE) {
        this.DATA_SCALE = DATA_SCALE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALL_ARGUMENTS.RADIX
     *
     * @return the value of ALL_ARGUMENTS.RADIX
     */
    public BigDecimal getRADIX() {
        return RADIX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALL_ARGUMENTS.RADIX
     *
     * @param RADIX the value for ALL_ARGUMENTS.RADIX
     */
    public void setRADIX(BigDecimal RADIX) {
        this.RADIX = RADIX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALL_ARGUMENTS.CHARACTER_SET_NAME
     *
     * @return the value of ALL_ARGUMENTS.CHARACTER_SET_NAME
     */
    public String getCHARACTER_SET_NAME() {
        return CHARACTER_SET_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALL_ARGUMENTS.CHARACTER_SET_NAME
     *
     * @param CHARACTER_SET_NAME the value for ALL_ARGUMENTS.CHARACTER_SET_NAME
     */
    public void setCHARACTER_SET_NAME(String CHARACTER_SET_NAME) {
        this.CHARACTER_SET_NAME = CHARACTER_SET_NAME == null ? null : CHARACTER_SET_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALL_ARGUMENTS.TYPE_OWNER
     *
     * @return the value of ALL_ARGUMENTS.TYPE_OWNER
     */
    public String getTYPE_OWNER() {
        return TYPE_OWNER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALL_ARGUMENTS.TYPE_OWNER
     *
     * @param TYPE_OWNER the value for ALL_ARGUMENTS.TYPE_OWNER
     */
    public void setTYPE_OWNER(String TYPE_OWNER) {
        this.TYPE_OWNER = TYPE_OWNER == null ? null : TYPE_OWNER.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALL_ARGUMENTS.TYPE_NAME
     *
     * @return the value of ALL_ARGUMENTS.TYPE_NAME
     */
    public String getTYPE_NAME() {
        return TYPE_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALL_ARGUMENTS.TYPE_NAME
     *
     * @param TYPE_NAME the value for ALL_ARGUMENTS.TYPE_NAME
     */
    public void setTYPE_NAME(String TYPE_NAME) {
        this.TYPE_NAME = TYPE_NAME == null ? null : TYPE_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALL_ARGUMENTS.TYPE_SUBNAME
     *
     * @return the value of ALL_ARGUMENTS.TYPE_SUBNAME
     */
    public String getTYPE_SUBNAME() {
        return TYPE_SUBNAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALL_ARGUMENTS.TYPE_SUBNAME
     *
     * @param TYPE_SUBNAME the value for ALL_ARGUMENTS.TYPE_SUBNAME
     */
    public void setTYPE_SUBNAME(String TYPE_SUBNAME) {
        this.TYPE_SUBNAME = TYPE_SUBNAME == null ? null : TYPE_SUBNAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALL_ARGUMENTS.TYPE_LINK
     *
     * @return the value of ALL_ARGUMENTS.TYPE_LINK
     */
    public String getTYPE_LINK() {
        return TYPE_LINK;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALL_ARGUMENTS.TYPE_LINK
     *
     * @param TYPE_LINK the value for ALL_ARGUMENTS.TYPE_LINK
     */
    public void setTYPE_LINK(String TYPE_LINK) {
        this.TYPE_LINK = TYPE_LINK == null ? null : TYPE_LINK.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALL_ARGUMENTS.PLS_TYPE
     *
     * @return the value of ALL_ARGUMENTS.PLS_TYPE
     */
    public String getPLS_TYPE() {
        return PLS_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALL_ARGUMENTS.PLS_TYPE
     *
     * @param PLS_TYPE the value for ALL_ARGUMENTS.PLS_TYPE
     */
    public void setPLS_TYPE(String PLS_TYPE) {
        this.PLS_TYPE = PLS_TYPE == null ? null : PLS_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALL_ARGUMENTS.CHAR_LENGTH
     *
     * @return the value of ALL_ARGUMENTS.CHAR_LENGTH
     */
    public BigDecimal getCHAR_LENGTH() {
        return CHAR_LENGTH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALL_ARGUMENTS.CHAR_LENGTH
     *
     * @param CHAR_LENGTH the value for ALL_ARGUMENTS.CHAR_LENGTH
     */
    public void setCHAR_LENGTH(BigDecimal CHAR_LENGTH) {
        this.CHAR_LENGTH = CHAR_LENGTH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALL_ARGUMENTS.CHAR_USED
     *
     * @return the value of ALL_ARGUMENTS.CHAR_USED
     */
    public String getCHAR_USED() {
        return CHAR_USED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALL_ARGUMENTS.CHAR_USED
     *
     * @param CHAR_USED the value for ALL_ARGUMENTS.CHAR_USED
     */
    public void setCHAR_USED(String CHAR_USED) {
        this.CHAR_USED = CHAR_USED == null ? null : CHAR_USED.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALL_ARGUMENTS.DEFAULT_VALUE
     *
     * @return the value of ALL_ARGUMENTS.DEFAULT_VALUE
     */
    public String getDEFAULT_VALUE() {
        return DEFAULT_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALL_ARGUMENTS.DEFAULT_VALUE
     *
     * @param DEFAULT_VALUE the value for ALL_ARGUMENTS.DEFAULT_VALUE
     */
    public void setDEFAULT_VALUE(String DEFAULT_VALUE) {
        this.DEFAULT_VALUE = DEFAULT_VALUE == null ? null : DEFAULT_VALUE.trim();
    }
}