package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;
import java.util.Date;

public class ALRT_ENG_MSGVO extends BaseVO {
    /**
     * This field corresponds to the database column ALRT_ENG_MSG.REQUEST_ID
     */
    private BigDecimal REQUEST_ID;

    /**
     * This field corresponds to the database column ALRT_ENG_MSG.EVENT_ID
     */
    private BigDecimal EVENT_ID;

    /**
     * This field corresponds to the database column ALRT_ENG_MSG.MSG_ID
     */
    private BigDecimal MSG_ID;

    /**
     * This field corresponds to the database column ALRT_ENG_MSG.SUB_ID
     */
    private BigDecimal SUB_ID;

    /**
     * This field corresponds to the database column ALRT_ENG_MSG.USER_ID
     */
    private String USER_ID;

    /**
     * This field corresponds to the database column ALRT_ENG_MSG.CHANNEL_ID
     */
    private String CHANNEL_ID;

    /**
     * This field corresponds to the database column ALRT_ENG_MSG.EMAIL_ID
     */
    private String EMAIL_ID;

    /**
     * This field corresponds to the database column ALRT_ENG_MSG.MOBILE_PHONE
     */
    private String MOBILE_PHONE;

    /**
     * This field corresponds to the database column ALRT_ENG_MSG.CIF_NO
     */
    private BigDecimal CIF_NO;

    /**
     * This field corresponds to the database column ALRT_ENG_MSG.ADDITIONAL_REFERENCE
     */
    private String ADDITIONAL_REFERENCE;

    /**
     * This field corresponds to the database column ALRT_ENG_MSG.BRANCH_CODE
     */
    private BigDecimal BRANCH_CODE;

    /**
     * This field corresponds to the database column ALRT_ENG_MSG.CURRENCY_CODE
     */
    private BigDecimal CURRENCY_CODE;

    /**
     * This field corresponds to the database column ALRT_ENG_MSG.GL_CODE
     */
    private BigDecimal GL_CODE;

    /**
     * This field corresponds to the database column ALRT_ENG_MSG.SL_NO
     */
    private BigDecimal SL_NO;

    /**
     * This field corresponds to the database column ALRT_ENG_MSG.IBAN_ACC_NO
     */
    private String IBAN_ACC_NO;

    /**
     * This field corresponds to the database column ALRT_ENG_MSG.STARTING_TIME
     */
    private Date STARTING_TIME;

    /**
     * This field corresponds to the database column ALRT_ENG_MSG.ENDING_TIME
     */
    private Date ENDING_TIME;

    /**
     * This field corresponds to the database column ALRT_ENG_MSG.STATUS
     */
    private String STATUS;

    /**
     * This field corresponds to the database column ALRT_ENG_MSG.OUTPUT_MSG
     */
    private String OUTPUT_MSG;

    /**
     * This field corresponds to the database column ALRT_ENG_MSG.MACHINE_NAME_IP
     */
    private String MACHINE_NAME_IP;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_ENG_MSG.REQUEST_ID
     *
     * @return the value of ALRT_ENG_MSG.REQUEST_ID
     */
    public BigDecimal getREQUEST_ID() {
        return REQUEST_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_ENG_MSG.REQUEST_ID
     *
     * @param REQUEST_ID the value for ALRT_ENG_MSG.REQUEST_ID
     */
    public void setREQUEST_ID(BigDecimal REQUEST_ID) {
        this.REQUEST_ID = REQUEST_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_ENG_MSG.EVENT_ID
     *
     * @return the value of ALRT_ENG_MSG.EVENT_ID
     */
    public BigDecimal getEVENT_ID() {
        return EVENT_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_ENG_MSG.EVENT_ID
     *
     * @param EVENT_ID the value for ALRT_ENG_MSG.EVENT_ID
     */
    public void setEVENT_ID(BigDecimal EVENT_ID) {
        this.EVENT_ID = EVENT_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_ENG_MSG.MSG_ID
     *
     * @return the value of ALRT_ENG_MSG.MSG_ID
     */
    public BigDecimal getMSG_ID() {
        return MSG_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_ENG_MSG.MSG_ID
     *
     * @param MSG_ID the value for ALRT_ENG_MSG.MSG_ID
     */
    public void setMSG_ID(BigDecimal MSG_ID) {
        this.MSG_ID = MSG_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_ENG_MSG.SUB_ID
     *
     * @return the value of ALRT_ENG_MSG.SUB_ID
     */
    public BigDecimal getSUB_ID() {
        return SUB_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_ENG_MSG.SUB_ID
     *
     * @param SUB_ID the value for ALRT_ENG_MSG.SUB_ID
     */
    public void setSUB_ID(BigDecimal SUB_ID) {
        this.SUB_ID = SUB_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_ENG_MSG.USER_ID
     *
     * @return the value of ALRT_ENG_MSG.USER_ID
     */
    public String getUSER_ID() {
        return USER_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_ENG_MSG.USER_ID
     *
     * @param USER_ID the value for ALRT_ENG_MSG.USER_ID
     */
    public void setUSER_ID(String USER_ID) {
        this.USER_ID = USER_ID == null ? null : USER_ID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_ENG_MSG.CHANNEL_ID
     *
     * @return the value of ALRT_ENG_MSG.CHANNEL_ID
     */
    public String getCHANNEL_ID() {
        return CHANNEL_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_ENG_MSG.CHANNEL_ID
     *
     * @param CHANNEL_ID the value for ALRT_ENG_MSG.CHANNEL_ID
     */
    public void setCHANNEL_ID(String CHANNEL_ID) {
        this.CHANNEL_ID = CHANNEL_ID == null ? null : CHANNEL_ID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_ENG_MSG.EMAIL_ID
     *
     * @return the value of ALRT_ENG_MSG.EMAIL_ID
     */
    public String getEMAIL_ID() {
        return EMAIL_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_ENG_MSG.EMAIL_ID
     *
     * @param EMAIL_ID the value for ALRT_ENG_MSG.EMAIL_ID
     */
    public void setEMAIL_ID(String EMAIL_ID) {
        this.EMAIL_ID = EMAIL_ID == null ? null : EMAIL_ID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_ENG_MSG.MOBILE_PHONE
     *
     * @return the value of ALRT_ENG_MSG.MOBILE_PHONE
     */
    public String getMOBILE_PHONE() {
        return MOBILE_PHONE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_ENG_MSG.MOBILE_PHONE
     *
     * @param MOBILE_PHONE the value for ALRT_ENG_MSG.MOBILE_PHONE
     */
    public void setMOBILE_PHONE(String MOBILE_PHONE) {
        this.MOBILE_PHONE = MOBILE_PHONE == null ? null : MOBILE_PHONE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_ENG_MSG.CIF_NO
     *
     * @return the value of ALRT_ENG_MSG.CIF_NO
     */
    public BigDecimal getCIF_NO() {
        return CIF_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_ENG_MSG.CIF_NO
     *
     * @param CIF_NO the value for ALRT_ENG_MSG.CIF_NO
     */
    public void setCIF_NO(BigDecimal CIF_NO) {
        this.CIF_NO = CIF_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_ENG_MSG.ADDITIONAL_REFERENCE
     *
     * @return the value of ALRT_ENG_MSG.ADDITIONAL_REFERENCE
     */
    public String getADDITIONAL_REFERENCE() {
        return ADDITIONAL_REFERENCE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_ENG_MSG.ADDITIONAL_REFERENCE
     *
     * @param ADDITIONAL_REFERENCE the value for ALRT_ENG_MSG.ADDITIONAL_REFERENCE
     */
    public void setADDITIONAL_REFERENCE(String ADDITIONAL_REFERENCE) {
        this.ADDITIONAL_REFERENCE = ADDITIONAL_REFERENCE == null ? null : ADDITIONAL_REFERENCE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_ENG_MSG.BRANCH_CODE
     *
     * @return the value of ALRT_ENG_MSG.BRANCH_CODE
     */
    public BigDecimal getBRANCH_CODE() {
        return BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_ENG_MSG.BRANCH_CODE
     *
     * @param BRANCH_CODE the value for ALRT_ENG_MSG.BRANCH_CODE
     */
    public void setBRANCH_CODE(BigDecimal BRANCH_CODE) {
        this.BRANCH_CODE = BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_ENG_MSG.CURRENCY_CODE
     *
     * @return the value of ALRT_ENG_MSG.CURRENCY_CODE
     */
    public BigDecimal getCURRENCY_CODE() {
        return CURRENCY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_ENG_MSG.CURRENCY_CODE
     *
     * @param CURRENCY_CODE the value for ALRT_ENG_MSG.CURRENCY_CODE
     */
    public void setCURRENCY_CODE(BigDecimal CURRENCY_CODE) {
        this.CURRENCY_CODE = CURRENCY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_ENG_MSG.GL_CODE
     *
     * @return the value of ALRT_ENG_MSG.GL_CODE
     */
    public BigDecimal getGL_CODE() {
        return GL_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_ENG_MSG.GL_CODE
     *
     * @param GL_CODE the value for ALRT_ENG_MSG.GL_CODE
     */
    public void setGL_CODE(BigDecimal GL_CODE) {
        this.GL_CODE = GL_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_ENG_MSG.SL_NO
     *
     * @return the value of ALRT_ENG_MSG.SL_NO
     */
    public BigDecimal getSL_NO() {
        return SL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_ENG_MSG.SL_NO
     *
     * @param SL_NO the value for ALRT_ENG_MSG.SL_NO
     */
    public void setSL_NO(BigDecimal SL_NO) {
        this.SL_NO = SL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_ENG_MSG.IBAN_ACC_NO
     *
     * @return the value of ALRT_ENG_MSG.IBAN_ACC_NO
     */
    public String getIBAN_ACC_NO() {
        return IBAN_ACC_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_ENG_MSG.IBAN_ACC_NO
     *
     * @param IBAN_ACC_NO the value for ALRT_ENG_MSG.IBAN_ACC_NO
     */
    public void setIBAN_ACC_NO(String IBAN_ACC_NO) {
        this.IBAN_ACC_NO = IBAN_ACC_NO == null ? null : IBAN_ACC_NO.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_ENG_MSG.STARTING_TIME
     *
     * @return the value of ALRT_ENG_MSG.STARTING_TIME
     */
    public Date getSTARTING_TIME() {
        return STARTING_TIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_ENG_MSG.STARTING_TIME
     *
     * @param STARTING_TIME the value for ALRT_ENG_MSG.STARTING_TIME
     */
    public void setSTARTING_TIME(Date STARTING_TIME) {
        this.STARTING_TIME = STARTING_TIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_ENG_MSG.ENDING_TIME
     *
     * @return the value of ALRT_ENG_MSG.ENDING_TIME
     */
    public Date getENDING_TIME() {
        return ENDING_TIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_ENG_MSG.ENDING_TIME
     *
     * @param ENDING_TIME the value for ALRT_ENG_MSG.ENDING_TIME
     */
    public void setENDING_TIME(Date ENDING_TIME) {
        this.ENDING_TIME = ENDING_TIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_ENG_MSG.STATUS
     *
     * @return the value of ALRT_ENG_MSG.STATUS
     */
    public String getSTATUS() {
        return STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_ENG_MSG.STATUS
     *
     * @param STATUS the value for ALRT_ENG_MSG.STATUS
     */
    public void setSTATUS(String STATUS) {
        this.STATUS = STATUS == null ? null : STATUS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_ENG_MSG.OUTPUT_MSG
     *
     * @return the value of ALRT_ENG_MSG.OUTPUT_MSG
     */
    public String getOUTPUT_MSG() {
        return OUTPUT_MSG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_ENG_MSG.OUTPUT_MSG
     *
     * @param OUTPUT_MSG the value for ALRT_ENG_MSG.OUTPUT_MSG
     */
    public void setOUTPUT_MSG(String OUTPUT_MSG) {
        this.OUTPUT_MSG = OUTPUT_MSG == null ? null : OUTPUT_MSG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_ENG_MSG.MACHINE_NAME_IP
     *
     * @return the value of ALRT_ENG_MSG.MACHINE_NAME_IP
     */
    public String getMACHINE_NAME_IP() {
        return MACHINE_NAME_IP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_ENG_MSG.MACHINE_NAME_IP
     *
     * @param MACHINE_NAME_IP the value for ALRT_ENG_MSG.MACHINE_NAME_IP
     */
    public void setMACHINE_NAME_IP(String MACHINE_NAME_IP) {
        this.MACHINE_NAME_IP = MACHINE_NAME_IP == null ? null : MACHINE_NAME_IP.trim();
    }
}