package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;
import java.util.Date;

public class ALRT_ENG_REQUESTVO extends BaseVO {
    /**
     * This field corresponds to the database column ALRT_ENG_REQUEST.REQUEST_ID
     */
    private BigDecimal REQUEST_ID;

    /**
     * This field corresponds to the database column ALRT_ENG_REQUEST.EVENT_ID
     */
    private BigDecimal EVENT_ID;

    /**
     * This field corresponds to the database column ALRT_ENG_REQUEST.RECEIVED_TIME
     */
    private Date RECEIVED_TIME;

    /**
     * This field corresponds to the database column ALRT_ENG_REQUEST.STARTING_TIME
     */
    private Date STARTING_TIME;

    /**
     * This field corresponds to the database column ALRT_ENG_REQUEST.ENDING_TIME
     */
    private Date ENDING_TIME;

    /**
     * This field corresponds to the database column ALRT_ENG_REQUEST.STATUS
     */
    private String STATUS;

    /**
     * This field corresponds to the database column ALRT_ENG_REQUEST.OUTPUT_MSG
     */
    private String OUTPUT_MSG;

    /**
     * This field corresponds to the database column ALRT_ENG_REQUEST.MACHINE_NAME_IP
     */
    private String MACHINE_NAME_IP;

    /**
     * This field corresponds to the database column ALRT_ENG_REQUEST.REQUEST_BODY
     */
    private String REQUEST_BODY;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_ENG_REQUEST.REQUEST_ID
     *
     * @return the value of ALRT_ENG_REQUEST.REQUEST_ID
     */
    public BigDecimal getREQUEST_ID() {
        return REQUEST_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_ENG_REQUEST.REQUEST_ID
     *
     * @param REQUEST_ID the value for ALRT_ENG_REQUEST.REQUEST_ID
     */
    public void setREQUEST_ID(BigDecimal REQUEST_ID) {
        this.REQUEST_ID = REQUEST_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_ENG_REQUEST.EVENT_ID
     *
     * @return the value of ALRT_ENG_REQUEST.EVENT_ID
     */
    public BigDecimal getEVENT_ID() {
        return EVENT_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_ENG_REQUEST.EVENT_ID
     *
     * @param EVENT_ID the value for ALRT_ENG_REQUEST.EVENT_ID
     */
    public void setEVENT_ID(BigDecimal EVENT_ID) {
        this.EVENT_ID = EVENT_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_ENG_REQUEST.RECEIVED_TIME
     *
     * @return the value of ALRT_ENG_REQUEST.RECEIVED_TIME
     */
    public Date getRECEIVED_TIME() {
        return RECEIVED_TIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_ENG_REQUEST.RECEIVED_TIME
     *
     * @param RECEIVED_TIME the value for ALRT_ENG_REQUEST.RECEIVED_TIME
     */
    public void setRECEIVED_TIME(Date RECEIVED_TIME) {
        this.RECEIVED_TIME = RECEIVED_TIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_ENG_REQUEST.STARTING_TIME
     *
     * @return the value of ALRT_ENG_REQUEST.STARTING_TIME
     */
    public Date getSTARTING_TIME() {
        return STARTING_TIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_ENG_REQUEST.STARTING_TIME
     *
     * @param STARTING_TIME the value for ALRT_ENG_REQUEST.STARTING_TIME
     */
    public void setSTARTING_TIME(Date STARTING_TIME) {
        this.STARTING_TIME = STARTING_TIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_ENG_REQUEST.ENDING_TIME
     *
     * @return the value of ALRT_ENG_REQUEST.ENDING_TIME
     */
    public Date getENDING_TIME() {
        return ENDING_TIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_ENG_REQUEST.ENDING_TIME
     *
     * @param ENDING_TIME the value for ALRT_ENG_REQUEST.ENDING_TIME
     */
    public void setENDING_TIME(Date ENDING_TIME) {
        this.ENDING_TIME = ENDING_TIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_ENG_REQUEST.STATUS
     *
     * @return the value of ALRT_ENG_REQUEST.STATUS
     */
    public String getSTATUS() {
        return STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_ENG_REQUEST.STATUS
     *
     * @param STATUS the value for ALRT_ENG_REQUEST.STATUS
     */
    public void setSTATUS(String STATUS) {
        this.STATUS = STATUS == null ? null : STATUS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_ENG_REQUEST.OUTPUT_MSG
     *
     * @return the value of ALRT_ENG_REQUEST.OUTPUT_MSG
     */
    public String getOUTPUT_MSG() {
        return OUTPUT_MSG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_ENG_REQUEST.OUTPUT_MSG
     *
     * @param OUTPUT_MSG the value for ALRT_ENG_REQUEST.OUTPUT_MSG
     */
    public void setOUTPUT_MSG(String OUTPUT_MSG) {
        this.OUTPUT_MSG = OUTPUT_MSG == null ? null : OUTPUT_MSG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_ENG_REQUEST.MACHINE_NAME_IP
     *
     * @return the value of ALRT_ENG_REQUEST.MACHINE_NAME_IP
     */
    public String getMACHINE_NAME_IP() {
        return MACHINE_NAME_IP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_ENG_REQUEST.MACHINE_NAME_IP
     *
     * @param MACHINE_NAME_IP the value for ALRT_ENG_REQUEST.MACHINE_NAME_IP
     */
    public void setMACHINE_NAME_IP(String MACHINE_NAME_IP) {
        this.MACHINE_NAME_IP = MACHINE_NAME_IP == null ? null : MACHINE_NAME_IP.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_ENG_REQUEST.REQUEST_BODY
     *
     * @return the value of ALRT_ENG_REQUEST.REQUEST_BODY
     */
    public String getREQUEST_BODY() {
        return REQUEST_BODY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_ENG_REQUEST.REQUEST_BODY
     *
     * @param REQUEST_BODY the value for ALRT_ENG_REQUEST.REQUEST_BODY
     */
    public void setREQUEST_BODY(String REQUEST_BODY) {
        this.REQUEST_BODY = REQUEST_BODY == null ? null : REQUEST_BODY.trim();
    }
}