package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class AML_CUSTOMERVOKey extends BaseVO {
    /**
     * This field corresponds to the database column AML_CUSTOMER.CUSTOMER_ID
     */
    private BigDecimal CUSTOMER_ID;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AML_CUSTOMER.CUSTOMER_ID
     *
     * @return the value of AML_CUSTOMER.CUSTOMER_ID
     */
    public BigDecimal getCUSTOMER_ID() {
        return CUSTOMER_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AML_CUSTOMER.CUSTOMER_ID
     *
     * @param CUSTOMER_ID the value for AML_CUSTOMER.CUSTOMER_ID
     */
    public void setCUSTOMER_ID(BigDecimal CUSTOMER_ID) {
        this.CUSTOMER_ID = CUSTOMER_ID;
    }
}