package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class AML_REASONVO extends AML_REASONVOKey {
	
	/**
     * This field corresponds to the database column AML_REASON.REASON_REF
     */
    private String REASON_REF;

    /**
     * This field corresponds to the database column IMAL141_AML_O18.AML_REASON.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column IMAL141_AML_O18.AML_REASON.CODE
     */
    private BigDecimal CODE;

    /**
     * This field corresponds to the database column IMAL141_AML_O18.AML_REASON.BRIEF_NAME_ENG
     */
    private String BRIEF_NAME_ENG;

    /**
     * This field corresponds to the database column IMAL141_AML_O18.AML_REASON.BRIEF_NAME_ARAB
     */
    private String BRIEF_NAME_ARAB;

    /**
     * This field corresponds to the database column IMAL141_AML_O18.AML_REASON.REASON_TYPE
     */
    private String REASON_TYPE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMAL141_AML_O18.AML_REASON.COMP_CODE
     *
     * @return the value of IMAL141_AML_O18.AML_REASON.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMAL141_AML_O18.AML_REASON.COMP_CODE
     *
     * @param COMP_CODE the value for IMAL141_AML_O18.AML_REASON.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMAL141_AML_O18.AML_REASON.CODE
     *
     * @return the value of IMAL141_AML_O18.AML_REASON.CODE
     */
    public BigDecimal getCODE() {
        return CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMAL141_AML_O18.AML_REASON.CODE
     *
     * @param CODE the value for IMAL141_AML_O18.AML_REASON.CODE
     */
    public void setCODE(BigDecimal CODE) {
        this.CODE = CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMAL141_AML_O18.AML_REASON.BRIEF_NAME_ENG
     *
     * @return the value of IMAL141_AML_O18.AML_REASON.BRIEF_NAME_ENG
     */
    public String getBRIEF_NAME_ENG() {
        return BRIEF_NAME_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMAL141_AML_O18.AML_REASON.BRIEF_NAME_ENG
     *
     * @param BRIEF_NAME_ENG the value for IMAL141_AML_O18.AML_REASON.BRIEF_NAME_ENG
     */
    public void setBRIEF_NAME_ENG(String BRIEF_NAME_ENG) {
        this.BRIEF_NAME_ENG = BRIEF_NAME_ENG == null ? null : BRIEF_NAME_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMAL141_AML_O18.AML_REASON.BRIEF_NAME_ARAB
     *
     * @return the value of IMAL141_AML_O18.AML_REASON.BRIEF_NAME_ARAB
     */
    public String getBRIEF_NAME_ARAB() {
        return BRIEF_NAME_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMAL141_AML_O18.AML_REASON.BRIEF_NAME_ARAB
     *
     * @param BRIEF_NAME_ARAB the value for IMAL141_AML_O18.AML_REASON.BRIEF_NAME_ARAB
     */
    public void setBRIEF_NAME_ARAB(String BRIEF_NAME_ARAB) {
        this.BRIEF_NAME_ARAB = BRIEF_NAME_ARAB == null ? null : BRIEF_NAME_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMAL141_AML_O18.AML_REASON.REASON_TYPE
     *
     * @return the value of IMAL141_AML_O18.AML_REASON.REASON_TYPE
     */
    public String getREASON_TYPE() {
        return REASON_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMAL141_AML_O18.AML_REASON.REASON_TYPE
     *
     * @param REASON_TYPE the value for IMAL141_AML_O18.AML_REASON.REASON_TYPE
     */
    public void setREASON_TYPE(String REASON_TYPE) {
        this.REASON_TYPE = REASON_TYPE == null ? null : REASON_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AML_REASON.REASON_REF
     *
     * @return the value of AML_REASON.REASON_REF
     */
    public String getREASON_REF() {
        return REASON_REF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AML_REASON.REASON_REF
     *
     * @param REASON_REF the value for AML_REASON.REASON_REF
     */
    public void setREASON_REF(String REASON_REF) {
        this.REASON_REF = REASON_REF == null ? null : REASON_REF.trim();
    }
}