package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class AML_KYCVO extends AML_KYCVOKey {
    /**
     * This field corresponds to the database column AML_KYC.CIF_NO
     */
    private BigDecimal CIF_NO;

    /**
     * This field corresponds to the database column AML_KYC.DATE_UPDATED
     */
    private Date DATE_UPDATED;

    /**
     * This field corresponds to the database column AML_KYC.ENTITY_STATUS
     */
    private String ENTITY_STATUS;

    /**
     * This field corresponds to the database column AML_KYC.CREATED_BY
     */
    private String CREATED_BY;

    /**
     * This field corresponds to the database column AML_KYC.CREATED_DATE
     */
    private Date CREATED_DATE;

    /**
     * This field corresponds to the database column AML_KYC.APPROVED_BY
     */
    private String APPROVED_BY;

    /**
     * This field corresponds to the database column AML_KYC.APPROVED_DATE
     */
    private Date APPROVED_DATE;

    /**
     * This field corresponds to the database column AML_KYC.MODIFIED_BY
     */
    private String MODIFIED_BY;

    /**
     * This field corresponds to the database column AML_KYC.MODIFIED_DATE
     */
    private Date MODIFIED_DATE;

    /**
     * This field corresponds to the database column AML_KYC.DELETED_BY
     */
    private String DELETED_BY;

    /**
     * This field corresponds to the database column AML_KYC.DELETED_DATE
     */
    private Date DELETED_DATE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AML_KYC.CIF_NO
     *
     * @return the value of AML_KYC.CIF_NO
     */
    public BigDecimal getCIF_NO() {
        return CIF_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AML_KYC.CIF_NO
     *
     * @param CIF_NO the value for AML_KYC.CIF_NO
     */
    public void setCIF_NO(BigDecimal CIF_NO) {
        this.CIF_NO = CIF_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AML_KYC.DATE_UPDATED
     *
     * @return the value of AML_KYC.DATE_UPDATED
     */
    public Date getDATE_UPDATED() {
        return DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AML_KYC.DATE_UPDATED
     *
     * @param DATE_UPDATED the value for AML_KYC.DATE_UPDATED
     */
    public void setDATE_UPDATED(Date DATE_UPDATED) {
        this.DATE_UPDATED = DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AML_KYC.ENTITY_STATUS
     *
     * @return the value of AML_KYC.ENTITY_STATUS
     */
    public String getENTITY_STATUS() {
        return ENTITY_STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AML_KYC.ENTITY_STATUS
     *
     * @param ENTITY_STATUS the value for AML_KYC.ENTITY_STATUS
     */
    public void setENTITY_STATUS(String ENTITY_STATUS) {
        this.ENTITY_STATUS = ENTITY_STATUS == null ? null : ENTITY_STATUS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AML_KYC.CREATED_BY
     *
     * @return the value of AML_KYC.CREATED_BY
     */
    public String getCREATED_BY() {
        return CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AML_KYC.CREATED_BY
     *
     * @param CREATED_BY the value for AML_KYC.CREATED_BY
     */
    public void setCREATED_BY(String CREATED_BY) {
        this.CREATED_BY = CREATED_BY == null ? null : CREATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AML_KYC.CREATED_DATE
     *
     * @return the value of AML_KYC.CREATED_DATE
     */
    public Date getCREATED_DATE() {
        return CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AML_KYC.CREATED_DATE
     *
     * @param CREATED_DATE the value for AML_KYC.CREATED_DATE
     */
    public void setCREATED_DATE(Date CREATED_DATE) {
        this.CREATED_DATE = CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AML_KYC.APPROVED_BY
     *
     * @return the value of AML_KYC.APPROVED_BY
     */
    public String getAPPROVED_BY() {
        return APPROVED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AML_KYC.APPROVED_BY
     *
     * @param APPROVED_BY the value for AML_KYC.APPROVED_BY
     */
    public void setAPPROVED_BY(String APPROVED_BY) {
        this.APPROVED_BY = APPROVED_BY == null ? null : APPROVED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AML_KYC.APPROVED_DATE
     *
     * @return the value of AML_KYC.APPROVED_DATE
     */
    public Date getAPPROVED_DATE() {
        return APPROVED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AML_KYC.APPROVED_DATE
     *
     * @param APPROVED_DATE the value for AML_KYC.APPROVED_DATE
     */
    public void setAPPROVED_DATE(Date APPROVED_DATE) {
        this.APPROVED_DATE = APPROVED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AML_KYC.MODIFIED_BY
     *
     * @return the value of AML_KYC.MODIFIED_BY
     */
    public String getMODIFIED_BY() {
        return MODIFIED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AML_KYC.MODIFIED_BY
     *
     * @param MODIFIED_BY the value for AML_KYC.MODIFIED_BY
     */
    public void setMODIFIED_BY(String MODIFIED_BY) {
        this.MODIFIED_BY = MODIFIED_BY == null ? null : MODIFIED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AML_KYC.MODIFIED_DATE
     *
     * @return the value of AML_KYC.MODIFIED_DATE
     */
    public Date getMODIFIED_DATE() {
        return MODIFIED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AML_KYC.MODIFIED_DATE
     *
     * @param MODIFIED_DATE the value for AML_KYC.MODIFIED_DATE
     */
    public void setMODIFIED_DATE(Date MODIFIED_DATE) {
        this.MODIFIED_DATE = MODIFIED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AML_KYC.DELETED_BY
     *
     * @return the value of AML_KYC.DELETED_BY
     */
    public String getDELETED_BY() {
        return DELETED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AML_KYC.DELETED_BY
     *
     * @param DELETED_BY the value for AML_KYC.DELETED_BY
     */
    public void setDELETED_BY(String DELETED_BY) {
        this.DELETED_BY = DELETED_BY == null ? null : DELETED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AML_KYC.DELETED_DATE
     *
     * @return the value of AML_KYC.DELETED_DATE
     */
    public Date getDELETED_DATE() {
        return DELETED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AML_KYC.DELETED_DATE
     *
     * @param DELETED_DATE the value for AML_KYC.DELETED_DATE
     */
    public void setDELETED_DATE(Date DELETED_DATE) {
        this.DELETED_DATE = DELETED_DATE;
    }
}