package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class AML_CUSTOMER_REVIEW_PRIORITYVO extends AML_CUSTOMER_REVIEW_PRIORITYVOKey {
    /**
     * This field corresponds to the database column AML_CUSTOMER_REVIEW_PRIORITY.FROM_VALUE
     */
    private BigDecimal FROM_VALUE;

    /**
     * This field corresponds to the database column AML_CUSTOMER_REVIEW_PRIORITY.TO_VALUE
     */
    private BigDecimal TO_VALUE;

    /**
     * This field corresponds to the database column AML_CUSTOMER_REVIEW_PRIORITY.RISK
     */
    private String RISK;

    /**
     * This field corresponds to the database column AML_CUSTOMER_REVIEW_PRIORITY.STATUS
     */
    private String STATUS;

    /**
     * This field corresponds to the database column AML_CUSTOMER_REVIEW_PRIORITY.CREATED_DATE
     */
    private Date CREATED_DATE;

    /**
     * This field corresponds to the database column AML_CUSTOMER_REVIEW_PRIORITY.CREATED_BY
     */
    private String CREATED_BY;

    /**
     * This field corresponds to the database column AML_CUSTOMER_REVIEW_PRIORITY.MODIFIED_DATE
     */
    private Date MODIFIED_DATE;

    /**
     * This field corresponds to the database column AML_CUSTOMER_REVIEW_PRIORITY.AUTHORIZED_BY
     */
    private String AUTHORIZED_BY;

    /**
     * This field corresponds to the database column AML_CUSTOMER_REVIEW_PRIORITY.AUTHORIZED_DATE
     */
    private Date AUTHORIZED_DATE;

    /**
     * This field corresponds to the database column AML_CUSTOMER_REVIEW_PRIORITY.REJECTED_BY
     */
    private String REJECTED_BY;

    /**
     * This field corresponds to the database column AML_CUSTOMER_REVIEW_PRIORITY.REJECTED_DATE
     */
    private Date REJECTED_DATE;

    /**
     * This field corresponds to the database column AML_CUSTOMER_REVIEW_PRIORITY.DELETED_BY
     */
    private String DELETED_BY;

    /**
     * This field corresponds to the database column AML_CUSTOMER_REVIEW_PRIORITY.DELETED_DATE
     */
    private Date DELETED_DATE;

    /**
     * This field corresponds to the database column AML_CUSTOMER_REVIEW_PRIORITY.MODIFIED_BY
     */
    private String MODIFIED_BY;

    /**
     * This field corresponds to the database column AML_CUSTOMER_REVIEW_PRIORITY.UPDATED_DATE
     */
    private Date UPDATED_DATE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AML_CUSTOMER_REVIEW_PRIORITY.FROM_VALUE
     *
     * @return the value of AML_CUSTOMER_REVIEW_PRIORITY.FROM_VALUE
     */
    public BigDecimal getFROM_VALUE() {
        return FROM_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AML_CUSTOMER_REVIEW_PRIORITY.FROM_VALUE
     *
     * @param FROM_VALUE the value for AML_CUSTOMER_REVIEW_PRIORITY.FROM_VALUE
     */
    public void setFROM_VALUE(BigDecimal FROM_VALUE) {
        this.FROM_VALUE = FROM_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AML_CUSTOMER_REVIEW_PRIORITY.TO_VALUE
     *
     * @return the value of AML_CUSTOMER_REVIEW_PRIORITY.TO_VALUE
     */
    public BigDecimal getTO_VALUE() {
        return TO_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AML_CUSTOMER_REVIEW_PRIORITY.TO_VALUE
     *
     * @param TO_VALUE the value for AML_CUSTOMER_REVIEW_PRIORITY.TO_VALUE
     */
    public void setTO_VALUE(BigDecimal TO_VALUE) {
        this.TO_VALUE = TO_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AML_CUSTOMER_REVIEW_PRIORITY.RISK
     *
     * @return the value of AML_CUSTOMER_REVIEW_PRIORITY.RISK
     */
    public String getRISK() {
        return RISK;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AML_CUSTOMER_REVIEW_PRIORITY.RISK
     *
     * @param RISK the value for AML_CUSTOMER_REVIEW_PRIORITY.RISK
     */
    public void setRISK(String RISK) {
        this.RISK = RISK == null ? null : RISK.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AML_CUSTOMER_REVIEW_PRIORITY.STATUS
     *
     * @return the value of AML_CUSTOMER_REVIEW_PRIORITY.STATUS
     */
    public String getSTATUS() {
        return STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AML_CUSTOMER_REVIEW_PRIORITY.STATUS
     *
     * @param STATUS the value for AML_CUSTOMER_REVIEW_PRIORITY.STATUS
     */
    public void setSTATUS(String STATUS) {
        this.STATUS = STATUS == null ? null : STATUS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AML_CUSTOMER_REVIEW_PRIORITY.CREATED_DATE
     *
     * @return the value of AML_CUSTOMER_REVIEW_PRIORITY.CREATED_DATE
     */
    public Date getCREATED_DATE() {
        return CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AML_CUSTOMER_REVIEW_PRIORITY.CREATED_DATE
     *
     * @param CREATED_DATE the value for AML_CUSTOMER_REVIEW_PRIORITY.CREATED_DATE
     */
    public void setCREATED_DATE(Date CREATED_DATE) {
        this.CREATED_DATE = CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AML_CUSTOMER_REVIEW_PRIORITY.CREATED_BY
     *
     * @return the value of AML_CUSTOMER_REVIEW_PRIORITY.CREATED_BY
     */
    public String getCREATED_BY() {
        return CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AML_CUSTOMER_REVIEW_PRIORITY.CREATED_BY
     *
     * @param CREATED_BY the value for AML_CUSTOMER_REVIEW_PRIORITY.CREATED_BY
     */
    public void setCREATED_BY(String CREATED_BY) {
        this.CREATED_BY = CREATED_BY == null ? null : CREATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AML_CUSTOMER_REVIEW_PRIORITY.MODIFIED_DATE
     *
     * @return the value of AML_CUSTOMER_REVIEW_PRIORITY.MODIFIED_DATE
     */
    public Date getMODIFIED_DATE() {
        return MODIFIED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AML_CUSTOMER_REVIEW_PRIORITY.MODIFIED_DATE
     *
     * @param MODIFIED_DATE the value for AML_CUSTOMER_REVIEW_PRIORITY.MODIFIED_DATE
     */
    public void setMODIFIED_DATE(Date MODIFIED_DATE) {
        this.MODIFIED_DATE = MODIFIED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AML_CUSTOMER_REVIEW_PRIORITY.AUTHORIZED_BY
     *
     * @return the value of AML_CUSTOMER_REVIEW_PRIORITY.AUTHORIZED_BY
     */
    public String getAUTHORIZED_BY() {
        return AUTHORIZED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AML_CUSTOMER_REVIEW_PRIORITY.AUTHORIZED_BY
     *
     * @param AUTHORIZED_BY the value for AML_CUSTOMER_REVIEW_PRIORITY.AUTHORIZED_BY
     */
    public void setAUTHORIZED_BY(String AUTHORIZED_BY) {
        this.AUTHORIZED_BY = AUTHORIZED_BY == null ? null : AUTHORIZED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AML_CUSTOMER_REVIEW_PRIORITY.AUTHORIZED_DATE
     *
     * @return the value of AML_CUSTOMER_REVIEW_PRIORITY.AUTHORIZED_DATE
     */
    public Date getAUTHORIZED_DATE() {
        return AUTHORIZED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AML_CUSTOMER_REVIEW_PRIORITY.AUTHORIZED_DATE
     *
     * @param AUTHORIZED_DATE the value for AML_CUSTOMER_REVIEW_PRIORITY.AUTHORIZED_DATE
     */
    public void setAUTHORIZED_DATE(Date AUTHORIZED_DATE) {
        this.AUTHORIZED_DATE = AUTHORIZED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AML_CUSTOMER_REVIEW_PRIORITY.REJECTED_BY
     *
     * @return the value of AML_CUSTOMER_REVIEW_PRIORITY.REJECTED_BY
     */
    public String getREJECTED_BY() {
        return REJECTED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AML_CUSTOMER_REVIEW_PRIORITY.REJECTED_BY
     *
     * @param REJECTED_BY the value for AML_CUSTOMER_REVIEW_PRIORITY.REJECTED_BY
     */
    public void setREJECTED_BY(String REJECTED_BY) {
        this.REJECTED_BY = REJECTED_BY == null ? null : REJECTED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AML_CUSTOMER_REVIEW_PRIORITY.REJECTED_DATE
     *
     * @return the value of AML_CUSTOMER_REVIEW_PRIORITY.REJECTED_DATE
     */
    public Date getREJECTED_DATE() {
        return REJECTED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AML_CUSTOMER_REVIEW_PRIORITY.REJECTED_DATE
     *
     * @param REJECTED_DATE the value for AML_CUSTOMER_REVIEW_PRIORITY.REJECTED_DATE
     */
    public void setREJECTED_DATE(Date REJECTED_DATE) {
        this.REJECTED_DATE = REJECTED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AML_CUSTOMER_REVIEW_PRIORITY.DELETED_BY
     *
     * @return the value of AML_CUSTOMER_REVIEW_PRIORITY.DELETED_BY
     */
    public String getDELETED_BY() {
        return DELETED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AML_CUSTOMER_REVIEW_PRIORITY.DELETED_BY
     *
     * @param DELETED_BY the value for AML_CUSTOMER_REVIEW_PRIORITY.DELETED_BY
     */
    public void setDELETED_BY(String DELETED_BY) {
        this.DELETED_BY = DELETED_BY == null ? null : DELETED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AML_CUSTOMER_REVIEW_PRIORITY.DELETED_DATE
     *
     * @return the value of AML_CUSTOMER_REVIEW_PRIORITY.DELETED_DATE
     */
    public Date getDELETED_DATE() {
        return DELETED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AML_CUSTOMER_REVIEW_PRIORITY.DELETED_DATE
     *
     * @param DELETED_DATE the value for AML_CUSTOMER_REVIEW_PRIORITY.DELETED_DATE
     */
    public void setDELETED_DATE(Date DELETED_DATE) {
        this.DELETED_DATE = DELETED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AML_CUSTOMER_REVIEW_PRIORITY.MODIFIED_BY
     *
     * @return the value of AML_CUSTOMER_REVIEW_PRIORITY.MODIFIED_BY
     */
    public String getMODIFIED_BY() {
        return MODIFIED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AML_CUSTOMER_REVIEW_PRIORITY.MODIFIED_BY
     *
     * @param MODIFIED_BY the value for AML_CUSTOMER_REVIEW_PRIORITY.MODIFIED_BY
     */
    public void setMODIFIED_BY(String MODIFIED_BY) {
        this.MODIFIED_BY = MODIFIED_BY == null ? null : MODIFIED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AML_CUSTOMER_REVIEW_PRIORITY.UPDATED_DATE
     *
     * @return the value of AML_CUSTOMER_REVIEW_PRIORITY.UPDATED_DATE
     */
    public Date getUPDATED_DATE() {
        return UPDATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AML_CUSTOMER_REVIEW_PRIORITY.UPDATED_DATE
     *
     * @param UPDATED_DATE the value for AML_CUSTOMER_REVIEW_PRIORITY.UPDATED_DATE
     */
    public void setUPDATED_DATE(Date UPDATED_DATE) {
        this.UPDATED_DATE = UPDATED_DATE;
    }
}