package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class APPVO extends BaseVO {
    /**
     * This field corresponds to the database column APP.APP_ID
     */
    private BigDecimal APP_ID;

    /**
     * This field corresponds to the database column APP.BRIEF_NAME
     */
    private String BRIEF_NAME;

    /**
     * This field corresponds to the database column APP.LONG_NAME
     */
    private String LONG_NAME;

    /**
     * This field corresponds to the database column APP.APP_ENABLED
     */
    private BigDecimal APP_ENABLED;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP.APP_ID
     *
     * @return the value of APP.APP_ID
     */
    public BigDecimal getAPP_ID() {
        return APP_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP.APP_ID
     *
     * @param APP_ID the value for APP.APP_ID
     */
    public void setAPP_ID(BigDecimal APP_ID) {
        this.APP_ID = APP_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP.BRIEF_NAME
     *
     * @return the value of APP.BRIEF_NAME
     */
    public String getBRIEF_NAME() {
        return BRIEF_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP.BRIEF_NAME
     *
     * @param BRIEF_NAME the value for APP.BRIEF_NAME
     */
    public void setBRIEF_NAME(String BRIEF_NAME) {
        this.BRIEF_NAME = BRIEF_NAME == null ? null : BRIEF_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP.LONG_NAME
     *
     * @return the value of APP.LONG_NAME
     */
    public String getLONG_NAME() {
        return LONG_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP.LONG_NAME
     *
     * @param LONG_NAME the value for APP.LONG_NAME
     */
    public void setLONG_NAME(String LONG_NAME) {
        this.LONG_NAME = LONG_NAME == null ? null : LONG_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP.APP_ENABLED
     *
     * @return the value of APP.APP_ENABLED
     */
    public BigDecimal getAPP_ENABLED() {
        return APP_ENABLED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP.APP_ENABLED
     *
     * @param APP_ENABLED the value for APP.APP_ENABLED
     */
    public void setAPP_ENABLED(BigDecimal APP_ENABLED) {
        this.APP_ENABLED = APP_ENABLED;
    }
}