package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;
import java.util.Date;

public class ARCHIVED_BUS_AREAVO extends BaseVO {
    /**
     * This field corresponds to the database column IMAL141_DEV_O18.ARCHIVED_BUS_AREA.BUS_AREA_CODE
     */
    private BigDecimal BUS_AREA_CODE;

    /**
     * This field corresponds to the database column IMAL141_DEV_O18.ARCHIVED_BUS_AREA.BUS_AREA_DESC
     */
    private String BUS_AREA_DESC;

    /**
     * This field corresponds to the database column IMAL141_DEV_O18.ARCHIVED_BUS_AREA.BUS_AREA_DESC_AR
     */
    private String BUS_AREA_DESC_AR;

    /**
     * This field corresponds to the database column IMAL141_DEV_O18.ARCHIVED_BUS_AREA.BUS_AREA_DESC_FR
     */
    private String BUS_AREA_DESC_FR;

    /**
     * This field corresponds to the database column IMAL141_DEV_O18.ARCHIVED_BUS_AREA.BUS_AREA_DESC_RU
     */
    private String BUS_AREA_DESC_RU;

    /**
     * This field corresponds to the database column IMAL141_DEV_O18.ARCHIVED_BUS_AREA.BUS_AREA_DESC_TK
     */
    private String BUS_AREA_DESC_TK;

    /**
     * This field corresponds to the database column IMAL141_DEV_O18.ARCHIVED_BUS_AREA.ONLINE_MONTHS
     */
    private BigDecimal ONLINE_MONTHS;

    /**
     * This field corresponds to the database column IMAL141_DEV_O18.ARCHIVED_BUS_AREA.ONLINE_PERIOD
     */
    private BigDecimal ONLINE_PERIOD;

    /**
     * This field corresponds to the database column IMAL141_DEV_O18.ARCHIVED_BUS_AREA.ONLINE_PERIOD_TYPE
     */
    private String ONLINE_PERIOD_TYPE;

    /**
     * This field corresponds to the database column IMAL141_DEV_O18.ARCHIVED_BUS_AREA.APPLICABLE_DATE
     */
    private Date APPLICABLE_DATE;

    /**
     * This field corresponds to the database column IMAL141_DEV_O18.ARCHIVED_BUS_AREA.STEP_FLAG
     */
    private BigDecimal STEP_FLAG;

    /**
     * This field corresponds to the database column IMAL141_DEV_O18.ARCHIVED_BUS_AREA.STATUS
     */
    private BigDecimal STATUS;

    /**
     * This field corresponds to the database column IMAL141_DEV_O18.ARCHIVED_BUS_AREA.BACKUP_DATE
     */
    private Date BACKUP_DATE;

    /**
     * This field corresponds to the database column IMAL141_DEV_O18.ARCHIVED_BUS_AREA.PURGE_DATE
     */
    private Date PURGE_DATE;

    /**
     * This field corresponds to the database column IMAL141_DEV_O18.ARCHIVED_BUS_AREA.ARCHIVE_DATE
     */
    private Date ARCHIVE_DATE;

    /**
     * This field corresponds to the database column IMAL141_DEV_O18.ARCHIVED_BUS_AREA.CLEAN_DATE
     */
    private Date CLEAN_DATE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMAL141_DEV_O18.ARCHIVED_BUS_AREA.BUS_AREA_CODE
     *
     * @return the value of IMAL141_DEV_O18.ARCHIVED_BUS_AREA.BUS_AREA_CODE
     */
    public BigDecimal getBUS_AREA_CODE() {
        return BUS_AREA_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMAL141_DEV_O18.ARCHIVED_BUS_AREA.BUS_AREA_CODE
     *
     * @param BUS_AREA_CODE the value for IMAL141_DEV_O18.ARCHIVED_BUS_AREA.BUS_AREA_CODE
     */
    public void setBUS_AREA_CODE(BigDecimal BUS_AREA_CODE) {
        this.BUS_AREA_CODE = BUS_AREA_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMAL141_DEV_O18.ARCHIVED_BUS_AREA.BUS_AREA_DESC
     *
     * @return the value of IMAL141_DEV_O18.ARCHIVED_BUS_AREA.BUS_AREA_DESC
     */
    public String getBUS_AREA_DESC() {
        return BUS_AREA_DESC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMAL141_DEV_O18.ARCHIVED_BUS_AREA.BUS_AREA_DESC
     *
     * @param BUS_AREA_DESC the value for IMAL141_DEV_O18.ARCHIVED_BUS_AREA.BUS_AREA_DESC
     */
    public void setBUS_AREA_DESC(String BUS_AREA_DESC) {
        this.BUS_AREA_DESC = BUS_AREA_DESC == null ? null : BUS_AREA_DESC.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMAL141_DEV_O18.ARCHIVED_BUS_AREA.BUS_AREA_DESC_AR
     *
     * @return the value of IMAL141_DEV_O18.ARCHIVED_BUS_AREA.BUS_AREA_DESC_AR
     */
    public String getBUS_AREA_DESC_AR() {
        return BUS_AREA_DESC_AR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMAL141_DEV_O18.ARCHIVED_BUS_AREA.BUS_AREA_DESC_AR
     *
     * @param BUS_AREA_DESC_AR the value for IMAL141_DEV_O18.ARCHIVED_BUS_AREA.BUS_AREA_DESC_AR
     */
    public void setBUS_AREA_DESC_AR(String BUS_AREA_DESC_AR) {
        this.BUS_AREA_DESC_AR = BUS_AREA_DESC_AR == null ? null : BUS_AREA_DESC_AR.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMAL141_DEV_O18.ARCHIVED_BUS_AREA.BUS_AREA_DESC_FR
     *
     * @return the value of IMAL141_DEV_O18.ARCHIVED_BUS_AREA.BUS_AREA_DESC_FR
     */
    public String getBUS_AREA_DESC_FR() {
        return BUS_AREA_DESC_FR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMAL141_DEV_O18.ARCHIVED_BUS_AREA.BUS_AREA_DESC_FR
     *
     * @param BUS_AREA_DESC_FR the value for IMAL141_DEV_O18.ARCHIVED_BUS_AREA.BUS_AREA_DESC_FR
     */
    public void setBUS_AREA_DESC_FR(String BUS_AREA_DESC_FR) {
        this.BUS_AREA_DESC_FR = BUS_AREA_DESC_FR == null ? null : BUS_AREA_DESC_FR.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMAL141_DEV_O18.ARCHIVED_BUS_AREA.BUS_AREA_DESC_RU
     *
     * @return the value of IMAL141_DEV_O18.ARCHIVED_BUS_AREA.BUS_AREA_DESC_RU
     */
    public String getBUS_AREA_DESC_RU() {
        return BUS_AREA_DESC_RU;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMAL141_DEV_O18.ARCHIVED_BUS_AREA.BUS_AREA_DESC_RU
     *
     * @param BUS_AREA_DESC_RU the value for IMAL141_DEV_O18.ARCHIVED_BUS_AREA.BUS_AREA_DESC_RU
     */
    public void setBUS_AREA_DESC_RU(String BUS_AREA_DESC_RU) {
        this.BUS_AREA_DESC_RU = BUS_AREA_DESC_RU == null ? null : BUS_AREA_DESC_RU.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMAL141_DEV_O18.ARCHIVED_BUS_AREA.BUS_AREA_DESC_TK
     *
     * @return the value of IMAL141_DEV_O18.ARCHIVED_BUS_AREA.BUS_AREA_DESC_TK
     */
    public String getBUS_AREA_DESC_TK() {
        return BUS_AREA_DESC_TK;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMAL141_DEV_O18.ARCHIVED_BUS_AREA.BUS_AREA_DESC_TK
     *
     * @param BUS_AREA_DESC_TK the value for IMAL141_DEV_O18.ARCHIVED_BUS_AREA.BUS_AREA_DESC_TK
     */
    public void setBUS_AREA_DESC_TK(String BUS_AREA_DESC_TK) {
        this.BUS_AREA_DESC_TK = BUS_AREA_DESC_TK == null ? null : BUS_AREA_DESC_TK.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMAL141_DEV_O18.ARCHIVED_BUS_AREA.ONLINE_MONTHS
     *
     * @return the value of IMAL141_DEV_O18.ARCHIVED_BUS_AREA.ONLINE_MONTHS
     */
    public BigDecimal getONLINE_MONTHS() {
        return ONLINE_MONTHS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMAL141_DEV_O18.ARCHIVED_BUS_AREA.ONLINE_MONTHS
     *
     * @param ONLINE_MONTHS the value for IMAL141_DEV_O18.ARCHIVED_BUS_AREA.ONLINE_MONTHS
     */
    public void setONLINE_MONTHS(BigDecimal ONLINE_MONTHS) {
        this.ONLINE_MONTHS = ONLINE_MONTHS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMAL141_DEV_O18.ARCHIVED_BUS_AREA.ONLINE_PERIOD
     *
     * @return the value of IMAL141_DEV_O18.ARCHIVED_BUS_AREA.ONLINE_PERIOD
     */
    public BigDecimal getONLINE_PERIOD() {
        return ONLINE_PERIOD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMAL141_DEV_O18.ARCHIVED_BUS_AREA.ONLINE_PERIOD
     *
     * @param ONLINE_PERIOD the value for IMAL141_DEV_O18.ARCHIVED_BUS_AREA.ONLINE_PERIOD
     */
    public void setONLINE_PERIOD(BigDecimal ONLINE_PERIOD) {
        this.ONLINE_PERIOD = ONLINE_PERIOD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMAL141_DEV_O18.ARCHIVED_BUS_AREA.ONLINE_PERIOD_TYPE
     *
     * @return the value of IMAL141_DEV_O18.ARCHIVED_BUS_AREA.ONLINE_PERIOD_TYPE
     */
    public String getONLINE_PERIOD_TYPE() {
        return ONLINE_PERIOD_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMAL141_DEV_O18.ARCHIVED_BUS_AREA.ONLINE_PERIOD_TYPE
     *
     * @param ONLINE_PERIOD_TYPE the value for IMAL141_DEV_O18.ARCHIVED_BUS_AREA.ONLINE_PERIOD_TYPE
     */
    public void setONLINE_PERIOD_TYPE(String ONLINE_PERIOD_TYPE) {
        this.ONLINE_PERIOD_TYPE = ONLINE_PERIOD_TYPE == null ? null : ONLINE_PERIOD_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMAL141_DEV_O18.ARCHIVED_BUS_AREA.APPLICABLE_DATE
     *
     * @return the value of IMAL141_DEV_O18.ARCHIVED_BUS_AREA.APPLICABLE_DATE
     */
    public Date getAPPLICABLE_DATE() {
        return APPLICABLE_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMAL141_DEV_O18.ARCHIVED_BUS_AREA.APPLICABLE_DATE
     *
     * @param APPLICABLE_DATE the value for IMAL141_DEV_O18.ARCHIVED_BUS_AREA.APPLICABLE_DATE
     */
    public void setAPPLICABLE_DATE(Date APPLICABLE_DATE) {
        this.APPLICABLE_DATE = APPLICABLE_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMAL141_DEV_O18.ARCHIVED_BUS_AREA.STEP_FLAG
     *
     * @return the value of IMAL141_DEV_O18.ARCHIVED_BUS_AREA.STEP_FLAG
     */
    public BigDecimal getSTEP_FLAG() {
        return STEP_FLAG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMAL141_DEV_O18.ARCHIVED_BUS_AREA.STEP_FLAG
     *
     * @param STEP_FLAG the value for IMAL141_DEV_O18.ARCHIVED_BUS_AREA.STEP_FLAG
     */
    public void setSTEP_FLAG(BigDecimal STEP_FLAG) {
        this.STEP_FLAG = STEP_FLAG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMAL141_DEV_O18.ARCHIVED_BUS_AREA.STATUS
     *
     * @return the value of IMAL141_DEV_O18.ARCHIVED_BUS_AREA.STATUS
     */
    public BigDecimal getSTATUS() {
        return STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMAL141_DEV_O18.ARCHIVED_BUS_AREA.STATUS
     *
     * @param STATUS the value for IMAL141_DEV_O18.ARCHIVED_BUS_AREA.STATUS
     */
    public void setSTATUS(BigDecimal STATUS) {
        this.STATUS = STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMAL141_DEV_O18.ARCHIVED_BUS_AREA.BACKUP_DATE
     *
     * @return the value of IMAL141_DEV_O18.ARCHIVED_BUS_AREA.BACKUP_DATE
     */
    public Date getBACKUP_DATE() {
        return BACKUP_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMAL141_DEV_O18.ARCHIVED_BUS_AREA.BACKUP_DATE
     *
     * @param BACKUP_DATE the value for IMAL141_DEV_O18.ARCHIVED_BUS_AREA.BACKUP_DATE
     */
    public void setBACKUP_DATE(Date BACKUP_DATE) {
        this.BACKUP_DATE = BACKUP_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMAL141_DEV_O18.ARCHIVED_BUS_AREA.PURGE_DATE
     *
     * @return the value of IMAL141_DEV_O18.ARCHIVED_BUS_AREA.PURGE_DATE
     */
    public Date getPURGE_DATE() {
        return PURGE_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMAL141_DEV_O18.ARCHIVED_BUS_AREA.PURGE_DATE
     *
     * @param PURGE_DATE the value for IMAL141_DEV_O18.ARCHIVED_BUS_AREA.PURGE_DATE
     */
    public void setPURGE_DATE(Date PURGE_DATE) {
        this.PURGE_DATE = PURGE_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMAL141_DEV_O18.ARCHIVED_BUS_AREA.ARCHIVE_DATE
     *
     * @return the value of IMAL141_DEV_O18.ARCHIVED_BUS_AREA.ARCHIVE_DATE
     */
    public Date getARCHIVE_DATE() {
        return ARCHIVE_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMAL141_DEV_O18.ARCHIVED_BUS_AREA.ARCHIVE_DATE
     *
     * @param ARCHIVE_DATE the value for IMAL141_DEV_O18.ARCHIVED_BUS_AREA.ARCHIVE_DATE
     */
    public void setARCHIVE_DATE(Date ARCHIVE_DATE) {
        this.ARCHIVE_DATE = ARCHIVE_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMAL141_DEV_O18.ARCHIVED_BUS_AREA.CLEAN_DATE
     *
     * @return the value of IMAL141_DEV_O18.ARCHIVED_BUS_AREA.CLEAN_DATE
     */
    public Date getCLEAN_DATE() {
        return CLEAN_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMAL141_DEV_O18.ARCHIVED_BUS_AREA.CLEAN_DATE
     *
     * @param CLEAN_DATE the value for IMAL141_DEV_O18.ARCHIVED_BUS_AREA.CLEAN_DATE
     */
    public void setCLEAN_DATE(Date CLEAN_DATE) {
        this.CLEAN_DATE = CLEAN_DATE;
    }
}