package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class BRANCH_SESSIONVO extends BRANCH_SESSIONVOKey {
    /**
     * This field corresponds to the database column BRANCH_SESSION.DATE_CLOSED
     */
    private Date DATE_CLOSED;

    /**
     * This field corresponds to the database column BRANCH_SESSION.SESSION_COUNTER
     */
    private BigDecimal SESSION_COUNTER;

    /**
     * This field corresponds to the database column BRANCH_SESSION.OPENED_BY
     */
    private String OPENED_BY;

    /**
     * This field corresponds to the database column BRANCH_SESSION.CLOSED_BY
     */
    private String CLOSED_BY;

    /**
     * This field corresponds to the database column BRANCH_SESSION.IS_BRANCH
     */
    private String IS_BRANCH;

    /**
     * This field corresponds to the database column BRANCH_SESSION.REOPENED_BY
     */
    private String REOPENED_BY;

    /**
     * This field corresponds to the database column BRANCH_SESSION.DATE_REOPENED
     */
    private Date DATE_REOPENED;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BRANCH_SESSION.DATE_CLOSED
     *
     * @return the value of BRANCH_SESSION.DATE_CLOSED
     */
    public Date getDATE_CLOSED() {
        return DATE_CLOSED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BRANCH_SESSION.DATE_CLOSED
     *
     * @param DATE_CLOSED the value for BRANCH_SESSION.DATE_CLOSED
     */
    public void setDATE_CLOSED(Date DATE_CLOSED) {
        this.DATE_CLOSED = DATE_CLOSED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BRANCH_SESSION.SESSION_COUNTER
     *
     * @return the value of BRANCH_SESSION.SESSION_COUNTER
     */
    public BigDecimal getSESSION_COUNTER() {
        return SESSION_COUNTER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BRANCH_SESSION.SESSION_COUNTER
     *
     * @param SESSION_COUNTER the value for BRANCH_SESSION.SESSION_COUNTER
     */
    public void setSESSION_COUNTER(BigDecimal SESSION_COUNTER) {
        this.SESSION_COUNTER = SESSION_COUNTER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BRANCH_SESSION.OPENED_BY
     *
     * @return the value of BRANCH_SESSION.OPENED_BY
     */
    public String getOPENED_BY() {
        return OPENED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BRANCH_SESSION.OPENED_BY
     *
     * @param OPENED_BY the value for BRANCH_SESSION.OPENED_BY
     */
    public void setOPENED_BY(String OPENED_BY) {
        this.OPENED_BY = OPENED_BY == null ? null : OPENED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BRANCH_SESSION.CLOSED_BY
     *
     * @return the value of BRANCH_SESSION.CLOSED_BY
     */
    public String getCLOSED_BY() {
        return CLOSED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BRANCH_SESSION.CLOSED_BY
     *
     * @param CLOSED_BY the value for BRANCH_SESSION.CLOSED_BY
     */
    public void setCLOSED_BY(String CLOSED_BY) {
        this.CLOSED_BY = CLOSED_BY == null ? null : CLOSED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BRANCH_SESSION.IS_BRANCH
     *
     * @return the value of BRANCH_SESSION.IS_BRANCH
     */
    public String getIS_BRANCH() {
        return IS_BRANCH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BRANCH_SESSION.IS_BRANCH
     *
     * @param IS_BRANCH the value for BRANCH_SESSION.IS_BRANCH
     */
    public void setIS_BRANCH(String IS_BRANCH) {
        this.IS_BRANCH = IS_BRANCH == null ? null : IS_BRANCH.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BRANCH_SESSION.REOPENED_BY
     *
     * @return the value of BRANCH_SESSION.REOPENED_BY
     */
    public String getREOPENED_BY() {
        return REOPENED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BRANCH_SESSION.REOPENED_BY
     *
     * @param REOPENED_BY the value for BRANCH_SESSION.REOPENED_BY
     */
    public void setREOPENED_BY(String REOPENED_BY) {
        this.REOPENED_BY = REOPENED_BY == null ? null : REOPENED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BRANCH_SESSION.DATE_REOPENED
     *
     * @return the value of BRANCH_SESSION.DATE_REOPENED
     */
    public Date getDATE_REOPENED() {
        return DATE_REOPENED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BRANCH_SESSION.DATE_REOPENED
     *
     * @param DATE_REOPENED the value for BRANCH_SESSION.DATE_REOPENED
     */
    public void setDATE_REOPENED(Date DATE_REOPENED) {
        this.DATE_REOPENED = DATE_REOPENED;
    }
}