package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class BRANCH_HOLIDAYVOKey extends BaseVO {
    /**
     * This field corresponds to the database column BRANCH_HOLIDAY.BRANCH_CODE
     */
    private BigDecimal BRANCH_CODE;

    /**
     * This field corresponds to the database column BRANCH_HOLIDAY.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column BRANCH_HOLIDAY.DD_HOL
     */
    private BigDecimal DD_HOL;

    /**
     * This field corresponds to the database column BRANCH_HOLIDAY.MM_HOL
     */
    private BigDecimal MM_HOL;

    /**
     * This field corresponds to the database column BRANCH_HOLIDAY.YYYY_HOL
     */
    private BigDecimal YYYY_HOL;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BRANCH_HOLIDAY.BRANCH_CODE
     *
     * @return the value of BRANCH_HOLIDAY.BRANCH_CODE
     */
    public BigDecimal getBRANCH_CODE() {
        return BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BRANCH_HOLIDAY.BRANCH_CODE
     *
     * @param BRANCH_CODE the value for BRANCH_HOLIDAY.BRANCH_CODE
     */
    public void setBRANCH_CODE(BigDecimal BRANCH_CODE) {
        this.BRANCH_CODE = BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BRANCH_HOLIDAY.COMP_CODE
     *
     * @return the value of BRANCH_HOLIDAY.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BRANCH_HOLIDAY.COMP_CODE
     *
     * @param COMP_CODE the value for BRANCH_HOLIDAY.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BRANCH_HOLIDAY.DD_HOL
     *
     * @return the value of BRANCH_HOLIDAY.DD_HOL
     */
    public BigDecimal getDD_HOL() {
        return DD_HOL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BRANCH_HOLIDAY.DD_HOL
     *
     * @param DD_HOL the value for BRANCH_HOLIDAY.DD_HOL
     */
    public void setDD_HOL(BigDecimal DD_HOL) {
        this.DD_HOL = DD_HOL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BRANCH_HOLIDAY.MM_HOL
     *
     * @return the value of BRANCH_HOLIDAY.MM_HOL
     */
    public BigDecimal getMM_HOL() {
        return MM_HOL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BRANCH_HOLIDAY.MM_HOL
     *
     * @param MM_HOL the value for BRANCH_HOLIDAY.MM_HOL
     */
    public void setMM_HOL(BigDecimal MM_HOL) {
        this.MM_HOL = MM_HOL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BRANCH_HOLIDAY.YYYY_HOL
     *
     * @return the value of BRANCH_HOLIDAY.YYYY_HOL
     */
    public BigDecimal getYYYY_HOL() {
        return YYYY_HOL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BRANCH_HOLIDAY.YYYY_HOL
     *
     * @param YYYY_HOL the value for BRANCH_HOLIDAY.YYYY_HOL
     */
    public void setYYYY_HOL(BigDecimal YYYY_HOL) {
        this.YYYY_HOL = YYYY_HOL;
    }
}