package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class CITIESVOKey extends BaseVO {
    /**
     * This field corresponds to the database column CITIES.CITY_CODE
     */
    private BigDecimal CITY_CODE;

    /**
     * This field corresponds to the database column CITIES.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column CITIES.COUNTRY_CODE
     */
    private BigDecimal COUNTRY_CODE;

    /**
     * This field corresponds to the database column CITIES.REGION_CODE
     */
    private BigDecimal REGION_CODE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CITIES.CITY_CODE
     *
     * @return the value of CITIES.CITY_CODE
     */
    public BigDecimal getCITY_CODE() {
        return CITY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CITIES.CITY_CODE
     *
     * @param CITY_CODE the value for CITIES.CITY_CODE
     */
    public void setCITY_CODE(BigDecimal CITY_CODE) {
        this.CITY_CODE = CITY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CITIES.COMP_CODE
     *
     * @return the value of CITIES.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CITIES.COMP_CODE
     *
     * @param COMP_CODE the value for CITIES.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CITIES.COUNTRY_CODE
     *
     * @return the value of CITIES.COUNTRY_CODE
     */
    public BigDecimal getCOUNTRY_CODE() {
        return COUNTRY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CITIES.COUNTRY_CODE
     *
     * @param COUNTRY_CODE the value for CITIES.COUNTRY_CODE
     */
    public void setCOUNTRY_CODE(BigDecimal COUNTRY_CODE) {
        this.COUNTRY_CODE = COUNTRY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CITIES.REGION_CODE
     *
     * @return the value of CITIES.REGION_CODE
     */
    public BigDecimal getREGION_CODE() {
        return REGION_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CITIES.REGION_CODE
     *
     * @param REGION_CODE the value for CITIES.REGION_CODE
     */
    public void setREGION_CODE(BigDecimal REGION_CODE) {
        this.REGION_CODE = REGION_CODE;
    }
}