package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class CIVIL_CODESVOKey extends BaseVO {
    /**
     * This field corresponds to the database column CIVIL_CODES.CIVIL_CODE
     */
    private BigDecimal CIVIL_CODE;

    /**
     * This field corresponds to the database column CIVIL_CODES.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIVIL_CODES.CIVIL_CODE
     *
     * @return the value of CIVIL_CODES.CIVIL_CODE
     */
    public BigDecimal getCIVIL_CODE() {
        return CIVIL_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIVIL_CODES.CIVIL_CODE
     *
     * @param CIVIL_CODE the value for CIVIL_CODES.CIVIL_CODE
     */
    public void setCIVIL_CODE(BigDecimal CIVIL_CODE) {
        this.CIVIL_CODE = CIVIL_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CIVIL_CODES.COMP_CODE
     *
     * @return the value of CIVIL_CODES.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CIVIL_CODES.COMP_CODE
     *
     * @param COMP_CODE the value for CIVIL_CODES.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }
}