package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;
import java.util.Date;

public class COMMON_PWS_MAPPINGVO extends BaseVO {
    /**
     * This field corresponds to the database column COMMON_PWS_MAPPING.MAPPING_ID
     */
    private BigDecimal MAPPING_ID;

    /**
     * This field corresponds to the database column COMMON_PWS_MAPPING.WS_NAME
     */
    private String WS_NAME;

    /**
     * This field corresponds to the database column COMMON_PWS_MAPPING.OPER_NAME
     */
    private String OPER_NAME;

    /**
     * This field corresponds to the database column COMMON_PWS_MAPPING.CREATED_BY
     */
    private String CREATED_BY;

    /**
     * This field corresponds to the database column COMMON_PWS_MAPPING.CREATED_DATE
     */
    private Date CREATED_DATE;

    /**
     * This field corresponds to the database column COMMON_PWS_MAPPING.MODIFIED_BY
     */
    private String MODIFIED_BY;

    /**
     * This field corresponds to the database column COMMON_PWS_MAPPING.MODIFIED_DATE
     */
    private Date MODIFIED_DATE;

    /**
     * This field corresponds to the database column COMMON_PWS_MAPPING.API_CODE
     */
    private BigDecimal API_CODE;

    /**
     * This field corresponds to the database column COMMON_PWS_MAPPING.SERVICE_APP_NAME
     */
    private String SERVICE_APP_NAME;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMMON_PWS_MAPPING.MAPPING_ID
     *
     * @return the value of COMMON_PWS_MAPPING.MAPPING_ID
     */
    public BigDecimal getMAPPING_ID() {
        return MAPPING_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMMON_PWS_MAPPING.MAPPING_ID
     *
     * @param MAPPING_ID the value for COMMON_PWS_MAPPING.MAPPING_ID
     */
    public void setMAPPING_ID(BigDecimal MAPPING_ID) {
        this.MAPPING_ID = MAPPING_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMMON_PWS_MAPPING.WS_NAME
     *
     * @return the value of COMMON_PWS_MAPPING.WS_NAME
     */
    public String getWS_NAME() {
        return WS_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMMON_PWS_MAPPING.WS_NAME
     *
     * @param WS_NAME the value for COMMON_PWS_MAPPING.WS_NAME
     */
    public void setWS_NAME(String WS_NAME) {
        this.WS_NAME = WS_NAME == null ? null : WS_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMMON_PWS_MAPPING.OPER_NAME
     *
     * @return the value of COMMON_PWS_MAPPING.OPER_NAME
     */
    public String getOPER_NAME() {
        return OPER_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMMON_PWS_MAPPING.OPER_NAME
     *
     * @param OPER_NAME the value for COMMON_PWS_MAPPING.OPER_NAME
     */
    public void setOPER_NAME(String OPER_NAME) {
        this.OPER_NAME = OPER_NAME == null ? null : OPER_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMMON_PWS_MAPPING.CREATED_BY
     *
     * @return the value of COMMON_PWS_MAPPING.CREATED_BY
     */
    public String getCREATED_BY() {
        return CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMMON_PWS_MAPPING.CREATED_BY
     *
     * @param CREATED_BY the value for COMMON_PWS_MAPPING.CREATED_BY
     */
    public void setCREATED_BY(String CREATED_BY) {
        this.CREATED_BY = CREATED_BY == null ? null : CREATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMMON_PWS_MAPPING.CREATED_DATE
     *
     * @return the value of COMMON_PWS_MAPPING.CREATED_DATE
     */
    public Date getCREATED_DATE() {
        return CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMMON_PWS_MAPPING.CREATED_DATE
     *
     * @param CREATED_DATE the value for COMMON_PWS_MAPPING.CREATED_DATE
     */
    public void setCREATED_DATE(Date CREATED_DATE) {
        this.CREATED_DATE = CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMMON_PWS_MAPPING.MODIFIED_BY
     *
     * @return the value of COMMON_PWS_MAPPING.MODIFIED_BY
     */
    public String getMODIFIED_BY() {
        return MODIFIED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMMON_PWS_MAPPING.MODIFIED_BY
     *
     * @param MODIFIED_BY the value for COMMON_PWS_MAPPING.MODIFIED_BY
     */
    public void setMODIFIED_BY(String MODIFIED_BY) {
        this.MODIFIED_BY = MODIFIED_BY == null ? null : MODIFIED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMMON_PWS_MAPPING.MODIFIED_DATE
     *
     * @return the value of COMMON_PWS_MAPPING.MODIFIED_DATE
     */
    public Date getMODIFIED_DATE() {
        return MODIFIED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMMON_PWS_MAPPING.MODIFIED_DATE
     *
     * @param MODIFIED_DATE the value for COMMON_PWS_MAPPING.MODIFIED_DATE
     */
    public void setMODIFIED_DATE(Date MODIFIED_DATE) {
        this.MODIFIED_DATE = MODIFIED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMMON_PWS_MAPPING.API_CODE
     *
     * @return the value of COMMON_PWS_MAPPING.API_CODE
     */
    public BigDecimal getAPI_CODE() {
        return API_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMMON_PWS_MAPPING.API_CODE
     *
     * @param API_CODE the value for COMMON_PWS_MAPPING.API_CODE
     */
    public void setAPI_CODE(BigDecimal API_CODE) {
        this.API_CODE = API_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMMON_PWS_MAPPING.SERVICE_APP_NAME
     *
     * @return the value of COMMON_PWS_MAPPING.SERVICE_APP_NAME
     */
    public String getSERVICE_APP_NAME() {
        return SERVICE_APP_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMMON_PWS_MAPPING.SERVICE_APP_NAME
     *
     * @param SERVICE_APP_NAME the value for COMMON_PWS_MAPPING.SERVICE_APP_NAME
     */
    public void setSERVICE_APP_NAME(String SERVICE_APP_NAME) {
        this.SERVICE_APP_NAME = SERVICE_APP_NAME == null ? null : SERVICE_APP_NAME.trim();
    }
}