package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class COMMON_PWS_MAPPING_DETAILSVOKey extends BaseVO {
    /**
     * This field corresponds to the database column COMMON_PWS_MAPPING_DETAILS.MAPPING_DET_ID
     */
    private BigDecimal MAPPING_DET_ID;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMMON_PWS_MAPPING_DETAILS.MAPPING_DET_ID
     *
     * @return the value of COMMON_PWS_MAPPING_DETAILS.MAPPING_DET_ID
     */
    public BigDecimal getMAPPING_DET_ID() {
        return MAPPING_DET_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMMON_PWS_MAPPING_DETAILS.MAPPING_DET_ID
     *
     * @param MAPPING_DET_ID the value for COMMON_PWS_MAPPING_DETAILS.MAPPING_DET_ID
     */
    public void setMAPPING_DET_ID(BigDecimal MAPPING_DET_ID) {
        this.MAPPING_DET_ID = MAPPING_DET_ID;
    }
}