package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class COMMON_GLOB_ACT_ID_AFTER_EXECVO extends BaseVO {
    /**
     * This field corresponds to the database column COMMON_GLOB_ACT_ID_AFTER_EXEC.APP_NAME
     */
    private String APP_NAME;

    /**
     * This field corresponds to the database column COMMON_GLOB_ACT_ID_AFTER_EXEC.GLOB_ACT_BUS
     */
    private String GLOB_ACT_BUS;

    /**
     * This field corresponds to the database column COMMON_GLOB_ACT_ID_AFTER_EXEC.GLOB_ACT_ID
     */
    private BigDecimal GLOB_ACT_ID;

    /**
     * This field corresponds to the database column COMMON_GLOB_ACT_ID_AFTER_EXEC.IV_CRUD
     */
    private String IV_CRUD;

    /**
     * This field corresponds to the database column COMMON_GLOB_ACT_ID_AFTER_EXEC.SCREEN_REF
     */
    private String SCREEN_REF;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMMON_GLOB_ACT_ID_AFTER_EXEC.APP_NAME
     *
     * @return the value of COMMON_GLOB_ACT_ID_AFTER_EXEC.APP_NAME
     */
    public String getAPP_NAME() {
        return APP_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMMON_GLOB_ACT_ID_AFTER_EXEC.APP_NAME
     *
     * @param APP_NAME the value for COMMON_GLOB_ACT_ID_AFTER_EXEC.APP_NAME
     */
    public void setAPP_NAME(String APP_NAME) {
        this.APP_NAME = APP_NAME == null ? null : APP_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMMON_GLOB_ACT_ID_AFTER_EXEC.GLOB_ACT_BUS
     *
     * @return the value of COMMON_GLOB_ACT_ID_AFTER_EXEC.GLOB_ACT_BUS
     */
    public String getGLOB_ACT_BUS() {
        return GLOB_ACT_BUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMMON_GLOB_ACT_ID_AFTER_EXEC.GLOB_ACT_BUS
     *
     * @param GLOB_ACT_BUS the value for COMMON_GLOB_ACT_ID_AFTER_EXEC.GLOB_ACT_BUS
     */
    public void setGLOB_ACT_BUS(String GLOB_ACT_BUS) {
        this.GLOB_ACT_BUS = GLOB_ACT_BUS == null ? null : GLOB_ACT_BUS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMMON_GLOB_ACT_ID_AFTER_EXEC.GLOB_ACT_ID
     *
     * @return the value of COMMON_GLOB_ACT_ID_AFTER_EXEC.GLOB_ACT_ID
     */
    public BigDecimal getGLOB_ACT_ID() {
        return GLOB_ACT_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMMON_GLOB_ACT_ID_AFTER_EXEC.GLOB_ACT_ID
     *
     * @param GLOB_ACT_ID the value for COMMON_GLOB_ACT_ID_AFTER_EXEC.GLOB_ACT_ID
     */
    public void setGLOB_ACT_ID(BigDecimal GLOB_ACT_ID) {
        this.GLOB_ACT_ID = GLOB_ACT_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMMON_GLOB_ACT_ID_AFTER_EXEC.IV_CRUD
     *
     * @return the value of COMMON_GLOB_ACT_ID_AFTER_EXEC.IV_CRUD
     */
    public String getIV_CRUD() {
        return IV_CRUD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMMON_GLOB_ACT_ID_AFTER_EXEC.IV_CRUD
     *
     * @param IV_CRUD the value for COMMON_GLOB_ACT_ID_AFTER_EXEC.IV_CRUD
     */
    public void setIV_CRUD(String IV_CRUD) {
        this.IV_CRUD = IV_CRUD == null ? null : IV_CRUD.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMMON_GLOB_ACT_ID_AFTER_EXEC.SCREEN_REF
     *
     * @return the value of COMMON_GLOB_ACT_ID_AFTER_EXEC.SCREEN_REF
     */
    public String getSCREEN_REF() {
        return SCREEN_REF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMMON_GLOB_ACT_ID_AFTER_EXEC.SCREEN_REF
     *
     * @param SCREEN_REF the value for COMMON_GLOB_ACT_ID_AFTER_EXEC.SCREEN_REF
     */
    public void setSCREEN_REF(String SCREEN_REF) {
        this.SCREEN_REF = SCREEN_REF == null ? null : SCREEN_REF.trim();
    }
}