package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;
import java.util.Date;

public class COUNTRIES_LIMIT_CIFVO extends BaseVO {
    /**
     * This field corresponds to the database column COUNTRIES_LIMIT_CIF.CIF
     */
    private BigDecimal CIF;

    /**
     * This field corresponds to the database column COUNTRIES_LIMIT_CIF.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column COUNTRIES_LIMIT_CIF.COUNTRY_CODE
     */
    private BigDecimal COUNTRY_CODE;

    /**
     * This field corresponds to the database column COUNTRIES_LIMIT_CIF.LIMIT_CURRENCY
     */
    private BigDecimal LIMIT_CURRENCY;

    /**
     * This field corresponds to the database column COUNTRIES_LIMIT_CIF.LIMIT_AMOUNT_FC
     */
    private BigDecimal LIMIT_AMOUNT_FC;

    /**
     * This field corresponds to the database column COUNTRIES_LIMIT_CIF.CHK_ENABLED
     */
    private String CHK_ENABLED;

    /**
     * This field corresponds to the database column COUNTRIES_LIMIT_CIF.STATUS
     */
    private String STATUS;

    /**
     * This field corresponds to the database column COUNTRIES_LIMIT_CIF.DATE_CREATED
     */
    private Date DATE_CREATED;

    /**
     * This field corresponds to the database column COUNTRIES_LIMIT_CIF.CREATED_BY
     */
    private String CREATED_BY;

    /**
     * This field corresponds to the database column COUNTRIES_LIMIT_CIF.DATE_MODIFIED
     */
    private Date DATE_MODIFIED;

    /**
     * This field corresponds to the database column COUNTRIES_LIMIT_CIF.MODIFIED_BY
     */
    private String MODIFIED_BY;

    /**
     * This field corresponds to the database column COUNTRIES_LIMIT_CIF.DATE_APPROVED
     */
    private Date DATE_APPROVED;

    /**
     * This field corresponds to the database column COUNTRIES_LIMIT_CIF.APPROVED_BY
     */
    private String APPROVED_BY;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUNTRIES_LIMIT_CIF.CIF
     *
     * @return the value of COUNTRIES_LIMIT_CIF.CIF
     */
    public BigDecimal getCIF() {
        return CIF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUNTRIES_LIMIT_CIF.CIF
     *
     * @param CIF the value for COUNTRIES_LIMIT_CIF.CIF
     */
    public void setCIF(BigDecimal CIF) {
        this.CIF = CIF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUNTRIES_LIMIT_CIF.COMP_CODE
     *
     * @return the value of COUNTRIES_LIMIT_CIF.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUNTRIES_LIMIT_CIF.COMP_CODE
     *
     * @param COMP_CODE the value for COUNTRIES_LIMIT_CIF.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUNTRIES_LIMIT_CIF.COUNTRY_CODE
     *
     * @return the value of COUNTRIES_LIMIT_CIF.COUNTRY_CODE
     */
    public BigDecimal getCOUNTRY_CODE() {
        return COUNTRY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUNTRIES_LIMIT_CIF.COUNTRY_CODE
     *
     * @param COUNTRY_CODE the value for COUNTRIES_LIMIT_CIF.COUNTRY_CODE
     */
    public void setCOUNTRY_CODE(BigDecimal COUNTRY_CODE) {
        this.COUNTRY_CODE = COUNTRY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUNTRIES_LIMIT_CIF.LIMIT_CURRENCY
     *
     * @return the value of COUNTRIES_LIMIT_CIF.LIMIT_CURRENCY
     */
    public BigDecimal getLIMIT_CURRENCY() {
        return LIMIT_CURRENCY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUNTRIES_LIMIT_CIF.LIMIT_CURRENCY
     *
     * @param LIMIT_CURRENCY the value for COUNTRIES_LIMIT_CIF.LIMIT_CURRENCY
     */
    public void setLIMIT_CURRENCY(BigDecimal LIMIT_CURRENCY) {
        this.LIMIT_CURRENCY = LIMIT_CURRENCY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUNTRIES_LIMIT_CIF.LIMIT_AMOUNT_FC
     *
     * @return the value of COUNTRIES_LIMIT_CIF.LIMIT_AMOUNT_FC
     */
    public BigDecimal getLIMIT_AMOUNT_FC() {
        return LIMIT_AMOUNT_FC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUNTRIES_LIMIT_CIF.LIMIT_AMOUNT_FC
     *
     * @param LIMIT_AMOUNT_FC the value for COUNTRIES_LIMIT_CIF.LIMIT_AMOUNT_FC
     */
    public void setLIMIT_AMOUNT_FC(BigDecimal LIMIT_AMOUNT_FC) {
        this.LIMIT_AMOUNT_FC = LIMIT_AMOUNT_FC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUNTRIES_LIMIT_CIF.CHK_ENABLED
     *
     * @return the value of COUNTRIES_LIMIT_CIF.CHK_ENABLED
     */
    public String getCHK_ENABLED() {
        return CHK_ENABLED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUNTRIES_LIMIT_CIF.CHK_ENABLED
     *
     * @param CHK_ENABLED the value for COUNTRIES_LIMIT_CIF.CHK_ENABLED
     */
    public void setCHK_ENABLED(String CHK_ENABLED) {
        this.CHK_ENABLED = CHK_ENABLED == null ? null : CHK_ENABLED.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUNTRIES_LIMIT_CIF.STATUS
     *
     * @return the value of COUNTRIES_LIMIT_CIF.STATUS
     */
    public String getSTATUS() {
        return STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUNTRIES_LIMIT_CIF.STATUS
     *
     * @param STATUS the value for COUNTRIES_LIMIT_CIF.STATUS
     */
    public void setSTATUS(String STATUS) {
        this.STATUS = STATUS == null ? null : STATUS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUNTRIES_LIMIT_CIF.DATE_CREATED
     *
     * @return the value of COUNTRIES_LIMIT_CIF.DATE_CREATED
     */
    public Date getDATE_CREATED() {
        return DATE_CREATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUNTRIES_LIMIT_CIF.DATE_CREATED
     *
     * @param DATE_CREATED the value for COUNTRIES_LIMIT_CIF.DATE_CREATED
     */
    public void setDATE_CREATED(Date DATE_CREATED) {
        this.DATE_CREATED = DATE_CREATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUNTRIES_LIMIT_CIF.CREATED_BY
     *
     * @return the value of COUNTRIES_LIMIT_CIF.CREATED_BY
     */
    public String getCREATED_BY() {
        return CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUNTRIES_LIMIT_CIF.CREATED_BY
     *
     * @param CREATED_BY the value for COUNTRIES_LIMIT_CIF.CREATED_BY
     */
    public void setCREATED_BY(String CREATED_BY) {
        this.CREATED_BY = CREATED_BY == null ? null : CREATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUNTRIES_LIMIT_CIF.DATE_MODIFIED
     *
     * @return the value of COUNTRIES_LIMIT_CIF.DATE_MODIFIED
     */
    public Date getDATE_MODIFIED() {
        return DATE_MODIFIED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUNTRIES_LIMIT_CIF.DATE_MODIFIED
     *
     * @param DATE_MODIFIED the value for COUNTRIES_LIMIT_CIF.DATE_MODIFIED
     */
    public void setDATE_MODIFIED(Date DATE_MODIFIED) {
        this.DATE_MODIFIED = DATE_MODIFIED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUNTRIES_LIMIT_CIF.MODIFIED_BY
     *
     * @return the value of COUNTRIES_LIMIT_CIF.MODIFIED_BY
     */
    public String getMODIFIED_BY() {
        return MODIFIED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUNTRIES_LIMIT_CIF.MODIFIED_BY
     *
     * @param MODIFIED_BY the value for COUNTRIES_LIMIT_CIF.MODIFIED_BY
     */
    public void setMODIFIED_BY(String MODIFIED_BY) {
        this.MODIFIED_BY = MODIFIED_BY == null ? null : MODIFIED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUNTRIES_LIMIT_CIF.DATE_APPROVED
     *
     * @return the value of COUNTRIES_LIMIT_CIF.DATE_APPROVED
     */
    public Date getDATE_APPROVED() {
        return DATE_APPROVED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUNTRIES_LIMIT_CIF.DATE_APPROVED
     *
     * @param DATE_APPROVED the value for COUNTRIES_LIMIT_CIF.DATE_APPROVED
     */
    public void setDATE_APPROVED(Date DATE_APPROVED) {
        this.DATE_APPROVED = DATE_APPROVED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUNTRIES_LIMIT_CIF.APPROVED_BY
     *
     * @return the value of COUNTRIES_LIMIT_CIF.APPROVED_BY
     */
    public String getAPPROVED_BY() {
        return APPROVED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUNTRIES_LIMIT_CIF.APPROVED_BY
     *
     * @param APPROVED_BY the value for COUNTRIES_LIMIT_CIF.APPROVED_BY
     */
    public void setAPPROVED_BY(String APPROVED_BY) {
        this.APPROVED_BY = APPROVED_BY == null ? null : APPROVED_BY.trim();
    }
}