package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class COUNTRIES_REGIONVOKey extends BaseVO {
    /**
     * This field corresponds to the database column COUNTRIES_REGION.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column COUNTRIES_REGION.COUNTRY_CODE
     */
    private BigDecimal COUNTRY_CODE;

    /**
     * This field corresponds to the database column COUNTRIES_REGION.REGION_CODE
     */
    private BigDecimal REGION_CODE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUNTRIES_REGION.COMP_CODE
     *
     * @return the value of COUNTRIES_REGION.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUNTRIES_REGION.COMP_CODE
     *
     * @param COMP_CODE the value for COUNTRIES_REGION.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUNTRIES_REGION.COUNTRY_CODE
     *
     * @return the value of COUNTRIES_REGION.COUNTRY_CODE
     */
    public BigDecimal getCOUNTRY_CODE() {
        return COUNTRY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUNTRIES_REGION.COUNTRY_CODE
     *
     * @param COUNTRY_CODE the value for COUNTRIES_REGION.COUNTRY_CODE
     */
    public void setCOUNTRY_CODE(BigDecimal COUNTRY_CODE) {
        this.COUNTRY_CODE = COUNTRY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUNTRIES_REGION.REGION_CODE
     *
     * @return the value of COUNTRIES_REGION.REGION_CODE
     */
    public BigDecimal getREGION_CODE() {
        return REGION_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUNTRIES_REGION.REGION_CODE
     *
     * @param REGION_CODE the value for COUNTRIES_REGION.REGION_CODE
     */
    public void setREGION_CODE(BigDecimal REGION_CODE) {
        this.REGION_CODE = REGION_CODE;
    }
}