package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class COUNTRIES_TEL_FORMATVO extends COUNTRIES_TEL_FORMATVOKey {
    /**
     * This field corresponds to the database column COUNTRIES_TEL_FORMAT.TEL_CODE_LEN
     */
    private BigDecimal TEL_CODE_LEN;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUNTRIES_TEL_FORMAT.TEL_CODE_LEN
     *
     * @return the value of COUNTRIES_TEL_FORMAT.TEL_CODE_LEN
     */
    public BigDecimal getTEL_CODE_LEN() {
        return TEL_CODE_LEN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUNTRIES_TEL_FORMAT.TEL_CODE_LEN
     *
     * @param TEL_CODE_LEN the value for COUNTRIES_TEL_FORMAT.TEL_CODE_LEN
     */
    public void setTEL_CODE_LEN(BigDecimal TEL_CODE_LEN) {
        this.TEL_CODE_LEN = TEL_CODE_LEN;
    }
}