package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class COUNTRYVO extends BaseVO {
    /**
     * This field corresponds to the database column COUNTRY.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column COUNTRY.COUNTRY_CODE
     */
    private BigDecimal COUNTRY_CODE;

    /**
     * This field corresponds to the database column COUNTRY.BRIEF_DESC_ENG
     */
    private String BRIEF_DESC_ENG;

    /**
     * This field corresponds to the database column COUNTRY.BRIEF_DESC_ARAB
     */
    private String BRIEF_DESC_ARAB;

    /**
     * This field corresponds to the database column COUNTRY.LONG_DESC_ENG
     */
    private String LONG_DESC_ENG;

    /**
     * This field corresponds to the database column COUNTRY.LONG_DESC_ARAB
     */
    private String LONG_DESC_ARAB;

    /**
     * This field corresponds to the database column COUNTRY.SS_IND
     */
    private String SS_IND;

    /**
     * This field corresponds to the database column COUNTRY.LIMIT
     */
    private BigDecimal LIMIT;

    /**
     * This field corresponds to the database column COUNTRY.CONTINENT
     */
    private BigDecimal CONTINENT;

    /**
     * This field corresponds to the database column COUNTRY.COUNTRY_RATING
     */
    private String COUNTRY_RATING;

    /**
     * This field corresponds to the database column COUNTRY.LOCALITE
     */
    private String LOCALITE;

    /**
     * This field corresponds to the database column COUNTRY.ADDITIONAL_REFERENCE
     */
    private String ADDITIONAL_REFERENCE;

    /**
     * This field corresponds to the database column COUNTRY.CREDIT_RATING
     */
    private BigDecimal CREDIT_RATING;

    /**
     * This field corresponds to the database column COUNTRY.TELEPHONE_CODE
     */
    private BigDecimal TELEPHONE_CODE;

    /**
     * This field corresponds to the database column COUNTRY.TELEPHONE_FORMAT
     */
    private String TELEPHONE_FORMAT;

    /**
     * This field corresponds to the database column COUNTRY.SS_CODE
     */
    private BigDecimal SS_CODE;

    /**
     * This field corresponds to the database column COUNTRY.UNEMPLOYMENT_IND
     */
    private String UNEMPLOYMENT_IND;

    /**
     * This field corresponds to the database column COUNTRY.UNEMPLOYMENT_CODE
     */
    private BigDecimal UNEMPLOYMENT_CODE;

    /**
     * This field corresponds to the database column COUNTRY.INDEMNITY_IND
     */
    private String INDEMNITY_IND;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUNTRY.COMP_CODE
     *
     * @return the value of COUNTRY.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUNTRY.COMP_CODE
     *
     * @param COMP_CODE the value for COUNTRY.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUNTRY.COUNTRY_CODE
     *
     * @return the value of COUNTRY.COUNTRY_CODE
     */
    public BigDecimal getCOUNTRY_CODE() {
        return COUNTRY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUNTRY.COUNTRY_CODE
     *
     * @param COUNTRY_CODE the value for COUNTRY.COUNTRY_CODE
     */
    public void setCOUNTRY_CODE(BigDecimal COUNTRY_CODE) {
        this.COUNTRY_CODE = COUNTRY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUNTRY.BRIEF_DESC_ENG
     *
     * @return the value of COUNTRY.BRIEF_DESC_ENG
     */
    public String getBRIEF_DESC_ENG() {
        return BRIEF_DESC_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUNTRY.BRIEF_DESC_ENG
     *
     * @param BRIEF_DESC_ENG the value for COUNTRY.BRIEF_DESC_ENG
     */
    public void setBRIEF_DESC_ENG(String BRIEF_DESC_ENG) {
        this.BRIEF_DESC_ENG = BRIEF_DESC_ENG == null ? null : BRIEF_DESC_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUNTRY.BRIEF_DESC_ARAB
     *
     * @return the value of COUNTRY.BRIEF_DESC_ARAB
     */
    public String getBRIEF_DESC_ARAB() {
        return BRIEF_DESC_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUNTRY.BRIEF_DESC_ARAB
     *
     * @param BRIEF_DESC_ARAB the value for COUNTRY.BRIEF_DESC_ARAB
     */
    public void setBRIEF_DESC_ARAB(String BRIEF_DESC_ARAB) {
        this.BRIEF_DESC_ARAB = BRIEF_DESC_ARAB == null ? null : BRIEF_DESC_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUNTRY.LONG_DESC_ENG
     *
     * @return the value of COUNTRY.LONG_DESC_ENG
     */
    public String getLONG_DESC_ENG() {
        return LONG_DESC_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUNTRY.LONG_DESC_ENG
     *
     * @param LONG_DESC_ENG the value for COUNTRY.LONG_DESC_ENG
     */
    public void setLONG_DESC_ENG(String LONG_DESC_ENG) {
        this.LONG_DESC_ENG = LONG_DESC_ENG == null ? null : LONG_DESC_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUNTRY.LONG_DESC_ARAB
     *
     * @return the value of COUNTRY.LONG_DESC_ARAB
     */
    public String getLONG_DESC_ARAB() {
        return LONG_DESC_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUNTRY.LONG_DESC_ARAB
     *
     * @param LONG_DESC_ARAB the value for COUNTRY.LONG_DESC_ARAB
     */
    public void setLONG_DESC_ARAB(String LONG_DESC_ARAB) {
        this.LONG_DESC_ARAB = LONG_DESC_ARAB == null ? null : LONG_DESC_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUNTRY.SS_IND
     *
     * @return the value of COUNTRY.SS_IND
     */
    public String getSS_IND() {
        return SS_IND;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUNTRY.SS_IND
     *
     * @param SS_IND the value for COUNTRY.SS_IND
     */
    public void setSS_IND(String SS_IND) {
        this.SS_IND = SS_IND == null ? null : SS_IND.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUNTRY.LIMIT
     *
     * @return the value of COUNTRY.LIMIT
     */
    public BigDecimal getLIMIT() {
        return LIMIT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUNTRY.LIMIT
     *
     * @param LIMIT the value for COUNTRY.LIMIT
     */
    public void setLIMIT(BigDecimal LIMIT) {
        this.LIMIT = LIMIT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUNTRY.CONTINENT
     *
     * @return the value of COUNTRY.CONTINENT
     */
    public BigDecimal getCONTINENT() {
        return CONTINENT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUNTRY.CONTINENT
     *
     * @param CONTINENT the value for COUNTRY.CONTINENT
     */
    public void setCONTINENT(BigDecimal CONTINENT) {
        this.CONTINENT = CONTINENT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUNTRY.COUNTRY_RATING
     *
     * @return the value of COUNTRY.COUNTRY_RATING
     */
    public String getCOUNTRY_RATING() {
        return COUNTRY_RATING;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUNTRY.COUNTRY_RATING
     *
     * @param COUNTRY_RATING the value for COUNTRY.COUNTRY_RATING
     */
    public void setCOUNTRY_RATING(String COUNTRY_RATING) {
        this.COUNTRY_RATING = COUNTRY_RATING == null ? null : COUNTRY_RATING.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUNTRY.LOCALITE
     *
     * @return the value of COUNTRY.LOCALITE
     */
    public String getLOCALITE() {
        return LOCALITE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUNTRY.LOCALITE
     *
     * @param LOCALITE the value for COUNTRY.LOCALITE
     */
    public void setLOCALITE(String LOCALITE) {
        this.LOCALITE = LOCALITE == null ? null : LOCALITE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUNTRY.ADDITIONAL_REFERENCE
     *
     * @return the value of COUNTRY.ADDITIONAL_REFERENCE
     */
    public String getADDITIONAL_REFERENCE() {
        return ADDITIONAL_REFERENCE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUNTRY.ADDITIONAL_REFERENCE
     *
     * @param ADDITIONAL_REFERENCE the value for COUNTRY.ADDITIONAL_REFERENCE
     */
    public void setADDITIONAL_REFERENCE(String ADDITIONAL_REFERENCE) {
        this.ADDITIONAL_REFERENCE = ADDITIONAL_REFERENCE == null ? null : ADDITIONAL_REFERENCE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUNTRY.CREDIT_RATING
     *
     * @return the value of COUNTRY.CREDIT_RATING
     */
    public BigDecimal getCREDIT_RATING() {
        return CREDIT_RATING;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUNTRY.CREDIT_RATING
     *
     * @param CREDIT_RATING the value for COUNTRY.CREDIT_RATING
     */
    public void setCREDIT_RATING(BigDecimal CREDIT_RATING) {
        this.CREDIT_RATING = CREDIT_RATING;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUNTRY.TELEPHONE_CODE
     *
     * @return the value of COUNTRY.TELEPHONE_CODE
     */
    public BigDecimal getTELEPHONE_CODE() {
        return TELEPHONE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUNTRY.TELEPHONE_CODE
     *
     * @param TELEPHONE_CODE the value for COUNTRY.TELEPHONE_CODE
     */
    public void setTELEPHONE_CODE(BigDecimal TELEPHONE_CODE) {
        this.TELEPHONE_CODE = TELEPHONE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUNTRY.TELEPHONE_FORMAT
     *
     * @return the value of COUNTRY.TELEPHONE_FORMAT
     */
    public String getTELEPHONE_FORMAT() {
        return TELEPHONE_FORMAT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUNTRY.TELEPHONE_FORMAT
     *
     * @param TELEPHONE_FORMAT the value for COUNTRY.TELEPHONE_FORMAT
     */
    public void setTELEPHONE_FORMAT(String TELEPHONE_FORMAT) {
        this.TELEPHONE_FORMAT = TELEPHONE_FORMAT == null ? null : TELEPHONE_FORMAT.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUNTRY.SS_CODE
     *
     * @return the value of COUNTRY.SS_CODE
     */
    public BigDecimal getSS_CODE() {
        return SS_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUNTRY.SS_CODE
     *
     * @param SS_CODE the value for COUNTRY.SS_CODE
     */
    public void setSS_CODE(BigDecimal SS_CODE) {
        this.SS_CODE = SS_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUNTRY.UNEMPLOYMENT_IND
     *
     * @return the value of COUNTRY.UNEMPLOYMENT_IND
     */
    public String getUNEMPLOYMENT_IND() {
        return UNEMPLOYMENT_IND;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUNTRY.UNEMPLOYMENT_IND
     *
     * @param UNEMPLOYMENT_IND the value for COUNTRY.UNEMPLOYMENT_IND
     */
    public void setUNEMPLOYMENT_IND(String UNEMPLOYMENT_IND) {
        this.UNEMPLOYMENT_IND = UNEMPLOYMENT_IND == null ? null : UNEMPLOYMENT_IND.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUNTRY.UNEMPLOYMENT_CODE
     *
     * @return the value of COUNTRY.UNEMPLOYMENT_CODE
     */
    public BigDecimal getUNEMPLOYMENT_CODE() {
        return UNEMPLOYMENT_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUNTRY.UNEMPLOYMENT_CODE
     *
     * @param UNEMPLOYMENT_CODE the value for COUNTRY.UNEMPLOYMENT_CODE
     */
    public void setUNEMPLOYMENT_CODE(BigDecimal UNEMPLOYMENT_CODE) {
        this.UNEMPLOYMENT_CODE = UNEMPLOYMENT_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUNTRY.INDEMNITY_IND
     *
     * @return the value of COUNTRY.INDEMNITY_IND
     */
    public String getINDEMNITY_IND() {
        return INDEMNITY_IND;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUNTRY.INDEMNITY_IND
     *
     * @param INDEMNITY_IND the value for COUNTRY.INDEMNITY_IND
     */
    public void setINDEMNITY_IND(String INDEMNITY_IND) {
        this.INDEMNITY_IND = INDEMNITY_IND == null ? null : INDEMNITY_IND.trim();
    }
}