package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class CRS03AVO extends BaseVO {
    /**
     * This field corresponds to the database column CRS03A.TII_COMP_CODE
     */
    private BigDecimal TII_COMP_CODE;

    /**
     * This field corresponds to the database column CRS03A.TII_BRANCH_CODE
     */
    private BigDecimal TII_BRANCH_CODE;

    /**
     * This field corresponds to the database column CRS03A.SERIAL_NO
     */
    private BigDecimal SERIAL_NO;

    /**
     * This field corresponds to the database column CRS03A.REF_NO
     */
    private BigDecimal REF_NO;

    /**
     * This field corresponds to the database column CRS03A.MATR_IND
     */
    private String MATR_IND;

    /**
     * This field corresponds to the database column CRS03A.MGMT_IND
     */
    private String MGMT_IND;

    /**
     * This field corresponds to the database column CRS03A.MODARIB_IND
     */
    private String MODARIB_IND;

    /**
     * This field corresponds to the database column CRS03A.GAIN_LOSS_PERCENT
     */
    private BigDecimal GAIN_LOSS_PERCENT;

    /**
     * This field corresponds to the database column CRS03A.ISLAMIC_INTEGRATED
     */
    private String ISLAMIC_INTEGRATED;

    /**
     * This field corresponds to the database column CRS03A.DEBUG_MODE
     */
    private BigDecimal DEBUG_MODE;

    /**
     * This field corresponds to the database column CRS03A.ROLLOVER_NO
     */
    private BigDecimal ROLLOVER_NO;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRS03A.TII_COMP_CODE
     *
     * @return the value of CRS03A.TII_COMP_CODE
     */
    public BigDecimal getTII_COMP_CODE() {
        return TII_COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRS03A.TII_COMP_CODE
     *
     * @param TII_COMP_CODE the value for CRS03A.TII_COMP_CODE
     */
    public void setTII_COMP_CODE(BigDecimal TII_COMP_CODE) {
        this.TII_COMP_CODE = TII_COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRS03A.TII_BRANCH_CODE
     *
     * @return the value of CRS03A.TII_BRANCH_CODE
     */
    public BigDecimal getTII_BRANCH_CODE() {
        return TII_BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRS03A.TII_BRANCH_CODE
     *
     * @param TII_BRANCH_CODE the value for CRS03A.TII_BRANCH_CODE
     */
    public void setTII_BRANCH_CODE(BigDecimal TII_BRANCH_CODE) {
        this.TII_BRANCH_CODE = TII_BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRS03A.SERIAL_NO
     *
     * @return the value of CRS03A.SERIAL_NO
     */
    public BigDecimal getSERIAL_NO() {
        return SERIAL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRS03A.SERIAL_NO
     *
     * @param SERIAL_NO the value for CRS03A.SERIAL_NO
     */
    public void setSERIAL_NO(BigDecimal SERIAL_NO) {
        this.SERIAL_NO = SERIAL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRS03A.REF_NO
     *
     * @return the value of CRS03A.REF_NO
     */
    public BigDecimal getREF_NO() {
        return REF_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRS03A.REF_NO
     *
     * @param REF_NO the value for CRS03A.REF_NO
     */
    public void setREF_NO(BigDecimal REF_NO) {
        this.REF_NO = REF_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRS03A.MATR_IND
     *
     * @return the value of CRS03A.MATR_IND
     */
    public String getMATR_IND() {
        return MATR_IND;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRS03A.MATR_IND
     *
     * @param MATR_IND the value for CRS03A.MATR_IND
     */
    public void setMATR_IND(String MATR_IND) {
        this.MATR_IND = MATR_IND == null ? null : MATR_IND.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRS03A.MGMT_IND
     *
     * @return the value of CRS03A.MGMT_IND
     */
    public String getMGMT_IND() {
        return MGMT_IND;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRS03A.MGMT_IND
     *
     * @param MGMT_IND the value for CRS03A.MGMT_IND
     */
    public void setMGMT_IND(String MGMT_IND) {
        this.MGMT_IND = MGMT_IND == null ? null : MGMT_IND.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRS03A.MODARIB_IND
     *
     * @return the value of CRS03A.MODARIB_IND
     */
    public String getMODARIB_IND() {
        return MODARIB_IND;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRS03A.MODARIB_IND
     *
     * @param MODARIB_IND the value for CRS03A.MODARIB_IND
     */
    public void setMODARIB_IND(String MODARIB_IND) {
        this.MODARIB_IND = MODARIB_IND == null ? null : MODARIB_IND.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRS03A.GAIN_LOSS_PERCENT
     *
     * @return the value of CRS03A.GAIN_LOSS_PERCENT
     */
    public BigDecimal getGAIN_LOSS_PERCENT() {
        return GAIN_LOSS_PERCENT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRS03A.GAIN_LOSS_PERCENT
     *
     * @param GAIN_LOSS_PERCENT the value for CRS03A.GAIN_LOSS_PERCENT
     */
    public void setGAIN_LOSS_PERCENT(BigDecimal GAIN_LOSS_PERCENT) {
        this.GAIN_LOSS_PERCENT = GAIN_LOSS_PERCENT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRS03A.ISLAMIC_INTEGRATED
     *
     * @return the value of CRS03A.ISLAMIC_INTEGRATED
     */
    public String getISLAMIC_INTEGRATED() {
        return ISLAMIC_INTEGRATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRS03A.ISLAMIC_INTEGRATED
     *
     * @param ISLAMIC_INTEGRATED the value for CRS03A.ISLAMIC_INTEGRATED
     */
    public void setISLAMIC_INTEGRATED(String ISLAMIC_INTEGRATED) {
        this.ISLAMIC_INTEGRATED = ISLAMIC_INTEGRATED == null ? null : ISLAMIC_INTEGRATED.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRS03A.DEBUG_MODE
     *
     * @return the value of CRS03A.DEBUG_MODE
     */
    public BigDecimal getDEBUG_MODE() {
        return DEBUG_MODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRS03A.DEBUG_MODE
     *
     * @param DEBUG_MODE the value for CRS03A.DEBUG_MODE
     */
    public void setDEBUG_MODE(BigDecimal DEBUG_MODE) {
        this.DEBUG_MODE = DEBUG_MODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRS03A.ROLLOVER_NO
     *
     * @return the value of CRS03A.ROLLOVER_NO
     */
    public BigDecimal getROLLOVER_NO() {
        return ROLLOVER_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRS03A.ROLLOVER_NO
     *
     * @param ROLLOVER_NO the value for CRS03A.ROLLOVER_NO
     */
    public void setROLLOVER_NO(BigDecimal ROLLOVER_NO) {
        this.ROLLOVER_NO = ROLLOVER_NO;
    }
}