package com.path.dbmaps.vo;

import java.math.BigDecimal;

import com.path.lib.vo.BaseVO;

public class CURRENCIESVOKey extends BaseVO {
    /**
     * This field corresponds to the database column CURRENCIES.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column CURRENCIES.CURRENCY_CODE
     */
    private BigDecimal CURRENCY_CODE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CURRENCIES.COMP_CODE
     *
     * @return the value of CURRENCIES.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CURRENCIES.COMP_CODE
     *
     * @param COMP_CODE the value for CURRENCIES.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CURRENCIES.CURRENCY_CODE
     *
     * @return the value of CURRENCIES.CURRENCY_CODE
     */
    public BigDecimal getCURRENCY_CODE() {
        return CURRENCY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CURRENCIES.CURRENCY_CODE
     *
     * @param CURRENCY_CODE the value for CURRENCIES.CURRENCY_CODE
     */
    public void setCURRENCY_CODE(BigDecimal CURRENCY_CODE) {
        this.CURRENCY_CODE = CURRENCY_CODE;
    }
}