package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class CURRENCY_PRICINGVOKey extends BaseVO {
    /**
     * This field corresponds to the database column CURRENCY_PRICING.BRANCH_CODE
     */
    private BigDecimal BRANCH_CODE;

    /**
     * This field corresponds to the database column CURRENCY_PRICING.CIF_PRIORITY
     */
    private BigDecimal CIF_PRIORITY;

    /**
     * This field corresponds to the database column CURRENCY_PRICING.CIF_TYPE
     */
    private BigDecimal CIF_TYPE;

    /**
     * This field corresponds to the database column CURRENCY_PRICING.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column CURRENCY_PRICING.CURRENCY_CODE
     */
    private BigDecimal CURRENCY_CODE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CURRENCY_PRICING.BRANCH_CODE
     *
     * @return the value of CURRENCY_PRICING.BRANCH_CODE
     */
    public BigDecimal getBRANCH_CODE() {
        return BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CURRENCY_PRICING.BRANCH_CODE
     *
     * @param BRANCH_CODE the value for CURRENCY_PRICING.BRANCH_CODE
     */
    public void setBRANCH_CODE(BigDecimal BRANCH_CODE) {
        this.BRANCH_CODE = BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CURRENCY_PRICING.CIF_PRIORITY
     *
     * @return the value of CURRENCY_PRICING.CIF_PRIORITY
     */
    public BigDecimal getCIF_PRIORITY() {
        return CIF_PRIORITY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CURRENCY_PRICING.CIF_PRIORITY
     *
     * @param CIF_PRIORITY the value for CURRENCY_PRICING.CIF_PRIORITY
     */
    public void setCIF_PRIORITY(BigDecimal CIF_PRIORITY) {
        this.CIF_PRIORITY = CIF_PRIORITY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CURRENCY_PRICING.CIF_TYPE
     *
     * @return the value of CURRENCY_PRICING.CIF_TYPE
     */
    public BigDecimal getCIF_TYPE() {
        return CIF_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CURRENCY_PRICING.CIF_TYPE
     *
     * @param CIF_TYPE the value for CURRENCY_PRICING.CIF_TYPE
     */
    public void setCIF_TYPE(BigDecimal CIF_TYPE) {
        this.CIF_TYPE = CIF_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CURRENCY_PRICING.COMP_CODE
     *
     * @return the value of CURRENCY_PRICING.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CURRENCY_PRICING.COMP_CODE
     *
     * @param COMP_CODE the value for CURRENCY_PRICING.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CURRENCY_PRICING.CURRENCY_CODE
     *
     * @return the value of CURRENCY_PRICING.CURRENCY_CODE
     */
    public BigDecimal getCURRENCY_CODE() {
        return CURRENCY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CURRENCY_PRICING.CURRENCY_CODE
     *
     * @param CURRENCY_CODE the value for CURRENCY_PRICING.CURRENCY_CODE
     */
    public void setCURRENCY_CODE(BigDecimal CURRENCY_CODE) {
        this.CURRENCY_CODE = CURRENCY_CODE;
    }
}