package com.path.dbmaps.vo;

import java.math.BigDecimal;

import com.path.lib.vo.BaseVO;

public class CUSTGRADEVOKey extends BaseVO {
    /**
     * This field corresponds to the database column CUSTGRADE.APP_NAME
     */
    private String APP_NAME;

    /**
     * This field corresponds to the database column CUSTGRADE.BRANCH
     */
    private BigDecimal BRANCH;

    /**
     * This field corresponds to the database column CUSTGRADE.CODE
     */
    private BigDecimal CODE;

    /**
     * This field corresponds to the database column CUSTGRADE.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSTGRADE.APP_NAME
     *
     * @return the value of CUSTGRADE.APP_NAME
     */
    public String getAPP_NAME() {
        return APP_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSTGRADE.APP_NAME
     *
     * @param APP_NAME the value for CUSTGRADE.APP_NAME
     */
    public void setAPP_NAME(String APP_NAME) {
        this.APP_NAME = APP_NAME == null ? null : APP_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSTGRADE.BRANCH
     *
     * @return the value of CUSTGRADE.BRANCH
     */
    public BigDecimal getBRANCH() {
        return BRANCH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSTGRADE.BRANCH
     *
     * @param BRANCH the value for CUSTGRADE.BRANCH
     */
    public void setBRANCH(BigDecimal BRANCH) {
        this.BRANCH = BRANCH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSTGRADE.CODE
     *
     * @return the value of CUSTGRADE.CODE
     */
    public BigDecimal getCODE() {
        return CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSTGRADE.CODE
     *
     * @param CODE the value for CUSTGRADE.CODE
     */
    public void setCODE(BigDecimal CODE) {
        this.CODE = CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSTGRADE.COMP_CODE
     *
     * @return the value of CUSTGRADE.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSTGRADE.COMP_CODE
     *
     * @param COMP_CODE the value for CUSTGRADE.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }
}