package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class DEPARTMENTSVOKey extends BaseVO {
    /**
     * This field corresponds to the database column DEPARTMENTS.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column DEPARTMENTS.DEPT_CODE
     */
    private BigDecimal DEPT_CODE;

    /**
     * This field corresponds to the database column DEPARTMENTS.DIVISION_CODE
     */
    private BigDecimal DIVISION_CODE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEPARTMENTS.COMP_CODE
     *
     * @return the value of DEPARTMENTS.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEPARTMENTS.COMP_CODE
     *
     * @param COMP_CODE the value for DEPARTMENTS.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEPARTMENTS.DEPT_CODE
     *
     * @return the value of DEPARTMENTS.DEPT_CODE
     */
    public BigDecimal getDEPT_CODE() {
        return DEPT_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEPARTMENTS.DEPT_CODE
     *
     * @param DEPT_CODE the value for DEPARTMENTS.DEPT_CODE
     */
    public void setDEPT_CODE(BigDecimal DEPT_CODE) {
        this.DEPT_CODE = DEPT_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEPARTMENTS.DIVISION_CODE
     *
     * @return the value of DEPARTMENTS.DIVISION_CODE
     */
    public BigDecimal getDIVISION_CODE() {
        return DIVISION_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEPARTMENTS.DIVISION_CODE
     *
     * @param DIVISION_CODE the value for DEPARTMENTS.DIVISION_CODE
     */
    public void setDIVISION_CODE(BigDecimal DIVISION_CODE) {
        this.DIVISION_CODE = DIVISION_CODE;
    }
}