package com.path.dbmaps.vo;

public class DF_FILE_MIGR_TABLESVO extends DF_FILE_MIGR_TABLESVOKey {
    /**
     * This field corresponds to the database column DF_FILE_MIGR_TABLES.TABLE_NAME
     */
    private String TABLE_NAME;

    /**
     * This field corresponds to the database column DF_FILE_MIGR_TABLES.DYNAMIC_CONDITION
     */
    private String DYNAMIC_CONDITION;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DF_FILE_MIGR_TABLES.TABLE_NAME
     *
     * @return the value of DF_FILE_MIGR_TABLES.TABLE_NAME
     */
    public String getTABLE_NAME() {
        return TABLE_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DF_FILE_MIGR_TABLES.TABLE_NAME
     *
     * @param TABLE_NAME the value for DF_FILE_MIGR_TABLES.TABLE_NAME
     */
    public void setTABLE_NAME(String TABLE_NAME) {
        this.TABLE_NAME = TABLE_NAME == null ? null : TABLE_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DF_FILE_MIGR_TABLES.DYNAMIC_CONDITION
     *
     * @return the value of DF_FILE_MIGR_TABLES.DYNAMIC_CONDITION
     */
    public String getDYNAMIC_CONDITION() {
        return DYNAMIC_CONDITION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DF_FILE_MIGR_TABLES.DYNAMIC_CONDITION
     *
     * @param DYNAMIC_CONDITION the value for DF_FILE_MIGR_TABLES.DYNAMIC_CONDITION
     */
    public void setDYNAMIC_CONDITION(String DYNAMIC_CONDITION) {
        this.DYNAMIC_CONDITION = DYNAMIC_CONDITION == null ? null : DYNAMIC_CONDITION.trim();
    }
}