package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class DF_FILE_MISC_SQLVOKey extends BaseVO {
    /**
     * This field corresponds to the database column DF_FILE_MISC_SQL.FILE_CODE
     */
    private String FILE_CODE;

    /**
     * This field corresponds to the database column DF_FILE_MISC_SQL.SOURCE_SQL_NO
     */
    private BigDecimal SOURCE_SQL_NO;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DF_FILE_MISC_SQL.FILE_CODE
     *
     * @return the value of DF_FILE_MISC_SQL.FILE_CODE
     */
    public String getFILE_CODE() {
        return FILE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DF_FILE_MISC_SQL.FILE_CODE
     *
     * @param FILE_CODE the value for DF_FILE_MISC_SQL.FILE_CODE
     */
    public void setFILE_CODE(String FILE_CODE) {
        this.FILE_CODE = FILE_CODE == null ? null : FILE_CODE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DF_FILE_MISC_SQL.SOURCE_SQL_NO
     *
     * @return the value of DF_FILE_MISC_SQL.SOURCE_SQL_NO
     */
    public BigDecimal getSOURCE_SQL_NO() {
        return SOURCE_SQL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DF_FILE_MISC_SQL.SOURCE_SQL_NO
     *
     * @param SOURCE_SQL_NO the value for DF_FILE_MISC_SQL.SOURCE_SQL_NO
     */
    public void setSOURCE_SQL_NO(BigDecimal SOURCE_SQL_NO) {
        this.SOURCE_SQL_NO = SOURCE_SQL_NO;
    }
}