package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class DF_FILE_STRUCT_DETAILVOKey extends BaseVO {
    /**
     * This field corresponds to the database column DF_FILE_STRUCT_DETAIL.STRUCT_CODE
     */
    private String STRUCT_CODE;

    /**
     * This field corresponds to the database column DF_FILE_STRUCT_DETAIL.TAG_NO
     */
    private BigDecimal TAG_NO;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DF_FILE_STRUCT_DETAIL.STRUCT_CODE
     *
     * @return the value of DF_FILE_STRUCT_DETAIL.STRUCT_CODE
     */
    public String getSTRUCT_CODE() {
        return STRUCT_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DF_FILE_STRUCT_DETAIL.STRUCT_CODE
     *
     * @param STRUCT_CODE the value for DF_FILE_STRUCT_DETAIL.STRUCT_CODE
     */
    public void setSTRUCT_CODE(String STRUCT_CODE) {
        this.STRUCT_CODE = STRUCT_CODE == null ? null : STRUCT_CODE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DF_FILE_STRUCT_DETAIL.TAG_NO
     *
     * @return the value of DF_FILE_STRUCT_DETAIL.TAG_NO
     */
    public BigDecimal getTAG_NO() {
        return TAG_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DF_FILE_STRUCT_DETAIL.TAG_NO
     *
     * @param TAG_NO the value for DF_FILE_STRUCT_DETAIL.TAG_NO
     */
    public void setTAG_NO(BigDecimal TAG_NO) {
        this.TAG_NO = TAG_NO;
    }
}