package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class DF_FILE_FUNC_INP_PARMVOKey extends BaseVO {
    /**
     * This field corresponds to the database column DF_FILE_FUNC_INP_PARM.FILE_CODE
     */
    private String FILE_CODE;

    /**
     * This field corresponds to the database column DF_FILE_FUNC_INP_PARM.FUNC_NO
     */
    private BigDecimal FUNC_NO;

    /**
     * This field corresponds to the database column DF_FILE_FUNC_INP_PARM.INP_PARM_NO
     */
    private BigDecimal INP_PARM_NO;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DF_FILE_FUNC_INP_PARM.FILE_CODE
     *
     * @return the value of DF_FILE_FUNC_INP_PARM.FILE_CODE
     */
    public String getFILE_CODE() {
        return FILE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DF_FILE_FUNC_INP_PARM.FILE_CODE
     *
     * @param FILE_CODE the value for DF_FILE_FUNC_INP_PARM.FILE_CODE
     */
    public void setFILE_CODE(String FILE_CODE) {
        this.FILE_CODE = FILE_CODE == null ? null : FILE_CODE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DF_FILE_FUNC_INP_PARM.FUNC_NO
     *
     * @return the value of DF_FILE_FUNC_INP_PARM.FUNC_NO
     */
    public BigDecimal getFUNC_NO() {
        return FUNC_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DF_FILE_FUNC_INP_PARM.FUNC_NO
     *
     * @param FUNC_NO the value for DF_FILE_FUNC_INP_PARM.FUNC_NO
     */
    public void setFUNC_NO(BigDecimal FUNC_NO) {
        this.FUNC_NO = FUNC_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DF_FILE_FUNC_INP_PARM.INP_PARM_NO
     *
     * @return the value of DF_FILE_FUNC_INP_PARM.INP_PARM_NO
     */
    public BigDecimal getINP_PARM_NO() {
        return INP_PARM_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DF_FILE_FUNC_INP_PARM.INP_PARM_NO
     *
     * @param INP_PARM_NO the value for DF_FILE_FUNC_INP_PARM.INP_PARM_NO
     */
    public void setINP_PARM_NO(BigDecimal INP_PARM_NO) {
        this.INP_PARM_NO = INP_PARM_NO;
    }
}