package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class DF_FILE_MIGR_TABLESVOKey extends BaseVO {
    /**
     * This field corresponds to the database column DF_FILE_MIGR_TABLES.COL_NO
     */
    private BigDecimal COL_NO;

    /**
     * This field corresponds to the database column DF_FILE_MIGR_TABLES.FILE_CODE
     */
    private String FILE_CODE;

    /**
     * This field corresponds to the database column DF_FILE_MIGR_TABLES.TABLE_NO
     */
    private BigDecimal TABLE_NO;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DF_FILE_MIGR_TABLES.COL_NO
     *
     * @return the value of DF_FILE_MIGR_TABLES.COL_NO
     */
    public BigDecimal getCOL_NO() {
        return COL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DF_FILE_MIGR_TABLES.COL_NO
     *
     * @param COL_NO the value for DF_FILE_MIGR_TABLES.COL_NO
     */
    public void setCOL_NO(BigDecimal COL_NO) {
        this.COL_NO = COL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DF_FILE_MIGR_TABLES.FILE_CODE
     *
     * @return the value of DF_FILE_MIGR_TABLES.FILE_CODE
     */
    public String getFILE_CODE() {
        return FILE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DF_FILE_MIGR_TABLES.FILE_CODE
     *
     * @param FILE_CODE the value for DF_FILE_MIGR_TABLES.FILE_CODE
     */
    public void setFILE_CODE(String FILE_CODE) {
        this.FILE_CODE = FILE_CODE == null ? null : FILE_CODE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DF_FILE_MIGR_TABLES.TABLE_NO
     *
     * @return the value of DF_FILE_MIGR_TABLES.TABLE_NO
     */
    public BigDecimal getTABLE_NO() {
        return TABLE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DF_FILE_MIGR_TABLES.TABLE_NO
     *
     * @param TABLE_NO the value for DF_FILE_MIGR_TABLES.TABLE_NO
     */
    public void setTABLE_NO(BigDecimal TABLE_NO) {
        this.TABLE_NO = TABLE_NO;
    }
}