package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class DF_FILE_TAG_VALUESVO extends DF_FILE_TAG_VALUESVOKey {
    /**
     * This field corresponds to the database column DF_FILE_TAG_VALUES.SOURCE_SQL_NO
     */
    private BigDecimal SOURCE_SQL_NO;

    /**
     * This field corresponds to the database column DF_FILE_TAG_VALUES.SOURCE_SQL_COL
     */
    private String SOURCE_SQL_COL;

    /**
     * This field corresponds to the database column DF_FILE_TAG_VALUES.FIELD_DATA_TYPE
     */
    private String FIELD_DATA_TYPE;

    /**
     * This field corresponds to the database column DF_FILE_TAG_VALUES.FIELD_LEN
     */
    private BigDecimal FIELD_LEN;

    /**
     * This field corresponds to the database column DF_FILE_TAG_VALUES.FORMAT_EXPR
     */
    private String FORMAT_EXPR;

    /**
     * This field corresponds to the database column DF_FILE_TAG_VALUES.PAD_LEFT_RIGHT
     */
    private String PAD_LEFT_RIGHT;

    /**
     * This field corresponds to the database column DF_FILE_TAG_VALUES.PADDING_CHAR
     */
    private String PADDING_CHAR;

    /**
     * This field corresponds to the database column DF_FILE_TAG_VALUES.VISIBLE_FLAG
     */
    private String VISIBLE_FLAG;

    /**
     * This field corresponds to the database column DF_FILE_TAG_VALUES.DISPLAY_ORDER_NO
     */
    private BigDecimal DISPLAY_ORDER_NO;

    /**
     * This field corresponds to the database column DF_FILE_TAG_VALUES.POSITION
     */
    private BigDecimal POSITION;

    /**
     * This field corresponds to the database column DF_FILE_TAG_VALUES.FILE_PARM_NO
     */
    private BigDecimal FILE_PARM_NO;

    /**
     * This field corresponds to the database column DF_FILE_TAG_VALUES.EXCEL_COLUMN_NO
     */
    private BigDecimal EXCEL_COLUMN_NO;

    /**
     * This field corresponds to the database column DF_FILE_TAG_VALUES.SKIP_TAG
     */
    private String SKIP_TAG;

    /**
     * This field corresponds to the database column DF_FILE_TAG_VALUES.SOURCE_LST_SQL_NO
     */
    private BigDecimal SOURCE_LST_SQL_NO;

    /**
     * This field corresponds to the database column DF_FILE_TAG_VALUES.EDITABLE
     */
    private String EDITABLE;

    /**
     * This field corresponds to the database column DF_FILE_TAG_VALUES.COMP_EXPR
     */
    private String COMP_EXPR;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DF_FILE_TAG_VALUES.SOURCE_SQL_NO
     *
     * @return the value of DF_FILE_TAG_VALUES.SOURCE_SQL_NO
     */
    public BigDecimal getSOURCE_SQL_NO() {
        return SOURCE_SQL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DF_FILE_TAG_VALUES.SOURCE_SQL_NO
     *
     * @param SOURCE_SQL_NO the value for DF_FILE_TAG_VALUES.SOURCE_SQL_NO
     */
    public void setSOURCE_SQL_NO(BigDecimal SOURCE_SQL_NO) {
        this.SOURCE_SQL_NO = SOURCE_SQL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DF_FILE_TAG_VALUES.SOURCE_SQL_COL
     *
     * @return the value of DF_FILE_TAG_VALUES.SOURCE_SQL_COL
     */
    public String getSOURCE_SQL_COL() {
        return SOURCE_SQL_COL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DF_FILE_TAG_VALUES.SOURCE_SQL_COL
     *
     * @param SOURCE_SQL_COL the value for DF_FILE_TAG_VALUES.SOURCE_SQL_COL
     */
    public void setSOURCE_SQL_COL(String SOURCE_SQL_COL) {
        this.SOURCE_SQL_COL = SOURCE_SQL_COL == null ? null : SOURCE_SQL_COL.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DF_FILE_TAG_VALUES.FIELD_DATA_TYPE
     *
     * @return the value of DF_FILE_TAG_VALUES.FIELD_DATA_TYPE
     */
    public String getFIELD_DATA_TYPE() {
        return FIELD_DATA_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DF_FILE_TAG_VALUES.FIELD_DATA_TYPE
     *
     * @param FIELD_DATA_TYPE the value for DF_FILE_TAG_VALUES.FIELD_DATA_TYPE
     */
    public void setFIELD_DATA_TYPE(String FIELD_DATA_TYPE) {
        this.FIELD_DATA_TYPE = FIELD_DATA_TYPE == null ? null : FIELD_DATA_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DF_FILE_TAG_VALUES.FIELD_LEN
     *
     * @return the value of DF_FILE_TAG_VALUES.FIELD_LEN
     */
    public BigDecimal getFIELD_LEN() {
        return FIELD_LEN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DF_FILE_TAG_VALUES.FIELD_LEN
     *
     * @param FIELD_LEN the value for DF_FILE_TAG_VALUES.FIELD_LEN
     */
    public void setFIELD_LEN(BigDecimal FIELD_LEN) {
        this.FIELD_LEN = FIELD_LEN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DF_FILE_TAG_VALUES.FORMAT_EXPR
     *
     * @return the value of DF_FILE_TAG_VALUES.FORMAT_EXPR
     */
    public String getFORMAT_EXPR() {
        return FORMAT_EXPR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DF_FILE_TAG_VALUES.FORMAT_EXPR
     *
     * @param FORMAT_EXPR the value for DF_FILE_TAG_VALUES.FORMAT_EXPR
     */
    public void setFORMAT_EXPR(String FORMAT_EXPR) {
        this.FORMAT_EXPR = FORMAT_EXPR == null ? null : FORMAT_EXPR.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DF_FILE_TAG_VALUES.PAD_LEFT_RIGHT
     *
     * @return the value of DF_FILE_TAG_VALUES.PAD_LEFT_RIGHT
     */
    public String getPAD_LEFT_RIGHT() {
        return PAD_LEFT_RIGHT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DF_FILE_TAG_VALUES.PAD_LEFT_RIGHT
     *
     * @param PAD_LEFT_RIGHT the value for DF_FILE_TAG_VALUES.PAD_LEFT_RIGHT
     */
    public void setPAD_LEFT_RIGHT(String PAD_LEFT_RIGHT) {
        this.PAD_LEFT_RIGHT = PAD_LEFT_RIGHT == null ? null : PAD_LEFT_RIGHT.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DF_FILE_TAG_VALUES.PADDING_CHAR
     *
     * @return the value of DF_FILE_TAG_VALUES.PADDING_CHAR
     */
    public String getPADDING_CHAR() {
        return PADDING_CHAR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DF_FILE_TAG_VALUES.PADDING_CHAR
     *
     * @param PADDING_CHAR the value for DF_FILE_TAG_VALUES.PADDING_CHAR
     */
    public void setPADDING_CHAR(String PADDING_CHAR) {
        this.PADDING_CHAR = PADDING_CHAR == null ? null : PADDING_CHAR.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DF_FILE_TAG_VALUES.VISIBLE_FLAG
     *
     * @return the value of DF_FILE_TAG_VALUES.VISIBLE_FLAG
     */
    public String getVISIBLE_FLAG() {
        return VISIBLE_FLAG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DF_FILE_TAG_VALUES.VISIBLE_FLAG
     *
     * @param VISIBLE_FLAG the value for DF_FILE_TAG_VALUES.VISIBLE_FLAG
     */
    public void setVISIBLE_FLAG(String VISIBLE_FLAG) {
        this.VISIBLE_FLAG = VISIBLE_FLAG == null ? null : VISIBLE_FLAG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DF_FILE_TAG_VALUES.DISPLAY_ORDER_NO
     *
     * @return the value of DF_FILE_TAG_VALUES.DISPLAY_ORDER_NO
     */
    public BigDecimal getDISPLAY_ORDER_NO() {
        return DISPLAY_ORDER_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DF_FILE_TAG_VALUES.DISPLAY_ORDER_NO
     *
     * @param DISPLAY_ORDER_NO the value for DF_FILE_TAG_VALUES.DISPLAY_ORDER_NO
     */
    public void setDISPLAY_ORDER_NO(BigDecimal DISPLAY_ORDER_NO) {
        this.DISPLAY_ORDER_NO = DISPLAY_ORDER_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DF_FILE_TAG_VALUES.POSITION
     *
     * @return the value of DF_FILE_TAG_VALUES.POSITION
     */
    public BigDecimal getPOSITION() {
        return POSITION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DF_FILE_TAG_VALUES.POSITION
     *
     * @param POSITION the value for DF_FILE_TAG_VALUES.POSITION
     */
    public void setPOSITION(BigDecimal POSITION) {
        this.POSITION = POSITION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DF_FILE_TAG_VALUES.FILE_PARM_NO
     *
     * @return the value of DF_FILE_TAG_VALUES.FILE_PARM_NO
     */
    public BigDecimal getFILE_PARM_NO() {
        return FILE_PARM_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DF_FILE_TAG_VALUES.FILE_PARM_NO
     *
     * @param FILE_PARM_NO the value for DF_FILE_TAG_VALUES.FILE_PARM_NO
     */
    public void setFILE_PARM_NO(BigDecimal FILE_PARM_NO) {
        this.FILE_PARM_NO = FILE_PARM_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DF_FILE_TAG_VALUES.EXCEL_COLUMN_NO
     *
     * @return the value of DF_FILE_TAG_VALUES.EXCEL_COLUMN_NO
     */
    public BigDecimal getEXCEL_COLUMN_NO() {
        return EXCEL_COLUMN_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DF_FILE_TAG_VALUES.EXCEL_COLUMN_NO
     *
     * @param EXCEL_COLUMN_NO the value for DF_FILE_TAG_VALUES.EXCEL_COLUMN_NO
     */
    public void setEXCEL_COLUMN_NO(BigDecimal EXCEL_COLUMN_NO) {
        this.EXCEL_COLUMN_NO = EXCEL_COLUMN_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DF_FILE_TAG_VALUES.SKIP_TAG
     *
     * @return the value of DF_FILE_TAG_VALUES.SKIP_TAG
     */
    public String getSKIP_TAG() {
        return SKIP_TAG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DF_FILE_TAG_VALUES.SKIP_TAG
     *
     * @param SKIP_TAG the value for DF_FILE_TAG_VALUES.SKIP_TAG
     */
    public void setSKIP_TAG(String SKIP_TAG) {
        this.SKIP_TAG = SKIP_TAG == null ? null : SKIP_TAG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DF_FILE_TAG_VALUES.SOURCE_LST_SQL_NO
     *
     * @return the value of DF_FILE_TAG_VALUES.SOURCE_LST_SQL_NO
     */
    public BigDecimal getSOURCE_LST_SQL_NO() {
        return SOURCE_LST_SQL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DF_FILE_TAG_VALUES.SOURCE_LST_SQL_NO
     *
     * @param SOURCE_LST_SQL_NO the value for DF_FILE_TAG_VALUES.SOURCE_LST_SQL_NO
     */
    public void setSOURCE_LST_SQL_NO(BigDecimal SOURCE_LST_SQL_NO) {
        this.SOURCE_LST_SQL_NO = SOURCE_LST_SQL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DF_FILE_TAG_VALUES.EDITABLE
     *
     * @return the value of DF_FILE_TAG_VALUES.EDITABLE
     */
    public String getEDITABLE() {
        return EDITABLE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DF_FILE_TAG_VALUES.EDITABLE
     *
     * @param EDITABLE the value for DF_FILE_TAG_VALUES.EDITABLE
     */
    public void setEDITABLE(String EDITABLE) {
        this.EDITABLE = EDITABLE == null ? null : EDITABLE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DF_FILE_TAG_VALUES.COMP_EXPR
     *
     * @return the value of DF_FILE_TAG_VALUES.COMP_EXPR
     */
    public String getCOMP_EXPR() {
        return COMP_EXPR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DF_FILE_TAG_VALUES.COMP_EXPR
     *
     * @param COMP_EXPR the value for DF_FILE_TAG_VALUES.COMP_EXPR
     */
    public void setCOMP_EXPR(String COMP_EXPR) {
        this.COMP_EXPR = COMP_EXPR == null ? null : COMP_EXPR.trim();
    }
}