package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class DF_HD_FILE_GROUPVO extends BaseVO {
    /**
     * This field corresponds to the database column DF_HD_FILE_GROUP.GROUP_CODE
     */
    private String GROUP_CODE;

    /**
     * This field corresponds to the database column DF_HD_FILE_GROUP.GROUP_DSC
     */
    private String GROUP_DSC;

    /**
     * This field corresponds to the database column DF_HD_FILE_GROUP.STRUCT_TYPE
     */
    private String STRUCT_TYPE;

    /**
     * This field corresponds to the database column DF_HD_FILE_GROUP.FILE_LOCATION
     */
    private String FILE_LOCATION;

    /**
     * This field corresponds to the database column DF_HD_FILE_GROUP.FILE_NAME
     */
    private String FILE_NAME;

    /**
     * This field corresponds to the database column DF_HD_FILE_GROUP.FILE_EXT
     */
    private String FILE_EXT;

    /**
     * This field corresponds to the database column DF_HD_FILE_GROUP.APPL_NAME
     */
    private String APPL_NAME;

    /**
     * This field corresponds to the database column DF_HD_FILE_GROUP.ALLOW_FILE_NAME_CHG
     */
    private String ALLOW_FILE_NAME_CHG;

    /**
     * This field corresponds to the database column DF_HD_FILE_GROUP.ALLOW_FILE_LOC_CHG
     */
    private String ALLOW_FILE_LOC_CHG;

    /**
     * This field corresponds to the database column DF_HD_FILE_GROUP.FILE_TYPE
     */
    private String FILE_TYPE;

    /**
     * This field corresponds to the database column DF_HD_FILE_GROUP.IMPORT_TYPE
     */
    private String IMPORT_TYPE;

    /**
     * This field corresponds to the database column DF_HD_FILE_GROUP.RUN_SCRIPT
     */
    private String RUN_SCRIPT;

    /**
     * This field corresponds to the database column DF_HD_FILE_GROUP.START_LINE_NO
     */
    private BigDecimal START_LINE_NO;

    /**
     * This field corresponds to the database column DF_HD_FILE_GROUP.COMMIT_EACH_SELECT
     */
    private String COMMIT_EACH_SELECT;

    /**
     * This field corresponds to the database column DF_HD_FILE_GROUP.SHOW_SCRIPT
     */
    private String SHOW_SCRIPT;

    /**
     * This field corresponds to the database column DF_HD_FILE_GROUP.UPDATE_SCRIPT
     */
    private String UPDATE_SCRIPT;

    /**
     * This field corresponds to the database column DF_HD_FILE_GROUP.MIGRATION_STRUCT
     */
    private String MIGRATION_STRUCT;

    /**
     * This field corresponds to the database column DF_HD_FILE_GROUP.FILE_NAME_SQL
     */
    private String FILE_NAME_SQL;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DF_HD_FILE_GROUP.GROUP_CODE
     *
     * @return the value of DF_HD_FILE_GROUP.GROUP_CODE
     */
    public String getGROUP_CODE() {
        return GROUP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DF_HD_FILE_GROUP.GROUP_CODE
     *
     * @param GROUP_CODE the value for DF_HD_FILE_GROUP.GROUP_CODE
     */
    public void setGROUP_CODE(String GROUP_CODE) {
        this.GROUP_CODE = GROUP_CODE == null ? null : GROUP_CODE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DF_HD_FILE_GROUP.GROUP_DSC
     *
     * @return the value of DF_HD_FILE_GROUP.GROUP_DSC
     */
    public String getGROUP_DSC() {
        return GROUP_DSC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DF_HD_FILE_GROUP.GROUP_DSC
     *
     * @param GROUP_DSC the value for DF_HD_FILE_GROUP.GROUP_DSC
     */
    public void setGROUP_DSC(String GROUP_DSC) {
        this.GROUP_DSC = GROUP_DSC == null ? null : GROUP_DSC.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DF_HD_FILE_GROUP.STRUCT_TYPE
     *
     * @return the value of DF_HD_FILE_GROUP.STRUCT_TYPE
     */
    public String getSTRUCT_TYPE() {
        return STRUCT_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DF_HD_FILE_GROUP.STRUCT_TYPE
     *
     * @param STRUCT_TYPE the value for DF_HD_FILE_GROUP.STRUCT_TYPE
     */
    public void setSTRUCT_TYPE(String STRUCT_TYPE) {
        this.STRUCT_TYPE = STRUCT_TYPE == null ? null : STRUCT_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DF_HD_FILE_GROUP.FILE_LOCATION
     *
     * @return the value of DF_HD_FILE_GROUP.FILE_LOCATION
     */
    public String getFILE_LOCATION() {
        return FILE_LOCATION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DF_HD_FILE_GROUP.FILE_LOCATION
     *
     * @param FILE_LOCATION the value for DF_HD_FILE_GROUP.FILE_LOCATION
     */
    public void setFILE_LOCATION(String FILE_LOCATION) {
        this.FILE_LOCATION = FILE_LOCATION == null ? null : FILE_LOCATION.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DF_HD_FILE_GROUP.FILE_NAME
     *
     * @return the value of DF_HD_FILE_GROUP.FILE_NAME
     */
    public String getFILE_NAME() {
        return FILE_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DF_HD_FILE_GROUP.FILE_NAME
     *
     * @param FILE_NAME the value for DF_HD_FILE_GROUP.FILE_NAME
     */
    public void setFILE_NAME(String FILE_NAME) {
        this.FILE_NAME = FILE_NAME == null ? null : FILE_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DF_HD_FILE_GROUP.FILE_EXT
     *
     * @return the value of DF_HD_FILE_GROUP.FILE_EXT
     */
    public String getFILE_EXT() {
        return FILE_EXT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DF_HD_FILE_GROUP.FILE_EXT
     *
     * @param FILE_EXT the value for DF_HD_FILE_GROUP.FILE_EXT
     */
    public void setFILE_EXT(String FILE_EXT) {
        this.FILE_EXT = FILE_EXT == null ? null : FILE_EXT.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DF_HD_FILE_GROUP.APPL_NAME
     *
     * @return the value of DF_HD_FILE_GROUP.APPL_NAME
     */
    public String getAPPL_NAME() {
        return APPL_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DF_HD_FILE_GROUP.APPL_NAME
     *
     * @param APPL_NAME the value for DF_HD_FILE_GROUP.APPL_NAME
     */
    public void setAPPL_NAME(String APPL_NAME) {
        this.APPL_NAME = APPL_NAME == null ? null : APPL_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DF_HD_FILE_GROUP.ALLOW_FILE_NAME_CHG
     *
     * @return the value of DF_HD_FILE_GROUP.ALLOW_FILE_NAME_CHG
     */
    public String getALLOW_FILE_NAME_CHG() {
        return ALLOW_FILE_NAME_CHG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DF_HD_FILE_GROUP.ALLOW_FILE_NAME_CHG
     *
     * @param ALLOW_FILE_NAME_CHG the value for DF_HD_FILE_GROUP.ALLOW_FILE_NAME_CHG
     */
    public void setALLOW_FILE_NAME_CHG(String ALLOW_FILE_NAME_CHG) {
        this.ALLOW_FILE_NAME_CHG = ALLOW_FILE_NAME_CHG == null ? null : ALLOW_FILE_NAME_CHG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DF_HD_FILE_GROUP.ALLOW_FILE_LOC_CHG
     *
     * @return the value of DF_HD_FILE_GROUP.ALLOW_FILE_LOC_CHG
     */
    public String getALLOW_FILE_LOC_CHG() {
        return ALLOW_FILE_LOC_CHG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DF_HD_FILE_GROUP.ALLOW_FILE_LOC_CHG
     *
     * @param ALLOW_FILE_LOC_CHG the value for DF_HD_FILE_GROUP.ALLOW_FILE_LOC_CHG
     */
    public void setALLOW_FILE_LOC_CHG(String ALLOW_FILE_LOC_CHG) {
        this.ALLOW_FILE_LOC_CHG = ALLOW_FILE_LOC_CHG == null ? null : ALLOW_FILE_LOC_CHG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DF_HD_FILE_GROUP.FILE_TYPE
     *
     * @return the value of DF_HD_FILE_GROUP.FILE_TYPE
     */
    public String getFILE_TYPE() {
        return FILE_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DF_HD_FILE_GROUP.FILE_TYPE
     *
     * @param FILE_TYPE the value for DF_HD_FILE_GROUP.FILE_TYPE
     */
    public void setFILE_TYPE(String FILE_TYPE) {
        this.FILE_TYPE = FILE_TYPE == null ? null : FILE_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DF_HD_FILE_GROUP.IMPORT_TYPE
     *
     * @return the value of DF_HD_FILE_GROUP.IMPORT_TYPE
     */
    public String getIMPORT_TYPE() {
        return IMPORT_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DF_HD_FILE_GROUP.IMPORT_TYPE
     *
     * @param IMPORT_TYPE the value for DF_HD_FILE_GROUP.IMPORT_TYPE
     */
    public void setIMPORT_TYPE(String IMPORT_TYPE) {
        this.IMPORT_TYPE = IMPORT_TYPE == null ? null : IMPORT_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DF_HD_FILE_GROUP.RUN_SCRIPT
     *
     * @return the value of DF_HD_FILE_GROUP.RUN_SCRIPT
     */
    public String getRUN_SCRIPT() {
        return RUN_SCRIPT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DF_HD_FILE_GROUP.RUN_SCRIPT
     *
     * @param RUN_SCRIPT the value for DF_HD_FILE_GROUP.RUN_SCRIPT
     */
    public void setRUN_SCRIPT(String RUN_SCRIPT) {
        this.RUN_SCRIPT = RUN_SCRIPT == null ? null : RUN_SCRIPT.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DF_HD_FILE_GROUP.START_LINE_NO
     *
     * @return the value of DF_HD_FILE_GROUP.START_LINE_NO
     */
    public BigDecimal getSTART_LINE_NO() {
        return START_LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DF_HD_FILE_GROUP.START_LINE_NO
     *
     * @param START_LINE_NO the value for DF_HD_FILE_GROUP.START_LINE_NO
     */
    public void setSTART_LINE_NO(BigDecimal START_LINE_NO) {
        this.START_LINE_NO = START_LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DF_HD_FILE_GROUP.COMMIT_EACH_SELECT
     *
     * @return the value of DF_HD_FILE_GROUP.COMMIT_EACH_SELECT
     */
    public String getCOMMIT_EACH_SELECT() {
        return COMMIT_EACH_SELECT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DF_HD_FILE_GROUP.COMMIT_EACH_SELECT
     *
     * @param COMMIT_EACH_SELECT the value for DF_HD_FILE_GROUP.COMMIT_EACH_SELECT
     */
    public void setCOMMIT_EACH_SELECT(String COMMIT_EACH_SELECT) {
        this.COMMIT_EACH_SELECT = COMMIT_EACH_SELECT == null ? null : COMMIT_EACH_SELECT.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DF_HD_FILE_GROUP.SHOW_SCRIPT
     *
     * @return the value of DF_HD_FILE_GROUP.SHOW_SCRIPT
     */
    public String getSHOW_SCRIPT() {
        return SHOW_SCRIPT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DF_HD_FILE_GROUP.SHOW_SCRIPT
     *
     * @param SHOW_SCRIPT the value for DF_HD_FILE_GROUP.SHOW_SCRIPT
     */
    public void setSHOW_SCRIPT(String SHOW_SCRIPT) {
        this.SHOW_SCRIPT = SHOW_SCRIPT == null ? null : SHOW_SCRIPT.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DF_HD_FILE_GROUP.UPDATE_SCRIPT
     *
     * @return the value of DF_HD_FILE_GROUP.UPDATE_SCRIPT
     */
    public String getUPDATE_SCRIPT() {
        return UPDATE_SCRIPT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DF_HD_FILE_GROUP.UPDATE_SCRIPT
     *
     * @param UPDATE_SCRIPT the value for DF_HD_FILE_GROUP.UPDATE_SCRIPT
     */
    public void setUPDATE_SCRIPT(String UPDATE_SCRIPT) {
        this.UPDATE_SCRIPT = UPDATE_SCRIPT == null ? null : UPDATE_SCRIPT.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DF_HD_FILE_GROUP.MIGRATION_STRUCT
     *
     * @return the value of DF_HD_FILE_GROUP.MIGRATION_STRUCT
     */
    public String getMIGRATION_STRUCT() {
        return MIGRATION_STRUCT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DF_HD_FILE_GROUP.MIGRATION_STRUCT
     *
     * @param MIGRATION_STRUCT the value for DF_HD_FILE_GROUP.MIGRATION_STRUCT
     */
    public void setMIGRATION_STRUCT(String MIGRATION_STRUCT) {
        this.MIGRATION_STRUCT = MIGRATION_STRUCT == null ? null : MIGRATION_STRUCT.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DF_HD_FILE_GROUP.FILE_NAME_SQL
     *
     * @return the value of DF_HD_FILE_GROUP.FILE_NAME_SQL
     */
    public String getFILE_NAME_SQL() {
        return FILE_NAME_SQL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DF_HD_FILE_GROUP.FILE_NAME_SQL
     *
     * @param FILE_NAME_SQL the value for DF_HD_FILE_GROUP.FILE_NAME_SQL
     */
    public void setFILE_NAME_SQL(String FILE_NAME_SQL) {
        this.FILE_NAME_SQL = FILE_NAME_SQL == null ? null : FILE_NAME_SQL.trim();
    }
}