package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class DF_SQL_INP_PARMVO extends DF_SQL_INP_PARMVOKey {
    /**
     * This field corresponds to the database column DF_SQL_INP_PARM.INP_PARM_NAME
     */
    private String INP_PARM_NAME;

    /**
     * This field corresponds to the database column DF_SQL_INP_PARM.INP_PARM_DSC
     */
    private String INP_PARM_DSC;

    /**
     * This field corresponds to the database column DF_SQL_INP_PARM.INP_PARM_TYPE
     */
    private String INP_PARM_TYPE;

    /**
     * This field corresponds to the database column DF_SQL_INP_PARM.FILE_PARM_NO
     */
    private BigDecimal FILE_PARM_NO;

    /**
     * This field corresponds to the database column DF_SQL_INP_PARM.TAG_DEPEND_FLAG
     */
    private String TAG_DEPEND_FLAG;

    /**
     * This field corresponds to the database column DF_SQL_INP_PARM.VAR_TABLE_NAME
     */
    private String VAR_TABLE_NAME;

    /**
     * This field corresponds to the database column DF_SQL_INP_PARM.VAR_COL_NAME
     */
    private String VAR_COL_NAME;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DF_SQL_INP_PARM.INP_PARM_NAME
     *
     * @return the value of DF_SQL_INP_PARM.INP_PARM_NAME
     */
    public String getINP_PARM_NAME() {
        return INP_PARM_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DF_SQL_INP_PARM.INP_PARM_NAME
     *
     * @param INP_PARM_NAME the value for DF_SQL_INP_PARM.INP_PARM_NAME
     */
    public void setINP_PARM_NAME(String INP_PARM_NAME) {
        this.INP_PARM_NAME = INP_PARM_NAME == null ? null : INP_PARM_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DF_SQL_INP_PARM.INP_PARM_DSC
     *
     * @return the value of DF_SQL_INP_PARM.INP_PARM_DSC
     */
    public String getINP_PARM_DSC() {
        return INP_PARM_DSC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DF_SQL_INP_PARM.INP_PARM_DSC
     *
     * @param INP_PARM_DSC the value for DF_SQL_INP_PARM.INP_PARM_DSC
     */
    public void setINP_PARM_DSC(String INP_PARM_DSC) {
        this.INP_PARM_DSC = INP_PARM_DSC == null ? null : INP_PARM_DSC.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DF_SQL_INP_PARM.INP_PARM_TYPE
     *
     * @return the value of DF_SQL_INP_PARM.INP_PARM_TYPE
     */
    public String getINP_PARM_TYPE() {
        return INP_PARM_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DF_SQL_INP_PARM.INP_PARM_TYPE
     *
     * @param INP_PARM_TYPE the value for DF_SQL_INP_PARM.INP_PARM_TYPE
     */
    public void setINP_PARM_TYPE(String INP_PARM_TYPE) {
        this.INP_PARM_TYPE = INP_PARM_TYPE == null ? null : INP_PARM_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DF_SQL_INP_PARM.FILE_PARM_NO
     *
     * @return the value of DF_SQL_INP_PARM.FILE_PARM_NO
     */
    public BigDecimal getFILE_PARM_NO() {
        return FILE_PARM_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DF_SQL_INP_PARM.FILE_PARM_NO
     *
     * @param FILE_PARM_NO the value for DF_SQL_INP_PARM.FILE_PARM_NO
     */
    public void setFILE_PARM_NO(BigDecimal FILE_PARM_NO) {
        this.FILE_PARM_NO = FILE_PARM_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DF_SQL_INP_PARM.TAG_DEPEND_FLAG
     *
     * @return the value of DF_SQL_INP_PARM.TAG_DEPEND_FLAG
     */
    public String getTAG_DEPEND_FLAG() {
        return TAG_DEPEND_FLAG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DF_SQL_INP_PARM.TAG_DEPEND_FLAG
     *
     * @param TAG_DEPEND_FLAG the value for DF_SQL_INP_PARM.TAG_DEPEND_FLAG
     */
    public void setTAG_DEPEND_FLAG(String TAG_DEPEND_FLAG) {
        this.TAG_DEPEND_FLAG = TAG_DEPEND_FLAG == null ? null : TAG_DEPEND_FLAG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DF_SQL_INP_PARM.VAR_TABLE_NAME
     *
     * @return the value of DF_SQL_INP_PARM.VAR_TABLE_NAME
     */
    public String getVAR_TABLE_NAME() {
        return VAR_TABLE_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DF_SQL_INP_PARM.VAR_TABLE_NAME
     *
     * @param VAR_TABLE_NAME the value for DF_SQL_INP_PARM.VAR_TABLE_NAME
     */
    public void setVAR_TABLE_NAME(String VAR_TABLE_NAME) {
        this.VAR_TABLE_NAME = VAR_TABLE_NAME == null ? null : VAR_TABLE_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DF_SQL_INP_PARM.VAR_COL_NAME
     *
     * @return the value of DF_SQL_INP_PARM.VAR_COL_NAME
     */
    public String getVAR_COL_NAME() {
        return VAR_COL_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DF_SQL_INP_PARM.VAR_COL_NAME
     *
     * @param VAR_COL_NAME the value for DF_SQL_INP_PARM.VAR_COL_NAME
     */
    public void setVAR_COL_NAME(String VAR_COL_NAME) {
        this.VAR_COL_NAME = VAR_COL_NAME == null ? null : VAR_COL_NAME.trim();
    }
}