package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class DMS_AXS_MAPVO extends DMS_AXS_MAPVOKey
{

	/**
	 * This field corresponds to the database column DMS_AXS_MAP.INTEGRATION_ID
	 */
	private BigDecimal INTEGRATION_ID;

	/**
	 * This field corresponds to the database column DMS_AXS_MAP.INDEX_NUM
	 */
	private BigDecimal INDEX_NUM;

	private Date DATE_UPDATED;

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column DMS_AXS_MAP.INDEX_NUM
	 *
	 * @return the value of DMS_AXS_MAP.INDEX_NUM
	 */
	public BigDecimal getINDEX_NUM()
	{
		return INDEX_NUM;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column DMS_AXS_MAP.INDEX_NUM
	 *
	 * @param INDEX_NUM the value for DMS_AXS_MAP.INDEX_NUM
	 */
	public void setINDEX_NUM(BigDecimal INDEX_NUM)
	{
		this.INDEX_NUM = INDEX_NUM;
	}

	public Date getDATE_UPDATED()
	{
		return DATE_UPDATED;
	}

	public void setDATE_UPDATED(Date dATE_UPDATED)
	{
		DATE_UPDATED = dATE_UPDATED;
	}

	/**
	* This method was generated by MyBatis Generator.
	* This method returns the value of the database column DMS_AXS_MAP.INTEGRATION_ID
	*
	* @return the value of DMS_AXS_MAP.INTEGRATION_ID
	*/
	public BigDecimal getINTEGRATION_ID()
	{
		return INTEGRATION_ID;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column DMS_AXS_MAP.INTEGRATION_ID
	 *
	 * @param INTEGRATION_ID the value for DMS_AXS_MAP.INTEGRATION_ID
	 */
	public void setINTEGRATION_ID(BigDecimal INTEGRATION_ID)
	{
		this.INTEGRATION_ID = INTEGRATION_ID;
	}
}
