package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class EMP_PHOTOSVO extends BaseVO {
    /**
     * This field corresponds to the database column EMP_PHOTOS.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column EMP_PHOTOS.EMPLOYEE_ID
     */
    private BigDecimal EMPLOYEE_ID;

    /**
     * This field corresponds to the database column EMP_PHOTOS.FILE_TYPE
     */
    private String FILE_TYPE;

    /**
     * This field corresponds to the database column EMP_PHOTOS.EMP_PHOTO
     */
    private byte[] EMP_PHOTO;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMP_PHOTOS.COMP_CODE
     *
     * @return the value of EMP_PHOTOS.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMP_PHOTOS.COMP_CODE
     *
     * @param COMP_CODE the value for EMP_PHOTOS.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMP_PHOTOS.EMPLOYEE_ID
     *
     * @return the value of EMP_PHOTOS.EMPLOYEE_ID
     */
    public BigDecimal getEMPLOYEE_ID() {
        return EMPLOYEE_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMP_PHOTOS.EMPLOYEE_ID
     *
     * @param EMPLOYEE_ID the value for EMP_PHOTOS.EMPLOYEE_ID
     */
    public void setEMPLOYEE_ID(BigDecimal EMPLOYEE_ID) {
        this.EMPLOYEE_ID = EMPLOYEE_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMP_PHOTOS.FILE_TYPE
     *
     * @return the value of EMP_PHOTOS.FILE_TYPE
     */
    public String getFILE_TYPE() {
        return FILE_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMP_PHOTOS.FILE_TYPE
     *
     * @param FILE_TYPE the value for EMP_PHOTOS.FILE_TYPE
     */
    public void setFILE_TYPE(String FILE_TYPE) {
        this.FILE_TYPE = FILE_TYPE == null ? null : FILE_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMP_PHOTOS.EMP_PHOTO
     *
     * @return the value of EMP_PHOTOS.EMP_PHOTO
     */
    public byte[] getEMP_PHOTO() {
        return EMP_PHOTO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMP_PHOTOS.EMP_PHOTO
     *
     * @param EMP_PHOTO the value for EMP_PHOTOS.EMP_PHOTO
     */
    public void setEMP_PHOTO(byte[] EMP_PHOTO) {
        this.EMP_PHOTO = EMP_PHOTO;
    }
}