package com.path.dbmaps.vo;

public class EOD_ENG_MGMTVOWithBLOBs extends EOD_ENG_MGMTVO {
    /**
     * This field corresponds to the database column EOD_ENG_MGMT.STATEMENT
     */
    private String STATEMENT;

    /**
     * This field corresponds to the database column EOD_ENG_MGMT.ERROR_MESSAGE
     */
    private String ERROR_MESSAGE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EOD_ENG_MGMT.STATEMENT
     *
     * @return the value of EOD_ENG_MGMT.STATEMENT
     */
    public String getSTATEMENT() {
        return STATEMENT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EOD_ENG_MGMT.STATEMENT
     *
     * @param STATEMENT the value for EOD_ENG_MGMT.STATEMENT
     */
    public void setSTATEMENT(String STATEMENT) {
        this.STATEMENT = STATEMENT == null ? null : STATEMENT.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EOD_ENG_MGMT.ERROR_MESSAGE
     *
     * @return the value of EOD_ENG_MGMT.ERROR_MESSAGE
     */
    public String getERROR_MESSAGE() {
        return ERROR_MESSAGE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EOD_ENG_MGMT.ERROR_MESSAGE
     *
     * @param ERROR_MESSAGE the value for EOD_ENG_MGMT.ERROR_MESSAGE
     */
    public void setERROR_MESSAGE(String ERROR_MESSAGE) {
        this.ERROR_MESSAGE = ERROR_MESSAGE == null ? null : ERROR_MESSAGE.trim();
    }
}