package com.path.dbmaps.vo;

public class EOD_ENG_MGMT_PARENTVOWithBLOBs extends EOD_ENG_MGMT_PARENTVO {
    /**
     * This field corresponds to the database column EOD_ENG_MGMT_PARENT.ERROR_MESSAGE
     */
    private String ERROR_MESSAGE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EOD_ENG_MGMT_PARENT.ERROR_MESSAGE
     *
     * @return the value of EOD_ENG_MGMT_PARENT.ERROR_MESSAGE
     */
    public String getERROR_MESSAGE() {
        return ERROR_MESSAGE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EOD_ENG_MGMT_PARENT.ERROR_MESSAGE
     *
     * @param ERROR_MESSAGE the value for EOD_ENG_MGMT_PARENT.ERROR_MESSAGE
     */
    public void setERROR_MESSAGE(String ERROR_MESSAGE) {
        this.ERROR_MESSAGE = ERROR_MESSAGE == null ? null : ERROR_MESSAGE.trim();
    }
}