package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.util.Date;

public class EOD_SCHEDULE_LISTENERVO extends BaseVO {
    /**
     * This field corresponds to the database column EOD_SCHEDULE_LISTENER.MACHINE_NAME
     */
    private String MACHINE_NAME;

    /**
     * This field corresponds to the database column EOD_SCHEDULE_LISTENER.DATE_UPDATED
     */
    private Date DATE_UPDATED;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EOD_SCHEDULE_LISTENER.MACHINE_NAME
     *
     * @return the value of EOD_SCHEDULE_LISTENER.MACHINE_NAME
     */
    public String getMACHINE_NAME() {
        return MACHINE_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EOD_SCHEDULE_LISTENER.MACHINE_NAME
     *
     * @param MACHINE_NAME the value for EOD_SCHEDULE_LISTENER.MACHINE_NAME
     */
    public void setMACHINE_NAME(String MACHINE_NAME) {
        this.MACHINE_NAME = MACHINE_NAME == null ? null : MACHINE_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EOD_SCHEDULE_LISTENER.DATE_UPDATED
     *
     * @return the value of EOD_SCHEDULE_LISTENER.DATE_UPDATED
     */
    public Date getDATE_UPDATED() {
        return DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EOD_SCHEDULE_LISTENER.DATE_UPDATED
     *
     * @param DATE_UPDATED the value for EOD_SCHEDULE_LISTENER.DATE_UPDATED
     */
    public void setDATE_UPDATED(Date DATE_UPDATED) {
        this.DATE_UPDATED = DATE_UPDATED;
    }
}