package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class FAS_SUPPLIERSVOKey extends BaseVO {
    /**
     * This field corresponds to the database column FAS_SUPPLIERS.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column FAS_SUPPLIERS.SUPP_CODE
     */
    private BigDecimal SUPP_CODE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FAS_SUPPLIERS.COMP_CODE
     *
     * @return the value of FAS_SUPPLIERS.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FAS_SUPPLIERS.COMP_CODE
     *
     * @param COMP_CODE the value for FAS_SUPPLIERS.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FAS_SUPPLIERS.SUPP_CODE
     *
     * @return the value of FAS_SUPPLIERS.SUPP_CODE
     */
    public BigDecimal getSUPP_CODE() {
        return SUPP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FAS_SUPPLIERS.SUPP_CODE
     *
     * @param SUPP_CODE the value for FAS_SUPPLIERS.SUPP_CODE
     */
    public void setSUPP_CODE(BigDecimal SUPP_CODE) {
        this.SUPP_CODE = SUPP_CODE;
    }
}