package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class FASLOCVO extends FASLOCVOKey {
    /**
     * This field corresponds to the database column FASLOC.BRIEF_DESC_ENG
     */
    private String BRIEF_DESC_ENG;

    /**
     * This field corresponds to the database column FASLOC.LONG_DESC_ENG
     */
    private String LONG_DESC_ENG;

    /**
     * This field corresponds to the database column FASLOC.BRIEF_DESC_ARAB
     */
    private String BRIEF_DESC_ARAB;

    /**
     * This field corresponds to the database column FASLOC.LONG_DESC_ARAB
     */
    private String LONG_DESC_ARAB;

    /**
     * This field corresponds to the database column FASLOC.WH_CODE
     */
    private BigDecimal WH_CODE;

    /**
     * This field corresponds to the database column FASLOC.DIV_CODE
     */
    private BigDecimal DIV_CODE;

    /**
     * This field corresponds to the database column FASLOC.DEPT_CODE
     */
    private BigDecimal DEPT_CODE;

    /**
     * This field corresponds to the database column FASLOC.OVERSEER_NAME
     */
    private String OVERSEER_NAME;

    /**
     * This field corresponds to the database column FASLOC.ASSET_VALUE_GL
     */
    private BigDecimal ASSET_VALUE_GL;

    /**
     * This field corresponds to the database column FASLOC.ASSET_VALUE_SUB
     */
    private BigDecimal ASSET_VALUE_SUB;

    /**
     * This field corresponds to the database column FASLOC.ASSET_VALUE_SL_NO
     */
    private BigDecimal ASSET_VALUE_SL_NO;

    /**
     * This field corresponds to the database column FASLOC.ACCUM_DEPR_GL
     */
    private BigDecimal ACCUM_DEPR_GL;

    /**
     * This field corresponds to the database column FASLOC.ACCUM_DEPR_SUB
     */
    private BigDecimal ACCUM_DEPR_SUB;

    /**
     * This field corresponds to the database column FASLOC.ACCUM_DEPR_SL_NO
     */
    private BigDecimal ACCUM_DEPR_SL_NO;

    /**
     * This field corresponds to the database column FASLOC.BRANCH_CODE
     */
    private BigDecimal BRANCH_CODE;

    /**
     * This field corresponds to the database column FASLOC.UNIT_CODE
     */
    private BigDecimal UNIT_CODE;

    /**
     * This field corresponds to the database column FASLOC.INVENTORY
     */
    private BigDecimal INVENTORY;

    /**
     * This field corresponds to the database column FASLOC.DATE_UPDATED
     */
    private Date DATE_UPDATED;

    /**
     * This field corresponds to the database column FASLOC.BARCODE
     */
    private String BARCODE;

    /**
     * This field corresponds to the database column FASLOC.BARCODE_LABEL
     */
    private String BARCODE_LABEL;

    /**
     * This field corresponds to the database column FASLOC.BARCODE_LABEL_DESC
     */
    private String BARCODE_LABEL_DESC;

    /**
     * This field corresponds to the database column FASLOC.BARCODE_LABEL_P1
     */
    private String BARCODE_LABEL_P1;

    /**
     * This field corresponds to the database column FASLOC.BARCODE_LABEL_P1_DESC
     */
    private String BARCODE_LABEL_P1_DESC;

    /**
     * This field corresponds to the database column FASLOC.BARCODE_LABEL_P2
     */
    private String BARCODE_LABEL_P2;

    /**
     * This field corresponds to the database column FASLOC.BARCODE_LABEL_P2_DESC
     */
    private String BARCODE_LABEL_P2_DESC;

    /**
     * This field corresponds to the database column FASLOC.BARCODE_LABEL_P3
     */
    private String BARCODE_LABEL_P3;

    /**
     * This field corresponds to the database column FASLOC.BARCODE_LABEL_P3_DESC
     */
    private String BARCODE_LABEL_P3_DESC;

    /**
     * This field corresponds to the database column FASLOC.BARCODE_LABEL_P4
     */
    private String BARCODE_LABEL_P4;

    /**
     * This field corresponds to the database column FASLOC.BARCODE_LABEL_P4_DESC
     */
    private String BARCODE_LABEL_P4_DESC;

    /**
     * This field corresponds to the database column FASLOC.LOC_TYPE
     */
    private BigDecimal LOC_TYPE;

    /**
     * This field corresponds to the database column FASLOC.PARENT_LOC
     */
    private BigDecimal PARENT_LOC;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FASLOC.BRIEF_DESC_ENG
     *
     * @return the value of FASLOC.BRIEF_DESC_ENG
     */
    public String getBRIEF_DESC_ENG() {
        return BRIEF_DESC_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FASLOC.BRIEF_DESC_ENG
     *
     * @param BRIEF_DESC_ENG the value for FASLOC.BRIEF_DESC_ENG
     */
    public void setBRIEF_DESC_ENG(String BRIEF_DESC_ENG) {
        this.BRIEF_DESC_ENG = BRIEF_DESC_ENG == null ? null : BRIEF_DESC_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FASLOC.LONG_DESC_ENG
     *
     * @return the value of FASLOC.LONG_DESC_ENG
     */
    public String getLONG_DESC_ENG() {
        return LONG_DESC_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FASLOC.LONG_DESC_ENG
     *
     * @param LONG_DESC_ENG the value for FASLOC.LONG_DESC_ENG
     */
    public void setLONG_DESC_ENG(String LONG_DESC_ENG) {
        this.LONG_DESC_ENG = LONG_DESC_ENG == null ? null : LONG_DESC_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FASLOC.BRIEF_DESC_ARAB
     *
     * @return the value of FASLOC.BRIEF_DESC_ARAB
     */
    public String getBRIEF_DESC_ARAB() {
        return BRIEF_DESC_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FASLOC.BRIEF_DESC_ARAB
     *
     * @param BRIEF_DESC_ARAB the value for FASLOC.BRIEF_DESC_ARAB
     */
    public void setBRIEF_DESC_ARAB(String BRIEF_DESC_ARAB) {
        this.BRIEF_DESC_ARAB = BRIEF_DESC_ARAB == null ? null : BRIEF_DESC_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FASLOC.LONG_DESC_ARAB
     *
     * @return the value of FASLOC.LONG_DESC_ARAB
     */
    public String getLONG_DESC_ARAB() {
        return LONG_DESC_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FASLOC.LONG_DESC_ARAB
     *
     * @param LONG_DESC_ARAB the value for FASLOC.LONG_DESC_ARAB
     */
    public void setLONG_DESC_ARAB(String LONG_DESC_ARAB) {
        this.LONG_DESC_ARAB = LONG_DESC_ARAB == null ? null : LONG_DESC_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FASLOC.WH_CODE
     *
     * @return the value of FASLOC.WH_CODE
     */
    public BigDecimal getWH_CODE() {
        return WH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FASLOC.WH_CODE
     *
     * @param WH_CODE the value for FASLOC.WH_CODE
     */
    public void setWH_CODE(BigDecimal WH_CODE) {
        this.WH_CODE = WH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FASLOC.DIV_CODE
     *
     * @return the value of FASLOC.DIV_CODE
     */
    public BigDecimal getDIV_CODE() {
        return DIV_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FASLOC.DIV_CODE
     *
     * @param DIV_CODE the value for FASLOC.DIV_CODE
     */
    public void setDIV_CODE(BigDecimal DIV_CODE) {
        this.DIV_CODE = DIV_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FASLOC.DEPT_CODE
     *
     * @return the value of FASLOC.DEPT_CODE
     */
    public BigDecimal getDEPT_CODE() {
        return DEPT_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FASLOC.DEPT_CODE
     *
     * @param DEPT_CODE the value for FASLOC.DEPT_CODE
     */
    public void setDEPT_CODE(BigDecimal DEPT_CODE) {
        this.DEPT_CODE = DEPT_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FASLOC.OVERSEER_NAME
     *
     * @return the value of FASLOC.OVERSEER_NAME
     */
    public String getOVERSEER_NAME() {
        return OVERSEER_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FASLOC.OVERSEER_NAME
     *
     * @param OVERSEER_NAME the value for FASLOC.OVERSEER_NAME
     */
    public void setOVERSEER_NAME(String OVERSEER_NAME) {
        this.OVERSEER_NAME = OVERSEER_NAME == null ? null : OVERSEER_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FASLOC.ASSET_VALUE_GL
     *
     * @return the value of FASLOC.ASSET_VALUE_GL
     */
    public BigDecimal getASSET_VALUE_GL() {
        return ASSET_VALUE_GL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FASLOC.ASSET_VALUE_GL
     *
     * @param ASSET_VALUE_GL the value for FASLOC.ASSET_VALUE_GL
     */
    public void setASSET_VALUE_GL(BigDecimal ASSET_VALUE_GL) {
        this.ASSET_VALUE_GL = ASSET_VALUE_GL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FASLOC.ASSET_VALUE_SUB
     *
     * @return the value of FASLOC.ASSET_VALUE_SUB
     */
    public BigDecimal getASSET_VALUE_SUB() {
        return ASSET_VALUE_SUB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FASLOC.ASSET_VALUE_SUB
     *
     * @param ASSET_VALUE_SUB the value for FASLOC.ASSET_VALUE_SUB
     */
    public void setASSET_VALUE_SUB(BigDecimal ASSET_VALUE_SUB) {
        this.ASSET_VALUE_SUB = ASSET_VALUE_SUB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FASLOC.ASSET_VALUE_SL_NO
     *
     * @return the value of FASLOC.ASSET_VALUE_SL_NO
     */
    public BigDecimal getASSET_VALUE_SL_NO() {
        return ASSET_VALUE_SL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FASLOC.ASSET_VALUE_SL_NO
     *
     * @param ASSET_VALUE_SL_NO the value for FASLOC.ASSET_VALUE_SL_NO
     */
    public void setASSET_VALUE_SL_NO(BigDecimal ASSET_VALUE_SL_NO) {
        this.ASSET_VALUE_SL_NO = ASSET_VALUE_SL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FASLOC.ACCUM_DEPR_GL
     *
     * @return the value of FASLOC.ACCUM_DEPR_GL
     */
    public BigDecimal getACCUM_DEPR_GL() {
        return ACCUM_DEPR_GL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FASLOC.ACCUM_DEPR_GL
     *
     * @param ACCUM_DEPR_GL the value for FASLOC.ACCUM_DEPR_GL
     */
    public void setACCUM_DEPR_GL(BigDecimal ACCUM_DEPR_GL) {
        this.ACCUM_DEPR_GL = ACCUM_DEPR_GL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FASLOC.ACCUM_DEPR_SUB
     *
     * @return the value of FASLOC.ACCUM_DEPR_SUB
     */
    public BigDecimal getACCUM_DEPR_SUB() {
        return ACCUM_DEPR_SUB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FASLOC.ACCUM_DEPR_SUB
     *
     * @param ACCUM_DEPR_SUB the value for FASLOC.ACCUM_DEPR_SUB
     */
    public void setACCUM_DEPR_SUB(BigDecimal ACCUM_DEPR_SUB) {
        this.ACCUM_DEPR_SUB = ACCUM_DEPR_SUB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FASLOC.ACCUM_DEPR_SL_NO
     *
     * @return the value of FASLOC.ACCUM_DEPR_SL_NO
     */
    public BigDecimal getACCUM_DEPR_SL_NO() {
        return ACCUM_DEPR_SL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FASLOC.ACCUM_DEPR_SL_NO
     *
     * @param ACCUM_DEPR_SL_NO the value for FASLOC.ACCUM_DEPR_SL_NO
     */
    public void setACCUM_DEPR_SL_NO(BigDecimal ACCUM_DEPR_SL_NO) {
        this.ACCUM_DEPR_SL_NO = ACCUM_DEPR_SL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FASLOC.BRANCH_CODE
     *
     * @return the value of FASLOC.BRANCH_CODE
     */
    public BigDecimal getBRANCH_CODE() {
        return BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FASLOC.BRANCH_CODE
     *
     * @param BRANCH_CODE the value for FASLOC.BRANCH_CODE
     */
    public void setBRANCH_CODE(BigDecimal BRANCH_CODE) {
        this.BRANCH_CODE = BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FASLOC.UNIT_CODE
     *
     * @return the value of FASLOC.UNIT_CODE
     */
    public BigDecimal getUNIT_CODE() {
        return UNIT_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FASLOC.UNIT_CODE
     *
     * @param UNIT_CODE the value for FASLOC.UNIT_CODE
     */
    public void setUNIT_CODE(BigDecimal UNIT_CODE) {
        this.UNIT_CODE = UNIT_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FASLOC.INVENTORY
     *
     * @return the value of FASLOC.INVENTORY
     */
    public BigDecimal getINVENTORY() {
        return INVENTORY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FASLOC.INVENTORY
     *
     * @param INVENTORY the value for FASLOC.INVENTORY
     */
    public void setINVENTORY(BigDecimal INVENTORY) {
        this.INVENTORY = INVENTORY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FASLOC.DATE_UPDATED
     *
     * @return the value of FASLOC.DATE_UPDATED
     */
    public Date getDATE_UPDATED() {
        return DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FASLOC.DATE_UPDATED
     *
     * @param DATE_UPDATED the value for FASLOC.DATE_UPDATED
     */
    public void setDATE_UPDATED(Date DATE_UPDATED) {
        this.DATE_UPDATED = DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FASLOC.BARCODE
     *
     * @return the value of FASLOC.BARCODE
     */
    public String getBARCODE() {
        return BARCODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FASLOC.BARCODE
     *
     * @param BARCODE the value for FASLOC.BARCODE
     */
    public void setBARCODE(String BARCODE) {
        this.BARCODE = BARCODE == null ? null : BARCODE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FASLOC.BARCODE_LABEL
     *
     * @return the value of FASLOC.BARCODE_LABEL
     */
    public String getBARCODE_LABEL() {
        return BARCODE_LABEL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FASLOC.BARCODE_LABEL
     *
     * @param BARCODE_LABEL the value for FASLOC.BARCODE_LABEL
     */
    public void setBARCODE_LABEL(String BARCODE_LABEL) {
        this.BARCODE_LABEL = BARCODE_LABEL == null ? null : BARCODE_LABEL.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FASLOC.BARCODE_LABEL_DESC
     *
     * @return the value of FASLOC.BARCODE_LABEL_DESC
     */
    public String getBARCODE_LABEL_DESC() {
        return BARCODE_LABEL_DESC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FASLOC.BARCODE_LABEL_DESC
     *
     * @param BARCODE_LABEL_DESC the value for FASLOC.BARCODE_LABEL_DESC
     */
    public void setBARCODE_LABEL_DESC(String BARCODE_LABEL_DESC) {
        this.BARCODE_LABEL_DESC = BARCODE_LABEL_DESC == null ? null : BARCODE_LABEL_DESC.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FASLOC.BARCODE_LABEL_P1
     *
     * @return the value of FASLOC.BARCODE_LABEL_P1
     */
    public String getBARCODE_LABEL_P1() {
        return BARCODE_LABEL_P1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FASLOC.BARCODE_LABEL_P1
     *
     * @param BARCODE_LABEL_P1 the value for FASLOC.BARCODE_LABEL_P1
     */
    public void setBARCODE_LABEL_P1(String BARCODE_LABEL_P1) {
        this.BARCODE_LABEL_P1 = BARCODE_LABEL_P1 == null ? null : BARCODE_LABEL_P1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FASLOC.BARCODE_LABEL_P1_DESC
     *
     * @return the value of FASLOC.BARCODE_LABEL_P1_DESC
     */
    public String getBARCODE_LABEL_P1_DESC() {
        return BARCODE_LABEL_P1_DESC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FASLOC.BARCODE_LABEL_P1_DESC
     *
     * @param BARCODE_LABEL_P1_DESC the value for FASLOC.BARCODE_LABEL_P1_DESC
     */
    public void setBARCODE_LABEL_P1_DESC(String BARCODE_LABEL_P1_DESC) {
        this.BARCODE_LABEL_P1_DESC = BARCODE_LABEL_P1_DESC == null ? null : BARCODE_LABEL_P1_DESC.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FASLOC.BARCODE_LABEL_P2
     *
     * @return the value of FASLOC.BARCODE_LABEL_P2
     */
    public String getBARCODE_LABEL_P2() {
        return BARCODE_LABEL_P2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FASLOC.BARCODE_LABEL_P2
     *
     * @param BARCODE_LABEL_P2 the value for FASLOC.BARCODE_LABEL_P2
     */
    public void setBARCODE_LABEL_P2(String BARCODE_LABEL_P2) {
        this.BARCODE_LABEL_P2 = BARCODE_LABEL_P2 == null ? null : BARCODE_LABEL_P2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FASLOC.BARCODE_LABEL_P2_DESC
     *
     * @return the value of FASLOC.BARCODE_LABEL_P2_DESC
     */
    public String getBARCODE_LABEL_P2_DESC() {
        return BARCODE_LABEL_P2_DESC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FASLOC.BARCODE_LABEL_P2_DESC
     *
     * @param BARCODE_LABEL_P2_DESC the value for FASLOC.BARCODE_LABEL_P2_DESC
     */
    public void setBARCODE_LABEL_P2_DESC(String BARCODE_LABEL_P2_DESC) {
        this.BARCODE_LABEL_P2_DESC = BARCODE_LABEL_P2_DESC == null ? null : BARCODE_LABEL_P2_DESC.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FASLOC.BARCODE_LABEL_P3
     *
     * @return the value of FASLOC.BARCODE_LABEL_P3
     */
    public String getBARCODE_LABEL_P3() {
        return BARCODE_LABEL_P3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FASLOC.BARCODE_LABEL_P3
     *
     * @param BARCODE_LABEL_P3 the value for FASLOC.BARCODE_LABEL_P3
     */
    public void setBARCODE_LABEL_P3(String BARCODE_LABEL_P3) {
        this.BARCODE_LABEL_P3 = BARCODE_LABEL_P3 == null ? null : BARCODE_LABEL_P3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FASLOC.BARCODE_LABEL_P3_DESC
     *
     * @return the value of FASLOC.BARCODE_LABEL_P3_DESC
     */
    public String getBARCODE_LABEL_P3_DESC() {
        return BARCODE_LABEL_P3_DESC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FASLOC.BARCODE_LABEL_P3_DESC
     *
     * @param BARCODE_LABEL_P3_DESC the value for FASLOC.BARCODE_LABEL_P3_DESC
     */
    public void setBARCODE_LABEL_P3_DESC(String BARCODE_LABEL_P3_DESC) {
        this.BARCODE_LABEL_P3_DESC = BARCODE_LABEL_P3_DESC == null ? null : BARCODE_LABEL_P3_DESC.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FASLOC.BARCODE_LABEL_P4
     *
     * @return the value of FASLOC.BARCODE_LABEL_P4
     */
    public String getBARCODE_LABEL_P4() {
        return BARCODE_LABEL_P4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FASLOC.BARCODE_LABEL_P4
     *
     * @param BARCODE_LABEL_P4 the value for FASLOC.BARCODE_LABEL_P4
     */
    public void setBARCODE_LABEL_P4(String BARCODE_LABEL_P4) {
        this.BARCODE_LABEL_P4 = BARCODE_LABEL_P4 == null ? null : BARCODE_LABEL_P4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FASLOC.BARCODE_LABEL_P4_DESC
     *
     * @return the value of FASLOC.BARCODE_LABEL_P4_DESC
     */
    public String getBARCODE_LABEL_P4_DESC() {
        return BARCODE_LABEL_P4_DESC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FASLOC.BARCODE_LABEL_P4_DESC
     *
     * @param BARCODE_LABEL_P4_DESC the value for FASLOC.BARCODE_LABEL_P4_DESC
     */
    public void setBARCODE_LABEL_P4_DESC(String BARCODE_LABEL_P4_DESC) {
        this.BARCODE_LABEL_P4_DESC = BARCODE_LABEL_P4_DESC == null ? null : BARCODE_LABEL_P4_DESC.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FASLOC.LOC_TYPE
     *
     * @return the value of FASLOC.LOC_TYPE
     */
    public BigDecimal getLOC_TYPE() {
        return LOC_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FASLOC.LOC_TYPE
     *
     * @param LOC_TYPE the value for FASLOC.LOC_TYPE
     */
    public void setLOC_TYPE(BigDecimal LOC_TYPE) {
        this.LOC_TYPE = LOC_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FASLOC.PARENT_LOC
     *
     * @return the value of FASLOC.PARENT_LOC
     */
    public BigDecimal getPARENT_LOC() {
        return PARENT_LOC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FASLOC.PARENT_LOC
     *
     * @param PARENT_LOC the value for FASLOC.PARENT_LOC
     */
    public void setPARENT_LOC(BigDecimal PARENT_LOC) {
        this.PARENT_LOC = PARENT_LOC;
    }
}