package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class FMS_DEV_LIMITVO extends FMS_DEV_LIMITVOKey
{
    /**
     * This field corresponds to the database column FMS_DEV_LIMIT.PROJECT_DESC
     */
    private String PROJECT_DESC;

    /**
     * This field corresponds to the database column FMS_DEV_LIMIT.CURRENCY
     */
    private BigDecimal CURRENCY;

    /**
     * This field corresponds to the database column FMS_DEV_LIMIT.LIMIT
     */
    private BigDecimal LIMIT;

    /**
     * This field corresponds to the database column FMS_DEV_LIMIT.UTILIZED
     */
    private BigDecimal UTILIZED;

    /**
     * This field corresponds to the database column FMS_DEV_LIMIT.REMAINING
     */
    private BigDecimal REMAINING;

    /**
     * This field corresponds to the database column FMS_DEV_LIMIT.AREA_TYPE
     */
    private String AREA_TYPE;

    /**
     * This field corresponds to the database column FMS_DEV_LIMIT.YIELD
     */
    private BigDecimal YIELD;

    /**
     * This field corresponds to the database column FMS_DEV_LIMIT.SECTOR
     */
    private String SECTOR;

    private Date DATE_UPDATED;

    /**
     * This field corresponds to the database column FMSAPPL.UPDATED_BY
     */
    private String UPDATED_BY;

    public Date getDATE_UPDATED()
    {
	return DATE_UPDATED;
    }

    public void setDATE_UPDATED(Date dATE_UPDATED)
    {
	DATE_UPDATED = dATE_UPDATED;
    }

    public String getUPDATED_BY()
    {
	return UPDATED_BY;
    }

    public void setUPDATED_BY(String uPDATED_BY)
    {
	UPDATED_BY = uPDATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column FMS_DEV_LIMIT.PROJECT_DESC
     *
     * @return the value of FMS_DEV_LIMIT.PROJECT_DESC
     */
    public String getPROJECT_DESC()
    {
	return PROJECT_DESC;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column FMS_DEV_LIMIT.PROJECT_DESC
     *
     * @param PROJECT_DESC the value for FMS_DEV_LIMIT.PROJECT_DESC
     */
    public void setPROJECT_DESC(String PROJECT_DESC)
    {
	this.PROJECT_DESC = PROJECT_DESC == null ? null : PROJECT_DESC.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column FMS_DEV_LIMIT.CURRENCY
     *
     * @return the value of FMS_DEV_LIMIT.CURRENCY
     */
    public BigDecimal getCURRENCY()
    {
	return CURRENCY;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column FMS_DEV_LIMIT.CURRENCY
     *
     * @param CURRENCY the value for FMS_DEV_LIMIT.CURRENCY
     */
    public void setCURRENCY(BigDecimal CURRENCY)
    {
	this.CURRENCY = CURRENCY;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column FMS_DEV_LIMIT.LIMIT
     *
     * @return the value of FMS_DEV_LIMIT.LIMIT
     */
    public BigDecimal getLIMIT()
    {
	return LIMIT;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column FMS_DEV_LIMIT.LIMIT
     *
     * @param LIMIT the value for FMS_DEV_LIMIT.LIMIT
     */
    public void setLIMIT(BigDecimal LIMIT)
    {
	this.LIMIT = LIMIT;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column FMS_DEV_LIMIT.UTILIZED
     *
     * @return the value of FMS_DEV_LIMIT.UTILIZED
     */
    public BigDecimal getUTILIZED()
    {
	return UTILIZED;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column FMS_DEV_LIMIT.UTILIZED
     *
     * @param UTILIZED the value for FMS_DEV_LIMIT.UTILIZED
     */
    public void setUTILIZED(BigDecimal UTILIZED)
    {
	this.UTILIZED = UTILIZED;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column FMS_DEV_LIMIT.REMAINING
     *
     * @return the value of FMS_DEV_LIMIT.REMAINING
     */
    public BigDecimal getREMAINING()
    {
	return REMAINING;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column FMS_DEV_LIMIT.REMAINING
     *
     * @param REMAINING the value for FMS_DEV_LIMIT.REMAINING
     */
    public void setREMAINING(BigDecimal REMAINING)
    {
	this.REMAINING = REMAINING;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column FMS_DEV_LIMIT.AREA_TYPE
     *
     * @return the value of FMS_DEV_LIMIT.AREA_TYPE
     */
    public String getAREA_TYPE()
    {
	return AREA_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column FMS_DEV_LIMIT.AREA_TYPE
     *
     * @param AREA_TYPE the value for FMS_DEV_LIMIT.AREA_TYPE
     */
    public void setAREA_TYPE(String AREA_TYPE)
    {
	this.AREA_TYPE = AREA_TYPE == null ? null : AREA_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column FMS_DEV_LIMIT.YIELD
     *
     * @return the value of FMS_DEV_LIMIT.YIELD
     */
    public BigDecimal getYIELD()
    {
	return YIELD;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column FMS_DEV_LIMIT.YIELD
     *
     * @param YIELD the value for FMS_DEV_LIMIT.YIELD
     */
    public void setYIELD(BigDecimal YIELD)
    {
	this.YIELD = YIELD;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column FMS_DEV_LIMIT.SECTOR
     *
     * @return the value of FMS_DEV_LIMIT.SECTOR
     */
    public String getSECTOR()
    {
	return SECTOR;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column FMS_DEV_LIMIT.SECTOR
     *
     * @param SECTOR the value for FMS_DEV_LIMIT.SECTOR
     */
    public void setSECTOR(String SECTOR)
    {
	this.SECTOR = SECTOR == null ? null : SECTOR.trim();
    }
}