package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class FMS_FACILITY_RISK_RATING_HISTVO extends FMS_FACILITY_RISK_RATING_HISTVOKey
{
    /**
     * This field corresponds to the database column
     * FMS_FACILITY_RISK_RATING_HIST.FRR_SCORE
     */
    private BigDecimal FRR_SCORE;

    /**
     * This field corresponds to the database column
     * FMS_FACILITY_RISK_RATING_HIST.FRR_RATING
     */
    private String FRR_RATING;

    /**
     * This field corresponds to the database column
     * FMS_FACILITY_RISK_RATING_HIST.CREATED_BY
     */
    private String CREATED_BY;

    /**
     * This field corresponds to the database column
     * FMS_FACILITY_RISK_RATING_HIST.CREATED_DATE
     */
    private Date CREATED_DATE;

    /**
     * This field corresponds to the database column
     * FMS_FACILITY_RISK_RATING_HIST.MODIFIED_BY
     */
    private String MODIFIED_BY;

    /**
     * This field corresponds to the database column
     * FMS_FACILITY_RISK_RATING_HIST.MODIFIED_DATE
     */
    private Date MODIFIED_DATE;

    /**
     * This field corresponds to the database column
     * FMS_FACILITY_RISK_RATING_HIST.VALUE_DATE
     */
    private Date VALUE_DATE;

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column FMS_FACILITY_RISK_RATING_HIST.FRR_SCORE
     *
     * @return the value of FMS_FACILITY_RISK_RATING_HIST.FRR_SCORE
     */
    public BigDecimal getFRR_SCORE()
    {
	return FRR_SCORE;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column FMS_FACILITY_RISK_RATING_HIST.FRR_SCORE
     *
     * @param FRR_SCORE the value for FMS_FACILITY_RISK_RATING_HIST.FRR_SCORE
     */
    public void setFRR_SCORE(BigDecimal FRR_SCORE)
    {
	this.FRR_SCORE = FRR_SCORE;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column FMS_FACILITY_RISK_RATING_HIST.FRR_RATING
     *
     * @return the value of FMS_FACILITY_RISK_RATING_HIST.FRR_RATING
     */
    public String getFRR_RATING()
    {
	return FRR_RATING;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column FMS_FACILITY_RISK_RATING_HIST.FRR_RATING
     *
     * @param FRR_RATING the value for FMS_FACILITY_RISK_RATING_HIST.FRR_RATING
     */
    public void setFRR_RATING(String FRR_RATING)
    {
	this.FRR_RATING = FRR_RATING == null ? null : FRR_RATING.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column FMS_FACILITY_RISK_RATING_HIST.CREATED_BY
     *
     * @return the value of FMS_FACILITY_RISK_RATING_HIST.CREATED_BY
     */
    public String getCREATED_BY()
    {
	return CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column FMS_FACILITY_RISK_RATING_HIST.CREATED_BY
     *
     * @param CREATED_BY the value for FMS_FACILITY_RISK_RATING_HIST.CREATED_BY
     */
    public void setCREATED_BY(String CREATED_BY)
    {
	this.CREATED_BY = CREATED_BY == null ? null : CREATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column FMS_FACILITY_RISK_RATING_HIST.CREATED_DATE
     *
     * @return the value of FMS_FACILITY_RISK_RATING_HIST.CREATED_DATE
     */
    public Date getCREATED_DATE()
    {
	return CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column FMS_FACILITY_RISK_RATING_HIST.CREATED_DATE
     *
     * @param CREATED_DATE the value for
     *            FMS_FACILITY_RISK_RATING_HIST.CREATED_DATE
     */
    public void setCREATED_DATE(Date CREATED_DATE)
    {
	this.CREATED_DATE = CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column FMS_FACILITY_RISK_RATING_HIST.MODIFIED_BY
     *
     * @return the value of FMS_FACILITY_RISK_RATING_HIST.MODIFIED_BY
     */
    public String getMODIFIED_BY()
    {
	return MODIFIED_BY;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column FMS_FACILITY_RISK_RATING_HIST.MODIFIED_BY
     *
     * @param MODIFIED_BY the value for
     *            FMS_FACILITY_RISK_RATING_HIST.MODIFIED_BY
     */
    public void setMODIFIED_BY(String MODIFIED_BY)
    {
	this.MODIFIED_BY = MODIFIED_BY == null ? null : MODIFIED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column FMS_FACILITY_RISK_RATING_HIST.MODIFIED_DATE
     *
     * @return the value of FMS_FACILITY_RISK_RATING_HIST.MODIFIED_DATE
     */
    public Date getMODIFIED_DATE()
    {
	return MODIFIED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column FMS_FACILITY_RISK_RATING_HIST.MODIFIED_DATE
     *
     * @param MODIFIED_DATE the value for
     *            FMS_FACILITY_RISK_RATING_HIST.MODIFIED_DATE
     */
    public void setMODIFIED_DATE(Date MODIFIED_DATE)
    {
	this.MODIFIED_DATE = MODIFIED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column FMS_FACILITY_RISK_RATING_HIST.VALUE_DATE
     *
     * @return the value of FMS_FACILITY_RISK_RATING_HIST.VALUE_DATE
     */
    public Date getVALUE_DATE()
    {
	return VALUE_DATE;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column FMS_FACILITY_RISK_RATING_HIST.VALUE_DATE
     *
     * @param VALUE_DATE the value for FMS_FACILITY_RISK_RATING_HIST.VALUE_DATE
     */
    public void setVALUE_DATE(Date VALUE_DATE)
    {
	this.VALUE_DATE = VALUE_DATE;
    }
}