package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class FMS_APPL_RED_PERIODVO extends FMS_APPL_RED_PERIODVOKey {
    /**
     * This field corresponds to the database column FMS_APPL_RED_PERIOD.PERIOD_NBR
     */
    private BigDecimal PERIOD_NBR;

    /**
     * This field corresponds to the database column FMS_APPL_RED_PERIOD.PERIOD_TYPE
     */
    private String PERIOD_TYPE;

    /**
     * This field corresponds to the database column FMS_APPL_RED_PERIOD.FROM_DATE
     */
    private Date FROM_DATE;

    /**
     * This field corresponds to the database column FMS_APPL_RED_PERIOD.TO_DATE
     */
    private Date TO_DATE;

    /**
     * This field corresponds to the database column FMS_APPL_RED_PERIOD.AMOUNT
     */
    private BigDecimal AMOUNT;

    /**
     * This field corresponds to the database column FMS_APPL_RED_PERIOD.PERIODICITY_NBR
     */
    private BigDecimal PERIODICITY_NBR;

    /**
     * This field corresponds to the database column FMS_APPL_RED_PERIOD.PERIODICITY_TYPE
     */
    private String PERIODICITY_TYPE;

    /**
     * This field corresponds to the database column FMS_APPL_RED_PERIOD.NEXT_PERIOD_DATE
     */
    private Date NEXT_PERIOD_DATE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMS_APPL_RED_PERIOD.PERIOD_NBR
     *
     * @return the value of FMS_APPL_RED_PERIOD.PERIOD_NBR
     */
    public BigDecimal getPERIOD_NBR() {
        return PERIOD_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMS_APPL_RED_PERIOD.PERIOD_NBR
     *
     * @param PERIOD_NBR the value for FMS_APPL_RED_PERIOD.PERIOD_NBR
     */
    public void setPERIOD_NBR(BigDecimal PERIOD_NBR) {
        this.PERIOD_NBR = PERIOD_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMS_APPL_RED_PERIOD.PERIOD_TYPE
     *
     * @return the value of FMS_APPL_RED_PERIOD.PERIOD_TYPE
     */
    public String getPERIOD_TYPE() {
        return PERIOD_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMS_APPL_RED_PERIOD.PERIOD_TYPE
     *
     * @param PERIOD_TYPE the value for FMS_APPL_RED_PERIOD.PERIOD_TYPE
     */
    public void setPERIOD_TYPE(String PERIOD_TYPE) {
        this.PERIOD_TYPE = PERIOD_TYPE == null ? null : PERIOD_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMS_APPL_RED_PERIOD.FROM_DATE
     *
     * @return the value of FMS_APPL_RED_PERIOD.FROM_DATE
     */
    public Date getFROM_DATE() {
        return FROM_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMS_APPL_RED_PERIOD.FROM_DATE
     *
     * @param FROM_DATE the value for FMS_APPL_RED_PERIOD.FROM_DATE
     */
    public void setFROM_DATE(Date FROM_DATE) {
        this.FROM_DATE = FROM_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMS_APPL_RED_PERIOD.TO_DATE
     *
     * @return the value of FMS_APPL_RED_PERIOD.TO_DATE
     */
    public Date getTO_DATE() {
        return TO_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMS_APPL_RED_PERIOD.TO_DATE
     *
     * @param TO_DATE the value for FMS_APPL_RED_PERIOD.TO_DATE
     */
    public void setTO_DATE(Date TO_DATE) {
        this.TO_DATE = TO_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMS_APPL_RED_PERIOD.AMOUNT
     *
     * @return the value of FMS_APPL_RED_PERIOD.AMOUNT
     */
    public BigDecimal getAMOUNT() {
        return AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMS_APPL_RED_PERIOD.AMOUNT
     *
     * @param AMOUNT the value for FMS_APPL_RED_PERIOD.AMOUNT
     */
    public void setAMOUNT(BigDecimal AMOUNT) {
        this.AMOUNT = AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMS_APPL_RED_PERIOD.PERIODICITY_NBR
     *
     * @return the value of FMS_APPL_RED_PERIOD.PERIODICITY_NBR
     */
    public BigDecimal getPERIODICITY_NBR() {
        return PERIODICITY_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMS_APPL_RED_PERIOD.PERIODICITY_NBR
     *
     * @param PERIODICITY_NBR the value for FMS_APPL_RED_PERIOD.PERIODICITY_NBR
     */
    public void setPERIODICITY_NBR(BigDecimal PERIODICITY_NBR) {
        this.PERIODICITY_NBR = PERIODICITY_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMS_APPL_RED_PERIOD.PERIODICITY_TYPE
     *
     * @return the value of FMS_APPL_RED_PERIOD.PERIODICITY_TYPE
     */
    public String getPERIODICITY_TYPE() {
        return PERIODICITY_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMS_APPL_RED_PERIOD.PERIODICITY_TYPE
     *
     * @param PERIODICITY_TYPE the value for FMS_APPL_RED_PERIOD.PERIODICITY_TYPE
     */
    public void setPERIODICITY_TYPE(String PERIODICITY_TYPE) {
        this.PERIODICITY_TYPE = PERIODICITY_TYPE == null ? null : PERIODICITY_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMS_APPL_RED_PERIOD.NEXT_PERIOD_DATE
     *
     * @return the value of FMS_APPL_RED_PERIOD.NEXT_PERIOD_DATE
     */
    public Date getNEXT_PERIOD_DATE() {
        return NEXT_PERIOD_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMS_APPL_RED_PERIOD.NEXT_PERIOD_DATE
     *
     * @param NEXT_PERIOD_DATE the value for FMS_APPL_RED_PERIOD.NEXT_PERIOD_DATE
     */
    public void setNEXT_PERIOD_DATE(Date NEXT_PERIOD_DATE) {
        this.NEXT_PERIOD_DATE = NEXT_PERIOD_DATE;
    }
}