package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class FMS_PURPOSEFINANCE_CLASSVO extends FMS_PURPOSEFINANCE_CLASSVOKey {
    /**
     * This field corresponds to the database column FMS_PURPOSEFINANCE_CLASS.PRODUCTCLASS
     */
    private BigDecimal PRODUCTCLASS;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMS_PURPOSEFINANCE_CLASS.PRODUCTCLASS
     *
     * @return the value of FMS_PURPOSEFINANCE_CLASS.PRODUCTCLASS
     */
    public BigDecimal getPRODUCTCLASS() {
        return PRODUCTCLASS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMS_PURPOSEFINANCE_CLASS.PRODUCTCLASS
     *
     * @param PRODUCTCLASS the value for FMS_PURPOSEFINANCE_CLASS.PRODUCTCLASS
     */
    public void setPRODUCTCLASS(BigDecimal PRODUCTCLASS) {
        this.PRODUCTCLASS = PRODUCTCLASS;
    }
}