package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class FMS_CORP_PKGVO extends FMS_CORP_PKGVOKey {
    /**
     * This field corresponds to the database column FMS_CORP_PKG.CIF_NO
     */
    private BigDecimal CIF_NO;

    /**
     * This field corresponds to the database column FMS_CORP_PKG.STATUS
     */
    private String STATUS;

    /**
     * This field corresponds to the database column FMS_CORP_PKG.RET_AGE
     */
    private BigDecimal RET_AGE;

    /**
     * This field corresponds to the database column FMS_CORP_PKG.SUBSIDIZED
     */
    private String SUBSIDIZED;

    /**
     * This field corresponds to the database column FMS_CORP_PKG.REPAY_MODE
     */
    private String REPAY_MODE;

    /**
     * This field corresponds to the database column FMS_CORP_PKG.RATE
     */
    private BigDecimal RATE;

    /**
     * This field corresponds to the database column FMS_CORP_PKG.CURRENCY
     */
    private BigDecimal CURRENCY;

    /**
     * This field corresponds to the database column FMS_CORP_PKG.LIMIT
     */
    private BigDecimal LIMIT;

    /**
     * This field corresponds to the database column FMS_CORP_PKG.UTILIZED
     */
    private BigDecimal UTILIZED;

    /**
     * This field corresponds to the database column FMS_CORP_PKG.CORP_GROUP
     */
    private String CORP_GROUP;

    /**
     * This field corresponds to the database column FMS_CORP_PKG.CREATED_BY
     */
    private String CREATED_BY;

    /**
     * This field corresponds to the database column FMS_CORP_PKG.CREATED_DATE
     */
    private Date CREATED_DATE;

    /**
     * This field corresponds to the database column FMS_CORP_PKG.MODIFIED_BY
     */
    private String MODIFIED_BY;

    /**
     * This field corresponds to the database column FMS_CORP_PKG.MODIFIED_DATE
     */
    private Date MODIFIED_DATE;

    /**
     * This field corresponds to the database column FMS_CORP_PKG.APPROVED_BY
     */
    private String APPROVED_BY;

    /**
     * This field corresponds to the database column FMS_CORP_PKG.APPROVED_DATE
     */
    private Date APPROVED_DATE;

    /**
     * This field corresponds to the database column FMS_CORP_PKG.REVERSED_BY
     */
    private String REVERSED_BY;

    /**
     * This field corresponds to the database column FMS_CORP_PKG.REVERSED_DATE
     */
    private Date REVERSED_DATE;

    /**
     * This field corresponds to the database column FMS_CORP_PKG.DELETED_BY
     */
    private String DELETED_BY;

    /**
     * This field corresponds to the database column FMS_CORP_PKG.DELETED_DATE
     */
    private Date DELETED_DATE;

    /**
     * This field corresponds to the database column FMS_CORP_PKG.DATE_UPDATED
     */
    private Date DATE_UPDATED;

    /**
     * This field corresponds to the database column FMS_CORP_PKG.UPDATED_BY
     */
    private String UPDATED_BY;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMS_CORP_PKG.CIF_NO
     *
     * @return the value of FMS_CORP_PKG.CIF_NO
     */
    public BigDecimal getCIF_NO() {
        return CIF_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMS_CORP_PKG.CIF_NO
     *
     * @param CIF_NO the value for FMS_CORP_PKG.CIF_NO
     */
    public void setCIF_NO(BigDecimal CIF_NO) {
        this.CIF_NO = CIF_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMS_CORP_PKG.STATUS
     *
     * @return the value of FMS_CORP_PKG.STATUS
     */
    public String getSTATUS() {
        return STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMS_CORP_PKG.STATUS
     *
     * @param STATUS the value for FMS_CORP_PKG.STATUS
     */
    public void setSTATUS(String STATUS) {
        this.STATUS = STATUS == null ? null : STATUS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMS_CORP_PKG.RET_AGE
     *
     * @return the value of FMS_CORP_PKG.RET_AGE
     */
    public BigDecimal getRET_AGE() {
        return RET_AGE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMS_CORP_PKG.RET_AGE
     *
     * @param RET_AGE the value for FMS_CORP_PKG.RET_AGE
     */
    public void setRET_AGE(BigDecimal RET_AGE) {
        this.RET_AGE = RET_AGE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMS_CORP_PKG.SUBSIDIZED
     *
     * @return the value of FMS_CORP_PKG.SUBSIDIZED
     */
    public String getSUBSIDIZED() {
        return SUBSIDIZED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMS_CORP_PKG.SUBSIDIZED
     *
     * @param SUBSIDIZED the value for FMS_CORP_PKG.SUBSIDIZED
     */
    public void setSUBSIDIZED(String SUBSIDIZED) {
        this.SUBSIDIZED = SUBSIDIZED == null ? null : SUBSIDIZED.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMS_CORP_PKG.REPAY_MODE
     *
     * @return the value of FMS_CORP_PKG.REPAY_MODE
     */
    public String getREPAY_MODE() {
        return REPAY_MODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMS_CORP_PKG.REPAY_MODE
     *
     * @param REPAY_MODE the value for FMS_CORP_PKG.REPAY_MODE
     */
    public void setREPAY_MODE(String REPAY_MODE) {
        this.REPAY_MODE = REPAY_MODE == null ? null : REPAY_MODE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMS_CORP_PKG.RATE
     *
     * @return the value of FMS_CORP_PKG.RATE
     */
    public BigDecimal getRATE() {
        return RATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMS_CORP_PKG.RATE
     *
     * @param RATE the value for FMS_CORP_PKG.RATE
     */
    public void setRATE(BigDecimal RATE) {
        this.RATE = RATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMS_CORP_PKG.CURRENCY
     *
     * @return the value of FMS_CORP_PKG.CURRENCY
     */
    public BigDecimal getCURRENCY() {
        return CURRENCY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMS_CORP_PKG.CURRENCY
     *
     * @param CURRENCY the value for FMS_CORP_PKG.CURRENCY
     */
    public void setCURRENCY(BigDecimal CURRENCY) {
        this.CURRENCY = CURRENCY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMS_CORP_PKG.LIMIT
     *
     * @return the value of FMS_CORP_PKG.LIMIT
     */
    public BigDecimal getLIMIT() {
        return LIMIT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMS_CORP_PKG.LIMIT
     *
     * @param LIMIT the value for FMS_CORP_PKG.LIMIT
     */
    public void setLIMIT(BigDecimal LIMIT) {
        this.LIMIT = LIMIT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMS_CORP_PKG.UTILIZED
     *
     * @return the value of FMS_CORP_PKG.UTILIZED
     */
    public BigDecimal getUTILIZED() {
        return UTILIZED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMS_CORP_PKG.UTILIZED
     *
     * @param UTILIZED the value for FMS_CORP_PKG.UTILIZED
     */
    public void setUTILIZED(BigDecimal UTILIZED) {
        this.UTILIZED = UTILIZED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMS_CORP_PKG.CORP_GROUP
     *
     * @return the value of FMS_CORP_PKG.CORP_GROUP
     */
    public String getCORP_GROUP() {
        return CORP_GROUP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMS_CORP_PKG.CORP_GROUP
     *
     * @param CORP_GROUP the value for FMS_CORP_PKG.CORP_GROUP
     */
    public void setCORP_GROUP(String CORP_GROUP) {
        this.CORP_GROUP = CORP_GROUP == null ? null : CORP_GROUP.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMS_CORP_PKG.CREATED_BY
     *
     * @return the value of FMS_CORP_PKG.CREATED_BY
     */
    public String getCREATED_BY() {
        return CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMS_CORP_PKG.CREATED_BY
     *
     * @param CREATED_BY the value for FMS_CORP_PKG.CREATED_BY
     */
    public void setCREATED_BY(String CREATED_BY) {
        this.CREATED_BY = CREATED_BY == null ? null : CREATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMS_CORP_PKG.CREATED_DATE
     *
     * @return the value of FMS_CORP_PKG.CREATED_DATE
     */
    public Date getCREATED_DATE() {
        return CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMS_CORP_PKG.CREATED_DATE
     *
     * @param CREATED_DATE the value for FMS_CORP_PKG.CREATED_DATE
     */
    public void setCREATED_DATE(Date CREATED_DATE) {
        this.CREATED_DATE = CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMS_CORP_PKG.MODIFIED_BY
     *
     * @return the value of FMS_CORP_PKG.MODIFIED_BY
     */
    public String getMODIFIED_BY() {
        return MODIFIED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMS_CORP_PKG.MODIFIED_BY
     *
     * @param MODIFIED_BY the value for FMS_CORP_PKG.MODIFIED_BY
     */
    public void setMODIFIED_BY(String MODIFIED_BY) {
        this.MODIFIED_BY = MODIFIED_BY == null ? null : MODIFIED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMS_CORP_PKG.MODIFIED_DATE
     *
     * @return the value of FMS_CORP_PKG.MODIFIED_DATE
     */
    public Date getMODIFIED_DATE() {
        return MODIFIED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMS_CORP_PKG.MODIFIED_DATE
     *
     * @param MODIFIED_DATE the value for FMS_CORP_PKG.MODIFIED_DATE
     */
    public void setMODIFIED_DATE(Date MODIFIED_DATE) {
        this.MODIFIED_DATE = MODIFIED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMS_CORP_PKG.APPROVED_BY
     *
     * @return the value of FMS_CORP_PKG.APPROVED_BY
     */
    public String getAPPROVED_BY() {
        return APPROVED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMS_CORP_PKG.APPROVED_BY
     *
     * @param APPROVED_BY the value for FMS_CORP_PKG.APPROVED_BY
     */
    public void setAPPROVED_BY(String APPROVED_BY) {
        this.APPROVED_BY = APPROVED_BY == null ? null : APPROVED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMS_CORP_PKG.APPROVED_DATE
     *
     * @return the value of FMS_CORP_PKG.APPROVED_DATE
     */
    public Date getAPPROVED_DATE() {
        return APPROVED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMS_CORP_PKG.APPROVED_DATE
     *
     * @param APPROVED_DATE the value for FMS_CORP_PKG.APPROVED_DATE
     */
    public void setAPPROVED_DATE(Date APPROVED_DATE) {
        this.APPROVED_DATE = APPROVED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMS_CORP_PKG.REVERSED_BY
     *
     * @return the value of FMS_CORP_PKG.REVERSED_BY
     */
    public String getREVERSED_BY() {
        return REVERSED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMS_CORP_PKG.REVERSED_BY
     *
     * @param REVERSED_BY the value for FMS_CORP_PKG.REVERSED_BY
     */
    public void setREVERSED_BY(String REVERSED_BY) {
        this.REVERSED_BY = REVERSED_BY == null ? null : REVERSED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMS_CORP_PKG.REVERSED_DATE
     *
     * @return the value of FMS_CORP_PKG.REVERSED_DATE
     */
    public Date getREVERSED_DATE() {
        return REVERSED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMS_CORP_PKG.REVERSED_DATE
     *
     * @param REVERSED_DATE the value for FMS_CORP_PKG.REVERSED_DATE
     */
    public void setREVERSED_DATE(Date REVERSED_DATE) {
        this.REVERSED_DATE = REVERSED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMS_CORP_PKG.DELETED_BY
     *
     * @return the value of FMS_CORP_PKG.DELETED_BY
     */
    public String getDELETED_BY() {
        return DELETED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMS_CORP_PKG.DELETED_BY
     *
     * @param DELETED_BY the value for FMS_CORP_PKG.DELETED_BY
     */
    public void setDELETED_BY(String DELETED_BY) {
        this.DELETED_BY = DELETED_BY == null ? null : DELETED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMS_CORP_PKG.DELETED_DATE
     *
     * @return the value of FMS_CORP_PKG.DELETED_DATE
     */
    public Date getDELETED_DATE() {
        return DELETED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMS_CORP_PKG.DELETED_DATE
     *
     * @param DELETED_DATE the value for FMS_CORP_PKG.DELETED_DATE
     */
    public void setDELETED_DATE(Date DELETED_DATE) {
        this.DELETED_DATE = DELETED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMS_CORP_PKG.DATE_UPDATED
     *
     * @return the value of FMS_CORP_PKG.DATE_UPDATED
     */
    public Date getDATE_UPDATED() {
        return DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMS_CORP_PKG.DATE_UPDATED
     *
     * @param DATE_UPDATED the value for FMS_CORP_PKG.DATE_UPDATED
     */
    public void setDATE_UPDATED(Date DATE_UPDATED) {
        this.DATE_UPDATED = DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMS_CORP_PKG.UPDATED_BY
     *
     * @return the value of FMS_CORP_PKG.UPDATED_BY
     */
    public String getUPDATED_BY() {
        return UPDATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMS_CORP_PKG.UPDATED_BY
     *
     * @param UPDATED_BY the value for FMS_CORP_PKG.UPDATED_BY
     */
    public void setUPDATED_BY(String UPDATED_BY) {
        this.UPDATED_BY = UPDATED_BY == null ? null : UPDATED_BY.trim();
    }
}