package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class FMS_RED_HISTVO extends FMS_RED_HISTVOKey {
    /**
     * This field corresponds to the database column FMS_RED_HIST.TYPE
     */
    private String TYPE;

    /**
     * This field corresponds to the database column FMS_RED_HIST.DATE_1
     */
    private Date DATE_1;

    /**
     * This field corresponds to the database column FMS_RED_HIST.AMOUNT
     */
    private BigDecimal AMOUNT;

    /**
     * This field corresponds to the database column FMS_RED_HIST.DRAWING_POWER
     */
    private BigDecimal DRAWING_POWER;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMS_RED_HIST.TYPE
     *
     * @return the value of FMS_RED_HIST.TYPE
     */
    public String getTYPE() {
        return TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMS_RED_HIST.TYPE
     *
     * @param TYPE the value for FMS_RED_HIST.TYPE
     */
    public void setTYPE(String TYPE) {
        this.TYPE = TYPE == null ? null : TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMS_RED_HIST.DATE_1
     *
     * @return the value of FMS_RED_HIST.DATE_1
     */
    public Date getDATE_1() {
        return DATE_1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMS_RED_HIST.DATE_1
     *
     * @param DATE_1 the value for FMS_RED_HIST.DATE_1
     */
    public void setDATE_1(Date DATE_1) {
        this.DATE_1 = DATE_1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMS_RED_HIST.AMOUNT
     *
     * @return the value of FMS_RED_HIST.AMOUNT
     */
    public BigDecimal getAMOUNT() {
        return AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMS_RED_HIST.AMOUNT
     *
     * @param AMOUNT the value for FMS_RED_HIST.AMOUNT
     */
    public void setAMOUNT(BigDecimal AMOUNT) {
        this.AMOUNT = AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMS_RED_HIST.DRAWING_POWER
     *
     * @return the value of FMS_RED_HIST.DRAWING_POWER
     */
    public BigDecimal getDRAWING_POWER() {
        return DRAWING_POWER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMS_RED_HIST.DRAWING_POWER
     *
     * @param DRAWING_POWER the value for FMS_RED_HIST.DRAWING_POWER
     */
    public void setDRAWING_POWER(BigDecimal DRAWING_POWER) {
        this.DRAWING_POWER = DRAWING_POWER;
    }
}