package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class FMS_PURPOSEFINANCE_CLASSVOKey extends BaseVO {
    /**
     * This field corresponds to the database column FMS_PURPOSEFINANCE_CLASS.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column FMS_PURPOSEFINANCE_CLASS.LINE_NBR
     */
    private BigDecimal LINE_NBR;

    /**
     * This field corresponds to the database column FMS_PURPOSEFINANCE_CLASS.PURPOSEFINANCE_CODE
     */
    private BigDecimal PURPOSEFINANCE_CODE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMS_PURPOSEFINANCE_CLASS.COMP_CODE
     *
     * @return the value of FMS_PURPOSEFINANCE_CLASS.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMS_PURPOSEFINANCE_CLASS.COMP_CODE
     *
     * @param COMP_CODE the value for FMS_PURPOSEFINANCE_CLASS.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMS_PURPOSEFINANCE_CLASS.LINE_NBR
     *
     * @return the value of FMS_PURPOSEFINANCE_CLASS.LINE_NBR
     */
    public BigDecimal getLINE_NBR() {
        return LINE_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMS_PURPOSEFINANCE_CLASS.LINE_NBR
     *
     * @param LINE_NBR the value for FMS_PURPOSEFINANCE_CLASS.LINE_NBR
     */
    public void setLINE_NBR(BigDecimal LINE_NBR) {
        this.LINE_NBR = LINE_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMS_PURPOSEFINANCE_CLASS.PURPOSEFINANCE_CODE
     *
     * @return the value of FMS_PURPOSEFINANCE_CLASS.PURPOSEFINANCE_CODE
     */
    public BigDecimal getPURPOSEFINANCE_CODE() {
        return PURPOSEFINANCE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMS_PURPOSEFINANCE_CLASS.PURPOSEFINANCE_CODE
     *
     * @param PURPOSEFINANCE_CODE the value for FMS_PURPOSEFINANCE_CLASS.PURPOSEFINANCE_CODE
     */
    public void setPURPOSEFINANCE_CODE(BigDecimal PURPOSEFINANCE_CODE) {
        this.PURPOSEFINANCE_CODE = PURPOSEFINANCE_CODE;
    }
}