package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class FMS_TEMPLATE_PARTICIPANT_HDRVO extends FMS_TEMPLATE_PARTICIPANT_HDRVOKey {
    /**
     * This field corresponds to the database column FMS_TEMPLATE_PARTICIPANT_HDR.TEMPLATE_DATE
     */
    private Date TEMPLATE_DATE;

    /**
     * This field corresponds to the database column FMS_TEMPLATE_PARTICIPANT_HDR.STATUS
     */
    private String STATUS;

    /**
     * This field corresponds to the database column FMS_TEMPLATE_PARTICIPANT_HDR.APPLICATION_CODE
     */
    private BigDecimal APPLICATION_CODE;

    /**
     * This field corresponds to the database column FMS_TEMPLATE_PARTICIPANT_HDR.FACILITY_NO
     */
    private BigDecimal FACILITY_NO;

    /**
     * This field corresponds to the database column FMS_TEMPLATE_PARTICIPANT_HDR.PARTICIPANT_DIST_METHOD
     */
    private String PARTICIPANT_DIST_METHOD;

    /**
     * This field corresponds to the database column FMS_TEMPLATE_PARTICIPANT_HDR.REMARKS
     */
    private String REMARKS;

    /**
     * This field corresponds to the database column FMS_TEMPLATE_PARTICIPANT_HDR.CREATED_BY
     */
    private String CREATED_BY;

    /**
     * This field corresponds to the database column FMS_TEMPLATE_PARTICIPANT_HDR.DATE_CREATED
     */
    private Date DATE_CREATED;

    /**
     * This field corresponds to the database column FMS_TEMPLATE_PARTICIPANT_HDR.DELETED_BY
     */
    private String DELETED_BY;

    /**
     * This field corresponds to the database column FMS_TEMPLATE_PARTICIPANT_HDR.DATE_DELETED
     */
    private Date DATE_DELETED;

    /**
     * This field corresponds to the database column FMS_TEMPLATE_PARTICIPANT_HDR.APPROVED_BY
     */
    private String APPROVED_BY;

    /**
     * This field corresponds to the database column FMS_TEMPLATE_PARTICIPANT_HDR.DATE_APPROVED
     */
    private Date DATE_APPROVED;

    /**
     * This field corresponds to the database column FMS_TEMPLATE_PARTICIPANT_HDR.REVERSED_BY
     */
    private String REVERSED_BY;

    /**
     * This field corresponds to the database column FMS_TEMPLATE_PARTICIPANT_HDR.DATE_REVERSED
     */
    private Date DATE_REVERSED;

    /**
     * This field corresponds to the database column FMS_TEMPLATE_PARTICIPANT_HDR.MODIFIED_BY
     */
    private String MODIFIED_BY;

    /**
     * This field corresponds to the database column FMS_TEMPLATE_PARTICIPANT_HDR.DATE_MODIFIED
     */
    private Date DATE_MODIFIED;

    /**
     * This field corresponds to the database column FMS_TEMPLATE_PARTICIPANT_HDR.SAVED_AS_DRAFT
     */
    private String SAVED_AS_DRAFT;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMS_TEMPLATE_PARTICIPANT_HDR.TEMPLATE_DATE
     *
     * @return the value of FMS_TEMPLATE_PARTICIPANT_HDR.TEMPLATE_DATE
     */
    public Date getTEMPLATE_DATE() {
        return TEMPLATE_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMS_TEMPLATE_PARTICIPANT_HDR.TEMPLATE_DATE
     *
     * @param TEMPLATE_DATE the value for FMS_TEMPLATE_PARTICIPANT_HDR.TEMPLATE_DATE
     */
    public void setTEMPLATE_DATE(Date TEMPLATE_DATE) {
        this.TEMPLATE_DATE = TEMPLATE_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMS_TEMPLATE_PARTICIPANT_HDR.STATUS
     *
     * @return the value of FMS_TEMPLATE_PARTICIPANT_HDR.STATUS
     */
    public String getSTATUS() {
        return STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMS_TEMPLATE_PARTICIPANT_HDR.STATUS
     *
     * @param STATUS the value for FMS_TEMPLATE_PARTICIPANT_HDR.STATUS
     */
    public void setSTATUS(String STATUS) {
        this.STATUS = STATUS == null ? null : STATUS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMS_TEMPLATE_PARTICIPANT_HDR.APPLICATION_CODE
     *
     * @return the value of FMS_TEMPLATE_PARTICIPANT_HDR.APPLICATION_CODE
     */
    public BigDecimal getAPPLICATION_CODE() {
        return APPLICATION_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMS_TEMPLATE_PARTICIPANT_HDR.APPLICATION_CODE
     *
     * @param APPLICATION_CODE the value for FMS_TEMPLATE_PARTICIPANT_HDR.APPLICATION_CODE
     */
    public void setAPPLICATION_CODE(BigDecimal APPLICATION_CODE) {
        this.APPLICATION_CODE = APPLICATION_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMS_TEMPLATE_PARTICIPANT_HDR.FACILITY_NO
     *
     * @return the value of FMS_TEMPLATE_PARTICIPANT_HDR.FACILITY_NO
     */
    public BigDecimal getFACILITY_NO() {
        return FACILITY_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMS_TEMPLATE_PARTICIPANT_HDR.FACILITY_NO
     *
     * @param FACILITY_NO the value for FMS_TEMPLATE_PARTICIPANT_HDR.FACILITY_NO
     */
    public void setFACILITY_NO(BigDecimal FACILITY_NO) {
        this.FACILITY_NO = FACILITY_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMS_TEMPLATE_PARTICIPANT_HDR.PARTICIPANT_DIST_METHOD
     *
     * @return the value of FMS_TEMPLATE_PARTICIPANT_HDR.PARTICIPANT_DIST_METHOD
     */
    public String getPARTICIPANT_DIST_METHOD() {
        return PARTICIPANT_DIST_METHOD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMS_TEMPLATE_PARTICIPANT_HDR.PARTICIPANT_DIST_METHOD
     *
     * @param PARTICIPANT_DIST_METHOD the value for FMS_TEMPLATE_PARTICIPANT_HDR.PARTICIPANT_DIST_METHOD
     */
    public void setPARTICIPANT_DIST_METHOD(String PARTICIPANT_DIST_METHOD) {
        this.PARTICIPANT_DIST_METHOD = PARTICIPANT_DIST_METHOD == null ? null : PARTICIPANT_DIST_METHOD.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMS_TEMPLATE_PARTICIPANT_HDR.REMARKS
     *
     * @return the value of FMS_TEMPLATE_PARTICIPANT_HDR.REMARKS
     */
    public String getREMARKS() {
        return REMARKS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMS_TEMPLATE_PARTICIPANT_HDR.REMARKS
     *
     * @param REMARKS the value for FMS_TEMPLATE_PARTICIPANT_HDR.REMARKS
     */
    public void setREMARKS(String REMARKS) {
        this.REMARKS = REMARKS == null ? null : REMARKS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMS_TEMPLATE_PARTICIPANT_HDR.CREATED_BY
     *
     * @return the value of FMS_TEMPLATE_PARTICIPANT_HDR.CREATED_BY
     */
    public String getCREATED_BY() {
        return CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMS_TEMPLATE_PARTICIPANT_HDR.CREATED_BY
     *
     * @param CREATED_BY the value for FMS_TEMPLATE_PARTICIPANT_HDR.CREATED_BY
     */
    public void setCREATED_BY(String CREATED_BY) {
        this.CREATED_BY = CREATED_BY == null ? null : CREATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMS_TEMPLATE_PARTICIPANT_HDR.DATE_CREATED
     *
     * @return the value of FMS_TEMPLATE_PARTICIPANT_HDR.DATE_CREATED
     */
    public Date getDATE_CREATED() {
        return DATE_CREATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMS_TEMPLATE_PARTICIPANT_HDR.DATE_CREATED
     *
     * @param DATE_CREATED the value for FMS_TEMPLATE_PARTICIPANT_HDR.DATE_CREATED
     */
    public void setDATE_CREATED(Date DATE_CREATED) {
        this.DATE_CREATED = DATE_CREATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMS_TEMPLATE_PARTICIPANT_HDR.DELETED_BY
     *
     * @return the value of FMS_TEMPLATE_PARTICIPANT_HDR.DELETED_BY
     */
    public String getDELETED_BY() {
        return DELETED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMS_TEMPLATE_PARTICIPANT_HDR.DELETED_BY
     *
     * @param DELETED_BY the value for FMS_TEMPLATE_PARTICIPANT_HDR.DELETED_BY
     */
    public void setDELETED_BY(String DELETED_BY) {
        this.DELETED_BY = DELETED_BY == null ? null : DELETED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMS_TEMPLATE_PARTICIPANT_HDR.DATE_DELETED
     *
     * @return the value of FMS_TEMPLATE_PARTICIPANT_HDR.DATE_DELETED
     */
    public Date getDATE_DELETED() {
        return DATE_DELETED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMS_TEMPLATE_PARTICIPANT_HDR.DATE_DELETED
     *
     * @param DATE_DELETED the value for FMS_TEMPLATE_PARTICIPANT_HDR.DATE_DELETED
     */
    public void setDATE_DELETED(Date DATE_DELETED) {
        this.DATE_DELETED = DATE_DELETED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMS_TEMPLATE_PARTICIPANT_HDR.APPROVED_BY
     *
     * @return the value of FMS_TEMPLATE_PARTICIPANT_HDR.APPROVED_BY
     */
    public String getAPPROVED_BY() {
        return APPROVED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMS_TEMPLATE_PARTICIPANT_HDR.APPROVED_BY
     *
     * @param APPROVED_BY the value for FMS_TEMPLATE_PARTICIPANT_HDR.APPROVED_BY
     */
    public void setAPPROVED_BY(String APPROVED_BY) {
        this.APPROVED_BY = APPROVED_BY == null ? null : APPROVED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMS_TEMPLATE_PARTICIPANT_HDR.DATE_APPROVED
     *
     * @return the value of FMS_TEMPLATE_PARTICIPANT_HDR.DATE_APPROVED
     */
    public Date getDATE_APPROVED() {
        return DATE_APPROVED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMS_TEMPLATE_PARTICIPANT_HDR.DATE_APPROVED
     *
     * @param DATE_APPROVED the value for FMS_TEMPLATE_PARTICIPANT_HDR.DATE_APPROVED
     */
    public void setDATE_APPROVED(Date DATE_APPROVED) {
        this.DATE_APPROVED = DATE_APPROVED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMS_TEMPLATE_PARTICIPANT_HDR.REVERSED_BY
     *
     * @return the value of FMS_TEMPLATE_PARTICIPANT_HDR.REVERSED_BY
     */
    public String getREVERSED_BY() {
        return REVERSED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMS_TEMPLATE_PARTICIPANT_HDR.REVERSED_BY
     *
     * @param REVERSED_BY the value for FMS_TEMPLATE_PARTICIPANT_HDR.REVERSED_BY
     */
    public void setREVERSED_BY(String REVERSED_BY) {
        this.REVERSED_BY = REVERSED_BY == null ? null : REVERSED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMS_TEMPLATE_PARTICIPANT_HDR.DATE_REVERSED
     *
     * @return the value of FMS_TEMPLATE_PARTICIPANT_HDR.DATE_REVERSED
     */
    public Date getDATE_REVERSED() {
        return DATE_REVERSED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMS_TEMPLATE_PARTICIPANT_HDR.DATE_REVERSED
     *
     * @param DATE_REVERSED the value for FMS_TEMPLATE_PARTICIPANT_HDR.DATE_REVERSED
     */
    public void setDATE_REVERSED(Date DATE_REVERSED) {
        this.DATE_REVERSED = DATE_REVERSED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMS_TEMPLATE_PARTICIPANT_HDR.MODIFIED_BY
     *
     * @return the value of FMS_TEMPLATE_PARTICIPANT_HDR.MODIFIED_BY
     */
    public String getMODIFIED_BY() {
        return MODIFIED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMS_TEMPLATE_PARTICIPANT_HDR.MODIFIED_BY
     *
     * @param MODIFIED_BY the value for FMS_TEMPLATE_PARTICIPANT_HDR.MODIFIED_BY
     */
    public void setMODIFIED_BY(String MODIFIED_BY) {
        this.MODIFIED_BY = MODIFIED_BY == null ? null : MODIFIED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMS_TEMPLATE_PARTICIPANT_HDR.DATE_MODIFIED
     *
     * @return the value of FMS_TEMPLATE_PARTICIPANT_HDR.DATE_MODIFIED
     */
    public Date getDATE_MODIFIED() {
        return DATE_MODIFIED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMS_TEMPLATE_PARTICIPANT_HDR.DATE_MODIFIED
     *
     * @param DATE_MODIFIED the value for FMS_TEMPLATE_PARTICIPANT_HDR.DATE_MODIFIED
     */
    public void setDATE_MODIFIED(Date DATE_MODIFIED) {
        this.DATE_MODIFIED = DATE_MODIFIED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMS_TEMPLATE_PARTICIPANT_HDR.SAVED_AS_DRAFT
     *
     * @return the value of FMS_TEMPLATE_PARTICIPANT_HDR.SAVED_AS_DRAFT
     */
    public String getSAVED_AS_DRAFT() {
        return SAVED_AS_DRAFT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMS_TEMPLATE_PARTICIPANT_HDR.SAVED_AS_DRAFT
     *
     * @param SAVED_AS_DRAFT the value for FMS_TEMPLATE_PARTICIPANT_HDR.SAVED_AS_DRAFT
     */
    public void setSAVED_AS_DRAFT(String SAVED_AS_DRAFT) {
        this.SAVED_AS_DRAFT = SAVED_AS_DRAFT == null ? null : SAVED_AS_DRAFT.trim();
    }
}