package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class FMS_PUR_FIN_ADD_DETVOKey extends BaseVO {
    /**
     * This field corresponds to the database column FMS_PUR_FIN_ADD_DET.BRANCH_CODE
     */
    private BigDecimal BRANCH_CODE;

    /**
     * This field corresponds to the database column FMS_PUR_FIN_ADD_DET.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column FMS_PUR_FIN_ADD_DET.LINE_NBR
     */
    private BigDecimal LINE_NBR;

    /**
     * This field corresponds to the database column FMS_PUR_FIN_ADD_DET.LINE_NBR_SUB
     */
    private BigDecimal LINE_NBR_SUB;

    /**
     * This field corresponds to the database column FMS_PUR_FIN_ADD_DET.SERIAL_NO
     */
    private BigDecimal SERIAL_NO;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMS_PUR_FIN_ADD_DET.BRANCH_CODE
     *
     * @return the value of FMS_PUR_FIN_ADD_DET.BRANCH_CODE
     */
    public BigDecimal getBRANCH_CODE() {
        return BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMS_PUR_FIN_ADD_DET.BRANCH_CODE
     *
     * @param BRANCH_CODE the value for FMS_PUR_FIN_ADD_DET.BRANCH_CODE
     */
    public void setBRANCH_CODE(BigDecimal BRANCH_CODE) {
        this.BRANCH_CODE = BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMS_PUR_FIN_ADD_DET.COMP_CODE
     *
     * @return the value of FMS_PUR_FIN_ADD_DET.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMS_PUR_FIN_ADD_DET.COMP_CODE
     *
     * @param COMP_CODE the value for FMS_PUR_FIN_ADD_DET.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMS_PUR_FIN_ADD_DET.LINE_NBR
     *
     * @return the value of FMS_PUR_FIN_ADD_DET.LINE_NBR
     */
    public BigDecimal getLINE_NBR() {
        return LINE_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMS_PUR_FIN_ADD_DET.LINE_NBR
     *
     * @param LINE_NBR the value for FMS_PUR_FIN_ADD_DET.LINE_NBR
     */
    public void setLINE_NBR(BigDecimal LINE_NBR) {
        this.LINE_NBR = LINE_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMS_PUR_FIN_ADD_DET.LINE_NBR_SUB
     *
     * @return the value of FMS_PUR_FIN_ADD_DET.LINE_NBR_SUB
     */
    public BigDecimal getLINE_NBR_SUB() {
        return LINE_NBR_SUB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMS_PUR_FIN_ADD_DET.LINE_NBR_SUB
     *
     * @param LINE_NBR_SUB the value for FMS_PUR_FIN_ADD_DET.LINE_NBR_SUB
     */
    public void setLINE_NBR_SUB(BigDecimal LINE_NBR_SUB) {
        this.LINE_NBR_SUB = LINE_NBR_SUB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMS_PUR_FIN_ADD_DET.SERIAL_NO
     *
     * @return the value of FMS_PUR_FIN_ADD_DET.SERIAL_NO
     */
    public BigDecimal getSERIAL_NO() {
        return SERIAL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMS_PUR_FIN_ADD_DET.SERIAL_NO
     *
     * @param SERIAL_NO the value for FMS_PUR_FIN_ADD_DET.SERIAL_NO
     */
    public void setSERIAL_NO(BigDecimal SERIAL_NO) {
        this.SERIAL_NO = SERIAL_NO;
    }
}