package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class FMSAPPLIMITDET_CUSTOM_FIELDSVO extends FMSAPPLIMITDET_CUSTOM_FIELDSVOKey
{
    /**
     * This field corresponds to the database column
     * FMSAPPLIMITDET_CUSTOM_FIELDS.CUSTOM_FIELD_DATE
     */
    private Date CUSTOM_FIELD_DATE;

    /**
     * This field corresponds to the database column
     * FMSAPPLIMITDET_CUSTOM_FIELDS.CUSTOM_FIELD_NUMBER
     */
    private BigDecimal CUSTOM_FIELD_NUMBER;

    /**
     * This field corresponds to the database column
     * FMSAPPLIMITDET_CUSTOM_FIELDS.CUSTOM_FIELD_ALPHANUMERIC
     */
    private String CUSTOM_FIELD_ALPHANUMERIC;

    /**
     * This field corresponds to the database column
     * FMSAPPLIMITDET_CUSTOM_FIELDS.CUSTOM_FIELD_ORDER
     */
    private BigDecimal CUSTOM_FIELD_ORDER;

    /**
     * This field corresponds to the database column
     * FMSAPPLIMITDET_CUSTOM_FIELDS.CUSTOM_FIELD_LABEL
     */
    private String CUSTOM_FIELD_LABEL;

    /**
     * This field corresponds to the database column
     * FMSAPPLIMITDET_CUSTOM_FIELDS.CREATED_BY
     */
    private String CREATED_BY;

    /**
     * This field corresponds to the database column
     * FMSAPPLIMITDET_CUSTOM_FIELDS.CREATED_DATE
     */
    private Date CREATED_DATE;

    /**
     * This field corresponds to the database column
     * FMSAPPLIMITDET_CUSTOM_FIELDS.MODIFIED_BY
     */
    private String MODIFIED_BY;

    /**
     * This field corresponds to the database column
     * FMSAPPLIMITDET_CUSTOM_FIELDS.MODIFIED_DATE
     */
    private Date MODIFIED_DATE;

    /**
     * This field corresponds to the database column
     * FMSAPPLIMITDET_CUSTOM_FIELDS.CUSTOM_FIELD_UPLOAD_DATE
     */
    private Date CUSTOM_FIELD_UPLOAD_DATE;

    /**
     * This field corresponds to the database column
     * FMSAPPLIMITDET_CUSTOM_FIELDS.CUSTOM_FIELD_ATTACH_NAME
     */
    private String CUSTOM_FIELD_ATTACH_NAME;

    /**
     * This field corresponds to the database column
     * FMSAPPLIMITDET_CUSTOM_FIELDS.CUSTOM_FIELD_CODE
     */
    private BigDecimal CUSTOM_FIELD_CODE;

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column
     * FMSAPPLIMITDET_CUSTOM_FIELDS.CUSTOM_FIELD_DATE
     *
     * @return the value of FMSAPPLIMITDET_CUSTOM_FIELDS.CUSTOM_FIELD_DATE
     */
    public Date getCUSTOM_FIELD_DATE()
    {
	return CUSTOM_FIELD_DATE;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column
     * FMSAPPLIMITDET_CUSTOM_FIELDS.CUSTOM_FIELD_DATE
     *
     * @param CUSTOM_FIELD_DATE the value for
     *            FMSAPPLIMITDET_CUSTOM_FIELDS.CUSTOM_FIELD_DATE
     */
    public void setCUSTOM_FIELD_DATE(Date CUSTOM_FIELD_DATE)
    {
	this.CUSTOM_FIELD_DATE = CUSTOM_FIELD_DATE;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column
     * FMSAPPLIMITDET_CUSTOM_FIELDS.CUSTOM_FIELD_NUMBER
     *
     * @return the value of FMSAPPLIMITDET_CUSTOM_FIELDS.CUSTOM_FIELD_NUMBER
     */
    public BigDecimal getCUSTOM_FIELD_NUMBER()
    {
	return CUSTOM_FIELD_NUMBER;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column
     * FMSAPPLIMITDET_CUSTOM_FIELDS.CUSTOM_FIELD_NUMBER
     *
     * @param CUSTOM_FIELD_NUMBER the value for
     *            FMSAPPLIMITDET_CUSTOM_FIELDS.CUSTOM_FIELD_NUMBER
     */
    public void setCUSTOM_FIELD_NUMBER(BigDecimal CUSTOM_FIELD_NUMBER)
    {
	this.CUSTOM_FIELD_NUMBER = CUSTOM_FIELD_NUMBER;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column
     * FMSAPPLIMITDET_CUSTOM_FIELDS.CUSTOM_FIELD_ALPHANUMERIC
     *
     * @return the value of
     *         FMSAPPLIMITDET_CUSTOM_FIELDS.CUSTOM_FIELD_ALPHANUMERIC
     */
    public String getCUSTOM_FIELD_ALPHANUMERIC()
    {
	return CUSTOM_FIELD_ALPHANUMERIC;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column
     * FMSAPPLIMITDET_CUSTOM_FIELDS.CUSTOM_FIELD_ALPHANUMERIC
     *
     * @param CUSTOM_FIELD_ALPHANUMERIC the value for
     *            FMSAPPLIMITDET_CUSTOM_FIELDS.CUSTOM_FIELD_ALPHANUMERIC
     */
    public void setCUSTOM_FIELD_ALPHANUMERIC(String CUSTOM_FIELD_ALPHANUMERIC)
    {
	this.CUSTOM_FIELD_ALPHANUMERIC = CUSTOM_FIELD_ALPHANUMERIC == null ? null : CUSTOM_FIELD_ALPHANUMERIC.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column
     * FMSAPPLIMITDET_CUSTOM_FIELDS.CUSTOM_FIELD_ORDER
     *
     * @return the value of FMSAPPLIMITDET_CUSTOM_FIELDS.CUSTOM_FIELD_ORDER
     */
    public BigDecimal getCUSTOM_FIELD_ORDER()
    {
	return CUSTOM_FIELD_ORDER;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column
     * FMSAPPLIMITDET_CUSTOM_FIELDS.CUSTOM_FIELD_ORDER
     *
     * @param CUSTOM_FIELD_ORDER the value for
     *            FMSAPPLIMITDET_CUSTOM_FIELDS.CUSTOM_FIELD_ORDER
     */
    public void setCUSTOM_FIELD_ORDER(BigDecimal CUSTOM_FIELD_ORDER)
    {
	this.CUSTOM_FIELD_ORDER = CUSTOM_FIELD_ORDER;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column
     * FMSAPPLIMITDET_CUSTOM_FIELDS.CUSTOM_FIELD_LABEL
     *
     * @return the value of FMSAPPLIMITDET_CUSTOM_FIELDS.CUSTOM_FIELD_LABEL
     */
    public String getCUSTOM_FIELD_LABEL()
    {
	return CUSTOM_FIELD_LABEL;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column
     * FMSAPPLIMITDET_CUSTOM_FIELDS.CUSTOM_FIELD_LABEL
     *
     * @param CUSTOM_FIELD_LABEL the value for
     *            FMSAPPLIMITDET_CUSTOM_FIELDS.CUSTOM_FIELD_LABEL
     */
    public void setCUSTOM_FIELD_LABEL(String CUSTOM_FIELD_LABEL)
    {
	this.CUSTOM_FIELD_LABEL = CUSTOM_FIELD_LABEL == null ? null : CUSTOM_FIELD_LABEL.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column FMSAPPLIMITDET_CUSTOM_FIELDS.CREATED_BY
     *
     * @return the value of FMSAPPLIMITDET_CUSTOM_FIELDS.CREATED_BY
     */
    public String getCREATED_BY()
    {
	return CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column FMSAPPLIMITDET_CUSTOM_FIELDS.CREATED_BY
     *
     * @param CREATED_BY the value for FMSAPPLIMITDET_CUSTOM_FIELDS.CREATED_BY
     */
    public void setCREATED_BY(String CREATED_BY)
    {
	this.CREATED_BY = CREATED_BY == null ? null : CREATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column FMSAPPLIMITDET_CUSTOM_FIELDS.CREATED_DATE
     *
     * @return the value of FMSAPPLIMITDET_CUSTOM_FIELDS.CREATED_DATE
     */
    public Date getCREATED_DATE()
    {
	return CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column FMSAPPLIMITDET_CUSTOM_FIELDS.CREATED_DATE
     *
     * @param CREATED_DATE the value for
     *            FMSAPPLIMITDET_CUSTOM_FIELDS.CREATED_DATE
     */
    public void setCREATED_DATE(Date CREATED_DATE)
    {
	this.CREATED_DATE = CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column FMSAPPLIMITDET_CUSTOM_FIELDS.MODIFIED_BY
     *
     * @return the value of FMSAPPLIMITDET_CUSTOM_FIELDS.MODIFIED_BY
     */
    public String getMODIFIED_BY()
    {
	return MODIFIED_BY;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column FMSAPPLIMITDET_CUSTOM_FIELDS.MODIFIED_BY
     *
     * @param MODIFIED_BY the value for FMSAPPLIMITDET_CUSTOM_FIELDS.MODIFIED_BY
     */
    public void setMODIFIED_BY(String MODIFIED_BY)
    {
	this.MODIFIED_BY = MODIFIED_BY == null ? null : MODIFIED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column FMSAPPLIMITDET_CUSTOM_FIELDS.MODIFIED_DATE
     *
     * @return the value of FMSAPPLIMITDET_CUSTOM_FIELDS.MODIFIED_DATE
     */
    public Date getMODIFIED_DATE()
    {
	return MODIFIED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column FMSAPPLIMITDET_CUSTOM_FIELDS.MODIFIED_DATE
     *
     * @param MODIFIED_DATE the value for
     *            FMSAPPLIMITDET_CUSTOM_FIELDS.MODIFIED_DATE
     */
    public void setMODIFIED_DATE(Date MODIFIED_DATE)
    {
	this.MODIFIED_DATE = MODIFIED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column
     * FMSAPPLIMITDET_CUSTOM_FIELDS.CUSTOM_FIELD_UPLOAD_DATE
     *
     * @return the value of
     *         FMSAPPLIMITDET_CUSTOM_FIELDS.CUSTOM_FIELD_UPLOAD_DATE
     */
    public Date getCUSTOM_FIELD_UPLOAD_DATE()
    {
	return CUSTOM_FIELD_UPLOAD_DATE;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column
     * FMSAPPLIMITDET_CUSTOM_FIELDS.CUSTOM_FIELD_UPLOAD_DATE
     *
     * @param CUSTOM_FIELD_UPLOAD_DATE the value for
     *            FMSAPPLIMITDET_CUSTOM_FIELDS.CUSTOM_FIELD_UPLOAD_DATE
     */
    public void setCUSTOM_FIELD_UPLOAD_DATE(Date CUSTOM_FIELD_UPLOAD_DATE)
    {
	this.CUSTOM_FIELD_UPLOAD_DATE = CUSTOM_FIELD_UPLOAD_DATE;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column
     * FMSAPPLIMITDET_CUSTOM_FIELDS.CUSTOM_FIELD_ATTACH_NAME
     *
     * @return the value of
     *         FMSAPPLIMITDET_CUSTOM_FIELDS.CUSTOM_FIELD_ATTACH_NAME
     */
    public String getCUSTOM_FIELD_ATTACH_NAME()
    {
	return CUSTOM_FIELD_ATTACH_NAME;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column
     * FMSAPPLIMITDET_CUSTOM_FIELDS.CUSTOM_FIELD_ATTACH_NAME
     *
     * @param CUSTOM_FIELD_ATTACH_NAME the value for
     *            FMSAPPLIMITDET_CUSTOM_FIELDS.CUSTOM_FIELD_ATTACH_NAME
     */
    public void setCUSTOM_FIELD_ATTACH_NAME(String CUSTOM_FIELD_ATTACH_NAME)
    {
	this.CUSTOM_FIELD_ATTACH_NAME = CUSTOM_FIELD_ATTACH_NAME == null ? null : CUSTOM_FIELD_ATTACH_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column
     * FMSAPPLIMITDET_CUSTOM_FIELDS.CUSTOM_FIELD_CODE
     *
     * @return the value of FMSAPPLIMITDET_CUSTOM_FIELDS.CUSTOM_FIELD_CODE
     */
    public BigDecimal getCUSTOM_FIELD_CODE()
    {
	return CUSTOM_FIELD_CODE;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column
     * FMSAPPLIMITDET_CUSTOM_FIELDS.CUSTOM_FIELD_CODE
     *
     * @param CUSTOM_FIELD_CODE the value for
     *            FMSAPPLIMITDET_CUSTOM_FIELDS.CUSTOM_FIELD_CODE
     */
    public void setCUSTOM_FIELD_CODE(BigDecimal CUSTOM_FIELD_CODE)
    {
	this.CUSTOM_FIELD_CODE = CUSTOM_FIELD_CODE;
    }
}