package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class FMSAPPL_SEC_COMPONENTSVO extends FMSAPPL_SEC_COMPONENTSVOKey {
    /**
     * This field corresponds to the database column FMSAPPL_SEC_COMPONENTS.COLATTYPE_CODE
     */
    private BigDecimal COLATTYPE_CODE;

    /**
     * This field corresponds to the database column FMSAPPL_SEC_COMPONENTS.COVERAGE_PERC
     */
    private BigDecimal COVERAGE_PERC;

    /**
     * This field corresponds to the database column FMSAPPL_SEC_COMPONENTS.PROVIDER
     */
    private BigDecimal PROVIDER;

    /**
     * This field corresponds to the database column FMSAPPL_SEC_COMPONENTS.COMMENTS
     */
    private String COMMENTS;

    /**
     * This field corresponds to the database column FMSAPPL_SEC_COMPONENTS.FIXED_AMOUNT
     */
    private BigDecimal FIXED_AMOUNT;

    /**
     * This field corresponds to the database column FMSAPPL_SEC_COMPONENTS.CY_CODE
     */
    private BigDecimal CY_CODE;

    /**
     * This field corresponds to the database column FMSAPPL_SEC_COMPONENTS.FIN_AMOUNT_PERC
     */
    private BigDecimal FIN_AMOUNT_PERC;

    /**
     * This field corresponds to the database column FMSAPPL_SEC_COMPONENTS.COST_BEARING_PARTY
     */
    private BigDecimal COST_BEARING_PARTY;

    /**
     * This field corresponds to the database column FMSAPPL_SEC_COMPONENTS.CREATED_BY
     */
    private String CREATED_BY;

    /**
     * This field corresponds to the database column FMSAPPL_SEC_COMPONENTS.CREATED_DATE
     */
    private Date CREATED_DATE;

    /**
     * This field corresponds to the database column FMSAPPL_SEC_COMPONENTS.MODIFIED_BY
     */
    private String MODIFIED_BY;

    /**
     * This field corresponds to the database column FMSAPPL_SEC_COMPONENTS.MODIFIED_DATE
     */
    private Date MODIFIED_DATE;

    /**
     * This field corresponds to the database column FMSAPPL_SEC_COMPONENTS.COMMODITY
     */
    private BigDecimal COMMODITY;

    /**
     * This field corresponds to the database column FMSAPPL_SEC_COMPONENTS.COLLECTION_LEVEL
     */
    private BigDecimal COLLECTION_LEVEL;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSAPPL_SEC_COMPONENTS.COLATTYPE_CODE
     *
     * @return the value of FMSAPPL_SEC_COMPONENTS.COLATTYPE_CODE
     */
    public BigDecimal getCOLATTYPE_CODE() {
        return COLATTYPE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSAPPL_SEC_COMPONENTS.COLATTYPE_CODE
     *
     * @param COLATTYPE_CODE the value for FMSAPPL_SEC_COMPONENTS.COLATTYPE_CODE
     */
    public void setCOLATTYPE_CODE(BigDecimal COLATTYPE_CODE) {
        this.COLATTYPE_CODE = COLATTYPE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSAPPL_SEC_COMPONENTS.COVERAGE_PERC
     *
     * @return the value of FMSAPPL_SEC_COMPONENTS.COVERAGE_PERC
     */
    public BigDecimal getCOVERAGE_PERC() {
        return COVERAGE_PERC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSAPPL_SEC_COMPONENTS.COVERAGE_PERC
     *
     * @param COVERAGE_PERC the value for FMSAPPL_SEC_COMPONENTS.COVERAGE_PERC
     */
    public void setCOVERAGE_PERC(BigDecimal COVERAGE_PERC) {
        this.COVERAGE_PERC = COVERAGE_PERC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSAPPL_SEC_COMPONENTS.PROVIDER
     *
     * @return the value of FMSAPPL_SEC_COMPONENTS.PROVIDER
     */
    public BigDecimal getPROVIDER() {
        return PROVIDER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSAPPL_SEC_COMPONENTS.PROVIDER
     *
     * @param PROVIDER the value for FMSAPPL_SEC_COMPONENTS.PROVIDER
     */
    public void setPROVIDER(BigDecimal PROVIDER) {
        this.PROVIDER = PROVIDER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSAPPL_SEC_COMPONENTS.COMMENTS
     *
     * @return the value of FMSAPPL_SEC_COMPONENTS.COMMENTS
     */
    public String getCOMMENTS() {
        return COMMENTS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSAPPL_SEC_COMPONENTS.COMMENTS
     *
     * @param COMMENTS the value for FMSAPPL_SEC_COMPONENTS.COMMENTS
     */
    public void setCOMMENTS(String COMMENTS) {
        this.COMMENTS = COMMENTS == null ? null : COMMENTS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSAPPL_SEC_COMPONENTS.FIXED_AMOUNT
     *
     * @return the value of FMSAPPL_SEC_COMPONENTS.FIXED_AMOUNT
     */
    public BigDecimal getFIXED_AMOUNT() {
        return FIXED_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSAPPL_SEC_COMPONENTS.FIXED_AMOUNT
     *
     * @param FIXED_AMOUNT the value for FMSAPPL_SEC_COMPONENTS.FIXED_AMOUNT
     */
    public void setFIXED_AMOUNT(BigDecimal FIXED_AMOUNT) {
        this.FIXED_AMOUNT = FIXED_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSAPPL_SEC_COMPONENTS.CY_CODE
     *
     * @return the value of FMSAPPL_SEC_COMPONENTS.CY_CODE
     */
    public BigDecimal getCY_CODE() {
        return CY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSAPPL_SEC_COMPONENTS.CY_CODE
     *
     * @param CY_CODE the value for FMSAPPL_SEC_COMPONENTS.CY_CODE
     */
    public void setCY_CODE(BigDecimal CY_CODE) {
        this.CY_CODE = CY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSAPPL_SEC_COMPONENTS.FIN_AMOUNT_PERC
     *
     * @return the value of FMSAPPL_SEC_COMPONENTS.FIN_AMOUNT_PERC
     */
    public BigDecimal getFIN_AMOUNT_PERC() {
        return FIN_AMOUNT_PERC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSAPPL_SEC_COMPONENTS.FIN_AMOUNT_PERC
     *
     * @param FIN_AMOUNT_PERC the value for FMSAPPL_SEC_COMPONENTS.FIN_AMOUNT_PERC
     */
    public void setFIN_AMOUNT_PERC(BigDecimal FIN_AMOUNT_PERC) {
        this.FIN_AMOUNT_PERC = FIN_AMOUNT_PERC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSAPPL_SEC_COMPONENTS.COST_BEARING_PARTY
     *
     * @return the value of FMSAPPL_SEC_COMPONENTS.COST_BEARING_PARTY
     */
    public BigDecimal getCOST_BEARING_PARTY() {
        return COST_BEARING_PARTY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSAPPL_SEC_COMPONENTS.COST_BEARING_PARTY
     *
     * @param COST_BEARING_PARTY the value for FMSAPPL_SEC_COMPONENTS.COST_BEARING_PARTY
     */
    public void setCOST_BEARING_PARTY(BigDecimal COST_BEARING_PARTY) {
        this.COST_BEARING_PARTY = COST_BEARING_PARTY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSAPPL_SEC_COMPONENTS.CREATED_BY
     *
     * @return the value of FMSAPPL_SEC_COMPONENTS.CREATED_BY
     */
    public String getCREATED_BY() {
        return CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSAPPL_SEC_COMPONENTS.CREATED_BY
     *
     * @param CREATED_BY the value for FMSAPPL_SEC_COMPONENTS.CREATED_BY
     */
    public void setCREATED_BY(String CREATED_BY) {
        this.CREATED_BY = CREATED_BY == null ? null : CREATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSAPPL_SEC_COMPONENTS.CREATED_DATE
     *
     * @return the value of FMSAPPL_SEC_COMPONENTS.CREATED_DATE
     */
    public Date getCREATED_DATE() {
        return CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSAPPL_SEC_COMPONENTS.CREATED_DATE
     *
     * @param CREATED_DATE the value for FMSAPPL_SEC_COMPONENTS.CREATED_DATE
     */
    public void setCREATED_DATE(Date CREATED_DATE) {
        this.CREATED_DATE = CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSAPPL_SEC_COMPONENTS.MODIFIED_BY
     *
     * @return the value of FMSAPPL_SEC_COMPONENTS.MODIFIED_BY
     */
    public String getMODIFIED_BY() {
        return MODIFIED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSAPPL_SEC_COMPONENTS.MODIFIED_BY
     *
     * @param MODIFIED_BY the value for FMSAPPL_SEC_COMPONENTS.MODIFIED_BY
     */
    public void setMODIFIED_BY(String MODIFIED_BY) {
        this.MODIFIED_BY = MODIFIED_BY == null ? null : MODIFIED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSAPPL_SEC_COMPONENTS.MODIFIED_DATE
     *
     * @return the value of FMSAPPL_SEC_COMPONENTS.MODIFIED_DATE
     */
    public Date getMODIFIED_DATE() {
        return MODIFIED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSAPPL_SEC_COMPONENTS.MODIFIED_DATE
     *
     * @param MODIFIED_DATE the value for FMSAPPL_SEC_COMPONENTS.MODIFIED_DATE
     */
    public void setMODIFIED_DATE(Date MODIFIED_DATE) {
        this.MODIFIED_DATE = MODIFIED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSAPPL_SEC_COMPONENTS.COMMODITY
     *
     * @return the value of FMSAPPL_SEC_COMPONENTS.COMMODITY
     */
    public BigDecimal getCOMMODITY() {
        return COMMODITY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSAPPL_SEC_COMPONENTS.COMMODITY
     *
     * @param COMMODITY the value for FMSAPPL_SEC_COMPONENTS.COMMODITY
     */
    public void setCOMMODITY(BigDecimal COMMODITY) {
        this.COMMODITY = COMMODITY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSAPPL_SEC_COMPONENTS.COLLECTION_LEVEL
     *
     * @return the value of FMSAPPL_SEC_COMPONENTS.COLLECTION_LEVEL
     */
    public BigDecimal getCOLLECTION_LEVEL() {
        return COLLECTION_LEVEL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSAPPL_SEC_COMPONENTS.COLLECTION_LEVEL
     *
     * @param COLLECTION_LEVEL the value for FMSAPPL_SEC_COMPONENTS.COLLECTION_LEVEL
     */
    public void setCOLLECTION_LEVEL(BigDecimal COLLECTION_LEVEL) {
        this.COLLECTION_LEVEL = COLLECTION_LEVEL;
    }
}