package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class FMSAPPLCHARGESVOKey extends BaseVO {
    /**
     * This field corresponds to the database column FMSAPPLCHARGES.BRANCH_CODE
     */
    private BigDecimal BRANCH_CODE;

    /**
     * This field corresponds to the database column FMSAPPLCHARGES.CHARGES_CODE
     */
    private BigDecimal CHARGES_CODE;

    /**
     * This field corresponds to the database column FMSAPPLCHARGES.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column FMSAPPLCHARGES.LINE_NO
     */
    private BigDecimal LINE_NO;

    /**
     * This field corresponds to the database column FMSAPPLCHARGES.PLAN_LINE_NO
     */
    private BigDecimal PLAN_LINE_NO;

    /**
     * This field corresponds to the database column FMSAPPLCHARGES.SERIAL_NO
     */
    private BigDecimal SERIAL_NO;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSAPPLCHARGES.BRANCH_CODE
     *
     * @return the value of FMSAPPLCHARGES.BRANCH_CODE
     */
    public BigDecimal getBRANCH_CODE() {
        return BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSAPPLCHARGES.BRANCH_CODE
     *
     * @param BRANCH_CODE the value for FMSAPPLCHARGES.BRANCH_CODE
     */
    public void setBRANCH_CODE(BigDecimal BRANCH_CODE) {
        this.BRANCH_CODE = BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSAPPLCHARGES.CHARGES_CODE
     *
     * @return the value of FMSAPPLCHARGES.CHARGES_CODE
     */
    public BigDecimal getCHARGES_CODE() {
        return CHARGES_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSAPPLCHARGES.CHARGES_CODE
     *
     * @param CHARGES_CODE the value for FMSAPPLCHARGES.CHARGES_CODE
     */
    public void setCHARGES_CODE(BigDecimal CHARGES_CODE) {
        this.CHARGES_CODE = CHARGES_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSAPPLCHARGES.COMP_CODE
     *
     * @return the value of FMSAPPLCHARGES.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSAPPLCHARGES.COMP_CODE
     *
     * @param COMP_CODE the value for FMSAPPLCHARGES.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSAPPLCHARGES.LINE_NO
     *
     * @return the value of FMSAPPLCHARGES.LINE_NO
     */
    public BigDecimal getLINE_NO() {
        return LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSAPPLCHARGES.LINE_NO
     *
     * @param LINE_NO the value for FMSAPPLCHARGES.LINE_NO
     */
    public void setLINE_NO(BigDecimal LINE_NO) {
        this.LINE_NO = LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSAPPLCHARGES.PLAN_LINE_NO
     *
     * @return the value of FMSAPPLCHARGES.PLAN_LINE_NO
     */
    public BigDecimal getPLAN_LINE_NO() {
        return PLAN_LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSAPPLCHARGES.PLAN_LINE_NO
     *
     * @param PLAN_LINE_NO the value for FMSAPPLCHARGES.PLAN_LINE_NO
     */
    public void setPLAN_LINE_NO(BigDecimal PLAN_LINE_NO) {
        this.PLAN_LINE_NO = PLAN_LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSAPPLCHARGES.SERIAL_NO
     *
     * @return the value of FMSAPPLCHARGES.SERIAL_NO
     */
    public BigDecimal getSERIAL_NO() {
        return SERIAL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSAPPLCHARGES.SERIAL_NO
     *
     * @param SERIAL_NO the value for FMSAPPLCHARGES.SERIAL_NO
     */
    public void setSERIAL_NO(BigDecimal SERIAL_NO) {
        this.SERIAL_NO = SERIAL_NO;
    }
}