package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class FMSAPPCOLLATERALSVO extends FMSAPPCOLLATERALSVOKey {
    /**
     * This field corresponds to the database column FMSAPPCOLLATERALS.COVERAGE
     */
    private BigDecimal COVERAGE;

    /**
     * This field corresponds to the database column FMSAPPCOLLATERALS.AMOUNT_TYPE
     */
    private String AMOUNT_TYPE;

    /**
     * This field corresponds to the database column FMSAPPCOLLATERALS.ALLOCATED_AMT
     */
    private BigDecimal ALLOCATED_AMT;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSAPPCOLLATERALS.COVERAGE
     *
     * @return the value of FMSAPPCOLLATERALS.COVERAGE
     */
    public BigDecimal getCOVERAGE() {
        return COVERAGE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSAPPCOLLATERALS.COVERAGE
     *
     * @param COVERAGE the value for FMSAPPCOLLATERALS.COVERAGE
     */
    public void setCOVERAGE(BigDecimal COVERAGE) {
        this.COVERAGE = COVERAGE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSAPPCOLLATERALS.AMOUNT_TYPE
     *
     * @return the value of FMSAPPCOLLATERALS.AMOUNT_TYPE
     */
    public String getAMOUNT_TYPE() {
        return AMOUNT_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSAPPCOLLATERALS.AMOUNT_TYPE
     *
     * @param AMOUNT_TYPE the value for FMSAPPCOLLATERALS.AMOUNT_TYPE
     */
    public void setAMOUNT_TYPE(String AMOUNT_TYPE) {
        this.AMOUNT_TYPE = AMOUNT_TYPE == null ? null : AMOUNT_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSAPPCOLLATERALS.ALLOCATED_AMT
     *
     * @return the value of FMSAPPCOLLATERALS.ALLOCATED_AMT
     */
    public BigDecimal getALLOCATED_AMT() {
        return ALLOCATED_AMT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSAPPCOLLATERALS.ALLOCATED_AMT
     *
     * @param ALLOCATED_AMT the value for FMSAPPCOLLATERALS.ALLOCATED_AMT
     */
    public void setALLOCATED_AMT(BigDecimal ALLOCATED_AMT) {
        this.ALLOCATED_AMT = ALLOCATED_AMT;
    }
}