package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class FMSAPPLGUARANTVO extends FMSAPPLGUARANTVOKey {
    /**
     * This field corresponds to the database column FMSAPPLGUARANT.INDICATOR_CODE
     */
    private BigDecimal INDICATOR_CODE;

    /**
     * This field corresponds to the database column FMSAPPLGUARANT.INDICATOR_AMOUNT
     */
    private BigDecimal INDICATOR_AMOUNT;

    /**
     * This field corresponds to the database column FMSAPPLGUARANT.GUARANTOR_CIF
     */
    private BigDecimal GUARANTOR_CIF;

    /**
     * This field corresponds to the database column FMSAPPLGUARANT.CREDIT_RATING
     */
    private BigDecimal CREDIT_RATING;

    /**
     * This field corresponds to the database column FMSAPPLGUARANT.PROFILE
     */
    private BigDecimal PROFILE;

    /**
     * This field corresponds to the database column FMSAPPLGUARANT.RF_CIF_NAME_ENG
     */
    private String RF_CIF_NAME_ENG;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSAPPLGUARANT.INDICATOR_CODE
     *
     * @return the value of FMSAPPLGUARANT.INDICATOR_CODE
     */
    public BigDecimal getINDICATOR_CODE() {
        return INDICATOR_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSAPPLGUARANT.INDICATOR_CODE
     *
     * @param INDICATOR_CODE the value for FMSAPPLGUARANT.INDICATOR_CODE
     */
    public void setINDICATOR_CODE(BigDecimal INDICATOR_CODE) {
        this.INDICATOR_CODE = INDICATOR_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSAPPLGUARANT.INDICATOR_AMOUNT
     *
     * @return the value of FMSAPPLGUARANT.INDICATOR_AMOUNT
     */
    public BigDecimal getINDICATOR_AMOUNT() {
        return INDICATOR_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSAPPLGUARANT.INDICATOR_AMOUNT
     *
     * @param INDICATOR_AMOUNT the value for FMSAPPLGUARANT.INDICATOR_AMOUNT
     */
    public void setINDICATOR_AMOUNT(BigDecimal INDICATOR_AMOUNT) {
        this.INDICATOR_AMOUNT = INDICATOR_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSAPPLGUARANT.GUARANTOR_CIF
     *
     * @return the value of FMSAPPLGUARANT.GUARANTOR_CIF
     */
    public BigDecimal getGUARANTOR_CIF() {
        return GUARANTOR_CIF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSAPPLGUARANT.GUARANTOR_CIF
     *
     * @param GUARANTOR_CIF the value for FMSAPPLGUARANT.GUARANTOR_CIF
     */
    public void setGUARANTOR_CIF(BigDecimal GUARANTOR_CIF) {
        this.GUARANTOR_CIF = GUARANTOR_CIF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSAPPLGUARANT.CREDIT_RATING
     *
     * @return the value of FMSAPPLGUARANT.CREDIT_RATING
     */
    public BigDecimal getCREDIT_RATING() {
        return CREDIT_RATING;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSAPPLGUARANT.CREDIT_RATING
     *
     * @param CREDIT_RATING the value for FMSAPPLGUARANT.CREDIT_RATING
     */
    public void setCREDIT_RATING(BigDecimal CREDIT_RATING) {
        this.CREDIT_RATING = CREDIT_RATING;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSAPPLGUARANT.PROFILE
     *
     * @return the value of FMSAPPLGUARANT.PROFILE
     */
    public BigDecimal getPROFILE() {
        return PROFILE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSAPPLGUARANT.PROFILE
     *
     * @param PROFILE the value for FMSAPPLGUARANT.PROFILE
     */
    public void setPROFILE(BigDecimal PROFILE) {
        this.PROFILE = PROFILE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSAPPLGUARANT.RF_CIF_NAME_ENG
     *
     * @return the value of FMSAPPLGUARANT.RF_CIF_NAME_ENG
     */
    public String getRF_CIF_NAME_ENG() {
        return RF_CIF_NAME_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSAPPLGUARANT.RF_CIF_NAME_ENG
     *
     * @param RF_CIF_NAME_ENG the value for FMSAPPLGUARANT.RF_CIF_NAME_ENG
     */
    public void setRF_CIF_NAME_ENG(String RF_CIF_NAME_ENG) {
        this.RF_CIF_NAME_ENG = RF_CIF_NAME_ENG == null ? null : RF_CIF_NAME_ENG.trim();
    }
}