package com.path.dbmaps.vo;

public class FMSAPPLVOWithBLOBs extends FMSAPPLVO
{
    /**
     * This field corresponds to the database column FMSAPPL.AUDIT_DETAILS
     */
    private String AUDIT_DETAILS;

    /**
     * This field corresponds to the database column FMSAPPL.SPECIAL_CONDITIONS
     */
    private String SPECIAL_CONDITIONS;

    /**
     * This field corresponds to the database column FMSAPPL.RECOMMENDATIONS
     */
    private String RECOMMENDATIONS;

    /**
     * This field corresponds to the database column
     * FMSAPPL.BRANCH_MANAGER_RECOMM
     */
    private String BRANCH_MANAGER_RECOMM;

    /**
     * This field corresponds to the database column FMSAPPL.AUDIT_TRAIL
     */
    private String AUDIT_TRAIL;

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column FMSAPPL.AUDIT_DETAILS
     *
     * @return the value of FMSAPPL.AUDIT_DETAILS
     */
    public String getAUDIT_DETAILS()
    {
	return AUDIT_DETAILS;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column FMSAPPL.AUDIT_DETAILS
     *
     * @param AUDIT_DETAILS the value for FMSAPPL.AUDIT_DETAILS
     */
    public void setAUDIT_DETAILS(String AUDIT_DETAILS)
    {
	this.AUDIT_DETAILS = AUDIT_DETAILS == null ? null : AUDIT_DETAILS.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column FMSAPPL.SPECIAL_CONDITIONS
     *
     * @return the value of FMSAPPL.SPECIAL_CONDITIONS
     */
    public String getSPECIAL_CONDITIONS()
    {
	return SPECIAL_CONDITIONS;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column FMSAPPL.SPECIAL_CONDITIONS
     *
     * @param SPECIAL_CONDITIONS the value for FMSAPPL.SPECIAL_CONDITIONS
     */
    public void setSPECIAL_CONDITIONS(String SPECIAL_CONDITIONS)
    {
	this.SPECIAL_CONDITIONS = SPECIAL_CONDITIONS == null ? null : SPECIAL_CONDITIONS.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column FMSAPPL.RECOMMENDATIONS
     *
     * @return the value of FMSAPPL.RECOMMENDATIONS
     */
    public String getRECOMMENDATIONS()
    {
	return RECOMMENDATIONS;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column FMSAPPL.RECOMMENDATIONS
     *
     * @param RECOMMENDATIONS the value for FMSAPPL.RECOMMENDATIONS
     */
    public void setRECOMMENDATIONS(String RECOMMENDATIONS)
    {
	this.RECOMMENDATIONS = RECOMMENDATIONS == null ? null : RECOMMENDATIONS.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column FMSAPPL.BRANCH_MANAGER_RECOMM
     *
     * @return the value of FMSAPPL.BRANCH_MANAGER_RECOMM
     */
    public String getBRANCH_MANAGER_RECOMM()
    {
	return BRANCH_MANAGER_RECOMM;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column FMSAPPL.BRANCH_MANAGER_RECOMM
     *
     * @param BRANCH_MANAGER_RECOMM the value for FMSAPPL.BRANCH_MANAGER_RECOMM
     */
    public void setBRANCH_MANAGER_RECOMM(String BRANCH_MANAGER_RECOMM)
    {
	this.BRANCH_MANAGER_RECOMM = BRANCH_MANAGER_RECOMM == null ? null : BRANCH_MANAGER_RECOMM.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column FMSAPPL.AUDIT_TRAIL
     *
     * @return the value of FMSAPPL.AUDIT_TRAIL
     */
    public String getAUDIT_TRAIL()
    {
	return AUDIT_TRAIL;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column FMSAPPL.AUDIT_TRAIL
     *
     * @param AUDIT_TRAIL the value for FMSAPPL.AUDIT_TRAIL
     */
    public void setAUDIT_TRAIL(String AUDIT_TRAIL)
    {
	this.AUDIT_TRAIL = AUDIT_TRAIL == null ? null : AUDIT_TRAIL.trim();
    }
}