package com.path.dbmaps.vo;

public class FMSCOLATTYPE_PROPERTYDETVO extends FMSCOLATTYPE_PROPERTYDETVOKey {
    /**
     * This field corresponds to the database column FMSCOLATTYPE_PROPERTYDET.PROPERTY_VALUE_ENG
     */
    private String PROPERTY_VALUE_ENG;

    /**
     * This field corresponds to the database column FMSCOLATTYPE_PROPERTYDET.PROPERTY_VALUE_ARAB
     */
    private String PROPERTY_VALUE_ARAB;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSCOLATTYPE_PROPERTYDET.PROPERTY_VALUE_ENG
     *
     * @return the value of FMSCOLATTYPE_PROPERTYDET.PROPERTY_VALUE_ENG
     */
    public String getPROPERTY_VALUE_ENG() {
        return PROPERTY_VALUE_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSCOLATTYPE_PROPERTYDET.PROPERTY_VALUE_ENG
     *
     * @param PROPERTY_VALUE_ENG the value for FMSCOLATTYPE_PROPERTYDET.PROPERTY_VALUE_ENG
     */
    public void setPROPERTY_VALUE_ENG(String PROPERTY_VALUE_ENG) {
        this.PROPERTY_VALUE_ENG = PROPERTY_VALUE_ENG == null ? null : PROPERTY_VALUE_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSCOLATTYPE_PROPERTYDET.PROPERTY_VALUE_ARAB
     *
     * @return the value of FMSCOLATTYPE_PROPERTYDET.PROPERTY_VALUE_ARAB
     */
    public String getPROPERTY_VALUE_ARAB() {
        return PROPERTY_VALUE_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSCOLATTYPE_PROPERTYDET.PROPERTY_VALUE_ARAB
     *
     * @param PROPERTY_VALUE_ARAB the value for FMSCOLATTYPE_PROPERTYDET.PROPERTY_VALUE_ARAB
     */
    public void setPROPERTY_VALUE_ARAB(String PROPERTY_VALUE_ARAB) {
        this.PROPERTY_VALUE_ARAB = PROPERTY_VALUE_ARAB == null ? null : PROPERTY_VALUE_ARAB.trim();
    }
}