package com.path.dbmaps.vo;

import java.util.Date;

public class FMSCOLATTYPE_PROPERTYVO extends FMSCOLATTYPE_PROPERTYVOKey {
    /**
     * This field corresponds to the database column FMSCOLATTYPE_PROPERTY.BRIEF_DESC_ENG
     */
    private String BRIEF_DESC_ENG;

    /**
     * This field corresponds to the database column FMSCOLATTYPE_PROPERTY.BRIEF_DESC_ARAB
     */
    private String BRIEF_DESC_ARAB;

    /**
     * This field corresponds to the database column FMSCOLATTYPE_PROPERTY.LONG_DESC_ENG
     */
    private String LONG_DESC_ENG;

    /**
     * This field corresponds to the database column FMSCOLATTYPE_PROPERTY.LONG_DESC_ARAB
     */
    private String LONG_DESC_ARAB;

    /**
     * This field corresponds to the database column FMSCOLATTYPE_PROPERTY.DATE_UPDATED
     */
    private Date DATE_UPDATED;

    /**
     * This field corresponds to the database column FMSCOLATTYPE_PROPERTY.UPDATED_BY
     */
    private String UPDATED_BY;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSCOLATTYPE_PROPERTY.BRIEF_DESC_ENG
     *
     * @return the value of FMSCOLATTYPE_PROPERTY.BRIEF_DESC_ENG
     */
    public String getBRIEF_DESC_ENG() {
        return BRIEF_DESC_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSCOLATTYPE_PROPERTY.BRIEF_DESC_ENG
     *
     * @param BRIEF_DESC_ENG the value for FMSCOLATTYPE_PROPERTY.BRIEF_DESC_ENG
     */
    public void setBRIEF_DESC_ENG(String BRIEF_DESC_ENG) {
        this.BRIEF_DESC_ENG = BRIEF_DESC_ENG == null ? null : BRIEF_DESC_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSCOLATTYPE_PROPERTY.BRIEF_DESC_ARAB
     *
     * @return the value of FMSCOLATTYPE_PROPERTY.BRIEF_DESC_ARAB
     */
    public String getBRIEF_DESC_ARAB() {
        return BRIEF_DESC_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSCOLATTYPE_PROPERTY.BRIEF_DESC_ARAB
     *
     * @param BRIEF_DESC_ARAB the value for FMSCOLATTYPE_PROPERTY.BRIEF_DESC_ARAB
     */
    public void setBRIEF_DESC_ARAB(String BRIEF_DESC_ARAB) {
        this.BRIEF_DESC_ARAB = BRIEF_DESC_ARAB == null ? null : BRIEF_DESC_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSCOLATTYPE_PROPERTY.LONG_DESC_ENG
     *
     * @return the value of FMSCOLATTYPE_PROPERTY.LONG_DESC_ENG
     */
    public String getLONG_DESC_ENG() {
        return LONG_DESC_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSCOLATTYPE_PROPERTY.LONG_DESC_ENG
     *
     * @param LONG_DESC_ENG the value for FMSCOLATTYPE_PROPERTY.LONG_DESC_ENG
     */
    public void setLONG_DESC_ENG(String LONG_DESC_ENG) {
        this.LONG_DESC_ENG = LONG_DESC_ENG == null ? null : LONG_DESC_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSCOLATTYPE_PROPERTY.LONG_DESC_ARAB
     *
     * @return the value of FMSCOLATTYPE_PROPERTY.LONG_DESC_ARAB
     */
    public String getLONG_DESC_ARAB() {
        return LONG_DESC_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSCOLATTYPE_PROPERTY.LONG_DESC_ARAB
     *
     * @param LONG_DESC_ARAB the value for FMSCOLATTYPE_PROPERTY.LONG_DESC_ARAB
     */
    public void setLONG_DESC_ARAB(String LONG_DESC_ARAB) {
        this.LONG_DESC_ARAB = LONG_DESC_ARAB == null ? null : LONG_DESC_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSCOLATTYPE_PROPERTY.DATE_UPDATED
     *
     * @return the value of FMSCOLATTYPE_PROPERTY.DATE_UPDATED
     */
    public Date getDATE_UPDATED() {
        return DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSCOLATTYPE_PROPERTY.DATE_UPDATED
     *
     * @param DATE_UPDATED the value for FMSCOLATTYPE_PROPERTY.DATE_UPDATED
     */
    public void setDATE_UPDATED(Date DATE_UPDATED) {
        this.DATE_UPDATED = DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSCOLATTYPE_PROPERTY.UPDATED_BY
     *
     * @return the value of FMSCOLATTYPE_PROPERTY.UPDATED_BY
     */
    public String getUPDATED_BY() {
        return UPDATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSCOLATTYPE_PROPERTY.UPDATED_BY
     *
     * @param UPDATED_BY the value for FMSCOLATTYPE_PROPERTY.UPDATED_BY
     */
    public void setUPDATED_BY(String UPDATED_BY) {
        this.UPDATED_BY = UPDATED_BY == null ? null : UPDATED_BY.trim();
    }
}