package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class FMSCOLLATERAL_ARCHIVEVO extends FMSCOLLATERAL_ARCHIVEVOKey {
    /**
     * This field corresponds to the database column FMSCOLLATERAL_ARCHIVE.DATE_OF_CHANGE
     */
    private Date DATE_OF_CHANGE;

    /**
     * This field corresponds to the database column FMSCOLLATERAL_ARCHIVE.MARKET_VALUE
     */
    private BigDecimal MARKET_VALUE;

    /**
     * This field corresponds to the database column FMSCOLLATERAL_ARCHIVE.MARKET_VALUATION_DATE
     */
    private Date MARKET_VALUATION_DATE;

    /**
     * This field corresponds to the database column FMSCOLLATERAL_ARCHIVE.BANK_VALUE
     */
    private BigDecimal BANK_VALUE;

    /**
     * This field corresponds to the database column FMSCOLLATERAL_ARCHIVE.BANK_VALUATION_DATE
     */
    private Date BANK_VALUATION_DATE;

    /**
     * This field corresponds to the database column FMSCOLLATERAL_ARCHIVE.BOOK_VALUE
     */
    private BigDecimal BOOK_VALUE;

    /**
     * This field corresponds to the database column FMSCOLLATERAL_ARCHIVE.VALID_FROM
     */
    private Date VALID_FROM;

    /**
     * This field corresponds to the database column FMSCOLLATERAL_ARCHIVE.MARKET_CY_RATE
     */
    private BigDecimal MARKET_CY_RATE;

    /**
     * This field corresponds to the database column FMSCOLLATERAL_ARCHIVE.MARKET_CY_UNIT
     */
    private BigDecimal MARKET_CY_UNIT;

    /**
     * This field corresponds to the database column FMSCOLLATERAL_ARCHIVE.MARKET_MULT_DIV
     */
    private String MARKET_MULT_DIV;

    /**
     * This field corresponds to the database column FMSCOLLATERAL_ARCHIVE.BANK_CY_RATE
     */
    private BigDecimal BANK_CY_RATE;

    /**
     * This field corresponds to the database column FMSCOLLATERAL_ARCHIVE.BANK_CY_UNIT
     */
    private BigDecimal BANK_CY_UNIT;

    /**
     * This field corresponds to the database column FMSCOLLATERAL_ARCHIVE.BANK_MULT_DIV
     */
    private String BANK_MULT_DIV;

    /**
     * This field corresponds to the database column FMSCOLLATERAL_ARCHIVE.BOOK_CY_RATE
     */
    private BigDecimal BOOK_CY_RATE;

    /**
     * This field corresponds to the database column FMSCOLLATERAL_ARCHIVE.QTY
     */
    private BigDecimal QTY;

    /**
     * This field corresponds to the database column FMSCOLLATERAL_ARCHIVE.MARKET_PRICE
     */
    private BigDecimal MARKET_PRICE;

    /**
     * This field corresponds to the database column FMSCOLLATERAL_ARCHIVE.ORIGIN_APP
     */
    private String ORIGIN_APP;

    /**
     * This field corresponds to the database column FMSCOLLATERAL_ARCHIVE.VALUE_SECURITY
     */
    private BigDecimal VALUE_SECURITY;

    /**
     * This field corresponds to the database column FMSCOLLATERAL_ARCHIVE.MARKET_PRICE_CV
     */
    private BigDecimal MARKET_PRICE_CV;

    /**
     * This field corresponds to the database column FMSCOLLATERAL_ARCHIVE.AMOUNT
     */
    private BigDecimal AMOUNT;

    /**
     * This field corresponds to the database column FMSCOLLATERAL_ARCHIVE.FORCED_SALE_VALUE
     */
    private BigDecimal FORCED_SALE_VALUE;

    /**
     * This field corresponds to the database column FMSCOLLATERAL_ARCHIVE.FORCED_VALUATION_DATE
     */
    private Date FORCED_VALUATION_DATE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSCOLLATERAL_ARCHIVE.DATE_OF_CHANGE
     *
     * @return the value of FMSCOLLATERAL_ARCHIVE.DATE_OF_CHANGE
     */
    public Date getDATE_OF_CHANGE() {
        return DATE_OF_CHANGE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSCOLLATERAL_ARCHIVE.DATE_OF_CHANGE
     *
     * @param DATE_OF_CHANGE the value for FMSCOLLATERAL_ARCHIVE.DATE_OF_CHANGE
     */
    public void setDATE_OF_CHANGE(Date DATE_OF_CHANGE) {
        this.DATE_OF_CHANGE = DATE_OF_CHANGE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSCOLLATERAL_ARCHIVE.MARKET_VALUE
     *
     * @return the value of FMSCOLLATERAL_ARCHIVE.MARKET_VALUE
     */
    public BigDecimal getMARKET_VALUE() {
        return MARKET_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSCOLLATERAL_ARCHIVE.MARKET_VALUE
     *
     * @param MARKET_VALUE the value for FMSCOLLATERAL_ARCHIVE.MARKET_VALUE
     */
    public void setMARKET_VALUE(BigDecimal MARKET_VALUE) {
        this.MARKET_VALUE = MARKET_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSCOLLATERAL_ARCHIVE.MARKET_VALUATION_DATE
     *
     * @return the value of FMSCOLLATERAL_ARCHIVE.MARKET_VALUATION_DATE
     */
    public Date getMARKET_VALUATION_DATE() {
        return MARKET_VALUATION_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSCOLLATERAL_ARCHIVE.MARKET_VALUATION_DATE
     *
     * @param MARKET_VALUATION_DATE the value for FMSCOLLATERAL_ARCHIVE.MARKET_VALUATION_DATE
     */
    public void setMARKET_VALUATION_DATE(Date MARKET_VALUATION_DATE) {
        this.MARKET_VALUATION_DATE = MARKET_VALUATION_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSCOLLATERAL_ARCHIVE.BANK_VALUE
     *
     * @return the value of FMSCOLLATERAL_ARCHIVE.BANK_VALUE
     */
    public BigDecimal getBANK_VALUE() {
        return BANK_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSCOLLATERAL_ARCHIVE.BANK_VALUE
     *
     * @param BANK_VALUE the value for FMSCOLLATERAL_ARCHIVE.BANK_VALUE
     */
    public void setBANK_VALUE(BigDecimal BANK_VALUE) {
        this.BANK_VALUE = BANK_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSCOLLATERAL_ARCHIVE.BANK_VALUATION_DATE
     *
     * @return the value of FMSCOLLATERAL_ARCHIVE.BANK_VALUATION_DATE
     */
    public Date getBANK_VALUATION_DATE() {
        return BANK_VALUATION_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSCOLLATERAL_ARCHIVE.BANK_VALUATION_DATE
     *
     * @param BANK_VALUATION_DATE the value for FMSCOLLATERAL_ARCHIVE.BANK_VALUATION_DATE
     */
    public void setBANK_VALUATION_DATE(Date BANK_VALUATION_DATE) {
        this.BANK_VALUATION_DATE = BANK_VALUATION_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSCOLLATERAL_ARCHIVE.BOOK_VALUE
     *
     * @return the value of FMSCOLLATERAL_ARCHIVE.BOOK_VALUE
     */
    public BigDecimal getBOOK_VALUE() {
        return BOOK_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSCOLLATERAL_ARCHIVE.BOOK_VALUE
     *
     * @param BOOK_VALUE the value for FMSCOLLATERAL_ARCHIVE.BOOK_VALUE
     */
    public void setBOOK_VALUE(BigDecimal BOOK_VALUE) {
        this.BOOK_VALUE = BOOK_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSCOLLATERAL_ARCHIVE.VALID_FROM
     *
     * @return the value of FMSCOLLATERAL_ARCHIVE.VALID_FROM
     */
    public Date getVALID_FROM() {
        return VALID_FROM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSCOLLATERAL_ARCHIVE.VALID_FROM
     *
     * @param VALID_FROM the value for FMSCOLLATERAL_ARCHIVE.VALID_FROM
     */
    public void setVALID_FROM(Date VALID_FROM) {
        this.VALID_FROM = VALID_FROM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSCOLLATERAL_ARCHIVE.MARKET_CY_RATE
     *
     * @return the value of FMSCOLLATERAL_ARCHIVE.MARKET_CY_RATE
     */
    public BigDecimal getMARKET_CY_RATE() {
        return MARKET_CY_RATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSCOLLATERAL_ARCHIVE.MARKET_CY_RATE
     *
     * @param MARKET_CY_RATE the value for FMSCOLLATERAL_ARCHIVE.MARKET_CY_RATE
     */
    public void setMARKET_CY_RATE(BigDecimal MARKET_CY_RATE) {
        this.MARKET_CY_RATE = MARKET_CY_RATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSCOLLATERAL_ARCHIVE.MARKET_CY_UNIT
     *
     * @return the value of FMSCOLLATERAL_ARCHIVE.MARKET_CY_UNIT
     */
    public BigDecimal getMARKET_CY_UNIT() {
        return MARKET_CY_UNIT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSCOLLATERAL_ARCHIVE.MARKET_CY_UNIT
     *
     * @param MARKET_CY_UNIT the value for FMSCOLLATERAL_ARCHIVE.MARKET_CY_UNIT
     */
    public void setMARKET_CY_UNIT(BigDecimal MARKET_CY_UNIT) {
        this.MARKET_CY_UNIT = MARKET_CY_UNIT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSCOLLATERAL_ARCHIVE.MARKET_MULT_DIV
     *
     * @return the value of FMSCOLLATERAL_ARCHIVE.MARKET_MULT_DIV
     */
    public String getMARKET_MULT_DIV() {
        return MARKET_MULT_DIV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSCOLLATERAL_ARCHIVE.MARKET_MULT_DIV
     *
     * @param MARKET_MULT_DIV the value for FMSCOLLATERAL_ARCHIVE.MARKET_MULT_DIV
     */
    public void setMARKET_MULT_DIV(String MARKET_MULT_DIV) {
        this.MARKET_MULT_DIV = MARKET_MULT_DIV == null ? null : MARKET_MULT_DIV.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSCOLLATERAL_ARCHIVE.BANK_CY_RATE
     *
     * @return the value of FMSCOLLATERAL_ARCHIVE.BANK_CY_RATE
     */
    public BigDecimal getBANK_CY_RATE() {
        return BANK_CY_RATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSCOLLATERAL_ARCHIVE.BANK_CY_RATE
     *
     * @param BANK_CY_RATE the value for FMSCOLLATERAL_ARCHIVE.BANK_CY_RATE
     */
    public void setBANK_CY_RATE(BigDecimal BANK_CY_RATE) {
        this.BANK_CY_RATE = BANK_CY_RATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSCOLLATERAL_ARCHIVE.BANK_CY_UNIT
     *
     * @return the value of FMSCOLLATERAL_ARCHIVE.BANK_CY_UNIT
     */
    public BigDecimal getBANK_CY_UNIT() {
        return BANK_CY_UNIT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSCOLLATERAL_ARCHIVE.BANK_CY_UNIT
     *
     * @param BANK_CY_UNIT the value for FMSCOLLATERAL_ARCHIVE.BANK_CY_UNIT
     */
    public void setBANK_CY_UNIT(BigDecimal BANK_CY_UNIT) {
        this.BANK_CY_UNIT = BANK_CY_UNIT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSCOLLATERAL_ARCHIVE.BANK_MULT_DIV
     *
     * @return the value of FMSCOLLATERAL_ARCHIVE.BANK_MULT_DIV
     */
    public String getBANK_MULT_DIV() {
        return BANK_MULT_DIV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSCOLLATERAL_ARCHIVE.BANK_MULT_DIV
     *
     * @param BANK_MULT_DIV the value for FMSCOLLATERAL_ARCHIVE.BANK_MULT_DIV
     */
    public void setBANK_MULT_DIV(String BANK_MULT_DIV) {
        this.BANK_MULT_DIV = BANK_MULT_DIV == null ? null : BANK_MULT_DIV.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSCOLLATERAL_ARCHIVE.BOOK_CY_RATE
     *
     * @return the value of FMSCOLLATERAL_ARCHIVE.BOOK_CY_RATE
     */
    public BigDecimal getBOOK_CY_RATE() {
        return BOOK_CY_RATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSCOLLATERAL_ARCHIVE.BOOK_CY_RATE
     *
     * @param BOOK_CY_RATE the value for FMSCOLLATERAL_ARCHIVE.BOOK_CY_RATE
     */
    public void setBOOK_CY_RATE(BigDecimal BOOK_CY_RATE) {
        this.BOOK_CY_RATE = BOOK_CY_RATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSCOLLATERAL_ARCHIVE.QTY
     *
     * @return the value of FMSCOLLATERAL_ARCHIVE.QTY
     */
    public BigDecimal getQTY() {
        return QTY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSCOLLATERAL_ARCHIVE.QTY
     *
     * @param QTY the value for FMSCOLLATERAL_ARCHIVE.QTY
     */
    public void setQTY(BigDecimal QTY) {
        this.QTY = QTY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSCOLLATERAL_ARCHIVE.MARKET_PRICE
     *
     * @return the value of FMSCOLLATERAL_ARCHIVE.MARKET_PRICE
     */
    public BigDecimal getMARKET_PRICE() {
        return MARKET_PRICE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSCOLLATERAL_ARCHIVE.MARKET_PRICE
     *
     * @param MARKET_PRICE the value for FMSCOLLATERAL_ARCHIVE.MARKET_PRICE
     */
    public void setMARKET_PRICE(BigDecimal MARKET_PRICE) {
        this.MARKET_PRICE = MARKET_PRICE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSCOLLATERAL_ARCHIVE.ORIGIN_APP
     *
     * @return the value of FMSCOLLATERAL_ARCHIVE.ORIGIN_APP
     */
    public String getORIGIN_APP() {
        return ORIGIN_APP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSCOLLATERAL_ARCHIVE.ORIGIN_APP
     *
     * @param ORIGIN_APP the value for FMSCOLLATERAL_ARCHIVE.ORIGIN_APP
     */
    public void setORIGIN_APP(String ORIGIN_APP) {
        this.ORIGIN_APP = ORIGIN_APP == null ? null : ORIGIN_APP.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSCOLLATERAL_ARCHIVE.VALUE_SECURITY
     *
     * @return the value of FMSCOLLATERAL_ARCHIVE.VALUE_SECURITY
     */
    public BigDecimal getVALUE_SECURITY() {
        return VALUE_SECURITY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSCOLLATERAL_ARCHIVE.VALUE_SECURITY
     *
     * @param VALUE_SECURITY the value for FMSCOLLATERAL_ARCHIVE.VALUE_SECURITY
     */
    public void setVALUE_SECURITY(BigDecimal VALUE_SECURITY) {
        this.VALUE_SECURITY = VALUE_SECURITY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSCOLLATERAL_ARCHIVE.MARKET_PRICE_CV
     *
     * @return the value of FMSCOLLATERAL_ARCHIVE.MARKET_PRICE_CV
     */
    public BigDecimal getMARKET_PRICE_CV() {
        return MARKET_PRICE_CV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSCOLLATERAL_ARCHIVE.MARKET_PRICE_CV
     *
     * @param MARKET_PRICE_CV the value for FMSCOLLATERAL_ARCHIVE.MARKET_PRICE_CV
     */
    public void setMARKET_PRICE_CV(BigDecimal MARKET_PRICE_CV) {
        this.MARKET_PRICE_CV = MARKET_PRICE_CV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSCOLLATERAL_ARCHIVE.AMOUNT
     *
     * @return the value of FMSCOLLATERAL_ARCHIVE.AMOUNT
     */
    public BigDecimal getAMOUNT() {
        return AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSCOLLATERAL_ARCHIVE.AMOUNT
     *
     * @param AMOUNT the value for FMSCOLLATERAL_ARCHIVE.AMOUNT
     */
    public void setAMOUNT(BigDecimal AMOUNT) {
        this.AMOUNT = AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSCOLLATERAL_ARCHIVE.FORCED_SALE_VALUE
     *
     * @return the value of FMSCOLLATERAL_ARCHIVE.FORCED_SALE_VALUE
     */
    public BigDecimal getFORCED_SALE_VALUE() {
        return FORCED_SALE_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSCOLLATERAL_ARCHIVE.FORCED_SALE_VALUE
     *
     * @param FORCED_SALE_VALUE the value for FMSCOLLATERAL_ARCHIVE.FORCED_SALE_VALUE
     */
    public void setFORCED_SALE_VALUE(BigDecimal FORCED_SALE_VALUE) {
        this.FORCED_SALE_VALUE = FORCED_SALE_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSCOLLATERAL_ARCHIVE.FORCED_VALUATION_DATE
     *
     * @return the value of FMSCOLLATERAL_ARCHIVE.FORCED_VALUATION_DATE
     */
    public Date getFORCED_VALUATION_DATE() {
        return FORCED_VALUATION_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSCOLLATERAL_ARCHIVE.FORCED_VALUATION_DATE
     *
     * @param FORCED_VALUATION_DATE the value for FMSCOLLATERAL_ARCHIVE.FORCED_VALUATION_DATE
     */
    public void setFORCED_VALUATION_DATE(Date FORCED_VALUATION_DATE) {
        this.FORCED_VALUATION_DATE = FORCED_VALUATION_DATE;
    }
}