package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class FMSCLOSUREVO extends FMSCLOSUREVOKey
{
    /**
     * This field corresponds to the database column FMSCLOSURE.FACILITY
     */
    private BigDecimal FACILITY;

    /**
     * This field corresponds to the database column FMSCLOSURE.CLOSURE_REASON
     */
    private String CLOSURE_REASON;

    /**
     * This field corresponds to the database column FMSCLOSURE.STATUS
     */
    private String STATUS;

    /**
     * This field corresponds to the database column FMSCLOSURE.DATE_REQUESTED
     */
    private Date DATE_REQUESTED;

    /**
     * This field corresponds to the database column FMSCLOSURE.REQUESTED_BY
     */
    private String REQUESTED_BY;

    /**
     * This field corresponds to the database column FMSCLOSURE.DATE_CREATED
     */
    private Date DATE_CREATED;

    /**
     * This field corresponds to the database column FMSCLOSURE.CREATED_BY
     */
    private String CREATED_BY;

    /**
     * This field corresponds to the database column FMSCLOSURE.DATE_UPDATED
     */
    private Date DATE_UPDATED;

    /**
     * This field corresponds to the database column FMSCLOSURE.UPDATED_BY
     */
    private String UPDATED_BY;

    /**
     * This field corresponds to the database column FMSCLOSURE.DATE_DELETED
     */
    private Date DATE_DELETED;

    /**
     * This field corresponds to the database column FMSCLOSURE.DELETED_BY
     */
    private String DELETED_BY;

    /**
     * This field corresponds to the database column FMSCLOSURE.DATE_APPROVED
     */
    private Date DATE_APPROVED;

    /**
     * This field corresponds to the database column FMSCLOSURE.APPROVED_BY
     */
    private String APPROVED_BY;

    /**
     * This field corresponds to the database column FMSCLOSURE.DATE_REVERSED
     */
    private Date DATE_REVERSED;

    /**
     * This field corresponds to the database column FMSCLOSURE.REVERSED_BY
     */
    private String REVERSED_BY;

    /**
     * This field corresponds to the database column FMSCLOSURE.DATE_MODIFIED
     */
    private Date DATE_MODIFIED;

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column FMSCLOSURE.FACILITY
     * 
     * @return the value of FMSCLOSURE.FACILITY
     */
    public BigDecimal getFACILITY()
    {
	return FACILITY;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column FMSCLOSURE.FACILITY
     * 
     * @param FACILITY the value for FMSCLOSURE.FACILITY
     */
    public void setFACILITY(BigDecimal FACILITY)
    {
	this.FACILITY = FACILITY;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column FMSCLOSURE.CLOSURE_REASON
     * 
     * @return the value of FMSCLOSURE.CLOSURE_REASON
     */
    public String getCLOSURE_REASON()
    {
	return CLOSURE_REASON;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column FMSCLOSURE.CLOSURE_REASON
     * 
     * @param CLOSURE_REASON the value for FMSCLOSURE.CLOSURE_REASON
     */
    public void setCLOSURE_REASON(String CLOSURE_REASON)
    {
	this.CLOSURE_REASON = CLOSURE_REASON == null ? null : CLOSURE_REASON.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column FMSCLOSURE.STATUS
     * 
     * @return the value of FMSCLOSURE.STATUS
     */
    public String getSTATUS()
    {
	return STATUS;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column FMSCLOSURE.STATUS
     * 
     * @param STATUS the value for FMSCLOSURE.STATUS
     */
    public void setSTATUS(String STATUS)
    {
	this.STATUS = STATUS == null ? null : STATUS.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column FMSCLOSURE.DATE_REQUESTED
     * 
     * @return the value of FMSCLOSURE.DATE_REQUESTED
     */
    public Date getDATE_REQUESTED()
    {
	return DATE_REQUESTED;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column FMSCLOSURE.DATE_REQUESTED
     * 
     * @param DATE_REQUESTED the value for FMSCLOSURE.DATE_REQUESTED
     */
    public void setDATE_REQUESTED(Date DATE_REQUESTED)
    {
	this.DATE_REQUESTED = DATE_REQUESTED;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column FMSCLOSURE.REQUESTED_BY
     * 
     * @return the value of FMSCLOSURE.REQUESTED_BY
     */
    public String getREQUESTED_BY()
    {
	return REQUESTED_BY;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column FMSCLOSURE.REQUESTED_BY
     * 
     * @param REQUESTED_BY the value for FMSCLOSURE.REQUESTED_BY
     */
    public void setREQUESTED_BY(String REQUESTED_BY)
    {
	this.REQUESTED_BY = REQUESTED_BY == null ? null : REQUESTED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column FMSCLOSURE.DATE_CREATED
     * 
     * @return the value of FMSCLOSURE.DATE_CREATED
     */
    public Date getDATE_CREATED()
    {
	return DATE_CREATED;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column FMSCLOSURE.DATE_CREATED
     * 
     * @param DATE_CREATED the value for FMSCLOSURE.DATE_CREATED
     */
    public void setDATE_CREATED(Date DATE_CREATED)
    {
	this.DATE_CREATED = DATE_CREATED;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column FMSCLOSURE.CREATED_BY
     * 
     * @return the value of FMSCLOSURE.CREATED_BY
     */
    public String getCREATED_BY()
    {
	return CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column FMSCLOSURE.CREATED_BY
     * 
     * @param CREATED_BY the value for FMSCLOSURE.CREATED_BY
     */
    public void setCREATED_BY(String CREATED_BY)
    {
	this.CREATED_BY = CREATED_BY == null ? null : CREATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column FMSCLOSURE.DATE_UPDATED
     * 
     * @return the value of FMSCLOSURE.DATE_UPDATED
     */
    public Date getDATE_UPDATED()
    {
	return DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column FMSCLOSURE.DATE_UPDATED
     * 
     * @param DATE_UPDATED the value for FMSCLOSURE.DATE_UPDATED
     */
    public void setDATE_UPDATED(Date DATE_UPDATED)
    {
	this.DATE_UPDATED = DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column FMSCLOSURE.UPDATED_BY
     * 
     * @return the value of FMSCLOSURE.UPDATED_BY
     */
    public String getUPDATED_BY()
    {
	return UPDATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column FMSCLOSURE.UPDATED_BY
     * 
     * @param UPDATED_BY the value for FMSCLOSURE.UPDATED_BY
     */
    public void setUPDATED_BY(String UPDATED_BY)
    {
	this.UPDATED_BY = UPDATED_BY == null ? null : UPDATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column FMSCLOSURE.DATE_DELETED
     * 
     * @return the value of FMSCLOSURE.DATE_DELETED
     */
    public Date getDATE_DELETED()
    {
	return DATE_DELETED;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column FMSCLOSURE.DATE_DELETED
     * 
     * @param DATE_DELETED the value for FMSCLOSURE.DATE_DELETED
     */
    public void setDATE_DELETED(Date DATE_DELETED)
    {
	this.DATE_DELETED = DATE_DELETED;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column FMSCLOSURE.DELETED_BY
     * 
     * @return the value of FMSCLOSURE.DELETED_BY
     */
    public String getDELETED_BY()
    {
	return DELETED_BY;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column FMSCLOSURE.DELETED_BY
     * 
     * @param DELETED_BY the value for FMSCLOSURE.DELETED_BY
     */
    public void setDELETED_BY(String DELETED_BY)
    {
	this.DELETED_BY = DELETED_BY == null ? null : DELETED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column FMSCLOSURE.DATE_APPROVED
     * 
     * @return the value of FMSCLOSURE.DATE_APPROVED
     */
    public Date getDATE_APPROVED()
    {
	return DATE_APPROVED;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column FMSCLOSURE.DATE_APPROVED
     * 
     * @param DATE_APPROVED the value for FMSCLOSURE.DATE_APPROVED
     */
    public void setDATE_APPROVED(Date DATE_APPROVED)
    {
	this.DATE_APPROVED = DATE_APPROVED;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column FMSCLOSURE.APPROVED_BY
     * 
     * @return the value of FMSCLOSURE.APPROVED_BY
     */
    public String getAPPROVED_BY()
    {
	return APPROVED_BY;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column FMSCLOSURE.APPROVED_BY
     * 
     * @param APPROVED_BY the value for FMSCLOSURE.APPROVED_BY
     */
    public void setAPPROVED_BY(String APPROVED_BY)
    {
	this.APPROVED_BY = APPROVED_BY == null ? null : APPROVED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column FMSCLOSURE.DATE_REVERSED
     * 
     * @return the value of FMSCLOSURE.DATE_REVERSED
     */
    public Date getDATE_REVERSED()
    {
	return DATE_REVERSED;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column FMSCLOSURE.DATE_REVERSED
     * 
     * @param DATE_REVERSED the value for FMSCLOSURE.DATE_REVERSED
     */
    public void setDATE_REVERSED(Date DATE_REVERSED)
    {
	this.DATE_REVERSED = DATE_REVERSED;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column FMSCLOSURE.REVERSED_BY
     * 
     * @return the value of FMSCLOSURE.REVERSED_BY
     */
    public String getREVERSED_BY()
    {
	return REVERSED_BY;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column FMSCLOSURE.REVERSED_BY
     * 
     * @param REVERSED_BY the value for FMSCLOSURE.REVERSED_BY
     */
    public void setREVERSED_BY(String REVERSED_BY)
    {
	this.REVERSED_BY = REVERSED_BY == null ? null : REVERSED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column FMSCLOSURE.DATE_MODIFIED
     * 
     * @return the value of FMSCLOSURE.DATE_MODIFIED
     */
    public Date getDATE_MODIFIED()
    {
	return DATE_MODIFIED;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column FMSCLOSURE.DATE_MODIFIED
     * 
     * @param DATE_MODIFIED the value for FMSCLOSURE.DATE_MODIFIED
     */
    public void setDATE_MODIFIED(Date DATE_MODIFIED)
    {
	this.DATE_MODIFIED = DATE_MODIFIED;
    }
}