package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class FMSCOLLATERAL_INSURVOKey extends BaseVO {
    /**
     * This field corresponds to the database column FMSCOLLATERAL_INSUR.BRANCH_CODE
     */
    private BigDecimal BRANCH_CODE;

    /**
     * This field corresponds to the database column FMSCOLLATERAL_INSUR.COLLATERAL_CODE
     */
    private BigDecimal COLLATERAL_CODE;

    /**
     * This field corresponds to the database column FMSCOLLATERAL_INSUR.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column FMSCOLLATERAL_INSUR.INSURANCE_CODE
     */
    private BigDecimal INSURANCE_CODE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSCOLLATERAL_INSUR.BRANCH_CODE
     *
     * @return the value of FMSCOLLATERAL_INSUR.BRANCH_CODE
     */
    public BigDecimal getBRANCH_CODE() {
        return BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSCOLLATERAL_INSUR.BRANCH_CODE
     *
     * @param BRANCH_CODE the value for FMSCOLLATERAL_INSUR.BRANCH_CODE
     */
    public void setBRANCH_CODE(BigDecimal BRANCH_CODE) {
        this.BRANCH_CODE = BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSCOLLATERAL_INSUR.COLLATERAL_CODE
     *
     * @return the value of FMSCOLLATERAL_INSUR.COLLATERAL_CODE
     */
    public BigDecimal getCOLLATERAL_CODE() {
        return COLLATERAL_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSCOLLATERAL_INSUR.COLLATERAL_CODE
     *
     * @param COLLATERAL_CODE the value for FMSCOLLATERAL_INSUR.COLLATERAL_CODE
     */
    public void setCOLLATERAL_CODE(BigDecimal COLLATERAL_CODE) {
        this.COLLATERAL_CODE = COLLATERAL_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSCOLLATERAL_INSUR.COMP_CODE
     *
     * @return the value of FMSCOLLATERAL_INSUR.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSCOLLATERAL_INSUR.COMP_CODE
     *
     * @param COMP_CODE the value for FMSCOLLATERAL_INSUR.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSCOLLATERAL_INSUR.INSURANCE_CODE
     *
     * @return the value of FMSCOLLATERAL_INSUR.INSURANCE_CODE
     */
    public BigDecimal getINSURANCE_CODE() {
        return INSURANCE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSCOLLATERAL_INSUR.INSURANCE_CODE
     *
     * @param INSURANCE_CODE the value for FMSCOLLATERAL_INSUR.INSURANCE_CODE
     */
    public void setINSURANCE_CODE(BigDecimal INSURANCE_CODE) {
        this.INSURANCE_CODE = INSURANCE_CODE;
    }
}