package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class FMSCOLLAT_OFF_BS_TEMPLATEVO extends FMSCOLLAT_OFF_BS_TEMPLATEVOKey {
    /**
     * This field corresponds to the database column FMSCOLLAT_OFF_BS_TEMPLATE.ACC_SIGN
     */
    private String ACC_SIGN;

    /**
     * This field corresponds to the database column FMSCOLLAT_OFF_BS_TEMPLATE.ACC_BRANCH_TYPE
     */
    private String ACC_BRANCH_TYPE;

    /**
     * This field corresponds to the database column FMSCOLLAT_OFF_BS_TEMPLATE.ACC_BRANCH_CODE
     */
    private BigDecimal ACC_BRANCH_CODE;

    /**
     * This field corresponds to the database column FMSCOLLAT_OFF_BS_TEMPLATE.ACC_CUR_TYPE
     */
    private String ACC_CUR_TYPE;

    /**
     * This field corresponds to the database column FMSCOLLAT_OFF_BS_TEMPLATE.ACC_GL_CODE
     */
    private BigDecimal ACC_GL_CODE;

    /**
     * This field corresponds to the database column FMSCOLLAT_OFF_BS_TEMPLATE.ACC_CIF_TYPE
     */
    private String ACC_CIF_TYPE;

    /**
     * This field corresponds to the database column FMSCOLLAT_OFF_BS_TEMPLATE.ACC_CIF_NO
     */
    private BigDecimal ACC_CIF_NO;

    /**
     * This field corresponds to the database column FMSCOLLAT_OFF_BS_TEMPLATE.ACC_SL_TYPE
     */
    private String ACC_SL_TYPE;

    /**
     * This field corresponds to the database column FMSCOLLAT_OFF_BS_TEMPLATE.ACC_SL_NO
     */
    private BigDecimal ACC_SL_NO;

    /**
     * This field corresponds to the database column FMSCOLLAT_OFF_BS_TEMPLATE.CREATED_BY
     */
    private String CREATED_BY;

    /**
     * This field corresponds to the database column FMSCOLLAT_OFF_BS_TEMPLATE.CREATED_DATE
     */
    private Date CREATED_DATE;

    /**
     * This field corresponds to the database column FMSCOLLAT_OFF_BS_TEMPLATE.MODIFIED_BY
     */
    private String MODIFIED_BY;

    /**
     * This field corresponds to the database column FMSCOLLAT_OFF_BS_TEMPLATE.MODIFIED_DATE
     */
    private Date MODIFIED_DATE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSCOLLAT_OFF_BS_TEMPLATE.ACC_SIGN
     *
     * @return the value of FMSCOLLAT_OFF_BS_TEMPLATE.ACC_SIGN
     */
    public String getACC_SIGN() {
        return ACC_SIGN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSCOLLAT_OFF_BS_TEMPLATE.ACC_SIGN
     *
     * @param ACC_SIGN the value for FMSCOLLAT_OFF_BS_TEMPLATE.ACC_SIGN
     */
    public void setACC_SIGN(String ACC_SIGN) {
        this.ACC_SIGN = ACC_SIGN == null ? null : ACC_SIGN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSCOLLAT_OFF_BS_TEMPLATE.ACC_BRANCH_TYPE
     *
     * @return the value of FMSCOLLAT_OFF_BS_TEMPLATE.ACC_BRANCH_TYPE
     */
    public String getACC_BRANCH_TYPE() {
        return ACC_BRANCH_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSCOLLAT_OFF_BS_TEMPLATE.ACC_BRANCH_TYPE
     *
     * @param ACC_BRANCH_TYPE the value for FMSCOLLAT_OFF_BS_TEMPLATE.ACC_BRANCH_TYPE
     */
    public void setACC_BRANCH_TYPE(String ACC_BRANCH_TYPE) {
        this.ACC_BRANCH_TYPE = ACC_BRANCH_TYPE == null ? null : ACC_BRANCH_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSCOLLAT_OFF_BS_TEMPLATE.ACC_BRANCH_CODE
     *
     * @return the value of FMSCOLLAT_OFF_BS_TEMPLATE.ACC_BRANCH_CODE
     */
    public BigDecimal getACC_BRANCH_CODE() {
        return ACC_BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSCOLLAT_OFF_BS_TEMPLATE.ACC_BRANCH_CODE
     *
     * @param ACC_BRANCH_CODE the value for FMSCOLLAT_OFF_BS_TEMPLATE.ACC_BRANCH_CODE
     */
    public void setACC_BRANCH_CODE(BigDecimal ACC_BRANCH_CODE) {
        this.ACC_BRANCH_CODE = ACC_BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSCOLLAT_OFF_BS_TEMPLATE.ACC_CUR_TYPE
     *
     * @return the value of FMSCOLLAT_OFF_BS_TEMPLATE.ACC_CUR_TYPE
     */
    public String getACC_CUR_TYPE() {
        return ACC_CUR_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSCOLLAT_OFF_BS_TEMPLATE.ACC_CUR_TYPE
     *
     * @param ACC_CUR_TYPE the value for FMSCOLLAT_OFF_BS_TEMPLATE.ACC_CUR_TYPE
     */
    public void setACC_CUR_TYPE(String ACC_CUR_TYPE) {
        this.ACC_CUR_TYPE = ACC_CUR_TYPE == null ? null : ACC_CUR_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSCOLLAT_OFF_BS_TEMPLATE.ACC_GL_CODE
     *
     * @return the value of FMSCOLLAT_OFF_BS_TEMPLATE.ACC_GL_CODE
     */
    public BigDecimal getACC_GL_CODE() {
        return ACC_GL_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSCOLLAT_OFF_BS_TEMPLATE.ACC_GL_CODE
     *
     * @param ACC_GL_CODE the value for FMSCOLLAT_OFF_BS_TEMPLATE.ACC_GL_CODE
     */
    public void setACC_GL_CODE(BigDecimal ACC_GL_CODE) {
        this.ACC_GL_CODE = ACC_GL_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSCOLLAT_OFF_BS_TEMPLATE.ACC_CIF_TYPE
     *
     * @return the value of FMSCOLLAT_OFF_BS_TEMPLATE.ACC_CIF_TYPE
     */
    public String getACC_CIF_TYPE() {
        return ACC_CIF_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSCOLLAT_OFF_BS_TEMPLATE.ACC_CIF_TYPE
     *
     * @param ACC_CIF_TYPE the value for FMSCOLLAT_OFF_BS_TEMPLATE.ACC_CIF_TYPE
     */
    public void setACC_CIF_TYPE(String ACC_CIF_TYPE) {
        this.ACC_CIF_TYPE = ACC_CIF_TYPE == null ? null : ACC_CIF_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSCOLLAT_OFF_BS_TEMPLATE.ACC_CIF_NO
     *
     * @return the value of FMSCOLLAT_OFF_BS_TEMPLATE.ACC_CIF_NO
     */
    public BigDecimal getACC_CIF_NO() {
        return ACC_CIF_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSCOLLAT_OFF_BS_TEMPLATE.ACC_CIF_NO
     *
     * @param ACC_CIF_NO the value for FMSCOLLAT_OFF_BS_TEMPLATE.ACC_CIF_NO
     */
    public void setACC_CIF_NO(BigDecimal ACC_CIF_NO) {
        this.ACC_CIF_NO = ACC_CIF_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSCOLLAT_OFF_BS_TEMPLATE.ACC_SL_TYPE
     *
     * @return the value of FMSCOLLAT_OFF_BS_TEMPLATE.ACC_SL_TYPE
     */
    public String getACC_SL_TYPE() {
        return ACC_SL_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSCOLLAT_OFF_BS_TEMPLATE.ACC_SL_TYPE
     *
     * @param ACC_SL_TYPE the value for FMSCOLLAT_OFF_BS_TEMPLATE.ACC_SL_TYPE
     */
    public void setACC_SL_TYPE(String ACC_SL_TYPE) {
        this.ACC_SL_TYPE = ACC_SL_TYPE == null ? null : ACC_SL_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSCOLLAT_OFF_BS_TEMPLATE.ACC_SL_NO
     *
     * @return the value of FMSCOLLAT_OFF_BS_TEMPLATE.ACC_SL_NO
     */
    public BigDecimal getACC_SL_NO() {
        return ACC_SL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSCOLLAT_OFF_BS_TEMPLATE.ACC_SL_NO
     *
     * @param ACC_SL_NO the value for FMSCOLLAT_OFF_BS_TEMPLATE.ACC_SL_NO
     */
    public void setACC_SL_NO(BigDecimal ACC_SL_NO) {
        this.ACC_SL_NO = ACC_SL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSCOLLAT_OFF_BS_TEMPLATE.CREATED_BY
     *
     * @return the value of FMSCOLLAT_OFF_BS_TEMPLATE.CREATED_BY
     */
    public String getCREATED_BY() {
        return CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSCOLLAT_OFF_BS_TEMPLATE.CREATED_BY
     *
     * @param CREATED_BY the value for FMSCOLLAT_OFF_BS_TEMPLATE.CREATED_BY
     */
    public void setCREATED_BY(String CREATED_BY) {
        this.CREATED_BY = CREATED_BY == null ? null : CREATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSCOLLAT_OFF_BS_TEMPLATE.CREATED_DATE
     *
     * @return the value of FMSCOLLAT_OFF_BS_TEMPLATE.CREATED_DATE
     */
    public Date getCREATED_DATE() {
        return CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSCOLLAT_OFF_BS_TEMPLATE.CREATED_DATE
     *
     * @param CREATED_DATE the value for FMSCOLLAT_OFF_BS_TEMPLATE.CREATED_DATE
     */
    public void setCREATED_DATE(Date CREATED_DATE) {
        this.CREATED_DATE = CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSCOLLAT_OFF_BS_TEMPLATE.MODIFIED_BY
     *
     * @return the value of FMSCOLLAT_OFF_BS_TEMPLATE.MODIFIED_BY
     */
    public String getMODIFIED_BY() {
        return MODIFIED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSCOLLAT_OFF_BS_TEMPLATE.MODIFIED_BY
     *
     * @param MODIFIED_BY the value for FMSCOLLAT_OFF_BS_TEMPLATE.MODIFIED_BY
     */
    public void setMODIFIED_BY(String MODIFIED_BY) {
        this.MODIFIED_BY = MODIFIED_BY == null ? null : MODIFIED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSCOLLAT_OFF_BS_TEMPLATE.MODIFIED_DATE
     *
     * @return the value of FMSCOLLAT_OFF_BS_TEMPLATE.MODIFIED_DATE
     */
    public Date getMODIFIED_DATE() {
        return MODIFIED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSCOLLAT_OFF_BS_TEMPLATE.MODIFIED_DATE
     *
     * @param MODIFIED_DATE the value for FMSCOLLAT_OFF_BS_TEMPLATE.MODIFIED_DATE
     */
    public void setMODIFIED_DATE(Date MODIFIED_DATE) {
        this.MODIFIED_DATE = MODIFIED_DATE;
    }
}