package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class FMSCOLLATERAL_INSUR_COLLVOKey extends BaseVO {
    /**
     * This field corresponds to the database column FMSCOLLATERAL_INSUR_COLL.BRANCH_CODE
     */
    private BigDecimal BRANCH_CODE;

    /**
     * This field corresponds to the database column FMSCOLLATERAL_INSUR_COLL.COLLATERAL_NO
     */
    private BigDecimal COLLATERAL_NO;

    /**
     * This field corresponds to the database column FMSCOLLATERAL_INSUR_COLL.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column FMSCOLLATERAL_INSUR_COLL.LINE_NO
     */
    private BigDecimal LINE_NO;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSCOLLATERAL_INSUR_COLL.BRANCH_CODE
     *
     * @return the value of FMSCOLLATERAL_INSUR_COLL.BRANCH_CODE
     */
    public BigDecimal getBRANCH_CODE() {
        return BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSCOLLATERAL_INSUR_COLL.BRANCH_CODE
     *
     * @param BRANCH_CODE the value for FMSCOLLATERAL_INSUR_COLL.BRANCH_CODE
     */
    public void setBRANCH_CODE(BigDecimal BRANCH_CODE) {
        this.BRANCH_CODE = BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSCOLLATERAL_INSUR_COLL.COLLATERAL_NO
     *
     * @return the value of FMSCOLLATERAL_INSUR_COLL.COLLATERAL_NO
     */
    public BigDecimal getCOLLATERAL_NO() {
        return COLLATERAL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSCOLLATERAL_INSUR_COLL.COLLATERAL_NO
     *
     * @param COLLATERAL_NO the value for FMSCOLLATERAL_INSUR_COLL.COLLATERAL_NO
     */
    public void setCOLLATERAL_NO(BigDecimal COLLATERAL_NO) {
        this.COLLATERAL_NO = COLLATERAL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSCOLLATERAL_INSUR_COLL.COMP_CODE
     *
     * @return the value of FMSCOLLATERAL_INSUR_COLL.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSCOLLATERAL_INSUR_COLL.COMP_CODE
     *
     * @param COMP_CODE the value for FMSCOLLATERAL_INSUR_COLL.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSCOLLATERAL_INSUR_COLL.LINE_NO
     *
     * @return the value of FMSCOLLATERAL_INSUR_COLL.LINE_NO
     */
    public BigDecimal getLINE_NO() {
        return LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSCOLLATERAL_INSUR_COLL.LINE_NO
     *
     * @param LINE_NO the value for FMSCOLLATERAL_INSUR_COLL.LINE_NO
     */
    public void setLINE_NO(BigDecimal LINE_NO) {
        this.LINE_NO = LINE_NO;
    }
}