package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class FMSDRWHSTVO extends FMSDRWHSTVOKey {
    /**
     * This field corresponds to the database column FMSDRWHST.ORIGINAL_AMT
     */
    private BigDecimal ORIGINAL_AMT;

    /**
     * This field corresponds to the database column FMSDRWHST.NEW_AMT
     */
    private BigDecimal NEW_AMT;

    /**
     * This field corresponds to the database column FMSDRWHST.DATE_CREATED
     */
    private Date DATE_CREATED;

    /**
     * This field corresponds to the database column FMSDRWHST.DATE_UPDATED
     */
    private Date DATE_UPDATED;

    /**
     * This field corresponds to the database column FMSDRWHST.CREATED_BY
     */
    private String CREATED_BY;

    /**
     * This field corresponds to the database column FMSDRWHST.UPDATED_BY
     */
    private String UPDATED_BY;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSDRWHST.ORIGINAL_AMT
     *
     * @return the value of FMSDRWHST.ORIGINAL_AMT
     */
    public BigDecimal getORIGINAL_AMT() {
        return ORIGINAL_AMT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSDRWHST.ORIGINAL_AMT
     *
     * @param ORIGINAL_AMT the value for FMSDRWHST.ORIGINAL_AMT
     */
    public void setORIGINAL_AMT(BigDecimal ORIGINAL_AMT) {
        this.ORIGINAL_AMT = ORIGINAL_AMT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSDRWHST.NEW_AMT
     *
     * @return the value of FMSDRWHST.NEW_AMT
     */
    public BigDecimal getNEW_AMT() {
        return NEW_AMT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSDRWHST.NEW_AMT
     *
     * @param NEW_AMT the value for FMSDRWHST.NEW_AMT
     */
    public void setNEW_AMT(BigDecimal NEW_AMT) {
        this.NEW_AMT = NEW_AMT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSDRWHST.DATE_CREATED
     *
     * @return the value of FMSDRWHST.DATE_CREATED
     */
    public Date getDATE_CREATED() {
        return DATE_CREATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSDRWHST.DATE_CREATED
     *
     * @param DATE_CREATED the value for FMSDRWHST.DATE_CREATED
     */
    public void setDATE_CREATED(Date DATE_CREATED) {
        this.DATE_CREATED = DATE_CREATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSDRWHST.DATE_UPDATED
     *
     * @return the value of FMSDRWHST.DATE_UPDATED
     */
    public Date getDATE_UPDATED() {
        return DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSDRWHST.DATE_UPDATED
     *
     * @param DATE_UPDATED the value for FMSDRWHST.DATE_UPDATED
     */
    public void setDATE_UPDATED(Date DATE_UPDATED) {
        this.DATE_UPDATED = DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSDRWHST.CREATED_BY
     *
     * @return the value of FMSDRWHST.CREATED_BY
     */
    public String getCREATED_BY() {
        return CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSDRWHST.CREATED_BY
     *
     * @param CREATED_BY the value for FMSDRWHST.CREATED_BY
     */
    public void setCREATED_BY(String CREATED_BY) {
        this.CREATED_BY = CREATED_BY == null ? null : CREATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSDRWHST.UPDATED_BY
     *
     * @return the value of FMSDRWHST.UPDATED_BY
     */
    public String getUPDATED_BY() {
        return UPDATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSDRWHST.UPDATED_BY
     *
     * @param UPDATED_BY the value for FMSDRWHST.UPDATED_BY
     */
    public void setUPDATED_BY(String UPDATED_BY) {
        this.UPDATED_BY = UPDATED_BY == null ? null : UPDATED_BY.trim();
    }
}