package com.path.dbmaps.vo;

import java.util.Date;

public class FMSDOCUMENTSVO extends FMSDOCUMENTSVOKey
{
    /**
     * This field corresponds to the database column FMSDOCUMENTS.BRIEF_NAME_ENG
     */
    private String BRIEF_NAME_ENG;

    /**
     * This field corresponds to the database column FMSDOCUMENTS.LONG_NAME_ENG
     */
    private String LONG_NAME_ENG;

    /**
     * This field corresponds to the database column
     * FMSDOCUMENTS.BRIEF_NAME_ARAB
     */
    private String BRIEF_NAME_ARAB;

    /**
     * This field corresponds to the database column FMSDOCUMENTS.LONG_NAME_ARAB
     */
    private String LONG_NAME_ARAB;

    /**
     * This field corresponds to the database column FMSDOCUMENTS.MANDATORY
     */
    private String MANDATORY;

    private Date DATE_UPDATED;

    /**
     * This field corresponds to the database column FMSAPPL.UPDATED_BY
     */
    private String UPDATED_BY;

    public Date getDATE_UPDATED()
    {
	return DATE_UPDATED;
    }

    public void setDATE_UPDATED(Date dATE_UPDATED)
    {
	DATE_UPDATED = dATE_UPDATED;
    }

    public String getUPDATED_BY()
    {
	return UPDATED_BY;
    }

    public void setUPDATED_BY(String uPDATED_BY)
    {
	UPDATED_BY = uPDATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column FMSDOCUMENTS.BRIEF_NAME_ENG
     *
     * @return the value of FMSDOCUMENTS.BRIEF_NAME_ENG
     */
    public String getBRIEF_NAME_ENG()
    {
	return BRIEF_NAME_ENG;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column FMSDOCUMENTS.BRIEF_NAME_ENG
     *
     * @param BRIEF_NAME_ENG the value for FMSDOCUMENTS.BRIEF_NAME_ENG
     */
    public void setBRIEF_NAME_ENG(String BRIEF_NAME_ENG)
    {
	this.BRIEF_NAME_ENG = BRIEF_NAME_ENG == null ? null : BRIEF_NAME_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column FMSDOCUMENTS.LONG_NAME_ENG
     *
     * @return the value of FMSDOCUMENTS.LONG_NAME_ENG
     */
    public String getLONG_NAME_ENG()
    {
	return LONG_NAME_ENG;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column FMSDOCUMENTS.LONG_NAME_ENG
     *
     * @param LONG_NAME_ENG the value for FMSDOCUMENTS.LONG_NAME_ENG
     */
    public void setLONG_NAME_ENG(String LONG_NAME_ENG)
    {
	this.LONG_NAME_ENG = LONG_NAME_ENG == null ? null : LONG_NAME_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column FMSDOCUMENTS.BRIEF_NAME_ARAB
     *
     * @return the value of FMSDOCUMENTS.BRIEF_NAME_ARAB
     */
    public String getBRIEF_NAME_ARAB()
    {
	return BRIEF_NAME_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column FMSDOCUMENTS.BRIEF_NAME_ARAB
     *
     * @param BRIEF_NAME_ARAB the value for FMSDOCUMENTS.BRIEF_NAME_ARAB
     */
    public void setBRIEF_NAME_ARAB(String BRIEF_NAME_ARAB)
    {
	this.BRIEF_NAME_ARAB = BRIEF_NAME_ARAB == null ? null : BRIEF_NAME_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column FMSDOCUMENTS.LONG_NAME_ARAB
     *
     * @return the value of FMSDOCUMENTS.LONG_NAME_ARAB
     */
    public String getLONG_NAME_ARAB()
    {
	return LONG_NAME_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column FMSDOCUMENTS.LONG_NAME_ARAB
     *
     * @param LONG_NAME_ARAB the value for FMSDOCUMENTS.LONG_NAME_ARAB
     */
    public void setLONG_NAME_ARAB(String LONG_NAME_ARAB)
    {
	this.LONG_NAME_ARAB = LONG_NAME_ARAB == null ? null : LONG_NAME_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column FMSDOCUMENTS.MANDATORY
     *
     * @return the value of FMSDOCUMENTS.MANDATORY
     */
    public String getMANDATORY()
    {
	return MANDATORY;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column FMSDOCUMENTS.MANDATORY
     *
     * @param MANDATORY the value for FMSDOCUMENTS.MANDATORY
     */
    public void setMANDATORY(String MANDATORY)
    {
	this.MANDATORY = MANDATORY == null ? null : MANDATORY.trim();
    }
}