package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class FMSFACILITY_YIELD_PERIOD_DETVOKey extends BaseVO {
    /**
     * This field corresponds to the database column FMSFACILITY_YIELD_PERIOD_DET.BRANCH
     */
    private BigDecimal BRANCH;

    /**
     * This field corresponds to the database column FMSFACILITY_YIELD_PERIOD_DET.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column FMSFACILITY_YIELD_PERIOD_DET.FACILITY_CODE
     */
    private BigDecimal FACILITY_CODE;

    /**
     * This field corresponds to the database column FMSFACILITY_YIELD_PERIOD_DET.LINE_NBR
     */
    private BigDecimal LINE_NBR;

    /**
     * This field corresponds to the database column FMSFACILITY_YIELD_PERIOD_DET.SUBLIMIT_NBR
     */
    private BigDecimal SUBLIMIT_NBR;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSFACILITY_YIELD_PERIOD_DET.BRANCH
     *
     * @return the value of FMSFACILITY_YIELD_PERIOD_DET.BRANCH
     */
    public BigDecimal getBRANCH() {
        return BRANCH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSFACILITY_YIELD_PERIOD_DET.BRANCH
     *
     * @param BRANCH the value for FMSFACILITY_YIELD_PERIOD_DET.BRANCH
     */
    public void setBRANCH(BigDecimal BRANCH) {
        this.BRANCH = BRANCH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSFACILITY_YIELD_PERIOD_DET.COMP_CODE
     *
     * @return the value of FMSFACILITY_YIELD_PERIOD_DET.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSFACILITY_YIELD_PERIOD_DET.COMP_CODE
     *
     * @param COMP_CODE the value for FMSFACILITY_YIELD_PERIOD_DET.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSFACILITY_YIELD_PERIOD_DET.FACILITY_CODE
     *
     * @return the value of FMSFACILITY_YIELD_PERIOD_DET.FACILITY_CODE
     */
    public BigDecimal getFACILITY_CODE() {
        return FACILITY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSFACILITY_YIELD_PERIOD_DET.FACILITY_CODE
     *
     * @param FACILITY_CODE the value for FMSFACILITY_YIELD_PERIOD_DET.FACILITY_CODE
     */
    public void setFACILITY_CODE(BigDecimal FACILITY_CODE) {
        this.FACILITY_CODE = FACILITY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSFACILITY_YIELD_PERIOD_DET.LINE_NBR
     *
     * @return the value of FMSFACILITY_YIELD_PERIOD_DET.LINE_NBR
     */
    public BigDecimal getLINE_NBR() {
        return LINE_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSFACILITY_YIELD_PERIOD_DET.LINE_NBR
     *
     * @param LINE_NBR the value for FMSFACILITY_YIELD_PERIOD_DET.LINE_NBR
     */
    public void setLINE_NBR(BigDecimal LINE_NBR) {
        this.LINE_NBR = LINE_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSFACILITY_YIELD_PERIOD_DET.SUBLIMIT_NBR
     *
     * @return the value of FMSFACILITY_YIELD_PERIOD_DET.SUBLIMIT_NBR
     */
    public BigDecimal getSUBLIMIT_NBR() {
        return SUBLIMIT_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSFACILITY_YIELD_PERIOD_DET.SUBLIMIT_NBR
     *
     * @param SUBLIMIT_NBR the value for FMSFACILITY_YIELD_PERIOD_DET.SUBLIMIT_NBR
     */
    public void setSUBLIMIT_NBR(BigDecimal SUBLIMIT_NBR) {
        this.SUBLIMIT_NBR = SUBLIMIT_NBR;
    }
}