package com.path.dbmaps.vo;

public class FMSFACILITYVOWithBLOBs extends FMSFACILITYVO {
    /**
     * This field corresponds to the database column FMSFACILITY.CONDITIONS
     */
    private String CONDITIONS;

    /**
     * This field corresponds to the database column FMSFACILITY.COVENANTS
     */
    private String COVENANTS;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSFACILITY.CONDITIONS
     *
     * @return the value of FMSFACILITY.CONDITIONS
     */
    public String getCONDITIONS() {
        return CONDITIONS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSFACILITY.CONDITIONS
     *
     * @param CONDITIONS the value for FMSFACILITY.CONDITIONS
     */
    public void setCONDITIONS(String CONDITIONS) {
        this.CONDITIONS = CONDITIONS == null ? null : CONDITIONS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSFACILITY.COVENANTS
     *
     * @return the value of FMSFACILITY.COVENANTS
     */
    public String getCOVENANTS() {
        return COVENANTS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSFACILITY.COVENANTS
     *
     * @param COVENANTS the value for FMSFACILITY.COVENANTS
     */
    public void setCOVENANTS(String COVENANTS) {
        this.COVENANTS = COVENANTS == null ? null : COVENANTS.trim();
    }
}