package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class FMSFACILITYCIFVOKey extends BaseVO {
    /**
     * This field corresponds to the database column FMSFACILITYCIF.BRANCH
     */
    private BigDecimal BRANCH;

    /**
     * This field corresponds to the database column FMSFACILITYCIF.CODE
     */
    private BigDecimal CODE;

    /**
     * This field corresponds to the database column FMSFACILITYCIF.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column FMSFACILITYCIF.LINE_NBR
     */
    private BigDecimal LINE_NBR;

    /**
     * This field corresponds to the database column FMSFACILITYCIF.LINE_NBR_DET
     */
    private BigDecimal LINE_NBR_DET;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSFACILITYCIF.BRANCH
     *
     * @return the value of FMSFACILITYCIF.BRANCH
     */
    public BigDecimal getBRANCH() {
        return BRANCH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSFACILITYCIF.BRANCH
     *
     * @param BRANCH the value for FMSFACILITYCIF.BRANCH
     */
    public void setBRANCH(BigDecimal BRANCH) {
        this.BRANCH = BRANCH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSFACILITYCIF.CODE
     *
     * @return the value of FMSFACILITYCIF.CODE
     */
    public BigDecimal getCODE() {
        return CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSFACILITYCIF.CODE
     *
     * @param CODE the value for FMSFACILITYCIF.CODE
     */
    public void setCODE(BigDecimal CODE) {
        this.CODE = CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSFACILITYCIF.COMP_CODE
     *
     * @return the value of FMSFACILITYCIF.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSFACILITYCIF.COMP_CODE
     *
     * @param COMP_CODE the value for FMSFACILITYCIF.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSFACILITYCIF.LINE_NBR
     *
     * @return the value of FMSFACILITYCIF.LINE_NBR
     */
    public BigDecimal getLINE_NBR() {
        return LINE_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSFACILITYCIF.LINE_NBR
     *
     * @param LINE_NBR the value for FMSFACILITYCIF.LINE_NBR
     */
    public void setLINE_NBR(BigDecimal LINE_NBR) {
        this.LINE_NBR = LINE_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSFACILITYCIF.LINE_NBR_DET
     *
     * @return the value of FMSFACILITYCIF.LINE_NBR_DET
     */
    public BigDecimal getLINE_NBR_DET() {
        return LINE_NBR_DET;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSFACILITYCIF.LINE_NBR_DET
     *
     * @param LINE_NBR_DET the value for FMSFACILITYCIF.LINE_NBR_DET
     */
    public void setLINE_NBR_DET(BigDecimal LINE_NBR_DET) {
        this.LINE_NBR_DET = LINE_NBR_DET;
    }
}