package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class FMSFACSOLESTVO extends FMSFACSOLESTVOKey {
    /**
     * This field corresponds to the database column FMSFACSOLEST.SOLICITOR
     */
    private BigDecimal SOLICITOR;

    /**
     * This field corresponds to the database column FMSFACSOLEST.ESTIMATOR
     */
    private BigDecimal ESTIMATOR;

    /**
     * This field corresponds to the database column FMSFACSOLEST.PAYMENT_METHOD
     */
    private String PAYMENT_METHOD;

    /**
     * This field corresponds to the database column FMSFACSOLEST.CHEQUE_NO
     */
    private String CHEQUE_NO;

    /**
     * This field corresponds to the database column FMSFACSOLEST.CHEQUE_BANK
     */
    private String CHEQUE_BANK;

    /**
     * This field corresponds to the database column FMSFACSOLEST.ADD_FIELD
     */
    private String ADD_FIELD;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSFACSOLEST.SOLICITOR
     *
     * @return the value of FMSFACSOLEST.SOLICITOR
     */
    public BigDecimal getSOLICITOR() {
        return SOLICITOR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSFACSOLEST.SOLICITOR
     *
     * @param SOLICITOR the value for FMSFACSOLEST.SOLICITOR
     */
    public void setSOLICITOR(BigDecimal SOLICITOR) {
        this.SOLICITOR = SOLICITOR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSFACSOLEST.ESTIMATOR
     *
     * @return the value of FMSFACSOLEST.ESTIMATOR
     */
    public BigDecimal getESTIMATOR() {
        return ESTIMATOR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSFACSOLEST.ESTIMATOR
     *
     * @param ESTIMATOR the value for FMSFACSOLEST.ESTIMATOR
     */
    public void setESTIMATOR(BigDecimal ESTIMATOR) {
        this.ESTIMATOR = ESTIMATOR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSFACSOLEST.PAYMENT_METHOD
     *
     * @return the value of FMSFACSOLEST.PAYMENT_METHOD
     */
    public String getPAYMENT_METHOD() {
        return PAYMENT_METHOD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSFACSOLEST.PAYMENT_METHOD
     *
     * @param PAYMENT_METHOD the value for FMSFACSOLEST.PAYMENT_METHOD
     */
    public void setPAYMENT_METHOD(String PAYMENT_METHOD) {
        this.PAYMENT_METHOD = PAYMENT_METHOD == null ? null : PAYMENT_METHOD.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSFACSOLEST.CHEQUE_NO
     *
     * @return the value of FMSFACSOLEST.CHEQUE_NO
     */
    public String getCHEQUE_NO() {
        return CHEQUE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSFACSOLEST.CHEQUE_NO
     *
     * @param CHEQUE_NO the value for FMSFACSOLEST.CHEQUE_NO
     */
    public void setCHEQUE_NO(String CHEQUE_NO) {
        this.CHEQUE_NO = CHEQUE_NO == null ? null : CHEQUE_NO.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSFACSOLEST.CHEQUE_BANK
     *
     * @return the value of FMSFACSOLEST.CHEQUE_BANK
     */
    public String getCHEQUE_BANK() {
        return CHEQUE_BANK;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSFACSOLEST.CHEQUE_BANK
     *
     * @param CHEQUE_BANK the value for FMSFACSOLEST.CHEQUE_BANK
     */
    public void setCHEQUE_BANK(String CHEQUE_BANK) {
        this.CHEQUE_BANK = CHEQUE_BANK == null ? null : CHEQUE_BANK.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSFACSOLEST.ADD_FIELD
     *
     * @return the value of FMSFACSOLEST.ADD_FIELD
     */
    public String getADD_FIELD() {
        return ADD_FIELD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSFACSOLEST.ADD_FIELD
     *
     * @param ADD_FIELD the value for FMSFACSOLEST.ADD_FIELD
     */
    public void setADD_FIELD(String ADD_FIELD) {
        this.ADD_FIELD = ADD_FIELD == null ? null : ADD_FIELD.trim();
    }
}