package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class FMSFACDOCUMENTSVOKey extends BaseVO {
    /**
     * This field corresponds to the database column FMSFACDOCUMENTS.BRANCH
     */
    private BigDecimal BRANCH;

    /**
     * This field corresponds to the database column FMSFACDOCUMENTS.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column FMSFACDOCUMENTS.DOC_CODE
     */
    private BigDecimal DOC_CODE;

    /**
     * This field corresponds to the database column FMSFACDOCUMENTS.FAC_REF
     */
    private BigDecimal FAC_REF;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSFACDOCUMENTS.BRANCH
     *
     * @return the value of FMSFACDOCUMENTS.BRANCH
     */
    public BigDecimal getBRANCH() {
        return BRANCH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSFACDOCUMENTS.BRANCH
     *
     * @param BRANCH the value for FMSFACDOCUMENTS.BRANCH
     */
    public void setBRANCH(BigDecimal BRANCH) {
        this.BRANCH = BRANCH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSFACDOCUMENTS.COMP_CODE
     *
     * @return the value of FMSFACDOCUMENTS.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSFACDOCUMENTS.COMP_CODE
     *
     * @param COMP_CODE the value for FMSFACDOCUMENTS.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSFACDOCUMENTS.DOC_CODE
     *
     * @return the value of FMSFACDOCUMENTS.DOC_CODE
     */
    public BigDecimal getDOC_CODE() {
        return DOC_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSFACDOCUMENTS.DOC_CODE
     *
     * @param DOC_CODE the value for FMSFACDOCUMENTS.DOC_CODE
     */
    public void setDOC_CODE(BigDecimal DOC_CODE) {
        this.DOC_CODE = DOC_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSFACDOCUMENTS.FAC_REF
     *
     * @return the value of FMSFACDOCUMENTS.FAC_REF
     */
    public BigDecimal getFAC_REF() {
        return FAC_REF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSFACDOCUMENTS.FAC_REF
     *
     * @param FAC_REF the value for FMSFACDOCUMENTS.FAC_REF
     */
    public void setFAC_REF(BigDecimal FAC_REF) {
        this.FAC_REF = FAC_REF;
    }
}