package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class FMSFACILITYTYPE_CLASSVOKey extends BaseVO {
    /**
     * This field corresponds to the database column FMSFACILITYTYPE_CLASS.CLASS_CODE
     */
    private BigDecimal CLASS_CODE;

    /**
     * This field corresponds to the database column FMSFACILITYTYPE_CLASS.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column FMSFACILITYTYPE_CLASS.FACILITYTYPE_CODE
     */
    private BigDecimal FACILITYTYPE_CODE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSFACILITYTYPE_CLASS.CLASS_CODE
     *
     * @return the value of FMSFACILITYTYPE_CLASS.CLASS_CODE
     */
    public BigDecimal getCLASS_CODE() {
        return CLASS_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSFACILITYTYPE_CLASS.CLASS_CODE
     *
     * @param CLASS_CODE the value for FMSFACILITYTYPE_CLASS.CLASS_CODE
     */
    public void setCLASS_CODE(BigDecimal CLASS_CODE) {
        this.CLASS_CODE = CLASS_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSFACILITYTYPE_CLASS.COMP_CODE
     *
     * @return the value of FMSFACILITYTYPE_CLASS.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSFACILITYTYPE_CLASS.COMP_CODE
     *
     * @param COMP_CODE the value for FMSFACILITYTYPE_CLASS.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSFACILITYTYPE_CLASS.FACILITYTYPE_CODE
     *
     * @return the value of FMSFACILITYTYPE_CLASS.FACILITYTYPE_CODE
     */
    public BigDecimal getFACILITYTYPE_CODE() {
        return FACILITYTYPE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSFACILITYTYPE_CLASS.FACILITYTYPE_CODE
     *
     * @param FACILITYTYPE_CODE the value for FMSFACILITYTYPE_CLASS.FACILITYTYPE_CODE
     */
    public void setFACILITYTYPE_CODE(BigDecimal FACILITYTYPE_CODE) {
        this.FACILITYTYPE_CODE = FACILITYTYPE_CODE;
    }
}