package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class FMSPARTYBRANCHESVOKey extends BaseVO {
    /**
     * This field corresponds to the database column FMSPARTYBRANCHES.CIF
     */
    private BigDecimal CIF;

    /**
     * This field corresponds to the database column FMSPARTYBRANCHES.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column FMSPARTYBRANCHES.LINE_NBR
     */
    private BigDecimal LINE_NBR;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSPARTYBRANCHES.CIF
     *
     * @return the value of FMSPARTYBRANCHES.CIF
     */
    public BigDecimal getCIF() {
        return CIF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSPARTYBRANCHES.CIF
     *
     * @param CIF the value for FMSPARTYBRANCHES.CIF
     */
    public void setCIF(BigDecimal CIF) {
        this.CIF = CIF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSPARTYBRANCHES.COMP_CODE
     *
     * @return the value of FMSPARTYBRANCHES.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSPARTYBRANCHES.COMP_CODE
     *
     * @param COMP_CODE the value for FMSPARTYBRANCHES.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSPARTYBRANCHES.LINE_NBR
     *
     * @return the value of FMSPARTYBRANCHES.LINE_NBR
     */
    public BigDecimal getLINE_NBR() {
        return LINE_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSPARTYBRANCHES.LINE_NBR
     *
     * @param LINE_NBR the value for FMSPARTYBRANCHES.LINE_NBR
     */
    public void setLINE_NBR(BigDecimal LINE_NBR) {
        this.LINE_NBR = LINE_NBR;
    }
}