package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class FMSPAYPLANVOKey extends BaseVO {
    /**
     * This field corresponds to the database column FMSPAYPLAN.BRANCH
     */
    private BigDecimal BRANCH;

    /**
     * This field corresponds to the database column FMSPAYPLAN.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column FMSPAYPLAN.PLAN_NBR
     */
    private BigDecimal PLAN_NBR;

    /**
     * This field corresponds to the database column FMSPAYPLAN.PLAN_SEQ
     */
    private BigDecimal PLAN_SEQ;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSPAYPLAN.BRANCH
     *
     * @return the value of FMSPAYPLAN.BRANCH
     */
    public BigDecimal getBRANCH() {
        return BRANCH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSPAYPLAN.BRANCH
     *
     * @param BRANCH the value for FMSPAYPLAN.BRANCH
     */
    public void setBRANCH(BigDecimal BRANCH) {
        this.BRANCH = BRANCH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSPAYPLAN.COMP_CODE
     *
     * @return the value of FMSPAYPLAN.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSPAYPLAN.COMP_CODE
     *
     * @param COMP_CODE the value for FMSPAYPLAN.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSPAYPLAN.PLAN_NBR
     *
     * @return the value of FMSPAYPLAN.PLAN_NBR
     */
    public BigDecimal getPLAN_NBR() {
        return PLAN_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSPAYPLAN.PLAN_NBR
     *
     * @param PLAN_NBR the value for FMSPAYPLAN.PLAN_NBR
     */
    public void setPLAN_NBR(BigDecimal PLAN_NBR) {
        this.PLAN_NBR = PLAN_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FMSPAYPLAN.PLAN_SEQ
     *
     * @return the value of FMSPAYPLAN.PLAN_SEQ
     */
    public BigDecimal getPLAN_SEQ() {
        return PLAN_SEQ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FMSPAYPLAN.PLAN_SEQ
     *
     * @param PLAN_SEQ the value for FMSPAYPLAN.PLAN_SEQ
     */
    public void setPLAN_SEQ(BigDecimal PLAN_SEQ) {
        this.PLAN_SEQ = PLAN_SEQ;
    }
}