package com.path.dbmaps.vo;

import java.util.Date;

public class FX_DEALER_LIMITSVO extends FX_DEALER_LIMITSVOKey {
    /**
     * This field corresponds to the database column FX_DEALER_LIMITS.STATUS
     */
    private String STATUS;
	
	/**
     * This field corresponds to the database column FX_DEALER_LIMITS.STATUS
     */
    private String INTRADAY_LIMIT_ACTION;
	
	/**
     * This field corresponds to the database column FX_DEALER_LIMITS.STATUS
     */
    private String TRANSACTION_LIMIT_ACTION;
	
	/**
     * This field corresponds to the database column FX_DEALER_LIMITS.STATUS
     */
    private String APPLY_INTERPOL_RATE_FX_YN;

    /**
     * This field corresponds to the database column FX_DEALER_LIMITS.CREATED_BY
     */
    private String CREATED_BY;

    /**
     * This field corresponds to the database column FX_DEALER_LIMITS.DATE_CREATED
     */
    private Date DATE_CREATED;

    /**
     * This field corresponds to the database column FX_DEALER_LIMITS.MODIFIED_BY
     */
    private String MODIFIED_BY;

    /**
     * This field corresponds to the database column FX_DEALER_LIMITS.DATE_MODIFIED
     */
    private Date DATE_MODIFIED;

    /**
     * This field corresponds to the database column FX_DEALER_LIMITS.DELETED_BY
     */
    private String DELETED_BY;

    /**
     * This field corresponds to the database column FX_DEALER_LIMITS.DATE_DELETED
     */
    private Date DATE_DELETED;

    /**
     * This field corresponds to the database column FX_DEALER_LIMITS.APPROVED_BY
     */
    private String APPROVED_BY;

    /**
     * This field corresponds to the database column FX_DEALER_LIMITS.DATE_APPROVED
     */
    private Date DATE_APPROVED;

    /**
     * This field corresponds to the database column FX_DEALER_LIMITS.SUSPENDED_BY
     */
    private String SUSPENDED_BY;

    /**
     * This field corresponds to the database column FX_DEALER_LIMITS.DATE_SUSPENDED
     */
    private Date DATE_SUSPENDED;

    /**
     * This field corresponds to the database column FX_DEALER_LIMITS.REACTIVATED_BY
     */
    private String REACTIVATED_BY;

    /**
     * This field corresponds to the database column FX_DEALER_LIMITS.DATE_REACTIVATED
     */
    private Date DATE_REACTIVATED;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FX_DEALER_LIMITS.STATUS
     *
     * @return the value of FX_DEALER_LIMITS.STATUS
     */
    public String getSTATUS() {
        return STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FX_DEALER_LIMITS.STATUS
     *
     * @param STATUS the value for FX_DEALER_LIMITS.STATUS
     */
    public void setSTATUS(String STATUS) {
        this.STATUS = STATUS == null ? null : STATUS.trim();
    }
	
	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FX_DEALER_LIMITS.INTRADAY_LIMIT_ACTION
     *
     * @return the value of FX_DEALER_LIMITS.INTRADAY_LIMIT_ACTION
     */
    public String getINTRADAY_LIMIT_ACTION() {
        return INTRADAY_LIMIT_ACTION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FX_DEALER_LIMITS.INTRADAY_LIMIT_ACTION
     *
     * @param INTRADAY_LIMIT_ACTION the value for FX_DEALER_LIMITS.INTRADAY_LIMIT_ACTION
     */
    public void setINTRADAY_LIMIT_ACTION(String INTRADAY_LIMIT_ACTION) {
        this.INTRADAY_LIMIT_ACTION = INTRADAY_LIMIT_ACTION == null ? null : INTRADAY_LIMIT_ACTION.trim();
    }
	
	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FX_DEALER_LIMITS.TRANSACTION_LIMIT_ACTION
     *
     * @return the value of FX_DEALER_LIMITS.TRANSACTION_LIMIT_ACTION
     */
    public String getTRANSACTION_LIMIT_ACTION() {
        return TRANSACTION_LIMIT_ACTION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FX_DEALER_LIMITS.TRANSACTION_LIMIT_ACTION
     *
     * @param TRANSACTION_LIMIT_ACTION the value for FX_DEALER_LIMITS.TRANSACTION_LIMIT_ACTION
     */
    public void setTRANSACTION_LIMIT_ACTION(String TRANSACTION_LIMIT_ACTION) {
        this.TRANSACTION_LIMIT_ACTION = TRANSACTION_LIMIT_ACTION == null ? null : TRANSACTION_LIMIT_ACTION.trim();
    }
	
	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FX_DEALER_LIMITS.APPLY_INTERPOL_RATE_FX_YN
     *
     * @return the value of FX_DEALER_LIMITS.APPLY_INTERPOL_RATE_FX_YN
     */
    public String getAPPLY_INTERPOL_RATE_FX_YN() {
        return APPLY_INTERPOL_RATE_FX_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FX_DEALER_LIMITS.APPLY_INTERPOL_RATE_FX_YN
     *
     * @param APPLY_INTERPOL_RATE_FX_YN the value for FX_DEALER_LIMITS.APPLY_INTERPOL_RATE_FX_YN
     */
    public void setAPPLY_INTERPOL_RATE_FX_YN(String APPLY_INTERPOL_RATE_FX_YN) {
        this.APPLY_INTERPOL_RATE_FX_YN = APPLY_INTERPOL_RATE_FX_YN == null ? null : APPLY_INTERPOL_RATE_FX_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FX_DEALER_LIMITS.CREATED_BY
     *
     * @return the value of FX_DEALER_LIMITS.CREATED_BY
     */
    public String getCREATED_BY() {
        return CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FX_DEALER_LIMITS.CREATED_BY
     *
     * @param CREATED_BY the value for FX_DEALER_LIMITS.CREATED_BY
     */
    public void setCREATED_BY(String CREATED_BY) {
        this.CREATED_BY = CREATED_BY == null ? null : CREATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FX_DEALER_LIMITS.DATE_CREATED
     *
     * @return the value of FX_DEALER_LIMITS.DATE_CREATED
     */
    public Date getDATE_CREATED() {
        return DATE_CREATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FX_DEALER_LIMITS.DATE_CREATED
     *
     * @param DATE_CREATED the value for FX_DEALER_LIMITS.DATE_CREATED
     */
    public void setDATE_CREATED(Date DATE_CREATED) {
        this.DATE_CREATED = DATE_CREATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FX_DEALER_LIMITS.MODIFIED_BY
     *
     * @return the value of FX_DEALER_LIMITS.MODIFIED_BY
     */
    public String getMODIFIED_BY() {
        return MODIFIED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FX_DEALER_LIMITS.MODIFIED_BY
     *
     * @param MODIFIED_BY the value for FX_DEALER_LIMITS.MODIFIED_BY
     */
    public void setMODIFIED_BY(String MODIFIED_BY) {
        this.MODIFIED_BY = MODIFIED_BY == null ? null : MODIFIED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FX_DEALER_LIMITS.DATE_MODIFIED
     *
     * @return the value of FX_DEALER_LIMITS.DATE_MODIFIED
     */
    public Date getDATE_MODIFIED() {
        return DATE_MODIFIED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FX_DEALER_LIMITS.DATE_MODIFIED
     *
     * @param DATE_MODIFIED the value for FX_DEALER_LIMITS.DATE_MODIFIED
     */
    public void setDATE_MODIFIED(Date DATE_MODIFIED) {
        this.DATE_MODIFIED = DATE_MODIFIED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FX_DEALER_LIMITS.DELETED_BY
     *
     * @return the value of FX_DEALER_LIMITS.DELETED_BY
     */
    public String getDELETED_BY() {
        return DELETED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FX_DEALER_LIMITS.DELETED_BY
     *
     * @param DELETED_BY the value for FX_DEALER_LIMITS.DELETED_BY
     */
    public void setDELETED_BY(String DELETED_BY) {
        this.DELETED_BY = DELETED_BY == null ? null : DELETED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FX_DEALER_LIMITS.DATE_DELETED
     *
     * @return the value of FX_DEALER_LIMITS.DATE_DELETED
     */
    public Date getDATE_DELETED() {
        return DATE_DELETED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FX_DEALER_LIMITS.DATE_DELETED
     *
     * @param DATE_DELETED the value for FX_DEALER_LIMITS.DATE_DELETED
     */
    public void setDATE_DELETED(Date DATE_DELETED) {
        this.DATE_DELETED = DATE_DELETED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FX_DEALER_LIMITS.APPROVED_BY
     *
     * @return the value of FX_DEALER_LIMITS.APPROVED_BY
     */
    public String getAPPROVED_BY() {
        return APPROVED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FX_DEALER_LIMITS.APPROVED_BY
     *
     * @param APPROVED_BY the value for FX_DEALER_LIMITS.APPROVED_BY
     */
    public void setAPPROVED_BY(String APPROVED_BY) {
        this.APPROVED_BY = APPROVED_BY == null ? null : APPROVED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FX_DEALER_LIMITS.DATE_APPROVED
     *
     * @return the value of FX_DEALER_LIMITS.DATE_APPROVED
     */
    public Date getDATE_APPROVED() {
        return DATE_APPROVED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FX_DEALER_LIMITS.DATE_APPROVED
     *
     * @param DATE_APPROVED the value for FX_DEALER_LIMITS.DATE_APPROVED
     */
    public void setDATE_APPROVED(Date DATE_APPROVED) {
        this.DATE_APPROVED = DATE_APPROVED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FX_DEALER_LIMITS.SUSPENDED_BY
     *
     * @return the value of FX_DEALER_LIMITS.SUSPENDED_BY
     */
    public String getSUSPENDED_BY() {
        return SUSPENDED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FX_DEALER_LIMITS.SUSPENDED_BY
     *
     * @param SUSPENDED_BY the value for FX_DEALER_LIMITS.SUSPENDED_BY
     */
    public void setSUSPENDED_BY(String SUSPENDED_BY) {
        this.SUSPENDED_BY = SUSPENDED_BY == null ? null : SUSPENDED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FX_DEALER_LIMITS.DATE_SUSPENDED
     *
     * @return the value of FX_DEALER_LIMITS.DATE_SUSPENDED
     */
    public Date getDATE_SUSPENDED() {
        return DATE_SUSPENDED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FX_DEALER_LIMITS.DATE_SUSPENDED
     *
     * @param DATE_SUSPENDED the value for FX_DEALER_LIMITS.DATE_SUSPENDED
     */
    public void setDATE_SUSPENDED(Date DATE_SUSPENDED) {
        this.DATE_SUSPENDED = DATE_SUSPENDED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FX_DEALER_LIMITS.REACTIVATED_BY
     *
     * @return the value of FX_DEALER_LIMITS.REACTIVATED_BY
     */
    public String getREACTIVATED_BY() {
        return REACTIVATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FX_DEALER_LIMITS.REACTIVATED_BY
     *
     * @param REACTIVATED_BY the value for FX_DEALER_LIMITS.REACTIVATED_BY
     */
    public void setREACTIVATED_BY(String REACTIVATED_BY) {
        this.REACTIVATED_BY = REACTIVATED_BY == null ? null : REACTIVATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FX_DEALER_LIMITS.DATE_REACTIVATED
     *
     * @return the value of FX_DEALER_LIMITS.DATE_REACTIVATED
     */
    public Date getDATE_REACTIVATED() {
        return DATE_REACTIVATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FX_DEALER_LIMITS.DATE_REACTIVATED
     *
     * @param DATE_REACTIVATED the value for FX_DEALER_LIMITS.DATE_REACTIVATED
     */
    public void setDATE_REACTIVATED(Date DATE_REACTIVATED) {
        this.DATE_REACTIVATED = DATE_REACTIVATED;
    }
}