package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class GL_TYPE_TEMPLATEVOKey extends BaseVO {
    /**
     * This field corresponds to the database column GL_TYPE_TEMPLATE.APP_NAME
     */
    private String APP_NAME;

    /**
     * This field corresponds to the database column GL_TYPE_TEMPLATE.BRANCH_CODE
     */
    private BigDecimal BRANCH_CODE;

    /**
     * This field corresponds to the database column GL_TYPE_TEMPLATE.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column GL_TYPE_TEMPLATE.GL_TYPE
     */
    private String GL_TYPE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GL_TYPE_TEMPLATE.APP_NAME
     *
     * @return the value of GL_TYPE_TEMPLATE.APP_NAME
     */
    public String getAPP_NAME() {
        return APP_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GL_TYPE_TEMPLATE.APP_NAME
     *
     * @param APP_NAME the value for GL_TYPE_TEMPLATE.APP_NAME
     */
    public void setAPP_NAME(String APP_NAME) {
        this.APP_NAME = APP_NAME == null ? null : APP_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GL_TYPE_TEMPLATE.BRANCH_CODE
     *
     * @return the value of GL_TYPE_TEMPLATE.BRANCH_CODE
     */
    public BigDecimal getBRANCH_CODE() {
        return BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GL_TYPE_TEMPLATE.BRANCH_CODE
     *
     * @param BRANCH_CODE the value for GL_TYPE_TEMPLATE.BRANCH_CODE
     */
    public void setBRANCH_CODE(BigDecimal BRANCH_CODE) {
        this.BRANCH_CODE = BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GL_TYPE_TEMPLATE.COMP_CODE
     *
     * @return the value of GL_TYPE_TEMPLATE.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GL_TYPE_TEMPLATE.COMP_CODE
     *
     * @param COMP_CODE the value for GL_TYPE_TEMPLATE.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GL_TYPE_TEMPLATE.GL_TYPE
     *
     * @return the value of GL_TYPE_TEMPLATE.GL_TYPE
     */
    public String getGL_TYPE() {
        return GL_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GL_TYPE_TEMPLATE.GL_TYPE
     *
     * @param GL_TYPE the value for GL_TYPE_TEMPLATE.GL_TYPE
     */
    public void setGL_TYPE(String GL_TYPE) {
        this.GL_TYPE = GL_TYPE == null ? null : GL_TYPE.trim();
    }
}