package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class GLSFISCALYEARVOKey extends BaseVO {
    /**
     * This field corresponds to the database column GLSFISCALYEAR.BRANCH_CODE
     */
    private BigDecimal BRANCH_CODE;

    /**
     * This field corresponds to the database column GLSFISCALYEAR.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column GLSFISCALYEAR.FISCAL_YEAR
     */
    private BigDecimal FISCAL_YEAR;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GLSFISCALYEAR.BRANCH_CODE
     *
     * @return the value of GLSFISCALYEAR.BRANCH_CODE
     */
    public BigDecimal getBRANCH_CODE() {
        return BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GLSFISCALYEAR.BRANCH_CODE
     *
     * @param BRANCH_CODE the value for GLSFISCALYEAR.BRANCH_CODE
     */
    public void setBRANCH_CODE(BigDecimal BRANCH_CODE) {
        this.BRANCH_CODE = BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GLSFISCALYEAR.COMP_CODE
     *
     * @return the value of GLSFISCALYEAR.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GLSFISCALYEAR.COMP_CODE
     *
     * @param COMP_CODE the value for GLSFISCALYEAR.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GLSFISCALYEAR.FISCAL_YEAR
     *
     * @return the value of GLSFISCALYEAR.FISCAL_YEAR
     */
    public BigDecimal getFISCAL_YEAR() {
        return FISCAL_YEAR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GLSFISCALYEAR.FISCAL_YEAR
     *
     * @param FISCAL_YEAR the value for GLSFISCALYEAR.FISCAL_YEAR
     */
    public void setFISCAL_YEAR(BigDecimal FISCAL_YEAR) {
        this.FISCAL_YEAR = FISCAL_YEAR;
    }
}