package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class IPO_SUBSCRIBERVO extends IPO_SUBSCRIBERVOKey {
    /**
     * This field corresponds to the database column IPO_SUBSCRIBER.BRIEF_NAME_ENG
     */
    private String BRIEF_NAME_ENG;

    /**
     * This field corresponds to the database column IPO_SUBSCRIBER.LONG_NAME_ENG
     */
    private String LONG_NAME_ENG;

    /**
     * This field corresponds to the database column IPO_SUBSCRIBER.TYPE_CODE
     */
    private BigDecimal TYPE_CODE;

    /**
     * This field corresponds to the database column IPO_SUBSCRIBER.PRIORITY_CODE
     */
    private BigDecimal PRIORITY_CODE;

    /**
     * This field corresponds to the database column IPO_SUBSCRIBER.CIVIL_CODE
     */
    private BigDecimal CIVIL_CODE;

    /**
     * This field corresponds to the database column IPO_SUBSCRIBER.PORTFOLIO_CIF
     */
    private BigDecimal PORTFOLIO_CIF;

    /**
     * This field corresponds to the database column IPO_SUBSCRIBER.PORTFOLIO_SEQ
     */
    private BigDecimal PORTFOLIO_SEQ;

    /**
     * This field corresponds to the database column IPO_SUBSCRIBER.GROUP_ID
     */
    private String GROUP_ID;

    /**
     * This field corresponds to the database column IPO_SUBSCRIBER.BRIEF_NAME_ARAB
     */
    private String BRIEF_NAME_ARAB;

    /**
     * This field corresponds to the database column IPO_SUBSCRIBER.LONG_NAME_ARAB
     */
    private String LONG_NAME_ARAB;

    /**
     * This field corresponds to the database column IPO_SUBSCRIBER.ADDRESS_ENG1
     */
    private String ADDRESS_ENG1;

    /**
     * This field corresponds to the database column IPO_SUBSCRIBER.ADDRESS_ENG2
     */
    private String ADDRESS_ENG2;

    /**
     * This field corresponds to the database column IPO_SUBSCRIBER.ADDRESS_ENG3
     */
    private String ADDRESS_ENG3;

    /**
     * This field corresponds to the database column IPO_SUBSCRIBER.ADDRESS_ARAB1
     */
    private String ADDRESS_ARAB1;

    /**
     * This field corresponds to the database column IPO_SUBSCRIBER.ADDRESS_ARAB2
     */
    private String ADDRESS_ARAB2;

    /**
     * This field corresponds to the database column IPO_SUBSCRIBER.ADDRESS_ARAB3
     */
    private String ADDRESS_ARAB3;

    /**
     * This field corresponds to the database column IPO_SUBSCRIBER.STATUS
     */
    private String STATUS;

    /**
     * This field corresponds to the database column IPO_SUBSCRIBER.CREATED_BY
     */
    private String CREATED_BY;

    /**
     * This field corresponds to the database column IPO_SUBSCRIBER.DATE_CREATED
     */
    private Date DATE_CREATED;

    /**
     * This field corresponds to the database column IPO_SUBSCRIBER.MODIFIED_BY
     */
    private String MODIFIED_BY;

    /**
     * This field corresponds to the database column IPO_SUBSCRIBER.DATE_MODIFIED
     */
    private Date DATE_MODIFIED;

    /**
     * This field corresponds to the database column IPO_SUBSCRIBER.DELETED_BY
     */
    private String DELETED_BY;

    /**
     * This field corresponds to the database column IPO_SUBSCRIBER.DATE_DELETED
     */
    private Date DATE_DELETED;

    /**
     * This field corresponds to the database column IPO_SUBSCRIBER.SUSPENDED_BY
     */
    private String SUSPENDED_BY;

    /**
     * This field corresponds to the database column IPO_SUBSCRIBER.DATE_SUSPENDED
     */
    private Date DATE_SUSPENDED;

    /**
     * This field corresponds to the database column IPO_SUBSCRIBER.REACTIVATED_BY
     */
    private String REACTIVATED_BY;

    /**
     * This field corresponds to the database column IPO_SUBSCRIBER.DATE_REACTIVATED
     */
    private Date DATE_REACTIVATED;

    /**
     * This field corresponds to the database column IPO_SUBSCRIBER.ID_NUMBER
     */
    private String ID_NUMBER;

    /**
     * This field corresponds to the database column IPO_SUBSCRIBER.LOCK_UP_PERIOD
     */
    private BigDecimal LOCK_UP_PERIOD;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IPO_SUBSCRIBER.BRIEF_NAME_ENG
     *
     * @return the value of IPO_SUBSCRIBER.BRIEF_NAME_ENG
     */
    public String getBRIEF_NAME_ENG() {
        return BRIEF_NAME_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IPO_SUBSCRIBER.BRIEF_NAME_ENG
     *
     * @param BRIEF_NAME_ENG the value for IPO_SUBSCRIBER.BRIEF_NAME_ENG
     */
    public void setBRIEF_NAME_ENG(String BRIEF_NAME_ENG) {
        this.BRIEF_NAME_ENG = BRIEF_NAME_ENG == null ? null : BRIEF_NAME_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IPO_SUBSCRIBER.LONG_NAME_ENG
     *
     * @return the value of IPO_SUBSCRIBER.LONG_NAME_ENG
     */
    public String getLONG_NAME_ENG() {
        return LONG_NAME_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IPO_SUBSCRIBER.LONG_NAME_ENG
     *
     * @param LONG_NAME_ENG the value for IPO_SUBSCRIBER.LONG_NAME_ENG
     */
    public void setLONG_NAME_ENG(String LONG_NAME_ENG) {
        this.LONG_NAME_ENG = LONG_NAME_ENG == null ? null : LONG_NAME_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IPO_SUBSCRIBER.TYPE_CODE
     *
     * @return the value of IPO_SUBSCRIBER.TYPE_CODE
     */
    public BigDecimal getTYPE_CODE() {
        return TYPE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IPO_SUBSCRIBER.TYPE_CODE
     *
     * @param TYPE_CODE the value for IPO_SUBSCRIBER.TYPE_CODE
     */
    public void setTYPE_CODE(BigDecimal TYPE_CODE) {
        this.TYPE_CODE = TYPE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IPO_SUBSCRIBER.PRIORITY_CODE
     *
     * @return the value of IPO_SUBSCRIBER.PRIORITY_CODE
     */
    public BigDecimal getPRIORITY_CODE() {
        return PRIORITY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IPO_SUBSCRIBER.PRIORITY_CODE
     *
     * @param PRIORITY_CODE the value for IPO_SUBSCRIBER.PRIORITY_CODE
     */
    public void setPRIORITY_CODE(BigDecimal PRIORITY_CODE) {
        this.PRIORITY_CODE = PRIORITY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IPO_SUBSCRIBER.CIVIL_CODE
     *
     * @return the value of IPO_SUBSCRIBER.CIVIL_CODE
     */
    public BigDecimal getCIVIL_CODE() {
        return CIVIL_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IPO_SUBSCRIBER.CIVIL_CODE
     *
     * @param CIVIL_CODE the value for IPO_SUBSCRIBER.CIVIL_CODE
     */
    public void setCIVIL_CODE(BigDecimal CIVIL_CODE) {
        this.CIVIL_CODE = CIVIL_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IPO_SUBSCRIBER.PORTFOLIO_CIF
     *
     * @return the value of IPO_SUBSCRIBER.PORTFOLIO_CIF
     */
    public BigDecimal getPORTFOLIO_CIF() {
        return PORTFOLIO_CIF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IPO_SUBSCRIBER.PORTFOLIO_CIF
     *
     * @param PORTFOLIO_CIF the value for IPO_SUBSCRIBER.PORTFOLIO_CIF
     */
    public void setPORTFOLIO_CIF(BigDecimal PORTFOLIO_CIF) {
        this.PORTFOLIO_CIF = PORTFOLIO_CIF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IPO_SUBSCRIBER.PORTFOLIO_SEQ
     *
     * @return the value of IPO_SUBSCRIBER.PORTFOLIO_SEQ
     */
    public BigDecimal getPORTFOLIO_SEQ() {
        return PORTFOLIO_SEQ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IPO_SUBSCRIBER.PORTFOLIO_SEQ
     *
     * @param PORTFOLIO_SEQ the value for IPO_SUBSCRIBER.PORTFOLIO_SEQ
     */
    public void setPORTFOLIO_SEQ(BigDecimal PORTFOLIO_SEQ) {
        this.PORTFOLIO_SEQ = PORTFOLIO_SEQ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IPO_SUBSCRIBER.GROUP_ID
     *
     * @return the value of IPO_SUBSCRIBER.GROUP_ID
     */
    public String getGROUP_ID() {
        return GROUP_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IPO_SUBSCRIBER.GROUP_ID
     *
     * @param GROUP_ID the value for IPO_SUBSCRIBER.GROUP_ID
     */
    public void setGROUP_ID(String GROUP_ID) {
        this.GROUP_ID = GROUP_ID == null ? null : GROUP_ID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IPO_SUBSCRIBER.BRIEF_NAME_ARAB
     *
     * @return the value of IPO_SUBSCRIBER.BRIEF_NAME_ARAB
     */
    public String getBRIEF_NAME_ARAB() {
        return BRIEF_NAME_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IPO_SUBSCRIBER.BRIEF_NAME_ARAB
     *
     * @param BRIEF_NAME_ARAB the value for IPO_SUBSCRIBER.BRIEF_NAME_ARAB
     */
    public void setBRIEF_NAME_ARAB(String BRIEF_NAME_ARAB) {
        this.BRIEF_NAME_ARAB = BRIEF_NAME_ARAB == null ? null : BRIEF_NAME_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IPO_SUBSCRIBER.LONG_NAME_ARAB
     *
     * @return the value of IPO_SUBSCRIBER.LONG_NAME_ARAB
     */
    public String getLONG_NAME_ARAB() {
        return LONG_NAME_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IPO_SUBSCRIBER.LONG_NAME_ARAB
     *
     * @param LONG_NAME_ARAB the value for IPO_SUBSCRIBER.LONG_NAME_ARAB
     */
    public void setLONG_NAME_ARAB(String LONG_NAME_ARAB) {
        this.LONG_NAME_ARAB = LONG_NAME_ARAB == null ? null : LONG_NAME_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IPO_SUBSCRIBER.ADDRESS_ENG1
     *
     * @return the value of IPO_SUBSCRIBER.ADDRESS_ENG1
     */
    public String getADDRESS_ENG1() {
        return ADDRESS_ENG1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IPO_SUBSCRIBER.ADDRESS_ENG1
     *
     * @param ADDRESS_ENG1 the value for IPO_SUBSCRIBER.ADDRESS_ENG1
     */
    public void setADDRESS_ENG1(String ADDRESS_ENG1) {
        this.ADDRESS_ENG1 = ADDRESS_ENG1 == null ? null : ADDRESS_ENG1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IPO_SUBSCRIBER.ADDRESS_ENG2
     *
     * @return the value of IPO_SUBSCRIBER.ADDRESS_ENG2
     */
    public String getADDRESS_ENG2() {
        return ADDRESS_ENG2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IPO_SUBSCRIBER.ADDRESS_ENG2
     *
     * @param ADDRESS_ENG2 the value for IPO_SUBSCRIBER.ADDRESS_ENG2
     */
    public void setADDRESS_ENG2(String ADDRESS_ENG2) {
        this.ADDRESS_ENG2 = ADDRESS_ENG2 == null ? null : ADDRESS_ENG2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IPO_SUBSCRIBER.ADDRESS_ENG3
     *
     * @return the value of IPO_SUBSCRIBER.ADDRESS_ENG3
     */
    public String getADDRESS_ENG3() {
        return ADDRESS_ENG3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IPO_SUBSCRIBER.ADDRESS_ENG3
     *
     * @param ADDRESS_ENG3 the value for IPO_SUBSCRIBER.ADDRESS_ENG3
     */
    public void setADDRESS_ENG3(String ADDRESS_ENG3) {
        this.ADDRESS_ENG3 = ADDRESS_ENG3 == null ? null : ADDRESS_ENG3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IPO_SUBSCRIBER.ADDRESS_ARAB1
     *
     * @return the value of IPO_SUBSCRIBER.ADDRESS_ARAB1
     */
    public String getADDRESS_ARAB1() {
        return ADDRESS_ARAB1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IPO_SUBSCRIBER.ADDRESS_ARAB1
     *
     * @param ADDRESS_ARAB1 the value for IPO_SUBSCRIBER.ADDRESS_ARAB1
     */
    public void setADDRESS_ARAB1(String ADDRESS_ARAB1) {
        this.ADDRESS_ARAB1 = ADDRESS_ARAB1 == null ? null : ADDRESS_ARAB1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IPO_SUBSCRIBER.ADDRESS_ARAB2
     *
     * @return the value of IPO_SUBSCRIBER.ADDRESS_ARAB2
     */
    public String getADDRESS_ARAB2() {
        return ADDRESS_ARAB2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IPO_SUBSCRIBER.ADDRESS_ARAB2
     *
     * @param ADDRESS_ARAB2 the value for IPO_SUBSCRIBER.ADDRESS_ARAB2
     */
    public void setADDRESS_ARAB2(String ADDRESS_ARAB2) {
        this.ADDRESS_ARAB2 = ADDRESS_ARAB2 == null ? null : ADDRESS_ARAB2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IPO_SUBSCRIBER.ADDRESS_ARAB3
     *
     * @return the value of IPO_SUBSCRIBER.ADDRESS_ARAB3
     */
    public String getADDRESS_ARAB3() {
        return ADDRESS_ARAB3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IPO_SUBSCRIBER.ADDRESS_ARAB3
     *
     * @param ADDRESS_ARAB3 the value for IPO_SUBSCRIBER.ADDRESS_ARAB3
     */
    public void setADDRESS_ARAB3(String ADDRESS_ARAB3) {
        this.ADDRESS_ARAB3 = ADDRESS_ARAB3 == null ? null : ADDRESS_ARAB3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IPO_SUBSCRIBER.STATUS
     *
     * @return the value of IPO_SUBSCRIBER.STATUS
     */
    public String getSTATUS() {
        return STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IPO_SUBSCRIBER.STATUS
     *
     * @param STATUS the value for IPO_SUBSCRIBER.STATUS
     */
    public void setSTATUS(String STATUS) {
        this.STATUS = STATUS == null ? null : STATUS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IPO_SUBSCRIBER.CREATED_BY
     *
     * @return the value of IPO_SUBSCRIBER.CREATED_BY
     */
    public String getCREATED_BY() {
        return CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IPO_SUBSCRIBER.CREATED_BY
     *
     * @param CREATED_BY the value for IPO_SUBSCRIBER.CREATED_BY
     */
    public void setCREATED_BY(String CREATED_BY) {
        this.CREATED_BY = CREATED_BY == null ? null : CREATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IPO_SUBSCRIBER.DATE_CREATED
     *
     * @return the value of IPO_SUBSCRIBER.DATE_CREATED
     */
    public Date getDATE_CREATED() {
        return DATE_CREATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IPO_SUBSCRIBER.DATE_CREATED
     *
     * @param DATE_CREATED the value for IPO_SUBSCRIBER.DATE_CREATED
     */
    public void setDATE_CREATED(Date DATE_CREATED) {
        this.DATE_CREATED = DATE_CREATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IPO_SUBSCRIBER.MODIFIED_BY
     *
     * @return the value of IPO_SUBSCRIBER.MODIFIED_BY
     */
    public String getMODIFIED_BY() {
        return MODIFIED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IPO_SUBSCRIBER.MODIFIED_BY
     *
     * @param MODIFIED_BY the value for IPO_SUBSCRIBER.MODIFIED_BY
     */
    public void setMODIFIED_BY(String MODIFIED_BY) {
        this.MODIFIED_BY = MODIFIED_BY == null ? null : MODIFIED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IPO_SUBSCRIBER.DATE_MODIFIED
     *
     * @return the value of IPO_SUBSCRIBER.DATE_MODIFIED
     */
    public Date getDATE_MODIFIED() {
        return DATE_MODIFIED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IPO_SUBSCRIBER.DATE_MODIFIED
     *
     * @param DATE_MODIFIED the value for IPO_SUBSCRIBER.DATE_MODIFIED
     */
    public void setDATE_MODIFIED(Date DATE_MODIFIED) {
        this.DATE_MODIFIED = DATE_MODIFIED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IPO_SUBSCRIBER.DELETED_BY
     *
     * @return the value of IPO_SUBSCRIBER.DELETED_BY
     */
    public String getDELETED_BY() {
        return DELETED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IPO_SUBSCRIBER.DELETED_BY
     *
     * @param DELETED_BY the value for IPO_SUBSCRIBER.DELETED_BY
     */
    public void setDELETED_BY(String DELETED_BY) {
        this.DELETED_BY = DELETED_BY == null ? null : DELETED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IPO_SUBSCRIBER.DATE_DELETED
     *
     * @return the value of IPO_SUBSCRIBER.DATE_DELETED
     */
    public Date getDATE_DELETED() {
        return DATE_DELETED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IPO_SUBSCRIBER.DATE_DELETED
     *
     * @param DATE_DELETED the value for IPO_SUBSCRIBER.DATE_DELETED
     */
    public void setDATE_DELETED(Date DATE_DELETED) {
        this.DATE_DELETED = DATE_DELETED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IPO_SUBSCRIBER.SUSPENDED_BY
     *
     * @return the value of IPO_SUBSCRIBER.SUSPENDED_BY
     */
    public String getSUSPENDED_BY() {
        return SUSPENDED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IPO_SUBSCRIBER.SUSPENDED_BY
     *
     * @param SUSPENDED_BY the value for IPO_SUBSCRIBER.SUSPENDED_BY
     */
    public void setSUSPENDED_BY(String SUSPENDED_BY) {
        this.SUSPENDED_BY = SUSPENDED_BY == null ? null : SUSPENDED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IPO_SUBSCRIBER.DATE_SUSPENDED
     *
     * @return the value of IPO_SUBSCRIBER.DATE_SUSPENDED
     */
    public Date getDATE_SUSPENDED() {
        return DATE_SUSPENDED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IPO_SUBSCRIBER.DATE_SUSPENDED
     *
     * @param DATE_SUSPENDED the value for IPO_SUBSCRIBER.DATE_SUSPENDED
     */
    public void setDATE_SUSPENDED(Date DATE_SUSPENDED) {
        this.DATE_SUSPENDED = DATE_SUSPENDED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IPO_SUBSCRIBER.REACTIVATED_BY
     *
     * @return the value of IPO_SUBSCRIBER.REACTIVATED_BY
     */
    public String getREACTIVATED_BY() {
        return REACTIVATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IPO_SUBSCRIBER.REACTIVATED_BY
     *
     * @param REACTIVATED_BY the value for IPO_SUBSCRIBER.REACTIVATED_BY
     */
    public void setREACTIVATED_BY(String REACTIVATED_BY) {
        this.REACTIVATED_BY = REACTIVATED_BY == null ? null : REACTIVATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IPO_SUBSCRIBER.DATE_REACTIVATED
     *
     * @return the value of IPO_SUBSCRIBER.DATE_REACTIVATED
     */
    public Date getDATE_REACTIVATED() {
        return DATE_REACTIVATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IPO_SUBSCRIBER.DATE_REACTIVATED
     *
     * @param DATE_REACTIVATED the value for IPO_SUBSCRIBER.DATE_REACTIVATED
     */
    public void setDATE_REACTIVATED(Date DATE_REACTIVATED) {
        this.DATE_REACTIVATED = DATE_REACTIVATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IPO_SUBSCRIBER.ID_NUMBER
     *
     * @return the value of IPO_SUBSCRIBER.ID_NUMBER
     */
    public String getID_NUMBER() {
        return ID_NUMBER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IPO_SUBSCRIBER.ID_NUMBER
     *
     * @param ID_NUMBER the value for IPO_SUBSCRIBER.ID_NUMBER
     */
    public void setID_NUMBER(String ID_NUMBER) {
        this.ID_NUMBER = ID_NUMBER == null ? null : ID_NUMBER.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IPO_SUBSCRIBER.LOCK_UP_PERIOD
     *
     * @return the value of IPO_SUBSCRIBER.LOCK_UP_PERIOD
     */
    public BigDecimal getLOCK_UP_PERIOD() {
        return LOCK_UP_PERIOD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IPO_SUBSCRIBER.LOCK_UP_PERIOD
     *
     * @param LOCK_UP_PERIOD the value for IPO_SUBSCRIBER.LOCK_UP_PERIOD
     */
    public void setLOCK_UP_PERIOD(BigDecimal LOCK_UP_PERIOD) {
        this.LOCK_UP_PERIOD = LOCK_UP_PERIOD;
    }
}