package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class IPO_SUBSCRIBERVOKey extends BaseVO {
    /**
     * This field corresponds to the database column IPO_SUBSCRIBER.BRANCH_CODE
     */
    private BigDecimal BRANCH_CODE;

    /**
     * This field corresponds to the database column IPO_SUBSCRIBER.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column IPO_SUBSCRIBER.SUBSCRIBER_ID
     */
    private BigDecimal SUBSCRIBER_ID;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IPO_SUBSCRIBER.BRANCH_CODE
     *
     * @return the value of IPO_SUBSCRIBER.BRANCH_CODE
     */
    public BigDecimal getBRANCH_CODE() {
        return BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IPO_SUBSCRIBER.BRANCH_CODE
     *
     * @param BRANCH_CODE the value for IPO_SUBSCRIBER.BRANCH_CODE
     */
    public void setBRANCH_CODE(BigDecimal BRANCH_CODE) {
        this.BRANCH_CODE = BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IPO_SUBSCRIBER.COMP_CODE
     *
     * @return the value of IPO_SUBSCRIBER.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IPO_SUBSCRIBER.COMP_CODE
     *
     * @param COMP_CODE the value for IPO_SUBSCRIBER.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IPO_SUBSCRIBER.SUBSCRIBER_ID
     *
     * @return the value of IPO_SUBSCRIBER.SUBSCRIBER_ID
     */
    public BigDecimal getSUBSCRIBER_ID() {
        return SUBSCRIBER_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IPO_SUBSCRIBER.SUBSCRIBER_ID
     *
     * @param SUBSCRIBER_ID the value for IPO_SUBSCRIBER.SUBSCRIBER_ID
     */
    public void setSUBSCRIBER_ID(BigDecimal SUBSCRIBER_ID) {
        this.SUBSCRIBER_ID = SUBSCRIBER_ID;
    }
}