package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class ITR_COUNTRY_OF_BIRTHVOKey extends BaseVO {
    /**
     * This field corresponds to the database column ITR_COUNTRY_OF_BIRTH.CODE
     */
    private BigDecimal CODE;

    /**
     * This field corresponds to the database column ITR_COUNTRY_OF_BIRTH.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column ITR_COUNTRY_OF_BIRTH.TAX_REG_ID
     */
    private BigDecimal TAX_REG_ID;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ITR_COUNTRY_OF_BIRTH.CODE
     *
     * @return the value of ITR_COUNTRY_OF_BIRTH.CODE
     */
    public BigDecimal getCODE() {
        return CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ITR_COUNTRY_OF_BIRTH.CODE
     *
     * @param CODE the value for ITR_COUNTRY_OF_BIRTH.CODE
     */
    public void setCODE(BigDecimal CODE) {
        this.CODE = CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ITR_COUNTRY_OF_BIRTH.COMP_CODE
     *
     * @return the value of ITR_COUNTRY_OF_BIRTH.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ITR_COUNTRY_OF_BIRTH.COMP_CODE
     *
     * @param COMP_CODE the value for ITR_COUNTRY_OF_BIRTH.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ITR_COUNTRY_OF_BIRTH.TAX_REG_ID
     *
     * @return the value of ITR_COUNTRY_OF_BIRTH.TAX_REG_ID
     */
    public BigDecimal getTAX_REG_ID() {
        return TAX_REG_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ITR_COUNTRY_OF_BIRTH.TAX_REG_ID
     *
     * @param TAX_REG_ID the value for ITR_COUNTRY_OF_BIRTH.TAX_REG_ID
     */
    public void setTAX_REG_ID(BigDecimal TAX_REG_ID) {
        this.TAX_REG_ID = TAX_REG_ID;
    }
}