package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class JV_TYPEVOKey extends BaseVO {
    /**
     * This field corresponds to the database column JV_TYPE.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column JV_TYPE.TYPE_CODE
     */
    private BigDecimal TYPE_CODE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JV_TYPE.COMP_CODE
     *
     * @return the value of JV_TYPE.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JV_TYPE.COMP_CODE
     *
     * @param COMP_CODE the value for JV_TYPE.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JV_TYPE.TYPE_CODE
     *
     * @return the value of JV_TYPE.TYPE_CODE
     */
    public BigDecimal getTYPE_CODE() {
        return TYPE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JV_TYPE.TYPE_CODE
     *
     * @param TYPE_CODE the value for JV_TYPE.TYPE_CODE
     */
    public void setTYPE_CODE(BigDecimal TYPE_CODE) {
        this.TYPE_CODE = TYPE_CODE;
    }
}