package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class LOCVO extends LOCVOKey {
    /**
     * This field corresponds to the database column LOC.DIVISION_CODE
     */
    private BigDecimal DIVISION_CODE;

    /**
     * This field corresponds to the database column LOC.DEPT_CODE
     */
    private BigDecimal DEPT_CODE;

    /**
     * This field corresponds to the database column LOC.USER_LOC_STS
     */
    private String USER_LOC_STS;

    /**
     * This field corresponds to the database column LOC.MACHINE_ID
     */
    private String MACHINE_ID;

    /**
     * This field corresponds to the database column LOC.MACHINE_ID_WEB
     */
    private String MACHINE_ID_WEB;

    /**
     * This field corresponds to the database column LOC.USER_LOC_STS_WEB
     */
    private String USER_LOC_STS_WEB;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOC.DIVISION_CODE
     *
     * @return the value of LOC.DIVISION_CODE
     */
    public BigDecimal getDIVISION_CODE() {
        return DIVISION_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOC.DIVISION_CODE
     *
     * @param DIVISION_CODE the value for LOC.DIVISION_CODE
     */
    public void setDIVISION_CODE(BigDecimal DIVISION_CODE) {
        this.DIVISION_CODE = DIVISION_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOC.DEPT_CODE
     *
     * @return the value of LOC.DEPT_CODE
     */
    public BigDecimal getDEPT_CODE() {
        return DEPT_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOC.DEPT_CODE
     *
     * @param DEPT_CODE the value for LOC.DEPT_CODE
     */
    public void setDEPT_CODE(BigDecimal DEPT_CODE) {
        this.DEPT_CODE = DEPT_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOC.USER_LOC_STS
     *
     * @return the value of LOC.USER_LOC_STS
     */
    public String getUSER_LOC_STS() {
        return USER_LOC_STS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOC.USER_LOC_STS
     *
     * @param USER_LOC_STS the value for LOC.USER_LOC_STS
     */
    public void setUSER_LOC_STS(String USER_LOC_STS) {
        this.USER_LOC_STS = USER_LOC_STS == null ? null : USER_LOC_STS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOC.MACHINE_ID
     *
     * @return the value of LOC.MACHINE_ID
     */
    public String getMACHINE_ID() {
        return MACHINE_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOC.MACHINE_ID
     *
     * @param MACHINE_ID the value for LOC.MACHINE_ID
     */
    public void setMACHINE_ID(String MACHINE_ID) {
        this.MACHINE_ID = MACHINE_ID == null ? null : MACHINE_ID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOC.MACHINE_ID_WEB
     *
     * @return the value of LOC.MACHINE_ID_WEB
     */
    public String getMACHINE_ID_WEB() {
        return MACHINE_ID_WEB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOC.MACHINE_ID_WEB
     *
     * @param MACHINE_ID_WEB the value for LOC.MACHINE_ID_WEB
     */
    public void setMACHINE_ID_WEB(String MACHINE_ID_WEB) {
        this.MACHINE_ID_WEB = MACHINE_ID_WEB == null ? null : MACHINE_ID_WEB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOC.USER_LOC_STS_WEB
     *
     * @return the value of LOC.USER_LOC_STS_WEB
     */
    public String getUSER_LOC_STS_WEB() {
        return USER_LOC_STS_WEB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOC.USER_LOC_STS_WEB
     *
     * @param USER_LOC_STS_WEB the value for LOC.USER_LOC_STS_WEB
     */
    public void setUSER_LOC_STS_WEB(String USER_LOC_STS_WEB) {
        this.USER_LOC_STS_WEB = USER_LOC_STS_WEB == null ? null : USER_LOC_STS_WEB.trim();
    }
}