package com.path.dbmaps.vo;

public class NATIONALITYVO extends NATIONALITYVOKey {
    /**
     * This field corresponds to the database column NATIONALITY.BRIEF_DESC_ENG
     */
    private String BRIEF_DESC_ENG;

    /**
     * This field corresponds to the database column NATIONALITY.LONG_DESC_ENG
     */
    private String LONG_DESC_ENG;

    /**
     * This field corresponds to the database column NATIONALITY.BRIEF_DESC_ARAB
     */
    private String BRIEF_DESC_ARAB;

    /**
     * This field corresponds to the database column NATIONALITY.LONG_DESC_ARAB
     */
    private String LONG_DESC_ARAB;

    /**
     * This field corresponds to the database column NATIONALITY.ADDITIONAL_REFERENCE
     */
    private String ADDITIONAL_REFERENCE;

    /**
     * This field corresponds to the database column NATIONALITY.DOUBTFULL
     */
    private String DOUBTFULL;
    
    /**
     * This field corresponds to the database column NATIONALITY.ISO_NATIONALITY
     */
    private String ISO_NATIONALITY;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NATIONALITY.BRIEF_DESC_ENG
     *
     * @return the value of NATIONALITY.BRIEF_DESC_ENG
     */
    public String getBRIEF_DESC_ENG() {
        return BRIEF_DESC_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NATIONALITY.BRIEF_DESC_ENG
     *
     * @param BRIEF_DESC_ENG the value for NATIONALITY.BRIEF_DESC_ENG
     */
    public void setBRIEF_DESC_ENG(String BRIEF_DESC_ENG) {
        this.BRIEF_DESC_ENG = BRIEF_DESC_ENG == null ? null : BRIEF_DESC_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NATIONALITY.LONG_DESC_ENG
     *
     * @return the value of NATIONALITY.LONG_DESC_ENG
     */
    public String getLONG_DESC_ENG() {
        return LONG_DESC_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NATIONALITY.LONG_DESC_ENG
     *
     * @param LONG_DESC_ENG the value for NATIONALITY.LONG_DESC_ENG
     */
    public void setLONG_DESC_ENG(String LONG_DESC_ENG) {
        this.LONG_DESC_ENG = LONG_DESC_ENG == null ? null : LONG_DESC_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NATIONALITY.BRIEF_DESC_ARAB
     *
     * @return the value of NATIONALITY.BRIEF_DESC_ARAB
     */
    public String getBRIEF_DESC_ARAB() {
        return BRIEF_DESC_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NATIONALITY.BRIEF_DESC_ARAB
     *
     * @param BRIEF_DESC_ARAB the value for NATIONALITY.BRIEF_DESC_ARAB
     */
    public void setBRIEF_DESC_ARAB(String BRIEF_DESC_ARAB) {
        this.BRIEF_DESC_ARAB = BRIEF_DESC_ARAB == null ? null : BRIEF_DESC_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NATIONALITY.LONG_DESC_ARAB
     *
     * @return the value of NATIONALITY.LONG_DESC_ARAB
     */
    public String getLONG_DESC_ARAB() {
        return LONG_DESC_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NATIONALITY.LONG_DESC_ARAB
     *
     * @param LONG_DESC_ARAB the value for NATIONALITY.LONG_DESC_ARAB
     */
    public void setLONG_DESC_ARAB(String LONG_DESC_ARAB) {
        this.LONG_DESC_ARAB = LONG_DESC_ARAB == null ? null : LONG_DESC_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NATIONALITY.ADDITIONAL_REFERENCE
     *
     * @return the value of NATIONALITY.ADDITIONAL_REFERENCE
     */
    public String getADDITIONAL_REFERENCE() {
        return ADDITIONAL_REFERENCE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NATIONALITY.ADDITIONAL_REFERENCE
     *
     * @param ADDITIONAL_REFERENCE the value for NATIONALITY.ADDITIONAL_REFERENCE
     */
    public void setADDITIONAL_REFERENCE(String ADDITIONAL_REFERENCE) {
        this.ADDITIONAL_REFERENCE = ADDITIONAL_REFERENCE == null ? null : ADDITIONAL_REFERENCE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NATIONALITY.DOUBTFULL
     *
     * @return the value of NATIONALITY.DOUBTFULL
     */
    public String getDOUBTFULL() {
        return DOUBTFULL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NATIONALITY.DOUBTFULL
     *
     * @param DOUBTFULL the value for NATIONALITY.DOUBTFULL
     */
    public void setDOUBTFULL(String DOUBTFULL) {
        this.DOUBTFULL = DOUBTFULL == null ? null : DOUBTFULL.trim();
    }
    

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NATIONALITY.ISO_NATIONALITY
     *
     * @return the value of NATIONALITY.ISO_NATIONALITY
     */
    public String getISO_NATIONALITY() {
        return ISO_NATIONALITY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NATIONALITY.ISO_NATIONALITY
     *
     * @param ISO_NATIONALITY the value for NATIONALITY.ISO_NATIONALITY
     */
    public void setISO_NATIONALITY(String ISO_NATIONALITY) {
        this.ISO_NATIONALITY = ISO_NATIONALITY == null ? null : ISO_NATIONALITY.trim();
    }
}