package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class OPT_EXTENDEDVO extends OPT_EXTENDEDVOKey {
    /**
     * This field corresponds to the database column OPT_EXTENDED.OPT_URL
     */
    private String OPT_URL;

    /**
     * This field corresponds to the database column OPT_EXTENDED.AUDIT_PROG_REF
     */
    private String AUDIT_PROG_REF;

    /**
     * This field corresponds to the database column OPT_EXTENDED.IV_CRUD
     */
    private String IV_CRUD;

    /**
     * This field corresponds to the database column OPT_EXTENDED.OPT_REFERENCE
     */
    private String OPT_REFERENCE;

    /**
     * This field corresponds to the database column OPT_EXTENDED.TARGET_APP_NAME
     */
    private String TARGET_APP_NAME;

    /**
     * This field corresponds to the database column OPT_EXTENDED.TARGET_PROG_REF
     */
    private String TARGET_PROG_REF;

    /**
     * This field corresponds to the database column OPT_EXTENDED.FOR_SERIES_PROG_REF
     */
    private String FOR_SERIES_PROG_REF;

    /**
     * This field corresponds to the database column OPT_EXTENDED.REPORT_SRC_APP_NAME
     */
    private String REPORT_SRC_APP_NAME;

    /**
     * This field corresponds to the database column OPT_EXTENDED.ADDITIONAL_PARENT_REF
     */
    private String ADDITIONAL_PARENT_REF;

    /**
     * This field corresponds to the database column OPT_EXTENDED.DYN_SCREEN_ID
     */
    private BigDecimal DYN_SCREEN_ID;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OPT_EXTENDED.OPT_URL
     *
     * @return the value of OPT_EXTENDED.OPT_URL
     */
    public String getOPT_URL() {
        return OPT_URL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OPT_EXTENDED.OPT_URL
     *
     * @param OPT_URL the value for OPT_EXTENDED.OPT_URL
     */
    public void setOPT_URL(String OPT_URL) {
        this.OPT_URL = OPT_URL == null ? null : OPT_URL.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OPT_EXTENDED.AUDIT_PROG_REF
     *
     * @return the value of OPT_EXTENDED.AUDIT_PROG_REF
     */
    public String getAUDIT_PROG_REF() {
        return AUDIT_PROG_REF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OPT_EXTENDED.AUDIT_PROG_REF
     *
     * @param AUDIT_PROG_REF the value for OPT_EXTENDED.AUDIT_PROG_REF
     */
    public void setAUDIT_PROG_REF(String AUDIT_PROG_REF) {
        this.AUDIT_PROG_REF = AUDIT_PROG_REF == null ? null : AUDIT_PROG_REF.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OPT_EXTENDED.IV_CRUD
     *
     * @return the value of OPT_EXTENDED.IV_CRUD
     */
    public String getIV_CRUD() {
        return IV_CRUD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OPT_EXTENDED.IV_CRUD
     *
     * @param IV_CRUD the value for OPT_EXTENDED.IV_CRUD
     */
    public void setIV_CRUD(String IV_CRUD) {
        this.IV_CRUD = IV_CRUD == null ? null : IV_CRUD.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OPT_EXTENDED.OPT_REFERENCE
     *
     * @return the value of OPT_EXTENDED.OPT_REFERENCE
     */
    public String getOPT_REFERENCE() {
        return OPT_REFERENCE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OPT_EXTENDED.OPT_REFERENCE
     *
     * @param OPT_REFERENCE the value for OPT_EXTENDED.OPT_REFERENCE
     */
    public void setOPT_REFERENCE(String OPT_REFERENCE) {
        this.OPT_REFERENCE = OPT_REFERENCE == null ? null : OPT_REFERENCE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OPT_EXTENDED.TARGET_APP_NAME
     *
     * @return the value of OPT_EXTENDED.TARGET_APP_NAME
     */
    public String getTARGET_APP_NAME() {
        return TARGET_APP_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OPT_EXTENDED.TARGET_APP_NAME
     *
     * @param TARGET_APP_NAME the value for OPT_EXTENDED.TARGET_APP_NAME
     */
    public void setTARGET_APP_NAME(String TARGET_APP_NAME) {
        this.TARGET_APP_NAME = TARGET_APP_NAME == null ? null : TARGET_APP_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OPT_EXTENDED.TARGET_PROG_REF
     *
     * @return the value of OPT_EXTENDED.TARGET_PROG_REF
     */
    public String getTARGET_PROG_REF() {
        return TARGET_PROG_REF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OPT_EXTENDED.TARGET_PROG_REF
     *
     * @param TARGET_PROG_REF the value for OPT_EXTENDED.TARGET_PROG_REF
     */
    public void setTARGET_PROG_REF(String TARGET_PROG_REF) {
        this.TARGET_PROG_REF = TARGET_PROG_REF == null ? null : TARGET_PROG_REF.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OPT_EXTENDED.FOR_SERIES_PROG_REF
     *
     * @return the value of OPT_EXTENDED.FOR_SERIES_PROG_REF
     */
    public String getFOR_SERIES_PROG_REF() {
        return FOR_SERIES_PROG_REF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OPT_EXTENDED.FOR_SERIES_PROG_REF
     *
     * @param FOR_SERIES_PROG_REF the value for OPT_EXTENDED.FOR_SERIES_PROG_REF
     */
    public void setFOR_SERIES_PROG_REF(String FOR_SERIES_PROG_REF) {
        this.FOR_SERIES_PROG_REF = FOR_SERIES_PROG_REF == null ? null : FOR_SERIES_PROG_REF.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OPT_EXTENDED.REPORT_SRC_APP_NAME
     *
     * @return the value of OPT_EXTENDED.REPORT_SRC_APP_NAME
     */
    public String getREPORT_SRC_APP_NAME() {
        return REPORT_SRC_APP_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OPT_EXTENDED.REPORT_SRC_APP_NAME
     *
     * @param REPORT_SRC_APP_NAME the value for OPT_EXTENDED.REPORT_SRC_APP_NAME
     */
    public void setREPORT_SRC_APP_NAME(String REPORT_SRC_APP_NAME) {
        this.REPORT_SRC_APP_NAME = REPORT_SRC_APP_NAME == null ? null : REPORT_SRC_APP_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OPT_EXTENDED.ADDITIONAL_PARENT_REF
     *
     * @return the value of OPT_EXTENDED.ADDITIONAL_PARENT_REF
     */
    public String getADDITIONAL_PARENT_REF() {
        return ADDITIONAL_PARENT_REF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OPT_EXTENDED.ADDITIONAL_PARENT_REF
     *
     * @param ADDITIONAL_PARENT_REF the value for OPT_EXTENDED.ADDITIONAL_PARENT_REF
     */
    public void setADDITIONAL_PARENT_REF(String ADDITIONAL_PARENT_REF) {
        this.ADDITIONAL_PARENT_REF = ADDITIONAL_PARENT_REF == null ? null : ADDITIONAL_PARENT_REF.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OPT_EXTENDED.DYN_SCREEN_ID
     *
     * @return the value of OPT_EXTENDED.DYN_SCREEN_ID
     */
    public BigDecimal getDYN_SCREEN_ID() {
        return DYN_SCREEN_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OPT_EXTENDED.DYN_SCREEN_ID
     *
     * @param DYN_SCREEN_ID the value for OPT_EXTENDED.DYN_SCREEN_ID
     */
    public void setDYN_SCREEN_ID(BigDecimal DYN_SCREEN_ID) {
        this.DYN_SCREEN_ID = DYN_SCREEN_ID;
    }
}