package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class OPT_CATEGORYVO extends BaseVO {
    /**
     * This field corresponds to the database column IMAL141_DEV_O18.OPT_CATEGORY.CATEG_ID
     */
    private BigDecimal CATEG_ID;

    /**
     * This field corresponds to the database column IMAL141_DEV_O18.OPT_CATEGORY.CATEG_DESC_FR
     */
    private String CATEG_DESC_FR;

    /**
     * This field corresponds to the database column IMAL141_DEV_O18.OPT_CATEGORY.CATEG_DESC_ENG
     */
    private String CATEG_DESC_ENG;

    /**
     * This field corresponds to the database column IMAL141_DEV_O18.OPT_CATEGORY.CATEG_DESC_AR
     */
    private String CATEG_DESC_AR;

    /**
     * This field corresponds to the database column IMAL141_DEV_O18.OPT_CATEGORY.CATEG_DESC_FA
     */
    private String CATEG_DESC_FA;

    /**
     * This field corresponds to the database column IMAL141_DEV_O18.OPT_CATEGORY.CATEG_DESC_RU
     */
    private String CATEG_DESC_RU;

    /**
     * This field corresponds to the database column IMAL141_DEV_O18.OPT_CATEGORY.CATEG_DESC_TK
     */
    private String CATEG_DESC_TK;

    /**
     * This field corresponds to the database column IMAL141_DEV_O18.OPT_CATEGORY.DISPLAY_ORDER
     */
    private BigDecimal DISPLAY_ORDER;

    /**
     * This field corresponds to the database column IMAL141_DEV_O18.OPT_CATEGORY.IS_WEB_YN
     */
    private BigDecimal IS_WEB_YN;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMAL141_DEV_O18.OPT_CATEGORY.CATEG_ID
     *
     * @return the value of IMAL141_DEV_O18.OPT_CATEGORY.CATEG_ID
     */
    public BigDecimal getCATEG_ID() {
        return CATEG_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMAL141_DEV_O18.OPT_CATEGORY.CATEG_ID
     *
     * @param CATEG_ID the value for IMAL141_DEV_O18.OPT_CATEGORY.CATEG_ID
     */
    public void setCATEG_ID(BigDecimal CATEG_ID) {
        this.CATEG_ID = CATEG_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMAL141_DEV_O18.OPT_CATEGORY.CATEG_DESC_FR
     *
     * @return the value of IMAL141_DEV_O18.OPT_CATEGORY.CATEG_DESC_FR
     */
    public String getCATEG_DESC_FR() {
        return CATEG_DESC_FR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMAL141_DEV_O18.OPT_CATEGORY.CATEG_DESC_FR
     *
     * @param CATEG_DESC_FR the value for IMAL141_DEV_O18.OPT_CATEGORY.CATEG_DESC_FR
     */
    public void setCATEG_DESC_FR(String CATEG_DESC_FR) {
        this.CATEG_DESC_FR = CATEG_DESC_FR == null ? null : CATEG_DESC_FR.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMAL141_DEV_O18.OPT_CATEGORY.CATEG_DESC_ENG
     *
     * @return the value of IMAL141_DEV_O18.OPT_CATEGORY.CATEG_DESC_ENG
     */
    public String getCATEG_DESC_ENG() {
        return CATEG_DESC_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMAL141_DEV_O18.OPT_CATEGORY.CATEG_DESC_ENG
     *
     * @param CATEG_DESC_ENG the value for IMAL141_DEV_O18.OPT_CATEGORY.CATEG_DESC_ENG
     */
    public void setCATEG_DESC_ENG(String CATEG_DESC_ENG) {
        this.CATEG_DESC_ENG = CATEG_DESC_ENG == null ? null : CATEG_DESC_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMAL141_DEV_O18.OPT_CATEGORY.CATEG_DESC_AR
     *
     * @return the value of IMAL141_DEV_O18.OPT_CATEGORY.CATEG_DESC_AR
     */
    public String getCATEG_DESC_AR() {
        return CATEG_DESC_AR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMAL141_DEV_O18.OPT_CATEGORY.CATEG_DESC_AR
     *
     * @param CATEG_DESC_AR the value for IMAL141_DEV_O18.OPT_CATEGORY.CATEG_DESC_AR
     */
    public void setCATEG_DESC_AR(String CATEG_DESC_AR) {
        this.CATEG_DESC_AR = CATEG_DESC_AR == null ? null : CATEG_DESC_AR.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMAL141_DEV_O18.OPT_CATEGORY.CATEG_DESC_FA
     *
     * @return the value of IMAL141_DEV_O18.OPT_CATEGORY.CATEG_DESC_FA
     */
    public String getCATEG_DESC_FA() {
        return CATEG_DESC_FA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMAL141_DEV_O18.OPT_CATEGORY.CATEG_DESC_FA
     *
     * @param CATEG_DESC_FA the value for IMAL141_DEV_O18.OPT_CATEGORY.CATEG_DESC_FA
     */
    public void setCATEG_DESC_FA(String CATEG_DESC_FA) {
        this.CATEG_DESC_FA = CATEG_DESC_FA == null ? null : CATEG_DESC_FA.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMAL141_DEV_O18.OPT_CATEGORY.CATEG_DESC_RU
     *
     * @return the value of IMAL141_DEV_O18.OPT_CATEGORY.CATEG_DESC_RU
     */
    public String getCATEG_DESC_RU() {
        return CATEG_DESC_RU;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMAL141_DEV_O18.OPT_CATEGORY.CATEG_DESC_RU
     *
     * @param CATEG_DESC_RU the value for IMAL141_DEV_O18.OPT_CATEGORY.CATEG_DESC_RU
     */
    public void setCATEG_DESC_RU(String CATEG_DESC_RU) {
        this.CATEG_DESC_RU = CATEG_DESC_RU == null ? null : CATEG_DESC_RU.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMAL141_DEV_O18.OPT_CATEGORY.CATEG_DESC_TK
     *
     * @return the value of IMAL141_DEV_O18.OPT_CATEGORY.CATEG_DESC_TK
     */
    public String getCATEG_DESC_TK() {
        return CATEG_DESC_TK;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMAL141_DEV_O18.OPT_CATEGORY.CATEG_DESC_TK
     *
     * @param CATEG_DESC_TK the value for IMAL141_DEV_O18.OPT_CATEGORY.CATEG_DESC_TK
     */
    public void setCATEG_DESC_TK(String CATEG_DESC_TK) {
        this.CATEG_DESC_TK = CATEG_DESC_TK == null ? null : CATEG_DESC_TK.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMAL141_DEV_O18.OPT_CATEGORY.DISPLAY_ORDER
     *
     * @return the value of IMAL141_DEV_O18.OPT_CATEGORY.DISPLAY_ORDER
     */
    public BigDecimal getDISPLAY_ORDER() {
        return DISPLAY_ORDER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMAL141_DEV_O18.OPT_CATEGORY.DISPLAY_ORDER
     *
     * @param DISPLAY_ORDER the value for IMAL141_DEV_O18.OPT_CATEGORY.DISPLAY_ORDER
     */
    public void setDISPLAY_ORDER(BigDecimal DISPLAY_ORDER) {
        this.DISPLAY_ORDER = DISPLAY_ORDER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IMAL141_DEV_O18.OPT_CATEGORY.IS_WEB_YN
     *
     * @return the value of IMAL141_DEV_O18.OPT_CATEGORY.IS_WEB_YN
     */
    public BigDecimal getIS_WEB_YN() {
        return IS_WEB_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IMAL141_DEV_O18.OPT_CATEGORY.IS_WEB_YN
     *
     * @param IS_WEB_YN the value for IMAL141_DEV_O18.OPT_CATEGORY.IS_WEB_YN
     */
    public void setIS_WEB_YN(BigDecimal IS_WEB_YN) {
        this.IS_WEB_YN = IS_WEB_YN;
    }
}