package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class PASSBOOK_INVENTORYVO extends PASSBOOK_INVENTORYVOKey {
    /**
     * This field corresponds to the database column PASSBOOK_INVENTORY.DATE_RECEIVED
     */
    private Date DATE_RECEIVED;

    /**
     * This field corresponds to the database column PASSBOOK_INVENTORY.STATUS
     */
    private String STATUS;

    /**
     * This field corresponds to the database column PASSBOOK_INVENTORY.QUANTITY
     */
    private BigDecimal QUANTITY;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PASSBOOK_INVENTORY.DATE_RECEIVED
     *
     * @return the value of PASSBOOK_INVENTORY.DATE_RECEIVED
     */
    public Date getDATE_RECEIVED() {
        return DATE_RECEIVED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PASSBOOK_INVENTORY.DATE_RECEIVED
     *
     * @param DATE_RECEIVED the value for PASSBOOK_INVENTORY.DATE_RECEIVED
     */
    public void setDATE_RECEIVED(Date DATE_RECEIVED) {
        this.DATE_RECEIVED = DATE_RECEIVED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PASSBOOK_INVENTORY.STATUS
     *
     * @return the value of PASSBOOK_INVENTORY.STATUS
     */
    public String getSTATUS() {
        return STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PASSBOOK_INVENTORY.STATUS
     *
     * @param STATUS the value for PASSBOOK_INVENTORY.STATUS
     */
    public void setSTATUS(String STATUS) {
        this.STATUS = STATUS == null ? null : STATUS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PASSBOOK_INVENTORY.QUANTITY
     *
     * @return the value of PASSBOOK_INVENTORY.QUANTITY
     */
    public BigDecimal getQUANTITY() {
        return QUANTITY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PASSBOOK_INVENTORY.QUANTITY
     *
     * @param QUANTITY the value for PASSBOOK_INVENTORY.QUANTITY
     */
    public void setQUANTITY(BigDecimal QUANTITY) {
        this.QUANTITY = QUANTITY;
    }
}