package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class PFT_RATEVOKey extends BaseVO {
    /**
     * This field corresponds to the database column PFT_RATE.CIF_TYPE
     */
    private BigDecimal CIF_TYPE;

    /**
     * This field corresponds to the database column PFT_RATE.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column PFT_RATE.CURRENCY_CODE
     */
    private BigDecimal CURRENCY_CODE;

    /**
     * This field corresponds to the database column PFT_RATE.DR_CR_IDX
     */
    private String DR_CR_IDX;

    /**
     * This field corresponds to the database column PFT_RATE.GL_CODE
     */
    private BigDecimal GL_CODE;

    /**
     * This field corresponds to the database column PFT_RATE.LINE_NUMBER
     */
    private BigDecimal LINE_NUMBER;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PFT_RATE.CIF_TYPE
     *
     * @return the value of PFT_RATE.CIF_TYPE
     */
    public BigDecimal getCIF_TYPE() {
        return CIF_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PFT_RATE.CIF_TYPE
     *
     * @param CIF_TYPE the value for PFT_RATE.CIF_TYPE
     */
    public void setCIF_TYPE(BigDecimal CIF_TYPE) {
        this.CIF_TYPE = CIF_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PFT_RATE.COMP_CODE
     *
     * @return the value of PFT_RATE.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PFT_RATE.COMP_CODE
     *
     * @param COMP_CODE the value for PFT_RATE.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PFT_RATE.CURRENCY_CODE
     *
     * @return the value of PFT_RATE.CURRENCY_CODE
     */
    public BigDecimal getCURRENCY_CODE() {
        return CURRENCY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PFT_RATE.CURRENCY_CODE
     *
     * @param CURRENCY_CODE the value for PFT_RATE.CURRENCY_CODE
     */
    public void setCURRENCY_CODE(BigDecimal CURRENCY_CODE) {
        this.CURRENCY_CODE = CURRENCY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PFT_RATE.DR_CR_IDX
     *
     * @return the value of PFT_RATE.DR_CR_IDX
     */
    public String getDR_CR_IDX() {
        return DR_CR_IDX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PFT_RATE.DR_CR_IDX
     *
     * @param DR_CR_IDX the value for PFT_RATE.DR_CR_IDX
     */
    public void setDR_CR_IDX(String DR_CR_IDX) {
        this.DR_CR_IDX = DR_CR_IDX == null ? null : DR_CR_IDX.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PFT_RATE.GL_CODE
     *
     * @return the value of PFT_RATE.GL_CODE
     */
    public BigDecimal getGL_CODE() {
        return GL_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PFT_RATE.GL_CODE
     *
     * @param GL_CODE the value for PFT_RATE.GL_CODE
     */
    public void setGL_CODE(BigDecimal GL_CODE) {
        this.GL_CODE = GL_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PFT_RATE.LINE_NUMBER
     *
     * @return the value of PFT_RATE.LINE_NUMBER
     */
    public BigDecimal getLINE_NUMBER() {
        return LINE_NUMBER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PFT_RATE.LINE_NUMBER
     *
     * @param LINE_NUMBER the value for PFT_RATE.LINE_NUMBER
     */
    public void setLINE_NUMBER(BigDecimal LINE_NUMBER) {
        this.LINE_NUMBER = LINE_NUMBER;
    }
}