package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;
import java.util.Date;

public class PFTAMFTRXPAR_DEPOSITVOKey extends BaseVO {
    /**
     * This field corresponds to the database column PFTAMFTRXPAR_DEPOSIT.BEFORE_AFTER_FLAG
     */
    private String BEFORE_AFTER_FLAG;

    /**
     * This field corresponds to the database column PFTAMFTRXPAR_DEPOSIT.BRANCH_CODE
     */
    private BigDecimal BRANCH_CODE;

    /**
     * This field corresponds to the database column PFTAMFTRXPAR_DEPOSIT.CIF_SUB_NO
     */
    private BigDecimal CIF_SUB_NO;

    /**
     * This field corresponds to the database column PFTAMFTRXPAR_DEPOSIT.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column PFTAMFTRXPAR_DEPOSIT.CURRENCY_CODE
     */
    private BigDecimal CURRENCY_CODE;

    /**
     * This field corresponds to the database column PFTAMFTRXPAR_DEPOSIT.FROM_DTE
     */
    private Date FROM_DTE;

    /**
     * This field corresponds to the database column PFTAMFTRXPAR_DEPOSIT.GL_CODE
     */
    private BigDecimal GL_CODE;

    /**
     * This field corresponds to the database column PFTAMFTRXPAR_DEPOSIT.JV_OP_LINE_NO
     */
    private BigDecimal JV_OP_LINE_NO;

    /**
     * This field corresponds to the database column PFTAMFTRXPAR_DEPOSIT.JV_OP_NO
     */
    private BigDecimal JV_OP_NO;

    /**
     * This field corresponds to the database column PFTAMFTRXPAR_DEPOSIT.JV_TYPE
     */
    private BigDecimal JV_TYPE;

    /**
     * This field corresponds to the database column PFTAMFTRXPAR_DEPOSIT.LOG_NUMBER
     */
    private BigDecimal LOG_NUMBER;

    /**
     * This field corresponds to the database column PFTAMFTRXPAR_DEPOSIT.SL_NO
     */
    private BigDecimal SL_NO;

    /**
     * This field corresponds to the database column PFTAMFTRXPAR_DEPOSIT.TO_DATE
     */
    private Date TO_DATE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PFTAMFTRXPAR_DEPOSIT.BEFORE_AFTER_FLAG
     *
     * @return the value of PFTAMFTRXPAR_DEPOSIT.BEFORE_AFTER_FLAG
     */
    public String getBEFORE_AFTER_FLAG() {
        return BEFORE_AFTER_FLAG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PFTAMFTRXPAR_DEPOSIT.BEFORE_AFTER_FLAG
     *
     * @param BEFORE_AFTER_FLAG the value for PFTAMFTRXPAR_DEPOSIT.BEFORE_AFTER_FLAG
     */
    public void setBEFORE_AFTER_FLAG(String BEFORE_AFTER_FLAG) {
        this.BEFORE_AFTER_FLAG = BEFORE_AFTER_FLAG == null ? null : BEFORE_AFTER_FLAG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PFTAMFTRXPAR_DEPOSIT.BRANCH_CODE
     *
     * @return the value of PFTAMFTRXPAR_DEPOSIT.BRANCH_CODE
     */
    public BigDecimal getBRANCH_CODE() {
        return BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PFTAMFTRXPAR_DEPOSIT.BRANCH_CODE
     *
     * @param BRANCH_CODE the value for PFTAMFTRXPAR_DEPOSIT.BRANCH_CODE
     */
    public void setBRANCH_CODE(BigDecimal BRANCH_CODE) {
        this.BRANCH_CODE = BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PFTAMFTRXPAR_DEPOSIT.CIF_SUB_NO
     *
     * @return the value of PFTAMFTRXPAR_DEPOSIT.CIF_SUB_NO
     */
    public BigDecimal getCIF_SUB_NO() {
        return CIF_SUB_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PFTAMFTRXPAR_DEPOSIT.CIF_SUB_NO
     *
     * @param CIF_SUB_NO the value for PFTAMFTRXPAR_DEPOSIT.CIF_SUB_NO
     */
    public void setCIF_SUB_NO(BigDecimal CIF_SUB_NO) {
        this.CIF_SUB_NO = CIF_SUB_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PFTAMFTRXPAR_DEPOSIT.COMP_CODE
     *
     * @return the value of PFTAMFTRXPAR_DEPOSIT.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PFTAMFTRXPAR_DEPOSIT.COMP_CODE
     *
     * @param COMP_CODE the value for PFTAMFTRXPAR_DEPOSIT.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PFTAMFTRXPAR_DEPOSIT.CURRENCY_CODE
     *
     * @return the value of PFTAMFTRXPAR_DEPOSIT.CURRENCY_CODE
     */
    public BigDecimal getCURRENCY_CODE() {
        return CURRENCY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PFTAMFTRXPAR_DEPOSIT.CURRENCY_CODE
     *
     * @param CURRENCY_CODE the value for PFTAMFTRXPAR_DEPOSIT.CURRENCY_CODE
     */
    public void setCURRENCY_CODE(BigDecimal CURRENCY_CODE) {
        this.CURRENCY_CODE = CURRENCY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PFTAMFTRXPAR_DEPOSIT.FROM_DTE
     *
     * @return the value of PFTAMFTRXPAR_DEPOSIT.FROM_DTE
     */
    public Date getFROM_DTE() {
        return FROM_DTE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PFTAMFTRXPAR_DEPOSIT.FROM_DTE
     *
     * @param FROM_DTE the value for PFTAMFTRXPAR_DEPOSIT.FROM_DTE
     */
    public void setFROM_DTE(Date FROM_DTE) {
        this.FROM_DTE = FROM_DTE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PFTAMFTRXPAR_DEPOSIT.GL_CODE
     *
     * @return the value of PFTAMFTRXPAR_DEPOSIT.GL_CODE
     */
    public BigDecimal getGL_CODE() {
        return GL_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PFTAMFTRXPAR_DEPOSIT.GL_CODE
     *
     * @param GL_CODE the value for PFTAMFTRXPAR_DEPOSIT.GL_CODE
     */
    public void setGL_CODE(BigDecimal GL_CODE) {
        this.GL_CODE = GL_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PFTAMFTRXPAR_DEPOSIT.JV_OP_LINE_NO
     *
     * @return the value of PFTAMFTRXPAR_DEPOSIT.JV_OP_LINE_NO
     */
    public BigDecimal getJV_OP_LINE_NO() {
        return JV_OP_LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PFTAMFTRXPAR_DEPOSIT.JV_OP_LINE_NO
     *
     * @param JV_OP_LINE_NO the value for PFTAMFTRXPAR_DEPOSIT.JV_OP_LINE_NO
     */
    public void setJV_OP_LINE_NO(BigDecimal JV_OP_LINE_NO) {
        this.JV_OP_LINE_NO = JV_OP_LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PFTAMFTRXPAR_DEPOSIT.JV_OP_NO
     *
     * @return the value of PFTAMFTRXPAR_DEPOSIT.JV_OP_NO
     */
    public BigDecimal getJV_OP_NO() {
        return JV_OP_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PFTAMFTRXPAR_DEPOSIT.JV_OP_NO
     *
     * @param JV_OP_NO the value for PFTAMFTRXPAR_DEPOSIT.JV_OP_NO
     */
    public void setJV_OP_NO(BigDecimal JV_OP_NO) {
        this.JV_OP_NO = JV_OP_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PFTAMFTRXPAR_DEPOSIT.JV_TYPE
     *
     * @return the value of PFTAMFTRXPAR_DEPOSIT.JV_TYPE
     */
    public BigDecimal getJV_TYPE() {
        return JV_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PFTAMFTRXPAR_DEPOSIT.JV_TYPE
     *
     * @param JV_TYPE the value for PFTAMFTRXPAR_DEPOSIT.JV_TYPE
     */
    public void setJV_TYPE(BigDecimal JV_TYPE) {
        this.JV_TYPE = JV_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PFTAMFTRXPAR_DEPOSIT.LOG_NUMBER
     *
     * @return the value of PFTAMFTRXPAR_DEPOSIT.LOG_NUMBER
     */
    public BigDecimal getLOG_NUMBER() {
        return LOG_NUMBER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PFTAMFTRXPAR_DEPOSIT.LOG_NUMBER
     *
     * @param LOG_NUMBER the value for PFTAMFTRXPAR_DEPOSIT.LOG_NUMBER
     */
    public void setLOG_NUMBER(BigDecimal LOG_NUMBER) {
        this.LOG_NUMBER = LOG_NUMBER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PFTAMFTRXPAR_DEPOSIT.SL_NO
     *
     * @return the value of PFTAMFTRXPAR_DEPOSIT.SL_NO
     */
    public BigDecimal getSL_NO() {
        return SL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PFTAMFTRXPAR_DEPOSIT.SL_NO
     *
     * @param SL_NO the value for PFTAMFTRXPAR_DEPOSIT.SL_NO
     */
    public void setSL_NO(BigDecimal SL_NO) {
        this.SL_NO = SL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PFTAMFTRXPAR_DEPOSIT.TO_DATE
     *
     * @return the value of PFTAMFTRXPAR_DEPOSIT.TO_DATE
     */
    public Date getTO_DATE() {
        return TO_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PFTAMFTRXPAR_DEPOSIT.TO_DATE
     *
     * @param TO_DATE the value for PFTAMFTRXPAR_DEPOSIT.TO_DATE
     */
    public void setTO_DATE(Date TO_DATE) {
        this.TO_DATE = TO_DATE;
    }
}