package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class PFTLOGDETVO extends PFTLOGDETVOKey {
    /**
     * This field corresponds to the database column PFTLOGDET.PFT_COMP_CODE
     */
    private BigDecimal PFT_COMP_CODE;

    /**
     * This field corresponds to the database column PFTLOGDET.PFT_BRANCH_CODE
     */
    private BigDecimal PFT_BRANCH_CODE;

    /**
     * This field corresponds to the database column PFTLOGDET.PFT_LOG_NUMBER
     */
    private BigDecimal PFT_LOG_NUMBER;

    /**
     * This field corresponds to the database column PFTLOGDET.TRIAL_FINAL
     */
    private String TRIAL_FINAL;

    /**
     * This field corresponds to the database column PFTLOGDET.PROFIT_GROUP
     */
    private BigDecimal PROFIT_GROUP;

    /**
     * This field corresponds to the database column PFTLOGDET.FIRST_WORK_DAY
     */
    private Date FIRST_WORK_DAY;

    /**
     * This field corresponds to the database column PFTLOGDET.FINAL_RUN_SEPARATE_ENTRIES
     */
    private String FINAL_RUN_SEPARATE_ENTRIES;

    /**
     * This field corresponds to the database column PFTLOGDET.FROM_DAY
     */
    private BigDecimal FROM_DAY;

    /**
     * This field corresponds to the database column PFTLOGDET.TO_DAY
     */
    private BigDecimal TO_DAY;

    /**
     * This field corresponds to the database column PFTLOGDET.FROM_MONTH
     */
    private BigDecimal FROM_MONTH;

    /**
     * This field corresponds to the database column PFTLOGDET.TO_MONTH
     */
    private BigDecimal TO_MONTH;

    /**
     * This field corresponds to the database column PFTLOGDET.FROM_YEAR
     */
    private BigDecimal FROM_YEAR;

    /**
     * This field corresponds to the database column PFTLOGDET.TO_YEAR
     */
    private BigDecimal TO_YEAR;

    /**
     * This field corresponds to the database column PFTLOGDET.DIR_IND_PROCESSED
     */
    private String DIR_IND_PROCESSED;

    /**
     * This field corresponds to the database column PFTLOGDET.NO_OF_DAYS
     */
    private BigDecimal NO_OF_DAYS;

    /**
     * This field corresponds to the database column PFTLOGDET.YEARLY_CALCULATION
     */
    private String YEARLY_CALCULATION;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PFTLOGDET.PFT_COMP_CODE
     *
     * @return the value of PFTLOGDET.PFT_COMP_CODE
     */
    public BigDecimal getPFT_COMP_CODE() {
        return PFT_COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PFTLOGDET.PFT_COMP_CODE
     *
     * @param PFT_COMP_CODE the value for PFTLOGDET.PFT_COMP_CODE
     */
    public void setPFT_COMP_CODE(BigDecimal PFT_COMP_CODE) {
        this.PFT_COMP_CODE = PFT_COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PFTLOGDET.PFT_BRANCH_CODE
     *
     * @return the value of PFTLOGDET.PFT_BRANCH_CODE
     */
    public BigDecimal getPFT_BRANCH_CODE() {
        return PFT_BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PFTLOGDET.PFT_BRANCH_CODE
     *
     * @param PFT_BRANCH_CODE the value for PFTLOGDET.PFT_BRANCH_CODE
     */
    public void setPFT_BRANCH_CODE(BigDecimal PFT_BRANCH_CODE) {
        this.PFT_BRANCH_CODE = PFT_BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PFTLOGDET.PFT_LOG_NUMBER
     *
     * @return the value of PFTLOGDET.PFT_LOG_NUMBER
     */
    public BigDecimal getPFT_LOG_NUMBER() {
        return PFT_LOG_NUMBER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PFTLOGDET.PFT_LOG_NUMBER
     *
     * @param PFT_LOG_NUMBER the value for PFTLOGDET.PFT_LOG_NUMBER
     */
    public void setPFT_LOG_NUMBER(BigDecimal PFT_LOG_NUMBER) {
        this.PFT_LOG_NUMBER = PFT_LOG_NUMBER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PFTLOGDET.TRIAL_FINAL
     *
     * @return the value of PFTLOGDET.TRIAL_FINAL
     */
    public String getTRIAL_FINAL() {
        return TRIAL_FINAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PFTLOGDET.TRIAL_FINAL
     *
     * @param TRIAL_FINAL the value for PFTLOGDET.TRIAL_FINAL
     */
    public void setTRIAL_FINAL(String TRIAL_FINAL) {
        this.TRIAL_FINAL = TRIAL_FINAL == null ? null : TRIAL_FINAL.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PFTLOGDET.PROFIT_GROUP
     *
     * @return the value of PFTLOGDET.PROFIT_GROUP
     */
    public BigDecimal getPROFIT_GROUP() {
        return PROFIT_GROUP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PFTLOGDET.PROFIT_GROUP
     *
     * @param PROFIT_GROUP the value for PFTLOGDET.PROFIT_GROUP
     */
    public void setPROFIT_GROUP(BigDecimal PROFIT_GROUP) {
        this.PROFIT_GROUP = PROFIT_GROUP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PFTLOGDET.FIRST_WORK_DAY
     *
     * @return the value of PFTLOGDET.FIRST_WORK_DAY
     */
    public Date getFIRST_WORK_DAY() {
        return FIRST_WORK_DAY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PFTLOGDET.FIRST_WORK_DAY
     *
     * @param FIRST_WORK_DAY the value for PFTLOGDET.FIRST_WORK_DAY
     */
    public void setFIRST_WORK_DAY(Date FIRST_WORK_DAY) {
        this.FIRST_WORK_DAY = FIRST_WORK_DAY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PFTLOGDET.FINAL_RUN_SEPARATE_ENTRIES
     *
     * @return the value of PFTLOGDET.FINAL_RUN_SEPARATE_ENTRIES
     */
    public String getFINAL_RUN_SEPARATE_ENTRIES() {
        return FINAL_RUN_SEPARATE_ENTRIES;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PFTLOGDET.FINAL_RUN_SEPARATE_ENTRIES
     *
     * @param FINAL_RUN_SEPARATE_ENTRIES the value for PFTLOGDET.FINAL_RUN_SEPARATE_ENTRIES
     */
    public void setFINAL_RUN_SEPARATE_ENTRIES(String FINAL_RUN_SEPARATE_ENTRIES) {
        this.FINAL_RUN_SEPARATE_ENTRIES = FINAL_RUN_SEPARATE_ENTRIES == null ? null : FINAL_RUN_SEPARATE_ENTRIES.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PFTLOGDET.FROM_DAY
     *
     * @return the value of PFTLOGDET.FROM_DAY
     */
    public BigDecimal getFROM_DAY() {
        return FROM_DAY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PFTLOGDET.FROM_DAY
     *
     * @param FROM_DAY the value for PFTLOGDET.FROM_DAY
     */
    public void setFROM_DAY(BigDecimal FROM_DAY) {
        this.FROM_DAY = FROM_DAY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PFTLOGDET.TO_DAY
     *
     * @return the value of PFTLOGDET.TO_DAY
     */
    public BigDecimal getTO_DAY() {
        return TO_DAY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PFTLOGDET.TO_DAY
     *
     * @param TO_DAY the value for PFTLOGDET.TO_DAY
     */
    public void setTO_DAY(BigDecimal TO_DAY) {
        this.TO_DAY = TO_DAY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PFTLOGDET.FROM_MONTH
     *
     * @return the value of PFTLOGDET.FROM_MONTH
     */
    public BigDecimal getFROM_MONTH() {
        return FROM_MONTH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PFTLOGDET.FROM_MONTH
     *
     * @param FROM_MONTH the value for PFTLOGDET.FROM_MONTH
     */
    public void setFROM_MONTH(BigDecimal FROM_MONTH) {
        this.FROM_MONTH = FROM_MONTH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PFTLOGDET.TO_MONTH
     *
     * @return the value of PFTLOGDET.TO_MONTH
     */
    public BigDecimal getTO_MONTH() {
        return TO_MONTH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PFTLOGDET.TO_MONTH
     *
     * @param TO_MONTH the value for PFTLOGDET.TO_MONTH
     */
    public void setTO_MONTH(BigDecimal TO_MONTH) {
        this.TO_MONTH = TO_MONTH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PFTLOGDET.FROM_YEAR
     *
     * @return the value of PFTLOGDET.FROM_YEAR
     */
    public BigDecimal getFROM_YEAR() {
        return FROM_YEAR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PFTLOGDET.FROM_YEAR
     *
     * @param FROM_YEAR the value for PFTLOGDET.FROM_YEAR
     */
    public void setFROM_YEAR(BigDecimal FROM_YEAR) {
        this.FROM_YEAR = FROM_YEAR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PFTLOGDET.TO_YEAR
     *
     * @return the value of PFTLOGDET.TO_YEAR
     */
    public BigDecimal getTO_YEAR() {
        return TO_YEAR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PFTLOGDET.TO_YEAR
     *
     * @param TO_YEAR the value for PFTLOGDET.TO_YEAR
     */
    public void setTO_YEAR(BigDecimal TO_YEAR) {
        this.TO_YEAR = TO_YEAR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PFTLOGDET.DIR_IND_PROCESSED
     *
     * @return the value of PFTLOGDET.DIR_IND_PROCESSED
     */
    public String getDIR_IND_PROCESSED() {
        return DIR_IND_PROCESSED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PFTLOGDET.DIR_IND_PROCESSED
     *
     * @param DIR_IND_PROCESSED the value for PFTLOGDET.DIR_IND_PROCESSED
     */
    public void setDIR_IND_PROCESSED(String DIR_IND_PROCESSED) {
        this.DIR_IND_PROCESSED = DIR_IND_PROCESSED == null ? null : DIR_IND_PROCESSED.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PFTLOGDET.NO_OF_DAYS
     *
     * @return the value of PFTLOGDET.NO_OF_DAYS
     */
    public BigDecimal getNO_OF_DAYS() {
        return NO_OF_DAYS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PFTLOGDET.NO_OF_DAYS
     *
     * @param NO_OF_DAYS the value for PFTLOGDET.NO_OF_DAYS
     */
    public void setNO_OF_DAYS(BigDecimal NO_OF_DAYS) {
        this.NO_OF_DAYS = NO_OF_DAYS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PFTLOGDET.YEARLY_CALCULATION
     *
     * @return the value of PFTLOGDET.YEARLY_CALCULATION
     */
    public String getYEARLY_CALCULATION() {
        return YEARLY_CALCULATION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PFTLOGDET.YEARLY_CALCULATION
     *
     * @param YEARLY_CALCULATION the value for PFTLOGDET.YEARLY_CALCULATION
     */
    public void setYEARLY_CALCULATION(String YEARLY_CALCULATION) {
        this.YEARLY_CALCULATION = YEARLY_CALCULATION == null ? null : YEARLY_CALCULATION.trim();
    }
}