package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class PMSTRADE_SETVOKey extends BaseVO {
    /**
     * This field corresponds to the database column PMSTRADE_SET.BILL_TYPE
     */
    private String BILL_TYPE;

    /**
     * This field corresponds to the database column PMSTRADE_SET.BRANCH_CODE
     */
    private BigDecimal BRANCH_CODE;

    /**
     * This field corresponds to the database column PMSTRADE_SET.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column PMSTRADE_SET.SBBA_FLAG
     */
    private String SBBA_FLAG;

    /**
     * This field corresponds to the database column PMSTRADE_SET.SWIFT_LINE_NBR
     */
    private BigDecimal SWIFT_LINE_NBR;

    /**
     * This field corresponds to the database column PMSTRADE_SET.TRADE_LINE_NBR
     */
    private BigDecimal TRADE_LINE_NBR;

    /**
     * This field corresponds to the database column PMSTRADE_SET.TRADE_SERIAL_NBR
     */
    private BigDecimal TRADE_SERIAL_NBR;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PMSTRADE_SET.BILL_TYPE
     *
     * @return the value of PMSTRADE_SET.BILL_TYPE
     */
    public String getBILL_TYPE() {
        return BILL_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PMSTRADE_SET.BILL_TYPE
     *
     * @param BILL_TYPE the value for PMSTRADE_SET.BILL_TYPE
     */
    public void setBILL_TYPE(String BILL_TYPE) {
        this.BILL_TYPE = BILL_TYPE == null ? null : BILL_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PMSTRADE_SET.BRANCH_CODE
     *
     * @return the value of PMSTRADE_SET.BRANCH_CODE
     */
    public BigDecimal getBRANCH_CODE() {
        return BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PMSTRADE_SET.BRANCH_CODE
     *
     * @param BRANCH_CODE the value for PMSTRADE_SET.BRANCH_CODE
     */
    public void setBRANCH_CODE(BigDecimal BRANCH_CODE) {
        this.BRANCH_CODE = BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PMSTRADE_SET.COMP_CODE
     *
     * @return the value of PMSTRADE_SET.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PMSTRADE_SET.COMP_CODE
     *
     * @param COMP_CODE the value for PMSTRADE_SET.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PMSTRADE_SET.SBBA_FLAG
     *
     * @return the value of PMSTRADE_SET.SBBA_FLAG
     */
    public String getSBBA_FLAG() {
        return SBBA_FLAG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PMSTRADE_SET.SBBA_FLAG
     *
     * @param SBBA_FLAG the value for PMSTRADE_SET.SBBA_FLAG
     */
    public void setSBBA_FLAG(String SBBA_FLAG) {
        this.SBBA_FLAG = SBBA_FLAG == null ? null : SBBA_FLAG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PMSTRADE_SET.SWIFT_LINE_NBR
     *
     * @return the value of PMSTRADE_SET.SWIFT_LINE_NBR
     */
    public BigDecimal getSWIFT_LINE_NBR() {
        return SWIFT_LINE_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PMSTRADE_SET.SWIFT_LINE_NBR
     *
     * @param SWIFT_LINE_NBR the value for PMSTRADE_SET.SWIFT_LINE_NBR
     */
    public void setSWIFT_LINE_NBR(BigDecimal SWIFT_LINE_NBR) {
        this.SWIFT_LINE_NBR = SWIFT_LINE_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PMSTRADE_SET.TRADE_LINE_NBR
     *
     * @return the value of PMSTRADE_SET.TRADE_LINE_NBR
     */
    public BigDecimal getTRADE_LINE_NBR() {
        return TRADE_LINE_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PMSTRADE_SET.TRADE_LINE_NBR
     *
     * @param TRADE_LINE_NBR the value for PMSTRADE_SET.TRADE_LINE_NBR
     */
    public void setTRADE_LINE_NBR(BigDecimal TRADE_LINE_NBR) {
        this.TRADE_LINE_NBR = TRADE_LINE_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PMSTRADE_SET.TRADE_SERIAL_NBR
     *
     * @return the value of PMSTRADE_SET.TRADE_SERIAL_NBR
     */
    public BigDecimal getTRADE_SERIAL_NBR() {
        return TRADE_SERIAL_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PMSTRADE_SET.TRADE_SERIAL_NBR
     *
     * @param TRADE_SERIAL_NBR the value for PMSTRADE_SET.TRADE_SERIAL_NBR
     */
    public void setTRADE_SERIAL_NBR(BigDecimal TRADE_SERIAL_NBR) {
        this.TRADE_SERIAL_NBR = TRADE_SERIAL_NBR;
    }
}