package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class PMSTYPE_TEMPLATE_DETVOKey extends BaseVO {
    /**
     * This field corresponds to the database column PMSTYPE_TEMPLATE_DET.BRANCH_CODE
     */
    private BigDecimal BRANCH_CODE;

    /**
     * This field corresponds to the database column PMSTYPE_TEMPLATE_DET.CIF
     */
    private BigDecimal CIF;

    /**
     * This field corresponds to the database column PMSTYPE_TEMPLATE_DET.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column PMSTYPE_TEMPLATE_DET.SEC_TYPE
     */
    private BigDecimal SEC_TYPE;

    /**
     * This field corresponds to the database column PMSTYPE_TEMPLATE_DET.SEQ
     */
    private BigDecimal SEQ;

    /**
     * This field corresponds to the database column PMSTYPE_TEMPLATE_DET.TRX_TYPE
     */
    private BigDecimal TRX_TYPE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PMSTYPE_TEMPLATE_DET.BRANCH_CODE
     *
     * @return the value of PMSTYPE_TEMPLATE_DET.BRANCH_CODE
     */
    public BigDecimal getBRANCH_CODE() {
        return BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PMSTYPE_TEMPLATE_DET.BRANCH_CODE
     *
     * @param BRANCH_CODE the value for PMSTYPE_TEMPLATE_DET.BRANCH_CODE
     */
    public void setBRANCH_CODE(BigDecimal BRANCH_CODE) {
        this.BRANCH_CODE = BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PMSTYPE_TEMPLATE_DET.CIF
     *
     * @return the value of PMSTYPE_TEMPLATE_DET.CIF
     */
    public BigDecimal getCIF() {
        return CIF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PMSTYPE_TEMPLATE_DET.CIF
     *
     * @param CIF the value for PMSTYPE_TEMPLATE_DET.CIF
     */
    public void setCIF(BigDecimal CIF) {
        this.CIF = CIF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PMSTYPE_TEMPLATE_DET.COMP_CODE
     *
     * @return the value of PMSTYPE_TEMPLATE_DET.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PMSTYPE_TEMPLATE_DET.COMP_CODE
     *
     * @param COMP_CODE the value for PMSTYPE_TEMPLATE_DET.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PMSTYPE_TEMPLATE_DET.SEC_TYPE
     *
     * @return the value of PMSTYPE_TEMPLATE_DET.SEC_TYPE
     */
    public BigDecimal getSEC_TYPE() {
        return SEC_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PMSTYPE_TEMPLATE_DET.SEC_TYPE
     *
     * @param SEC_TYPE the value for PMSTYPE_TEMPLATE_DET.SEC_TYPE
     */
    public void setSEC_TYPE(BigDecimal SEC_TYPE) {
        this.SEC_TYPE = SEC_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PMSTYPE_TEMPLATE_DET.SEQ
     *
     * @return the value of PMSTYPE_TEMPLATE_DET.SEQ
     */
    public BigDecimal getSEQ() {
        return SEQ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PMSTYPE_TEMPLATE_DET.SEQ
     *
     * @param SEQ the value for PMSTYPE_TEMPLATE_DET.SEQ
     */
    public void setSEQ(BigDecimal SEQ) {
        this.SEQ = SEQ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PMSTYPE_TEMPLATE_DET.TRX_TYPE
     *
     * @return the value of PMSTYPE_TEMPLATE_DET.TRX_TYPE
     */
    public BigDecimal getTRX_TYPE() {
        return TRX_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PMSTYPE_TEMPLATE_DET.TRX_TYPE
     *
     * @param TRX_TYPE the value for PMSTYPE_TEMPLATE_DET.TRX_TYPE
     */
    public void setTRX_TYPE(BigDecimal TRX_TYPE) {
        this.TRX_TYPE = TRX_TYPE;
    }
}