package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class PMSTYPE_TEMPLATEVO extends PMSTYPE_TEMPLATEVOKey {
    /**
     * This field corresponds to the database column PMSTYPE_TEMPLATE.TRX_TEMPLATE
     */
    private BigDecimal TRX_TEMPLATE;

    /**
     * This field corresponds to the database column PMSTYPE_TEMPLATE.FISCAL_IMP
     */
    private BigDecimal FISCAL_IMP;

    /**
     * This field corresponds to the database column PMSTYPE_TEMPLATE.SHOW_TEMPLATE
     */
    private String SHOW_TEMPLATE;

    /**
     * This field corresponds to the database column PMSTYPE_TEMPLATE.ALLOW_CHANGE
     */
    private String ALLOW_CHANGE;

    /**
     * This field corresponds to the database column PMSTYPE_TEMPLATE.TRX_TEMPLATE_PROC
     */
    private BigDecimal TRX_TEMPLATE_PROC;

    /**
     * This field corresponds to the database column PMSTYPE_TEMPLATE.DATE_UPDATED
     */
    private Date DATE_UPDATED;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PMSTYPE_TEMPLATE.TRX_TEMPLATE
     *
     * @return the value of PMSTYPE_TEMPLATE.TRX_TEMPLATE
     */
    public BigDecimal getTRX_TEMPLATE() {
        return TRX_TEMPLATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PMSTYPE_TEMPLATE.TRX_TEMPLATE
     *
     * @param TRX_TEMPLATE the value for PMSTYPE_TEMPLATE.TRX_TEMPLATE
     */
    public void setTRX_TEMPLATE(BigDecimal TRX_TEMPLATE) {
        this.TRX_TEMPLATE = TRX_TEMPLATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PMSTYPE_TEMPLATE.FISCAL_IMP
     *
     * @return the value of PMSTYPE_TEMPLATE.FISCAL_IMP
     */
    public BigDecimal getFISCAL_IMP() {
        return FISCAL_IMP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PMSTYPE_TEMPLATE.FISCAL_IMP
     *
     * @param FISCAL_IMP the value for PMSTYPE_TEMPLATE.FISCAL_IMP
     */
    public void setFISCAL_IMP(BigDecimal FISCAL_IMP) {
        this.FISCAL_IMP = FISCAL_IMP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PMSTYPE_TEMPLATE.SHOW_TEMPLATE
     *
     * @return the value of PMSTYPE_TEMPLATE.SHOW_TEMPLATE
     */
    public String getSHOW_TEMPLATE() {
        return SHOW_TEMPLATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PMSTYPE_TEMPLATE.SHOW_TEMPLATE
     *
     * @param SHOW_TEMPLATE the value for PMSTYPE_TEMPLATE.SHOW_TEMPLATE
     */
    public void setSHOW_TEMPLATE(String SHOW_TEMPLATE) {
        this.SHOW_TEMPLATE = SHOW_TEMPLATE == null ? null : SHOW_TEMPLATE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PMSTYPE_TEMPLATE.ALLOW_CHANGE
     *
     * @return the value of PMSTYPE_TEMPLATE.ALLOW_CHANGE
     */
    public String getALLOW_CHANGE() {
        return ALLOW_CHANGE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PMSTYPE_TEMPLATE.ALLOW_CHANGE
     *
     * @param ALLOW_CHANGE the value for PMSTYPE_TEMPLATE.ALLOW_CHANGE
     */
    public void setALLOW_CHANGE(String ALLOW_CHANGE) {
        this.ALLOW_CHANGE = ALLOW_CHANGE == null ? null : ALLOW_CHANGE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PMSTYPE_TEMPLATE.TRX_TEMPLATE_PROC
     *
     * @return the value of PMSTYPE_TEMPLATE.TRX_TEMPLATE_PROC
     */
    public BigDecimal getTRX_TEMPLATE_PROC() {
        return TRX_TEMPLATE_PROC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PMSTYPE_TEMPLATE.TRX_TEMPLATE_PROC
     *
     * @param TRX_TEMPLATE_PROC the value for PMSTYPE_TEMPLATE.TRX_TEMPLATE_PROC
     */
    public void setTRX_TEMPLATE_PROC(BigDecimal TRX_TEMPLATE_PROC) {
        this.TRX_TEMPLATE_PROC = TRX_TEMPLATE_PROC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PMSTYPE_TEMPLATE.DATE_UPDATED
     *
     * @return the value of PMSTYPE_TEMPLATE.DATE_UPDATED
     */
    public Date getDATE_UPDATED() {
        return DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PMSTYPE_TEMPLATE.DATE_UPDATED
     *
     * @param DATE_UPDATED the value for PMSTYPE_TEMPLATE.DATE_UPDATED
     */
    public void setDATE_UPDATED(Date DATE_UPDATED) {
        this.DATE_UPDATED = DATE_UPDATED;
    }
}