package com.path.dbmaps.vo;

public class PMSTRADE_CONTROLVO extends PMSTRADE_CONTROLVOKey {
    /**
     * This field corresponds to the database column PMSTRADE_CONTROL.TRADING_CONTROL
     */
    private String TRADING_CONTROL;

    /**
     * This field corresponds to the database column PMSTRADE_CONTROL.ALLOW_PROCEED
     */
    private String ALLOW_PROCEED;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PMSTRADE_CONTROL.TRADING_CONTROL
     *
     * @return the value of PMSTRADE_CONTROL.TRADING_CONTROL
     */
    public String getTRADING_CONTROL() {
        return TRADING_CONTROL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PMSTRADE_CONTROL.TRADING_CONTROL
     *
     * @param TRADING_CONTROL the value for PMSTRADE_CONTROL.TRADING_CONTROL
     */
    public void setTRADING_CONTROL(String TRADING_CONTROL) {
        this.TRADING_CONTROL = TRADING_CONTROL == null ? null : TRADING_CONTROL.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PMSTRADE_CONTROL.ALLOW_PROCEED
     *
     * @return the value of PMSTRADE_CONTROL.ALLOW_PROCEED
     */
    public String getALLOW_PROCEED() {
        return ALLOW_PROCEED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PMSTRADE_CONTROL.ALLOW_PROCEED
     *
     * @param ALLOW_PROCEED the value for PMSTRADE_CONTROL.ALLOW_PROCEED
     */
    public void setALLOW_PROCEED(String ALLOW_PROCEED) {
        this.ALLOW_PROCEED = ALLOW_PROCEED == null ? null : ALLOW_PROCEED.trim();
    }
}