package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class POSTAL_CODEVOKey extends BaseVO {
    /**
     * This field corresponds to the database column POSTAL_CODE.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column POSTAL_CODE.POST_CODE
     */
    private String POST_CODE;

    /**
     * This field corresponds to the database column POSTAL_CODE.REGION_CODE
     */
    private BigDecimal REGION_CODE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSTAL_CODE.COMP_CODE
     *
     * @return the value of POSTAL_CODE.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSTAL_CODE.COMP_CODE
     *
     * @param COMP_CODE the value for POSTAL_CODE.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSTAL_CODE.POST_CODE
     *
     * @return the value of POSTAL_CODE.POST_CODE
     */
    public String getPOST_CODE() {
        return POST_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSTAL_CODE.POST_CODE
     *
     * @param POST_CODE the value for POSTAL_CODE.POST_CODE
     */
    public void setPOST_CODE(String POST_CODE) {
        this.POST_CODE = POST_CODE == null ? null : POST_CODE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column POSTAL_CODE.REGION_CODE
     *
     * @return the value of POSTAL_CODE.REGION_CODE
     */
    public BigDecimal getREGION_CODE() {
        return REGION_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column POSTAL_CODE.REGION_CODE
     *
     * @param REGION_CODE the value for POSTAL_CODE.REGION_CODE
     */
    public void setREGION_CODE(BigDecimal REGION_CODE) {
        this.REGION_CODE = REGION_CODE;
    }
}