package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class PWS_OPERATION_FIELDSVO extends BaseVO {
    /**
     * This field corresponds to the database column PWS_OPERATION_FIELDS.FIELD_ID
     */
    private BigDecimal FIELD_ID;

    /**
     * This field corresponds to the database column PWS_OPERATION_FIELDS.OPERATION_ID
     */
    private BigDecimal OPERATION_ID;

    /**
     * This field corresponds to the database column PWS_OPERATION_FIELDS.PARAMETER_NAME
     */
    private String PARAMETER_NAME;

    /**
     * This field corresponds to the database column PWS_OPERATION_FIELDS.DESCRIPTION
     */
    private String DESCRIPTION;

    /**
     * This field corresponds to the database column PWS_OPERATION_FIELDS.TYPE
     */
    private String TYPE;

    /**
     * This field corresponds to the database column PWS_OPERATION_FIELDS.MANDATORY
     */
    private String MANDATORY;

    /**
     * This field corresponds to the database column PWS_OPERATION_FIELDS.IN_OUT
     */
    private String IN_OUT;

    /**
     * This field corresponds to the database column PWS_OPERATION_FIELDS.DEFAULT_VALUE
     */
    private String DEFAULT_VALUE;

    /**
     * This field corresponds to the database column PWS_OPERATION_FIELDS.MAPPING_FIELD
     */
    private String MAPPING_FIELD;

    /**
     * This field corresponds to the database column PWS_OPERATION_FIELDS.NILLABLE
     */
    private String NILLABLE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PWS_OPERATION_FIELDS.FIELD_ID
     *
     * @return the value of PWS_OPERATION_FIELDS.FIELD_ID
     */
    public BigDecimal getFIELD_ID() {
        return FIELD_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PWS_OPERATION_FIELDS.FIELD_ID
     *
     * @param FIELD_ID the value for PWS_OPERATION_FIELDS.FIELD_ID
     */
    public void setFIELD_ID(BigDecimal FIELD_ID) {
        this.FIELD_ID = FIELD_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PWS_OPERATION_FIELDS.OPERATION_ID
     *
     * @return the value of PWS_OPERATION_FIELDS.OPERATION_ID
     */
    public BigDecimal getOPERATION_ID() {
        return OPERATION_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PWS_OPERATION_FIELDS.OPERATION_ID
     *
     * @param OPERATION_ID the value for PWS_OPERATION_FIELDS.OPERATION_ID
     */
    public void setOPERATION_ID(BigDecimal OPERATION_ID) {
        this.OPERATION_ID = OPERATION_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PWS_OPERATION_FIELDS.PARAMETER_NAME
     *
     * @return the value of PWS_OPERATION_FIELDS.PARAMETER_NAME
     */
    public String getPARAMETER_NAME() {
        return PARAMETER_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PWS_OPERATION_FIELDS.PARAMETER_NAME
     *
     * @param PARAMETER_NAME the value for PWS_OPERATION_FIELDS.PARAMETER_NAME
     */
    public void setPARAMETER_NAME(String PARAMETER_NAME) {
        this.PARAMETER_NAME = PARAMETER_NAME == null ? null : PARAMETER_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PWS_OPERATION_FIELDS.DESCRIPTION
     *
     * @return the value of PWS_OPERATION_FIELDS.DESCRIPTION
     */
    public String getDESCRIPTION() {
        return DESCRIPTION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PWS_OPERATION_FIELDS.DESCRIPTION
     *
     * @param DESCRIPTION the value for PWS_OPERATION_FIELDS.DESCRIPTION
     */
    public void setDESCRIPTION(String DESCRIPTION) {
        this.DESCRIPTION = DESCRIPTION == null ? null : DESCRIPTION.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PWS_OPERATION_FIELDS.TYPE
     *
     * @return the value of PWS_OPERATION_FIELDS.TYPE
     */
    public String getTYPE() {
        return TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PWS_OPERATION_FIELDS.TYPE
     *
     * @param TYPE the value for PWS_OPERATION_FIELDS.TYPE
     */
    public void setTYPE(String TYPE) {
        this.TYPE = TYPE == null ? null : TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PWS_OPERATION_FIELDS.MANDATORY
     *
     * @return the value of PWS_OPERATION_FIELDS.MANDATORY
     */
    public String getMANDATORY() {
        return MANDATORY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PWS_OPERATION_FIELDS.MANDATORY
     *
     * @param MANDATORY the value for PWS_OPERATION_FIELDS.MANDATORY
     */
    public void setMANDATORY(String MANDATORY) {
        this.MANDATORY = MANDATORY == null ? null : MANDATORY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PWS_OPERATION_FIELDS.IN_OUT
     *
     * @return the value of PWS_OPERATION_FIELDS.IN_OUT
     */
    public String getIN_OUT() {
        return IN_OUT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PWS_OPERATION_FIELDS.IN_OUT
     *
     * @param IN_OUT the value for PWS_OPERATION_FIELDS.IN_OUT
     */
    public void setIN_OUT(String IN_OUT) {
        this.IN_OUT = IN_OUT == null ? null : IN_OUT.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PWS_OPERATION_FIELDS.DEFAULT_VALUE
     *
     * @return the value of PWS_OPERATION_FIELDS.DEFAULT_VALUE
     */
    public String getDEFAULT_VALUE() {
        return DEFAULT_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PWS_OPERATION_FIELDS.DEFAULT_VALUE
     *
     * @param DEFAULT_VALUE the value for PWS_OPERATION_FIELDS.DEFAULT_VALUE
     */
    public void setDEFAULT_VALUE(String DEFAULT_VALUE) {
        this.DEFAULT_VALUE = DEFAULT_VALUE == null ? null : DEFAULT_VALUE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PWS_OPERATION_FIELDS.MAPPING_FIELD
     *
     * @return the value of PWS_OPERATION_FIELDS.MAPPING_FIELD
     */
    public String getMAPPING_FIELD() {
        return MAPPING_FIELD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PWS_OPERATION_FIELDS.MAPPING_FIELD
     *
     * @param MAPPING_FIELD the value for PWS_OPERATION_FIELDS.MAPPING_FIELD
     */
    public void setMAPPING_FIELD(String MAPPING_FIELD) {
        this.MAPPING_FIELD = MAPPING_FIELD == null ? null : MAPPING_FIELD.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PWS_OPERATION_FIELDS.NILLABLE
     *
     * @return the value of PWS_OPERATION_FIELDS.NILLABLE
     */
    public String getNILLABLE() {
        return NILLABLE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PWS_OPERATION_FIELDS.NILLABLE
     *
     * @param NILLABLE the value for PWS_OPERATION_FIELDS.NILLABLE
     */
    public void setNILLABLE(String NILLABLE) {
        this.NILLABLE = NILLABLE == null ? null : NILLABLE.trim();
    }
}