package com.path.dbmaps.vo;

public class RIFCTT_ALLOWED_ID_TYPEVO extends RIFCTT_ALLOWED_ID_TYPEVOKey {
    /**
     * This field corresponds to the database column RIFCTT_ALLOWED_ID_TYPE.ID_TYPE_MAND_YN
     */
    private String ID_TYPE_MAND_YN;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RIFCTT_ALLOWED_ID_TYPE.ID_TYPE_MAND_YN
     *
     * @return the value of RIFCTT_ALLOWED_ID_TYPE.ID_TYPE_MAND_YN
     */
    public String getID_TYPE_MAND_YN() {
        return ID_TYPE_MAND_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RIFCTT_ALLOWED_ID_TYPE.ID_TYPE_MAND_YN
     *
     * @param ID_TYPE_MAND_YN the value for RIFCTT_ALLOWED_ID_TYPE.ID_TYPE_MAND_YN
     */
    public void setID_TYPE_MAND_YN(String ID_TYPE_MAND_YN) {
        this.ID_TYPE_MAND_YN = ID_TYPE_MAND_YN == null ? null : ID_TYPE_MAND_YN.trim();
    }
}