package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class RIFCTT_GLVOKey extends BaseVO {
    /**
     * This field corresponds to the database column RIFCTT_GL.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column RIFCTT_GL.LINE_NBR
     */
    private BigDecimal LINE_NBR;

    /**
     * This field corresponds to the database column RIFCTT_GL.TYPE_CODE
     */
    private BigDecimal TYPE_CODE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RIFCTT_GL.COMP_CODE
     *
     * @return the value of RIFCTT_GL.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RIFCTT_GL.COMP_CODE
     *
     * @param COMP_CODE the value for RIFCTT_GL.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RIFCTT_GL.LINE_NBR
     *
     * @return the value of RIFCTT_GL.LINE_NBR
     */
    public BigDecimal getLINE_NBR() {
        return LINE_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RIFCTT_GL.LINE_NBR
     *
     * @param LINE_NBR the value for RIFCTT_GL.LINE_NBR
     */
    public void setLINE_NBR(BigDecimal LINE_NBR) {
        this.LINE_NBR = LINE_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RIFCTT_GL.TYPE_CODE
     *
     * @return the value of RIFCTT_GL.TYPE_CODE
     */
    public BigDecimal getTYPE_CODE() {
        return TYPE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RIFCTT_GL.TYPE_CODE
     *
     * @param TYPE_CODE the value for RIFCTT_GL.TYPE_CODE
     */
    public void setTYPE_CODE(BigDecimal TYPE_CODE) {
        this.TYPE_CODE = TYPE_CODE;
    }
}