package com.path.dbmaps.vo;

public class RIFMESSAGEVO extends RIFMESSAGEVOKey {
    /**
     * This field corresponds to the database column RIFMESSAGE.INCLUDE_INSTR
     */
    private String INCLUDE_INSTR;

    /**
     * This field corresponds to the database column RIFMESSAGE.MSG_ENG
     */
    private String MSG_ENG;

    /**
     * This field corresponds to the database column RIFMESSAGE.MSG_ARAB
     */
    private String MSG_ARAB;

    /**
     * This field corresponds to the database column RIFMESSAGE.MSG_ENG1
     */
    private String MSG_ENG1;

    /**
     * This field corresponds to the database column RIFMESSAGE.MSG_ARAB1
     */
    private String MSG_ARAB1;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RIFMESSAGE.INCLUDE_INSTR
     *
     * @return the value of RIFMESSAGE.INCLUDE_INSTR
     */
    public String getINCLUDE_INSTR() {
        return INCLUDE_INSTR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RIFMESSAGE.INCLUDE_INSTR
     *
     * @param INCLUDE_INSTR the value for RIFMESSAGE.INCLUDE_INSTR
     */
    public void setINCLUDE_INSTR(String INCLUDE_INSTR) {
        this.INCLUDE_INSTR = INCLUDE_INSTR == null ? null : INCLUDE_INSTR.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RIFMESSAGE.MSG_ENG
     *
     * @return the value of RIFMESSAGE.MSG_ENG
     */
    public String getMSG_ENG() {
        return MSG_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RIFMESSAGE.MSG_ENG
     *
     * @param MSG_ENG the value for RIFMESSAGE.MSG_ENG
     */
    public void setMSG_ENG(String MSG_ENG) {
        this.MSG_ENG = MSG_ENG == null ? null : MSG_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RIFMESSAGE.MSG_ARAB
     *
     * @return the value of RIFMESSAGE.MSG_ARAB
     */
    public String getMSG_ARAB() {
        return MSG_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RIFMESSAGE.MSG_ARAB
     *
     * @param MSG_ARAB the value for RIFMESSAGE.MSG_ARAB
     */
    public void setMSG_ARAB(String MSG_ARAB) {
        this.MSG_ARAB = MSG_ARAB == null ? null : MSG_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RIFMESSAGE.MSG_ENG1
     *
     * @return the value of RIFMESSAGE.MSG_ENG1
     */
    public String getMSG_ENG1() {
        return MSG_ENG1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RIFMESSAGE.MSG_ENG1
     *
     * @param MSG_ENG1 the value for RIFMESSAGE.MSG_ENG1
     */
    public void setMSG_ENG1(String MSG_ENG1) {
        this.MSG_ENG1 = MSG_ENG1 == null ? null : MSG_ENG1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RIFMESSAGE.MSG_ARAB1
     *
     * @return the value of RIFMESSAGE.MSG_ARAB1
     */
    public String getMSG_ARAB1() {
        return MSG_ARAB1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RIFMESSAGE.MSG_ARAB1
     *
     * @param MSG_ARAB1 the value for RIFMESSAGE.MSG_ARAB1
     */
    public void setMSG_ARAB1(String MSG_ARAB1) {
        this.MSG_ARAB1 = MSG_ARAB1 == null ? null : MSG_ARAB1.trim();
    }
}