package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class RIFOBTVO extends RIFOBTVOKey {
    /**
     * This field corresponds to the database column RIFOBT.BRIEF_DESC_ENG
     */
    private String BRIEF_DESC_ENG;

    /**
     * This field corresponds to the database column RIFOBT.LONG_DESC_ENG
     */
    private String LONG_DESC_ENG;

    /**
     * This field corresponds to the database column RIFOBT.BRIEF_DESC_ARAB
     */
    private String BRIEF_DESC_ARAB;

    /**
     * This field corresponds to the database column RIFOBT.LONG_DESC_ARAB
     */
    private String LONG_DESC_ARAB;

    /**
     * This field corresponds to the database column RIFOBT.LIMIT
     */
    private BigDecimal LIMIT;

    /**
     * This field corresponds to the database column RIFOBT.ADDITIONAL_REFERENCE
     */
    private String ADDITIONAL_REFERENCE;

    /**
     * This field corresponds to the database column RIFOBT.ML_GROSS_AMOUNT
     */
    private BigDecimal ML_GROSS_AMOUNT;

    /**
     * This field corresponds to the database column RIFOBT.CREDIT_RATING
     */
    private BigDecimal CREDIT_RATING;

    /**
     * This field corresponds to the database column RIFOBT.PROFILE
     */
    private BigDecimal PROFILE;

    /**
     * This field corresponds to the database column RIFOBT.COMENT
     */
    private String COMENT;
    
    /**
     * This field corresponds to the database column RIFOBT.ALLOW_TO_EXCEED_ONE_OBLIGOR_YN
     */
    private String ALLOW_TO_EXCEED_ONE_OBLIGOR_YN;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RIFOBT.BRIEF_DESC_ENG
     *
     * @return the value of RIFOBT.BRIEF_DESC_ENG
     */
    public String getBRIEF_DESC_ENG() {
        return BRIEF_DESC_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RIFOBT.BRIEF_DESC_ENG
     *
     * @param BRIEF_DESC_ENG the value for RIFOBT.BRIEF_DESC_ENG
     */
    public void setBRIEF_DESC_ENG(String BRIEF_DESC_ENG) {
        this.BRIEF_DESC_ENG = BRIEF_DESC_ENG == null ? null : BRIEF_DESC_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RIFOBT.LONG_DESC_ENG
     *
     * @return the value of RIFOBT.LONG_DESC_ENG
     */
    public String getLONG_DESC_ENG() {
        return LONG_DESC_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RIFOBT.LONG_DESC_ENG
     *
     * @param LONG_DESC_ENG the value for RIFOBT.LONG_DESC_ENG
     */
    public void setLONG_DESC_ENG(String LONG_DESC_ENG) {
        this.LONG_DESC_ENG = LONG_DESC_ENG == null ? null : LONG_DESC_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RIFOBT.BRIEF_DESC_ARAB
     *
     * @return the value of RIFOBT.BRIEF_DESC_ARAB
     */
    public String getBRIEF_DESC_ARAB() {
        return BRIEF_DESC_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RIFOBT.BRIEF_DESC_ARAB
     *
     * @param BRIEF_DESC_ARAB the value for RIFOBT.BRIEF_DESC_ARAB
     */
    public void setBRIEF_DESC_ARAB(String BRIEF_DESC_ARAB) {
        this.BRIEF_DESC_ARAB = BRIEF_DESC_ARAB == null ? null : BRIEF_DESC_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RIFOBT.LONG_DESC_ARAB
     *
     * @return the value of RIFOBT.LONG_DESC_ARAB
     */
    public String getLONG_DESC_ARAB() {
        return LONG_DESC_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RIFOBT.LONG_DESC_ARAB
     *
     * @param LONG_DESC_ARAB the value for RIFOBT.LONG_DESC_ARAB
     */
    public void setLONG_DESC_ARAB(String LONG_DESC_ARAB) {
        this.LONG_DESC_ARAB = LONG_DESC_ARAB == null ? null : LONG_DESC_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RIFOBT.LIMIT
     *
     * @return the value of RIFOBT.LIMIT
     */
    public BigDecimal getLIMIT() {
        return LIMIT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RIFOBT.LIMIT
     *
     * @param LIMIT the value for RIFOBT.LIMIT
     */
    public void setLIMIT(BigDecimal LIMIT) {
        this.LIMIT = LIMIT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RIFOBT.ADDITIONAL_REFERENCE
     *
     * @return the value of RIFOBT.ADDITIONAL_REFERENCE
     */
    public String getADDITIONAL_REFERENCE() {
        return ADDITIONAL_REFERENCE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RIFOBT.ADDITIONAL_REFERENCE
     *
     * @param ADDITIONAL_REFERENCE the value for RIFOBT.ADDITIONAL_REFERENCE
     */
    public void setADDITIONAL_REFERENCE(String ADDITIONAL_REFERENCE) {
        this.ADDITIONAL_REFERENCE = ADDITIONAL_REFERENCE == null ? null : ADDITIONAL_REFERENCE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RIFOBT.ML_GROSS_AMOUNT
     *
     * @return the value of RIFOBT.ML_GROSS_AMOUNT
     */
    public BigDecimal getML_GROSS_AMOUNT() {
        return ML_GROSS_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RIFOBT.ML_GROSS_AMOUNT
     *
     * @param ML_GROSS_AMOUNT the value for RIFOBT.ML_GROSS_AMOUNT
     */
    public void setML_GROSS_AMOUNT(BigDecimal ML_GROSS_AMOUNT) {
        this.ML_GROSS_AMOUNT = ML_GROSS_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RIFOBT.CREDIT_RATING
     *
     * @return the value of RIFOBT.CREDIT_RATING
     */
    public BigDecimal getCREDIT_RATING() {
        return CREDIT_RATING;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RIFOBT.CREDIT_RATING
     *
     * @param CREDIT_RATING the value for RIFOBT.CREDIT_RATING
     */
    public void setCREDIT_RATING(BigDecimal CREDIT_RATING) {
        this.CREDIT_RATING = CREDIT_RATING;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RIFOBT.PROFILE
     *
     * @return the value of RIFOBT.PROFILE
     */
    public BigDecimal getPROFILE() {
        return PROFILE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RIFOBT.PROFILE
     *
     * @param PROFILE the value for RIFOBT.PROFILE
     */
    public void setPROFILE(BigDecimal PROFILE) {
        this.PROFILE = PROFILE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RIFOBT.COMENT
     *
     * @return the value of RIFOBT.COMENT
     */
    public String getCOMENT() {
        return COMENT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RIFOBT.COMENT
     *
     * @param COMENT the value for RIFOBT.COMENT
     */
    public void setCOMENT(String COMENT) {
        this.COMENT = COMENT == null ? null : COMENT.trim();
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RIFOBT.ALLOW_TO_EXCEED_ONE_OBLIGOR_YN
     *
     * @return the value of RIFOBT.ALLOW_TO_EXCEED_ONE_OBLIGOR_YN
     */
    public String getALLOW_TO_EXCEED_ONE_OBLIGOR_YN() {
        return ALLOW_TO_EXCEED_ONE_OBLIGOR_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RIFOBT.ALLOW_TO_EXCEED_ONE_OBLIGOR_YN
     *
     * @param ALLOW_TO_EXCEED_ONE_OBLIGOR_YN the value for RIFOBT.ALLOW_TO_EXCEED_ONE_OBLIGOR_YN
     */
    public void setALLOW_TO_EXCEED_ONE_OBLIGOR_YN(String ALLOW_TO_EXCEED_ONE_OBLIGOR_YN) {
        this.ALLOW_TO_EXCEED_ONE_OBLIGOR_YN = ALLOW_TO_EXCEED_ONE_OBLIGOR_YN == null ? null : ALLOW_TO_EXCEED_ONE_OBLIGOR_YN.trim();
    }
}