package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class RIFPTTRXMAINVO extends RIFPTTRXMAINVOKey {
    /**
     * This field corresponds to the database column RIFPTTRXMAIN.TRX_TYPE
     */
    private String TRX_TYPE;

    /**
     * This field corresponds to the database column RIFPTTRXMAIN.TRX_DATE
     */
    private Date TRX_DATE;

    /**
     * This field corresponds to the database column RIFPTTRXMAIN.REFERENCE
     */
    private String REFERENCE;

    /**
     * This field corresponds to the database column RIFPTTRXMAIN.COMMENTS
     */
    private String COMMENTS;

    /**
     * This field corresponds to the database column RIFPTTRXMAIN.POINTS
     */
    private BigDecimal POINTS;

    /**
     * This field corresponds to the database column RIFPTTRXMAIN.ORIGIN
     */
    private String ORIGIN;

    /**
     * This field corresponds to the database column RIFPTTRXMAIN.CREATED_BY
     */
    private String CREATED_BY;

    /**
     * This field corresponds to the database column RIFPTTRXMAIN.DATE_CREATED
     */
    private Date DATE_CREATED;

    /**
     * This field corresponds to the database column RIFPTTRXMAIN.DELETED_BY
     */
    private String DELETED_BY;

    /**
     * This field corresponds to the database column RIFPTTRXMAIN.DATE_DELETED
     */
    private Date DATE_DELETED;

    /**
     * This field corresponds to the database column RIFPTTRXMAIN.SPECIFIC_GLOBAL
     */
    private String SPECIFIC_GLOBAL;

    /**
     * This field corresponds to the database column RIFPTTRXMAIN.CURRENCY_CODE
     */
    private BigDecimal CURRENCY_CODE;

    /**
     * This field corresponds to the database column RIFPTTRXMAIN.GL_CODE
     */
    private BigDecimal GL_CODE;

    /**
     * This field corresponds to the database column RIFPTTRXMAIN.CIF_SUB_NO
     */
    private BigDecimal CIF_SUB_NO;

    /**
     * This field corresponds to the database column RIFPTTRXMAIN.SL_NO
     */
    private BigDecimal SL_NO;

    /**
     * This field corresponds to the database column RIFPTTRXMAIN.STATUS
     */
    private String STATUS;

    /**
     * This field corresponds to the database column RIFPTTRXMAIN.DEAL_NO
     */
    private BigDecimal DEAL_NO;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RIFPTTRXMAIN.TRX_TYPE
     *
     * @return the value of RIFPTTRXMAIN.TRX_TYPE
     */
    public String getTRX_TYPE() {
        return TRX_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RIFPTTRXMAIN.TRX_TYPE
     *
     * @param TRX_TYPE the value for RIFPTTRXMAIN.TRX_TYPE
     */
    public void setTRX_TYPE(String TRX_TYPE) {
        this.TRX_TYPE = TRX_TYPE == null ? null : TRX_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RIFPTTRXMAIN.TRX_DATE
     *
     * @return the value of RIFPTTRXMAIN.TRX_DATE
     */
    public Date getTRX_DATE() {
        return TRX_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RIFPTTRXMAIN.TRX_DATE
     *
     * @param TRX_DATE the value for RIFPTTRXMAIN.TRX_DATE
     */
    public void setTRX_DATE(Date TRX_DATE) {
        this.TRX_DATE = TRX_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RIFPTTRXMAIN.REFERENCE
     *
     * @return the value of RIFPTTRXMAIN.REFERENCE
     */
    public String getREFERENCE() {
        return REFERENCE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RIFPTTRXMAIN.REFERENCE
     *
     * @param REFERENCE the value for RIFPTTRXMAIN.REFERENCE
     */
    public void setREFERENCE(String REFERENCE) {
        this.REFERENCE = REFERENCE == null ? null : REFERENCE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RIFPTTRXMAIN.COMMENTS
     *
     * @return the value of RIFPTTRXMAIN.COMMENTS
     */
    public String getCOMMENTS() {
        return COMMENTS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RIFPTTRXMAIN.COMMENTS
     *
     * @param COMMENTS the value for RIFPTTRXMAIN.COMMENTS
     */
    public void setCOMMENTS(String COMMENTS) {
        this.COMMENTS = COMMENTS == null ? null : COMMENTS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RIFPTTRXMAIN.POINTS
     *
     * @return the value of RIFPTTRXMAIN.POINTS
     */
    public BigDecimal getPOINTS() {
        return POINTS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RIFPTTRXMAIN.POINTS
     *
     * @param POINTS the value for RIFPTTRXMAIN.POINTS
     */
    public void setPOINTS(BigDecimal POINTS) {
        this.POINTS = POINTS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RIFPTTRXMAIN.ORIGIN
     *
     * @return the value of RIFPTTRXMAIN.ORIGIN
     */
    public String getORIGIN() {
        return ORIGIN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RIFPTTRXMAIN.ORIGIN
     *
     * @param ORIGIN the value for RIFPTTRXMAIN.ORIGIN
     */
    public void setORIGIN(String ORIGIN) {
        this.ORIGIN = ORIGIN == null ? null : ORIGIN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RIFPTTRXMAIN.CREATED_BY
     *
     * @return the value of RIFPTTRXMAIN.CREATED_BY
     */
    public String getCREATED_BY() {
        return CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RIFPTTRXMAIN.CREATED_BY
     *
     * @param CREATED_BY the value for RIFPTTRXMAIN.CREATED_BY
     */
    public void setCREATED_BY(String CREATED_BY) {
        this.CREATED_BY = CREATED_BY == null ? null : CREATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RIFPTTRXMAIN.DATE_CREATED
     *
     * @return the value of RIFPTTRXMAIN.DATE_CREATED
     */
    public Date getDATE_CREATED() {
        return DATE_CREATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RIFPTTRXMAIN.DATE_CREATED
     *
     * @param DATE_CREATED the value for RIFPTTRXMAIN.DATE_CREATED
     */
    public void setDATE_CREATED(Date DATE_CREATED) {
        this.DATE_CREATED = DATE_CREATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RIFPTTRXMAIN.DELETED_BY
     *
     * @return the value of RIFPTTRXMAIN.DELETED_BY
     */
    public String getDELETED_BY() {
        return DELETED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RIFPTTRXMAIN.DELETED_BY
     *
     * @param DELETED_BY the value for RIFPTTRXMAIN.DELETED_BY
     */
    public void setDELETED_BY(String DELETED_BY) {
        this.DELETED_BY = DELETED_BY == null ? null : DELETED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RIFPTTRXMAIN.DATE_DELETED
     *
     * @return the value of RIFPTTRXMAIN.DATE_DELETED
     */
    public Date getDATE_DELETED() {
        return DATE_DELETED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RIFPTTRXMAIN.DATE_DELETED
     *
     * @param DATE_DELETED the value for RIFPTTRXMAIN.DATE_DELETED
     */
    public void setDATE_DELETED(Date DATE_DELETED) {
        this.DATE_DELETED = DATE_DELETED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RIFPTTRXMAIN.SPECIFIC_GLOBAL
     *
     * @return the value of RIFPTTRXMAIN.SPECIFIC_GLOBAL
     */
    public String getSPECIFIC_GLOBAL() {
        return SPECIFIC_GLOBAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RIFPTTRXMAIN.SPECIFIC_GLOBAL
     *
     * @param SPECIFIC_GLOBAL the value for RIFPTTRXMAIN.SPECIFIC_GLOBAL
     */
    public void setSPECIFIC_GLOBAL(String SPECIFIC_GLOBAL) {
        this.SPECIFIC_GLOBAL = SPECIFIC_GLOBAL == null ? null : SPECIFIC_GLOBAL.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RIFPTTRXMAIN.CURRENCY_CODE
     *
     * @return the value of RIFPTTRXMAIN.CURRENCY_CODE
     */
    public BigDecimal getCURRENCY_CODE() {
        return CURRENCY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RIFPTTRXMAIN.CURRENCY_CODE
     *
     * @param CURRENCY_CODE the value for RIFPTTRXMAIN.CURRENCY_CODE
     */
    public void setCURRENCY_CODE(BigDecimal CURRENCY_CODE) {
        this.CURRENCY_CODE = CURRENCY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RIFPTTRXMAIN.GL_CODE
     *
     * @return the value of RIFPTTRXMAIN.GL_CODE
     */
    public BigDecimal getGL_CODE() {
        return GL_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RIFPTTRXMAIN.GL_CODE
     *
     * @param GL_CODE the value for RIFPTTRXMAIN.GL_CODE
     */
    public void setGL_CODE(BigDecimal GL_CODE) {
        this.GL_CODE = GL_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RIFPTTRXMAIN.CIF_SUB_NO
     *
     * @return the value of RIFPTTRXMAIN.CIF_SUB_NO
     */
    public BigDecimal getCIF_SUB_NO() {
        return CIF_SUB_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RIFPTTRXMAIN.CIF_SUB_NO
     *
     * @param CIF_SUB_NO the value for RIFPTTRXMAIN.CIF_SUB_NO
     */
    public void setCIF_SUB_NO(BigDecimal CIF_SUB_NO) {
        this.CIF_SUB_NO = CIF_SUB_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RIFPTTRXMAIN.SL_NO
     *
     * @return the value of RIFPTTRXMAIN.SL_NO
     */
    public BigDecimal getSL_NO() {
        return SL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RIFPTTRXMAIN.SL_NO
     *
     * @param SL_NO the value for RIFPTTRXMAIN.SL_NO
     */
    public void setSL_NO(BigDecimal SL_NO) {
        this.SL_NO = SL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RIFPTTRXMAIN.STATUS
     *
     * @return the value of RIFPTTRXMAIN.STATUS
     */
    public String getSTATUS() {
        return STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RIFPTTRXMAIN.STATUS
     *
     * @param STATUS the value for RIFPTTRXMAIN.STATUS
     */
    public void setSTATUS(String STATUS) {
        this.STATUS = STATUS == null ? null : STATUS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RIFPTTRXMAIN.DEAL_NO
     *
     * @return the value of RIFPTTRXMAIN.DEAL_NO
     */
    public BigDecimal getDEAL_NO() {
        return DEAL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RIFPTTRXMAIN.DEAL_NO
     *
     * @param DEAL_NO the value for RIFPTTRXMAIN.DEAL_NO
     */
    public void setDEAL_NO(BigDecimal DEAL_NO) {
        this.DEAL_NO = DEAL_NO;
    }
}