package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class RIFPTTRXVO extends RIFPTTRXVOKey {
    /**
     * This field corresponds to the database column RIFPTTRX.TRX_DATE
     */
    private Date TRX_DATE;

    /**
     * This field corresponds to the database column RIFPTTRX.REFERENCE
     */
    private String REFERENCE;

    /**
     * This field corresponds to the database column RIFPTTRX.COMMENTS
     */
    private String COMMENTS;

    /**
     * This field corresponds to the database column RIFPTTRX.ORIGIN
     */
    private String ORIGIN;

    /**
     * This field corresponds to the database column RIFPTTRX.POINTS
     */
    private BigDecimal POINTS;

    /**
     * This field corresponds to the database column RIFPTTRX.CURRENCY_CODE
     */
    private BigDecimal CURRENCY_CODE;

    /**
     * This field corresponds to the database column RIFPTTRX.GL_CODE
     */
    private BigDecimal GL_CODE;

    /**
     * This field corresponds to the database column RIFPTTRX.CIF_SUB_NO
     */
    private BigDecimal CIF_SUB_NO;

    /**
     * This field corresponds to the database column RIFPTTRX.SL_NO
     */
    private BigDecimal SL_NO;

    /**
     * This field corresponds to the database column RIFPTTRX.EXCH_RATE
     */
    private BigDecimal EXCH_RATE;

    /**
     * This field corresponds to the database column RIFPTTRX.FC_POINTS
     */
    private BigDecimal FC_POINTS;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RIFPTTRX.TRX_DATE
     *
     * @return the value of RIFPTTRX.TRX_DATE
     */
    public Date getTRX_DATE() {
        return TRX_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RIFPTTRX.TRX_DATE
     *
     * @param TRX_DATE the value for RIFPTTRX.TRX_DATE
     */
    public void setTRX_DATE(Date TRX_DATE) {
        this.TRX_DATE = TRX_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RIFPTTRX.REFERENCE
     *
     * @return the value of RIFPTTRX.REFERENCE
     */
    public String getREFERENCE() {
        return REFERENCE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RIFPTTRX.REFERENCE
     *
     * @param REFERENCE the value for RIFPTTRX.REFERENCE
     */
    public void setREFERENCE(String REFERENCE) {
        this.REFERENCE = REFERENCE == null ? null : REFERENCE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RIFPTTRX.COMMENTS
     *
     * @return the value of RIFPTTRX.COMMENTS
     */
    public String getCOMMENTS() {
        return COMMENTS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RIFPTTRX.COMMENTS
     *
     * @param COMMENTS the value for RIFPTTRX.COMMENTS
     */
    public void setCOMMENTS(String COMMENTS) {
        this.COMMENTS = COMMENTS == null ? null : COMMENTS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RIFPTTRX.ORIGIN
     *
     * @return the value of RIFPTTRX.ORIGIN
     */
    public String getORIGIN() {
        return ORIGIN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RIFPTTRX.ORIGIN
     *
     * @param ORIGIN the value for RIFPTTRX.ORIGIN
     */
    public void setORIGIN(String ORIGIN) {
        this.ORIGIN = ORIGIN == null ? null : ORIGIN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RIFPTTRX.POINTS
     *
     * @return the value of RIFPTTRX.POINTS
     */
    public BigDecimal getPOINTS() {
        return POINTS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RIFPTTRX.POINTS
     *
     * @param POINTS the value for RIFPTTRX.POINTS
     */
    public void setPOINTS(BigDecimal POINTS) {
        this.POINTS = POINTS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RIFPTTRX.CURRENCY_CODE
     *
     * @return the value of RIFPTTRX.CURRENCY_CODE
     */
    public BigDecimal getCURRENCY_CODE() {
        return CURRENCY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RIFPTTRX.CURRENCY_CODE
     *
     * @param CURRENCY_CODE the value for RIFPTTRX.CURRENCY_CODE
     */
    public void setCURRENCY_CODE(BigDecimal CURRENCY_CODE) {
        this.CURRENCY_CODE = CURRENCY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RIFPTTRX.GL_CODE
     *
     * @return the value of RIFPTTRX.GL_CODE
     */
    public BigDecimal getGL_CODE() {
        return GL_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RIFPTTRX.GL_CODE
     *
     * @param GL_CODE the value for RIFPTTRX.GL_CODE
     */
    public void setGL_CODE(BigDecimal GL_CODE) {
        this.GL_CODE = GL_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RIFPTTRX.CIF_SUB_NO
     *
     * @return the value of RIFPTTRX.CIF_SUB_NO
     */
    public BigDecimal getCIF_SUB_NO() {
        return CIF_SUB_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RIFPTTRX.CIF_SUB_NO
     *
     * @param CIF_SUB_NO the value for RIFPTTRX.CIF_SUB_NO
     */
    public void setCIF_SUB_NO(BigDecimal CIF_SUB_NO) {
        this.CIF_SUB_NO = CIF_SUB_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RIFPTTRX.SL_NO
     *
     * @return the value of RIFPTTRX.SL_NO
     */
    public BigDecimal getSL_NO() {
        return SL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RIFPTTRX.SL_NO
     *
     * @param SL_NO the value for RIFPTTRX.SL_NO
     */
    public void setSL_NO(BigDecimal SL_NO) {
        this.SL_NO = SL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RIFPTTRX.EXCH_RATE
     *
     * @return the value of RIFPTTRX.EXCH_RATE
     */
    public BigDecimal getEXCH_RATE() {
        return EXCH_RATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RIFPTTRX.EXCH_RATE
     *
     * @param EXCH_RATE the value for RIFPTTRX.EXCH_RATE
     */
    public void setEXCH_RATE(BigDecimal EXCH_RATE) {
        this.EXCH_RATE = EXCH_RATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RIFPTTRX.FC_POINTS
     *
     * @return the value of RIFPTTRX.FC_POINTS
     */
    public BigDecimal getFC_POINTS() {
        return FC_POINTS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RIFPTTRX.FC_POINTS
     *
     * @param FC_POINTS the value for RIFPTTRX.FC_POINTS
     */
    public void setFC_POINTS(BigDecimal FC_POINTS) {
        this.FC_POINTS = FC_POINTS;
    }
}