package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class S_ADDITIONS_DETAILSVOKey extends BaseVO {
    /**
     * This field corresponds to the database column S_ADDITIONS_DETAILS.APP_NAME
     */
    private String APP_NAME;

    /**
     * This field corresponds to the database column S_ADDITIONS_DETAILS.PROG_REFERENCE
     */
    private String PROG_REFERENCE;

    /**
     * This field corresponds to the database column S_ADDITIONS_DETAILS.S_ADD_TYPE_CODE
     */
    private BigDecimal s_ADD_TYPE_CODE;

    /**
     * This field corresponds to the database column S_ADDITIONS_DETAILS.TRX_NBR
     */
    private String TRX_NBR;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S_ADDITIONS_DETAILS.APP_NAME
     *
     * @return the value of S_ADDITIONS_DETAILS.APP_NAME
     */
    public String getAPP_NAME() {
        return APP_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S_ADDITIONS_DETAILS.APP_NAME
     *
     * @param APP_NAME the value for S_ADDITIONS_DETAILS.APP_NAME
     */
    public void setAPP_NAME(String APP_NAME) {
        this.APP_NAME = APP_NAME == null ? null : APP_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S_ADDITIONS_DETAILS.PROG_REFERENCE
     *
     * @return the value of S_ADDITIONS_DETAILS.PROG_REFERENCE
     */
    public String getPROG_REFERENCE() {
        return PROG_REFERENCE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S_ADDITIONS_DETAILS.PROG_REFERENCE
     *
     * @param PROG_REFERENCE the value for S_ADDITIONS_DETAILS.PROG_REFERENCE
     */
    public void setPROG_REFERENCE(String PROG_REFERENCE) {
        this.PROG_REFERENCE = PROG_REFERENCE == null ? null : PROG_REFERENCE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S_ADDITIONS_DETAILS.S_ADD_TYPE_CODE
     *
     * @return the value of S_ADDITIONS_DETAILS.S_ADD_TYPE_CODE
     */
    public BigDecimal getS_ADD_TYPE_CODE() {
        return s_ADD_TYPE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S_ADDITIONS_DETAILS.S_ADD_TYPE_CODE
     *
     * @param s_ADD_TYPE_CODE the value for S_ADDITIONS_DETAILS.S_ADD_TYPE_CODE
     */
    public void setS_ADD_TYPE_CODE(BigDecimal s_ADD_TYPE_CODE) {
        this.s_ADD_TYPE_CODE = s_ADD_TYPE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S_ADDITIONS_DETAILS.TRX_NBR
     *
     * @return the value of S_ADDITIONS_DETAILS.TRX_NBR
     */
    public String getTRX_NBR() {
        return TRX_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S_ADDITIONS_DETAILS.TRX_NBR
     *
     * @param TRX_NBR the value for S_ADDITIONS_DETAILS.TRX_NBR
     */
    public void setTRX_NBR(String TRX_NBR) {
        this.TRX_NBR = TRX_NBR == null ? null : TRX_NBR.trim();
    }
}