package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class S_ADDITIONS_OPTIONSVOKey extends BaseVO {
    /**
     * This field corresponds to the database column S_ADDITIONS_OPTIONS.OPTION_CODE
     */
    private BigDecimal OPTION_CODE;

    /**
     * This field corresponds to the database column S_ADDITIONS_OPTIONS.OPTION_SERIAL
     */
    private BigDecimal OPTION_SERIAL;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S_ADDITIONS_OPTIONS.OPTION_CODE
     *
     * @return the value of S_ADDITIONS_OPTIONS.OPTION_CODE
     */
    public BigDecimal getOPTION_CODE() {
        return OPTION_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S_ADDITIONS_OPTIONS.OPTION_CODE
     *
     * @param OPTION_CODE the value for S_ADDITIONS_OPTIONS.OPTION_CODE
     */
    public void setOPTION_CODE(BigDecimal OPTION_CODE) {
        this.OPTION_CODE = OPTION_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S_ADDITIONS_OPTIONS.OPTION_SERIAL
     *
     * @return the value of S_ADDITIONS_OPTIONS.OPTION_SERIAL
     */
    public BigDecimal getOPTION_SERIAL() {
        return OPTION_SERIAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S_ADDITIONS_OPTIONS.OPTION_SERIAL
     *
     * @param OPTION_SERIAL the value for S_ADDITIONS_OPTIONS.OPTION_SERIAL
     */
    public void setOPTION_SERIAL(BigDecimal OPTION_SERIAL) {
        this.OPTION_SERIAL = OPTION_SERIAL;
    }
}