package com.path.dbmaps.vo;

public class S_ADDREF_MASK_SPECIFICVO extends S_ADDREF_MASK_SPECIFICVOKey {
    /**
     * This field corresponds to the database column S_ADDREF_MASK_SPECIFIC.COLUMN_NAME
     */
    private String COLUMN_NAME;

    /**
     * This field corresponds to the database column S_ADDREF_MASK_SPECIFIC.COLUMN_MASK
     */
    private String COLUMN_MASK;

    /**
     * This field corresponds to the database column S_ADDREF_MASK_SPECIFIC.COLUMN_SEPARATOR
     */
    private String COLUMN_SEPARATOR;

    /**
     * This field corresponds to the database column S_ADDREF_MASK_SPECIFIC.COLUMN_TYPE
     */
    private String COLUMN_TYPE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S_ADDREF_MASK_SPECIFIC.COLUMN_NAME
     *
     * @return the value of S_ADDREF_MASK_SPECIFIC.COLUMN_NAME
     */
    public String getCOLUMN_NAME() {
        return COLUMN_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S_ADDREF_MASK_SPECIFIC.COLUMN_NAME
     *
     * @param COLUMN_NAME the value for S_ADDREF_MASK_SPECIFIC.COLUMN_NAME
     */
    public void setCOLUMN_NAME(String COLUMN_NAME) {
        this.COLUMN_NAME = COLUMN_NAME == null ? null : COLUMN_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S_ADDREF_MASK_SPECIFIC.COLUMN_MASK
     *
     * @return the value of S_ADDREF_MASK_SPECIFIC.COLUMN_MASK
     */
    public String getCOLUMN_MASK() {
        return COLUMN_MASK;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S_ADDREF_MASK_SPECIFIC.COLUMN_MASK
     *
     * @param COLUMN_MASK the value for S_ADDREF_MASK_SPECIFIC.COLUMN_MASK
     */
    public void setCOLUMN_MASK(String COLUMN_MASK) {
        this.COLUMN_MASK = COLUMN_MASK == null ? null : COLUMN_MASK.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S_ADDREF_MASK_SPECIFIC.COLUMN_SEPARATOR
     *
     * @return the value of S_ADDREF_MASK_SPECIFIC.COLUMN_SEPARATOR
     */
    public String getCOLUMN_SEPARATOR() {
        return COLUMN_SEPARATOR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S_ADDREF_MASK_SPECIFIC.COLUMN_SEPARATOR
     *
     * @param COLUMN_SEPARATOR the value for S_ADDREF_MASK_SPECIFIC.COLUMN_SEPARATOR
     */
    public void setCOLUMN_SEPARATOR(String COLUMN_SEPARATOR) {
        this.COLUMN_SEPARATOR = COLUMN_SEPARATOR == null ? null : COLUMN_SEPARATOR.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S_ADDREF_MASK_SPECIFIC.COLUMN_TYPE
     *
     * @return the value of S_ADDREF_MASK_SPECIFIC.COLUMN_TYPE
     */
    public String getCOLUMN_TYPE() {
        return COLUMN_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S_ADDREF_MASK_SPECIFIC.COLUMN_TYPE
     *
     * @param COLUMN_TYPE the value for S_ADDREF_MASK_SPECIFIC.COLUMN_TYPE
     */
    public void setCOLUMN_TYPE(String COLUMN_TYPE) {
        this.COLUMN_TYPE = COLUMN_TYPE == null ? null : COLUMN_TYPE.trim();
    }
}