package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;
import java.util.Date;

public class S_ADDITIONS_DETAILS_HSTVOKey extends BaseVO {
    /**
     * This field corresponds to the database column S_ADDITIONS_DETAILS_HST.APP_NAME
     */
    private String APP_NAME;

    /**
     * This field corresponds to the database column S_ADDITIONS_DETAILS_HST.PROG_REFERENCE
     */
    private String PROG_REFERENCE;

    /**
     * This field corresponds to the database column S_ADDITIONS_DETAILS_HST.S_ADD_DATE
     */
    private Date s_ADD_DATE;

    /**
     * This field corresponds to the database column S_ADDITIONS_DETAILS_HST.S_ADD_TYPE_CODE
     */
    private BigDecimal s_ADD_TYPE_CODE;

    /**
     * This field corresponds to the database column S_ADDITIONS_DETAILS_HST.TRX_NBR
     */
    private String TRX_NBR;

    /**
     * This field corresponds to the database column S_ADDITIONS_DETAILS_HST.USER_ID
     */
    private String USER_ID;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S_ADDITIONS_DETAILS_HST.APP_NAME
     *
     * @return the value of S_ADDITIONS_DETAILS_HST.APP_NAME
     */
    public String getAPP_NAME() {
        return APP_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S_ADDITIONS_DETAILS_HST.APP_NAME
     *
     * @param APP_NAME the value for S_ADDITIONS_DETAILS_HST.APP_NAME
     */
    public void setAPP_NAME(String APP_NAME) {
        this.APP_NAME = APP_NAME == null ? null : APP_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S_ADDITIONS_DETAILS_HST.PROG_REFERENCE
     *
     * @return the value of S_ADDITIONS_DETAILS_HST.PROG_REFERENCE
     */
    public String getPROG_REFERENCE() {
        return PROG_REFERENCE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S_ADDITIONS_DETAILS_HST.PROG_REFERENCE
     *
     * @param PROG_REFERENCE the value for S_ADDITIONS_DETAILS_HST.PROG_REFERENCE
     */
    public void setPROG_REFERENCE(String PROG_REFERENCE) {
        this.PROG_REFERENCE = PROG_REFERENCE == null ? null : PROG_REFERENCE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S_ADDITIONS_DETAILS_HST.S_ADD_DATE
     *
     * @return the value of S_ADDITIONS_DETAILS_HST.S_ADD_DATE
     */
    public Date getS_ADD_DATE() {
        return s_ADD_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S_ADDITIONS_DETAILS_HST.S_ADD_DATE
     *
     * @param s_ADD_DATE the value for S_ADDITIONS_DETAILS_HST.S_ADD_DATE
     */
    public void setS_ADD_DATE(Date s_ADD_DATE) {
        this.s_ADD_DATE = s_ADD_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S_ADDITIONS_DETAILS_HST.S_ADD_TYPE_CODE
     *
     * @return the value of S_ADDITIONS_DETAILS_HST.S_ADD_TYPE_CODE
     */
    public BigDecimal getS_ADD_TYPE_CODE() {
        return s_ADD_TYPE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S_ADDITIONS_DETAILS_HST.S_ADD_TYPE_CODE
     *
     * @param s_ADD_TYPE_CODE the value for S_ADDITIONS_DETAILS_HST.S_ADD_TYPE_CODE
     */
    public void setS_ADD_TYPE_CODE(BigDecimal s_ADD_TYPE_CODE) {
        this.s_ADD_TYPE_CODE = s_ADD_TYPE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S_ADDITIONS_DETAILS_HST.TRX_NBR
     *
     * @return the value of S_ADDITIONS_DETAILS_HST.TRX_NBR
     */
    public String getTRX_NBR() {
        return TRX_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S_ADDITIONS_DETAILS_HST.TRX_NBR
     *
     * @param TRX_NBR the value for S_ADDITIONS_DETAILS_HST.TRX_NBR
     */
    public void setTRX_NBR(String TRX_NBR) {
        this.TRX_NBR = TRX_NBR == null ? null : TRX_NBR.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S_ADDITIONS_DETAILS_HST.USER_ID
     *
     * @return the value of S_ADDITIONS_DETAILS_HST.USER_ID
     */
    public String getUSER_ID() {
        return USER_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S_ADDITIONS_DETAILS_HST.USER_ID
     *
     * @param USER_ID the value for S_ADDITIONS_DETAILS_HST.USER_ID
     */
    public void setUSER_ID(String USER_ID) {
        this.USER_ID = USER_ID == null ? null : USER_ID.trim();
    }
}