package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class S_ADDITIONS_DETAILSVO extends S_ADDITIONS_DETAILSVOKey {
    /**
     * This field corresponds to the database column S_ADDITIONS_DETAILS.S_ADD_OPTION_CODE
     */
    private BigDecimal s_ADD_OPTION_CODE;

    /**
     * This field corresponds to the database column S_ADDITIONS_DETAILS.MANUAL_REFERENCE
     */
    private String MANUAL_REFERENCE;

    /**
     * This field corresponds to the database column S_ADDITIONS_DETAILS.ADDITION_TEXT
     */
    private String ADDITION_TEXT;

    /**
     * This field corresponds to the database column S_ADDITIONS_DETAILS.ADDITION_DATE
     */
    private Date ADDITION_DATE;

    /**
     * This field corresponds to the database column S_ADDITIONS_DETAILS.ADDITION_NUMBER
     */
    private BigDecimal ADDITION_NUMBER;

    /**
     * This field corresponds to the database column S_ADDITIONS_DETAILS.THIRD_PARTY_LOCATION
     */
    private String THIRD_PARTY_LOCATION;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S_ADDITIONS_DETAILS.S_ADD_OPTION_CODE
     *
     * @return the value of S_ADDITIONS_DETAILS.S_ADD_OPTION_CODE
     */
    public BigDecimal getS_ADD_OPTION_CODE() {
        return s_ADD_OPTION_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S_ADDITIONS_DETAILS.S_ADD_OPTION_CODE
     *
     * @param s_ADD_OPTION_CODE the value for S_ADDITIONS_DETAILS.S_ADD_OPTION_CODE
     */
    public void setS_ADD_OPTION_CODE(BigDecimal s_ADD_OPTION_CODE) {
        this.s_ADD_OPTION_CODE = s_ADD_OPTION_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S_ADDITIONS_DETAILS.MANUAL_REFERENCE
     *
     * @return the value of S_ADDITIONS_DETAILS.MANUAL_REFERENCE
     */
    public String getMANUAL_REFERENCE() {
        return MANUAL_REFERENCE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S_ADDITIONS_DETAILS.MANUAL_REFERENCE
     *
     * @param MANUAL_REFERENCE the value for S_ADDITIONS_DETAILS.MANUAL_REFERENCE
     */
    public void setMANUAL_REFERENCE(String MANUAL_REFERENCE) {
        this.MANUAL_REFERENCE = MANUAL_REFERENCE == null ? null : MANUAL_REFERENCE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S_ADDITIONS_DETAILS.ADDITION_TEXT
     *
     * @return the value of S_ADDITIONS_DETAILS.ADDITION_TEXT
     */
    public String getADDITION_TEXT() {
        return ADDITION_TEXT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S_ADDITIONS_DETAILS.ADDITION_TEXT
     *
     * @param ADDITION_TEXT the value for S_ADDITIONS_DETAILS.ADDITION_TEXT
     */
    public void setADDITION_TEXT(String ADDITION_TEXT) {
        this.ADDITION_TEXT = ADDITION_TEXT == null ? null : ADDITION_TEXT.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S_ADDITIONS_DETAILS.ADDITION_DATE
     *
     * @return the value of S_ADDITIONS_DETAILS.ADDITION_DATE
     */
    public Date getADDITION_DATE() {
        return ADDITION_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S_ADDITIONS_DETAILS.ADDITION_DATE
     *
     * @param ADDITION_DATE the value for S_ADDITIONS_DETAILS.ADDITION_DATE
     */
    public void setADDITION_DATE(Date ADDITION_DATE) {
        this.ADDITION_DATE = ADDITION_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S_ADDITIONS_DETAILS.ADDITION_NUMBER
     *
     * @return the value of S_ADDITIONS_DETAILS.ADDITION_NUMBER
     */
    public BigDecimal getADDITION_NUMBER() {
        return ADDITION_NUMBER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S_ADDITIONS_DETAILS.ADDITION_NUMBER
     *
     * @param ADDITION_NUMBER the value for S_ADDITIONS_DETAILS.ADDITION_NUMBER
     */
    public void setADDITION_NUMBER(BigDecimal ADDITION_NUMBER) {
        this.ADDITION_NUMBER = ADDITION_NUMBER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S_ADDITIONS_DETAILS.THIRD_PARTY_LOCATION
     *
     * @return the value of S_ADDITIONS_DETAILS.THIRD_PARTY_LOCATION
     */
    public String getTHIRD_PARTY_LOCATION() {
        return THIRD_PARTY_LOCATION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S_ADDITIONS_DETAILS.THIRD_PARTY_LOCATION
     *
     * @param THIRD_PARTY_LOCATION the value for S_ADDITIONS_DETAILS.THIRD_PARTY_LOCATION
     */
    public void setTHIRD_PARTY_LOCATION(String THIRD_PARTY_LOCATION) {
        this.THIRD_PARTY_LOCATION = THIRD_PARTY_LOCATION == null ? null : THIRD_PARTY_LOCATION.trim();
    }

}