package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class S_AUDIT_ACTION_DTLVO extends S_AUDIT_ACTION_DTLVOKey {
    /**
     * This field corresponds to the database column S_AUDIT_ACTION_DTL.FIELD_NAME
     */
    private String FIELD_NAME;

    /**
     * This field corresponds to the database column S_AUDIT_ACTION_DTL.OLD_VALUE
     */
    private String OLD_VALUE;

    /**
     * This field corresponds to the database column S_AUDIT_ACTION_DTL.NEW_VALUE
     */
    private String NEW_VALUE;

    /**
     * This field corresponds to the database column S_AUDIT_ACTION_DTL.RUNNING_DATE
     */
    private Date RUNNING_DATE;

    /**
     * This field corresponds to the database column S_AUDIT_ACTION_DTL.ELEMENT_NAME
     */
    private String ELEMENT_NAME;

    /**
     * This field corresponds to the database column S_AUDIT_ACTION_DTL.ELEMENT_TYPE
     */
    private BigDecimal ELEMENT_TYPE;
    
    //439073 ADD support for additional fields labels
    /**
     * This field corresponds to the database column S_AUDIT_ACTION_DTL.ADDITIONAL_FIELD_TYPE
     */
    private BigDecimal ADDITIONAL_FIELD_TYPE;
    
    /**
     * This field corresponds to the database column S_AUDIT_ACTION_DTL.ADD_FIELD_CODE
     */
    private BigDecimal ADD_FIELD_CODE;
    
    /**
     * This field corresponds to the database column S_AUDIT_ACTION_DTL.ADD_FIELD_BY_TYPE_COLUMN_NBR
     */
    private BigDecimal ADD_FIELD_BY_TYPE_COLUMN_NBR;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S_AUDIT_ACTION_DTL.FIELD_NAME
     *
     * @return the value of S_AUDIT_ACTION_DTL.FIELD_NAME
     */
    public String getFIELD_NAME() {
        return FIELD_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S_AUDIT_ACTION_DTL.FIELD_NAME
     *
     * @param FIELD_NAME the value for S_AUDIT_ACTION_DTL.FIELD_NAME
     */
    public void setFIELD_NAME(String FIELD_NAME) {
        this.FIELD_NAME = FIELD_NAME == null ? null : FIELD_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S_AUDIT_ACTION_DTL.OLD_VALUE
     *
     * @return the value of S_AUDIT_ACTION_DTL.OLD_VALUE
     */
    public String getOLD_VALUE() {
        return OLD_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S_AUDIT_ACTION_DTL.OLD_VALUE
     *
     * @param OLD_VALUE the value for S_AUDIT_ACTION_DTL.OLD_VALUE
     */
    public void setOLD_VALUE(String OLD_VALUE) {
        this.OLD_VALUE = OLD_VALUE == null ? null : OLD_VALUE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S_AUDIT_ACTION_DTL.NEW_VALUE
     *
     * @return the value of S_AUDIT_ACTION_DTL.NEW_VALUE
     */
    public String getNEW_VALUE() {
        return NEW_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S_AUDIT_ACTION_DTL.NEW_VALUE
     *
     * @param NEW_VALUE the value for S_AUDIT_ACTION_DTL.NEW_VALUE
     */
    public void setNEW_VALUE(String NEW_VALUE) {
        this.NEW_VALUE = NEW_VALUE == null ? null : NEW_VALUE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S_AUDIT_ACTION_DTL.RUNNING_DATE
     *
     * @return the value of S_AUDIT_ACTION_DTL.RUNNING_DATE
     */
    public Date getRUNNING_DATE() {
        return RUNNING_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S_AUDIT_ACTION_DTL.RUNNING_DATE
     *
     * @param RUNNING_DATE the value for S_AUDIT_ACTION_DTL.RUNNING_DATE
     */
    public void setRUNNING_DATE(Date RUNNING_DATE) {
        this.RUNNING_DATE = RUNNING_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S_AUDIT_ACTION_DTL.ELEMENT_NAME
     *
     * @return the value of S_AUDIT_ACTION_DTL.ELEMENT_NAME
     */
    public String getELEMENT_NAME() {
        return ELEMENT_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S_AUDIT_ACTION_DTL.ELEMENT_NAME
     *
     * @param ELEMENT_NAME the value for S_AUDIT_ACTION_DTL.ELEMENT_NAME
     */
    public void setELEMENT_NAME(String ELEMENT_NAME) {
        this.ELEMENT_NAME = ELEMENT_NAME == null ? null : ELEMENT_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S_AUDIT_ACTION_DTL.ELEMENT_TYPE
     *
     * @return the value of S_AUDIT_ACTION_DTL.ELEMENT_TYPE
     */
    public BigDecimal getELEMENT_TYPE() {
        return ELEMENT_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S_AUDIT_ACTION_DTL.ELEMENT_TYPE
     *
     * @param ELEMENT_TYPE the value for S_AUDIT_ACTION_DTL.ELEMENT_TYPE
     */
    public void setELEMENT_TYPE(BigDecimal ELEMENT_TYPE) {
        this.ELEMENT_TYPE = ELEMENT_TYPE;
    }

    public BigDecimal getADDITIONAL_FIELD_TYPE()
    {
	return ADDITIONAL_FIELD_TYPE;
    }

    public void setADDITIONAL_FIELD_TYPE(BigDecimal aDDITIONAL_FIELD_TYPE)
    {
	ADDITIONAL_FIELD_TYPE = aDDITIONAL_FIELD_TYPE;
    }

    public BigDecimal getADD_FIELD_CODE()
    {
	return ADD_FIELD_CODE;
    }

    public void setADD_FIELD_CODE(BigDecimal aDD_FIELD_CODE)
    {
	ADD_FIELD_CODE = aDD_FIELD_CODE;
    }

    public BigDecimal getADD_FIELD_BY_TYPE_COLUMN_NBR()
    {
	return ADD_FIELD_BY_TYPE_COLUMN_NBR;
    }

    public void setADD_FIELD_BY_TYPE_COLUMN_NBR(BigDecimal aDD_FIELD_BY_TYPE_COLUMN_NBR)
    {
	ADD_FIELD_BY_TYPE_COLUMN_NBR = aDD_FIELD_BY_TYPE_COLUMN_NBR;
    }
}