package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;
import java.util.Date;

public class S_AUDIT_ACTION_DTLVOKey extends BaseVO {
    /**
     * This field corresponds to the database column S_AUDIT_ACTION_DTL.ACTION_DATE
     */
    private Date ACTION_DATE;

    /**
     * This field corresponds to the database column S_AUDIT_ACTION_DTL.APP_NAME
     */
    private String APP_NAME;

    /**
     * This field corresponds to the database column S_AUDIT_ACTION_DTL.AUTO_INCREMENT
     */
    private BigDecimal AUTO_INCREMENT;

    /**
     * This field corresponds to the database column S_AUDIT_ACTION_DTL.LINE_NUMBER
     */
    private BigDecimal LINE_NUMBER;

    /**
     * This field corresponds to the database column S_AUDIT_ACTION_DTL.PROG_REF
     */
    private String PROG_REF;

    /**
     * This field corresponds to the database column S_AUDIT_ACTION_DTL.TRX_NUMBER
     */
    private String TRX_NUMBER;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S_AUDIT_ACTION_DTL.ACTION_DATE
     *
     * @return the value of S_AUDIT_ACTION_DTL.ACTION_DATE
     */
    public Date getACTION_DATE() {
        return ACTION_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S_AUDIT_ACTION_DTL.ACTION_DATE
     *
     * @param ACTION_DATE the value for S_AUDIT_ACTION_DTL.ACTION_DATE
     */
    public void setACTION_DATE(Date ACTION_DATE) {
        this.ACTION_DATE = ACTION_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S_AUDIT_ACTION_DTL.APP_NAME
     *
     * @return the value of S_AUDIT_ACTION_DTL.APP_NAME
     */
    public String getAPP_NAME() {
        return APP_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S_AUDIT_ACTION_DTL.APP_NAME
     *
     * @param APP_NAME the value for S_AUDIT_ACTION_DTL.APP_NAME
     */
    public void setAPP_NAME(String APP_NAME) {
        this.APP_NAME = APP_NAME == null ? null : APP_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S_AUDIT_ACTION_DTL.AUTO_INCREMENT
     *
     * @return the value of S_AUDIT_ACTION_DTL.AUTO_INCREMENT
     */
    public BigDecimal getAUTO_INCREMENT() {
        return AUTO_INCREMENT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S_AUDIT_ACTION_DTL.AUTO_INCREMENT
     *
     * @param AUTO_INCREMENT the value for S_AUDIT_ACTION_DTL.AUTO_INCREMENT
     */
    public void setAUTO_INCREMENT(BigDecimal AUTO_INCREMENT) {
        this.AUTO_INCREMENT = AUTO_INCREMENT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S_AUDIT_ACTION_DTL.LINE_NUMBER
     *
     * @return the value of S_AUDIT_ACTION_DTL.LINE_NUMBER
     */
    public BigDecimal getLINE_NUMBER() {
        return LINE_NUMBER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S_AUDIT_ACTION_DTL.LINE_NUMBER
     *
     * @param LINE_NUMBER the value for S_AUDIT_ACTION_DTL.LINE_NUMBER
     */
    public void setLINE_NUMBER(BigDecimal LINE_NUMBER) {
        this.LINE_NUMBER = LINE_NUMBER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S_AUDIT_ACTION_DTL.PROG_REF
     *
     * @return the value of S_AUDIT_ACTION_DTL.PROG_REF
     */
    public String getPROG_REF() {
        return PROG_REF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S_AUDIT_ACTION_DTL.PROG_REF
     *
     * @param PROG_REF the value for S_AUDIT_ACTION_DTL.PROG_REF
     */
    public void setPROG_REF(String PROG_REF) {
        this.PROG_REF = PROG_REF == null ? null : PROG_REF.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S_AUDIT_ACTION_DTL.TRX_NUMBER
     *
     * @return the value of S_AUDIT_ACTION_DTL.TRX_NUMBER
     */
    public String getTRX_NUMBER() {
        return TRX_NUMBER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S_AUDIT_ACTION_DTL.TRX_NUMBER
     *
     * @param TRX_NUMBER the value for S_AUDIT_ACTION_DTL.TRX_NUMBER
     */
    public void setTRX_NUMBER(String TRX_NUMBER) {
        this.TRX_NUMBER = TRX_NUMBER == null ? null : TRX_NUMBER.trim();
    }
}