package com.path.dbmaps.vo;

public class S_ROLEVO extends S_ROLEVOKey {
    /**
     * This field corresponds to the database column S_ROLE.LONG_NAME
     */
    private String LONG_NAME;

    /**
     * This field corresponds to the database column S_ROLE.REMARKS
     */
    private String REMARKS;

    /**
     * This field corresponds to the database column S_ROLE.APP_NAME
     */
    private String APP_NAME;

    /**
     * This field corresponds to the database column S_ROLE.STATUS
     */
    private String STATUS;

    /**
     * This field corresponds to the database column S_ROLE.CREATED_BY
     */
    private String CREATED_BY;

    /**
     * This field corresponds to the database column S_ROLE.AUTHORIZED_BY
     */
    private String AUTHORIZED_BY;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S_ROLE.LONG_NAME
     *
     * @return the value of S_ROLE.LONG_NAME
     */
    public String getLONG_NAME() {
        return LONG_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S_ROLE.LONG_NAME
     *
     * @param LONG_NAME the value for S_ROLE.LONG_NAME
     */
    public void setLONG_NAME(String LONG_NAME) {
        this.LONG_NAME = LONG_NAME == null ? null : LONG_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S_ROLE.REMARKS
     *
     * @return the value of S_ROLE.REMARKS
     */
    public String getREMARKS() {
        return REMARKS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S_ROLE.REMARKS
     *
     * @param REMARKS the value for S_ROLE.REMARKS
     */
    public void setREMARKS(String REMARKS) {
        this.REMARKS = REMARKS == null ? null : REMARKS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S_ROLE.APP_NAME
     *
     * @return the value of S_ROLE.APP_NAME
     */
    public String getAPP_NAME() {
        return APP_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S_ROLE.APP_NAME
     *
     * @param APP_NAME the value for S_ROLE.APP_NAME
     */
    public void setAPP_NAME(String APP_NAME) {
        this.APP_NAME = APP_NAME == null ? null : APP_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S_ROLE.STATUS
     *
     * @return the value of S_ROLE.STATUS
     */
    public String getSTATUS() {
        return STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S_ROLE.STATUS
     *
     * @param STATUS the value for S_ROLE.STATUS
     */
    public void setSTATUS(String STATUS) {
        this.STATUS = STATUS == null ? null : STATUS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S_ROLE.CREATED_BY
     *
     * @return the value of S_ROLE.CREATED_BY
     */
    public String getCREATED_BY() {
        return CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S_ROLE.CREATED_BY
     *
     * @param CREATED_BY the value for S_ROLE.CREATED_BY
     */
    public void setCREATED_BY(String CREATED_BY) {
        this.CREATED_BY = CREATED_BY == null ? null : CREATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S_ROLE.AUTHORIZED_BY
     *
     * @return the value of S_ROLE.AUTHORIZED_BY
     */
    public String getAUTHORIZED_BY() {
        return AUTHORIZED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S_ROLE.AUTHORIZED_BY
     *
     * @param AUTHORIZED_BY the value for S_ROLE.AUTHORIZED_BY
     */
    public void setAUTHORIZED_BY(String AUTHORIZED_BY) {
        this.AUTHORIZED_BY = AUTHORIZED_BY == null ? null : AUTHORIZED_BY.trim();
    }
}