package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class S_SIGN_MODIFVO extends S_SIGN_MODIFVOKey {
    /**
     * This field corresponds to the database column S_SIGN_MODIF.TO_BE_AMOUNT
     */
    private BigDecimal TO_BE_AMOUNT;

    /**
     * This field corresponds to the database column S_SIGN_MODIF.TO_BE_GROUP_ID
     */
    private String TO_BE_GROUP_ID;

    /**
     * This field corresponds to the database column S_SIGN_MODIF.TO_BE_DESCRIPTION
     */
    private String TO_BE_DESCRIPTION;

    /**
     * This field corresponds to the database column S_SIGN_MODIF.TO_BE_EXP_DATE
     */
    private Date TO_BE_EXP_DATE;

    /**
     * This field corresponds to the database column S_SIGN_MODIF.TO_BE_DEFAULT_UNLIMITED
     */
    private BigDecimal TO_BE_DEFAULT_UNLIMITED;

    /**
     * This field corresponds to the database column S_SIGN_MODIF.TO_BE_ANNOTATION
     */
    private String TO_BE_ANNOTATION;

    /**
     * This field corresponds to the database column S_SIGN_MODIF.TO_BE_STATUS
     */
    private String TO_BE_STATUS;

    /**
     * This field corresponds to the database column S_SIGN_MODIF.TO_BE_AMOUNT_CY
     */
    private BigDecimal TO_BE_AMOUNT_CY;

    /**
     * This field corresponds to the database column S_SIGN_MODIF.TO_BE_OBJECT_TYPE
     */
    private String TO_BE_OBJECT_TYPE;

    /**
     * This field corresponds to the database column S_SIGN_MODIF.TO_BE_DATE_CREATED
     */
    private Date TO_BE_DATE_CREATED;

    /**
     * This field corresponds to the database column S_SIGN_MODIF.TO_BE_CREATED_BY
     */
    private String TO_BE_CREATED_BY;

    /**
     * This field corresponds to the database column S_SIGN_MODIF.TO_BE_DATE_AUTHORISED
     */
    private Date TO_BE_DATE_AUTHORISED;

    /**
     * This field corresponds to the database column S_SIGN_MODIF.TO_BE_AUTHORISED_BY
     */
    private String TO_BE_AUTHORISED_BY;

    /**
     * This field corresponds to the database column S_SIGN_MODIF.TO_BE_SC_WIDTH
     */
    private BigDecimal TO_BE_SC_WIDTH;

    /**
     * This field corresponds to the database column S_SIGN_MODIF.TO_BE_SC_HEIGHT
     */
    private BigDecimal TO_BE_SC_HEIGHT;

    /**
     * This field corresponds to the database column S_SIGN_MODIF.TO_BE_SC_FORMAT
     */
    private String TO_BE_SC_FORMAT;

    /**
     * This field corresponds to the database column S_SIGN_MODIF.TO_BE_DATE_DELETED
     */
    private Date TO_BE_DATE_DELETED;

    /**
     * This field corresponds to the database column S_SIGN_MODIF.TO_BE_DELETED_BY
     */
    private String TO_BE_DELETED_BY;

    /**
     * This field corresponds to the database column S_SIGN_MODIF.ORIGIN_CODE
     */
    private BigDecimal ORIGIN_CODE;

    /**
     * This field corresponds to the database column S_SIGN_MODIF.ORIGIN_SEQ
     */
    private BigDecimal ORIGIN_SEQ;

    /**
     * This field corresponds to the database column S_SIGN_MODIF.TO_BE_DATE_MODIFIED
     */
    private Date TO_BE_DATE_MODIFIED;

    /**
     * This field corresponds to the database column S_SIGN_MODIF.TO_BE_MODIFIED_BY
     */
    private String TO_BE_MODIFIED_BY;

    /**
     * This field corresponds to the database column S_SIGN_MODIF.TO_BE_DEFAULT_PHOTO
     */
    private BigDecimal TO_BE_DEFAULT_PHOTO;

    /**
     * This field corresponds to the database column S_SIGN_MODIF.OLE_OBJECT
     */
    private byte[] OLE_OBJECT;
    
    /**
     * This field corresponds to the database column S_SIGN_MODIF.TO_BE_SIGN_INSTRUCTIONS
     */
    private String TO_BE_SIGN_INSTRUCTIONS;

    /**
     * This field corresponds to the database column S_SIGN_MODIF.TO_BE_INST_OTHER_VALUE
     */
    private String TO_BE_INST_OTHER_VALUE;
    
    
    private BigDecimal AUTH_CIF_NO;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S_SIGN_MODIF.TO_BE_AMOUNT
     *
     * @return the value of S_SIGN_MODIF.TO_BE_AMOUNT
     */
    public BigDecimal getTO_BE_AMOUNT() {
        return TO_BE_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S_SIGN_MODIF.TO_BE_AMOUNT
     *
     * @param TO_BE_AMOUNT the value for S_SIGN_MODIF.TO_BE_AMOUNT
     */
    public void setTO_BE_AMOUNT(BigDecimal TO_BE_AMOUNT) {
        this.TO_BE_AMOUNT = TO_BE_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S_SIGN_MODIF.TO_BE_GROUP_ID
     *
     * @return the value of S_SIGN_MODIF.TO_BE_GROUP_ID
     */
    public String getTO_BE_GROUP_ID() {
        return TO_BE_GROUP_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S_SIGN_MODIF.TO_BE_GROUP_ID
     *
     * @param TO_BE_GROUP_ID the value for S_SIGN_MODIF.TO_BE_GROUP_ID
     */
    public void setTO_BE_GROUP_ID(String TO_BE_GROUP_ID) {
        this.TO_BE_GROUP_ID = TO_BE_GROUP_ID == null ? null : TO_BE_GROUP_ID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S_SIGN_MODIF.TO_BE_DESCRIPTION
     *
     * @return the value of S_SIGN_MODIF.TO_BE_DESCRIPTION
     */
    public String getTO_BE_DESCRIPTION() {
        return TO_BE_DESCRIPTION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S_SIGN_MODIF.TO_BE_DESCRIPTION
     *
     * @param TO_BE_DESCRIPTION the value for S_SIGN_MODIF.TO_BE_DESCRIPTION
     */
    public void setTO_BE_DESCRIPTION(String TO_BE_DESCRIPTION) {
        this.TO_BE_DESCRIPTION = TO_BE_DESCRIPTION == null ? null : TO_BE_DESCRIPTION.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S_SIGN_MODIF.TO_BE_EXP_DATE
     *
     * @return the value of S_SIGN_MODIF.TO_BE_EXP_DATE
     */
    public Date getTO_BE_EXP_DATE() {
        return TO_BE_EXP_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S_SIGN_MODIF.TO_BE_EXP_DATE
     *
     * @param TO_BE_EXP_DATE the value for S_SIGN_MODIF.TO_BE_EXP_DATE
     */
    public void setTO_BE_EXP_DATE(Date TO_BE_EXP_DATE) {
        this.TO_BE_EXP_DATE = TO_BE_EXP_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S_SIGN_MODIF.TO_BE_DEFAULT_UNLIMITED
     *
     * @return the value of S_SIGN_MODIF.TO_BE_DEFAULT_UNLIMITED
     */
    public BigDecimal getTO_BE_DEFAULT_UNLIMITED() {
        return TO_BE_DEFAULT_UNLIMITED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S_SIGN_MODIF.TO_BE_DEFAULT_UNLIMITED
     *
     * @param TO_BE_DEFAULT_UNLIMITED the value for S_SIGN_MODIF.TO_BE_DEFAULT_UNLIMITED
     */
    public void setTO_BE_DEFAULT_UNLIMITED(BigDecimal TO_BE_DEFAULT_UNLIMITED) {
        this.TO_BE_DEFAULT_UNLIMITED = TO_BE_DEFAULT_UNLIMITED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S_SIGN_MODIF.TO_BE_ANNOTATION
     *
     * @return the value of S_SIGN_MODIF.TO_BE_ANNOTATION
     */
    public String getTO_BE_ANNOTATION() {
        return TO_BE_ANNOTATION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S_SIGN_MODIF.TO_BE_ANNOTATION
     *
     * @param TO_BE_ANNOTATION the value for S_SIGN_MODIF.TO_BE_ANNOTATION
     */
    public void setTO_BE_ANNOTATION(String TO_BE_ANNOTATION) {
        this.TO_BE_ANNOTATION = TO_BE_ANNOTATION == null ? null : TO_BE_ANNOTATION.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S_SIGN_MODIF.TO_BE_STATUS
     *
     * @return the value of S_SIGN_MODIF.TO_BE_STATUS
     */
    public String getTO_BE_STATUS() {
        return TO_BE_STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S_SIGN_MODIF.TO_BE_STATUS
     *
     * @param TO_BE_STATUS the value for S_SIGN_MODIF.TO_BE_STATUS
     */
    public void setTO_BE_STATUS(String TO_BE_STATUS) {
        this.TO_BE_STATUS = TO_BE_STATUS == null ? null : TO_BE_STATUS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S_SIGN_MODIF.TO_BE_AMOUNT_CY
     *
     * @return the value of S_SIGN_MODIF.TO_BE_AMOUNT_CY
     */
    public BigDecimal getTO_BE_AMOUNT_CY() {
        return TO_BE_AMOUNT_CY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S_SIGN_MODIF.TO_BE_AMOUNT_CY
     *
     * @param TO_BE_AMOUNT_CY the value for S_SIGN_MODIF.TO_BE_AMOUNT_CY
     */
    public void setTO_BE_AMOUNT_CY(BigDecimal TO_BE_AMOUNT_CY) {
        this.TO_BE_AMOUNT_CY = TO_BE_AMOUNT_CY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S_SIGN_MODIF.TO_BE_OBJECT_TYPE
     *
     * @return the value of S_SIGN_MODIF.TO_BE_OBJECT_TYPE
     */
    public String getTO_BE_OBJECT_TYPE() {
        return TO_BE_OBJECT_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S_SIGN_MODIF.TO_BE_OBJECT_TYPE
     *
     * @param TO_BE_OBJECT_TYPE the value for S_SIGN_MODIF.TO_BE_OBJECT_TYPE
     */
    public void setTO_BE_OBJECT_TYPE(String TO_BE_OBJECT_TYPE) {
        this.TO_BE_OBJECT_TYPE = TO_BE_OBJECT_TYPE == null ? null : TO_BE_OBJECT_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S_SIGN_MODIF.TO_BE_DATE_CREATED
     *
     * @return the value of S_SIGN_MODIF.TO_BE_DATE_CREATED
     */
    public Date getTO_BE_DATE_CREATED() {
        return TO_BE_DATE_CREATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S_SIGN_MODIF.TO_BE_DATE_CREATED
     *
     * @param TO_BE_DATE_CREATED the value for S_SIGN_MODIF.TO_BE_DATE_CREATED
     */
    public void setTO_BE_DATE_CREATED(Date TO_BE_DATE_CREATED) {
        this.TO_BE_DATE_CREATED = TO_BE_DATE_CREATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S_SIGN_MODIF.TO_BE_CREATED_BY
     *
     * @return the value of S_SIGN_MODIF.TO_BE_CREATED_BY
     */
    public String getTO_BE_CREATED_BY() {
        return TO_BE_CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S_SIGN_MODIF.TO_BE_CREATED_BY
     *
     * @param TO_BE_CREATED_BY the value for S_SIGN_MODIF.TO_BE_CREATED_BY
     */
    public void setTO_BE_CREATED_BY(String TO_BE_CREATED_BY) {
        this.TO_BE_CREATED_BY = TO_BE_CREATED_BY == null ? null : TO_BE_CREATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S_SIGN_MODIF.TO_BE_DATE_AUTHORISED
     *
     * @return the value of S_SIGN_MODIF.TO_BE_DATE_AUTHORISED
     */
    public Date getTO_BE_DATE_AUTHORISED() {
        return TO_BE_DATE_AUTHORISED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S_SIGN_MODIF.TO_BE_DATE_AUTHORISED
     *
     * @param TO_BE_DATE_AUTHORISED the value for S_SIGN_MODIF.TO_BE_DATE_AUTHORISED
     */
    public void setTO_BE_DATE_AUTHORISED(Date TO_BE_DATE_AUTHORISED) {
        this.TO_BE_DATE_AUTHORISED = TO_BE_DATE_AUTHORISED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S_SIGN_MODIF.TO_BE_AUTHORISED_BY
     *
     * @return the value of S_SIGN_MODIF.TO_BE_AUTHORISED_BY
     */
    public String getTO_BE_AUTHORISED_BY() {
        return TO_BE_AUTHORISED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S_SIGN_MODIF.TO_BE_AUTHORISED_BY
     *
     * @param TO_BE_AUTHORISED_BY the value for S_SIGN_MODIF.TO_BE_AUTHORISED_BY
     */
    public void setTO_BE_AUTHORISED_BY(String TO_BE_AUTHORISED_BY) {
        this.TO_BE_AUTHORISED_BY = TO_BE_AUTHORISED_BY == null ? null : TO_BE_AUTHORISED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S_SIGN_MODIF.TO_BE_SC_WIDTH
     *
     * @return the value of S_SIGN_MODIF.TO_BE_SC_WIDTH
     */
    public BigDecimal getTO_BE_SC_WIDTH() {
        return TO_BE_SC_WIDTH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S_SIGN_MODIF.TO_BE_SC_WIDTH
     *
     * @param TO_BE_SC_WIDTH the value for S_SIGN_MODIF.TO_BE_SC_WIDTH
     */
    public void setTO_BE_SC_WIDTH(BigDecimal TO_BE_SC_WIDTH) {
        this.TO_BE_SC_WIDTH = TO_BE_SC_WIDTH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S_SIGN_MODIF.TO_BE_SC_HEIGHT
     *
     * @return the value of S_SIGN_MODIF.TO_BE_SC_HEIGHT
     */
    public BigDecimal getTO_BE_SC_HEIGHT() {
        return TO_BE_SC_HEIGHT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S_SIGN_MODIF.TO_BE_SC_HEIGHT
     *
     * @param TO_BE_SC_HEIGHT the value for S_SIGN_MODIF.TO_BE_SC_HEIGHT
     */
    public void setTO_BE_SC_HEIGHT(BigDecimal TO_BE_SC_HEIGHT) {
        this.TO_BE_SC_HEIGHT = TO_BE_SC_HEIGHT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S_SIGN_MODIF.TO_BE_SC_FORMAT
     *
     * @return the value of S_SIGN_MODIF.TO_BE_SC_FORMAT
     */
    public String getTO_BE_SC_FORMAT() {
        return TO_BE_SC_FORMAT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S_SIGN_MODIF.TO_BE_SC_FORMAT
     *
     * @param TO_BE_SC_FORMAT the value for S_SIGN_MODIF.TO_BE_SC_FORMAT
     */
    public void setTO_BE_SC_FORMAT(String TO_BE_SC_FORMAT) {
        this.TO_BE_SC_FORMAT = TO_BE_SC_FORMAT == null ? null : TO_BE_SC_FORMAT.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S_SIGN_MODIF.TO_BE_DATE_DELETED
     *
     * @return the value of S_SIGN_MODIF.TO_BE_DATE_DELETED
     */
    public Date getTO_BE_DATE_DELETED() {
        return TO_BE_DATE_DELETED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S_SIGN_MODIF.TO_BE_DATE_DELETED
     *
     * @param TO_BE_DATE_DELETED the value for S_SIGN_MODIF.TO_BE_DATE_DELETED
     */
    public void setTO_BE_DATE_DELETED(Date TO_BE_DATE_DELETED) {
        this.TO_BE_DATE_DELETED = TO_BE_DATE_DELETED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S_SIGN_MODIF.TO_BE_DELETED_BY
     *
     * @return the value of S_SIGN_MODIF.TO_BE_DELETED_BY
     */
    public String getTO_BE_DELETED_BY() {
        return TO_BE_DELETED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S_SIGN_MODIF.TO_BE_DELETED_BY
     *
     * @param TO_BE_DELETED_BY the value for S_SIGN_MODIF.TO_BE_DELETED_BY
     */
    public void setTO_BE_DELETED_BY(String TO_BE_DELETED_BY) {
        this.TO_BE_DELETED_BY = TO_BE_DELETED_BY == null ? null : TO_BE_DELETED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S_SIGN_MODIF.ORIGIN_CODE
     *
     * @return the value of S_SIGN_MODIF.ORIGIN_CODE
     */
    public BigDecimal getORIGIN_CODE() {
        return ORIGIN_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S_SIGN_MODIF.ORIGIN_CODE
     *
     * @param ORIGIN_CODE the value for S_SIGN_MODIF.ORIGIN_CODE
     */
    public void setORIGIN_CODE(BigDecimal ORIGIN_CODE) {
        this.ORIGIN_CODE = ORIGIN_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S_SIGN_MODIF.ORIGIN_SEQ
     *
     * @return the value of S_SIGN_MODIF.ORIGIN_SEQ
     */
    public BigDecimal getORIGIN_SEQ() {
        return ORIGIN_SEQ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S_SIGN_MODIF.ORIGIN_SEQ
     *
     * @param ORIGIN_SEQ the value for S_SIGN_MODIF.ORIGIN_SEQ
     */
    public void setORIGIN_SEQ(BigDecimal ORIGIN_SEQ) {
        this.ORIGIN_SEQ = ORIGIN_SEQ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S_SIGN_MODIF.TO_BE_DATE_MODIFIED
     *
     * @return the value of S_SIGN_MODIF.TO_BE_DATE_MODIFIED
     */
    public Date getTO_BE_DATE_MODIFIED() {
        return TO_BE_DATE_MODIFIED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S_SIGN_MODIF.TO_BE_DATE_MODIFIED
     *
     * @param TO_BE_DATE_MODIFIED the value for S_SIGN_MODIF.TO_BE_DATE_MODIFIED
     */
    public void setTO_BE_DATE_MODIFIED(Date TO_BE_DATE_MODIFIED) {
        this.TO_BE_DATE_MODIFIED = TO_BE_DATE_MODIFIED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S_SIGN_MODIF.TO_BE_MODIFIED_BY
     *
     * @return the value of S_SIGN_MODIF.TO_BE_MODIFIED_BY
     */
    public String getTO_BE_MODIFIED_BY() {
        return TO_BE_MODIFIED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S_SIGN_MODIF.TO_BE_MODIFIED_BY
     *
     * @param TO_BE_MODIFIED_BY the value for S_SIGN_MODIF.TO_BE_MODIFIED_BY
     */
    public void setTO_BE_MODIFIED_BY(String TO_BE_MODIFIED_BY) {
        this.TO_BE_MODIFIED_BY = TO_BE_MODIFIED_BY == null ? null : TO_BE_MODIFIED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S_SIGN_MODIF.TO_BE_DEFAULT_PHOTO
     *
     * @return the value of S_SIGN_MODIF.TO_BE_DEFAULT_PHOTO
     */
    public BigDecimal getTO_BE_DEFAULT_PHOTO() {
        return TO_BE_DEFAULT_PHOTO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S_SIGN_MODIF.TO_BE_DEFAULT_PHOTO
     *
     * @param TO_BE_DEFAULT_PHOTO the value for S_SIGN_MODIF.TO_BE_DEFAULT_PHOTO
     */
    public void setTO_BE_DEFAULT_PHOTO(BigDecimal TO_BE_DEFAULT_PHOTO) {
        this.TO_BE_DEFAULT_PHOTO = TO_BE_DEFAULT_PHOTO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S_SIGN_MODIF.OLE_OBJECT
     *
     * @return the value of S_SIGN_MODIF.OLE_OBJECT
     */
    public byte[] getOLE_OBJECT() {
        return OLE_OBJECT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S_SIGN_MODIF.OLE_OBJECT
     *
     * @param OLE_OBJECT the value for S_SIGN_MODIF.OLE_OBJECT
     */
    public void setOLE_OBJECT(byte[] OLE_OBJECT) {
        this.OLE_OBJECT = OLE_OBJECT;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S_SIGN_MODIF.TO_BE_SIGN_INSTRUCTIONS
     *
     * @return the value of S_SIGN_MODIF.TO_BE_SIGN_INSTRUCTIONS
     */
    public String getTO_BE_SIGN_INSTRUCTIONS() {
        return TO_BE_SIGN_INSTRUCTIONS;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S_SIGN_MODIF.TO_BE_SIGN_INSTRUCTIONS
     *
     * @param TO_BE_SIGN_INSTRUCTIONS the value for S_SIGN_MODIF.TO_BE_SIGN_INSTRUCTIONS
     */
    public void setTO_BE_SIGN_INSTRUCTIONS(String TO_BE_SIGN_INSTRUCTIONS) {
        this.TO_BE_SIGN_INSTRUCTIONS = TO_BE_SIGN_INSTRUCTIONS == null ? null : TO_BE_SIGN_INSTRUCTIONS.trim();
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S_SIGN_MODIF.TO_BE_INST_OTHER_VALUE
     *
     * @return the value of S_SIGN_MODIF.TO_BE_INST_OTHER_VALUE
     */
    public String getTO_BE_INST_OTHER_VALUE() {
        return TO_BE_INST_OTHER_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S_SIGN_MODIF.TO_BE_INST_OTHER_VALUE
     *
     * @param TO_BE_INST_OTHER_VALUE the value for S_SIGN_MODIF.TO_BE_INST_OTHER_VALUE
     */
    public void setTO_BE_INST_OTHER_VALUE(String TO_BE_INST_OTHER_VALUE) {
        this.TO_BE_INST_OTHER_VALUE = TO_BE_INST_OTHER_VALUE == null ? null : TO_BE_INST_OTHER_VALUE.trim();
    }

    public BigDecimal getAUTH_CIF_NO()
    {
        return AUTH_CIF_NO;
    }

    public void setAUTH_CIF_NO(BigDecimal aUTH_CIF_NO)
    {
        AUTH_CIF_NO = aUTH_CIF_NO;
    }
    
    
    
    

}