package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class SERVICESVOKey extends BaseVO {
    /**
     * This field corresponds to the database column SERVICES.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column SERVICES.SERVICE_CODE
     */
    private BigDecimal SERVICE_CODE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SERVICES.COMP_CODE
     *
     * @return the value of SERVICES.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SERVICES.COMP_CODE
     *
     * @param COMP_CODE the value for SERVICES.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SERVICES.SERVICE_CODE
     *
     * @return the value of SERVICES.SERVICE_CODE
     */
    public BigDecimal getSERVICE_CODE() {
        return SERVICE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SERVICES.SERVICE_CODE
     *
     * @param SERVICE_CODE the value for SERVICES.SERVICE_CODE
     */
    public void setSERVICE_CODE(BigDecimal SERVICE_CODE) {
        this.SERVICE_CODE = SERVICE_CODE;
    }
}