package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class SERVICESVO extends SERVICESVOKey {
    /**
     * This field corresponds to the database column SERVICES.SERVICE_DESC
     */
    private String SERVICE_DESC;

    /**
     * This field corresponds to the database column SERVICES.SERVICE_TYPE
     */
    private BigDecimal SERVICE_TYPE;

    /**
     * This field corresponds to the database column SERVICES.MSG_SOURCE
     */
    private String MSG_SOURCE;

    /**
     * This field corresponds to the database column SERVICES.BANK_ATM
     */
    private String BANK_ATM;

    /**
     * This field corresponds to the database column SERVICES.ATM_T_ID
     */
    private String ATM_T_ID;

    /**
     * This field corresponds to the database column SERVICES.TRX_BR_CODE
     */
    private BigDecimal TRX_BR_CODE;

    /**
     * This field corresponds to the database column SERVICES.TELLER_ID
     */
    private BigDecimal TELLER_ID;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SERVICES.SERVICE_DESC
     *
     * @return the value of SERVICES.SERVICE_DESC
     */
    public String getSERVICE_DESC() {
        return SERVICE_DESC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SERVICES.SERVICE_DESC
     *
     * @param SERVICE_DESC the value for SERVICES.SERVICE_DESC
     */
    public void setSERVICE_DESC(String SERVICE_DESC) {
        this.SERVICE_DESC = SERVICE_DESC == null ? null : SERVICE_DESC.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SERVICES.SERVICE_TYPE
     *
     * @return the value of SERVICES.SERVICE_TYPE
     */
    public BigDecimal getSERVICE_TYPE() {
        return SERVICE_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SERVICES.SERVICE_TYPE
     *
     * @param SERVICE_TYPE the value for SERVICES.SERVICE_TYPE
     */
    public void setSERVICE_TYPE(BigDecimal SERVICE_TYPE) {
        this.SERVICE_TYPE = SERVICE_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SERVICES.MSG_SOURCE
     *
     * @return the value of SERVICES.MSG_SOURCE
     */
    public String getMSG_SOURCE() {
        return MSG_SOURCE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SERVICES.MSG_SOURCE
     *
     * @param MSG_SOURCE the value for SERVICES.MSG_SOURCE
     */
    public void setMSG_SOURCE(String MSG_SOURCE) {
        this.MSG_SOURCE = MSG_SOURCE == null ? null : MSG_SOURCE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SERVICES.BANK_ATM
     *
     * @return the value of SERVICES.BANK_ATM
     */
    public String getBANK_ATM() {
        return BANK_ATM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SERVICES.BANK_ATM
     *
     * @param BANK_ATM the value for SERVICES.BANK_ATM
     */
    public void setBANK_ATM(String BANK_ATM) {
        this.BANK_ATM = BANK_ATM == null ? null : BANK_ATM.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SERVICES.ATM_T_ID
     *
     * @return the value of SERVICES.ATM_T_ID
     */
    public String getATM_T_ID() {
        return ATM_T_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SERVICES.ATM_T_ID
     *
     * @param ATM_T_ID the value for SERVICES.ATM_T_ID
     */
    public void setATM_T_ID(String ATM_T_ID) {
        this.ATM_T_ID = ATM_T_ID == null ? null : ATM_T_ID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SERVICES.TRX_BR_CODE
     *
     * @return the value of SERVICES.TRX_BR_CODE
     */
    public BigDecimal getTRX_BR_CODE() {
        return TRX_BR_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SERVICES.TRX_BR_CODE
     *
     * @param TRX_BR_CODE the value for SERVICES.TRX_BR_CODE
     */
    public void setTRX_BR_CODE(BigDecimal TRX_BR_CODE) {
        this.TRX_BR_CODE = TRX_BR_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SERVICES.TELLER_ID
     *
     * @return the value of SERVICES.TELLER_ID
     */
    public BigDecimal getTELLER_ID() {
        return TELLER_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SERVICES.TELLER_ID
     *
     * @param TELLER_ID the value for SERVICES.TELLER_ID
     */
    public void setTELLER_ID(BigDecimal TELLER_ID) {
        this.TELLER_ID = TELLER_ID;
    }
}