package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class SIRON_BODATAVO extends BaseVO {
    /**
     * This field corresponds to the database column SIRON_BODATA.MAIN_CIF
     */
    private String MAIN_CIF;

    /**
     * This field corresponds to the database column SIRON_BODATA.CIF_REF
     */
    private String CIF_REF;

    /**
     * This field corresponds to the database column SIRON_BODATA.TYPE
     */
    private String TYPE;

    /**
     * This field corresponds to the database column SIRON_BODATA.SHAR_PERC
     */
    private BigDecimal SHAR_PERC;

    /**
     * This field corresponds to the database column SIRON_BODATA.FLAG1
     */
    private String FLAG1;

    /**
     * This field corresponds to the database column SIRON_BODATA.FLAG2
     */
    private String FLAG2;

    /**
     * This field corresponds to the database column SIRON_BODATA.FLAG3
     */
    private String FLAG3;

    /**
     * This field corresponds to the database column SIRON_BODATA.COMMENT
     */
    private String COMMENT;

    /**
     * This field corresponds to the database column SIRON_BODATA.DELETEFLAG
     */
    private String DELETEFLAG;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIRON_BODATA.MAIN_CIF
     *
     * @return the value of SIRON_BODATA.MAIN_CIF
     */
    public String getMAIN_CIF() {
        return MAIN_CIF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIRON_BODATA.MAIN_CIF
     *
     * @param MAIN_CIF the value for SIRON_BODATA.MAIN_CIF
     */
    public void setMAIN_CIF(String MAIN_CIF) {
        this.MAIN_CIF = MAIN_CIF == null ? null : MAIN_CIF.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIRON_BODATA.CIF_REF
     *
     * @return the value of SIRON_BODATA.CIF_REF
     */
    public String getCIF_REF() {
        return CIF_REF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIRON_BODATA.CIF_REF
     *
     * @param CIF_REF the value for SIRON_BODATA.CIF_REF
     */
    public void setCIF_REF(String CIF_REF) {
        this.CIF_REF = CIF_REF == null ? null : CIF_REF.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIRON_BODATA.TYPE
     *
     * @return the value of SIRON_BODATA.TYPE
     */
    public String getTYPE() {
        return TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIRON_BODATA.TYPE
     *
     * @param TYPE the value for SIRON_BODATA.TYPE
     */
    public void setTYPE(String TYPE) {
        this.TYPE = TYPE == null ? null : TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIRON_BODATA.SHAR_PERC
     *
     * @return the value of SIRON_BODATA.SHAR_PERC
     */
    public BigDecimal getSHAR_PERC() {
        return SHAR_PERC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIRON_BODATA.SHAR_PERC
     *
     * @param SHAR_PERC the value for SIRON_BODATA.SHAR_PERC
     */
    public void setSHAR_PERC(BigDecimal SHAR_PERC) {
        this.SHAR_PERC = SHAR_PERC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIRON_BODATA.FLAG1
     *
     * @return the value of SIRON_BODATA.FLAG1
     */
    public String getFLAG1() {
        return FLAG1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIRON_BODATA.FLAG1
     *
     * @param FLAG1 the value for SIRON_BODATA.FLAG1
     */
    public void setFLAG1(String FLAG1) {
        this.FLAG1 = FLAG1 == null ? null : FLAG1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIRON_BODATA.FLAG2
     *
     * @return the value of SIRON_BODATA.FLAG2
     */
    public String getFLAG2() {
        return FLAG2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIRON_BODATA.FLAG2
     *
     * @param FLAG2 the value for SIRON_BODATA.FLAG2
     */
    public void setFLAG2(String FLAG2) {
        this.FLAG2 = FLAG2 == null ? null : FLAG2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIRON_BODATA.FLAG3
     *
     * @return the value of SIRON_BODATA.FLAG3
     */
    public String getFLAG3() {
        return FLAG3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIRON_BODATA.FLAG3
     *
     * @param FLAG3 the value for SIRON_BODATA.FLAG3
     */
    public void setFLAG3(String FLAG3) {
        this.FLAG3 = FLAG3 == null ? null : FLAG3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIRON_BODATA.COMMENT
     *
     * @return the value of SIRON_BODATA.COMMENT
     */
    public String getCOMMENT() {
        return COMMENT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIRON_BODATA.COMMENT
     *
     * @param COMMENT the value for SIRON_BODATA.COMMENT
     */
    public void setCOMMENT(String COMMENT) {
        this.COMMENT = COMMENT == null ? null : COMMENT.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIRON_BODATA.DELETEFLAG
     *
     * @return the value of SIRON_BODATA.DELETEFLAG
     */
    public String getDELETEFLAG() {
        return DELETEFLAG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIRON_BODATA.DELETEFLAG
     *
     * @param DELETEFLAG the value for SIRON_BODATA.DELETEFLAG
     */
    public void setDELETEFLAG(String DELETEFLAG) {
        this.DELETEFLAG = DELETEFLAG == null ? null : DELETEFLAG.trim();
    }
}