package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class STF_COMMODITY_GRADEVOKey extends BaseVO {
    /**
     * This field corresponds to the database column STF_COMMODITY_GRADE.COMMODITY_GRADE_CODE
     */
    private BigDecimal COMMODITY_GRADE_CODE;

    /**
     * This field corresponds to the database column STF_COMMODITY_GRADE.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STF_COMMODITY_GRADE.COMMODITY_GRADE_CODE
     *
     * @return the value of STF_COMMODITY_GRADE.COMMODITY_GRADE_CODE
     */
    public BigDecimal getCOMMODITY_GRADE_CODE() {
        return COMMODITY_GRADE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STF_COMMODITY_GRADE.COMMODITY_GRADE_CODE
     *
     * @param COMMODITY_GRADE_CODE the value for STF_COMMODITY_GRADE.COMMODITY_GRADE_CODE
     */
    public void setCOMMODITY_GRADE_CODE(BigDecimal COMMODITY_GRADE_CODE) {
        this.COMMODITY_GRADE_CODE = COMMODITY_GRADE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STF_COMMODITY_GRADE.COMP_CODE
     *
     * @return the value of STF_COMMODITY_GRADE.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STF_COMMODITY_GRADE.COMP_CODE
     *
     * @param COMP_CODE the value for STF_COMMODITY_GRADE.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }
}