package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class SWIFT_CTRLVO extends SWIFT_CTRLVOKey {
    /**
     * This field corresponds to the database column SWIFT_CTRL.CIF_NO
     */
    private BigDecimal CIF_NO;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SWIFT_CTRL.CIF_NO
     *
     * @return the value of SWIFT_CTRL.CIF_NO
     */
    public BigDecimal getCIF_NO() {
        return CIF_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SWIFT_CTRL.CIF_NO
     *
     * @param CIF_NO the value for SWIFT_CTRL.CIF_NO
     */
    public void setCIF_NO(BigDecimal CIF_NO) {
        this.CIF_NO = CIF_NO;
    }
}