package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class SWIFT_DWS_CFVOKey extends BaseVO {
    /**
     * This field corresponds to the database column SWIFT_DWS_CF.ORDER_NO
     */
    private BigDecimal ORDER_NO;

    /**
     * This field corresponds to the database column SWIFT_DWS_CF.REP_ID
     */
    private BigDecimal REP_ID;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SWIFT_DWS_CF.ORDER_NO
     *
     * @return the value of SWIFT_DWS_CF.ORDER_NO
     */
    public BigDecimal getORDER_NO() {
        return ORDER_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SWIFT_DWS_CF.ORDER_NO
     *
     * @param ORDER_NO the value for SWIFT_DWS_CF.ORDER_NO
     */
    public void setORDER_NO(BigDecimal ORDER_NO) {
        this.ORDER_NO = ORDER_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SWIFT_DWS_CF.REP_ID
     *
     * @return the value of SWIFT_DWS_CF.REP_ID
     */
    public BigDecimal getREP_ID() {
        return REP_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SWIFT_DWS_CF.REP_ID
     *
     * @param REP_ID the value for SWIFT_DWS_CF.REP_ID
     */
    public void setREP_ID(BigDecimal REP_ID) {
        this.REP_ID = REP_ID;
    }
}