package com.path.dbmaps.vo;

public class SWIFT_MSG_REFVO extends SWIFT_MSG_REFVOKey {
    /**
     * This field corresponds to the database column SWIFT_MSG_REF.TAG
     */
    private String TAG;

    /**
     * This field corresponds to the database column SWIFT_MSG_REF.IN_OUT
     */
    private String IN_OUT;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SWIFT_MSG_REF.TAG
     *
     * @return the value of SWIFT_MSG_REF.TAG
     */
    public String getTAG() {
        return TAG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SWIFT_MSG_REF.TAG
     *
     * @param TAG the value for SWIFT_MSG_REF.TAG
     */
    public void setTAG(String TAG) {
        this.TAG = TAG == null ? null : TAG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SWIFT_MSG_REF.IN_OUT
     *
     * @return the value of SWIFT_MSG_REF.IN_OUT
     */
    public String getIN_OUT() {
        return IN_OUT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SWIFT_MSG_REF.IN_OUT
     *
     * @param IN_OUT the value for SWIFT_MSG_REF.IN_OUT
     */
    public void setIN_OUT(String IN_OUT) {
        this.IN_OUT = IN_OUT == null ? null : IN_OUT.trim();
    }
}