package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class SWIFT_CY_SETTINGSVOKey extends BaseVO {
    /**
     * This field corresponds to the database column SWIFT_CY_SETTINGS.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column SWIFT_CY_SETTINGS.CY_CODE
     */
    private BigDecimal CY_CODE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SWIFT_CY_SETTINGS.COMP_CODE
     *
     * @return the value of SWIFT_CY_SETTINGS.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SWIFT_CY_SETTINGS.COMP_CODE
     *
     * @param COMP_CODE the value for SWIFT_CY_SETTINGS.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SWIFT_CY_SETTINGS.CY_CODE
     *
     * @return the value of SWIFT_CY_SETTINGS.CY_CODE
     */
    public BigDecimal getCY_CODE() {
        return CY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SWIFT_CY_SETTINGS.CY_CODE
     *
     * @param CY_CODE the value for SWIFT_CY_SETTINGS.CY_CODE
     */
    public void setCY_CODE(BigDecimal CY_CODE) {
        this.CY_CODE = CY_CODE;
    }
}