package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class SWIFT_MSGDETVOKey extends BaseVO {
    /**
     * This field corresponds to the database column SWIFT_MSGDET.LINE_NO
     */
    private BigDecimal LINE_NO;

    /**
     * This field corresponds to the database column SWIFT_MSGDET.MESSAGE_ORDER
     */
    private BigDecimal MESSAGE_ORDER;

    /**
     * This field corresponds to the database column SWIFT_MSGDET.MODULE
     */
    private String MODULE;

    /**
     * This field corresponds to the database column SWIFT_MSGDET.MSG_CODE
     */
    private String MSG_CODE;

    /**
     * This field corresponds to the database column SWIFT_MSGDET.TRX_TYPE
     */
    private String TRX_TYPE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SWIFT_MSGDET.LINE_NO
     *
     * @return the value of SWIFT_MSGDET.LINE_NO
     */
    public BigDecimal getLINE_NO() {
        return LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SWIFT_MSGDET.LINE_NO
     *
     * @param LINE_NO the value for SWIFT_MSGDET.LINE_NO
     */
    public void setLINE_NO(BigDecimal LINE_NO) {
        this.LINE_NO = LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SWIFT_MSGDET.MESSAGE_ORDER
     *
     * @return the value of SWIFT_MSGDET.MESSAGE_ORDER
     */
    public BigDecimal getMESSAGE_ORDER() {
        return MESSAGE_ORDER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SWIFT_MSGDET.MESSAGE_ORDER
     *
     * @param MESSAGE_ORDER the value for SWIFT_MSGDET.MESSAGE_ORDER
     */
    public void setMESSAGE_ORDER(BigDecimal MESSAGE_ORDER) {
        this.MESSAGE_ORDER = MESSAGE_ORDER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SWIFT_MSGDET.MODULE
     *
     * @return the value of SWIFT_MSGDET.MODULE
     */
    public String getMODULE() {
        return MODULE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SWIFT_MSGDET.MODULE
     *
     * @param MODULE the value for SWIFT_MSGDET.MODULE
     */
    public void setMODULE(String MODULE) {
        this.MODULE = MODULE == null ? null : MODULE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SWIFT_MSGDET.MSG_CODE
     *
     * @return the value of SWIFT_MSGDET.MSG_CODE
     */
    public String getMSG_CODE() {
        return MSG_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SWIFT_MSGDET.MSG_CODE
     *
     * @param MSG_CODE the value for SWIFT_MSGDET.MSG_CODE
     */
    public void setMSG_CODE(String MSG_CODE) {
        this.MSG_CODE = MSG_CODE == null ? null : MSG_CODE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SWIFT_MSGDET.TRX_TYPE
     *
     * @return the value of SWIFT_MSGDET.TRX_TYPE
     */
    public String getTRX_TYPE() {
        return TRX_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SWIFT_MSGDET.TRX_TYPE
     *
     * @param TRX_TYPE the value for SWIFT_MSGDET.TRX_TYPE
     */
    public void setTRX_TYPE(String TRX_TYPE) {
        this.TRX_TYPE = TRX_TYPE == null ? null : TRX_TYPE.trim();
    }
}