package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class SWIFT_CUT_OFFVOKey extends BaseVO {
    /**
     * This field corresponds to the database column SWIFT_CUT_OFF.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column SWIFT_CUT_OFF.COUNTRY_CODE
     */
    private BigDecimal COUNTRY_CODE;

    /**
     * This field corresponds to the database column SWIFT_CUT_OFF.CY_CODE
     */
    private BigDecimal CY_CODE;

    /**
     * This field corresponds to the database column SWIFT_CUT_OFF.MODULE
     */
    private String MODULE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SWIFT_CUT_OFF.COMP_CODE
     *
     * @return the value of SWIFT_CUT_OFF.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SWIFT_CUT_OFF.COMP_CODE
     *
     * @param COMP_CODE the value for SWIFT_CUT_OFF.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SWIFT_CUT_OFF.COUNTRY_CODE
     *
     * @return the value of SWIFT_CUT_OFF.COUNTRY_CODE
     */
    public BigDecimal getCOUNTRY_CODE() {
        return COUNTRY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SWIFT_CUT_OFF.COUNTRY_CODE
     *
     * @param COUNTRY_CODE the value for SWIFT_CUT_OFF.COUNTRY_CODE
     */
    public void setCOUNTRY_CODE(BigDecimal COUNTRY_CODE) {
        this.COUNTRY_CODE = COUNTRY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SWIFT_CUT_OFF.CY_CODE
     *
     * @return the value of SWIFT_CUT_OFF.CY_CODE
     */
    public BigDecimal getCY_CODE() {
        return CY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SWIFT_CUT_OFF.CY_CODE
     *
     * @param CY_CODE the value for SWIFT_CUT_OFF.CY_CODE
     */
    public void setCY_CODE(BigDecimal CY_CODE) {
        this.CY_CODE = CY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SWIFT_CUT_OFF.MODULE
     *
     * @return the value of SWIFT_CUT_OFF.MODULE
     */
    public String getMODULE() {
        return MODULE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SWIFT_CUT_OFF.MODULE
     *
     * @param MODULE the value for SWIFT_CUT_OFF.MODULE
     */
    public void setMODULE(String MODULE) {
        this.MODULE = MODULE == null ? null : MODULE.trim();
    }
}