package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;
import java.util.Date;

public class SWIFT_LOGVO extends BaseVO {
    /**
     * This field corresponds to the database column SWIFT_LOG.REPID
     */
    private BigDecimal REPID;

    /**
     * This field corresponds to the database column SWIFT_LOG.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column SWIFT_LOG.TITLE
     */
    private String TITLE;

    /**
     * This field corresponds to the database column SWIFT_LOG.SEVERITY
     */
    private String SEVERITY;

    /**
     * This field corresponds to the database column SWIFT_LOG.LOG_DATE
     */
    private Date LOG_DATE;

    /**
     * This field corresponds to the database column SWIFT_LOG.MSG
     */
    private String MSG;

    private String FILE_NAME;
    public String getFILE_NAME() 
    {
		return FILE_NAME;
	}
	public void setFILE_NAME(String fILE_NAME) 
	{
		FILE_NAME = fILE_NAME;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SWIFT_LOG.REPID
     *
     * @return the value of SWIFT_LOG.REPID
     */
    public BigDecimal getREPID() {
        return REPID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SWIFT_LOG.REPID
     *
     * @param REPID the value for SWIFT_LOG.REPID
     */
    public void setREPID(BigDecimal REPID) {
        this.REPID = REPID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SWIFT_LOG.COMP_CODE
     *
     * @return the value of SWIFT_LOG.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SWIFT_LOG.COMP_CODE
     *
     * @param COMP_CODE the value for SWIFT_LOG.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SWIFT_LOG.TITLE
     *
     * @return the value of SWIFT_LOG.TITLE
     */
    public String getTITLE() {
        return TITLE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SWIFT_LOG.TITLE
     *
     * @param TITLE the value for SWIFT_LOG.TITLE
     */
    public void setTITLE(String TITLE) {
        this.TITLE = TITLE == null ? null : TITLE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SWIFT_LOG.SEVERITY
     *
     * @return the value of SWIFT_LOG.SEVERITY
     */
    public String getSEVERITY() {
        return SEVERITY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SWIFT_LOG.SEVERITY
     *
     * @param SEVERITY the value for SWIFT_LOG.SEVERITY
     */
    public void setSEVERITY(String SEVERITY) {
        this.SEVERITY = SEVERITY == null ? null : SEVERITY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SWIFT_LOG.LOG_DATE
     *
     * @return the value of SWIFT_LOG.LOG_DATE
     */
    public Date getLOG_DATE() {
        return LOG_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SWIFT_LOG.LOG_DATE
     *
     * @param LOG_DATE the value for SWIFT_LOG.LOG_DATE
     */
    public void setLOG_DATE(Date LOG_DATE) {
        this.LOG_DATE = LOG_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SWIFT_LOG.MSG
     *
     * @return the value of SWIFT_LOG.MSG
     */
    public String getMSG() {
        return MSG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SWIFT_LOG.MSG
     *
     * @param MSG the value for SWIFT_LOG.MSG
     */
    public void setMSG(String MSG) {
        this.MSG = MSG == null ? null : MSG.trim();
    }
}