package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class SWIFT_REPORTSVO extends BaseVO {
    /**
     * This field corresponds to the database column SWIFT_REPORTS.REP_ID
     */
    private BigDecimal REP_ID;

    /**
     * This field corresponds to the database column SWIFT_REPORTS.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column SWIFT_REPORTS.BRANCH_CODE
     */
    private BigDecimal BRANCH_CODE;

    /**
     * This field corresponds to the database column SWIFT_REPORTS.REP_TITLE
     */
    private String REP_TITLE;

    /**
     * This field corresponds to the database column SWIFT_REPORTS.REP_OBJ_NAME
     */
    private String REP_OBJ_NAME;

    /**
     * This field corresponds to the database column SWIFT_REPORTS.APP_NAME
     */
    private String APP_NAME;

    /**
     * This field corresponds to the database column SWIFT_REPORTS.USER_ID
     */
    private String USER_ID;

    /**
     * This field corresponds to the database column SWIFT_REPORTS.QUERY_TYPE
     */
    private String QUERY_TYPE;

    /**
     * This field corresponds to the database column SWIFT_REPORTS.REP_SQL
     */
    private String REP_SQL;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SWIFT_REPORTS.REP_ID
     *
     * @return the value of SWIFT_REPORTS.REP_ID
     */
    public BigDecimal getREP_ID() {
        return REP_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SWIFT_REPORTS.REP_ID
     *
     * @param REP_ID the value for SWIFT_REPORTS.REP_ID
     */
    public void setREP_ID(BigDecimal REP_ID) {
        this.REP_ID = REP_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SWIFT_REPORTS.COMP_CODE
     *
     * @return the value of SWIFT_REPORTS.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SWIFT_REPORTS.COMP_CODE
     *
     * @param COMP_CODE the value for SWIFT_REPORTS.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SWIFT_REPORTS.BRANCH_CODE
     *
     * @return the value of SWIFT_REPORTS.BRANCH_CODE
     */
    public BigDecimal getBRANCH_CODE() {
        return BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SWIFT_REPORTS.BRANCH_CODE
     *
     * @param BRANCH_CODE the value for SWIFT_REPORTS.BRANCH_CODE
     */
    public void setBRANCH_CODE(BigDecimal BRANCH_CODE) {
        this.BRANCH_CODE = BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SWIFT_REPORTS.REP_TITLE
     *
     * @return the value of SWIFT_REPORTS.REP_TITLE
     */
    public String getREP_TITLE() {
        return REP_TITLE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SWIFT_REPORTS.REP_TITLE
     *
     * @param REP_TITLE the value for SWIFT_REPORTS.REP_TITLE
     */
    public void setREP_TITLE(String REP_TITLE) {
        this.REP_TITLE = REP_TITLE == null ? null : REP_TITLE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SWIFT_REPORTS.REP_OBJ_NAME
     *
     * @return the value of SWIFT_REPORTS.REP_OBJ_NAME
     */
    public String getREP_OBJ_NAME() {
        return REP_OBJ_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SWIFT_REPORTS.REP_OBJ_NAME
     *
     * @param REP_OBJ_NAME the value for SWIFT_REPORTS.REP_OBJ_NAME
     */
    public void setREP_OBJ_NAME(String REP_OBJ_NAME) {
        this.REP_OBJ_NAME = REP_OBJ_NAME == null ? null : REP_OBJ_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SWIFT_REPORTS.APP_NAME
     *
     * @return the value of SWIFT_REPORTS.APP_NAME
     */
    public String getAPP_NAME() {
        return APP_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SWIFT_REPORTS.APP_NAME
     *
     * @param APP_NAME the value for SWIFT_REPORTS.APP_NAME
     */
    public void setAPP_NAME(String APP_NAME) {
        this.APP_NAME = APP_NAME == null ? null : APP_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SWIFT_REPORTS.USER_ID
     *
     * @return the value of SWIFT_REPORTS.USER_ID
     */
    public String getUSER_ID() {
        return USER_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SWIFT_REPORTS.USER_ID
     *
     * @param USER_ID the value for SWIFT_REPORTS.USER_ID
     */
    public void setUSER_ID(String USER_ID) {
        this.USER_ID = USER_ID == null ? null : USER_ID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SWIFT_REPORTS.QUERY_TYPE
     *
     * @return the value of SWIFT_REPORTS.QUERY_TYPE
     */
    public String getQUERY_TYPE() {
        return QUERY_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SWIFT_REPORTS.QUERY_TYPE
     *
     * @param QUERY_TYPE the value for SWIFT_REPORTS.QUERY_TYPE
     */
    public void setQUERY_TYPE(String QUERY_TYPE) {
        this.QUERY_TYPE = QUERY_TYPE == null ? null : QUERY_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SWIFT_REPORTS.REP_SQL
     *
     * @return the value of SWIFT_REPORTS.REP_SQL
     */
    public String getREP_SQL() {
        return REP_SQL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SWIFT_REPORTS.REP_SQL
     *
     * @param REP_SQL the value for SWIFT_REPORTS.REP_SQL
     */
    public void setREP_SQL(String REP_SQL) {
        this.REP_SQL = REP_SQL == null ? null : REP_SQL.trim();
    }
}