package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class SWIFT_DWSCHEDVOKey extends BaseVO {
    /**
     * This field corresponds to the database column SWIFT_DWSCHED.MODULE
     */
    private String MODULE;

    /**
     * This field corresponds to the database column SWIFT_DWSCHED.REP_ID
     */
    private BigDecimal REP_ID;

    /**
     * This field corresponds to the database column SWIFT_DWSCHED.SCHED_ID
     */
    private BigDecimal SCHED_ID;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SWIFT_DWSCHED.MODULE
     *
     * @return the value of SWIFT_DWSCHED.MODULE
     */
    public String getMODULE() {
        return MODULE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SWIFT_DWSCHED.MODULE
     *
     * @param MODULE the value for SWIFT_DWSCHED.MODULE
     */
    public void setMODULE(String MODULE) {
        this.MODULE = MODULE == null ? null : MODULE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SWIFT_DWSCHED.REP_ID
     *
     * @return the value of SWIFT_DWSCHED.REP_ID
     */
    public BigDecimal getREP_ID() {
        return REP_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SWIFT_DWSCHED.REP_ID
     *
     * @param REP_ID the value for SWIFT_DWSCHED.REP_ID
     */
    public void setREP_ID(BigDecimal REP_ID) {
        this.REP_ID = REP_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SWIFT_DWSCHED.SCHED_ID
     *
     * @return the value of SWIFT_DWSCHED.SCHED_ID
     */
    public BigDecimal getSCHED_ID() {
        return SCHED_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SWIFT_DWSCHED.SCHED_ID
     *
     * @param SCHED_ID the value for SWIFT_DWSCHED.SCHED_ID
     */
    public void setSCHED_ID(BigDecimal SCHED_ID) {
        this.SCHED_ID = SCHED_ID;
    }
}