package com.path.dbmaps.vo;

public class SWIFT_INFOVO extends SWIFT_INFOVOKey {
    /**
     * This field corresponds to the database column SWIFT_INFO.SEND_TO_RECEIVER
     */
    private String SEND_TO_RECEIVER;

    /**
     * This field corresponds to the database column SWIFT_INFO.SHOW_TEXT
     */
    private String SHOW_TEXT;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SWIFT_INFO.SEND_TO_RECEIVER
     *
     * @return the value of SWIFT_INFO.SEND_TO_RECEIVER
     */
    public String getSEND_TO_RECEIVER() {
        return SEND_TO_RECEIVER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SWIFT_INFO.SEND_TO_RECEIVER
     *
     * @param SEND_TO_RECEIVER the value for SWIFT_INFO.SEND_TO_RECEIVER
     */
    public void setSEND_TO_RECEIVER(String SEND_TO_RECEIVER) {
        this.SEND_TO_RECEIVER = SEND_TO_RECEIVER == null ? null : SEND_TO_RECEIVER.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SWIFT_INFO.SHOW_TEXT
     *
     * @return the value of SWIFT_INFO.SHOW_TEXT
     */
    public String getSHOW_TEXT() {
        return SHOW_TEXT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SWIFT_INFO.SHOW_TEXT
     *
     * @param SHOW_TEXT the value for SWIFT_INFO.SHOW_TEXT
     */
    public void setSHOW_TEXT(String SHOW_TEXT) {
        this.SHOW_TEXT = SHOW_TEXT == null ? null : SHOW_TEXT.trim();
    }
}