package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class SWIFT_REPORTS_DETVO extends BaseVO {
    /**
     * This field corresponds to the database column SWIFT_REPORTS_DET.COL_NAME
     */
    private String COL_NAME;

    /**
     * This field corresponds to the database column SWIFT_REPORTS_DET.REP_ID
     */
    private BigDecimal REP_ID;

    /**
     * This field corresponds to the database column SWIFT_REPORTS_DET.LINE_NO
     */
    private BigDecimal LINE_NO;

    /**
     * This field corresponds to the database column SWIFT_REPORTS_DET.COL_EXP
     */
    private String COL_EXP;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SWIFT_REPORTS_DET.COL_NAME
     *
     * @return the value of SWIFT_REPORTS_DET.COL_NAME
     */
    public String getCOL_NAME() {
        return COL_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SWIFT_REPORTS_DET.COL_NAME
     *
     * @param COL_NAME the value for SWIFT_REPORTS_DET.COL_NAME
     */
    public void setCOL_NAME(String COL_NAME) {
        this.COL_NAME = COL_NAME == null ? null : COL_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SWIFT_REPORTS_DET.REP_ID
     *
     * @return the value of SWIFT_REPORTS_DET.REP_ID
     */
    public BigDecimal getREP_ID() {
        return REP_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SWIFT_REPORTS_DET.REP_ID
     *
     * @param REP_ID the value for SWIFT_REPORTS_DET.REP_ID
     */
    public void setREP_ID(BigDecimal REP_ID) {
        this.REP_ID = REP_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SWIFT_REPORTS_DET.LINE_NO
     *
     * @return the value of SWIFT_REPORTS_DET.LINE_NO
     */
    public BigDecimal getLINE_NO() {
        return LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SWIFT_REPORTS_DET.LINE_NO
     *
     * @param LINE_NO the value for SWIFT_REPORTS_DET.LINE_NO
     */
    public void setLINE_NO(BigDecimal LINE_NO) {
        this.LINE_NO = LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SWIFT_REPORTS_DET.COL_EXP
     *
     * @return the value of SWIFT_REPORTS_DET.COL_EXP
     */
    public String getCOL_EXP() {
        return COL_EXP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SWIFT_REPORTS_DET.COL_EXP
     *
     * @param COL_EXP the value for SWIFT_REPORTS_DET.COL_EXP
     */
    public void setCOL_EXP(String COL_EXP) {
        this.COL_EXP = COL_EXP == null ? null : COL_EXP.trim();
    }
}