package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class SWIFT_DWSVO extends BaseVO {
    /**
     * This field corresponds to the database column SWIFT_DWS.REP_ID
     */
    private BigDecimal REP_ID;

    /**
     * This field corresponds to the database column SWIFT_DWS.MODULE
     */
    private String MODULE;

    /**
     * This field corresponds to the database column SWIFT_DWS.SUSPENDED
     */
    private String SUSPENDED;

    /**
     * This field corresponds to the database column SWIFT_DWS.STAT_ACC
     */
    private BigDecimal STAT_ACC;

    /**
     * This field corresponds to the database column SWIFT_DWS.UPDATE_STMT
     */
    private String UPDATE_STMT;

    /**
     * This field corresponds to the database column SWIFT_DWS.SKIP_COND
     */
    private String SKIP_COND;

    /**
     * This field corresponds to the database column SWIFT_DWS.ERROR_COND
     */
    private String ERROR_COND;
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SWIFT_DWS.REP_ID
     *
     * @return the value of SWIFT_DWS.REP_ID
     */
    public BigDecimal getREP_ID() {
        return REP_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SWIFT_DWS.REP_ID
     *
     * @param REP_ID the value for SWIFT_DWS.REP_ID
     */
    public void setREP_ID(BigDecimal REP_ID) {
        this.REP_ID = REP_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SWIFT_DWS.MODULE
     *
     * @return the value of SWIFT_DWS.MODULE
     */
    public String getMODULE() {
        return MODULE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SWIFT_DWS.MODULE
     *
     * @param MODULE the value for SWIFT_DWS.MODULE
     */
    public void setMODULE(String MODULE) {
        this.MODULE = MODULE == null ? null : MODULE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SWIFT_DWS.SUSPENDED
     *
     * @return the value of SWIFT_DWS.SUSPENDED
     */
    public String getSUSPENDED() {
        return SUSPENDED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SWIFT_DWS.SUSPENDED
     *
     * @param SUSPENDED the value for SWIFT_DWS.SUSPENDED
     */
    public void setSUSPENDED(String SUSPENDED) {
        this.SUSPENDED = SUSPENDED == null ? null : SUSPENDED.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SWIFT_DWS.STAT_ACC
     *
     * @return the value of SWIFT_DWS.STAT_ACC
     */
    public BigDecimal getSTAT_ACC() {
        return STAT_ACC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SWIFT_DWS.STAT_ACC
     *
     * @param STAT_ACC the value for SWIFT_DWS.STAT_ACC
     */
    public void setSTAT_ACC(BigDecimal STAT_ACC) {
        this.STAT_ACC = STAT_ACC;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SWIFT_DWS.UPDATE_STMT
     *
     * @return the value of SWIFT_DWS.UPDATE_STMT
     */
    public String getUPDATE_STMT() {
        return UPDATE_STMT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SWIFT_DWS.UPDATE_STMT
     *
     * @param UPDATE_STMT the value for SWIFT_DWS.UPDATE_STMT
     */
    public void setUPDATE_STMT(String UPDATE_STMT) {
        this.UPDATE_STMT = UPDATE_STMT == null ? null : UPDATE_STMT.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SWIFT_DWS.SKIP_COND
     *
     * @return the value of SWIFT_DWS.SKIP_COND
     */
    public String getSKIP_COND() {
        return SKIP_COND;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SWIFT_DWS.SKIP_COND
     *
     * @param SKIP_COND the value for SWIFT_DWS.SKIP_COND
     */
    public void setSKIP_COND(String SKIP_COND) {
        this.SKIP_COND = SKIP_COND == null ? null : SKIP_COND.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SWIFT_DWS.ERROR_COND
     *
     * @return the value of SWIFT_DWS.ERROR_COND
     */
    public String getERROR_COND() {
        return ERROR_COND;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SWIFT_DWS.ERROR_COND
     *
     * @param ERROR_COND the value for SWIFT_DWS.ERROR_COND
     */
    public void setERROR_COND(String ERROR_COND) {
        this.ERROR_COND = ERROR_COND == null ? null : ERROR_COND.trim();
    }    
}