package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class SYNC_RET_SIRON_RISKSVO extends BaseVO {  
    /**
     * This field corresponds to the database column SYNC_RET_SIRON_RISKS.ID
     */
    private BigDecimal ID;

    /**
     * This field corresponds to the database column SYNC_RET_SIRON_RISKS.LINE_NO
     */
    private BigDecimal LINE_NO;

    /**
     * This field corresponds to the database column SYNC_RET_SIRON_RISKS.RISK_ABBREV
     */
    private String RISK_ABBREV;

    /**
     * This field corresponds to the database column SYNC_RET_SIRON_RISKS.RISK_CLASS
     */
    private String RISK_CLASS;

    /**
     * This field corresponds to the database column SYNC_RET_SIRON_RISKS.RISK_CLASS_SPECIFIED_YN
     */
    private String RISK_CLASS_SPECIFIED_YN;

    /**
     * This field corresponds to the database column SYNC_RET_SIRON_RISKS.RISK_DESC
     */
    private String RISK_DESC;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_RET_SIRON_RISKS.ID
     *
     * @return the value of SYNC_RET_SIRON_RISKS.ID
     */
    public BigDecimal getID() {
        return ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_RET_SIRON_RISKS.ID
     *
     * @param ID the value for SYNC_RET_SIRON_RISKS.ID
     */
    public void setID(BigDecimal ID) {
        this.ID = ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_RET_SIRON_RISKS.LINE_NO
     *
     * @return the value of SYNC_RET_SIRON_RISKS.LINE_NO
     */
    public BigDecimal getLINE_NO() {
        return LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_RET_SIRON_RISKS.LINE_NO
     *
     * @param LINE_NO the value for SYNC_RET_SIRON_RISKS.LINE_NO
     */
    public void setLINE_NO(BigDecimal LINE_NO) {
        this.LINE_NO = LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_RET_SIRON_RISKS.RISK_ABBREV
     *
     * @return the value of SYNC_RET_SIRON_RISKS.RISK_ABBREV
     */
    public String getRISK_ABBREV() {
        return RISK_ABBREV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_RET_SIRON_RISKS.RISK_ABBREV
     *
     * @param RISK_ABBREV the value for SYNC_RET_SIRON_RISKS.RISK_ABBREV
     */
    public void setRISK_ABBREV(String RISK_ABBREV) {
        this.RISK_ABBREV = RISK_ABBREV == null ? null : RISK_ABBREV.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_RET_SIRON_RISKS.RISK_CLASS
     *
     * @return the value of SYNC_RET_SIRON_RISKS.RISK_CLASS
     */
    public String getRISK_CLASS() {
        return RISK_CLASS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_RET_SIRON_RISKS.RISK_CLASS
     *
     * @param RISK_CLASS the value for SYNC_RET_SIRON_RISKS.RISK_CLASS
     */
    public void setRISK_CLASS(String RISK_CLASS) {
        this.RISK_CLASS = RISK_CLASS == null ? null : RISK_CLASS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_RET_SIRON_RISKS.RISK_CLASS_SPECIFIED_YN
     *
     * @return the value of SYNC_RET_SIRON_RISKS.RISK_CLASS_SPECIFIED_YN
     */
    public String getRISK_CLASS_SPECIFIED_YN() {
        return RISK_CLASS_SPECIFIED_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_RET_SIRON_RISKS.RISK_CLASS_SPECIFIED_YN
     *
     * @param RISK_CLASS_SPECIFIED_YN the value for SYNC_RET_SIRON_RISKS.RISK_CLASS_SPECIFIED_YN
     */
    public void setRISK_CLASS_SPECIFIED_YN(String RISK_CLASS_SPECIFIED_YN) {
        this.RISK_CLASS_SPECIFIED_YN = RISK_CLASS_SPECIFIED_YN == null ? null : RISK_CLASS_SPECIFIED_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYNC_RET_SIRON_RISKS.RISK_DESC
     *
     * @return the value of SYNC_RET_SIRON_RISKS.RISK_DESC
     */
    public String getRISK_DESC() {
        return RISK_DESC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYNC_RET_SIRON_RISKS.RISK_DESC
     *
     * @param RISK_DESC the value for SYNC_RET_SIRON_RISKS.RISK_DESC
     */
    public void setRISK_DESC(String RISK_DESC) {
        this.RISK_DESC = RISK_DESC == null ? null : RISK_DESC.trim();
    }
}