package com.path.dbmaps.vo;

import java.util.Date;

public class SYS_PARAM_SCREEN_DEFINITIONVO extends SYS_PARAM_SCREEN_DEFINITIONVOKey {
    /**
     * This field corresponds to the database column SYS_PARAM_SCREEN_DEFINITION.APP_NAME
     */
    private String APP_NAME;

    /**
     * This field corresponds to the database column SYS_PARAM_SCREEN_DEFINITION.PROG_REF
     */
    private String PROG_REF;

    /**
     * This field corresponds to the database column SYS_PARAM_SCREEN_DEFINITION.SCREEN_DESC
     */
    private String SCREEN_DESC;

    /**
     * This field corresponds to the database column SYS_PARAM_SCREEN_DEFINITION.SCREEN_DESC_VALUE_CODE
     */
    private String SCREEN_DESC_VALUE_CODE;

    /**
     * This field corresponds to the database column SYS_PARAM_SCREEN_DEFINITION.URL
     */
    private String URL;

    /**
     * This field corresponds to the database column SYS_PARAM_SCREEN_DEFINITION.CREATED_BY
     */
    private String CREATED_BY;

    /**
     * This field corresponds to the database column SYS_PARAM_SCREEN_DEFINITION.CREATED_DATE
     */
    private Date CREATED_DATE;

    /**
     * This field corresponds to the database column SYS_PARAM_SCREEN_DEFINITION.MODIFIED_BY
     */
    private String MODIFIED_BY;

    /**
     * This field corresponds to the database column SYS_PARAM_SCREEN_DEFINITION.MODIFIED_DATE
     */
    private Date MODIFIED_DATE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_SCREEN_DEFINITION.APP_NAME
     *
     * @return the value of SYS_PARAM_SCREEN_DEFINITION.APP_NAME
     */
    public String getAPP_NAME() {
        return APP_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_SCREEN_DEFINITION.APP_NAME
     *
     * @param APP_NAME the value for SYS_PARAM_SCREEN_DEFINITION.APP_NAME
     */
    public void setAPP_NAME(String APP_NAME) {
        this.APP_NAME = APP_NAME == null ? null : APP_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_SCREEN_DEFINITION.PROG_REF
     *
     * @return the value of SYS_PARAM_SCREEN_DEFINITION.PROG_REF
     */
    public String getPROG_REF() {
        return PROG_REF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_SCREEN_DEFINITION.PROG_REF
     *
     * @param PROG_REF the value for SYS_PARAM_SCREEN_DEFINITION.PROG_REF
     */
    public void setPROG_REF(String PROG_REF) {
        this.PROG_REF = PROG_REF == null ? null : PROG_REF.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_SCREEN_DEFINITION.SCREEN_DESC
     *
     * @return the value of SYS_PARAM_SCREEN_DEFINITION.SCREEN_DESC
     */
    public String getSCREEN_DESC() {
        return SCREEN_DESC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_SCREEN_DEFINITION.SCREEN_DESC
     *
     * @param SCREEN_DESC the value for SYS_PARAM_SCREEN_DEFINITION.SCREEN_DESC
     */
    public void setSCREEN_DESC(String SCREEN_DESC) {
        this.SCREEN_DESC = SCREEN_DESC == null ? null : SCREEN_DESC.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_SCREEN_DEFINITION.SCREEN_DESC_VALUE_CODE
     *
     * @return the value of SYS_PARAM_SCREEN_DEFINITION.SCREEN_DESC_VALUE_CODE
     */
    public String getSCREEN_DESC_VALUE_CODE() {
        return SCREEN_DESC_VALUE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_SCREEN_DEFINITION.SCREEN_DESC_VALUE_CODE
     *
     * @param SCREEN_DESC_VALUE_CODE the value for SYS_PARAM_SCREEN_DEFINITION.SCREEN_DESC_VALUE_CODE
     */
    public void setSCREEN_DESC_VALUE_CODE(String SCREEN_DESC_VALUE_CODE) {
        this.SCREEN_DESC_VALUE_CODE = SCREEN_DESC_VALUE_CODE == null ? null : SCREEN_DESC_VALUE_CODE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_SCREEN_DEFINITION.URL
     *
     * @return the value of SYS_PARAM_SCREEN_DEFINITION.URL
     */
    public String getURL() {
        return URL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_SCREEN_DEFINITION.URL
     *
     * @param URL the value for SYS_PARAM_SCREEN_DEFINITION.URL
     */
    public void setURL(String URL) {
        this.URL = URL == null ? null : URL.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_SCREEN_DEFINITION.CREATED_BY
     *
     * @return the value of SYS_PARAM_SCREEN_DEFINITION.CREATED_BY
     */
    public String getCREATED_BY() {
        return CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_SCREEN_DEFINITION.CREATED_BY
     *
     * @param CREATED_BY the value for SYS_PARAM_SCREEN_DEFINITION.CREATED_BY
     */
    public void setCREATED_BY(String CREATED_BY) {
        this.CREATED_BY = CREATED_BY == null ? null : CREATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_SCREEN_DEFINITION.CREATED_DATE
     *
     * @return the value of SYS_PARAM_SCREEN_DEFINITION.CREATED_DATE
     */
    public Date getCREATED_DATE() {
        return CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_SCREEN_DEFINITION.CREATED_DATE
     *
     * @param CREATED_DATE the value for SYS_PARAM_SCREEN_DEFINITION.CREATED_DATE
     */
    public void setCREATED_DATE(Date CREATED_DATE) {
        this.CREATED_DATE = CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_SCREEN_DEFINITION.MODIFIED_BY
     *
     * @return the value of SYS_PARAM_SCREEN_DEFINITION.MODIFIED_BY
     */
    public String getMODIFIED_BY() {
        return MODIFIED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_SCREEN_DEFINITION.MODIFIED_BY
     *
     * @param MODIFIED_BY the value for SYS_PARAM_SCREEN_DEFINITION.MODIFIED_BY
     */
    public void setMODIFIED_BY(String MODIFIED_BY) {
        this.MODIFIED_BY = MODIFIED_BY == null ? null : MODIFIED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_SCREEN_DEFINITION.MODIFIED_DATE
     *
     * @return the value of SYS_PARAM_SCREEN_DEFINITION.MODIFIED_DATE
     */
    public Date getMODIFIED_DATE() {
        return MODIFIED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_SCREEN_DEFINITION.MODIFIED_DATE
     *
     * @param MODIFIED_DATE the value for SYS_PARAM_SCREEN_DEFINITION.MODIFIED_DATE
     */
    public void setMODIFIED_DATE(Date MODIFIED_DATE) {
        this.MODIFIED_DATE = MODIFIED_DATE;
    }
}