package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class SYS_PARAM_BPM_TASK_MAP_ARG_INVOKey extends BaseVO {
    /**
     * This field corresponds to the database column SYS_PARAM_BPM_TASK_MAP_ARG_IN.ARG_NAME
     */
    private String ARG_NAME;

    /**
     * This field corresponds to the database column SYS_PARAM_BPM_TASK_MAP_ARG_IN.SCREEN_CODE
     */
    private String SCREEN_CODE;

    /**
     * This field corresponds to the database column SYS_PARAM_BPM_TASK_MAP_ARG_IN.TASK_MAP_ID
     */
    private BigDecimal TASK_MAP_ID;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_BPM_TASK_MAP_ARG_IN.ARG_NAME
     *
     * @return the value of SYS_PARAM_BPM_TASK_MAP_ARG_IN.ARG_NAME
     */
    public String getARG_NAME() {
        return ARG_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_BPM_TASK_MAP_ARG_IN.ARG_NAME
     *
     * @param ARG_NAME the value for SYS_PARAM_BPM_TASK_MAP_ARG_IN.ARG_NAME
     */
    public void setARG_NAME(String ARG_NAME) {
        this.ARG_NAME = ARG_NAME == null ? null : ARG_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_BPM_TASK_MAP_ARG_IN.SCREEN_CODE
     *
     * @return the value of SYS_PARAM_BPM_TASK_MAP_ARG_IN.SCREEN_CODE
     */
    public String getSCREEN_CODE() {
        return SCREEN_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_BPM_TASK_MAP_ARG_IN.SCREEN_CODE
     *
     * @param SCREEN_CODE the value for SYS_PARAM_BPM_TASK_MAP_ARG_IN.SCREEN_CODE
     */
    public void setSCREEN_CODE(String SCREEN_CODE) {
        this.SCREEN_CODE = SCREEN_CODE == null ? null : SCREEN_CODE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_BPM_TASK_MAP_ARG_IN.TASK_MAP_ID
     *
     * @return the value of SYS_PARAM_BPM_TASK_MAP_ARG_IN.TASK_MAP_ID
     */
    public BigDecimal getTASK_MAP_ID() {
        return TASK_MAP_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_BPM_TASK_MAP_ARG_IN.TASK_MAP_ID
     *
     * @param TASK_MAP_ID the value for SYS_PARAM_BPM_TASK_MAP_ARG_IN.TASK_MAP_ID
     */
    public void setTASK_MAP_ID(BigDecimal TASK_MAP_ID) {
        this.TASK_MAP_ID = TASK_MAP_ID;
    }
}