package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;
import java.util.Date;

public class SYS_PARAM_ACTION_ARG_MAPVO extends BaseVO {
    /**
     * This field corresponds to the database column SYS_PARAM_ACTION_ARG_MAP.ARG_ID
     */
    private BigDecimal ARG_ID;

    /**
     * This field corresponds to the database column SYS_PARAM_ACTION_ARG_MAP.BTN_ID
     */
    private BigDecimal BTN_ID;

    /**
     * This field corresponds to the database column SYS_PARAM_ACTION_ARG_MAP.OP_ID
     */
    private BigDecimal OP_ID;

    /**
     * This field corresponds to the database column SYS_PARAM_ACTION_ARG_MAP.MAP_TYPE
     */
    private String MAP_TYPE;

    /**
     * This field corresponds to the database column SYS_PARAM_ACTION_ARG_MAP.MAP_VALUE
     */
    private String MAP_VALUE;
    
    /**
     * This field corresponds to the database column SYS_PARAM_ACTION_ARG_MAP.MAP_VALUE
     */
    private String MAP_EXPRESSION;
    
    /**
     * This field corresponds to the database column SYS_PARAM_ACTION_ARG_MAP.NESTED
     */
    private String NESTED;

    /**
     * This field corresponds to the database column SYS_PARAM_ACTION_ARG_MAP.LINK_OP_ID
     */
    private BigDecimal LINK_OP_ID;

    /**
     * This field corresponds to the database column SYS_PARAM_ACTION_ARG_MAP.LINK_API_CODE
     */
    private BigDecimal LINK_API_CODE;
    
    /**
     * This field corresponds to the database column SYS_PARAM_ACTION_ARG_MAP.LINK_ARG_ID
     */
    private BigDecimal LINK_ARG_ID;

    /**
     * This field corresponds to the database column SYS_PARAM_ACTION_ARG_MAP.CREATED_BY
     */
    private String CREATED_BY;

    /**
     * This field corresponds to the database column SYS_PARAM_ACTION_ARG_MAP.CREATED_DATE
     */
    private Date CREATED_DATE;

    /**
     * This field corresponds to the database column SYS_PARAM_ACTION_ARG_MAP.MODIFIED_BY
     */
    private String MODIFIED_BY;

    /**
     * This field corresponds to the database column SYS_PARAM_ACTION_ARG_MAP.MODIFIED_DATE
     */
    private Date MODIFIED_DATE;

    private String defaultMapping;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_ACTION_ARG_MAP.ARG_ID
     *
     * @return the value of SYS_PARAM_ACTION_ARG_MAP.ARG_ID
     */
    public BigDecimal getARG_ID() {
        return ARG_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_ACTION_ARG_MAP.ARG_ID
     *
     * @param ARG_ID the value for SYS_PARAM_ACTION_ARG_MAP.ARG_ID
     */
    public void setARG_ID(BigDecimal ARG_ID) {
        this.ARG_ID = ARG_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_ACTION_ARG_MAP.BTN_ID
     *
     * @return the value of SYS_PARAM_ACTION_ARG_MAP.BTN_ID
     */
    public BigDecimal getBTN_ID() {
        return BTN_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_ACTION_ARG_MAP.BTN_ID
     *
     * @param BTN_ID the value for SYS_PARAM_ACTION_ARG_MAP.BTN_ID
     */
    public void setBTN_ID(BigDecimal BTN_ID) {
        this.BTN_ID = BTN_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_ACTION_ARG_MAP.OP_ID
     *
     * @return the value of SYS_PARAM_ACTION_ARG_MAP.OP_ID
     */
    public BigDecimal getOP_ID() {
        return OP_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_ACTION_ARG_MAP.OP_ID
     *
     * @param OP_ID the value for SYS_PARAM_ACTION_ARG_MAP.OP_ID
     */
    public void setOP_ID(BigDecimal OP_ID) {
        this.OP_ID = OP_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_ACTION_ARG_MAP.MAP_TYPE
     *
     * @return the value of SYS_PARAM_ACTION_ARG_MAP.MAP_TYPE
     */
    public String getMAP_TYPE() {
        return MAP_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_ACTION_ARG_MAP.MAP_TYPE
     *
     * @param MAP_TYPE the value for SYS_PARAM_ACTION_ARG_MAP.MAP_TYPE
     */
    public void setMAP_TYPE(String MAP_TYPE) {
        this.MAP_TYPE = MAP_TYPE == null ? null : MAP_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_ACTION_ARG_MAP.MAP_VALUE
     *
     * @return the value of SYS_PARAM_ACTION_ARG_MAP.MAP_VALUE
     */
    public String getMAP_VALUE() {
        return MAP_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_ACTION_ARG_MAP.MAP_VALUE
     *
     * @param MAP_VALUE the value for SYS_PARAM_ACTION_ARG_MAP.MAP_VALUE
     */
    public void setMAP_VALUE(String MAP_VALUE) {
        this.MAP_VALUE = MAP_VALUE == null ? null : MAP_VALUE.trim();
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_ACTION_ARG_MAP.MAP_EXPRESSION
     *
     * @return the value of SYS_PARAM_ACTION_ARG_MAP.MAP_EXPRESSION
     */
    public String getMAP_EXPRESSION() {
	return MAP_EXPRESSION;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_ACTION_ARG_MAP.MAP_EXPRESSION
     *
     * @param MAP_EXPRESSION the value for SYS_PARAM_ACTION_ARG_MAP.MAP_EXPRESSION
     */
    public void setMAP_EXPRESSION(String MAP_EXPRESSION) {
	this.MAP_EXPRESSION = MAP_EXPRESSION == null ? null : MAP_EXPRESSION.trim();
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_ACTION_ARG_MAP.NESTED
     *
     * @return the value of SYS_PARAM_ACTION_ARG_MAP.NESTED
     */
    public String getNESTED() {
	return NESTED;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_ACTION_ARG_MAP.NESTED
     *
     * @param NESTED the value for SYS_PARAM_ACTION_ARG_MAP.NESTED
     */
    public void setNESTED(String NESTED) {
	this.NESTED = NESTED == null ? null : NESTED.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_ACTION_ARG_MAP.LINK_OP_ID
     *
     * @return the value of SYS_PARAM_ACTION_ARG_MAP.LINK_OP_ID
     */
    public BigDecimal getLINK_OP_ID() {
        return LINK_OP_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_ACTION_ARG_MAP.LINK_OP_ID
     *
     * @param LINK_OP_ID the value for SYS_PARAM_ACTION_ARG_MAP.LINK_OP_ID
     */
    public void setLINK_OP_ID(BigDecimal LINK_OP_ID) {
        this.LINK_OP_ID = LINK_OP_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_ACTION_ARG_MAP.LINK_ARG_ID
     *
     * @return the value of SYS_PARAM_ACTION_ARG_MAP.LINK_ARG_ID
     */
    public BigDecimal getLINK_ARG_ID() {
        return LINK_ARG_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_ACTION_ARG_MAP.LINK_ARG_ID
     *
     * @param LINK_ARG_ID the value for SYS_PARAM_ACTION_ARG_MAP.LINK_ARG_ID
     */
    public void setLINK_ARG_ID(BigDecimal LINK_ARG_ID) {
        this.LINK_ARG_ID = LINK_ARG_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_ACTION_ARG_MAP.CREATED_BY
     *
     * @return the value of SYS_PARAM_ACTION_ARG_MAP.CREATED_BY
     */
    public String getCREATED_BY() {
        return CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_ACTION_ARG_MAP.CREATED_BY
     *
     * @param CREATED_BY the value for SYS_PARAM_ACTION_ARG_MAP.CREATED_BY
     */
    public void setCREATED_BY(String CREATED_BY) {
        this.CREATED_BY = CREATED_BY == null ? null : CREATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_ACTION_ARG_MAP.CREATED_DATE
     *
     * @return the value of SYS_PARAM_ACTION_ARG_MAP.CREATED_DATE
     */
    public Date getCREATED_DATE() {
        return CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_ACTION_ARG_MAP.CREATED_DATE
     *
     * @param CREATED_DATE the value for SYS_PARAM_ACTION_ARG_MAP.CREATED_DATE
     */
    public void setCREATED_DATE(Date CREATED_DATE) {
        this.CREATED_DATE = CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_ACTION_ARG_MAP.MODIFIED_BY
     *
     * @return the value of SYS_PARAM_ACTION_ARG_MAP.MODIFIED_BY
     */
    public String getMODIFIED_BY() {
        return MODIFIED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_ACTION_ARG_MAP.MODIFIED_BY
     *
     * @param MODIFIED_BY the value for SYS_PARAM_ACTION_ARG_MAP.MODIFIED_BY
     */
    public void setMODIFIED_BY(String MODIFIED_BY) {
        this.MODIFIED_BY = MODIFIED_BY == null ? null : MODIFIED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_ACTION_ARG_MAP.MODIFIED_DATE
     *
     * @return the value of SYS_PARAM_ACTION_ARG_MAP.MODIFIED_DATE
     */
    public Date getMODIFIED_DATE() {
        return MODIFIED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_ACTION_ARG_MAP.MODIFIED_DATE
     *
     * @param MODIFIED_DATE the value for SYS_PARAM_ACTION_ARG_MAP.MODIFIED_DATE
     */
    public void setMODIFIED_DATE(Date MODIFIED_DATE) {
        this.MODIFIED_DATE = MODIFIED_DATE;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_ACTION_ARG_MAP.LINK_API_CODE
     *
     * @return the value of SYS_PARAM_ACTION_ARG_MAP.LINK_API_CODE
     */
    public BigDecimal getLINK_API_CODE() {
        return LINK_API_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_ACTION_ARG_MAP.LINK_API_CODE
     *
     * @param LINK_API_CODE the value for SYS_PARAM_ACTION_ARG_MAP.LINK_API_CODE
     */
    public void setLINK_API_CODE(BigDecimal LINK_API_CODE) {
        this.LINK_API_CODE = LINK_API_CODE;
    }

    public String getDefaultMapping()
    {
        return defaultMapping;
    }

    public void setDefaultMapping(String defaultMapping)
    {
        this.defaultMapping = defaultMapping;
    }
    
    
}