package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class SYS_THEMEVOKey extends BaseVO {
    /**
     * This field corresponds to the database column SYS_THEME.THEME_ID
     */
    private BigDecimal THEME_ID;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_THEME.THEME_ID
     *
     * @return the value of SYS_THEME.THEME_ID
     */
    public BigDecimal getTHEME_ID() {
        return THEME_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_THEME.THEME_ID
     *
     * @param THEME_ID the value for SYS_THEME.THEME_ID
     */
    public void setTHEME_ID(BigDecimal THEME_ID) {
        this.THEME_ID = THEME_ID;
    }
}