package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class SYS_PARAM_BPM_TASK_MAPVO extends SYS_PARAM_BPM_TASK_MAPVOKey {
    /**
     * This field corresponds to the database column SYS_PARAM_BPM_TASK_MAP.PROCESS_ID
     */
    private BigDecimal PROCESS_ID;

    /**
     * This field corresponds to the database column SYS_PARAM_BPM_TASK_MAP.TASK_NAME
     */
    private String TASK_NAME;

    /**
     * This field corresponds to the database column SYS_PARAM_BPM_TASK_MAP.SCREEN_CODE
     */
    private String SCREEN_CODE;

    /**
     * This field corresponds to the database column SYS_PARAM_BPM_TASK_MAP.BPM_ASSIGNMENT_YN
     */
    private String BPM_ASSIGNMENT_YN;

    /**
     * This field corresponds to the database column SYS_PARAM_BPM_TASK_MAP.CREATED_BY
     */
    private String CREATED_BY;

    /**
     * This field corresponds to the database column SYS_PARAM_BPM_TASK_MAP.CREATED_DATE
     */
    private Date CREATED_DATE;

    /**
     * This field corresponds to the database column SYS_PARAM_BPM_TASK_MAP.MODIFIED_BY
     */
    private String MODIFIED_BY;

    /**
     * This field corresponds to the database column SYS_PARAM_BPM_TASK_MAP.MODIFIED_DATE
     */
    private Date MODIFIED_DATE;

    /**
     * This field corresponds to the database column SYS_PARAM_BPM_TASK_MAP.PROG_REF
     */
    private String PROG_REF;

    /**
     * This field corresponds to the database column SYS_PARAM_BPM_TASK_MAP.COMPLETION_TYPE
     */
    private String COMPLETION_TYPE;
    
    /**
     * This field corresponds to the database column SYS_PARAM_BPM_TASK_MAP.ACTION_TYPE
     */
    private String ACTION_TYPE;

    /**
     * This field corresponds to the database column SYS_PARAM_BPM_TASK_MAP.PRIORITY
     */
    private String PRIORITY;
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_BPM_TASK_MAP.PROCESS_ID
     *
     * @return the value of SYS_PARAM_BPM_TASK_MAP.PROCESS_ID
     */
    public BigDecimal getPROCESS_ID() {
        return PROCESS_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_BPM_TASK_MAP.PROCESS_ID
     *
     * @param PROCESS_ID the value for SYS_PARAM_BPM_TASK_MAP.PROCESS_ID
     */
    public void setPROCESS_ID(BigDecimal PROCESS_ID) {
        this.PROCESS_ID = PROCESS_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_BPM_TASK_MAP.TASK_NAME
     *
     * @return the value of SYS_PARAM_BPM_TASK_MAP.TASK_NAME
     */
    public String getTASK_NAME() {
        return TASK_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_BPM_TASK_MAP.TASK_NAME
     *
     * @param TASK_NAME the value for SYS_PARAM_BPM_TASK_MAP.TASK_NAME
     */
    public void setTASK_NAME(String TASK_NAME) {
        this.TASK_NAME = TASK_NAME == null ? null : TASK_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_BPM_TASK_MAP.SCREEN_CODE
     *
     * @return the value of SYS_PARAM_BPM_TASK_MAP.SCREEN_CODE
     */
    public String getSCREEN_CODE() {
        return SCREEN_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_BPM_TASK_MAP.SCREEN_CODE
     *
     * @param SCREEN_CODE the value for SYS_PARAM_BPM_TASK_MAP.SCREEN_CODE
     */
    public void setSCREEN_CODE(String SCREEN_CODE) {
        this.SCREEN_CODE = SCREEN_CODE == null ? null : SCREEN_CODE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_BPM_TASK_MAP.BPM_ASSIGNMENT_YN
     *
     * @return the value of SYS_PARAM_BPM_TASK_MAP.BPM_ASSIGNMENT_YN
     */
    public String getBPM_ASSIGNMENT_YN() {
        return BPM_ASSIGNMENT_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_BPM_TASK_MAP.BPM_ASSIGNMENT_YN
     *
     * @param BPM_ASSIGNMENT_YN the value for SYS_PARAM_BPM_TASK_MAP.BPM_ASSIGNMENT_YN
     */
    public void setBPM_ASSIGNMENT_YN(String BPM_ASSIGNMENT_YN) {
        this.BPM_ASSIGNMENT_YN = BPM_ASSIGNMENT_YN == null ? null : BPM_ASSIGNMENT_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_BPM_TASK_MAP.CREATED_BY
     *
     * @return the value of SYS_PARAM_BPM_TASK_MAP.CREATED_BY
     */
    public String getCREATED_BY() {
        return CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_BPM_TASK_MAP.CREATED_BY
     *
     * @param CREATED_BY the value for SYS_PARAM_BPM_TASK_MAP.CREATED_BY
     */
    public void setCREATED_BY(String CREATED_BY) {
        this.CREATED_BY = CREATED_BY == null ? null : CREATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_BPM_TASK_MAP.CREATED_DATE
     *
     * @return the value of SYS_PARAM_BPM_TASK_MAP.CREATED_DATE
     */
    public Date getCREATED_DATE() {
        return CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_BPM_TASK_MAP.CREATED_DATE
     *
     * @param CREATED_DATE the value for SYS_PARAM_BPM_TASK_MAP.CREATED_DATE
     */
    public void setCREATED_DATE(Date CREATED_DATE) {
        this.CREATED_DATE = CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_BPM_TASK_MAP.MODIFIED_BY
     *
     * @return the value of SYS_PARAM_BPM_TASK_MAP.MODIFIED_BY
     */
    public String getMODIFIED_BY() {
        return MODIFIED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_BPM_TASK_MAP.MODIFIED_BY
     *
     * @param MODIFIED_BY the value for SYS_PARAM_BPM_TASK_MAP.MODIFIED_BY
     */
    public void setMODIFIED_BY(String MODIFIED_BY) {
        this.MODIFIED_BY = MODIFIED_BY == null ? null : MODIFIED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_BPM_TASK_MAP.MODIFIED_DATE
     *
     * @return the value of SYS_PARAM_BPM_TASK_MAP.MODIFIED_DATE
     */
    public Date getMODIFIED_DATE() {
        return MODIFIED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_BPM_TASK_MAP.MODIFIED_DATE
     *
     * @param MODIFIED_DATE the value for SYS_PARAM_BPM_TASK_MAP.MODIFIED_DATE
     */
    public void setMODIFIED_DATE(Date MODIFIED_DATE) {
        this.MODIFIED_DATE = MODIFIED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_BPM_TASK_MAP.PROG_REF
     *
     * @return the value of SYS_PARAM_BPM_TASK_MAP.PROG_REF
     */
    public String getPROG_REF() {
        return PROG_REF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_BPM_TASK_MAP.PROG_REF
     *
     * @param PROG_REF the value for SYS_PARAM_BPM_TASK_MAP.PROG_REF
     */
    public void setPROG_REF(String PROG_REF) {
        this.PROG_REF = PROG_REF == null ? null : PROG_REF.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_BPM_TASK_MAP.COMPLETION_TYPE
     *
     * @return the value of SYS_PARAM_BPM_TASK_MAP.COMPLETION_TYPE
     */
    public String getCOMPLETION_TYPE() {
        return COMPLETION_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_BPM_TASK_MAP.COMPLETION_TYPE
     *
     * @param COMPLETION_TYPE the value for SYS_PARAM_BPM_TASK_MAP.COMPLETION_TYPE
     */
    public void setCOMPLETION_TYPE(String COMPLETION_TYPE) {
        this.COMPLETION_TYPE = COMPLETION_TYPE == null ? null : COMPLETION_TYPE.trim();
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_BPM_TASK_MAP.ACTION_TYPE
     *
     * @return the value of SYS_PARAM_BPM_TASK_MAP.ACTION_TYPE
     */
    public String getACTION_TYPE() {
        return ACTION_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_BPM_TASK_MAP.ACTION_TYPE
     *
     * @param ACTION_TYPE the value for SYS_PARAM_BPM_TASK_MAP.ACTION_TYPE
     */
    public void setACTION_TYPE(String ACTION_TYPE) {
        this.ACTION_TYPE = ACTION_TYPE == null ? null : ACTION_TYPE.trim();
    }
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_BPM_TASK_MAP.PRIORITY
     *
     * @return the value of SYS_PARAM_BPM_TASK_MAP.PRIORITY
     */
    public String getPRIORITY() {
        return PRIORITY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_BPM_TASK_MAP.PRIORITY
     *
     * @param PRIORITY the value for SYS_PARAM_BPM_TASK_MAP.PRIORITY
     */
    public void setPRIORITY(String PRIORITY) {
        this.PRIORITY = PRIORITY == null ? null : PRIORITY.trim();
    }
    
}