package com.path.dbmaps.vo;

public class SYS_PARAM_TODO_ALERT_TYPEVO extends SYS_PARAM_TODO_ALERT_TYPEVOKey {
    /**
     * This field corresponds to the database column SYS_PARAM_TODO_ALERT_TYPE.BRIEF_DESC_ENG
     */
    private String BRIEF_DESC_ENG;

    /**
     * This field corresponds to the database column SYS_PARAM_TODO_ALERT_TYPE.TODO_ALERT_TYPE
     */
    private String TODO_ALERT_TYPE;

    /**
     * This field corresponds to the database column SYS_PARAM_TODO_ALERT_TYPE.OPT_URL
     */
    private String OPT_URL;

    /**
     * This field corresponds to the database column SYS_PARAM_TODO_ALERT_TYPE.APPROVE_METHOD
     */
    private String APPROVE_METHOD;

    /**
     * This field corresponds to the database column SYS_PARAM_TODO_ALERT_TYPE.OPEN_METHOD
     */
    private String OPEN_METHOD;

    /**
     * This field corresponds to the database column SYS_PARAM_TODO_ALERT_TYPE.REJECT_METHOD
     */
    private String REJECT_METHOD;

    /**
     * This field corresponds to the database column SYS_PARAM_TODO_ALERT_TYPE.PRINT_METHOD
     */
    private String PRINT_METHOD;

    /**
     * This field corresponds to the database column SYS_PARAM_TODO_ALERT_TYPE.FORWARD_METHOD
     */
    private String FORWARD_METHOD;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_TODO_ALERT_TYPE.BRIEF_DESC_ENG
     *
     * @return the value of SYS_PARAM_TODO_ALERT_TYPE.BRIEF_DESC_ENG
     */
    public String getBRIEF_DESC_ENG() {
        return BRIEF_DESC_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_TODO_ALERT_TYPE.BRIEF_DESC_ENG
     *
     * @param BRIEF_DESC_ENG the value for SYS_PARAM_TODO_ALERT_TYPE.BRIEF_DESC_ENG
     */
    public void setBRIEF_DESC_ENG(String BRIEF_DESC_ENG) {
        this.BRIEF_DESC_ENG = BRIEF_DESC_ENG == null ? null : BRIEF_DESC_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_TODO_ALERT_TYPE.TODO_ALERT_TYPE
     *
     * @return the value of SYS_PARAM_TODO_ALERT_TYPE.TODO_ALERT_TYPE
     */
    public String getTODO_ALERT_TYPE() {
        return TODO_ALERT_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_TODO_ALERT_TYPE.TODO_ALERT_TYPE
     *
     * @param TODO_ALERT_TYPE the value for SYS_PARAM_TODO_ALERT_TYPE.TODO_ALERT_TYPE
     */
    public void setTODO_ALERT_TYPE(String TODO_ALERT_TYPE) {
        this.TODO_ALERT_TYPE = TODO_ALERT_TYPE == null ? null : TODO_ALERT_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_TODO_ALERT_TYPE.OPT_URL
     *
     * @return the value of SYS_PARAM_TODO_ALERT_TYPE.OPT_URL
     */
    public String getOPT_URL() {
        return OPT_URL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_TODO_ALERT_TYPE.OPT_URL
     *
     * @param OPT_URL the value for SYS_PARAM_TODO_ALERT_TYPE.OPT_URL
     */
    public void setOPT_URL(String OPT_URL) {
        this.OPT_URL = OPT_URL == null ? null : OPT_URL.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_TODO_ALERT_TYPE.APPROVE_METHOD
     *
     * @return the value of SYS_PARAM_TODO_ALERT_TYPE.APPROVE_METHOD
     */
    public String getAPPROVE_METHOD() {
        return APPROVE_METHOD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_TODO_ALERT_TYPE.APPROVE_METHOD
     *
     * @param APPROVE_METHOD the value for SYS_PARAM_TODO_ALERT_TYPE.APPROVE_METHOD
     */
    public void setAPPROVE_METHOD(String APPROVE_METHOD) {
        this.APPROVE_METHOD = APPROVE_METHOD == null ? null : APPROVE_METHOD.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_TODO_ALERT_TYPE.OPEN_METHOD
     *
     * @return the value of SYS_PARAM_TODO_ALERT_TYPE.OPEN_METHOD
     */
    public String getOPEN_METHOD() {
        return OPEN_METHOD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_TODO_ALERT_TYPE.OPEN_METHOD
     *
     * @param OPEN_METHOD the value for SYS_PARAM_TODO_ALERT_TYPE.OPEN_METHOD
     */
    public void setOPEN_METHOD(String OPEN_METHOD) {
        this.OPEN_METHOD = OPEN_METHOD == null ? null : OPEN_METHOD.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_TODO_ALERT_TYPE.REJECT_METHOD
     *
     * @return the value of SYS_PARAM_TODO_ALERT_TYPE.REJECT_METHOD
     */
    public String getREJECT_METHOD() {
        return REJECT_METHOD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_TODO_ALERT_TYPE.REJECT_METHOD
     *
     * @param REJECT_METHOD the value for SYS_PARAM_TODO_ALERT_TYPE.REJECT_METHOD
     */
    public void setREJECT_METHOD(String REJECT_METHOD) {
        this.REJECT_METHOD = REJECT_METHOD == null ? null : REJECT_METHOD.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_TODO_ALERT_TYPE.PRINT_METHOD
     *
     * @return the value of SYS_PARAM_TODO_ALERT_TYPE.PRINT_METHOD
     */
    public String getPRINT_METHOD() {
        return PRINT_METHOD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_TODO_ALERT_TYPE.PRINT_METHOD
     *
     * @param PRINT_METHOD the value for SYS_PARAM_TODO_ALERT_TYPE.PRINT_METHOD
     */
    public void setPRINT_METHOD(String PRINT_METHOD) {
        this.PRINT_METHOD = PRINT_METHOD == null ? null : PRINT_METHOD.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_TODO_ALERT_TYPE.FORWARD_METHOD
     *
     * @return the value of SYS_PARAM_TODO_ALERT_TYPE.FORWARD_METHOD
     */
    public String getFORWARD_METHOD() {
        return FORWARD_METHOD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_TODO_ALERT_TYPE.FORWARD_METHOD
     *
     * @param FORWARD_METHOD the value for SYS_PARAM_TODO_ALERT_TYPE.FORWARD_METHOD
     */
    public void setFORWARD_METHOD(String FORWARD_METHOD) {
        this.FORWARD_METHOD = FORWARD_METHOD == null ? null : FORWARD_METHOD.trim();
    }
}