package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;
import java.util.Date;

public class SYS_PARAM_ACTION_ARG_LISTVO extends BaseVO {
    /**
     * This field corresponds to the database column SYS_PARAM_ACTION_ARG_LIST.ARG_ID
     */
    private BigDecimal ARG_ID;

    /**
     * This field corresponds to the database column SYS_PARAM_ACTION_ARG_LIST.BTN_ID
     */
    private BigDecimal BTN_ID;

    /**
     * This field corresponds to the database column SYS_PARAM_ACTION_ARG_LIST.LINE_NO
     */
    private BigDecimal LINE_NO;

    /**
     * This field corresponds to the database column SYS_PARAM_ACTION_ARG_LIST.OP_ID
     */
    private BigDecimal OP_ID;

    /**
     * This field corresponds to the database column SYS_PARAM_ACTION_ARG_LIST.LIST_TYPE
     */
    private String LIST_TYPE;

    /**
     * This field corresponds to the database column SYS_PARAM_ACTION_ARG_LIST.LIST_VALUE
     */
    private String LIST_VALUE;

    /**
     * This field corresponds to the database column SYS_PARAM_ACTION_ARG_LIST.CREATED_BY
     */
    private String CREATED_BY;

    /**
     * This field corresponds to the database column SYS_PARAM_ACTION_ARG_LIST.CREATED_DATE
     */
    private Date CREATED_DATE;

    /**
     * This field corresponds to the database column SYS_PARAM_ACTION_ARG_LIST.MODIFIED_BY
     */
    private String MODIFIED_BY;

    /**
     * This field corresponds to the database column SYS_PARAM_ACTION_ARG_LIST.MODIFIED_DATE
     */
    private Date MODIFIED_DATE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_ACTION_ARG_LIST.ARG_ID
     *
     * @return the value of SYS_PARAM_ACTION_ARG_LIST.ARG_ID
     */
    public BigDecimal getARG_ID() {
        return ARG_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_ACTION_ARG_LIST.ARG_ID
     *
     * @param ARG_ID the value for SYS_PARAM_ACTION_ARG_LIST.ARG_ID
     */
    public void setARG_ID(BigDecimal ARG_ID) {
        this.ARG_ID = ARG_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_ACTION_ARG_LIST.BTN_ID
     *
     * @return the value of SYS_PARAM_ACTION_ARG_LIST.BTN_ID
     */
    public BigDecimal getBTN_ID() {
        return BTN_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_ACTION_ARG_LIST.BTN_ID
     *
     * @param BTN_ID the value for SYS_PARAM_ACTION_ARG_LIST.BTN_ID
     */
    public void setBTN_ID(BigDecimal BTN_ID) {
        this.BTN_ID = BTN_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_ACTION_ARG_LIST.LINE_NO
     *
     * @return the value of SYS_PARAM_ACTION_ARG_LIST.LINE_NO
     */
    public BigDecimal getLINE_NO() {
        return LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_ACTION_ARG_LIST.LINE_NO
     *
     * @param LINE_NO the value for SYS_PARAM_ACTION_ARG_LIST.LINE_NO
     */
    public void setLINE_NO(BigDecimal LINE_NO) {
        this.LINE_NO = LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_ACTION_ARG_LIST.OP_ID
     *
     * @return the value of SYS_PARAM_ACTION_ARG_LIST.OP_ID
     */
    public BigDecimal getOP_ID() {
        return OP_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_ACTION_ARG_LIST.OP_ID
     *
     * @param OP_ID the value for SYS_PARAM_ACTION_ARG_LIST.OP_ID
     */
    public void setOP_ID(BigDecimal OP_ID) {
        this.OP_ID = OP_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_ACTION_ARG_LIST.LIST_TYPE
     *
     * @return the value of SYS_PARAM_ACTION_ARG_LIST.LIST_TYPE
     */
    public String getLIST_TYPE() {
        return LIST_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_ACTION_ARG_LIST.LIST_TYPE
     *
     * @param LIST_TYPE the value for SYS_PARAM_ACTION_ARG_LIST.LIST_TYPE
     */
    public void setLIST_TYPE(String LIST_TYPE) {
        this.LIST_TYPE = LIST_TYPE == null ? null : LIST_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_ACTION_ARG_LIST.LIST_VALUE
     *
     * @return the value of SYS_PARAM_ACTION_ARG_LIST.LIST_VALUE
     */
    public String getLIST_VALUE() {
        return LIST_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_ACTION_ARG_LIST.LIST_VALUE
     *
     * @param LIST_VALUE the value for SYS_PARAM_ACTION_ARG_LIST.LIST_VALUE
     */
    public void setLIST_VALUE(String LIST_VALUE) {
        this.LIST_VALUE = LIST_VALUE == null ? null : LIST_VALUE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_ACTION_ARG_LIST.CREATED_BY
     *
     * @return the value of SYS_PARAM_ACTION_ARG_LIST.CREATED_BY
     */
    public String getCREATED_BY() {
        return CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_ACTION_ARG_LIST.CREATED_BY
     *
     * @param CREATED_BY the value for SYS_PARAM_ACTION_ARG_LIST.CREATED_BY
     */
    public void setCREATED_BY(String CREATED_BY) {
        this.CREATED_BY = CREATED_BY == null ? null : CREATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_ACTION_ARG_LIST.CREATED_DATE
     *
     * @return the value of SYS_PARAM_ACTION_ARG_LIST.CREATED_DATE
     */
    public Date getCREATED_DATE() {
        return CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_ACTION_ARG_LIST.CREATED_DATE
     *
     * @param CREATED_DATE the value for SYS_PARAM_ACTION_ARG_LIST.CREATED_DATE
     */
    public void setCREATED_DATE(Date CREATED_DATE) {
        this.CREATED_DATE = CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_ACTION_ARG_LIST.MODIFIED_BY
     *
     * @return the value of SYS_PARAM_ACTION_ARG_LIST.MODIFIED_BY
     */
    public String getMODIFIED_BY() {
        return MODIFIED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_ACTION_ARG_LIST.MODIFIED_BY
     *
     * @param MODIFIED_BY the value for SYS_PARAM_ACTION_ARG_LIST.MODIFIED_BY
     */
    public void setMODIFIED_BY(String MODIFIED_BY) {
        this.MODIFIED_BY = MODIFIED_BY == null ? null : MODIFIED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_ACTION_ARG_LIST.MODIFIED_DATE
     *
     * @return the value of SYS_PARAM_ACTION_ARG_LIST.MODIFIED_DATE
     */
    public Date getMODIFIED_DATE() {
        return MODIFIED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_ACTION_ARG_LIST.MODIFIED_DATE
     *
     * @param MODIFIED_DATE the value for SYS_PARAM_ACTION_ARG_LIST.MODIFIED_DATE
     */
    public void setMODIFIED_DATE(Date MODIFIED_DATE) {
        this.MODIFIED_DATE = MODIFIED_DATE;
    }
}