package com.path.dbmaps.vo;

import java.util.Date;

public class SYS_PARAM_BPM_PROCESS_VARVO extends SYS_PARAM_BPM_PROCESS_VARVOKey {
    /**
     * This field corresponds to the database column SYS_PARAM_BPM_PROCESS_VAR.VARIABLE_NAME
     */
    private String VARIABLE_NAME;

    /**
     * This field corresponds to the database column SYS_PARAM_BPM_PROCESS_VAR.VARIABLE_TYPE
     */
    private String VARIABLE_TYPE;

    /**
     * This field corresponds to the database column SYS_PARAM_BPM_PROCESS_VAR.BUSINESS_NAME
     */
    private String BUSINESS_NAME;

    /**
     * This field corresponds to the database column SYS_PARAM_BPM_PROCESS_VAR.DESCRIPTION
     */
    private String DESCRIPTION;

    /**
     * This field corresponds to the database column SYS_PARAM_BPM_PROCESS_VAR.IS_MANDATORY_YN
     */
    private String IS_MANDATORY_YN;

    /**
     * This field corresponds to the database column SYS_PARAM_BPM_PROCESS_VAR.SHOW_ON_STARTUP_YN
     */
    private String SHOW_ON_STARTUP_YN;

    /**
     * This field corresponds to the database column SYS_PARAM_BPM_PROCESS_VAR.CREATED_BY
     */
    private String CREATED_BY;

    /**
     * This field corresponds to the database column SYS_PARAM_BPM_PROCESS_VAR.CREATED_DATE
     */
    private Date CREATED_DATE;

    /**
     * This field corresponds to the database column SYS_PARAM_BPM_PROCESS_VAR.MODIFIED_BY
     */
    private String MODIFIED_BY;

    /**
     * This field corresponds to the database column SYS_PARAM_BPM_PROCESS_VAR.MODIFIED_DATE
     */
    private Date MODIFIED_DATE;
    
    /**
     * This field corresponds to the database column SYS_PARAM_BPM_PROCESS_VAR.DEFAULT_VALUE
     */
    private String DEFAULT_VALUE;
    
    /**
     * This field corresponds to the database column SYS_PARAM_BPM_PROCESS_VAR.DEFAULT_TYPE
     */
    private String DEFAULT_TYPE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_BPM_PROCESS_VAR.VARIABLE_NAME
     *
     * @return the value of SYS_PARAM_BPM_PROCESS_VAR.VARIABLE_NAME
     */
    public String getVARIABLE_NAME() {
        return VARIABLE_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_BPM_PROCESS_VAR.VARIABLE_NAME
     *
     * @param VARIABLE_NAME the value for SYS_PARAM_BPM_PROCESS_VAR.VARIABLE_NAME
     */
    public void setVARIABLE_NAME(String VARIABLE_NAME) {
        this.VARIABLE_NAME = VARIABLE_NAME == null ? null : VARIABLE_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_BPM_PROCESS_VAR.VARIABLE_TYPE
     *
     * @return the value of SYS_PARAM_BPM_PROCESS_VAR.VARIABLE_TYPE
     */
    public String getVARIABLE_TYPE() {
        return VARIABLE_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_BPM_PROCESS_VAR.VARIABLE_TYPE
     *
     * @param VARIABLE_TYPE the value for SYS_PARAM_BPM_PROCESS_VAR.VARIABLE_TYPE
     */
    public void setVARIABLE_TYPE(String VARIABLE_TYPE) {
        this.VARIABLE_TYPE = VARIABLE_TYPE == null ? null : VARIABLE_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_BPM_PROCESS_VAR.BUSINESS_NAME
     *
     * @return the value of SYS_PARAM_BPM_PROCESS_VAR.BUSINESS_NAME
     */
    public String getBUSINESS_NAME() {
        return BUSINESS_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_BPM_PROCESS_VAR.BUSINESS_NAME
     *
     * @param BUSINESS_NAME the value for SYS_PARAM_BPM_PROCESS_VAR.BUSINESS_NAME
     */
    public void setBUSINESS_NAME(String BUSINESS_NAME) {
        this.BUSINESS_NAME = BUSINESS_NAME == null ? null : BUSINESS_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_BPM_PROCESS_VAR.DESCRIPTION
     *
     * @return the value of SYS_PARAM_BPM_PROCESS_VAR.DESCRIPTION
     */
    public String getDESCRIPTION() {
        return DESCRIPTION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_BPM_PROCESS_VAR.DESCRIPTION
     *
     * @param DESCRIPTION the value for SYS_PARAM_BPM_PROCESS_VAR.DESCRIPTION
     */
    public void setDESCRIPTION(String DESCRIPTION) {
        this.DESCRIPTION = DESCRIPTION == null ? null : DESCRIPTION.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_BPM_PROCESS_VAR.IS_MANDATORY_YN
     *
     * @return the value of SYS_PARAM_BPM_PROCESS_VAR.IS_MANDATORY_YN
     */
    public String getIS_MANDATORY_YN() {
        return IS_MANDATORY_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_BPM_PROCESS_VAR.IS_MANDATORY_YN
     *
     * @param IS_MANDATORY_YN the value for SYS_PARAM_BPM_PROCESS_VAR.IS_MANDATORY_YN
     */
    public void setIS_MANDATORY_YN(String IS_MANDATORY_YN) {
        this.IS_MANDATORY_YN = IS_MANDATORY_YN == null ? null : IS_MANDATORY_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_BPM_PROCESS_VAR.SHOW_ON_STARTUP_YN
     *
     * @return the value of SYS_PARAM_BPM_PROCESS_VAR.SHOW_ON_STARTUP_YN
     */
    public String getSHOW_ON_STARTUP_YN() {
        return SHOW_ON_STARTUP_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_BPM_PROCESS_VAR.SHOW_ON_STARTUP_YN
     *
     * @param SHOW_ON_STARTUP_YN the value for SYS_PARAM_BPM_PROCESS_VAR.SHOW_ON_STARTUP_YN
     */
    public void setSHOW_ON_STARTUP_YN(String SHOW_ON_STARTUP_YN) {
        this.SHOW_ON_STARTUP_YN = SHOW_ON_STARTUP_YN == null ? null : SHOW_ON_STARTUP_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_BPM_PROCESS_VAR.CREATED_BY
     *
     * @return the value of SYS_PARAM_BPM_PROCESS_VAR.CREATED_BY
     */
    public String getCREATED_BY() {
        return CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_BPM_PROCESS_VAR.CREATED_BY
     *
     * @param CREATED_BY the value for SYS_PARAM_BPM_PROCESS_VAR.CREATED_BY
     */
    public void setCREATED_BY(String CREATED_BY) {
        this.CREATED_BY = CREATED_BY == null ? null : CREATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_BPM_PROCESS_VAR.CREATED_DATE
     *
     * @return the value of SYS_PARAM_BPM_PROCESS_VAR.CREATED_DATE
     */
    public Date getCREATED_DATE() {
        return CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_BPM_PROCESS_VAR.CREATED_DATE
     *
     * @param CREATED_DATE the value for SYS_PARAM_BPM_PROCESS_VAR.CREATED_DATE
     */
    public void setCREATED_DATE(Date CREATED_DATE) {
        this.CREATED_DATE = CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_BPM_PROCESS_VAR.MODIFIED_BY
     *
     * @return the value of SYS_PARAM_BPM_PROCESS_VAR.MODIFIED_BY
     */
    public String getMODIFIED_BY() {
        return MODIFIED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_BPM_PROCESS_VAR.MODIFIED_BY
     *
     * @param MODIFIED_BY the value for SYS_PARAM_BPM_PROCESS_VAR.MODIFIED_BY
     */
    public void setMODIFIED_BY(String MODIFIED_BY) {
        this.MODIFIED_BY = MODIFIED_BY == null ? null : MODIFIED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_BPM_PROCESS_VAR.MODIFIED_DATE
     *
     * @return the value of SYS_PARAM_BPM_PROCESS_VAR.MODIFIED_DATE
     */
    public Date getMODIFIED_DATE() {
        return MODIFIED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_BPM_PROCESS_VAR.MODIFIED_DATE
     *
     * @param MODIFIED_DATE the value for SYS_PARAM_BPM_PROCESS_VAR.MODIFIED_DATE
     */
    public void setMODIFIED_DATE(Date MODIFIED_DATE) {
        this.MODIFIED_DATE = MODIFIED_DATE;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_BPM_PROCESS_VAR.DEFAULT_VALUE
     *
     * @return the value of SYS_PARAM_BPM_PROCESS_VAR.DEFAULT_VALUE
     */
    public String getDEFAULT_VALUE() {
        return DEFAULT_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_BPM_PROCESS_VAR.DEFAULT_VALUE
     *
     * @param DEFAULT_VALUE the value for SYS_PARAM_BPM_PROCESS_VAR.DEFAULT_VALUE
     */
    public void setDEFAULT_VALUE(String DEFAULT_VALUE) {
        this.DEFAULT_VALUE = DEFAULT_VALUE == null ? null : DEFAULT_VALUE.trim();
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_BPM_PROCESS_VAR.DEFAULT_TYPE
     *
     * @return the value of SYS_PARAM_BPM_PROCESS_VAR.DEFAULT_TYPE
     */
    public String getDEFAULT_TYPE() {
        return DEFAULT_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_BPM_PROCESS_VAR.DEFAULT_TYPE
     *
     * @param DEFAULT_VALUE the value for SYS_PARAM_BPM_PROCESS_VAR.DEFAULT_TYPE
     */
    public void setDEFAULT_TYPE(String DEFAULT_TYPE) {
        this.DEFAULT_TYPE = DEFAULT_TYPE == null ? null : DEFAULT_TYPE.trim();
    }
}