package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;
import java.util.Date;

public class SYS_PARAM_OBJ_DISPLAYVO extends BaseVO {
    /**
     * This field corresponds to the database column SYS_PARAM_OBJ_DISPLAY.OBJ_DISPLAY_ID
     */
    private BigDecimal OBJ_DISPLAY_ID;

    /**
     * This field corresponds to the database column SYS_PARAM_OBJ_DISPLAY.APP_NAME
     */
    private String APP_NAME;

    /**
     * This field corresponds to the database column SYS_PARAM_OBJ_DISPLAY.PROG_REF
     */
    private String PROG_REF;

    /**
     * This field corresponds to the database column SYS_PARAM_OBJ_DISPLAY.OBJECT_TYPE
     */
    private String OBJECT_TYPE;

    /**
     * This field corresponds to the database column SYS_PARAM_OBJ_DISPLAY.OBJECT_ID
     */
    private String OBJECT_ID;

    /**
     * This field corresponds to the database column SYS_PARAM_OBJ_DISPLAY.ADD_DELETE_ROW_YN
     */
    private BigDecimal ADD_DELETE_ROW_YN;

    /**
     * This field corresponds to the database column SYS_PARAM_OBJ_DISPLAY.IS_READONLY
     */
    private BigDecimal IS_READONLY;

    /**
     * This field corresponds to the database column SYS_PARAM_OBJ_DISPLAY.IS_VISIBLE
     */
    private BigDecimal IS_VISIBLE;

    /**
     * This field corresponds to the database column SYS_PARAM_OBJ_DISPLAY.BUS_RELATED
     */
    private BigDecimal BUS_RELATED;

    /**
     * This field corresponds to the database column SYS_PARAM_OBJ_DISPLAY.IS_ADM_CUST_DIS_YN
     */
    private BigDecimal IS_ADM_CUST_DIS_YN;

    /**
     * This field corresponds to the database column SYS_PARAM_OBJ_DISPLAY.CREATED_BY
     */
    private String CREATED_BY;

    /**
     * This field corresponds to the database column SYS_PARAM_OBJ_DISPLAY.CREATED_DATE
     */
    private Date CREATED_DATE;

    /**
     * This field corresponds to the database column SYS_PARAM_OBJ_DISPLAY.MODIFIED_BY
     */
    private String MODIFIED_BY;

    /**
     * This field corresponds to the database column SYS_PARAM_OBJ_DISPLAY.MODIFIED_DATE
     */
    private Date MODIFIED_DATE;

    /**
     * This field corresponds to the database column SYS_PARAM_OBJ_DISPLAY.ADD_DELETE_ROW_EXPR
     */
    private String ADD_DELETE_ROW_EXPR;

    /**
     * This field corresponds to the database column SYS_PARAM_OBJ_DISPLAY.READONLY_EXPR
     */
    private String READONLY_EXPR;

    /**
     * This field corresponds to the database column SYS_PARAM_OBJ_DISPLAY.VISIBILITY_EXPR
     */
    private String VISIBILITY_EXPR;
    
    /*953614 Specify Grid Filter Query Expression - Grid/Livesearch Customization Enhancements*/
    private String FILTER_EXPR;
   
    public String getFILTER_EXPR()
    {
	return FILTER_EXPR;
    }

    public void setFILTER_EXPR(String fILTER_EXPR)
    {
	FILTER_EXPR = fILTER_EXPR;
    }
    /*end: 953614*/

    

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_OBJ_DISPLAY.OBJ_DISPLAY_ID
     *
     * @return the value of SYS_PARAM_OBJ_DISPLAY.OBJ_DISPLAY_ID
     */
    public BigDecimal getOBJ_DISPLAY_ID() {
        return OBJ_DISPLAY_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_OBJ_DISPLAY.OBJ_DISPLAY_ID
     *
     * @param OBJ_DISPLAY_ID the value for SYS_PARAM_OBJ_DISPLAY.OBJ_DISPLAY_ID
     */
    public void setOBJ_DISPLAY_ID(BigDecimal OBJ_DISPLAY_ID) {
        this.OBJ_DISPLAY_ID = OBJ_DISPLAY_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_OBJ_DISPLAY.APP_NAME
     *
     * @return the value of SYS_PARAM_OBJ_DISPLAY.APP_NAME
     */
    public String getAPP_NAME() {
        return APP_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_OBJ_DISPLAY.APP_NAME
     *
     * @param APP_NAME the value for SYS_PARAM_OBJ_DISPLAY.APP_NAME
     */
    public void setAPP_NAME(String APP_NAME) {
        this.APP_NAME = APP_NAME == null ? null : APP_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_OBJ_DISPLAY.PROG_REF
     *
     * @return the value of SYS_PARAM_OBJ_DISPLAY.PROG_REF
     */
    public String getPROG_REF() {
        return PROG_REF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_OBJ_DISPLAY.PROG_REF
     *
     * @param PROG_REF the value for SYS_PARAM_OBJ_DISPLAY.PROG_REF
     */
    public void setPROG_REF(String PROG_REF) {
        this.PROG_REF = PROG_REF == null ? null : PROG_REF.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_OBJ_DISPLAY.OBJECT_TYPE
     *
     * @return the value of SYS_PARAM_OBJ_DISPLAY.OBJECT_TYPE
     */
    public String getOBJECT_TYPE() {
        return OBJECT_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_OBJ_DISPLAY.OBJECT_TYPE
     *
     * @param OBJECT_TYPE the value for SYS_PARAM_OBJ_DISPLAY.OBJECT_TYPE
     */
    public void setOBJECT_TYPE(String OBJECT_TYPE) {
        this.OBJECT_TYPE = OBJECT_TYPE == null ? null : OBJECT_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_OBJ_DISPLAY.OBJECT_ID
     *
     * @return the value of SYS_PARAM_OBJ_DISPLAY.OBJECT_ID
     */
    public String getOBJECT_ID() {
        return OBJECT_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_OBJ_DISPLAY.OBJECT_ID
     *
     * @param OBJECT_ID the value for SYS_PARAM_OBJ_DISPLAY.OBJECT_ID
     */
    public void setOBJECT_ID(String OBJECT_ID) {
        this.OBJECT_ID = OBJECT_ID == null ? null : OBJECT_ID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_OBJ_DISPLAY.ADD_DELETE_ROW_YN
     *
     * @return the value of SYS_PARAM_OBJ_DISPLAY.ADD_DELETE_ROW_YN
     */
    public BigDecimal getADD_DELETE_ROW_YN() {
        return ADD_DELETE_ROW_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_OBJ_DISPLAY.ADD_DELETE_ROW_YN
     *
     * @param ADD_DELETE_ROW_YN the value for SYS_PARAM_OBJ_DISPLAY.ADD_DELETE_ROW_YN
     */
    public void setADD_DELETE_ROW_YN(BigDecimal ADD_DELETE_ROW_YN) {
        this.ADD_DELETE_ROW_YN = ADD_DELETE_ROW_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_OBJ_DISPLAY.IS_READONLY
     *
     * @return the value of SYS_PARAM_OBJ_DISPLAY.IS_READONLY
     */
    public BigDecimal getIS_READONLY() {
        return IS_READONLY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_OBJ_DISPLAY.IS_READONLY
     *
     * @param IS_READONLY the value for SYS_PARAM_OBJ_DISPLAY.IS_READONLY
     */
    public void setIS_READONLY(BigDecimal IS_READONLY) {
        this.IS_READONLY = IS_READONLY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_OBJ_DISPLAY.IS_VISIBLE
     *
     * @return the value of SYS_PARAM_OBJ_DISPLAY.IS_VISIBLE
     */
    public BigDecimal getIS_VISIBLE() {
        return IS_VISIBLE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_OBJ_DISPLAY.IS_VISIBLE
     *
     * @param IS_VISIBLE the value for SYS_PARAM_OBJ_DISPLAY.IS_VISIBLE
     */
    public void setIS_VISIBLE(BigDecimal IS_VISIBLE) {
        this.IS_VISIBLE = IS_VISIBLE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_OBJ_DISPLAY.BUS_RELATED
     *
     * @return the value of SYS_PARAM_OBJ_DISPLAY.BUS_RELATED
     */
    public BigDecimal getBUS_RELATED() {
        return BUS_RELATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_OBJ_DISPLAY.BUS_RELATED
     *
     * @param BUS_RELATED the value for SYS_PARAM_OBJ_DISPLAY.BUS_RELATED
     */
    public void setBUS_RELATED(BigDecimal BUS_RELATED) {
        this.BUS_RELATED = BUS_RELATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_OBJ_DISPLAY.IS_ADM_CUST_DIS_YN
     *
     * @return the value of SYS_PARAM_OBJ_DISPLAY.IS_ADM_CUST_DIS_YN
     */
    public BigDecimal getIS_ADM_CUST_DIS_YN() {
        return IS_ADM_CUST_DIS_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_OBJ_DISPLAY.IS_ADM_CUST_DIS_YN
     *
     * @param IS_ADM_CUST_DIS_YN the value for SYS_PARAM_OBJ_DISPLAY.IS_ADM_CUST_DIS_YN
     */
    public void setIS_ADM_CUST_DIS_YN(BigDecimal IS_ADM_CUST_DIS_YN) {
        this.IS_ADM_CUST_DIS_YN = IS_ADM_CUST_DIS_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_OBJ_DISPLAY.CREATED_BY
     *
     * @return the value of SYS_PARAM_OBJ_DISPLAY.CREATED_BY
     */
    public String getCREATED_BY() {
        return CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_OBJ_DISPLAY.CREATED_BY
     *
     * @param CREATED_BY the value for SYS_PARAM_OBJ_DISPLAY.CREATED_BY
     */
    public void setCREATED_BY(String CREATED_BY) {
        this.CREATED_BY = CREATED_BY == null ? null : CREATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_OBJ_DISPLAY.CREATED_DATE
     *
     * @return the value of SYS_PARAM_OBJ_DISPLAY.CREATED_DATE
     */
    public Date getCREATED_DATE() {
        return CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_OBJ_DISPLAY.CREATED_DATE
     *
     * @param CREATED_DATE the value for SYS_PARAM_OBJ_DISPLAY.CREATED_DATE
     */
    public void setCREATED_DATE(Date CREATED_DATE) {
        this.CREATED_DATE = CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_OBJ_DISPLAY.MODIFIED_BY
     *
     * @return the value of SYS_PARAM_OBJ_DISPLAY.MODIFIED_BY
     */
    public String getMODIFIED_BY() {
        return MODIFIED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_OBJ_DISPLAY.MODIFIED_BY
     *
     * @param MODIFIED_BY the value for SYS_PARAM_OBJ_DISPLAY.MODIFIED_BY
     */
    public void setMODIFIED_BY(String MODIFIED_BY) {
        this.MODIFIED_BY = MODIFIED_BY == null ? null : MODIFIED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_OBJ_DISPLAY.MODIFIED_DATE
     *
     * @return the value of SYS_PARAM_OBJ_DISPLAY.MODIFIED_DATE
     */
    public Date getMODIFIED_DATE() {
        return MODIFIED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_OBJ_DISPLAY.MODIFIED_DATE
     *
     * @param MODIFIED_DATE the value for SYS_PARAM_OBJ_DISPLAY.MODIFIED_DATE
     */
    public void setMODIFIED_DATE(Date MODIFIED_DATE) {
        this.MODIFIED_DATE = MODIFIED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_OBJ_DISPLAY.ADD_DELETE_ROW_EXPR
     *
     * @return the value of SYS_PARAM_OBJ_DISPLAY.ADD_DELETE_ROW_EXPR
     */
    public String getADD_DELETE_ROW_EXPR() {
        return ADD_DELETE_ROW_EXPR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_OBJ_DISPLAY.ADD_DELETE_ROW_EXPR
     *
     * @param ADD_DELETE_ROW_EXPR the value for SYS_PARAM_OBJ_DISPLAY.ADD_DELETE_ROW_EXPR
     */
    public void setADD_DELETE_ROW_EXPR(String ADD_DELETE_ROW_EXPR) {
        this.ADD_DELETE_ROW_EXPR = ADD_DELETE_ROW_EXPR == null ? null : ADD_DELETE_ROW_EXPR.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_OBJ_DISPLAY.READONLY_EXPR
     *
     * @return the value of SYS_PARAM_OBJ_DISPLAY.READONLY_EXPR
     */
    public String getREADONLY_EXPR() {
        return READONLY_EXPR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_OBJ_DISPLAY.READONLY_EXPR
     *
     * @param READONLY_EXPR the value for SYS_PARAM_OBJ_DISPLAY.READONLY_EXPR
     */
    public void setREADONLY_EXPR(String READONLY_EXPR) {
        this.READONLY_EXPR = READONLY_EXPR == null ? null : READONLY_EXPR.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_OBJ_DISPLAY.VISIBILITY_EXPR
     *
     * @return the value of SYS_PARAM_OBJ_DISPLAY.VISIBILITY_EXPR
     */
    public String getVISIBILITY_EXPR() {
        return VISIBILITY_EXPR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_OBJ_DISPLAY.VISIBILITY_EXPR
     *
     * @param VISIBILITY_EXPR the value for SYS_PARAM_OBJ_DISPLAY.VISIBILITY_EXPR
     */
    public void setVISIBILITY_EXPR(String VISIBILITY_EXPR) {
        this.VISIBILITY_EXPR = VISIBILITY_EXPR == null ? null : VISIBILITY_EXPR.trim();
    }
}