package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class SYS_PARAM_STYLEVOKey extends BaseVO {
    /**
     * This field corresponds to the database column SYS_PARAM_STYLE.STYLE_ID
     */
    private BigDecimal STYLE_ID;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_STYLE.STYLE_ID
     *
     * @return the value of SYS_PARAM_STYLE.STYLE_ID
     */
    public BigDecimal getSTYLE_ID() {
        return STYLE_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_STYLE.STYLE_ID
     *
     * @param STYLE_ID the value for SYS_PARAM_STYLE.STYLE_ID
     */
    public void setSTYLE_ID(BigDecimal STYLE_ID) {
        this.STYLE_ID = STYLE_ID;
    }
}