package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;
import java.util.Date;

public class SYS_DYN_TABLE_DETVO extends BaseVO {
    /**
     * This field corresponds to the database column SYS_DYN_TABLE_DET.COL_ID
     */
    private BigDecimal COL_ID;

    /**
     * This field corresponds to the database column SYS_DYN_TABLE_DET.TABLE_ID
     */
    private BigDecimal TABLE_ID;

    /**
     * This field corresponds to the database column SYS_DYN_TABLE_DET.COL_TECH_NAME
     */
    private String COL_TECH_NAME;

    /**
     * This field corresponds to the database column SYS_DYN_TABLE_DET.COL_DESC
     */
    private String COL_DESC;

    /**
     * This field corresponds to the database column SYS_DYN_TABLE_DET.PRIMARY_KEY
     */
    private BigDecimal PRIMARY_KEY;

    /**
     * This field corresponds to the database column SYS_DYN_TABLE_DET.CREATED_BY
     */
    private String CREATED_BY;

    /**
     * This field corresponds to the database column SYS_DYN_TABLE_DET.CREATION_DATE
     */
    private Date CREATION_DATE;

    /**
     * This field corresponds to the database column SYS_DYN_TABLE_DET.MODIFIED_BY
     */
    private String MODIFIED_BY;

    /**
     * This field corresponds to the database column SYS_DYN_TABLE_DET.MODIFIED_DATE
     */
    private Date MODIFIED_DATE;

    /**
     * This field corresponds to the database column SYS_DYN_TABLE_DET.COL_TYPE
     */
    private BigDecimal COL_TYPE;

    /**
     * This field corresponds to the database column SYS_DYN_TABLE_DET.VISIBLE_YN
     */
    private BigDecimal VISIBLE_YN;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_DYN_TABLE_DET.COL_ID
     *
     * @return the value of SYS_DYN_TABLE_DET.COL_ID
     */
    public BigDecimal getCOL_ID() {
        return COL_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_DYN_TABLE_DET.COL_ID
     *
     * @param COL_ID the value for SYS_DYN_TABLE_DET.COL_ID
     */
    public void setCOL_ID(BigDecimal COL_ID) {
        this.COL_ID = COL_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_DYN_TABLE_DET.TABLE_ID
     *
     * @return the value of SYS_DYN_TABLE_DET.TABLE_ID
     */
    public BigDecimal getTABLE_ID() {
        return TABLE_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_DYN_TABLE_DET.TABLE_ID
     *
     * @param TABLE_ID the value for SYS_DYN_TABLE_DET.TABLE_ID
     */
    public void setTABLE_ID(BigDecimal TABLE_ID) {
        this.TABLE_ID = TABLE_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_DYN_TABLE_DET.COL_TECH_NAME
     *
     * @return the value of SYS_DYN_TABLE_DET.COL_TECH_NAME
     */
    public String getCOL_TECH_NAME() {
        return COL_TECH_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_DYN_TABLE_DET.COL_TECH_NAME
     *
     * @param COL_TECH_NAME the value for SYS_DYN_TABLE_DET.COL_TECH_NAME
     */
    public void setCOL_TECH_NAME(String COL_TECH_NAME) {
        this.COL_TECH_NAME = COL_TECH_NAME == null ? null : COL_TECH_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_DYN_TABLE_DET.COL_DESC
     *
     * @return the value of SYS_DYN_TABLE_DET.COL_DESC
     */
    public String getCOL_DESC() {
        return COL_DESC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_DYN_TABLE_DET.COL_DESC
     *
     * @param COL_DESC the value for SYS_DYN_TABLE_DET.COL_DESC
     */
    public void setCOL_DESC(String COL_DESC) {
        this.COL_DESC = COL_DESC == null ? null : COL_DESC.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_DYN_TABLE_DET.PRIMARY_KEY
     *
     * @return the value of SYS_DYN_TABLE_DET.PRIMARY_KEY
     */
    public BigDecimal getPRIMARY_KEY() {
        return PRIMARY_KEY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_DYN_TABLE_DET.PRIMARY_KEY
     *
     * @param PRIMARY_KEY the value for SYS_DYN_TABLE_DET.PRIMARY_KEY
     */
    public void setPRIMARY_KEY(BigDecimal PRIMARY_KEY) {
        this.PRIMARY_KEY = PRIMARY_KEY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_DYN_TABLE_DET.CREATED_BY
     *
     * @return the value of SYS_DYN_TABLE_DET.CREATED_BY
     */
    public String getCREATED_BY() {
        return CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_DYN_TABLE_DET.CREATED_BY
     *
     * @param CREATED_BY the value for SYS_DYN_TABLE_DET.CREATED_BY
     */
    public void setCREATED_BY(String CREATED_BY) {
        this.CREATED_BY = CREATED_BY == null ? null : CREATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_DYN_TABLE_DET.CREATION_DATE
     *
     * @return the value of SYS_DYN_TABLE_DET.CREATION_DATE
     */
    public Date getCREATION_DATE() {
        return CREATION_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_DYN_TABLE_DET.CREATION_DATE
     *
     * @param CREATION_DATE the value for SYS_DYN_TABLE_DET.CREATION_DATE
     */
    public void setCREATION_DATE(Date CREATION_DATE) {
        this.CREATION_DATE = CREATION_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_DYN_TABLE_DET.MODIFIED_BY
     *
     * @return the value of SYS_DYN_TABLE_DET.MODIFIED_BY
     */
    public String getMODIFIED_BY() {
        return MODIFIED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_DYN_TABLE_DET.MODIFIED_BY
     *
     * @param MODIFIED_BY the value for SYS_DYN_TABLE_DET.MODIFIED_BY
     */
    public void setMODIFIED_BY(String MODIFIED_BY) {
        this.MODIFIED_BY = MODIFIED_BY == null ? null : MODIFIED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_DYN_TABLE_DET.MODIFIED_DATE
     *
     * @return the value of SYS_DYN_TABLE_DET.MODIFIED_DATE
     */
    public Date getMODIFIED_DATE() {
        return MODIFIED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_DYN_TABLE_DET.MODIFIED_DATE
     *
     * @param MODIFIED_DATE the value for SYS_DYN_TABLE_DET.MODIFIED_DATE
     */
    public void setMODIFIED_DATE(Date MODIFIED_DATE) {
        this.MODIFIED_DATE = MODIFIED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_DYN_TABLE_DET.COL_TYPE
     *
     * @return the value of SYS_DYN_TABLE_DET.COL_TYPE
     */
    public BigDecimal getCOL_TYPE() {
        return COL_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_DYN_TABLE_DET.COL_TYPE
     *
     * @param COL_TYPE the value for SYS_DYN_TABLE_DET.COL_TYPE
     */
    public void setCOL_TYPE(BigDecimal COL_TYPE) {
        this.COL_TYPE = COL_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_DYN_TABLE_DET.VISIBLE_YN
     *
     * @return the value of SYS_DYN_TABLE_DET.VISIBLE_YN
     */
    public BigDecimal getVISIBLE_YN() {
        return VISIBLE_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_DYN_TABLE_DET.VISIBLE_YN
     *
     * @param VISIBLE_YN the value for SYS_DYN_TABLE_DET.VISIBLE_YN
     */
    public void setVISIBLE_YN(BigDecimal VISIBLE_YN) {
        this.VISIBLE_YN = VISIBLE_YN;
    }
}