package com.path.dbmaps.vo;

public class SYS_PARAM_LANGUAGESVO extends SYS_PARAM_LANGUAGESVOKey {
    /**
     * This field corresponds to the database column SYS_PARAM_LANGUAGES.LANG_NAME
     */
    private String LANG_NAME;

    /**
     * This field corresponds to the database column SYS_PARAM_LANGUAGES.ISO_CODE
     */
    private String ISO_CODE;

    /**
     * This field corresponds to the database column SYS_PARAM_LANGUAGES.IS_RIGHT_LEFT_YN
     */
    private String IS_RIGHT_LEFT_YN;

    /**
     * This field corresponds to the database column SYS_PARAM_LANGUAGES.CONVERT_LIKE_LANG
     */
    private String CONVERT_LIKE_LANG;

    /**
     * This field corresponds to the database column SYS_PARAM_LANGUAGES.CONVERSION_METHOD_ID
     */
    private String CONVERSION_METHOD_ID;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_LANGUAGES.LANG_NAME
     *
     * @return the value of SYS_PARAM_LANGUAGES.LANG_NAME
     */
    public String getLANG_NAME() {
        return LANG_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_LANGUAGES.LANG_NAME
     *
     * @param LANG_NAME the value for SYS_PARAM_LANGUAGES.LANG_NAME
     */
    public void setLANG_NAME(String LANG_NAME) {
        this.LANG_NAME = LANG_NAME == null ? null : LANG_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_LANGUAGES.ISO_CODE
     *
     * @return the value of SYS_PARAM_LANGUAGES.ISO_CODE
     */
    public String getISO_CODE() {
        return ISO_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_LANGUAGES.ISO_CODE
     *
     * @param ISO_CODE the value for SYS_PARAM_LANGUAGES.ISO_CODE
     */
    public void setISO_CODE(String ISO_CODE) {
        this.ISO_CODE = ISO_CODE == null ? null : ISO_CODE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_LANGUAGES.IS_RIGHT_LEFT_YN
     *
     * @return the value of SYS_PARAM_LANGUAGES.IS_RIGHT_LEFT_YN
     */
    public String getIS_RIGHT_LEFT_YN() {
        return IS_RIGHT_LEFT_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_LANGUAGES.IS_RIGHT_LEFT_YN
     *
     * @param IS_RIGHT_LEFT_YN the value for SYS_PARAM_LANGUAGES.IS_RIGHT_LEFT_YN
     */
    public void setIS_RIGHT_LEFT_YN(String IS_RIGHT_LEFT_YN) {
        this.IS_RIGHT_LEFT_YN = IS_RIGHT_LEFT_YN == null ? null : IS_RIGHT_LEFT_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_LANGUAGES.CONVERT_LIKE_LANG
     *
     * @return the value of SYS_PARAM_LANGUAGES.CONVERT_LIKE_LANG
     */
    public String getCONVERT_LIKE_LANG() {
        return CONVERT_LIKE_LANG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_LANGUAGES.CONVERT_LIKE_LANG
     *
     * @param CONVERT_LIKE_LANG the value for SYS_PARAM_LANGUAGES.CONVERT_LIKE_LANG
     */
    public void setCONVERT_LIKE_LANG(String CONVERT_LIKE_LANG) {
        this.CONVERT_LIKE_LANG = CONVERT_LIKE_LANG == null ? null : CONVERT_LIKE_LANG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_LANGUAGES.CONVERSION_METHOD_ID
     *
     * @return the value of SYS_PARAM_LANGUAGES.CONVERSION_METHOD_ID
     */
    public String getCONVERSION_METHOD_ID() {
        return CONVERSION_METHOD_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_LANGUAGES.CONVERSION_METHOD_ID
     *
     * @param CONVERSION_METHOD_ID the value for SYS_PARAM_LANGUAGES.CONVERSION_METHOD_ID
     */
    public void setCONVERSION_METHOD_ID(String CONVERSION_METHOD_ID) {
        this.CONVERSION_METHOD_ID = CONVERSION_METHOD_ID == null ? null : CONVERSION_METHOD_ID.trim();
    }
}