package com.path.dbmaps.vo;

import java.math.BigDecimal;

import com.path.lib.vo.BaseVO;

public class SYS_PARAM_STYLE_ATTRIBUTEVOKey extends BaseVO
{
    /**
     * This field corresponds to the database column
     * SYS_PARAM_STYLE_ATTRIBUTE.ATTRIBUTE_CODE
     */
    private String ATTRIBUTE_CODE;

    /**
     * This field corresponds to the database column
     * SYS_PARAM_STYLE_ATTRIBUTE.STYLE_ID
     */
    private BigDecimal STYLE_ID;

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column SYS_PARAM_STYLE_ATTRIBUTE.ATTRIBUTE_CODE
     * 
     * @return the value of SYS_PARAM_STYLE_ATTRIBUTE.ATTRIBUTE_CODE
     */
    public String getATTRIBUTE_CODE()
    {
	return ATTRIBUTE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column SYS_PARAM_STYLE_ATTRIBUTE.ATTRIBUTE_CODE
     * 
     * @param ATTRIBUTE_CODE the value for
     *            SYS_PARAM_STYLE_ATTRIBUTE.ATTRIBUTE_CODE
     */
    public void setATTRIBUTE_CODE(String ATTRIBUTE_CODE)
    {
	this.ATTRIBUTE_CODE = ATTRIBUTE_CODE == null ? null : ATTRIBUTE_CODE.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column SYS_PARAM_STYLE_ATTRIBUTE.STYLE_ID
     * 
     * @return the value of SYS_PARAM_STYLE_ATTRIBUTE.STYLE_ID
     */
    public BigDecimal getSTYLE_ID()
    {
	return STYLE_ID;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column SYS_PARAM_STYLE_ATTRIBUTE.STYLE_ID
     * 
     * @param STYLE_ID the value for SYS_PARAM_STYLE_ATTRIBUTE.STYLE_ID
     */
    public void setSTYLE_ID(BigDecimal STYLE_ID)
    {
	this.STYLE_ID = STYLE_ID;
    }

}