package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;
import java.util.Date;

public class SYS_PARAM_BTN_CUST_ACTIONSVO extends BaseVO {
    /**
     * This field corresponds to the database column SYS_PARAM_BTN_CUST_ACTIONS.BTN_ID
     */
    private BigDecimal BTN_ID;

    /**
     * This field corresponds to the database column SYS_PARAM_BTN_CUST_ACTIONS.OP_ID
     */
    private BigDecimal OP_ID;

    /**
     * This field corresponds to the database column SYS_PARAM_BTN_CUST_ACTIONS.OP_TYPE
     */
    private String OP_TYPE;

    /**
     * This field corresponds to the database column SYS_PARAM_BTN_CUST_ACTIONS.DESCRIPTION
     */
    private String DESCRIPTION;

    /**
     * This field corresponds to the database column SYS_PARAM_BTN_CUST_ACTIONS.PARENT_OP_ID
     */
    private BigDecimal PARENT_OP_ID;

    /**
     * This field corresponds to the database column SYS_PARAM_BTN_CUST_ACTIONS.API_CODE
     */
    private BigDecimal API_CODE;

    /**
     * This field corresponds to the database column SYS_PARAM_BTN_CUST_ACTIONS.CREATED_BY
     */
    private String CREATED_BY;

    /**
     * This field corresponds to the database column SYS_PARAM_BTN_CUST_ACTIONS.CREATED_DATE
     */
    private Date CREATED_DATE;

    /**
     * This field corresponds to the database column SYS_PARAM_BTN_CUST_ACTIONS.MODIFIED_BY
     */
    private String MODIFIED_BY;

    /**
     * This field corresponds to the database column SYS_PARAM_BTN_CUST_ACTIONS.MODIFIED_DATE
     */
    private Date MODIFIED_DATE;

    /**
     * This field corresponds to the database column SYS_PARAM_BTN_CUST_ACTIONS.REPORT_PROG_REF
     */
    private String REPORT_PROG_REF;

    /**
     * This field corresponds to the database column SYS_PARAM_BTN_CUST_ACTIONS.REPORT_APP_NAME
     */
    private String REPORT_APP_NAME;

    /**
     * This field corresponds to the database column SYS_PARAM_BTN_CUST_ACTIONS.COND_EXPR
     */
    private String COND_EXPR;
    
    /**
     * This field corresponds to the database column SYS_PARAM_BTN_CUST_ACTIONS.API_TYPE
     */
    private String API_TYPE;
    
    /**
     * This field corresponds to the database column SYS_PARAM_BTN_CUST_ACTIONS.SCREEN_WIDTH
     */
    private BigDecimal SCREEN_WIDTH;

    /**
     * This field corresponds to the database column SYS_PARAM_BTN_CUST_ACTIONS.SCREEN_HEIGHT
     */
    private BigDecimal SCREEN_HEIGHT;
    
    /**
     * This field corresponds to the database column SYS_PARAM_BTN_CUST_ACTIONS.SCREEN_TITLE
     */
    private String SCREEN_TITLE;
    
    /*TP 983067 Option to load JS Method to be called from js File located on the server*/
    private String SCRIPT_URL;
    
    // TP 1062269 Loading Report Assigned by Customization into provided Div or iFrame ID - Customization Enhancement
    private String COMPONENT_ID;
    
	public String getCOMPONENT_ID() 
	{
		return COMPONENT_ID;
	}

	public void setCOMPONENT_ID(String cOMPONENT_ID) 
	{
		COMPONENT_ID = cOMPONENT_ID;
	}

	public String getSCRIPT_URL()
    {
	return SCRIPT_URL;
    }

    public void setSCRIPT_URL(String sCRIPT_URL)
    {
	SCRIPT_URL = sCRIPT_URL;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_BTN_CUST_ACTIONS.BTN_ID
     *
     * @return the value of SYS_PARAM_BTN_CUST_ACTIONS.BTN_ID
     */
    public BigDecimal getBTN_ID() {
        return BTN_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_BTN_CUST_ACTIONS.BTN_ID
     *
     * @param BTN_ID the value for SYS_PARAM_BTN_CUST_ACTIONS.BTN_ID
     */
    public void setBTN_ID(BigDecimal BTN_ID) {
        this.BTN_ID = BTN_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_BTN_CUST_ACTIONS.OP_ID
     *
     * @return the value of SYS_PARAM_BTN_CUST_ACTIONS.OP_ID
     */
    public BigDecimal getOP_ID() {
        return OP_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_BTN_CUST_ACTIONS.OP_ID
     *
     * @param OP_ID the value for SYS_PARAM_BTN_CUST_ACTIONS.OP_ID
     */
    public void setOP_ID(BigDecimal OP_ID) {
        this.OP_ID = OP_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_BTN_CUST_ACTIONS.OP_TYPE
     *
     * @return the value of SYS_PARAM_BTN_CUST_ACTIONS.OP_TYPE
     */
    public String getOP_TYPE() {
        return OP_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_BTN_CUST_ACTIONS.OP_TYPE
     *
     * @param OP_TYPE the value for SYS_PARAM_BTN_CUST_ACTIONS.OP_TYPE
     */
    public void setOP_TYPE(String OP_TYPE) {
        this.OP_TYPE = OP_TYPE == null ? null : OP_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_BTN_CUST_ACTIONS.DESCRIPTION
     *
     * @return the value of SYS_PARAM_BTN_CUST_ACTIONS.DESCRIPTION
     */
    public String getDESCRIPTION() {
        return DESCRIPTION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_BTN_CUST_ACTIONS.DESCRIPTION
     *
     * @param DESCRIPTION the value for SYS_PARAM_BTN_CUST_ACTIONS.DESCRIPTION
     */
    public void setDESCRIPTION(String DESCRIPTION) {
        this.DESCRIPTION = DESCRIPTION == null ? null : DESCRIPTION.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_BTN_CUST_ACTIONS.PARENT_OP_ID
     *
     * @return the value of SYS_PARAM_BTN_CUST_ACTIONS.PARENT_OP_ID
     */
    public BigDecimal getPARENT_OP_ID() {
        return PARENT_OP_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_BTN_CUST_ACTIONS.PARENT_OP_ID
     *
     * @param PARENT_OP_ID the value for SYS_PARAM_BTN_CUST_ACTIONS.PARENT_OP_ID
     */
    public void setPARENT_OP_ID(BigDecimal PARENT_OP_ID) {
        this.PARENT_OP_ID = PARENT_OP_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_BTN_CUST_ACTIONS.API_CODE
     *
     * @return the value of SYS_PARAM_BTN_CUST_ACTIONS.API_CODE
     */
    public BigDecimal getAPI_CODE() {
        return API_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_BTN_CUST_ACTIONS.API_CODE
     *
     * @param API_CODE the value for SYS_PARAM_BTN_CUST_ACTIONS.API_CODE
     */
    public void setAPI_CODE(BigDecimal API_CODE) {
        this.API_CODE = API_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_BTN_CUST_ACTIONS.CREATED_BY
     *
     * @return the value of SYS_PARAM_BTN_CUST_ACTIONS.CREATED_BY
     */
    public String getCREATED_BY() {
        return CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_BTN_CUST_ACTIONS.CREATED_BY
     *
     * @param CREATED_BY the value for SYS_PARAM_BTN_CUST_ACTIONS.CREATED_BY
     */
    public void setCREATED_BY(String CREATED_BY) {
        this.CREATED_BY = CREATED_BY == null ? null : CREATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_BTN_CUST_ACTIONS.CREATED_DATE
     *
     * @return the value of SYS_PARAM_BTN_CUST_ACTIONS.CREATED_DATE
     */
    public Date getCREATED_DATE() {
        return CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_BTN_CUST_ACTIONS.CREATED_DATE
     *
     * @param CREATED_DATE the value for SYS_PARAM_BTN_CUST_ACTIONS.CREATED_DATE
     */
    public void setCREATED_DATE(Date CREATED_DATE) {
        this.CREATED_DATE = CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_BTN_CUST_ACTIONS.MODIFIED_BY
     *
     * @return the value of SYS_PARAM_BTN_CUST_ACTIONS.MODIFIED_BY
     */
    public String getMODIFIED_BY() {
        return MODIFIED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_BTN_CUST_ACTIONS.MODIFIED_BY
     *
     * @param MODIFIED_BY the value for SYS_PARAM_BTN_CUST_ACTIONS.MODIFIED_BY
     */
    public void setMODIFIED_BY(String MODIFIED_BY) {
        this.MODIFIED_BY = MODIFIED_BY == null ? null : MODIFIED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_BTN_CUST_ACTIONS.MODIFIED_DATE
     *
     * @return the value of SYS_PARAM_BTN_CUST_ACTIONS.MODIFIED_DATE
     */
    public Date getMODIFIED_DATE() {
        return MODIFIED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_BTN_CUST_ACTIONS.MODIFIED_DATE
     *
     * @param MODIFIED_DATE the value for SYS_PARAM_BTN_CUST_ACTIONS.MODIFIED_DATE
     */
    public void setMODIFIED_DATE(Date MODIFIED_DATE) {
        this.MODIFIED_DATE = MODIFIED_DATE;
    }

        /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_BTN_CUST_ACTIONS.REPORT_PROG_REF
     *
     * @return the value of SYS_PARAM_BTN_CUST_ACTIONS.REPORT_PROG_REF
     */
    public String getREPORT_PROG_REF() {
        return REPORT_PROG_REF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_BTN_CUST_ACTIONS.REPORT_PROG_REF
     *
     * @param REPORT_PROG_REF the value for SYS_PARAM_BTN_CUST_ACTIONS.REPORT_PROG_REF
     */
    public void setREPORT_PROG_REF(String REPORT_PROG_REF) {
        this.REPORT_PROG_REF = REPORT_PROG_REF == null ? null : REPORT_PROG_REF.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_BTN_CUST_ACTIONS.REPORT_APP_NAME
     *
     * @return the value of SYS_PARAM_BTN_CUST_ACTIONS.REPORT_APP_NAME
     */
    public String getREPORT_APP_NAME() {
        return REPORT_APP_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_BTN_CUST_ACTIONS.REPORT_APP_NAME
     *
     * @param REPORT_APP_NAME the value for SYS_PARAM_BTN_CUST_ACTIONS.REPORT_APP_NAME
     */
    public void setREPORT_APP_NAME(String REPORT_APP_NAME) {
        this.REPORT_APP_NAME = REPORT_APP_NAME == null ? null : REPORT_APP_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_BTN_CUST_ACTIONS.COND_EXPR
     *
     * @return the value of SYS_PARAM_BTN_CUST_ACTIONS.COND_EXPR
     */
    public String getCOND_EXPR() {
        return COND_EXPR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_BTN_CUST_ACTIONS.COND_EXPR
     *
     * @param COND_EXPR the value for SYS_PARAM_BTN_CUST_ACTIONS.COND_EXPR
     */
    public void setCOND_EXPR(String COND_EXPR) {
        this.COND_EXPR = COND_EXPR == null ? null : COND_EXPR.trim();
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_BTN_CUST_ACTIONS.API_TYPE
     *
     * @return the value of SYS_PARAM_BTN_CUST_ACTIONS.API_TYPE
     */
    public String getAPI_TYPE() {
        return API_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_BTN_CUST_ACTIONS.API_TYPE
     *
     * @param API_TYPE the value for SYS_PARAM_BTN_CUST_ACTIONS.API_TYPE
     */
    public void setAPI_TYPE(String API_TYPE) {
        this.API_TYPE = API_TYPE == null ? null : API_TYPE.trim();
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_BTN_CUST_ACTIONS.SCREEN_WIDTH
     *
     * @return the value of SYS_PARAM_BTN_CUST_ACTIONS.SCREEN_WIDTH
     */
    public BigDecimal getSCREEN_WIDTH() {
        return SCREEN_WIDTH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_BTN_CUST_ACTIONS.SCREEN_WIDTH
     *
     * @param SCREEN_WIDTH the value for SYS_PARAM_BTN_CUST_ACTIONS.SCREEN_WIDTH
     */
    public void setSCREEN_WIDTH(BigDecimal SCREEN_WIDTH) {
        this.SCREEN_WIDTH = SCREEN_WIDTH;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_BTN_CUST_ACTIONS.SCREEN_HEIGHT
     *
     * @return the value of SYS_PARAM_BTN_CUST_ACTIONS.SCREEN_HEIGHT
     */
    public BigDecimal getSCREEN_HEIGHT() {
        return SCREEN_HEIGHT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_BTN_CUST_ACTIONS.SCREEN_HEIGHT
     *
     * @param SCREEN_HEIGHT the value for SYS_PARAM_BTN_CUST_ACTIONS.SCREEN_HEIGHT
     */
    public void setSCREEN_HEIGHT(BigDecimal SCREEN_HEIGHT) {
        this.SCREEN_HEIGHT = SCREEN_HEIGHT;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_BTN_CUST_ACTIONS.SCREEN_TITLE
     *
     * @return the value of SYS_PARAM_BTN_CUST_ACTIONS.SCREEN_TITLE
     */
    public String getSCREEN_TITLE() {
        return SCREEN_TITLE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_BTN_CUST_ACTIONS.SCREEN_TITLE
     *
     * @param SCREEN_TITLE the value for SYS_PARAM_BTN_CUST_ACTIONS.SCREEN_TITLE
     */
    public void setSCREEN_TITLE(String SCREEN_TITLE) {
        this.SCREEN_TITLE = SCREEN_TITLE == null ? null : SCREEN_TITLE.trim();
    }
}