package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class SYS_DYN_SCREEN_ELEMENTSVO extends SYS_DYN_SCREEN_ELEMENTSVOKey {
    /**
     * This field corresponds to the database column SYS_DYN_SCREEN_ELEMENTS.DYN_SCREEN_ID
     */
    private BigDecimal DYN_SCREEN_ID;

    /**
     * This field corresponds to the database column SYS_DYN_SCREEN_ELEMENTS.ELEMENT_TYPE_CODE
     */
    private String ELEMENT_TYPE_CODE;

    /**
     * This field corresponds to the database column SYS_DYN_SCREEN_ELEMENTS.CREATED_BY
     */
    private String CREATED_BY;

    /**
     * This field corresponds to the database column SYS_DYN_SCREEN_ELEMENTS.CREATED_DATE
     */
    private Date CREATED_DATE;

    /**
     * This field corresponds to the database column SYS_DYN_SCREEN_ELEMENTS.MODIFIED_BY
     */
    private String MODIFIED_BY;

    /**
     * This field corresponds to the database column SYS_DYN_SCREEN_ELEMENTS.MODIFIED_DATE
     */
    private Date MODIFIED_DATE;
    
    private BigDecimal TECH_ID;
    private BigDecimal PARENT_TECH_ID;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_DYN_SCREEN_ELEMENTS.DYN_SCREEN_ID
     *
     * @return the value of SYS_DYN_SCREEN_ELEMENTS.DYN_SCREEN_ID
     */
    public BigDecimal getDYN_SCREEN_ID() {
        return DYN_SCREEN_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_DYN_SCREEN_ELEMENTS.DYN_SCREEN_ID
     *
     * @param DYN_SCREEN_ID the value for SYS_DYN_SCREEN_ELEMENTS.DYN_SCREEN_ID
     */
    public void setDYN_SCREEN_ID(BigDecimal DYN_SCREEN_ID) {
        this.DYN_SCREEN_ID = DYN_SCREEN_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_DYN_SCREEN_ELEMENTS.ELEMENT_TYPE_CODE
     *
     * @return the value of SYS_DYN_SCREEN_ELEMENTS.ELEMENT_TYPE_CODE
     */
    public String getELEMENT_TYPE_CODE() {
        return ELEMENT_TYPE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_DYN_SCREEN_ELEMENTS.ELEMENT_TYPE_CODE
     *
     * @param ELEMENT_TYPE_CODE the value for SYS_DYN_SCREEN_ELEMENTS.ELEMENT_TYPE_CODE
     */
    public void setELEMENT_TYPE_CODE(String ELEMENT_TYPE_CODE) {
        this.ELEMENT_TYPE_CODE = ELEMENT_TYPE_CODE == null ? null : ELEMENT_TYPE_CODE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_DYN_SCREEN_ELEMENTS.CREATED_BY
     *
     * @return the value of SYS_DYN_SCREEN_ELEMENTS.CREATED_BY
     */
    public String getCREATED_BY() {
        return CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_DYN_SCREEN_ELEMENTS.CREATED_BY
     *
     * @param CREATED_BY the value for SYS_DYN_SCREEN_ELEMENTS.CREATED_BY
     */
    public void setCREATED_BY(String CREATED_BY) {
        this.CREATED_BY = CREATED_BY == null ? null : CREATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_DYN_SCREEN_ELEMENTS.CREATED_DATE
     *
     * @return the value of SYS_DYN_SCREEN_ELEMENTS.CREATED_DATE
     */
    public Date getCREATED_DATE() {
        return CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_DYN_SCREEN_ELEMENTS.CREATED_DATE
     *
     * @param CREATED_DATE the value for SYS_DYN_SCREEN_ELEMENTS.CREATED_DATE
     */
    public void setCREATED_DATE(Date CREATED_DATE) {
        this.CREATED_DATE = CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_DYN_SCREEN_ELEMENTS.MODIFIED_BY
     *
     * @return the value of SYS_DYN_SCREEN_ELEMENTS.MODIFIED_BY
     */
    public String getMODIFIED_BY() {
        return MODIFIED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_DYN_SCREEN_ELEMENTS.MODIFIED_BY
     *
     * @param MODIFIED_BY the value for SYS_DYN_SCREEN_ELEMENTS.MODIFIED_BY
     */
    public void setMODIFIED_BY(String MODIFIED_BY) {
        this.MODIFIED_BY = MODIFIED_BY == null ? null : MODIFIED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_DYN_SCREEN_ELEMENTS.MODIFIED_DATE
     *
     * @return the value of SYS_DYN_SCREEN_ELEMENTS.MODIFIED_DATE
     */
    public Date getMODIFIED_DATE() {
        return MODIFIED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_DYN_SCREEN_ELEMENTS.MODIFIED_DATE
     *
     * @param MODIFIED_DATE the value for SYS_DYN_SCREEN_ELEMENTS.MODIFIED_DATE
     */
    public void setMODIFIED_DATE(Date MODIFIED_DATE) {
        this.MODIFIED_DATE = MODIFIED_DATE;
    }

    public BigDecimal getTECH_ID()
    {
        return TECH_ID;
    }

    public void setTECH_ID(BigDecimal tECH_ID)
    {
        TECH_ID = tECH_ID;
    }

    public BigDecimal getPARENT_TECH_ID()
    {
        return PARENT_TECH_ID;
    }

    public void setPARENT_TECH_ID(BigDecimal pARENT_TECH_ID)
    {
        PARENT_TECH_ID = pARENT_TECH_ID;
    }
}