package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;

public class SYS_CONVERT_NUMBER_TO_WORDSVOKey extends BaseVO {
    /**
     * This field corresponds to the database column SYS_CONVERT_NUMBER_TO_WORDS.BASE_UNIT
     */
    private String BASE_UNIT;

    /**
     * This field corresponds to the database column SYS_CONVERT_NUMBER_TO_WORDS.LANG_CODE
     */
    private String LANG_CODE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_CONVERT_NUMBER_TO_WORDS.BASE_UNIT
     *
     * @return the value of SYS_CONVERT_NUMBER_TO_WORDS.BASE_UNIT
     */
    public String getBASE_UNIT() {
        return BASE_UNIT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_CONVERT_NUMBER_TO_WORDS.BASE_UNIT
     *
     * @param BASE_UNIT the value for SYS_CONVERT_NUMBER_TO_WORDS.BASE_UNIT
     */
    public void setBASE_UNIT(String BASE_UNIT) {
        this.BASE_UNIT = BASE_UNIT == null ? null : BASE_UNIT.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_CONVERT_NUMBER_TO_WORDS.LANG_CODE
     *
     * @return the value of SYS_CONVERT_NUMBER_TO_WORDS.LANG_CODE
     */
    public String getLANG_CODE() {
        return LANG_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_CONVERT_NUMBER_TO_WORDS.LANG_CODE
     *
     * @param LANG_CODE the value for SYS_CONVERT_NUMBER_TO_WORDS.LANG_CODE
     */
    public void setLANG_CODE(String LANG_CODE) {
        this.LANG_CODE = LANG_CODE == null ? null : LANG_CODE.trim();
    }
}