package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;
import java.util.Date;

public class SYS_PARAM_ELEM_ACTIVITIESVO extends BaseVO {
    /**
     * This field corresponds to the database column SYS_PARAM_ELEM_ACTIVITIES.SEQUENCE_ID
     */
    private BigDecimal SEQUENCE_ID;

    /**
     * This field corresponds to the database column SYS_PARAM_ELEM_ACTIVITIES.APP_NAME
     */
    private String APP_NAME;

    /**
     * This field corresponds to the database column SYS_PARAM_ELEM_ACTIVITIES.PROG_REF
     */
    private String PROG_REF;

    /**
     * This field corresponds to the database column SYS_PARAM_ELEM_ACTIVITIES.FLD_IDENTIFIER
     */
    private BigDecimal FLD_IDENTIFIER;

    /**
     * This field corresponds to the database column SYS_PARAM_ELEM_ACTIVITIES.ACTIVITY_TYPE
     */
    private String ACTIVITY_TYPE;

    /**
     * This field corresponds to the database column SYS_PARAM_ELEM_ACTIVITIES.ACTIVITY_ID
     */
    private BigDecimal ACTIVITY_ID;

    /**
     * This field corresponds to the database column SYS_PARAM_ELEM_ACTIVITIES.DESCRIPTION
     */
    private String DESCRIPTION;

    /**
     * This field corresponds to the database column SYS_PARAM_ELEM_ACTIVITIES.PROCEED_ON_FAIL
     */
    private String PROCEED_ON_FAIL;
    
    /**
     * This field corresponds to the database column SYS_PARAM_ELEM_ACTIVITIES.ACTIVE
     */
    private String ACTIVITY_ENABLE_YN;

    /**
     * This field corresponds to the database column SYS_PARAM_ELEM_ACTIVITIES.SCREEN_WIDTH
     */
    private BigDecimal SCREEN_WIDTH;

    /**
     * This field corresponds to the database column SYS_PARAM_ELEM_ACTIVITIES.SCREEN_HEIGHT
     */
    private BigDecimal SCREEN_HEIGHT;

    /**
     * This field corresponds to the database column SYS_PARAM_ELEM_ACTIVITIES.CREATED_BY
     */
    private String CREATED_BY;

    /**
     * This field corresponds to the database column SYS_PARAM_ELEM_ACTIVITIES.CREATED_DATE
     */
    private Date CREATED_DATE;

    /**
     * This field corresponds to the database column SYS_PARAM_ELEM_ACTIVITIES.MODIFIED_BY
     */
    private String MODIFIED_BY;

    /**
     * This field corresponds to the database column SYS_PARAM_ELEM_ACTIVITIES.MODIFIED_DATE
     */
    private Date MODIFIED_DATE;

    /**
     * This field corresponds to the database column SYS_PARAM_ELEM_ACTIVITIES.PROCEED_ON_EXPRESSION
     */
    private String PROCEED_ON_EXPRESSION;
    
    /**
     * This field corresponds to the database column SYS_PARAM_ELEM_ACTIVITIES.SCREEN_TITLE
     */
    private String SCREEN_TITLE;

    /**
     * This field corresponds to the database column SYS_PARAM_ELEM_ACTIVITIES.OBJ_DISPLAY_ID
     */
    private BigDecimal OBJ_DISPLAY_ID;
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_ELEM_ACTIVITIES.SEQUENCE_ID
     *
     * @return the value of SYS_PARAM_ELEM_ACTIVITIES.SEQUENCE_ID
     */
    public BigDecimal getSEQUENCE_ID() {
        return SEQUENCE_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_ELEM_ACTIVITIES.SEQUENCE_ID
     *
     * @param SEQUENCE_ID the value for SYS_PARAM_ELEM_ACTIVITIES.SEQUENCE_ID
     */
    public void setSEQUENCE_ID(BigDecimal SEQUENCE_ID) {
        this.SEQUENCE_ID = SEQUENCE_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_ELEM_ACTIVITIES.APP_NAME
     *
     * @return the value of SYS_PARAM_ELEM_ACTIVITIES.APP_NAME
     */
    public String getAPP_NAME() {
        return APP_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_ELEM_ACTIVITIES.APP_NAME
     *
     * @param APP_NAME the value for SYS_PARAM_ELEM_ACTIVITIES.APP_NAME
     */
    public void setAPP_NAME(String APP_NAME) {
        this.APP_NAME = APP_NAME == null ? null : APP_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_ELEM_ACTIVITIES.PROG_REF
     *
     * @return the value of SYS_PARAM_ELEM_ACTIVITIES.PROG_REF
     */
    public String getPROG_REF() {
        return PROG_REF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_ELEM_ACTIVITIES.PROG_REF
     *
     * @param PROG_REF the value for SYS_PARAM_ELEM_ACTIVITIES.PROG_REF
     */
    public void setPROG_REF(String PROG_REF) {
        this.PROG_REF = PROG_REF == null ? null : PROG_REF.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_ELEM_ACTIVITIES.FLD_IDENTIFIER
     *
     * @return the value of SYS_PARAM_ELEM_ACTIVITIES.FLD_IDENTIFIER
     */
    public BigDecimal getFLD_IDENTIFIER() {
        return FLD_IDENTIFIER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_ELEM_ACTIVITIES.FLD_IDENTIFIER
     *
     * @param FLD_IDENTIFIER the value for SYS_PARAM_ELEM_ACTIVITIES.FLD_IDENTIFIER
     */
    public void setFLD_IDENTIFIER(BigDecimal FLD_IDENTIFIER) {
        this.FLD_IDENTIFIER = FLD_IDENTIFIER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_ELEM_ACTIVITIES.ACTIVITY_TYPE
     *
     * @return the value of SYS_PARAM_ELEM_ACTIVITIES.ACTIVITY_TYPE
     */
    public String getACTIVITY_TYPE() {
        return ACTIVITY_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_ELEM_ACTIVITIES.ACTIVITY_TYPE
     *
     * @param ACTIVITY_TYPE the value for SYS_PARAM_ELEM_ACTIVITIES.ACTIVITY_TYPE
     */
    public void setACTIVITY_TYPE(String ACTIVITY_TYPE) {
        this.ACTIVITY_TYPE = ACTIVITY_TYPE == null ? null : ACTIVITY_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_ELEM_ACTIVITIES.ACTIVITY_ID
     *
     * @return the value of SYS_PARAM_ELEM_ACTIVITIES.ACTIVITY_ID
     */
    public BigDecimal getACTIVITY_ID() {
        return ACTIVITY_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_ELEM_ACTIVITIES.ACTIVITY_ID
     *
     * @param ACTIVITY_ID the value for SYS_PARAM_ELEM_ACTIVITIES.ACTIVITY_ID
     */
    public void setACTIVITY_ID(BigDecimal ACTIVITY_ID) {
        this.ACTIVITY_ID = ACTIVITY_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_ELEM_ACTIVITIES.DESCRIPTION
     *
     * @return the value of SYS_PARAM_ELEM_ACTIVITIES.DESCRIPTION
     */
    public String getDESCRIPTION() {
        return DESCRIPTION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_ELEM_ACTIVITIES.DESCRIPTION
     *
     * @param DESCRIPTION the value for SYS_PARAM_ELEM_ACTIVITIES.DESCRIPTION
     */
    public void setDESCRIPTION(String DESCRIPTION) {
        this.DESCRIPTION = DESCRIPTION == null ? null : DESCRIPTION.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_ELEM_ACTIVITIES.PROCEED_ON_FAIL
     *
     * @return the value of SYS_PARAM_ELEM_ACTIVITIES.PROCEED_ON_FAIL
     */
    public String getPROCEED_ON_FAIL() {
        return PROCEED_ON_FAIL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_ELEM_ACTIVITIES.PROCEED_ON_FAIL
     *
     * @param PROCEED_ON_FAIL the value for SYS_PARAM_ELEM_ACTIVITIES.PROCEED_ON_FAIL
     */
    public void setPROCEED_ON_FAIL(String PROCEED_ON_FAIL) {
        this.PROCEED_ON_FAIL = PROCEED_ON_FAIL == null ? null : PROCEED_ON_FAIL.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_ELEM_ACTIVITIES.SCREEN_WIDTH
     *
     * @return the value of SYS_PARAM_ELEM_ACTIVITIES.SCREEN_WIDTH
     */
    public BigDecimal getSCREEN_WIDTH() {
        return SCREEN_WIDTH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_ELEM_ACTIVITIES.SCREEN_WIDTH
     *
     * @param SCREEN_WIDTH the value for SYS_PARAM_ELEM_ACTIVITIES.SCREEN_WIDTH
     */
    public void setSCREEN_WIDTH(BigDecimal SCREEN_WIDTH) {
        this.SCREEN_WIDTH = SCREEN_WIDTH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_ELEM_ACTIVITIES.SCREEN_HEIGHT
     *
     * @return the value of SYS_PARAM_ELEM_ACTIVITIES.SCREEN_HEIGHT
     */
    public BigDecimal getSCREEN_HEIGHT() {
        return SCREEN_HEIGHT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_ELEM_ACTIVITIES.SCREEN_HEIGHT
     *
     * @param SCREEN_HEIGHT the value for SYS_PARAM_ELEM_ACTIVITIES.SCREEN_HEIGHT
     */
    public void setSCREEN_HEIGHT(BigDecimal SCREEN_HEIGHT) {
        this.SCREEN_HEIGHT = SCREEN_HEIGHT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_ELEM_ACTIVITIES.CREATED_BY
     *
     * @return the value of SYS_PARAM_ELEM_ACTIVITIES.CREATED_BY
     */
    public String getCREATED_BY() {
        return CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_ELEM_ACTIVITIES.CREATED_BY
     *
     * @param CREATED_BY the value for SYS_PARAM_ELEM_ACTIVITIES.CREATED_BY
     */
    public void setCREATED_BY(String CREATED_BY) {
        this.CREATED_BY = CREATED_BY == null ? null : CREATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_ELEM_ACTIVITIES.CREATED_DATE
     *
     * @return the value of SYS_PARAM_ELEM_ACTIVITIES.CREATED_DATE
     */
    public Date getCREATED_DATE() {
        return CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_ELEM_ACTIVITIES.CREATED_DATE
     *
     * @param CREATED_DATE the value for SYS_PARAM_ELEM_ACTIVITIES.CREATED_DATE
     */
    public void setCREATED_DATE(Date CREATED_DATE) {
        this.CREATED_DATE = CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_ELEM_ACTIVITIES.MODIFIED_BY
     *
     * @return the value of SYS_PARAM_ELEM_ACTIVITIES.MODIFIED_BY
     */
    public String getMODIFIED_BY() {
        return MODIFIED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_ELEM_ACTIVITIES.MODIFIED_BY
     *
     * @param MODIFIED_BY the value for SYS_PARAM_ELEM_ACTIVITIES.MODIFIED_BY
     */
    public void setMODIFIED_BY(String MODIFIED_BY) {
        this.MODIFIED_BY = MODIFIED_BY == null ? null : MODIFIED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_ELEM_ACTIVITIES.MODIFIED_DATE
     *
     * @return the value of SYS_PARAM_ELEM_ACTIVITIES.MODIFIED_DATE
     */
    public Date getMODIFIED_DATE() {
        return MODIFIED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_ELEM_ACTIVITIES.MODIFIED_DATE
     *
     * @param MODIFIED_DATE the value for SYS_PARAM_ELEM_ACTIVITIES.MODIFIED_DATE
     */
    public void setMODIFIED_DATE(Date MODIFIED_DATE) {
        this.MODIFIED_DATE = MODIFIED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_ELEM_ACTIVITIES.PROCEED_ON_EXPRESSION
     *
     * @return the value of SYS_PARAM_ELEM_ACTIVITIES.PROCEED_ON_EXPRESSION
     */
    public String getPROCEED_ON_EXPRESSION() {
        return PROCEED_ON_EXPRESSION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_ELEM_ACTIVITIES.PROCEED_ON_EXPRESSION
     *
     * @param PROCEED_ON_EXPRESSION the value for SYS_PARAM_ELEM_ACTIVITIES.PROCEED_ON_EXPRESSION
     */
    public void setPROCEED_ON_EXPRESSION(String PROCEED_ON_EXPRESSION) {
        this.PROCEED_ON_EXPRESSION = PROCEED_ON_EXPRESSION == null ? null : PROCEED_ON_EXPRESSION.trim();
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_ELEM_ACTIVITIES.SCREEN_TITLE
     *
     * @return the value of SYS_PARAM_ELEM_ACTIVITIES.SCREEN_TITLE
     */
    public String getSCREEN_TITLE() {
	return SCREEN_TITLE;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_ELEM_ACTIVITIES.SCREEN_TITLE
     *
     * @param SCREEN_TITLE the value for SYS_PARAM_ELEM_ACTIVITIES.SCREEN_TITLE
     */
    public void setSCREEN_TITLE(String SCREEN_TITLE) {
	this.SCREEN_TITLE = SCREEN_TITLE == null ? null : SCREEN_TITLE.trim();
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_ELEM_ACTIVITIES.OBJ_DISPLAY_ID
     *
     * @return the value of SYS_PARAM_ELEM_ACTIVITIES.OBJ_DISPLAY_ID
     */
    public BigDecimal getOBJ_DISPLAY_ID() {
        return OBJ_DISPLAY_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_ELEM_ACTIVITIES.OBJ_DISPLAY_ID
     *
     * @param OBJ_DISPLAY_ID the value for SYS_PARAM_ELEM_ACTIVITIES.OBJ_DISPLAY_ID
     */
    public void setOBJ_DISPLAY_ID(BigDecimal OBJ_DISPLAY_ID) {
        this.OBJ_DISPLAY_ID = OBJ_DISPLAY_ID;
    }
    /**
     * This method sets the value of the database column SYS_PARAM_ELEM_ACTIVITIES.ACTIVITY_ENABLE_YN
     *
     * @param ACTIVITY_ENABLE_YN the value for SYS_PARAM_ELEM_ACTIVITIES.ACTIVITY_ENABLE_YN
     */
    public String getACTIVITY_ENABLE_YN()
    {
        return ACTIVITY_ENABLE_YN;
    }

    public void setACTIVITY_ENABLE_YN(String ACTIVITY_ENABLE_YN)
    {
	this.ACTIVITY_ENABLE_YN = ACTIVITY_ENABLE_YN == null ? null : ACTIVITY_ENABLE_YN.trim();
    }
}