package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class SYS_PARAM_GLOBAL_ACT_ARG_MAPVOKey extends BaseVO {
    /**
     * This field corresponds to the database column SYS_PARAM_GLOBAL_ACT_ARG_MAP.MAP_ID
     */
    private BigDecimal MAP_ID;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_GLOBAL_ACT_ARG_MAP.MAP_ID
     *
     * @return the value of SYS_PARAM_GLOBAL_ACT_ARG_MAP.MAP_ID
     */
    public BigDecimal getMAP_ID() {
        return MAP_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_GLOBAL_ACT_ARG_MAP.MAP_ID
     *
     * @param MAP_ID the value for SYS_PARAM_GLOBAL_ACT_ARG_MAP.MAP_ID
     */
    public void setMAP_ID(BigDecimal MAP_ID) {
        this.MAP_ID = MAP_ID;
    }
}