package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class SYS_PARAM_BPM_ACCESS_RIGHTVOKey extends BaseVO {
    /**
     * This field corresponds to the database column SYS_PARAM_BPM_ACCESS_RIGHT.ENTITY_NAME
     */
    private String ENTITY_NAME;

    /**
     * This field corresponds to the database column SYS_PARAM_BPM_ACCESS_RIGHT.ENTITY_TYPE
     */
    private String ENTITY_TYPE;

    /**
     * This field corresponds to the database column SYS_PARAM_BPM_ACCESS_RIGHT.PROCESS_ID
     */
    private BigDecimal PROCESS_ID;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_BPM_ACCESS_RIGHT.ENTITY_NAME
     *
     * @return the value of SYS_PARAM_BPM_ACCESS_RIGHT.ENTITY_NAME
     */
    public String getENTITY_NAME() {
        return ENTITY_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_BPM_ACCESS_RIGHT.ENTITY_NAME
     *
     * @param ENTITY_NAME the value for SYS_PARAM_BPM_ACCESS_RIGHT.ENTITY_NAME
     */
    public void setENTITY_NAME(String ENTITY_NAME) {
        this.ENTITY_NAME = ENTITY_NAME == null ? null : ENTITY_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_BPM_ACCESS_RIGHT.ENTITY_TYPE
     *
     * @return the value of SYS_PARAM_BPM_ACCESS_RIGHT.ENTITY_TYPE
     */
    public String getENTITY_TYPE() {
        return ENTITY_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_BPM_ACCESS_RIGHT.ENTITY_TYPE
     *
     * @param ENTITY_TYPE the value for SYS_PARAM_BPM_ACCESS_RIGHT.ENTITY_TYPE
     */
    public void setENTITY_TYPE(String ENTITY_TYPE) {
        this.ENTITY_TYPE = ENTITY_TYPE == null ? null : ENTITY_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_BPM_ACCESS_RIGHT.PROCESS_ID
     *
     * @return the value of SYS_PARAM_BPM_ACCESS_RIGHT.PROCESS_ID
     */
    public BigDecimal getPROCESS_ID() {
        return PROCESS_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_BPM_ACCESS_RIGHT.PROCESS_ID
     *
     * @param PROCESS_ID the value for SYS_PARAM_BPM_ACCESS_RIGHT.PROCESS_ID
     */
    public void setPROCESS_ID(BigDecimal PROCESS_ID) {
        this.PROCESS_ID = PROCESS_ID;
    }
}