package com.path.dbmaps.vo;

public class SYS_PARAM_PORTLET_TYPEVO extends SYS_PARAM_PORTLET_TYPEVOKey {
    /**
     * This field corresponds to the database column SYS_PARAM_PORTLET_TYPE.IMG_URL
     */
    private String IMG_URL;

    /**
     * This field corresponds to the database column SYS_PARAM_PORTLET_TYPE.ABV_DESC_KEY
     */
    private String ABV_DESC_KEY;

    /**
     * This field corresponds to the database column SYS_PARAM_PORTLET_TYPE.TITLE_KEY
     */
    private String TITLE_KEY;

    /**
     * This field corresponds to the database column SYS_PARAM_PORTLET_TYPE.PORTLET_URL
     */
    private String PORTLET_URL;

    /**
     * This field corresponds to the database column SYS_PARAM_PORTLET_TYPE.USR_DEFINED_PORTLET_YN
     */
    private String USR_DEFINED_PORTLET_YN;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_PORTLET_TYPE.IMG_URL
     *
     * @return the value of SYS_PARAM_PORTLET_TYPE.IMG_URL
     */
    public String getIMG_URL() {
        return IMG_URL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_PORTLET_TYPE.IMG_URL
     *
     * @param IMG_URL the value for SYS_PARAM_PORTLET_TYPE.IMG_URL
     */
    public void setIMG_URL(String IMG_URL) {
        this.IMG_URL = IMG_URL == null ? null : IMG_URL.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_PORTLET_TYPE.ABV_DESC_KEY
     *
     * @return the value of SYS_PARAM_PORTLET_TYPE.ABV_DESC_KEY
     */
    public String getABV_DESC_KEY() {
        return ABV_DESC_KEY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_PORTLET_TYPE.ABV_DESC_KEY
     *
     * @param ABV_DESC_KEY the value for SYS_PARAM_PORTLET_TYPE.ABV_DESC_KEY
     */
    public void setABV_DESC_KEY(String ABV_DESC_KEY) {
        this.ABV_DESC_KEY = ABV_DESC_KEY == null ? null : ABV_DESC_KEY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_PORTLET_TYPE.TITLE_KEY
     *
     * @return the value of SYS_PARAM_PORTLET_TYPE.TITLE_KEY
     */
    public String getTITLE_KEY() {
        return TITLE_KEY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_PORTLET_TYPE.TITLE_KEY
     *
     * @param TITLE_KEY the value for SYS_PARAM_PORTLET_TYPE.TITLE_KEY
     */
    public void setTITLE_KEY(String TITLE_KEY) {
        this.TITLE_KEY = TITLE_KEY == null ? null : TITLE_KEY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_PORTLET_TYPE.PORTLET_URL
     *
     * @return the value of SYS_PARAM_PORTLET_TYPE.PORTLET_URL
     */
    public String getPORTLET_URL() {
        return PORTLET_URL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_PORTLET_TYPE.PORTLET_URL
     *
     * @param PORTLET_URL the value for SYS_PARAM_PORTLET_TYPE.PORTLET_URL
     */
    public void setPORTLET_URL(String PORTLET_URL) {
        this.PORTLET_URL = PORTLET_URL == null ? null : PORTLET_URL.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_PARAM_PORTLET_TYPE.USR_DEFINED_PORTLET_YN
     *
     * @return the value of SYS_PARAM_PORTLET_TYPE.USR_DEFINED_PORTLET_YN
     */
    public String getUSR_DEFINED_PORTLET_YN() {
        return USR_DEFINED_PORTLET_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_PARAM_PORTLET_TYPE.USR_DEFINED_PORTLET_YN
     *
     * @param USR_DEFINED_PORTLET_YN the value for SYS_PARAM_PORTLET_TYPE.USR_DEFINED_PORTLET_YN
     */
    public void setUSR_DEFINED_PORTLET_YN(String USR_DEFINED_PORTLET_YN) {
        this.USR_DEFINED_PORTLET_YN = USR_DEFINED_PORTLET_YN == null ? null : USR_DEFINED_PORTLET_YN.trim();
    }
}