package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class TFS_MULTI_EFORMVO extends BaseVO {
    /**
     * This field corresponds to the database column TFS_MULTI_EFORM.BRANCH_CODE
     */
    private BigDecimal BRANCH_CODE;

    /**
     * This field corresponds to the database column TFS_MULTI_EFORM.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column TFS_MULTI_EFORM.DOC_TYPE
     */
    private String DOC_TYPE;

    /**
     * This field corresponds to the database column TFS_MULTI_EFORM.EFORM_CERTIFICATION_CODE_NO
     */
    private BigDecimal EFORM_CERTIFICATION_CODE_NO;

    /**
     * This field corresponds to the database column TFS_MULTI_EFORM.TRX_NBR
     */
    private BigDecimal TRX_NBR;

    /**
     * This field corresponds to the database column TFS_MULTI_EFORM.TRX_TYPE
     */
    private BigDecimal TRX_TYPE;

    /**
     * This field corresponds to the database column TFS_MULTI_EFORM.AMENDMENT_TYPE
     */
    private String AMENDMENT_TYPE;

    /**
     * This field corresponds to the database column TFS_MULTI_EFORM.AMEND_OTHER_SL
     */
    private BigDecimal AMEND_OTHER_SL;

    /**
     * This field corresponds to the database column TFS_MULTI_EFORM.UTILIZED_AMOUNT
     */
    private BigDecimal UTILIZED_AMOUNT;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_MULTI_EFORM.BRANCH_CODE
     *
     * @return the value of TFS_MULTI_EFORM.BRANCH_CODE
     */
    public BigDecimal getBRANCH_CODE() {
        return BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_MULTI_EFORM.BRANCH_CODE
     *
     * @param BRANCH_CODE the value for TFS_MULTI_EFORM.BRANCH_CODE
     */
    public void setBRANCH_CODE(BigDecimal BRANCH_CODE) {
        this.BRANCH_CODE = BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_MULTI_EFORM.COMP_CODE
     *
     * @return the value of TFS_MULTI_EFORM.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_MULTI_EFORM.COMP_CODE
     *
     * @param COMP_CODE the value for TFS_MULTI_EFORM.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_MULTI_EFORM.DOC_TYPE
     *
     * @return the value of TFS_MULTI_EFORM.DOC_TYPE
     */
    public String getDOC_TYPE() {
        return DOC_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_MULTI_EFORM.DOC_TYPE
     *
     * @param DOC_TYPE the value for TFS_MULTI_EFORM.DOC_TYPE
     */
    public void setDOC_TYPE(String DOC_TYPE) {
        this.DOC_TYPE = DOC_TYPE == null ? null : DOC_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_MULTI_EFORM.EFORM_CERTIFICATION_CODE_NO
     *
     * @return the value of TFS_MULTI_EFORM.EFORM_CERTIFICATION_CODE_NO
     */
    public BigDecimal getEFORM_CERTIFICATION_CODE_NO() {
        return EFORM_CERTIFICATION_CODE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_MULTI_EFORM.EFORM_CERTIFICATION_CODE_NO
     *
     * @param EFORM_CERTIFICATION_CODE_NO the value for TFS_MULTI_EFORM.EFORM_CERTIFICATION_CODE_NO
     */
    public void setEFORM_CERTIFICATION_CODE_NO(BigDecimal EFORM_CERTIFICATION_CODE_NO) {
        this.EFORM_CERTIFICATION_CODE_NO = EFORM_CERTIFICATION_CODE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_MULTI_EFORM.TRX_NBR
     *
     * @return the value of TFS_MULTI_EFORM.TRX_NBR
     */
    public BigDecimal getTRX_NBR() {
        return TRX_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_MULTI_EFORM.TRX_NBR
     *
     * @param TRX_NBR the value for TFS_MULTI_EFORM.TRX_NBR
     */
    public void setTRX_NBR(BigDecimal TRX_NBR) {
        this.TRX_NBR = TRX_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_MULTI_EFORM.TRX_TYPE
     *
     * @return the value of TFS_MULTI_EFORM.TRX_TYPE
     */
    public BigDecimal getTRX_TYPE() {
        return TRX_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_MULTI_EFORM.TRX_TYPE
     *
     * @param TRX_TYPE the value for TFS_MULTI_EFORM.TRX_TYPE
     */
    public void setTRX_TYPE(BigDecimal TRX_TYPE) {
        this.TRX_TYPE = TRX_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_MULTI_EFORM.AMENDMENT_TYPE
     *
     * @return the value of TFS_MULTI_EFORM.AMENDMENT_TYPE
     */
    public String getAMENDMENT_TYPE() {
        return AMENDMENT_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_MULTI_EFORM.AMENDMENT_TYPE
     *
     * @param AMENDMENT_TYPE the value for TFS_MULTI_EFORM.AMENDMENT_TYPE
     */
    public void setAMENDMENT_TYPE(String AMENDMENT_TYPE) {
        this.AMENDMENT_TYPE = AMENDMENT_TYPE == null ? null : AMENDMENT_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_MULTI_EFORM.AMEND_OTHER_SL
     *
     * @return the value of TFS_MULTI_EFORM.AMEND_OTHER_SL
     */
    public BigDecimal getAMEND_OTHER_SL() {
        return AMEND_OTHER_SL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_MULTI_EFORM.AMEND_OTHER_SL
     *
     * @param AMEND_OTHER_SL the value for TFS_MULTI_EFORM.AMEND_OTHER_SL
     */
    public void setAMEND_OTHER_SL(BigDecimal AMEND_OTHER_SL) {
        this.AMEND_OTHER_SL = AMEND_OTHER_SL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFS_MULTI_EFORM.UTILIZED_AMOUNT
     *
     * @return the value of TFS_MULTI_EFORM.UTILIZED_AMOUNT
     */
    public BigDecimal getUTILIZED_AMOUNT() {
        return UTILIZED_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFS_MULTI_EFORM.UTILIZED_AMOUNT
     *
     * @param UTILIZED_AMOUNT the value for TFS_MULTI_EFORM.UTILIZED_AMOUNT
     */
    public void setUTILIZED_AMOUNT(BigDecimal UTILIZED_AMOUNT) {
        this.UTILIZED_AMOUNT = UTILIZED_AMOUNT;
    }
}