package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;
import java.util.Date;

public class TR_TYPESVO extends TR_TYPESVOKey {
    /**
     * This field corresponds to the database column TR_TYPES.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column TR_TYPES.TR_CODE
     */
    private BigDecimal TR_CODE;

    /**
     * This field corresponds to the database column TR_TYPES.BRIEF_DESC_ENG
     */
    private String BRIEF_DESC_ENG;

    /**
     * This field corresponds to the database column TR_TYPES.LONG_DESC_ENG
     */
    private String LONG_DESC_ENG;

    /**
     * This field corresponds to the database column TR_TYPES.BRIEF_DESC_ARAB
     */
    private String BRIEF_DESC_ARAB;

    /**
     * This field corresponds to the database column TR_TYPES.LONG_DESC_ARAB
     */
    private String LONG_DESC_ARAB;

    /**
     * This field corresponds to the database column TR_TYPES.ALLOW_DELETE_YN
     */
    private String ALLOW_DELETE_YN;

    /**
     * This field corresponds to the database column TR_TYPES.STATUS
     */
    private String STATUS;

    /**
     * This field corresponds to the database column TR_TYPES.CREATED_BY
     */
    private String CREATED_BY;

    /**
     * This field corresponds to the database column TR_TYPES.CREATED_DATE
     */
    private Date CREATED_DATE;

    /**
     * This field corresponds to the database column TR_TYPES.MODIFIED_BY
     */
    private String MODIFIED_BY;

    /**
     * This field corresponds to the database column TR_TYPES.MODIFIED_DATE
     */
    private Date MODIFIED_DATE;

    /**
     * This field corresponds to the database column TR_TYPES.APPROVE_BY
     */
    private String APPROVE_BY;

    /**
     * This field corresponds to the database column TR_TYPES.APPROVE_DATE
     */
    private Date APPROVE_DATE;

    /**
     * This field corresponds to the database column TR_TYPES.DELETED_BY
     */
    private String DELETED_BY;

    /**
     * This field corresponds to the database column TR_TYPES.DELETED_DATE
     */
    private Date DELETED_DATE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TR_TYPES.COMP_CODE
     *
     * @return the value of TR_TYPES.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TR_TYPES.COMP_CODE
     *
     * @param COMP_CODE the value for TR_TYPES.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TR_TYPES.TR_CODE
     *
     * @return the value of TR_TYPES.TR_CODE
     */
    public BigDecimal getTR_CODE() {
        return TR_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TR_TYPES.TR_CODE
     *
     * @param TR_CODE the value for TR_TYPES.TR_CODE
     */
    public void setTR_CODE(BigDecimal TR_CODE) {
        this.TR_CODE = TR_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TR_TYPES.BRIEF_DESC_ENG
     *
     * @return the value of TR_TYPES.BRIEF_DESC_ENG
     */
    public String getBRIEF_DESC_ENG() {
        return BRIEF_DESC_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TR_TYPES.BRIEF_DESC_ENG
     *
     * @param BRIEF_DESC_ENG the value for TR_TYPES.BRIEF_DESC_ENG
     */
    public void setBRIEF_DESC_ENG(String BRIEF_DESC_ENG) {
        this.BRIEF_DESC_ENG = BRIEF_DESC_ENG == null ? null : BRIEF_DESC_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TR_TYPES.LONG_DESC_ENG
     *
     * @return the value of TR_TYPES.LONG_DESC_ENG
     */
    public String getLONG_DESC_ENG() {
        return LONG_DESC_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TR_TYPES.LONG_DESC_ENG
     *
     * @param LONG_DESC_ENG the value for TR_TYPES.LONG_DESC_ENG
     */
    public void setLONG_DESC_ENG(String LONG_DESC_ENG) {
        this.LONG_DESC_ENG = LONG_DESC_ENG == null ? null : LONG_DESC_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TR_TYPES.BRIEF_DESC_ARAB
     *
     * @return the value of TR_TYPES.BRIEF_DESC_ARAB
     */
    public String getBRIEF_DESC_ARAB() {
        return BRIEF_DESC_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TR_TYPES.BRIEF_DESC_ARAB
     *
     * @param BRIEF_DESC_ARAB the value for TR_TYPES.BRIEF_DESC_ARAB
     */
    public void setBRIEF_DESC_ARAB(String BRIEF_DESC_ARAB) {
        this.BRIEF_DESC_ARAB = BRIEF_DESC_ARAB == null ? null : BRIEF_DESC_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TR_TYPES.LONG_DESC_ARAB
     *
     * @return the value of TR_TYPES.LONG_DESC_ARAB
     */
    public String getLONG_DESC_ARAB() {
        return LONG_DESC_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TR_TYPES.LONG_DESC_ARAB
     *
     * @param LONG_DESC_ARAB the value for TR_TYPES.LONG_DESC_ARAB
     */
    public void setLONG_DESC_ARAB(String LONG_DESC_ARAB) {
        this.LONG_DESC_ARAB = LONG_DESC_ARAB == null ? null : LONG_DESC_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TR_TYPES.ALLOW_DELETE_YN
     *
     * @return the value of TR_TYPES.ALLOW_DELETE_YN
     */
    public String getALLOW_DELETE_YN() {
        return ALLOW_DELETE_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TR_TYPES.ALLOW_DELETE_YN
     *
     * @param ALLOW_DELETE_YN the value for TR_TYPES.ALLOW_DELETE_YN
     */
    public void setALLOW_DELETE_YN(String ALLOW_DELETE_YN) {
        this.ALLOW_DELETE_YN = ALLOW_DELETE_YN == null ? null : ALLOW_DELETE_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TR_TYPES.STATUS
     *
     * @return the value of TR_TYPES.STATUS
     */
    public String getSTATUS() {
        return STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TR_TYPES.STATUS
     *
     * @param STATUS the value for TR_TYPES.STATUS
     */
    public void setSTATUS(String STATUS) {
        this.STATUS = STATUS == null ? null : STATUS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TR_TYPES.CREATED_BY
     *
     * @return the value of TR_TYPES.CREATED_BY
     */
    public String getCREATED_BY() {
        return CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TR_TYPES.CREATED_BY
     *
     * @param CREATED_BY the value for TR_TYPES.CREATED_BY
     */
    public void setCREATED_BY(String CREATED_BY) {
        this.CREATED_BY = CREATED_BY == null ? null : CREATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TR_TYPES.CREATED_DATE
     *
     * @return the value of TR_TYPES.CREATED_DATE
     */
    public Date getCREATED_DATE() {
        return CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TR_TYPES.CREATED_DATE
     *
     * @param CREATED_DATE the value for TR_TYPES.CREATED_DATE
     */
    public void setCREATED_DATE(Date CREATED_DATE) {
        this.CREATED_DATE = CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TR_TYPES.MODIFIED_BY
     *
     * @return the value of TR_TYPES.MODIFIED_BY
     */
    public String getMODIFIED_BY() {
        return MODIFIED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TR_TYPES.MODIFIED_BY
     *
     * @param MODIFIED_BY the value for TR_TYPES.MODIFIED_BY
     */
    public void setMODIFIED_BY(String MODIFIED_BY) {
        this.MODIFIED_BY = MODIFIED_BY == null ? null : MODIFIED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TR_TYPES.MODIFIED_DATE
     *
     * @return the value of TR_TYPES.MODIFIED_DATE
     */
    public Date getMODIFIED_DATE() {
        return MODIFIED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TR_TYPES.MODIFIED_DATE
     *
     * @param MODIFIED_DATE the value for TR_TYPES.MODIFIED_DATE
     */
    public void setMODIFIED_DATE(Date MODIFIED_DATE) {
        this.MODIFIED_DATE = MODIFIED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TR_TYPES.APPROVE_BY
     *
     * @return the value of TR_TYPES.APPROVE_BY
     */
    public String getAPPROVE_BY() {
        return APPROVE_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TR_TYPES.APPROVE_BY
     *
     * @param APPROVE_BY the value for TR_TYPES.APPROVE_BY
     */
    public void setAPPROVE_BY(String APPROVE_BY) {
        this.APPROVE_BY = APPROVE_BY == null ? null : APPROVE_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TR_TYPES.APPROVE_DATE
     *
     * @return the value of TR_TYPES.APPROVE_DATE
     */
    public Date getAPPROVE_DATE() {
        return APPROVE_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TR_TYPES.APPROVE_DATE
     *
     * @param APPROVE_DATE the value for TR_TYPES.APPROVE_DATE
     */
    public void setAPPROVE_DATE(Date APPROVE_DATE) {
        this.APPROVE_DATE = APPROVE_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TR_TYPES.DELETED_BY
     *
     * @return the value of TR_TYPES.DELETED_BY
     */
    public String getDELETED_BY() {
        return DELETED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TR_TYPES.DELETED_BY
     *
     * @param DELETED_BY the value for TR_TYPES.DELETED_BY
     */
    public void setDELETED_BY(String DELETED_BY) {
        this.DELETED_BY = DELETED_BY == null ? null : DELETED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TR_TYPES.DELETED_DATE
     *
     * @return the value of TR_TYPES.DELETED_DATE
     */
    public Date getDELETED_DATE() {
        return DELETED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TR_TYPES.DELETED_DATE
     *
     * @param DELETED_DATE the value for TR_TYPES.DELETED_DATE
     */
    public void setDELETED_DATE(Date DELETED_DATE) {
        this.DELETED_DATE = DELETED_DATE;
    }
}