package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class TRS_IBOR_REVALUATION_PROCESSVOKey extends BaseVO {
    /**
     * This field corresponds to the database column TRS_IBOR_REVALUATION_PROCESS.BRANCH_CODE
     */
    private BigDecimal BRANCH_CODE;

    /**
     * This field corresponds to the database column TRS_IBOR_REVALUATION_PROCESS.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column TRS_IBOR_REVALUATION_PROCESS.DEAL_NO
     */
    private BigDecimal DEAL_NO;

    /**
     * This field corresponds to the database column TRS_IBOR_REVALUATION_PROCESS.PLAN_NBR
     */
    private BigDecimal PLAN_NBR;

    /**
     * This field corresponds to the database column TRS_IBOR_REVALUATION_PROCESS.PLAN_SEQ
     */
    private BigDecimal PLAN_SEQ;

    /**
     * This field corresponds to the database column TRS_IBOR_REVALUATION_PROCESS.PROCESS_CODE
     */
    private BigDecimal PROCESS_CODE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_IBOR_REVALUATION_PROCESS.BRANCH_CODE
     *
     * @return the value of TRS_IBOR_REVALUATION_PROCESS.BRANCH_CODE
     */
    public BigDecimal getBRANCH_CODE() {
        return BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_IBOR_REVALUATION_PROCESS.BRANCH_CODE
     *
     * @param BRANCH_CODE the value for TRS_IBOR_REVALUATION_PROCESS.BRANCH_CODE
     */
    public void setBRANCH_CODE(BigDecimal BRANCH_CODE) {
        this.BRANCH_CODE = BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_IBOR_REVALUATION_PROCESS.COMP_CODE
     *
     * @return the value of TRS_IBOR_REVALUATION_PROCESS.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_IBOR_REVALUATION_PROCESS.COMP_CODE
     *
     * @param COMP_CODE the value for TRS_IBOR_REVALUATION_PROCESS.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_IBOR_REVALUATION_PROCESS.DEAL_NO
     *
     * @return the value of TRS_IBOR_REVALUATION_PROCESS.DEAL_NO
     */
    public BigDecimal getDEAL_NO() {
        return DEAL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_IBOR_REVALUATION_PROCESS.DEAL_NO
     *
     * @param DEAL_NO the value for TRS_IBOR_REVALUATION_PROCESS.DEAL_NO
     */
    public void setDEAL_NO(BigDecimal DEAL_NO) {
        this.DEAL_NO = DEAL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_IBOR_REVALUATION_PROCESS.PLAN_NBR
     *
     * @return the value of TRS_IBOR_REVALUATION_PROCESS.PLAN_NBR
     */
    public BigDecimal getPLAN_NBR() {
        return PLAN_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_IBOR_REVALUATION_PROCESS.PLAN_NBR
     *
     * @param PLAN_NBR the value for TRS_IBOR_REVALUATION_PROCESS.PLAN_NBR
     */
    public void setPLAN_NBR(BigDecimal PLAN_NBR) {
        this.PLAN_NBR = PLAN_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_IBOR_REVALUATION_PROCESS.PLAN_SEQ
     *
     * @return the value of TRS_IBOR_REVALUATION_PROCESS.PLAN_SEQ
     */
    public BigDecimal getPLAN_SEQ() {
        return PLAN_SEQ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_IBOR_REVALUATION_PROCESS.PLAN_SEQ
     *
     * @param PLAN_SEQ the value for TRS_IBOR_REVALUATION_PROCESS.PLAN_SEQ
     */
    public void setPLAN_SEQ(BigDecimal PLAN_SEQ) {
        this.PLAN_SEQ = PLAN_SEQ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_IBOR_REVALUATION_PROCESS.PROCESS_CODE
     *
     * @return the value of TRS_IBOR_REVALUATION_PROCESS.PROCESS_CODE
     */
    public BigDecimal getPROCESS_CODE() {
        return PROCESS_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_IBOR_REVALUATION_PROCESS.PROCESS_CODE
     *
     * @param PROCESS_CODE the value for TRS_IBOR_REVALUATION_PROCESS.PROCESS_CODE
     */
    public void setPROCESS_CODE(BigDecimal PROCESS_CODE) {
        this.PROCESS_CODE = PROCESS_CODE;
    }
}