package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;
import java.util.Date;

public class TRS_CY_FORWARD_RATEVOKey extends BaseVO {
    /**
     * This field corresponds to the database column TRS_CY_FORWARD_RATE.BASE_CY_CODE
     */
    private BigDecimal BASE_CY_CODE;

    /**
     * This field corresponds to the database column TRS_CY_FORWARD_RATE.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column TRS_CY_FORWARD_RATE.CURRENCY_CODE
     */
    private BigDecimal CURRENCY_CODE;

    /**
     * This field corresponds to the database column TRS_CY_FORWARD_RATE.DATE_RATE
     */
    private Date DATE_RATE;

    /**
     * This field corresponds to the database column TRS_CY_FORWARD_RATE.SETTLEMENT_DATE
     */
    private Date SETTLEMENT_DATE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_CY_FORWARD_RATE.BASE_CY_CODE
     *
     * @return the value of TRS_CY_FORWARD_RATE.BASE_CY_CODE
     */
    public BigDecimal getBASE_CY_CODE() {
        return BASE_CY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_CY_FORWARD_RATE.BASE_CY_CODE
     *
     * @param BASE_CY_CODE the value for TRS_CY_FORWARD_RATE.BASE_CY_CODE
     */
    public void setBASE_CY_CODE(BigDecimal BASE_CY_CODE) {
        this.BASE_CY_CODE = BASE_CY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_CY_FORWARD_RATE.COMP_CODE
     *
     * @return the value of TRS_CY_FORWARD_RATE.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_CY_FORWARD_RATE.COMP_CODE
     *
     * @param COMP_CODE the value for TRS_CY_FORWARD_RATE.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_CY_FORWARD_RATE.CURRENCY_CODE
     *
     * @return the value of TRS_CY_FORWARD_RATE.CURRENCY_CODE
     */
    public BigDecimal getCURRENCY_CODE() {
        return CURRENCY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_CY_FORWARD_RATE.CURRENCY_CODE
     *
     * @param CURRENCY_CODE the value for TRS_CY_FORWARD_RATE.CURRENCY_CODE
     */
    public void setCURRENCY_CODE(BigDecimal CURRENCY_CODE) {
        this.CURRENCY_CODE = CURRENCY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_CY_FORWARD_RATE.DATE_RATE
     *
     * @return the value of TRS_CY_FORWARD_RATE.DATE_RATE
     */
    public Date getDATE_RATE() {
        return DATE_RATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_CY_FORWARD_RATE.DATE_RATE
     *
     * @param DATE_RATE the value for TRS_CY_FORWARD_RATE.DATE_RATE
     */
    public void setDATE_RATE(Date DATE_RATE) {
        this.DATE_RATE = DATE_RATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_CY_FORWARD_RATE.SETTLEMENT_DATE
     *
     * @return the value of TRS_CY_FORWARD_RATE.SETTLEMENT_DATE
     */
    public Date getSETTLEMENT_DATE() {
        return SETTLEMENT_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_CY_FORWARD_RATE.SETTLEMENT_DATE
     *
     * @param SETTLEMENT_DATE the value for TRS_CY_FORWARD_RATE.SETTLEMENT_DATE
     */
    public void setSETTLEMENT_DATE(Date SETTLEMENT_DATE) {
        this.SETTLEMENT_DATE = SETTLEMENT_DATE;
    }
}