package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class TRS_CHARGES_REVERSAL_DETVO extends TRS_CHARGES_REVERSAL_DETVOKey {
    /**
     * This field corresponds to the database column TRS_CHARGES_REVERSAL_DET.REVERSE_YN
     */
    private BigDecimal REVERSE_YN;

    /**
     * This field corresponds to the database column TRS_CHARGES_REVERSAL_DET.CHARGE_CODE
     */
    private BigDecimal CHARGE_CODE;

    /**
     * This field corresponds to the database column TRS_CHARGES_REVERSAL_DET.CHARGE_LINK_DEAL_NBR
     */
    private BigDecimal CHARGE_LINK_DEAL_NBR;

    /**
     * This field corresponds to the database column TRS_CHARGES_REVERSAL_DET.CHARGE_LINK_TRX_TYPE
     */
    private String CHARGE_LINK_TRX_TYPE;

    /**
     * This field corresponds to the database column TRS_CHARGES_REVERSAL_DET.CHARGE_LINK_TRX_NBR
     */
    private BigDecimal CHARGE_LINK_TRX_NBR;

    /**
     * This field corresponds to the database column TRS_CHARGES_REVERSAL_DET.CHARGE_LINK_SL_NBR
     */
    private BigDecimal CHARGE_LINK_SL_NBR;

    /**
     * This field corresponds to the database column TRS_CHARGES_REVERSAL_DET.CHARGE_LINK_LINE_NBR
     */
    private BigDecimal CHARGE_LINK_LINE_NBR;

    /**
     * This field corresponds to the database column TRS_CHARGES_REVERSAL_DET.CHARGE_AMOUNT_FC
     */
    private BigDecimal CHARGE_AMOUNT_FC;

    /**
     * This field corresponds to the database column TRS_CHARGES_REVERSAL_DET.REVERSAL_AMOUNT_FC
     */
    private BigDecimal REVERSAL_AMOUNT_FC;

    /**
     * This field corresponds to the database column TRS_CHARGES_REVERSAL_DET.CURRENCY_CODE
     */
    private BigDecimal CURRENCY_CODE;

    /**
     * This field corresponds to the database column TRS_CHARGES_REVERSAL_DET.CY_RATE
     */
    private BigDecimal CY_RATE;

    /**
     * This field corresponds to the database column TRS_CHARGES_REVERSAL_DET.CHARGE_AMOUNT_CV
     */
    private BigDecimal CHARGE_AMOUNT_CV;

    /**
     * This field corresponds to the database column TRS_CHARGES_REVERSAL_DET.REVERSAL_AMOUNT_CV
     */
    private BigDecimal REVERSAL_AMOUNT_CV;

    /**
     * This field corresponds to the database column TRS_CHARGES_REVERSAL_DET.CR_ACC_BRANCH
     */
    private BigDecimal CR_ACC_BRANCH;

    /**
     * This field corresponds to the database column TRS_CHARGES_REVERSAL_DET.CR_ACC_CURRENCY
     */
    private BigDecimal CR_ACC_CURRENCY;

    /**
     * This field corresponds to the database column TRS_CHARGES_REVERSAL_DET.CR_ACC_GL
     */
    private BigDecimal CR_ACC_GL;

    /**
     * This field corresponds to the database column TRS_CHARGES_REVERSAL_DET.CR_ACC_CIF_SUB_NO
     */
    private BigDecimal CR_ACC_CIF_SUB_NO;

    /**
     * This field corresponds to the database column TRS_CHARGES_REVERSAL_DET.CR_ACC_SL_NO
     */
    private BigDecimal CR_ACC_SL_NO;

    /**
     * This field corresponds to the database column TRS_CHARGES_REVERSAL_DET.DR_ACC_BRANCH
     */
    private BigDecimal DR_ACC_BRANCH;

    /**
     * This field corresponds to the database column TRS_CHARGES_REVERSAL_DET.DR_ACC_CURRENCY
     */
    private BigDecimal DR_ACC_CURRENCY;

    /**
     * This field corresponds to the database column TRS_CHARGES_REVERSAL_DET.DR_ACC_GL
     */
    private BigDecimal DR_ACC_GL;

    /**
     * This field corresponds to the database column TRS_CHARGES_REVERSAL_DET.DR_ACC_CIF_SUB_NO
     */
    private BigDecimal DR_ACC_CIF_SUB_NO;

    /**
     * This field corresponds to the database column TRS_CHARGES_REVERSAL_DET.DR_ACC_SL_NO
     */
    private BigDecimal DR_ACC_SL_NO;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_CHARGES_REVERSAL_DET.REVERSE_YN
     *
     * @return the value of TRS_CHARGES_REVERSAL_DET.REVERSE_YN
     */
    public BigDecimal getREVERSE_YN() {
        return REVERSE_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_CHARGES_REVERSAL_DET.REVERSE_YN
     *
     * @param REVERSE_YN the value for TRS_CHARGES_REVERSAL_DET.REVERSE_YN
     */
    public void setREVERSE_YN(BigDecimal REVERSE_YN) {
        this.REVERSE_YN = REVERSE_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_CHARGES_REVERSAL_DET.CHARGE_CODE
     *
     * @return the value of TRS_CHARGES_REVERSAL_DET.CHARGE_CODE
     */
    public BigDecimal getCHARGE_CODE() {
        return CHARGE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_CHARGES_REVERSAL_DET.CHARGE_CODE
     *
     * @param CHARGE_CODE the value for TRS_CHARGES_REVERSAL_DET.CHARGE_CODE
     */
    public void setCHARGE_CODE(BigDecimal CHARGE_CODE) {
        this.CHARGE_CODE = CHARGE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_CHARGES_REVERSAL_DET.CHARGE_LINK_DEAL_NBR
     *
     * @return the value of TRS_CHARGES_REVERSAL_DET.CHARGE_LINK_DEAL_NBR
     */
    public BigDecimal getCHARGE_LINK_DEAL_NBR() {
        return CHARGE_LINK_DEAL_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_CHARGES_REVERSAL_DET.CHARGE_LINK_DEAL_NBR
     *
     * @param CHARGE_LINK_DEAL_NBR the value for TRS_CHARGES_REVERSAL_DET.CHARGE_LINK_DEAL_NBR
     */
    public void setCHARGE_LINK_DEAL_NBR(BigDecimal CHARGE_LINK_DEAL_NBR) {
        this.CHARGE_LINK_DEAL_NBR = CHARGE_LINK_DEAL_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_CHARGES_REVERSAL_DET.CHARGE_LINK_TRX_TYPE
     *
     * @return the value of TRS_CHARGES_REVERSAL_DET.CHARGE_LINK_TRX_TYPE
     */
    public String getCHARGE_LINK_TRX_TYPE() {
        return CHARGE_LINK_TRX_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_CHARGES_REVERSAL_DET.CHARGE_LINK_TRX_TYPE
     *
     * @param CHARGE_LINK_TRX_TYPE the value for TRS_CHARGES_REVERSAL_DET.CHARGE_LINK_TRX_TYPE
     */
    public void setCHARGE_LINK_TRX_TYPE(String CHARGE_LINK_TRX_TYPE) {
        this.CHARGE_LINK_TRX_TYPE = CHARGE_LINK_TRX_TYPE == null ? null : CHARGE_LINK_TRX_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_CHARGES_REVERSAL_DET.CHARGE_LINK_TRX_NBR
     *
     * @return the value of TRS_CHARGES_REVERSAL_DET.CHARGE_LINK_TRX_NBR
     */
    public BigDecimal getCHARGE_LINK_TRX_NBR() {
        return CHARGE_LINK_TRX_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_CHARGES_REVERSAL_DET.CHARGE_LINK_TRX_NBR
     *
     * @param CHARGE_LINK_TRX_NBR the value for TRS_CHARGES_REVERSAL_DET.CHARGE_LINK_TRX_NBR
     */
    public void setCHARGE_LINK_TRX_NBR(BigDecimal CHARGE_LINK_TRX_NBR) {
        this.CHARGE_LINK_TRX_NBR = CHARGE_LINK_TRX_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_CHARGES_REVERSAL_DET.CHARGE_LINK_SL_NBR
     *
     * @return the value of TRS_CHARGES_REVERSAL_DET.CHARGE_LINK_SL_NBR
     */
    public BigDecimal getCHARGE_LINK_SL_NBR() {
        return CHARGE_LINK_SL_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_CHARGES_REVERSAL_DET.CHARGE_LINK_SL_NBR
     *
     * @param CHARGE_LINK_SL_NBR the value for TRS_CHARGES_REVERSAL_DET.CHARGE_LINK_SL_NBR
     */
    public void setCHARGE_LINK_SL_NBR(BigDecimal CHARGE_LINK_SL_NBR) {
        this.CHARGE_LINK_SL_NBR = CHARGE_LINK_SL_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_CHARGES_REVERSAL_DET.CHARGE_LINK_LINE_NBR
     *
     * @return the value of TRS_CHARGES_REVERSAL_DET.CHARGE_LINK_LINE_NBR
     */
    public BigDecimal getCHARGE_LINK_LINE_NBR() {
        return CHARGE_LINK_LINE_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_CHARGES_REVERSAL_DET.CHARGE_LINK_LINE_NBR
     *
     * @param CHARGE_LINK_LINE_NBR the value for TRS_CHARGES_REVERSAL_DET.CHARGE_LINK_LINE_NBR
     */
    public void setCHARGE_LINK_LINE_NBR(BigDecimal CHARGE_LINK_LINE_NBR) {
        this.CHARGE_LINK_LINE_NBR = CHARGE_LINK_LINE_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_CHARGES_REVERSAL_DET.CHARGE_AMOUNT_FC
     *
     * @return the value of TRS_CHARGES_REVERSAL_DET.CHARGE_AMOUNT_FC
     */
    public BigDecimal getCHARGE_AMOUNT_FC() {
        return CHARGE_AMOUNT_FC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_CHARGES_REVERSAL_DET.CHARGE_AMOUNT_FC
     *
     * @param CHARGE_AMOUNT_FC the value for TRS_CHARGES_REVERSAL_DET.CHARGE_AMOUNT_FC
     */
    public void setCHARGE_AMOUNT_FC(BigDecimal CHARGE_AMOUNT_FC) {
        this.CHARGE_AMOUNT_FC = CHARGE_AMOUNT_FC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_CHARGES_REVERSAL_DET.REVERSAL_AMOUNT_FC
     *
     * @return the value of TRS_CHARGES_REVERSAL_DET.REVERSAL_AMOUNT_FC
     */
    public BigDecimal getREVERSAL_AMOUNT_FC() {
        return REVERSAL_AMOUNT_FC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_CHARGES_REVERSAL_DET.REVERSAL_AMOUNT_FC
     *
     * @param REVERSAL_AMOUNT_FC the value for TRS_CHARGES_REVERSAL_DET.REVERSAL_AMOUNT_FC
     */
    public void setREVERSAL_AMOUNT_FC(BigDecimal REVERSAL_AMOUNT_FC) {
        this.REVERSAL_AMOUNT_FC = REVERSAL_AMOUNT_FC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_CHARGES_REVERSAL_DET.CURRENCY_CODE
     *
     * @return the value of TRS_CHARGES_REVERSAL_DET.CURRENCY_CODE
     */
    public BigDecimal getCURRENCY_CODE() {
        return CURRENCY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_CHARGES_REVERSAL_DET.CURRENCY_CODE
     *
     * @param CURRENCY_CODE the value for TRS_CHARGES_REVERSAL_DET.CURRENCY_CODE
     */
    public void setCURRENCY_CODE(BigDecimal CURRENCY_CODE) {
        this.CURRENCY_CODE = CURRENCY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_CHARGES_REVERSAL_DET.CY_RATE
     *
     * @return the value of TRS_CHARGES_REVERSAL_DET.CY_RATE
     */
    public BigDecimal getCY_RATE() {
        return CY_RATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_CHARGES_REVERSAL_DET.CY_RATE
     *
     * @param CY_RATE the value for TRS_CHARGES_REVERSAL_DET.CY_RATE
     */
    public void setCY_RATE(BigDecimal CY_RATE) {
        this.CY_RATE = CY_RATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_CHARGES_REVERSAL_DET.CHARGE_AMOUNT_CV
     *
     * @return the value of TRS_CHARGES_REVERSAL_DET.CHARGE_AMOUNT_CV
     */
    public BigDecimal getCHARGE_AMOUNT_CV() {
        return CHARGE_AMOUNT_CV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_CHARGES_REVERSAL_DET.CHARGE_AMOUNT_CV
     *
     * @param CHARGE_AMOUNT_CV the value for TRS_CHARGES_REVERSAL_DET.CHARGE_AMOUNT_CV
     */
    public void setCHARGE_AMOUNT_CV(BigDecimal CHARGE_AMOUNT_CV) {
        this.CHARGE_AMOUNT_CV = CHARGE_AMOUNT_CV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_CHARGES_REVERSAL_DET.REVERSAL_AMOUNT_CV
     *
     * @return the value of TRS_CHARGES_REVERSAL_DET.REVERSAL_AMOUNT_CV
     */
    public BigDecimal getREVERSAL_AMOUNT_CV() {
        return REVERSAL_AMOUNT_CV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_CHARGES_REVERSAL_DET.REVERSAL_AMOUNT_CV
     *
     * @param REVERSAL_AMOUNT_CV the value for TRS_CHARGES_REVERSAL_DET.REVERSAL_AMOUNT_CV
     */
    public void setREVERSAL_AMOUNT_CV(BigDecimal REVERSAL_AMOUNT_CV) {
        this.REVERSAL_AMOUNT_CV = REVERSAL_AMOUNT_CV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_CHARGES_REVERSAL_DET.CR_ACC_BRANCH
     *
     * @return the value of TRS_CHARGES_REVERSAL_DET.CR_ACC_BRANCH
     */
    public BigDecimal getCR_ACC_BRANCH() {
        return CR_ACC_BRANCH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_CHARGES_REVERSAL_DET.CR_ACC_BRANCH
     *
     * @param CR_ACC_BRANCH the value for TRS_CHARGES_REVERSAL_DET.CR_ACC_BRANCH
     */
    public void setCR_ACC_BRANCH(BigDecimal CR_ACC_BRANCH) {
        this.CR_ACC_BRANCH = CR_ACC_BRANCH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_CHARGES_REVERSAL_DET.CR_ACC_CURRENCY
     *
     * @return the value of TRS_CHARGES_REVERSAL_DET.CR_ACC_CURRENCY
     */
    public BigDecimal getCR_ACC_CURRENCY() {
        return CR_ACC_CURRENCY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_CHARGES_REVERSAL_DET.CR_ACC_CURRENCY
     *
     * @param CR_ACC_CURRENCY the value for TRS_CHARGES_REVERSAL_DET.CR_ACC_CURRENCY
     */
    public void setCR_ACC_CURRENCY(BigDecimal CR_ACC_CURRENCY) {
        this.CR_ACC_CURRENCY = CR_ACC_CURRENCY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_CHARGES_REVERSAL_DET.CR_ACC_GL
     *
     * @return the value of TRS_CHARGES_REVERSAL_DET.CR_ACC_GL
     */
    public BigDecimal getCR_ACC_GL() {
        return CR_ACC_GL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_CHARGES_REVERSAL_DET.CR_ACC_GL
     *
     * @param CR_ACC_GL the value for TRS_CHARGES_REVERSAL_DET.CR_ACC_GL
     */
    public void setCR_ACC_GL(BigDecimal CR_ACC_GL) {
        this.CR_ACC_GL = CR_ACC_GL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_CHARGES_REVERSAL_DET.CR_ACC_CIF_SUB_NO
     *
     * @return the value of TRS_CHARGES_REVERSAL_DET.CR_ACC_CIF_SUB_NO
     */
    public BigDecimal getCR_ACC_CIF_SUB_NO() {
        return CR_ACC_CIF_SUB_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_CHARGES_REVERSAL_DET.CR_ACC_CIF_SUB_NO
     *
     * @param CR_ACC_CIF_SUB_NO the value for TRS_CHARGES_REVERSAL_DET.CR_ACC_CIF_SUB_NO
     */
    public void setCR_ACC_CIF_SUB_NO(BigDecimal CR_ACC_CIF_SUB_NO) {
        this.CR_ACC_CIF_SUB_NO = CR_ACC_CIF_SUB_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_CHARGES_REVERSAL_DET.CR_ACC_SL_NO
     *
     * @return the value of TRS_CHARGES_REVERSAL_DET.CR_ACC_SL_NO
     */
    public BigDecimal getCR_ACC_SL_NO() {
        return CR_ACC_SL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_CHARGES_REVERSAL_DET.CR_ACC_SL_NO
     *
     * @param CR_ACC_SL_NO the value for TRS_CHARGES_REVERSAL_DET.CR_ACC_SL_NO
     */
    public void setCR_ACC_SL_NO(BigDecimal CR_ACC_SL_NO) {
        this.CR_ACC_SL_NO = CR_ACC_SL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_CHARGES_REVERSAL_DET.DR_ACC_BRANCH
     *
     * @return the value of TRS_CHARGES_REVERSAL_DET.DR_ACC_BRANCH
     */
    public BigDecimal getDR_ACC_BRANCH() {
        return DR_ACC_BRANCH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_CHARGES_REVERSAL_DET.DR_ACC_BRANCH
     *
     * @param DR_ACC_BRANCH the value for TRS_CHARGES_REVERSAL_DET.DR_ACC_BRANCH
     */
    public void setDR_ACC_BRANCH(BigDecimal DR_ACC_BRANCH) {
        this.DR_ACC_BRANCH = DR_ACC_BRANCH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_CHARGES_REVERSAL_DET.DR_ACC_CURRENCY
     *
     * @return the value of TRS_CHARGES_REVERSAL_DET.DR_ACC_CURRENCY
     */
    public BigDecimal getDR_ACC_CURRENCY() {
        return DR_ACC_CURRENCY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_CHARGES_REVERSAL_DET.DR_ACC_CURRENCY
     *
     * @param DR_ACC_CURRENCY the value for TRS_CHARGES_REVERSAL_DET.DR_ACC_CURRENCY
     */
    public void setDR_ACC_CURRENCY(BigDecimal DR_ACC_CURRENCY) {
        this.DR_ACC_CURRENCY = DR_ACC_CURRENCY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_CHARGES_REVERSAL_DET.DR_ACC_GL
     *
     * @return the value of TRS_CHARGES_REVERSAL_DET.DR_ACC_GL
     */
    public BigDecimal getDR_ACC_GL() {
        return DR_ACC_GL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_CHARGES_REVERSAL_DET.DR_ACC_GL
     *
     * @param DR_ACC_GL the value for TRS_CHARGES_REVERSAL_DET.DR_ACC_GL
     */
    public void setDR_ACC_GL(BigDecimal DR_ACC_GL) {
        this.DR_ACC_GL = DR_ACC_GL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_CHARGES_REVERSAL_DET.DR_ACC_CIF_SUB_NO
     *
     * @return the value of TRS_CHARGES_REVERSAL_DET.DR_ACC_CIF_SUB_NO
     */
    public BigDecimal getDR_ACC_CIF_SUB_NO() {
        return DR_ACC_CIF_SUB_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_CHARGES_REVERSAL_DET.DR_ACC_CIF_SUB_NO
     *
     * @param DR_ACC_CIF_SUB_NO the value for TRS_CHARGES_REVERSAL_DET.DR_ACC_CIF_SUB_NO
     */
    public void setDR_ACC_CIF_SUB_NO(BigDecimal DR_ACC_CIF_SUB_NO) {
        this.DR_ACC_CIF_SUB_NO = DR_ACC_CIF_SUB_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_CHARGES_REVERSAL_DET.DR_ACC_SL_NO
     *
     * @return the value of TRS_CHARGES_REVERSAL_DET.DR_ACC_SL_NO
     */
    public BigDecimal getDR_ACC_SL_NO() {
        return DR_ACC_SL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_CHARGES_REVERSAL_DET.DR_ACC_SL_NO
     *
     * @param DR_ACC_SL_NO the value for TRS_CHARGES_REVERSAL_DET.DR_ACC_SL_NO
     */
    public void setDR_ACC_SL_NO(BigDecimal DR_ACC_SL_NO) {
        this.DR_ACC_SL_NO = DR_ACC_SL_NO;
    }
}