package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class TRS_MANUAL_CLASSIFY_DEALVO extends TRS_MANUAL_CLASSIFY_DEALVOKey {
    /**
     * This field corresponds to the database column TRS_MANUAL_CLASSIFY_DEAL.DEAL_BRANCH
     */
    private BigDecimal DEAL_BRANCH;

    /**
     * This field corresponds to the database column TRS_MANUAL_CLASSIFY_DEAL.DEAL_NO
     */
    private BigDecimal DEAL_NO;

    /**
     * This field corresponds to the database column TRS_MANUAL_CLASSIFY_DEAL.OUTSTANDING_PRINCIPAL
     */
    private BigDecimal OUTSTANDING_PRINCIPAL;

    /**
     * This field corresponds to the database column TRS_MANUAL_CLASSIFY_DEAL.OUTSTANDING_PRINCIPAL_CV
     */
    private BigDecimal OUTSTANDING_PRINCIPAL_CV;

    /**
     * This field corresponds to the database column TRS_MANUAL_CLASSIFY_DEAL.OUTSTANDING_PROFIT
     */
    private BigDecimal OUTSTANDING_PROFIT;

    /**
     * This field corresponds to the database column TRS_MANUAL_CLASSIFY_DEAL.OUTSTANDING_PROFIT_CV
     */
    private BigDecimal OUTSTANDING_PROFIT_CV;

    /**
     * This field corresponds to the database column TRS_MANUAL_CLASSIFY_DEAL.PAST_DUE_AMOUNT
     */
    private BigDecimal PAST_DUE_AMOUNT;

    /**
     * This field corresponds to the database column TRS_MANUAL_CLASSIFY_DEAL.EXCESS_SETTLED_PROFIT
     */
    private BigDecimal EXCESS_SETTLED_PROFIT;

    /**
     * This field corresponds to the database column TRS_MANUAL_CLASSIFY_DEAL.ACCRUED_PFT_AFTER_AS_OF_DATE
     */
    private BigDecimal ACCRUED_PFT_AFTER_AS_OF_DATE;

    /**
     * This field corresponds to the database column TRS_MANUAL_CLASSIFY_DEAL.UNEARNED_INCOME
     */
    private BigDecimal UNEARNED_INCOME;

    /**
     * This field corresponds to the database column TRS_MANUAL_CLASSIFY_DEAL.PLAN_NBR
     */
    private BigDecimal PLAN_NBR;

    /**
     * This field corresponds to the database column TRS_MANUAL_CLASSIFY_DEAL.PLAN_SEQ
     */
    private BigDecimal PLAN_SEQ;

    /**
     * This field corresponds to the database column TRS_MANUAL_CLASSIFY_DEAL.PLAN_SEQ_NEW
     */
    private BigDecimal PLAN_SEQ_NEW;

    /**
     * This field corresponds to the database column TRS_MANUAL_CLASSIFY_DEAL.SELECT_YN
     */
    private String SELECT_YN;

    /**
     * This field corresponds to the database column TRS_MANUAL_CLASSIFY_DEAL.CTS_TRS_NO
     */
    private BigDecimal CTS_TRS_NO;

    /**
     * This field corresponds to the database column TRS_MANUAL_CLASSIFY_DEAL.OUTSTANDING_CHARGE_AMT
     */
    private BigDecimal OUTSTANDING_CHARGE_AMT;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_MANUAL_CLASSIFY_DEAL.DEAL_BRANCH
     *
     * @return the value of TRS_MANUAL_CLASSIFY_DEAL.DEAL_BRANCH
     */
    public BigDecimal getDEAL_BRANCH() {
        return DEAL_BRANCH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_MANUAL_CLASSIFY_DEAL.DEAL_BRANCH
     *
     * @param DEAL_BRANCH the value for TRS_MANUAL_CLASSIFY_DEAL.DEAL_BRANCH
     */
    public void setDEAL_BRANCH(BigDecimal DEAL_BRANCH) {
        this.DEAL_BRANCH = DEAL_BRANCH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_MANUAL_CLASSIFY_DEAL.DEAL_NO
     *
     * @return the value of TRS_MANUAL_CLASSIFY_DEAL.DEAL_NO
     */
    public BigDecimal getDEAL_NO() {
        return DEAL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_MANUAL_CLASSIFY_DEAL.DEAL_NO
     *
     * @param DEAL_NO the value for TRS_MANUAL_CLASSIFY_DEAL.DEAL_NO
     */
    public void setDEAL_NO(BigDecimal DEAL_NO) {
        this.DEAL_NO = DEAL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_MANUAL_CLASSIFY_DEAL.OUTSTANDING_PRINCIPAL
     *
     * @return the value of TRS_MANUAL_CLASSIFY_DEAL.OUTSTANDING_PRINCIPAL
     */
    public BigDecimal getOUTSTANDING_PRINCIPAL() {
        return OUTSTANDING_PRINCIPAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_MANUAL_CLASSIFY_DEAL.OUTSTANDING_PRINCIPAL
     *
     * @param OUTSTANDING_PRINCIPAL the value for TRS_MANUAL_CLASSIFY_DEAL.OUTSTANDING_PRINCIPAL
     */
    public void setOUTSTANDING_PRINCIPAL(BigDecimal OUTSTANDING_PRINCIPAL) {
        this.OUTSTANDING_PRINCIPAL = OUTSTANDING_PRINCIPAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_MANUAL_CLASSIFY_DEAL.OUTSTANDING_PRINCIPAL_CV
     *
     * @return the value of TRS_MANUAL_CLASSIFY_DEAL.OUTSTANDING_PRINCIPAL_CV
     */
    public BigDecimal getOUTSTANDING_PRINCIPAL_CV() {
        return OUTSTANDING_PRINCIPAL_CV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_MANUAL_CLASSIFY_DEAL.OUTSTANDING_PRINCIPAL_CV
     *
     * @param OUTSTANDING_PRINCIPAL_CV the value for TRS_MANUAL_CLASSIFY_DEAL.OUTSTANDING_PRINCIPAL_CV
     */
    public void setOUTSTANDING_PRINCIPAL_CV(BigDecimal OUTSTANDING_PRINCIPAL_CV) {
        this.OUTSTANDING_PRINCIPAL_CV = OUTSTANDING_PRINCIPAL_CV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_MANUAL_CLASSIFY_DEAL.OUTSTANDING_PROFIT
     *
     * @return the value of TRS_MANUAL_CLASSIFY_DEAL.OUTSTANDING_PROFIT
     */
    public BigDecimal getOUTSTANDING_PROFIT() {
        return OUTSTANDING_PROFIT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_MANUAL_CLASSIFY_DEAL.OUTSTANDING_PROFIT
     *
     * @param OUTSTANDING_PROFIT the value for TRS_MANUAL_CLASSIFY_DEAL.OUTSTANDING_PROFIT
     */
    public void setOUTSTANDING_PROFIT(BigDecimal OUTSTANDING_PROFIT) {
        this.OUTSTANDING_PROFIT = OUTSTANDING_PROFIT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_MANUAL_CLASSIFY_DEAL.OUTSTANDING_PROFIT_CV
     *
     * @return the value of TRS_MANUAL_CLASSIFY_DEAL.OUTSTANDING_PROFIT_CV
     */
    public BigDecimal getOUTSTANDING_PROFIT_CV() {
        return OUTSTANDING_PROFIT_CV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_MANUAL_CLASSIFY_DEAL.OUTSTANDING_PROFIT_CV
     *
     * @param OUTSTANDING_PROFIT_CV the value for TRS_MANUAL_CLASSIFY_DEAL.OUTSTANDING_PROFIT_CV
     */
    public void setOUTSTANDING_PROFIT_CV(BigDecimal OUTSTANDING_PROFIT_CV) {
        this.OUTSTANDING_PROFIT_CV = OUTSTANDING_PROFIT_CV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_MANUAL_CLASSIFY_DEAL.PAST_DUE_AMOUNT
     *
     * @return the value of TRS_MANUAL_CLASSIFY_DEAL.PAST_DUE_AMOUNT
     */
    public BigDecimal getPAST_DUE_AMOUNT() {
        return PAST_DUE_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_MANUAL_CLASSIFY_DEAL.PAST_DUE_AMOUNT
     *
     * @param PAST_DUE_AMOUNT the value for TRS_MANUAL_CLASSIFY_DEAL.PAST_DUE_AMOUNT
     */
    public void setPAST_DUE_AMOUNT(BigDecimal PAST_DUE_AMOUNT) {
        this.PAST_DUE_AMOUNT = PAST_DUE_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_MANUAL_CLASSIFY_DEAL.EXCESS_SETTLED_PROFIT
     *
     * @return the value of TRS_MANUAL_CLASSIFY_DEAL.EXCESS_SETTLED_PROFIT
     */
    public BigDecimal getEXCESS_SETTLED_PROFIT() {
        return EXCESS_SETTLED_PROFIT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_MANUAL_CLASSIFY_DEAL.EXCESS_SETTLED_PROFIT
     *
     * @param EXCESS_SETTLED_PROFIT the value for TRS_MANUAL_CLASSIFY_DEAL.EXCESS_SETTLED_PROFIT
     */
    public void setEXCESS_SETTLED_PROFIT(BigDecimal EXCESS_SETTLED_PROFIT) {
        this.EXCESS_SETTLED_PROFIT = EXCESS_SETTLED_PROFIT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_MANUAL_CLASSIFY_DEAL.ACCRUED_PFT_AFTER_AS_OF_DATE
     *
     * @return the value of TRS_MANUAL_CLASSIFY_DEAL.ACCRUED_PFT_AFTER_AS_OF_DATE
     */
    public BigDecimal getACCRUED_PFT_AFTER_AS_OF_DATE() {
        return ACCRUED_PFT_AFTER_AS_OF_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_MANUAL_CLASSIFY_DEAL.ACCRUED_PFT_AFTER_AS_OF_DATE
     *
     * @param ACCRUED_PFT_AFTER_AS_OF_DATE the value for TRS_MANUAL_CLASSIFY_DEAL.ACCRUED_PFT_AFTER_AS_OF_DATE
     */
    public void setACCRUED_PFT_AFTER_AS_OF_DATE(BigDecimal ACCRUED_PFT_AFTER_AS_OF_DATE) {
        this.ACCRUED_PFT_AFTER_AS_OF_DATE = ACCRUED_PFT_AFTER_AS_OF_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_MANUAL_CLASSIFY_DEAL.UNEARNED_INCOME
     *
     * @return the value of TRS_MANUAL_CLASSIFY_DEAL.UNEARNED_INCOME
     */
    public BigDecimal getUNEARNED_INCOME() {
        return UNEARNED_INCOME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_MANUAL_CLASSIFY_DEAL.UNEARNED_INCOME
     *
     * @param UNEARNED_INCOME the value for TRS_MANUAL_CLASSIFY_DEAL.UNEARNED_INCOME
     */
    public void setUNEARNED_INCOME(BigDecimal UNEARNED_INCOME) {
        this.UNEARNED_INCOME = UNEARNED_INCOME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_MANUAL_CLASSIFY_DEAL.PLAN_NBR
     *
     * @return the value of TRS_MANUAL_CLASSIFY_DEAL.PLAN_NBR
     */
    public BigDecimal getPLAN_NBR() {
        return PLAN_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_MANUAL_CLASSIFY_DEAL.PLAN_NBR
     *
     * @param PLAN_NBR the value for TRS_MANUAL_CLASSIFY_DEAL.PLAN_NBR
     */
    public void setPLAN_NBR(BigDecimal PLAN_NBR) {
        this.PLAN_NBR = PLAN_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_MANUAL_CLASSIFY_DEAL.PLAN_SEQ
     *
     * @return the value of TRS_MANUAL_CLASSIFY_DEAL.PLAN_SEQ
     */
    public BigDecimal getPLAN_SEQ() {
        return PLAN_SEQ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_MANUAL_CLASSIFY_DEAL.PLAN_SEQ
     *
     * @param PLAN_SEQ the value for TRS_MANUAL_CLASSIFY_DEAL.PLAN_SEQ
     */
    public void setPLAN_SEQ(BigDecimal PLAN_SEQ) {
        this.PLAN_SEQ = PLAN_SEQ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_MANUAL_CLASSIFY_DEAL.PLAN_SEQ_NEW
     *
     * @return the value of TRS_MANUAL_CLASSIFY_DEAL.PLAN_SEQ_NEW
     */
    public BigDecimal getPLAN_SEQ_NEW() {
        return PLAN_SEQ_NEW;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_MANUAL_CLASSIFY_DEAL.PLAN_SEQ_NEW
     *
     * @param PLAN_SEQ_NEW the value for TRS_MANUAL_CLASSIFY_DEAL.PLAN_SEQ_NEW
     */
    public void setPLAN_SEQ_NEW(BigDecimal PLAN_SEQ_NEW) {
        this.PLAN_SEQ_NEW = PLAN_SEQ_NEW;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_MANUAL_CLASSIFY_DEAL.SELECT_YN
     *
     * @return the value of TRS_MANUAL_CLASSIFY_DEAL.SELECT_YN
     */
    public String getSELECT_YN() {
        return SELECT_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_MANUAL_CLASSIFY_DEAL.SELECT_YN
     *
     * @param SELECT_YN the value for TRS_MANUAL_CLASSIFY_DEAL.SELECT_YN
     */
    public void setSELECT_YN(String SELECT_YN) {
        this.SELECT_YN = SELECT_YN == null ? null : SELECT_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_MANUAL_CLASSIFY_DEAL.CTS_TRS_NO
     *
     * @return the value of TRS_MANUAL_CLASSIFY_DEAL.CTS_TRS_NO
     */
    public BigDecimal getCTS_TRS_NO() {
        return CTS_TRS_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_MANUAL_CLASSIFY_DEAL.CTS_TRS_NO
     *
     * @param CTS_TRS_NO the value for TRS_MANUAL_CLASSIFY_DEAL.CTS_TRS_NO
     */
    public void setCTS_TRS_NO(BigDecimal CTS_TRS_NO) {
        this.CTS_TRS_NO = CTS_TRS_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_MANUAL_CLASSIFY_DEAL.OUTSTANDING_CHARGE_AMT
     *
     * @return the value of TRS_MANUAL_CLASSIFY_DEAL.OUTSTANDING_CHARGE_AMT
     */
    public BigDecimal getOUTSTANDING_CHARGE_AMT() {
        return OUTSTANDING_CHARGE_AMT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_MANUAL_CLASSIFY_DEAL.OUTSTANDING_CHARGE_AMT
     *
     * @param OUTSTANDING_CHARGE_AMT the value for TRS_MANUAL_CLASSIFY_DEAL.OUTSTANDING_CHARGE_AMT
     */
    public void setOUTSTANDING_CHARGE_AMT(BigDecimal OUTSTANDING_CHARGE_AMT) {
        this.OUTSTANDING_CHARGE_AMT = OUTSTANDING_CHARGE_AMT;
    }
}