package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class TRS_PROV_PROCESS_AMEND_PRODVO extends TRS_PROV_PROCESS_AMEND_PRODVOKey {
    /**
     * This field corresponds to the database column TRS_PROV_PROCESS_AMEND_PROD.PRODUCT_TYPE_CODE
     */
    private BigDecimal PRODUCT_TYPE_CODE;

    /**
     * This field corresponds to the database column TRS_PROV_PROCESS_AMEND_PROD.ACC_BRANCH
     */
    private BigDecimal ACC_BRANCH;

    /**
     * This field corresponds to the database column TRS_PROV_PROCESS_AMEND_PROD.AC_NO
     */
    private String AC_NO;

    /**
     * This field corresponds to the database column TRS_PROV_PROCESS_AMEND_PROD.CURRENCY_CODE
     */
    private BigDecimal CURRENCY_CODE;

    /**
     * This field corresponds to the database column TRS_PROV_PROCESS_AMEND_PROD.GL_CODE
     */
    private BigDecimal GL_CODE;

    /**
     * This field corresponds to the database column TRS_PROV_PROCESS_AMEND_PROD.CIF_SUB_NO
     */
    private BigDecimal CIF_SUB_NO;

    /**
     * This field corresponds to the database column TRS_PROV_PROCESS_AMEND_PROD.SL_NO
     */
    private BigDecimal SL_NO;

    /**
     * This field corresponds to the database column TRS_PROV_PROCESS_AMEND_PROD.PROVISION_CATEGORY_CODE
     */
    private BigDecimal PROVISION_CATEGORY_CODE;

    /**
     * This field corresponds to the database column TRS_PROV_PROCESS_AMEND_PROD.OUTSTANDING_AMOUNT
     */
    private BigDecimal OUTSTANDING_AMOUNT;

    /**
     * This field corresponds to the database column TRS_PROV_PROCESS_AMEND_PROD.PROVISION_AMOUNT_USER
     */
    private BigDecimal PROVISION_AMOUNT_USER;

    /**
     * This field corresponds to the database column TRS_PROV_PROCESS_AMEND_PROD.PROVISION_PERC_USER
     */
    private BigDecimal PROVISION_PERC_USER;

    /**
     * This field corresponds to the database column TRS_PROV_PROCESS_AMEND_PROD.PROVISION_AMOUNT_SYSTEM
     */
    private BigDecimal PROVISION_AMOUNT_SYSTEM;

    /**
     * This field corresponds to the database column TRS_PROV_PROCESS_AMEND_PROD.PROVISION_PERC_SYSTEM
     */
    private BigDecimal PROVISION_PERC_SYSTEM;

    /**
     * This field corresponds to the database column TRS_PROV_PROCESS_AMEND_PROD.PROVISION_AMOUNT_CV_USER_OLD
     */
    private BigDecimal PROVISION_AMOUNT_CV_USER_OLD;

    /**
     * This field corresponds to the database column TRS_PROV_PROCESS_AMEND_PROD.PROVISION_AMOUNT_USER_OLD
     */
    private BigDecimal PROVISION_AMOUNT_USER_OLD;

    /**
     * This field corresponds to the database column TRS_PROV_PROCESS_AMEND_PROD.PROVISION_PERC_USER_OLD
     */
    private BigDecimal PROVISION_PERC_USER_OLD;

    /**
     * This field corresponds to the database column TRS_PROV_PROCESS_AMEND_PROD.PROCESS_REF_NBR
     */
    private BigDecimal PROCESS_REF_NBR;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROV_PROCESS_AMEND_PROD.PRODUCT_TYPE_CODE
     *
     * @return the value of TRS_PROV_PROCESS_AMEND_PROD.PRODUCT_TYPE_CODE
     */
    public BigDecimal getPRODUCT_TYPE_CODE() {
        return PRODUCT_TYPE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROV_PROCESS_AMEND_PROD.PRODUCT_TYPE_CODE
     *
     * @param PRODUCT_TYPE_CODE the value for TRS_PROV_PROCESS_AMEND_PROD.PRODUCT_TYPE_CODE
     */
    public void setPRODUCT_TYPE_CODE(BigDecimal PRODUCT_TYPE_CODE) {
        this.PRODUCT_TYPE_CODE = PRODUCT_TYPE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROV_PROCESS_AMEND_PROD.ACC_BRANCH
     *
     * @return the value of TRS_PROV_PROCESS_AMEND_PROD.ACC_BRANCH
     */
    public BigDecimal getACC_BRANCH() {
        return ACC_BRANCH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROV_PROCESS_AMEND_PROD.ACC_BRANCH
     *
     * @param ACC_BRANCH the value for TRS_PROV_PROCESS_AMEND_PROD.ACC_BRANCH
     */
    public void setACC_BRANCH(BigDecimal ACC_BRANCH) {
        this.ACC_BRANCH = ACC_BRANCH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROV_PROCESS_AMEND_PROD.AC_NO
     *
     * @return the value of TRS_PROV_PROCESS_AMEND_PROD.AC_NO
     */
    public String getAC_NO() {
        return AC_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROV_PROCESS_AMEND_PROD.AC_NO
     *
     * @param AC_NO the value for TRS_PROV_PROCESS_AMEND_PROD.AC_NO
     */
    public void setAC_NO(String AC_NO) {
        this.AC_NO = AC_NO == null ? null : AC_NO.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROV_PROCESS_AMEND_PROD.CURRENCY_CODE
     *
     * @return the value of TRS_PROV_PROCESS_AMEND_PROD.CURRENCY_CODE
     */
    public BigDecimal getCURRENCY_CODE() {
        return CURRENCY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROV_PROCESS_AMEND_PROD.CURRENCY_CODE
     *
     * @param CURRENCY_CODE the value for TRS_PROV_PROCESS_AMEND_PROD.CURRENCY_CODE
     */
    public void setCURRENCY_CODE(BigDecimal CURRENCY_CODE) {
        this.CURRENCY_CODE = CURRENCY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROV_PROCESS_AMEND_PROD.GL_CODE
     *
     * @return the value of TRS_PROV_PROCESS_AMEND_PROD.GL_CODE
     */
    public BigDecimal getGL_CODE() {
        return GL_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROV_PROCESS_AMEND_PROD.GL_CODE
     *
     * @param GL_CODE the value for TRS_PROV_PROCESS_AMEND_PROD.GL_CODE
     */
    public void setGL_CODE(BigDecimal GL_CODE) {
        this.GL_CODE = GL_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROV_PROCESS_AMEND_PROD.CIF_SUB_NO
     *
     * @return the value of TRS_PROV_PROCESS_AMEND_PROD.CIF_SUB_NO
     */
    public BigDecimal getCIF_SUB_NO() {
        return CIF_SUB_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROV_PROCESS_AMEND_PROD.CIF_SUB_NO
     *
     * @param CIF_SUB_NO the value for TRS_PROV_PROCESS_AMEND_PROD.CIF_SUB_NO
     */
    public void setCIF_SUB_NO(BigDecimal CIF_SUB_NO) {
        this.CIF_SUB_NO = CIF_SUB_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROV_PROCESS_AMEND_PROD.SL_NO
     *
     * @return the value of TRS_PROV_PROCESS_AMEND_PROD.SL_NO
     */
    public BigDecimal getSL_NO() {
        return SL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROV_PROCESS_AMEND_PROD.SL_NO
     *
     * @param SL_NO the value for TRS_PROV_PROCESS_AMEND_PROD.SL_NO
     */
    public void setSL_NO(BigDecimal SL_NO) {
        this.SL_NO = SL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROV_PROCESS_AMEND_PROD.PROVISION_CATEGORY_CODE
     *
     * @return the value of TRS_PROV_PROCESS_AMEND_PROD.PROVISION_CATEGORY_CODE
     */
    public BigDecimal getPROVISION_CATEGORY_CODE() {
        return PROVISION_CATEGORY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROV_PROCESS_AMEND_PROD.PROVISION_CATEGORY_CODE
     *
     * @param PROVISION_CATEGORY_CODE the value for TRS_PROV_PROCESS_AMEND_PROD.PROVISION_CATEGORY_CODE
     */
    public void setPROVISION_CATEGORY_CODE(BigDecimal PROVISION_CATEGORY_CODE) {
        this.PROVISION_CATEGORY_CODE = PROVISION_CATEGORY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROV_PROCESS_AMEND_PROD.OUTSTANDING_AMOUNT
     *
     * @return the value of TRS_PROV_PROCESS_AMEND_PROD.OUTSTANDING_AMOUNT
     */
    public BigDecimal getOUTSTANDING_AMOUNT() {
        return OUTSTANDING_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROV_PROCESS_AMEND_PROD.OUTSTANDING_AMOUNT
     *
     * @param OUTSTANDING_AMOUNT the value for TRS_PROV_PROCESS_AMEND_PROD.OUTSTANDING_AMOUNT
     */
    public void setOUTSTANDING_AMOUNT(BigDecimal OUTSTANDING_AMOUNT) {
        this.OUTSTANDING_AMOUNT = OUTSTANDING_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROV_PROCESS_AMEND_PROD.PROVISION_AMOUNT_USER
     *
     * @return the value of TRS_PROV_PROCESS_AMEND_PROD.PROVISION_AMOUNT_USER
     */
    public BigDecimal getPROVISION_AMOUNT_USER() {
        return PROVISION_AMOUNT_USER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROV_PROCESS_AMEND_PROD.PROVISION_AMOUNT_USER
     *
     * @param PROVISION_AMOUNT_USER the value for TRS_PROV_PROCESS_AMEND_PROD.PROVISION_AMOUNT_USER
     */
    public void setPROVISION_AMOUNT_USER(BigDecimal PROVISION_AMOUNT_USER) {
        this.PROVISION_AMOUNT_USER = PROVISION_AMOUNT_USER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROV_PROCESS_AMEND_PROD.PROVISION_PERC_USER
     *
     * @return the value of TRS_PROV_PROCESS_AMEND_PROD.PROVISION_PERC_USER
     */
    public BigDecimal getPROVISION_PERC_USER() {
        return PROVISION_PERC_USER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROV_PROCESS_AMEND_PROD.PROVISION_PERC_USER
     *
     * @param PROVISION_PERC_USER the value for TRS_PROV_PROCESS_AMEND_PROD.PROVISION_PERC_USER
     */
    public void setPROVISION_PERC_USER(BigDecimal PROVISION_PERC_USER) {
        this.PROVISION_PERC_USER = PROVISION_PERC_USER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROV_PROCESS_AMEND_PROD.PROVISION_AMOUNT_SYSTEM
     *
     * @return the value of TRS_PROV_PROCESS_AMEND_PROD.PROVISION_AMOUNT_SYSTEM
     */
    public BigDecimal getPROVISION_AMOUNT_SYSTEM() {
        return PROVISION_AMOUNT_SYSTEM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROV_PROCESS_AMEND_PROD.PROVISION_AMOUNT_SYSTEM
     *
     * @param PROVISION_AMOUNT_SYSTEM the value for TRS_PROV_PROCESS_AMEND_PROD.PROVISION_AMOUNT_SYSTEM
     */
    public void setPROVISION_AMOUNT_SYSTEM(BigDecimal PROVISION_AMOUNT_SYSTEM) {
        this.PROVISION_AMOUNT_SYSTEM = PROVISION_AMOUNT_SYSTEM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROV_PROCESS_AMEND_PROD.PROVISION_PERC_SYSTEM
     *
     * @return the value of TRS_PROV_PROCESS_AMEND_PROD.PROVISION_PERC_SYSTEM
     */
    public BigDecimal getPROVISION_PERC_SYSTEM() {
        return PROVISION_PERC_SYSTEM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROV_PROCESS_AMEND_PROD.PROVISION_PERC_SYSTEM
     *
     * @param PROVISION_PERC_SYSTEM the value for TRS_PROV_PROCESS_AMEND_PROD.PROVISION_PERC_SYSTEM
     */
    public void setPROVISION_PERC_SYSTEM(BigDecimal PROVISION_PERC_SYSTEM) {
        this.PROVISION_PERC_SYSTEM = PROVISION_PERC_SYSTEM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROV_PROCESS_AMEND_PROD.PROVISION_AMOUNT_CV_USER_OLD
     *
     * @return the value of TRS_PROV_PROCESS_AMEND_PROD.PROVISION_AMOUNT_CV_USER_OLD
     */
    public BigDecimal getPROVISION_AMOUNT_CV_USER_OLD() {
        return PROVISION_AMOUNT_CV_USER_OLD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROV_PROCESS_AMEND_PROD.PROVISION_AMOUNT_CV_USER_OLD
     *
     * @param PROVISION_AMOUNT_CV_USER_OLD the value for TRS_PROV_PROCESS_AMEND_PROD.PROVISION_AMOUNT_CV_USER_OLD
     */
    public void setPROVISION_AMOUNT_CV_USER_OLD(BigDecimal PROVISION_AMOUNT_CV_USER_OLD) {
        this.PROVISION_AMOUNT_CV_USER_OLD = PROVISION_AMOUNT_CV_USER_OLD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROV_PROCESS_AMEND_PROD.PROVISION_AMOUNT_USER_OLD
     *
     * @return the value of TRS_PROV_PROCESS_AMEND_PROD.PROVISION_AMOUNT_USER_OLD
     */
    public BigDecimal getPROVISION_AMOUNT_USER_OLD() {
        return PROVISION_AMOUNT_USER_OLD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROV_PROCESS_AMEND_PROD.PROVISION_AMOUNT_USER_OLD
     *
     * @param PROVISION_AMOUNT_USER_OLD the value for TRS_PROV_PROCESS_AMEND_PROD.PROVISION_AMOUNT_USER_OLD
     */
    public void setPROVISION_AMOUNT_USER_OLD(BigDecimal PROVISION_AMOUNT_USER_OLD) {
        this.PROVISION_AMOUNT_USER_OLD = PROVISION_AMOUNT_USER_OLD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROV_PROCESS_AMEND_PROD.PROVISION_PERC_USER_OLD
     *
     * @return the value of TRS_PROV_PROCESS_AMEND_PROD.PROVISION_PERC_USER_OLD
     */
    public BigDecimal getPROVISION_PERC_USER_OLD() {
        return PROVISION_PERC_USER_OLD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROV_PROCESS_AMEND_PROD.PROVISION_PERC_USER_OLD
     *
     * @param PROVISION_PERC_USER_OLD the value for TRS_PROV_PROCESS_AMEND_PROD.PROVISION_PERC_USER_OLD
     */
    public void setPROVISION_PERC_USER_OLD(BigDecimal PROVISION_PERC_USER_OLD) {
        this.PROVISION_PERC_USER_OLD = PROVISION_PERC_USER_OLD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROV_PROCESS_AMEND_PROD.PROCESS_REF_NBR
     *
     * @return the value of TRS_PROV_PROCESS_AMEND_PROD.PROCESS_REF_NBR
     */
    public BigDecimal getPROCESS_REF_NBR() {
        return PROCESS_REF_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROV_PROCESS_AMEND_PROD.PROCESS_REF_NBR
     *
     * @param PROCESS_REF_NBR the value for TRS_PROV_PROCESS_AMEND_PROD.PROCESS_REF_NBR
     */
    public void setPROCESS_REF_NBR(BigDecimal PROCESS_REF_NBR) {
        this.PROCESS_REF_NBR = PROCESS_REF_NBR;
    }
}