package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class TRS_MUDARABAH_RATE_DETVO extends TRS_MUDARABAH_RATE_DETVOKey {
    /**
     * This field corresponds to the database column TRS_MUDARABAH_RATE_DET.GIVEN_RATE
     */
    private BigDecimal GIVEN_RATE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_MUDARABAH_RATE_DET.GIVEN_RATE
     *
     * @return the value of TRS_MUDARABAH_RATE_DET.GIVEN_RATE
     */
    public BigDecimal getGIVEN_RATE() {
        return GIVEN_RATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_MUDARABAH_RATE_DET.GIVEN_RATE
     *
     * @param GIVEN_RATE the value for TRS_MUDARABAH_RATE_DET.GIVEN_RATE
     */
    public void setGIVEN_RATE(BigDecimal GIVEN_RATE) {
        this.GIVEN_RATE = GIVEN_RATE;
    }
}