package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class TRS_CONTRIBBLOCK_RELEASE_TRXVOKey extends BaseVO {
    /**
     * This field corresponds to the database column TRS_CONTRIBBLOCK_RELEASE_TRX.BRANCH_CODE
     */
    private BigDecimal BRANCH_CODE;

    /**
     * This field corresponds to the database column TRS_CONTRIBBLOCK_RELEASE_TRX.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column TRS_CONTRIBBLOCK_RELEASE_TRX.LINE_NO
     */
    private BigDecimal LINE_NO;

    /**
     * This field corresponds to the database column TRS_CONTRIBBLOCK_RELEASE_TRX.TRX_NBR
     */
    private BigDecimal TRX_NBR;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_CONTRIBBLOCK_RELEASE_TRX.BRANCH_CODE
     *
     * @return the value of TRS_CONTRIBBLOCK_RELEASE_TRX.BRANCH_CODE
     */
    public BigDecimal getBRANCH_CODE() {
        return BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_CONTRIBBLOCK_RELEASE_TRX.BRANCH_CODE
     *
     * @param BRANCH_CODE the value for TRS_CONTRIBBLOCK_RELEASE_TRX.BRANCH_CODE
     */
    public void setBRANCH_CODE(BigDecimal BRANCH_CODE) {
        this.BRANCH_CODE = BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_CONTRIBBLOCK_RELEASE_TRX.COMP_CODE
     *
     * @return the value of TRS_CONTRIBBLOCK_RELEASE_TRX.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_CONTRIBBLOCK_RELEASE_TRX.COMP_CODE
     *
     * @param COMP_CODE the value for TRS_CONTRIBBLOCK_RELEASE_TRX.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_CONTRIBBLOCK_RELEASE_TRX.LINE_NO
     *
     * @return the value of TRS_CONTRIBBLOCK_RELEASE_TRX.LINE_NO
     */
    public BigDecimal getLINE_NO() {
        return LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_CONTRIBBLOCK_RELEASE_TRX.LINE_NO
     *
     * @param LINE_NO the value for TRS_CONTRIBBLOCK_RELEASE_TRX.LINE_NO
     */
    public void setLINE_NO(BigDecimal LINE_NO) {
        this.LINE_NO = LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_CONTRIBBLOCK_RELEASE_TRX.TRX_NBR
     *
     * @return the value of TRS_CONTRIBBLOCK_RELEASE_TRX.TRX_NBR
     */
    public BigDecimal getTRX_NBR() {
        return TRX_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_CONTRIBBLOCK_RELEASE_TRX.TRX_NBR
     *
     * @param TRX_NBR the value for TRS_CONTRIBBLOCK_RELEASE_TRX.TRX_NBR
     */
    public void setTRX_NBR(BigDecimal TRX_NBR) {
        this.TRX_NBR = TRX_NBR;
    }
}