package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;
import java.util.Date;

public class TRS_PROCESS_RUNVOKey extends BaseVO {
    /**
     * This field corresponds to the database column TRS_PROCESS_RUN.BRANCH_CODE
     */
    private BigDecimal BRANCH_CODE;

    /**
     * This field corresponds to the database column TRS_PROCESS_RUN.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column TRS_PROCESS_RUN.LINE_NO
     */
    private BigDecimal LINE_NO;

    /**
     * This field corresponds to the database column TRS_PROCESS_RUN.PROCESS_CODE
     */
    private BigDecimal PROCESS_CODE;

    /**
     * This field corresponds to the database column TRS_PROCESS_RUN.PROCESS_DATE
     */
    private Date PROCESS_DATE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROCESS_RUN.BRANCH_CODE
     *
     * @return the value of TRS_PROCESS_RUN.BRANCH_CODE
     */
    public BigDecimal getBRANCH_CODE() {
        return BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROCESS_RUN.BRANCH_CODE
     *
     * @param BRANCH_CODE the value for TRS_PROCESS_RUN.BRANCH_CODE
     */
    public void setBRANCH_CODE(BigDecimal BRANCH_CODE) {
        this.BRANCH_CODE = BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROCESS_RUN.COMP_CODE
     *
     * @return the value of TRS_PROCESS_RUN.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROCESS_RUN.COMP_CODE
     *
     * @param COMP_CODE the value for TRS_PROCESS_RUN.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROCESS_RUN.LINE_NO
     *
     * @return the value of TRS_PROCESS_RUN.LINE_NO
     */
    public BigDecimal getLINE_NO() {
        return LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROCESS_RUN.LINE_NO
     *
     * @param LINE_NO the value for TRS_PROCESS_RUN.LINE_NO
     */
    public void setLINE_NO(BigDecimal LINE_NO) {
        this.LINE_NO = LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROCESS_RUN.PROCESS_CODE
     *
     * @return the value of TRS_PROCESS_RUN.PROCESS_CODE
     */
    public BigDecimal getPROCESS_CODE() {
        return PROCESS_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROCESS_RUN.PROCESS_CODE
     *
     * @param PROCESS_CODE the value for TRS_PROCESS_RUN.PROCESS_CODE
     */
    public void setPROCESS_CODE(BigDecimal PROCESS_CODE) {
        this.PROCESS_CODE = PROCESS_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROCESS_RUN.PROCESS_DATE
     *
     * @return the value of TRS_PROCESS_RUN.PROCESS_DATE
     */
    public Date getPROCESS_DATE() {
        return PROCESS_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROCESS_RUN.PROCESS_DATE
     *
     * @param PROCESS_DATE the value for TRS_PROCESS_RUN.PROCESS_DATE
     */
    public void setPROCESS_DATE(Date PROCESS_DATE) {
        this.PROCESS_DATE = PROCESS_DATE;
    }
}