package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class TRS_PROVISION_PROCESS_HDRVO extends TRS_PROVISION_PROCESS_HDRVOKey {
    /**
     * This field corresponds to the database column TRS_PROVISION_PROCESS_HDR.PROCESS_DATE
     */
    private Date PROCESS_DATE;

    /**
     * This field corresponds to the database column TRS_PROVISION_PROCESS_HDR.STATUS
     */
    private String STATUS;

    /**
     * This field corresponds to the database column TRS_PROVISION_PROCESS_HDR.CIF_FROM
     */
    private BigDecimal CIF_FROM;

    /**
     * This field corresponds to the database column TRS_PROVISION_PROCESS_HDR.CIF_TO
     */
    private BigDecimal CIF_TO;

    /**
     * This field corresponds to the database column TRS_PROVISION_PROCESS_HDR.PRODUCT_CLASS_FROM
     */
    private BigDecimal PRODUCT_CLASS_FROM;

    /**
     * This field corresponds to the database column TRS_PROVISION_PROCESS_HDR.PRODUCT_CLASS_TO
     */
    private BigDecimal PRODUCT_CLASS_TO;

    /**
     * This field corresponds to the database column TRS_PROVISION_PROCESS_HDR.DEAL_NO_FROM
     */
    private BigDecimal DEAL_NO_FROM;

    /**
     * This field corresponds to the database column TRS_PROVISION_PROCESS_HDR.DEAL_NO_TO
     */
    private BigDecimal DEAL_NO_TO;

    /**
     * This field corresponds to the database column TRS_PROVISION_PROCESS_HDR.PRODUCT_CODE_FROM
     */
    private BigDecimal PRODUCT_CODE_FROM;

    /**
     * This field corresponds to the database column TRS_PROVISION_PROCESS_HDR.PRODUCT_CODE_TO
     */
    private BigDecimal PRODUCT_CODE_TO;

    /**
     * This field corresponds to the database column TRS_PROVISION_PROCESS_HDR.PROVISION_CLASS_FROM
     */
    private BigDecimal PROVISION_CLASS_FROM;

    /**
     * This field corresponds to the database column TRS_PROVISION_PROCESS_HDR.PROVISION_CLASS_TO
     */
    private BigDecimal PROVISION_CLASS_TO;

    /**
     * This field corresponds to the database column TRS_PROVISION_PROCESS_HDR.DEAL_CATEGORY_FROM
     */
    private BigDecimal DEAL_CATEGORY_FROM;

    /**
     * This field corresponds to the database column TRS_PROVISION_PROCESS_HDR.DEAL_CATEGORY_TO
     */
    private BigDecimal DEAL_CATEGORY_TO;

    /**
     * This field corresponds to the database column TRS_PROVISION_PROCESS_HDR.DEAL_BRANCH_FROM
     */
    private BigDecimal DEAL_BRANCH_FROM;

    /**
     * This field corresponds to the database column TRS_PROVISION_PROCESS_HDR.DEAL_BRANCH_TO
     */
    private BigDecimal DEAL_BRANCH_TO;

    /**
     * This field corresponds to the database column TRS_PROVISION_PROCESS_HDR.EXCLUDE_CLOSED_DEALS
     */
    private String EXCLUDE_CLOSED_DEALS;

    /**
     * This field corresponds to the database column TRS_PROVISION_PROCESS_HDR.PROCESSED_BY
     */
    private String PROCESSED_BY;

    /**
     * This field corresponds to the database column TRS_PROVISION_PROCESS_HDR.PROCESS_SERVER_DATE
     */
    private Date PROCESS_SERVER_DATE;

    /**
     * This field corresponds to the database column TRS_PROVISION_PROCESS_HDR.VERIFIED_BY
     */
    private String VERIFIED_BY;

    /**
     * This field corresponds to the database column TRS_PROVISION_PROCESS_HDR.VERIFIED_DATE
     */
    private Date VERIFIED_DATE;

    /**
     * This field corresponds to the database column TRS_PROVISION_PROCESS_HDR.VERIFIED_SERVER_DATE
     */
    private Date VERIFIED_SERVER_DATE;

    /**
     * This field corresponds to the database column TRS_PROVISION_PROCESS_HDR.APPROVED_BY
     */
    private String APPROVED_BY;

    /**
     * This field corresponds to the database column TRS_PROVISION_PROCESS_HDR.APPROVED_DATE
     */
    private Date APPROVED_DATE;

    /**
     * This field corresponds to the database column TRS_PROVISION_PROCESS_HDR.APPROVED_SERVER_DATE
     */
    private Date APPROVED_SERVER_DATE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROVISION_PROCESS_HDR.PROCESS_DATE
     *
     * @return the value of TRS_PROVISION_PROCESS_HDR.PROCESS_DATE
     */
    public Date getPROCESS_DATE() {
        return PROCESS_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROVISION_PROCESS_HDR.PROCESS_DATE
     *
     * @param PROCESS_DATE the value for TRS_PROVISION_PROCESS_HDR.PROCESS_DATE
     */
    public void setPROCESS_DATE(Date PROCESS_DATE) {
        this.PROCESS_DATE = PROCESS_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROVISION_PROCESS_HDR.STATUS
     *
     * @return the value of TRS_PROVISION_PROCESS_HDR.STATUS
     */
    public String getSTATUS() {
        return STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROVISION_PROCESS_HDR.STATUS
     *
     * @param STATUS the value for TRS_PROVISION_PROCESS_HDR.STATUS
     */
    public void setSTATUS(String STATUS) {
        this.STATUS = STATUS == null ? null : STATUS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROVISION_PROCESS_HDR.CIF_FROM
     *
     * @return the value of TRS_PROVISION_PROCESS_HDR.CIF_FROM
     */
    public BigDecimal getCIF_FROM() {
        return CIF_FROM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROVISION_PROCESS_HDR.CIF_FROM
     *
     * @param CIF_FROM the value for TRS_PROVISION_PROCESS_HDR.CIF_FROM
     */
    public void setCIF_FROM(BigDecimal CIF_FROM) {
        this.CIF_FROM = CIF_FROM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROVISION_PROCESS_HDR.CIF_TO
     *
     * @return the value of TRS_PROVISION_PROCESS_HDR.CIF_TO
     */
    public BigDecimal getCIF_TO() {
        return CIF_TO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROVISION_PROCESS_HDR.CIF_TO
     *
     * @param CIF_TO the value for TRS_PROVISION_PROCESS_HDR.CIF_TO
     */
    public void setCIF_TO(BigDecimal CIF_TO) {
        this.CIF_TO = CIF_TO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROVISION_PROCESS_HDR.PRODUCT_CLASS_FROM
     *
     * @return the value of TRS_PROVISION_PROCESS_HDR.PRODUCT_CLASS_FROM
     */
    public BigDecimal getPRODUCT_CLASS_FROM() {
        return PRODUCT_CLASS_FROM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROVISION_PROCESS_HDR.PRODUCT_CLASS_FROM
     *
     * @param PRODUCT_CLASS_FROM the value for TRS_PROVISION_PROCESS_HDR.PRODUCT_CLASS_FROM
     */
    public void setPRODUCT_CLASS_FROM(BigDecimal PRODUCT_CLASS_FROM) {
        this.PRODUCT_CLASS_FROM = PRODUCT_CLASS_FROM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROVISION_PROCESS_HDR.PRODUCT_CLASS_TO
     *
     * @return the value of TRS_PROVISION_PROCESS_HDR.PRODUCT_CLASS_TO
     */
    public BigDecimal getPRODUCT_CLASS_TO() {
        return PRODUCT_CLASS_TO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROVISION_PROCESS_HDR.PRODUCT_CLASS_TO
     *
     * @param PRODUCT_CLASS_TO the value for TRS_PROVISION_PROCESS_HDR.PRODUCT_CLASS_TO
     */
    public void setPRODUCT_CLASS_TO(BigDecimal PRODUCT_CLASS_TO) {
        this.PRODUCT_CLASS_TO = PRODUCT_CLASS_TO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROVISION_PROCESS_HDR.DEAL_NO_FROM
     *
     * @return the value of TRS_PROVISION_PROCESS_HDR.DEAL_NO_FROM
     */
    public BigDecimal getDEAL_NO_FROM() {
        return DEAL_NO_FROM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROVISION_PROCESS_HDR.DEAL_NO_FROM
     *
     * @param DEAL_NO_FROM the value for TRS_PROVISION_PROCESS_HDR.DEAL_NO_FROM
     */
    public void setDEAL_NO_FROM(BigDecimal DEAL_NO_FROM) {
        this.DEAL_NO_FROM = DEAL_NO_FROM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROVISION_PROCESS_HDR.DEAL_NO_TO
     *
     * @return the value of TRS_PROVISION_PROCESS_HDR.DEAL_NO_TO
     */
    public BigDecimal getDEAL_NO_TO() {
        return DEAL_NO_TO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROVISION_PROCESS_HDR.DEAL_NO_TO
     *
     * @param DEAL_NO_TO the value for TRS_PROVISION_PROCESS_HDR.DEAL_NO_TO
     */
    public void setDEAL_NO_TO(BigDecimal DEAL_NO_TO) {
        this.DEAL_NO_TO = DEAL_NO_TO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROVISION_PROCESS_HDR.PRODUCT_CODE_FROM
     *
     * @return the value of TRS_PROVISION_PROCESS_HDR.PRODUCT_CODE_FROM
     */
    public BigDecimal getPRODUCT_CODE_FROM() {
        return PRODUCT_CODE_FROM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROVISION_PROCESS_HDR.PRODUCT_CODE_FROM
     *
     * @param PRODUCT_CODE_FROM the value for TRS_PROVISION_PROCESS_HDR.PRODUCT_CODE_FROM
     */
    public void setPRODUCT_CODE_FROM(BigDecimal PRODUCT_CODE_FROM) {
        this.PRODUCT_CODE_FROM = PRODUCT_CODE_FROM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROVISION_PROCESS_HDR.PRODUCT_CODE_TO
     *
     * @return the value of TRS_PROVISION_PROCESS_HDR.PRODUCT_CODE_TO
     */
    public BigDecimal getPRODUCT_CODE_TO() {
        return PRODUCT_CODE_TO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROVISION_PROCESS_HDR.PRODUCT_CODE_TO
     *
     * @param PRODUCT_CODE_TO the value for TRS_PROVISION_PROCESS_HDR.PRODUCT_CODE_TO
     */
    public void setPRODUCT_CODE_TO(BigDecimal PRODUCT_CODE_TO) {
        this.PRODUCT_CODE_TO = PRODUCT_CODE_TO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROVISION_PROCESS_HDR.PROVISION_CLASS_FROM
     *
     * @return the value of TRS_PROVISION_PROCESS_HDR.PROVISION_CLASS_FROM
     */
    public BigDecimal getPROVISION_CLASS_FROM() {
        return PROVISION_CLASS_FROM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROVISION_PROCESS_HDR.PROVISION_CLASS_FROM
     *
     * @param PROVISION_CLASS_FROM the value for TRS_PROVISION_PROCESS_HDR.PROVISION_CLASS_FROM
     */
    public void setPROVISION_CLASS_FROM(BigDecimal PROVISION_CLASS_FROM) {
        this.PROVISION_CLASS_FROM = PROVISION_CLASS_FROM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROVISION_PROCESS_HDR.PROVISION_CLASS_TO
     *
     * @return the value of TRS_PROVISION_PROCESS_HDR.PROVISION_CLASS_TO
     */
    public BigDecimal getPROVISION_CLASS_TO() {
        return PROVISION_CLASS_TO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROVISION_PROCESS_HDR.PROVISION_CLASS_TO
     *
     * @param PROVISION_CLASS_TO the value for TRS_PROVISION_PROCESS_HDR.PROVISION_CLASS_TO
     */
    public void setPROVISION_CLASS_TO(BigDecimal PROVISION_CLASS_TO) {
        this.PROVISION_CLASS_TO = PROVISION_CLASS_TO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROVISION_PROCESS_HDR.DEAL_CATEGORY_FROM
     *
     * @return the value of TRS_PROVISION_PROCESS_HDR.DEAL_CATEGORY_FROM
     */
    public BigDecimal getDEAL_CATEGORY_FROM() {
        return DEAL_CATEGORY_FROM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROVISION_PROCESS_HDR.DEAL_CATEGORY_FROM
     *
     * @param DEAL_CATEGORY_FROM the value for TRS_PROVISION_PROCESS_HDR.DEAL_CATEGORY_FROM
     */
    public void setDEAL_CATEGORY_FROM(BigDecimal DEAL_CATEGORY_FROM) {
        this.DEAL_CATEGORY_FROM = DEAL_CATEGORY_FROM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROVISION_PROCESS_HDR.DEAL_CATEGORY_TO
     *
     * @return the value of TRS_PROVISION_PROCESS_HDR.DEAL_CATEGORY_TO
     */
    public BigDecimal getDEAL_CATEGORY_TO() {
        return DEAL_CATEGORY_TO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROVISION_PROCESS_HDR.DEAL_CATEGORY_TO
     *
     * @param DEAL_CATEGORY_TO the value for TRS_PROVISION_PROCESS_HDR.DEAL_CATEGORY_TO
     */
    public void setDEAL_CATEGORY_TO(BigDecimal DEAL_CATEGORY_TO) {
        this.DEAL_CATEGORY_TO = DEAL_CATEGORY_TO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROVISION_PROCESS_HDR.DEAL_BRANCH_FROM
     *
     * @return the value of TRS_PROVISION_PROCESS_HDR.DEAL_BRANCH_FROM
     */
    public BigDecimal getDEAL_BRANCH_FROM() {
        return DEAL_BRANCH_FROM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROVISION_PROCESS_HDR.DEAL_BRANCH_FROM
     *
     * @param DEAL_BRANCH_FROM the value for TRS_PROVISION_PROCESS_HDR.DEAL_BRANCH_FROM
     */
    public void setDEAL_BRANCH_FROM(BigDecimal DEAL_BRANCH_FROM) {
        this.DEAL_BRANCH_FROM = DEAL_BRANCH_FROM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROVISION_PROCESS_HDR.DEAL_BRANCH_TO
     *
     * @return the value of TRS_PROVISION_PROCESS_HDR.DEAL_BRANCH_TO
     */
    public BigDecimal getDEAL_BRANCH_TO() {
        return DEAL_BRANCH_TO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROVISION_PROCESS_HDR.DEAL_BRANCH_TO
     *
     * @param DEAL_BRANCH_TO the value for TRS_PROVISION_PROCESS_HDR.DEAL_BRANCH_TO
     */
    public void setDEAL_BRANCH_TO(BigDecimal DEAL_BRANCH_TO) {
        this.DEAL_BRANCH_TO = DEAL_BRANCH_TO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROVISION_PROCESS_HDR.EXCLUDE_CLOSED_DEALS
     *
     * @return the value of TRS_PROVISION_PROCESS_HDR.EXCLUDE_CLOSED_DEALS
     */
    public String getEXCLUDE_CLOSED_DEALS() {
        return EXCLUDE_CLOSED_DEALS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROVISION_PROCESS_HDR.EXCLUDE_CLOSED_DEALS
     *
     * @param EXCLUDE_CLOSED_DEALS the value for TRS_PROVISION_PROCESS_HDR.EXCLUDE_CLOSED_DEALS
     */
    public void setEXCLUDE_CLOSED_DEALS(String EXCLUDE_CLOSED_DEALS) {
        this.EXCLUDE_CLOSED_DEALS = EXCLUDE_CLOSED_DEALS == null ? null : EXCLUDE_CLOSED_DEALS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROVISION_PROCESS_HDR.PROCESSED_BY
     *
     * @return the value of TRS_PROVISION_PROCESS_HDR.PROCESSED_BY
     */
    public String getPROCESSED_BY() {
        return PROCESSED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROVISION_PROCESS_HDR.PROCESSED_BY
     *
     * @param PROCESSED_BY the value for TRS_PROVISION_PROCESS_HDR.PROCESSED_BY
     */
    public void setPROCESSED_BY(String PROCESSED_BY) {
        this.PROCESSED_BY = PROCESSED_BY == null ? null : PROCESSED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROVISION_PROCESS_HDR.PROCESS_SERVER_DATE
     *
     * @return the value of TRS_PROVISION_PROCESS_HDR.PROCESS_SERVER_DATE
     */
    public Date getPROCESS_SERVER_DATE() {
        return PROCESS_SERVER_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROVISION_PROCESS_HDR.PROCESS_SERVER_DATE
     *
     * @param PROCESS_SERVER_DATE the value for TRS_PROVISION_PROCESS_HDR.PROCESS_SERVER_DATE
     */
    public void setPROCESS_SERVER_DATE(Date PROCESS_SERVER_DATE) {
        this.PROCESS_SERVER_DATE = PROCESS_SERVER_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROVISION_PROCESS_HDR.VERIFIED_BY
     *
     * @return the value of TRS_PROVISION_PROCESS_HDR.VERIFIED_BY
     */
    public String getVERIFIED_BY() {
        return VERIFIED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROVISION_PROCESS_HDR.VERIFIED_BY
     *
     * @param VERIFIED_BY the value for TRS_PROVISION_PROCESS_HDR.VERIFIED_BY
     */
    public void setVERIFIED_BY(String VERIFIED_BY) {
        this.VERIFIED_BY = VERIFIED_BY == null ? null : VERIFIED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROVISION_PROCESS_HDR.VERIFIED_DATE
     *
     * @return the value of TRS_PROVISION_PROCESS_HDR.VERIFIED_DATE
     */
    public Date getVERIFIED_DATE() {
        return VERIFIED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROVISION_PROCESS_HDR.VERIFIED_DATE
     *
     * @param VERIFIED_DATE the value for TRS_PROVISION_PROCESS_HDR.VERIFIED_DATE
     */
    public void setVERIFIED_DATE(Date VERIFIED_DATE) {
        this.VERIFIED_DATE = VERIFIED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROVISION_PROCESS_HDR.VERIFIED_SERVER_DATE
     *
     * @return the value of TRS_PROVISION_PROCESS_HDR.VERIFIED_SERVER_DATE
     */
    public Date getVERIFIED_SERVER_DATE() {
        return VERIFIED_SERVER_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROVISION_PROCESS_HDR.VERIFIED_SERVER_DATE
     *
     * @param VERIFIED_SERVER_DATE the value for TRS_PROVISION_PROCESS_HDR.VERIFIED_SERVER_DATE
     */
    public void setVERIFIED_SERVER_DATE(Date VERIFIED_SERVER_DATE) {
        this.VERIFIED_SERVER_DATE = VERIFIED_SERVER_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROVISION_PROCESS_HDR.APPROVED_BY
     *
     * @return the value of TRS_PROVISION_PROCESS_HDR.APPROVED_BY
     */
    public String getAPPROVED_BY() {
        return APPROVED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROVISION_PROCESS_HDR.APPROVED_BY
     *
     * @param APPROVED_BY the value for TRS_PROVISION_PROCESS_HDR.APPROVED_BY
     */
    public void setAPPROVED_BY(String APPROVED_BY) {
        this.APPROVED_BY = APPROVED_BY == null ? null : APPROVED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROVISION_PROCESS_HDR.APPROVED_DATE
     *
     * @return the value of TRS_PROVISION_PROCESS_HDR.APPROVED_DATE
     */
    public Date getAPPROVED_DATE() {
        return APPROVED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROVISION_PROCESS_HDR.APPROVED_DATE
     *
     * @param APPROVED_DATE the value for TRS_PROVISION_PROCESS_HDR.APPROVED_DATE
     */
    public void setAPPROVED_DATE(Date APPROVED_DATE) {
        this.APPROVED_DATE = APPROVED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROVISION_PROCESS_HDR.APPROVED_SERVER_DATE
     *
     * @return the value of TRS_PROVISION_PROCESS_HDR.APPROVED_SERVER_DATE
     */
    public Date getAPPROVED_SERVER_DATE() {
        return APPROVED_SERVER_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROVISION_PROCESS_HDR.APPROVED_SERVER_DATE
     *
     * @param APPROVED_SERVER_DATE the value for TRS_PROVISION_PROCESS_HDR.APPROVED_SERVER_DATE
     */
    public void setAPPROVED_SERVER_DATE(Date APPROVED_SERVER_DATE) {
        this.APPROVED_SERVER_DATE = APPROVED_SERVER_DATE;
    }
}