package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class TRS_ITEM_CATEGORYVO extends TRS_ITEM_CATEGORYVOKey {
    /**
     * This field corresponds to the database column TRS_ITEM_CATEGORY.BRIEF_NAME_ENG
     */
    private String BRIEF_NAME_ENG;

    /**
     * This field corresponds to the database column TRS_ITEM_CATEGORY.LONG_NAME_ENG
     */
    private String LONG_NAME_ENG;

    /**
     * This field corresponds to the database column TRS_ITEM_CATEGORY.BRIEF_NAME_ARAB
     */
    private String BRIEF_NAME_ARAB;

    /**
     * This field corresponds to the database column TRS_ITEM_CATEGORY.LONG_NAME_ARAB
     */
    private String LONG_NAME_ARAB;

    /**
     * This field corresponds to the database column TRS_ITEM_CATEGORY.TITLE1
     */
    private String TITLE1;

    /**
     * This field corresponds to the database column TRS_ITEM_CATEGORY.TITLE2
     */
    private String TITLE2;

    /**
     * This field corresponds to the database column TRS_ITEM_CATEGORY.TITLE3
     */
    private String TITLE3;

    /**
     * This field corresponds to the database column TRS_ITEM_CATEGORY.TITLE4
     */
    private String TITLE4;

    /**
     * This field corresponds to the database column TRS_ITEM_CATEGORY.TITLE5
     */
    private String TITLE5;

    /**
     * This field corresponds to the database column TRS_ITEM_CATEGORY.CREATED_BY
     */
    private String CREATED_BY;

    /**
     * This field corresponds to the database column TRS_ITEM_CATEGORY.DATE_CREATED
     */
    private Date DATE_CREATED;

    /**
     * This field corresponds to the database column TRS_ITEM_CATEGORY.MODIFIED_BY
     */
    private String MODIFIED_BY;

    /**
     * This field corresponds to the database column TRS_ITEM_CATEGORY.DATE_MODIFIED
     */
    private Date DATE_MODIFIED;

    /**
     * This field corresponds to the database column TRS_ITEM_CATEGORY.TITLE6
     */
    private String TITLE6;

    /**
     * This field corresponds to the database column TRS_ITEM_CATEGORY.TITLE7
     */
    private String TITLE7;

    /**
     * This field corresponds to the database column TRS_ITEM_CATEGORY.TITLE8
     */
    private String TITLE8;

    /**
     * This field corresponds to the database column TRS_ITEM_CATEGORY.TITLE9
     */
    private String TITLE9;

    /**
     * This field corresponds to the database column TRS_ITEM_CATEGORY.TITLE10
     */
    private String TITLE10;

    /**
     * This field corresponds to the database column TRS_ITEM_CATEGORY.PROPERTY_CODE1
     */
    private BigDecimal PROPERTY_CODE1;

    /**
     * This field corresponds to the database column TRS_ITEM_CATEGORY.PROPERTY_CODE2
     */
    private BigDecimal PROPERTY_CODE2;

    /**
     * This field corresponds to the database column TRS_ITEM_CATEGORY.PROPERTY_CODE3
     */
    private BigDecimal PROPERTY_CODE3;

    /**
     * This field corresponds to the database column TRS_ITEM_CATEGORY.PROPERTY_CODE4
     */
    private BigDecimal PROPERTY_CODE4;

    /**
     * This field corresponds to the database column TRS_ITEM_CATEGORY.PROPERTY_CODE5
     */
    private BigDecimal PROPERTY_CODE5;

    /**
     * This field corresponds to the database column TRS_ITEM_CATEGORY.PROPERTY_CODE6
     */
    private BigDecimal PROPERTY_CODE6;

    /**
     * This field corresponds to the database column TRS_ITEM_CATEGORY.PROPERTY_CODE7
     */
    private BigDecimal PROPERTY_CODE7;

    /**
     * This field corresponds to the database column TRS_ITEM_CATEGORY.PROPERTY_CODE8
     */
    private BigDecimal PROPERTY_CODE8;

    /**
     * This field corresponds to the database column TRS_ITEM_CATEGORY.PROPERTY_CODE9
     */
    private BigDecimal PROPERTY_CODE9;

    /**
     * This field corresponds to the database column TRS_ITEM_CATEGORY.PROPERTY_CODE10
     */
    private BigDecimal PROPERTY_CODE10;

    /**
     * This field corresponds to the database column TRS_ITEM_CATEGORY.AR_RAHNU_YN
     */
    private String AR_RAHNU_YN;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_ITEM_CATEGORY.BRIEF_NAME_ENG
     *
     * @return the value of TRS_ITEM_CATEGORY.BRIEF_NAME_ENG
     */
    public String getBRIEF_NAME_ENG() {
        return BRIEF_NAME_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_ITEM_CATEGORY.BRIEF_NAME_ENG
     *
     * @param BRIEF_NAME_ENG the value for TRS_ITEM_CATEGORY.BRIEF_NAME_ENG
     */
    public void setBRIEF_NAME_ENG(String BRIEF_NAME_ENG) {
        this.BRIEF_NAME_ENG = BRIEF_NAME_ENG == null ? null : BRIEF_NAME_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_ITEM_CATEGORY.LONG_NAME_ENG
     *
     * @return the value of TRS_ITEM_CATEGORY.LONG_NAME_ENG
     */
    public String getLONG_NAME_ENG() {
        return LONG_NAME_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_ITEM_CATEGORY.LONG_NAME_ENG
     *
     * @param LONG_NAME_ENG the value for TRS_ITEM_CATEGORY.LONG_NAME_ENG
     */
    public void setLONG_NAME_ENG(String LONG_NAME_ENG) {
        this.LONG_NAME_ENG = LONG_NAME_ENG == null ? null : LONG_NAME_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_ITEM_CATEGORY.BRIEF_NAME_ARAB
     *
     * @return the value of TRS_ITEM_CATEGORY.BRIEF_NAME_ARAB
     */
    public String getBRIEF_NAME_ARAB() {
        return BRIEF_NAME_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_ITEM_CATEGORY.BRIEF_NAME_ARAB
     *
     * @param BRIEF_NAME_ARAB the value for TRS_ITEM_CATEGORY.BRIEF_NAME_ARAB
     */
    public void setBRIEF_NAME_ARAB(String BRIEF_NAME_ARAB) {
        this.BRIEF_NAME_ARAB = BRIEF_NAME_ARAB == null ? null : BRIEF_NAME_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_ITEM_CATEGORY.LONG_NAME_ARAB
     *
     * @return the value of TRS_ITEM_CATEGORY.LONG_NAME_ARAB
     */
    public String getLONG_NAME_ARAB() {
        return LONG_NAME_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_ITEM_CATEGORY.LONG_NAME_ARAB
     *
     * @param LONG_NAME_ARAB the value for TRS_ITEM_CATEGORY.LONG_NAME_ARAB
     */
    public void setLONG_NAME_ARAB(String LONG_NAME_ARAB) {
        this.LONG_NAME_ARAB = LONG_NAME_ARAB == null ? null : LONG_NAME_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_ITEM_CATEGORY.TITLE1
     *
     * @return the value of TRS_ITEM_CATEGORY.TITLE1
     */
    public String getTITLE1() {
        return TITLE1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_ITEM_CATEGORY.TITLE1
     *
     * @param TITLE1 the value for TRS_ITEM_CATEGORY.TITLE1
     */
    public void setTITLE1(String TITLE1) {
        this.TITLE1 = TITLE1 == null ? null : TITLE1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_ITEM_CATEGORY.TITLE2
     *
     * @return the value of TRS_ITEM_CATEGORY.TITLE2
     */
    public String getTITLE2() {
        return TITLE2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_ITEM_CATEGORY.TITLE2
     *
     * @param TITLE2 the value for TRS_ITEM_CATEGORY.TITLE2
     */
    public void setTITLE2(String TITLE2) {
        this.TITLE2 = TITLE2 == null ? null : TITLE2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_ITEM_CATEGORY.TITLE3
     *
     * @return the value of TRS_ITEM_CATEGORY.TITLE3
     */
    public String getTITLE3() {
        return TITLE3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_ITEM_CATEGORY.TITLE3
     *
     * @param TITLE3 the value for TRS_ITEM_CATEGORY.TITLE3
     */
    public void setTITLE3(String TITLE3) {
        this.TITLE3 = TITLE3 == null ? null : TITLE3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_ITEM_CATEGORY.TITLE4
     *
     * @return the value of TRS_ITEM_CATEGORY.TITLE4
     */
    public String getTITLE4() {
        return TITLE4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_ITEM_CATEGORY.TITLE4
     *
     * @param TITLE4 the value for TRS_ITEM_CATEGORY.TITLE4
     */
    public void setTITLE4(String TITLE4) {
        this.TITLE4 = TITLE4 == null ? null : TITLE4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_ITEM_CATEGORY.TITLE5
     *
     * @return the value of TRS_ITEM_CATEGORY.TITLE5
     */
    public String getTITLE5() {
        return TITLE5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_ITEM_CATEGORY.TITLE5
     *
     * @param TITLE5 the value for TRS_ITEM_CATEGORY.TITLE5
     */
    public void setTITLE5(String TITLE5) {
        this.TITLE5 = TITLE5 == null ? null : TITLE5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_ITEM_CATEGORY.CREATED_BY
     *
     * @return the value of TRS_ITEM_CATEGORY.CREATED_BY
     */
    public String getCREATED_BY() {
        return CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_ITEM_CATEGORY.CREATED_BY
     *
     * @param CREATED_BY the value for TRS_ITEM_CATEGORY.CREATED_BY
     */
    public void setCREATED_BY(String CREATED_BY) {
        this.CREATED_BY = CREATED_BY == null ? null : CREATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_ITEM_CATEGORY.DATE_CREATED
     *
     * @return the value of TRS_ITEM_CATEGORY.DATE_CREATED
     */
    public Date getDATE_CREATED() {
        return DATE_CREATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_ITEM_CATEGORY.DATE_CREATED
     *
     * @param DATE_CREATED the value for TRS_ITEM_CATEGORY.DATE_CREATED
     */
    public void setDATE_CREATED(Date DATE_CREATED) {
        this.DATE_CREATED = DATE_CREATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_ITEM_CATEGORY.MODIFIED_BY
     *
     * @return the value of TRS_ITEM_CATEGORY.MODIFIED_BY
     */
    public String getMODIFIED_BY() {
        return MODIFIED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_ITEM_CATEGORY.MODIFIED_BY
     *
     * @param MODIFIED_BY the value for TRS_ITEM_CATEGORY.MODIFIED_BY
     */
    public void setMODIFIED_BY(String MODIFIED_BY) {
        this.MODIFIED_BY = MODIFIED_BY == null ? null : MODIFIED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_ITEM_CATEGORY.DATE_MODIFIED
     *
     * @return the value of TRS_ITEM_CATEGORY.DATE_MODIFIED
     */
    public Date getDATE_MODIFIED() {
        return DATE_MODIFIED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_ITEM_CATEGORY.DATE_MODIFIED
     *
     * @param DATE_MODIFIED the value for TRS_ITEM_CATEGORY.DATE_MODIFIED
     */
    public void setDATE_MODIFIED(Date DATE_MODIFIED) {
        this.DATE_MODIFIED = DATE_MODIFIED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_ITEM_CATEGORY.TITLE6
     *
     * @return the value of TRS_ITEM_CATEGORY.TITLE6
     */
    public String getTITLE6() {
        return TITLE6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_ITEM_CATEGORY.TITLE6
     *
     * @param TITLE6 the value for TRS_ITEM_CATEGORY.TITLE6
     */
    public void setTITLE6(String TITLE6) {
        this.TITLE6 = TITLE6 == null ? null : TITLE6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_ITEM_CATEGORY.TITLE7
     *
     * @return the value of TRS_ITEM_CATEGORY.TITLE7
     */
    public String getTITLE7() {
        return TITLE7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_ITEM_CATEGORY.TITLE7
     *
     * @param TITLE7 the value for TRS_ITEM_CATEGORY.TITLE7
     */
    public void setTITLE7(String TITLE7) {
        this.TITLE7 = TITLE7 == null ? null : TITLE7.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_ITEM_CATEGORY.TITLE8
     *
     * @return the value of TRS_ITEM_CATEGORY.TITLE8
     */
    public String getTITLE8() {
        return TITLE8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_ITEM_CATEGORY.TITLE8
     *
     * @param TITLE8 the value for TRS_ITEM_CATEGORY.TITLE8
     */
    public void setTITLE8(String TITLE8) {
        this.TITLE8 = TITLE8 == null ? null : TITLE8.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_ITEM_CATEGORY.TITLE9
     *
     * @return the value of TRS_ITEM_CATEGORY.TITLE9
     */
    public String getTITLE9() {
        return TITLE9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_ITEM_CATEGORY.TITLE9
     *
     * @param TITLE9 the value for TRS_ITEM_CATEGORY.TITLE9
     */
    public void setTITLE9(String TITLE9) {
        this.TITLE9 = TITLE9 == null ? null : TITLE9.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_ITEM_CATEGORY.TITLE10
     *
     * @return the value of TRS_ITEM_CATEGORY.TITLE10
     */
    public String getTITLE10() {
        return TITLE10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_ITEM_CATEGORY.TITLE10
     *
     * @param TITLE10 the value for TRS_ITEM_CATEGORY.TITLE10
     */
    public void setTITLE10(String TITLE10) {
        this.TITLE10 = TITLE10 == null ? null : TITLE10.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_ITEM_CATEGORY.PROPERTY_CODE1
     *
     * @return the value of TRS_ITEM_CATEGORY.PROPERTY_CODE1
     */
    public BigDecimal getPROPERTY_CODE1() {
        return PROPERTY_CODE1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_ITEM_CATEGORY.PROPERTY_CODE1
     *
     * @param PROPERTY_CODE1 the value for TRS_ITEM_CATEGORY.PROPERTY_CODE1
     */
    public void setPROPERTY_CODE1(BigDecimal PROPERTY_CODE1) {
        this.PROPERTY_CODE1 = PROPERTY_CODE1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_ITEM_CATEGORY.PROPERTY_CODE2
     *
     * @return the value of TRS_ITEM_CATEGORY.PROPERTY_CODE2
     */
    public BigDecimal getPROPERTY_CODE2() {
        return PROPERTY_CODE2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_ITEM_CATEGORY.PROPERTY_CODE2
     *
     * @param PROPERTY_CODE2 the value for TRS_ITEM_CATEGORY.PROPERTY_CODE2
     */
    public void setPROPERTY_CODE2(BigDecimal PROPERTY_CODE2) {
        this.PROPERTY_CODE2 = PROPERTY_CODE2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_ITEM_CATEGORY.PROPERTY_CODE3
     *
     * @return the value of TRS_ITEM_CATEGORY.PROPERTY_CODE3
     */
    public BigDecimal getPROPERTY_CODE3() {
        return PROPERTY_CODE3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_ITEM_CATEGORY.PROPERTY_CODE3
     *
     * @param PROPERTY_CODE3 the value for TRS_ITEM_CATEGORY.PROPERTY_CODE3
     */
    public void setPROPERTY_CODE3(BigDecimal PROPERTY_CODE3) {
        this.PROPERTY_CODE3 = PROPERTY_CODE3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_ITEM_CATEGORY.PROPERTY_CODE4
     *
     * @return the value of TRS_ITEM_CATEGORY.PROPERTY_CODE4
     */
    public BigDecimal getPROPERTY_CODE4() {
        return PROPERTY_CODE4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_ITEM_CATEGORY.PROPERTY_CODE4
     *
     * @param PROPERTY_CODE4 the value for TRS_ITEM_CATEGORY.PROPERTY_CODE4
     */
    public void setPROPERTY_CODE4(BigDecimal PROPERTY_CODE4) {
        this.PROPERTY_CODE4 = PROPERTY_CODE4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_ITEM_CATEGORY.PROPERTY_CODE5
     *
     * @return the value of TRS_ITEM_CATEGORY.PROPERTY_CODE5
     */
    public BigDecimal getPROPERTY_CODE5() {
        return PROPERTY_CODE5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_ITEM_CATEGORY.PROPERTY_CODE5
     *
     * @param PROPERTY_CODE5 the value for TRS_ITEM_CATEGORY.PROPERTY_CODE5
     */
    public void setPROPERTY_CODE5(BigDecimal PROPERTY_CODE5) {
        this.PROPERTY_CODE5 = PROPERTY_CODE5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_ITEM_CATEGORY.PROPERTY_CODE6
     *
     * @return the value of TRS_ITEM_CATEGORY.PROPERTY_CODE6
     */
    public BigDecimal getPROPERTY_CODE6() {
        return PROPERTY_CODE6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_ITEM_CATEGORY.PROPERTY_CODE6
     *
     * @param PROPERTY_CODE6 the value for TRS_ITEM_CATEGORY.PROPERTY_CODE6
     */
    public void setPROPERTY_CODE6(BigDecimal PROPERTY_CODE6) {
        this.PROPERTY_CODE6 = PROPERTY_CODE6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_ITEM_CATEGORY.PROPERTY_CODE7
     *
     * @return the value of TRS_ITEM_CATEGORY.PROPERTY_CODE7
     */
    public BigDecimal getPROPERTY_CODE7() {
        return PROPERTY_CODE7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_ITEM_CATEGORY.PROPERTY_CODE7
     *
     * @param PROPERTY_CODE7 the value for TRS_ITEM_CATEGORY.PROPERTY_CODE7
     */
    public void setPROPERTY_CODE7(BigDecimal PROPERTY_CODE7) {
        this.PROPERTY_CODE7 = PROPERTY_CODE7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_ITEM_CATEGORY.PROPERTY_CODE8
     *
     * @return the value of TRS_ITEM_CATEGORY.PROPERTY_CODE8
     */
    public BigDecimal getPROPERTY_CODE8() {
        return PROPERTY_CODE8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_ITEM_CATEGORY.PROPERTY_CODE8
     *
     * @param PROPERTY_CODE8 the value for TRS_ITEM_CATEGORY.PROPERTY_CODE8
     */
    public void setPROPERTY_CODE8(BigDecimal PROPERTY_CODE8) {
        this.PROPERTY_CODE8 = PROPERTY_CODE8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_ITEM_CATEGORY.PROPERTY_CODE9
     *
     * @return the value of TRS_ITEM_CATEGORY.PROPERTY_CODE9
     */
    public BigDecimal getPROPERTY_CODE9() {
        return PROPERTY_CODE9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_ITEM_CATEGORY.PROPERTY_CODE9
     *
     * @param PROPERTY_CODE9 the value for TRS_ITEM_CATEGORY.PROPERTY_CODE9
     */
    public void setPROPERTY_CODE9(BigDecimal PROPERTY_CODE9) {
        this.PROPERTY_CODE9 = PROPERTY_CODE9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_ITEM_CATEGORY.PROPERTY_CODE10
     *
     * @return the value of TRS_ITEM_CATEGORY.PROPERTY_CODE10
     */
    public BigDecimal getPROPERTY_CODE10() {
        return PROPERTY_CODE10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_ITEM_CATEGORY.PROPERTY_CODE10
     *
     * @param PROPERTY_CODE10 the value for TRS_ITEM_CATEGORY.PROPERTY_CODE10
     */
    public void setPROPERTY_CODE10(BigDecimal PROPERTY_CODE10) {
        this.PROPERTY_CODE10 = PROPERTY_CODE10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_ITEM_CATEGORY.AR_RAHNU_YN
     *
     * @return the value of TRS_ITEM_CATEGORY.AR_RAHNU_YN
     */
    public String getAR_RAHNU_YN() {
        return AR_RAHNU_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_ITEM_CATEGORY.AR_RAHNU_YN
     *
     * @param AR_RAHNU_YN the value for TRS_ITEM_CATEGORY.AR_RAHNU_YN
     */
    public void setAR_RAHNU_YN(String AR_RAHNU_YN) {
        this.AR_RAHNU_YN = AR_RAHNU_YN == null ? null : AR_RAHNU_YN.trim();
    }
}