package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class TRS_PROV_CATEGORY_COLLTYPEVOKey extends BaseVO {
    /**
     * This field corresponds to the database column TRS_PROV_CATEGORY_COLLTYPE.CATEGORY_CODE
     */
    private BigDecimal CATEGORY_CODE;

    /**
     * This field corresponds to the database column TRS_PROV_CATEGORY_COLLTYPE.COLLATERAL_TYPE
     */
    private BigDecimal COLLATERAL_TYPE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROV_CATEGORY_COLLTYPE.CATEGORY_CODE
     *
     * @return the value of TRS_PROV_CATEGORY_COLLTYPE.CATEGORY_CODE
     */
    public BigDecimal getCATEGORY_CODE() {
        return CATEGORY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROV_CATEGORY_COLLTYPE.CATEGORY_CODE
     *
     * @param CATEGORY_CODE the value for TRS_PROV_CATEGORY_COLLTYPE.CATEGORY_CODE
     */
    public void setCATEGORY_CODE(BigDecimal CATEGORY_CODE) {
        this.CATEGORY_CODE = CATEGORY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROV_CATEGORY_COLLTYPE.COLLATERAL_TYPE
     *
     * @return the value of TRS_PROV_CATEGORY_COLLTYPE.COLLATERAL_TYPE
     */
    public BigDecimal getCOLLATERAL_TYPE() {
        return COLLATERAL_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROV_CATEGORY_COLLTYPE.COLLATERAL_TYPE
     *
     * @param COLLATERAL_TYPE the value for TRS_PROV_CATEGORY_COLLTYPE.COLLATERAL_TYPE
     */
    public void setCOLLATERAL_TYPE(BigDecimal COLLATERAL_TYPE) {
        this.COLLATERAL_TYPE = COLLATERAL_TYPE;
    }
}