package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;
import java.util.Date;

public class TRS_FX_DESK_LIMIT_SUMVOKey extends BaseVO {
    /**
     * This field corresponds to the database column TRS_FX_DESK_LIMIT_SUM.BRANCH_CODE
     */
    private BigDecimal BRANCH_CODE;

    /**
     * This field corresponds to the database column TRS_FX_DESK_LIMIT_SUM.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column TRS_FX_DESK_LIMIT_SUM.DESK_CODE
     */
    private BigDecimal DESK_CODE;

    /**
     * This field corresponds to the database column TRS_FX_DESK_LIMIT_SUM.FIRST_CY
     */
    private BigDecimal FIRST_CY;

    /**
     * This field corresponds to the database column TRS_FX_DESK_LIMIT_SUM.SECOND_CY
     */
    private BigDecimal SECOND_CY;

    /**
     * This field corresponds to the database column TRS_FX_DESK_LIMIT_SUM.TRX_DATE
     */
    private Date TRX_DATE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_FX_DESK_LIMIT_SUM.BRANCH_CODE
     *
     * @return the value of TRS_FX_DESK_LIMIT_SUM.BRANCH_CODE
     */
    public BigDecimal getBRANCH_CODE() {
        return BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_FX_DESK_LIMIT_SUM.BRANCH_CODE
     *
     * @param BRANCH_CODE the value for TRS_FX_DESK_LIMIT_SUM.BRANCH_CODE
     */
    public void setBRANCH_CODE(BigDecimal BRANCH_CODE) {
        this.BRANCH_CODE = BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_FX_DESK_LIMIT_SUM.COMP_CODE
     *
     * @return the value of TRS_FX_DESK_LIMIT_SUM.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_FX_DESK_LIMIT_SUM.COMP_CODE
     *
     * @param COMP_CODE the value for TRS_FX_DESK_LIMIT_SUM.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_FX_DESK_LIMIT_SUM.DESK_CODE
     *
     * @return the value of TRS_FX_DESK_LIMIT_SUM.DESK_CODE
     */
    public BigDecimal getDESK_CODE() {
        return DESK_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_FX_DESK_LIMIT_SUM.DESK_CODE
     *
     * @param DESK_CODE the value for TRS_FX_DESK_LIMIT_SUM.DESK_CODE
     */
    public void setDESK_CODE(BigDecimal DESK_CODE) {
        this.DESK_CODE = DESK_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_FX_DESK_LIMIT_SUM.FIRST_CY
     *
     * @return the value of TRS_FX_DESK_LIMIT_SUM.FIRST_CY
     */
    public BigDecimal getFIRST_CY() {
        return FIRST_CY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_FX_DESK_LIMIT_SUM.FIRST_CY
     *
     * @param FIRST_CY the value for TRS_FX_DESK_LIMIT_SUM.FIRST_CY
     */
    public void setFIRST_CY(BigDecimal FIRST_CY) {
        this.FIRST_CY = FIRST_CY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_FX_DESK_LIMIT_SUM.SECOND_CY
     *
     * @return the value of TRS_FX_DESK_LIMIT_SUM.SECOND_CY
     */
    public BigDecimal getSECOND_CY() {
        return SECOND_CY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_FX_DESK_LIMIT_SUM.SECOND_CY
     *
     * @param SECOND_CY the value for TRS_FX_DESK_LIMIT_SUM.SECOND_CY
     */
    public void setSECOND_CY(BigDecimal SECOND_CY) {
        this.SECOND_CY = SECOND_CY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_FX_DESK_LIMIT_SUM.TRX_DATE
     *
     * @return the value of TRS_FX_DESK_LIMIT_SUM.TRX_DATE
     */
    public Date getTRX_DATE() {
        return TRX_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_FX_DESK_LIMIT_SUM.TRX_DATE
     *
     * @param TRX_DATE the value for TRS_FX_DESK_LIMIT_SUM.TRX_DATE
     */
    public void setTRX_DATE(Date TRX_DATE) {
        this.TRX_DATE = TRX_DATE;
    }
}