package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class TRS_CLASSIFY_NOT_PROCESSEDVO extends TRS_CLASSIFY_NOT_PROCESSEDVOKey {
    /**
     * This field corresponds to the database column TRS_CLASSIFY_NOT_PROCESSED.AC_NO
     */
    private String AC_NO;

    /**
     * This field corresponds to the database column TRS_CLASSIFY_NOT_PROCESSED.CIF_NO
     */
    private BigDecimal CIF_NO;

    /**
     * This field corresponds to the database column TRS_CLASSIFY_NOT_PROCESSED.REASON
     */
    private String REASON;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_CLASSIFY_NOT_PROCESSED.AC_NO
     *
     * @return the value of TRS_CLASSIFY_NOT_PROCESSED.AC_NO
     */
    public String getAC_NO() {
        return AC_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_CLASSIFY_NOT_PROCESSED.AC_NO
     *
     * @param AC_NO the value for TRS_CLASSIFY_NOT_PROCESSED.AC_NO
     */
    public void setAC_NO(String AC_NO) {
        this.AC_NO = AC_NO == null ? null : AC_NO.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_CLASSIFY_NOT_PROCESSED.CIF_NO
     *
     * @return the value of TRS_CLASSIFY_NOT_PROCESSED.CIF_NO
     */
    public BigDecimal getCIF_NO() {
        return CIF_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_CLASSIFY_NOT_PROCESSED.CIF_NO
     *
     * @param CIF_NO the value for TRS_CLASSIFY_NOT_PROCESSED.CIF_NO
     */
    public void setCIF_NO(BigDecimal CIF_NO) {
        this.CIF_NO = CIF_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_CLASSIFY_NOT_PROCESSED.REASON
     *
     * @return the value of TRS_CLASSIFY_NOT_PROCESSED.REASON
     */
    public String getREASON() {
        return REASON;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_CLASSIFY_NOT_PROCESSED.REASON
     *
     * @param REASON the value for TRS_CLASSIFY_NOT_PROCESSED.REASON
     */
    public void setREASON(String REASON) {
        this.REASON = REASON == null ? null : REASON.trim();
    }
}