package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class TRS_IBOR_REVALUATION_PROCESSVO extends TRS_IBOR_REVALUATION_PROCESSVOKey {
    /**
     * This field corresponds to the database column TRS_IBOR_REVALUATION_PROCESS.DEAL_RATE
     */
    private BigDecimal DEAL_RATE;

    /**
     * This field corresponds to the database column TRS_IBOR_REVALUATION_PROCESS.CURRENT_RATE
     */
    private BigDecimal CURRENT_RATE;

    /**
     * This field corresponds to the database column TRS_IBOR_REVALUATION_PROCESS.USER_MODIFIED_RATE
     */
    private BigDecimal USER_MODIFIED_RATE;

    /**
     * This field corresponds to the database column TRS_IBOR_REVALUATION_PROCESS.RATE_EFFECTIVE_FROM
     */
    private Date RATE_EFFECTIVE_FROM;

    /**
     * This field corresponds to the database column TRS_IBOR_REVALUATION_PROCESS.PROCESS_DATE
     */
    private Date PROCESS_DATE;

    /**
     * This field corresponds to the database column TRS_IBOR_REVALUATION_PROCESS.PROCESSED_BY
     */
    private String PROCESSED_BY;

    /**
     * This field corresponds to the database column TRS_IBOR_REVALUATION_PROCESS.SERVER_DATE_START
     */
    private Date SERVER_DATE_START;

    /**
     * This field corresponds to the database column TRS_IBOR_REVALUATION_PROCESS.SERVER_DATE_END
     */
    private Date SERVER_DATE_END;

    /**
     * This field corresponds to the database column TRS_IBOR_REVALUATION_PROCESS.EFFECTIVE_DATE
     */
    private Date EFFECTIVE_DATE;

    /**
     * This field corresponds to the database column TRS_IBOR_REVALUATION_PROCESS.REASON_CODE
     */
    private BigDecimal REASON_CODE;

    /**
     * This field corresponds to the database column TRS_IBOR_REVALUATION_PROCESS.ACTION_TYPE
     */
    private String ACTION_TYPE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_IBOR_REVALUATION_PROCESS.DEAL_RATE
     *
     * @return the value of TRS_IBOR_REVALUATION_PROCESS.DEAL_RATE
     */
    public BigDecimal getDEAL_RATE() {
        return DEAL_RATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_IBOR_REVALUATION_PROCESS.DEAL_RATE
     *
     * @param DEAL_RATE the value for TRS_IBOR_REVALUATION_PROCESS.DEAL_RATE
     */
    public void setDEAL_RATE(BigDecimal DEAL_RATE) {
        this.DEAL_RATE = DEAL_RATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_IBOR_REVALUATION_PROCESS.CURRENT_RATE
     *
     * @return the value of TRS_IBOR_REVALUATION_PROCESS.CURRENT_RATE
     */
    public BigDecimal getCURRENT_RATE() {
        return CURRENT_RATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_IBOR_REVALUATION_PROCESS.CURRENT_RATE
     *
     * @param CURRENT_RATE the value for TRS_IBOR_REVALUATION_PROCESS.CURRENT_RATE
     */
    public void setCURRENT_RATE(BigDecimal CURRENT_RATE) {
        this.CURRENT_RATE = CURRENT_RATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_IBOR_REVALUATION_PROCESS.USER_MODIFIED_RATE
     *
     * @return the value of TRS_IBOR_REVALUATION_PROCESS.USER_MODIFIED_RATE
     */
    public BigDecimal getUSER_MODIFIED_RATE() {
        return USER_MODIFIED_RATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_IBOR_REVALUATION_PROCESS.USER_MODIFIED_RATE
     *
     * @param USER_MODIFIED_RATE the value for TRS_IBOR_REVALUATION_PROCESS.USER_MODIFIED_RATE
     */
    public void setUSER_MODIFIED_RATE(BigDecimal USER_MODIFIED_RATE) {
        this.USER_MODIFIED_RATE = USER_MODIFIED_RATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_IBOR_REVALUATION_PROCESS.RATE_EFFECTIVE_FROM
     *
     * @return the value of TRS_IBOR_REVALUATION_PROCESS.RATE_EFFECTIVE_FROM
     */
    public Date getRATE_EFFECTIVE_FROM() {
        return RATE_EFFECTIVE_FROM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_IBOR_REVALUATION_PROCESS.RATE_EFFECTIVE_FROM
     *
     * @param RATE_EFFECTIVE_FROM the value for TRS_IBOR_REVALUATION_PROCESS.RATE_EFFECTIVE_FROM
     */
    public void setRATE_EFFECTIVE_FROM(Date RATE_EFFECTIVE_FROM) {
        this.RATE_EFFECTIVE_FROM = RATE_EFFECTIVE_FROM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_IBOR_REVALUATION_PROCESS.PROCESS_DATE
     *
     * @return the value of TRS_IBOR_REVALUATION_PROCESS.PROCESS_DATE
     */
    public Date getPROCESS_DATE() {
        return PROCESS_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_IBOR_REVALUATION_PROCESS.PROCESS_DATE
     *
     * @param PROCESS_DATE the value for TRS_IBOR_REVALUATION_PROCESS.PROCESS_DATE
     */
    public void setPROCESS_DATE(Date PROCESS_DATE) {
        this.PROCESS_DATE = PROCESS_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_IBOR_REVALUATION_PROCESS.PROCESSED_BY
     *
     * @return the value of TRS_IBOR_REVALUATION_PROCESS.PROCESSED_BY
     */
    public String getPROCESSED_BY() {
        return PROCESSED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_IBOR_REVALUATION_PROCESS.PROCESSED_BY
     *
     * @param PROCESSED_BY the value for TRS_IBOR_REVALUATION_PROCESS.PROCESSED_BY
     */
    public void setPROCESSED_BY(String PROCESSED_BY) {
        this.PROCESSED_BY = PROCESSED_BY == null ? null : PROCESSED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_IBOR_REVALUATION_PROCESS.SERVER_DATE_START
     *
     * @return the value of TRS_IBOR_REVALUATION_PROCESS.SERVER_DATE_START
     */
    public Date getSERVER_DATE_START() {
        return SERVER_DATE_START;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_IBOR_REVALUATION_PROCESS.SERVER_DATE_START
     *
     * @param SERVER_DATE_START the value for TRS_IBOR_REVALUATION_PROCESS.SERVER_DATE_START
     */
    public void setSERVER_DATE_START(Date SERVER_DATE_START) {
        this.SERVER_DATE_START = SERVER_DATE_START;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_IBOR_REVALUATION_PROCESS.SERVER_DATE_END
     *
     * @return the value of TRS_IBOR_REVALUATION_PROCESS.SERVER_DATE_END
     */
    public Date getSERVER_DATE_END() {
        return SERVER_DATE_END;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_IBOR_REVALUATION_PROCESS.SERVER_DATE_END
     *
     * @param SERVER_DATE_END the value for TRS_IBOR_REVALUATION_PROCESS.SERVER_DATE_END
     */
    public void setSERVER_DATE_END(Date SERVER_DATE_END) {
        this.SERVER_DATE_END = SERVER_DATE_END;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_IBOR_REVALUATION_PROCESS.EFFECTIVE_DATE
     *
     * @return the value of TRS_IBOR_REVALUATION_PROCESS.EFFECTIVE_DATE
     */
    public Date getEFFECTIVE_DATE() {
        return EFFECTIVE_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_IBOR_REVALUATION_PROCESS.EFFECTIVE_DATE
     *
     * @param EFFECTIVE_DATE the value for TRS_IBOR_REVALUATION_PROCESS.EFFECTIVE_DATE
     */
    public void setEFFECTIVE_DATE(Date EFFECTIVE_DATE) {
        this.EFFECTIVE_DATE = EFFECTIVE_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_IBOR_REVALUATION_PROCESS.REASON_CODE
     *
     * @return the value of TRS_IBOR_REVALUATION_PROCESS.REASON_CODE
     */
    public BigDecimal getREASON_CODE() {
        return REASON_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_IBOR_REVALUATION_PROCESS.REASON_CODE
     *
     * @param REASON_CODE the value for TRS_IBOR_REVALUATION_PROCESS.REASON_CODE
     */
    public void setREASON_CODE(BigDecimal REASON_CODE) {
        this.REASON_CODE = REASON_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_IBOR_REVALUATION_PROCESS.ACTION_TYPE
     *
     * @return the value of TRS_IBOR_REVALUATION_PROCESS.ACTION_TYPE
     */
    public String getACTION_TYPE() {
        return ACTION_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_IBOR_REVALUATION_PROCESS.ACTION_TYPE
     *
     * @param ACTION_TYPE the value for TRS_IBOR_REVALUATION_PROCESS.ACTION_TYPE
     */
    public void setACTION_TYPE(String ACTION_TYPE) {
        this.ACTION_TYPE = ACTION_TYPE == null ? null : ACTION_TYPE.trim();
    }
}