package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class TRS_PROVISION_CIF_STATUSVOKey extends BaseVO {
    /**
     * This field corresponds to the database column TRS_PROVISION_CIF_STATUS.CIF_NO
     */
    private BigDecimal CIF_NO;

    /**
     * This field corresponds to the database column TRS_PROVISION_CIF_STATUS.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column TRS_PROVISION_CIF_STATUS.PROVISION_CLASS
     */
    private BigDecimal PROVISION_CLASS;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROVISION_CIF_STATUS.CIF_NO
     *
     * @return the value of TRS_PROVISION_CIF_STATUS.CIF_NO
     */
    public BigDecimal getCIF_NO() {
        return CIF_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROVISION_CIF_STATUS.CIF_NO
     *
     * @param CIF_NO the value for TRS_PROVISION_CIF_STATUS.CIF_NO
     */
    public void setCIF_NO(BigDecimal CIF_NO) {
        this.CIF_NO = CIF_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROVISION_CIF_STATUS.COMP_CODE
     *
     * @return the value of TRS_PROVISION_CIF_STATUS.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROVISION_CIF_STATUS.COMP_CODE
     *
     * @param COMP_CODE the value for TRS_PROVISION_CIF_STATUS.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROVISION_CIF_STATUS.PROVISION_CLASS
     *
     * @return the value of TRS_PROVISION_CIF_STATUS.PROVISION_CLASS
     */
    public BigDecimal getPROVISION_CLASS() {
        return PROVISION_CLASS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROVISION_CIF_STATUS.PROVISION_CLASS
     *
     * @param PROVISION_CLASS the value for TRS_PROVISION_CIF_STATUS.PROVISION_CLASS
     */
    public void setPROVISION_CLASS(BigDecimal PROVISION_CLASS) {
        this.PROVISION_CLASS = PROVISION_CLASS;
    }
}