package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class TRS_EXPORT_REFINANCE_DETAILSVO extends TRS_EXPORT_REFINANCE_DETAILSVOKey {
    /**
     * This field corresponds to the database column TRS_EXPORT_REFINANCE_DETAILS.CENTRAL_BANK_APPROVAL_DATE
     */
    private Date CENTRAL_BANK_APPROVAL_DATE;

    /**
     * This field corresponds to the database column TRS_EXPORT_REFINANCE_DETAILS.CENTRAL_BANK_APPROV_REF_NO
     */
    private String CENTRAL_BANK_APPROV_REF_NO;

    /**
     * This field corresponds to the database column TRS_EXPORT_REFINANCE_DETAILS.CENTRAL_BANK_LOAN_ID
     */
    private String CENTRAL_BANK_LOAN_ID;

    /**
     * This field corresponds to the database column TRS_EXPORT_REFINANCE_DETAILS.BANK_MARKUP_RATE
     */
    private BigDecimal BANK_MARKUP_RATE;

    /**
     * This field corresponds to the database column TRS_EXPORT_REFINANCE_DETAILS.CENTRAL_BANK_MARKUP_RATE
     */
    private BigDecimal CENTRAL_BANK_MARKUP_RATE;

    /**
     * This field corresponds to the database column TRS_EXPORT_REFINANCE_DETAILS.CREATED_BY
     */
    private String CREATED_BY;

    /**
     * This field corresponds to the database column TRS_EXPORT_REFINANCE_DETAILS.CREATED_DATE
     */
    private Date CREATED_DATE;

    /**
     * This field corresponds to the database column TRS_EXPORT_REFINANCE_DETAILS.MODIFIED_BY
     */
    private String MODIFIED_BY;

    /**
     * This field corresponds to the database column TRS_EXPORT_REFINANCE_DETAILS.MODIFIED_DATE
     */
    private Date MODIFIED_DATE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_EXPORT_REFINANCE_DETAILS.CENTRAL_BANK_APPROVAL_DATE
     *
     * @return the value of TRS_EXPORT_REFINANCE_DETAILS.CENTRAL_BANK_APPROVAL_DATE
     */
    public Date getCENTRAL_BANK_APPROVAL_DATE() {
        return CENTRAL_BANK_APPROVAL_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_EXPORT_REFINANCE_DETAILS.CENTRAL_BANK_APPROVAL_DATE
     *
     * @param CENTRAL_BANK_APPROVAL_DATE the value for TRS_EXPORT_REFINANCE_DETAILS.CENTRAL_BANK_APPROVAL_DATE
     */
    public void setCENTRAL_BANK_APPROVAL_DATE(Date CENTRAL_BANK_APPROVAL_DATE) {
        this.CENTRAL_BANK_APPROVAL_DATE = CENTRAL_BANK_APPROVAL_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_EXPORT_REFINANCE_DETAILS.CENTRAL_BANK_APPROV_REF_NO
     *
     * @return the value of TRS_EXPORT_REFINANCE_DETAILS.CENTRAL_BANK_APPROV_REF_NO
     */
    public String getCENTRAL_BANK_APPROV_REF_NO() {
        return CENTRAL_BANK_APPROV_REF_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_EXPORT_REFINANCE_DETAILS.CENTRAL_BANK_APPROV_REF_NO
     *
     * @param CENTRAL_BANK_APPROV_REF_NO the value for TRS_EXPORT_REFINANCE_DETAILS.CENTRAL_BANK_APPROV_REF_NO
     */
    public void setCENTRAL_BANK_APPROV_REF_NO(String CENTRAL_BANK_APPROV_REF_NO) {
        this.CENTRAL_BANK_APPROV_REF_NO = CENTRAL_BANK_APPROV_REF_NO == null ? null : CENTRAL_BANK_APPROV_REF_NO.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_EXPORT_REFINANCE_DETAILS.CENTRAL_BANK_LOAN_ID
     *
     * @return the value of TRS_EXPORT_REFINANCE_DETAILS.CENTRAL_BANK_LOAN_ID
     */
    public String getCENTRAL_BANK_LOAN_ID() {
        return CENTRAL_BANK_LOAN_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_EXPORT_REFINANCE_DETAILS.CENTRAL_BANK_LOAN_ID
     *
     * @param CENTRAL_BANK_LOAN_ID the value for TRS_EXPORT_REFINANCE_DETAILS.CENTRAL_BANK_LOAN_ID
     */
    public void setCENTRAL_BANK_LOAN_ID(String CENTRAL_BANK_LOAN_ID) {
        this.CENTRAL_BANK_LOAN_ID = CENTRAL_BANK_LOAN_ID == null ? null : CENTRAL_BANK_LOAN_ID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_EXPORT_REFINANCE_DETAILS.BANK_MARKUP_RATE
     *
     * @return the value of TRS_EXPORT_REFINANCE_DETAILS.BANK_MARKUP_RATE
     */
    public BigDecimal getBANK_MARKUP_RATE() {
        return BANK_MARKUP_RATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_EXPORT_REFINANCE_DETAILS.BANK_MARKUP_RATE
     *
     * @param BANK_MARKUP_RATE the value for TRS_EXPORT_REFINANCE_DETAILS.BANK_MARKUP_RATE
     */
    public void setBANK_MARKUP_RATE(BigDecimal BANK_MARKUP_RATE) {
        this.BANK_MARKUP_RATE = BANK_MARKUP_RATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_EXPORT_REFINANCE_DETAILS.CENTRAL_BANK_MARKUP_RATE
     *
     * @return the value of TRS_EXPORT_REFINANCE_DETAILS.CENTRAL_BANK_MARKUP_RATE
     */
    public BigDecimal getCENTRAL_BANK_MARKUP_RATE() {
        return CENTRAL_BANK_MARKUP_RATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_EXPORT_REFINANCE_DETAILS.CENTRAL_BANK_MARKUP_RATE
     *
     * @param CENTRAL_BANK_MARKUP_RATE the value for TRS_EXPORT_REFINANCE_DETAILS.CENTRAL_BANK_MARKUP_RATE
     */
    public void setCENTRAL_BANK_MARKUP_RATE(BigDecimal CENTRAL_BANK_MARKUP_RATE) {
        this.CENTRAL_BANK_MARKUP_RATE = CENTRAL_BANK_MARKUP_RATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_EXPORT_REFINANCE_DETAILS.CREATED_BY
     *
     * @return the value of TRS_EXPORT_REFINANCE_DETAILS.CREATED_BY
     */
    public String getCREATED_BY() {
        return CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_EXPORT_REFINANCE_DETAILS.CREATED_BY
     *
     * @param CREATED_BY the value for TRS_EXPORT_REFINANCE_DETAILS.CREATED_BY
     */
    public void setCREATED_BY(String CREATED_BY) {
        this.CREATED_BY = CREATED_BY == null ? null : CREATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_EXPORT_REFINANCE_DETAILS.CREATED_DATE
     *
     * @return the value of TRS_EXPORT_REFINANCE_DETAILS.CREATED_DATE
     */
    public Date getCREATED_DATE() {
        return CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_EXPORT_REFINANCE_DETAILS.CREATED_DATE
     *
     * @param CREATED_DATE the value for TRS_EXPORT_REFINANCE_DETAILS.CREATED_DATE
     */
    public void setCREATED_DATE(Date CREATED_DATE) {
        this.CREATED_DATE = CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_EXPORT_REFINANCE_DETAILS.MODIFIED_BY
     *
     * @return the value of TRS_EXPORT_REFINANCE_DETAILS.MODIFIED_BY
     */
    public String getMODIFIED_BY() {
        return MODIFIED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_EXPORT_REFINANCE_DETAILS.MODIFIED_BY
     *
     * @param MODIFIED_BY the value for TRS_EXPORT_REFINANCE_DETAILS.MODIFIED_BY
     */
    public void setMODIFIED_BY(String MODIFIED_BY) {
        this.MODIFIED_BY = MODIFIED_BY == null ? null : MODIFIED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_EXPORT_REFINANCE_DETAILS.MODIFIED_DATE
     *
     * @return the value of TRS_EXPORT_REFINANCE_DETAILS.MODIFIED_DATE
     */
    public Date getMODIFIED_DATE() {
        return MODIFIED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_EXPORT_REFINANCE_DETAILS.MODIFIED_DATE
     *
     * @param MODIFIED_DATE the value for TRS_EXPORT_REFINANCE_DETAILS.MODIFIED_DATE
     */
    public void setMODIFIED_DATE(Date MODIFIED_DATE) {
        this.MODIFIED_DATE = MODIFIED_DATE;
    }
}