package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class TRS_FX_DESK_LIMIT_SUMVO extends TRS_FX_DESK_LIMIT_SUMVOKey {
    /**
     * This field corresponds to the database column TRS_FX_DESK_LIMIT_SUM.OPENING_BAL_OPEN_POSITION
     */
    private BigDecimal OPENING_BAL_OPEN_POSITION;

    /**
     * This field corresponds to the database column TRS_FX_DESK_LIMIT_SUM.OPEN_POSITION
     */
    private BigDecimal OPEN_POSITION;

    /**
     * This field corresponds to the database column TRS_FX_DESK_LIMIT_SUM.POSITION_IN_SECOND_CY
     */
    private BigDecimal POSITION_IN_SECOND_CY;

    /**
     * This field corresponds to the database column TRS_FX_DESK_LIMIT_SUM.OVERNIGHT_POSITION_USD
     */
    private BigDecimal OVERNIGHT_POSITION_USD;

    /**
     * This field corresponds to the database column TRS_FX_DESK_LIMIT_SUM.LONG_AMOUNT
     */
    private BigDecimal LONG_AMOUNT;

    /**
     * This field corresponds to the database column TRS_FX_DESK_LIMIT_SUM.SHORT_AMOUNT
     */
    private BigDecimal SHORT_AMOUNT;

    /**
     * This field corresponds to the database column TRS_FX_DESK_LIMIT_SUM.AVG_RATE
     */
    private BigDecimal AVG_RATE;

    /**
     * This field corresponds to the database column TRS_FX_DESK_LIMIT_SUM.EX_RATE_USD
     */
    private BigDecimal EX_RATE_USD;

    /**
     * This field corresponds to the database column TRS_FX_DESK_LIMIT_SUM.EX_RATE_BASE_CY
     */
    private BigDecimal EX_RATE_BASE_CY;

    /**
     * This field corresponds to the database column TRS_FX_DESK_LIMIT_SUM.MTM_RATE
     */
    private BigDecimal MTM_RATE;

    /**
     * This field corresponds to the database column TRS_FX_DESK_LIMIT_SUM.AVG_RATE_LONG
     */
    private BigDecimal AVG_RATE_LONG;

    /**
     * This field corresponds to the database column TRS_FX_DESK_LIMIT_SUM.AVG_RATE_SHORT
     */
    private BigDecimal AVG_RATE_SHORT;

    /**
     * This field corresponds to the database column TRS_FX_DESK_LIMIT_SUM.DESK_LIMIT_BREACHED
     */
    private String DESK_LIMIT_BREACHED;

    /**
     * This field corresponds to the database column TRS_FX_DESK_LIMIT_SUM.STOP_LOSS_LIMIT_BREACHED
     */
    private String STOP_LOSS_LIMIT_BREACHED;

    /**
     * This field corresponds to the database column TRS_FX_DESK_LIMIT_SUM.REALIZED_GAIN
     */
    private BigDecimal REALIZED_GAIN;

    /**
     * This field corresponds to the database column TRS_FX_DESK_LIMIT_SUM.UNREALIZED_GAIN
     */
    private BigDecimal UNREALIZED_GAIN;

    /**
     * This field corresponds to the database column TRS_FX_DESK_LIMIT_SUM.OVERNIGHT_POSTN_LIMIT_AMT
     */
    private BigDecimal OVERNIGHT_POSTN_LIMIT_AMT;

    /**
     * This field corresponds to the database column TRS_FX_DESK_LIMIT_SUM.STOP_LOSS_LMT_DAILY_AMT
     */
    private BigDecimal STOP_LOSS_LMT_DAILY_AMT;

    /**
     * This field corresponds to the database column TRS_FX_DESK_LIMIT_SUM.STOP_LOSS_LMT_MONTHLY_AMT
     */
    private BigDecimal STOP_LOSS_LMT_MONTHLY_AMT;

    /**
     * This field corresponds to the database column TRS_FX_DESK_LIMIT_SUM.STOP_LOSS_LMT_YEARLY_AMT
     */
    private BigDecimal STOP_LOSS_LMT_YEARLY_AMT;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_FX_DESK_LIMIT_SUM.OPENING_BAL_OPEN_POSITION
     *
     * @return the value of TRS_FX_DESK_LIMIT_SUM.OPENING_BAL_OPEN_POSITION
     */
    public BigDecimal getOPENING_BAL_OPEN_POSITION() {
        return OPENING_BAL_OPEN_POSITION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_FX_DESK_LIMIT_SUM.OPENING_BAL_OPEN_POSITION
     *
     * @param OPENING_BAL_OPEN_POSITION the value for TRS_FX_DESK_LIMIT_SUM.OPENING_BAL_OPEN_POSITION
     */
    public void setOPENING_BAL_OPEN_POSITION(BigDecimal OPENING_BAL_OPEN_POSITION) {
        this.OPENING_BAL_OPEN_POSITION = OPENING_BAL_OPEN_POSITION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_FX_DESK_LIMIT_SUM.OPEN_POSITION
     *
     * @return the value of TRS_FX_DESK_LIMIT_SUM.OPEN_POSITION
     */
    public BigDecimal getOPEN_POSITION() {
        return OPEN_POSITION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_FX_DESK_LIMIT_SUM.OPEN_POSITION
     *
     * @param OPEN_POSITION the value for TRS_FX_DESK_LIMIT_SUM.OPEN_POSITION
     */
    public void setOPEN_POSITION(BigDecimal OPEN_POSITION) {
        this.OPEN_POSITION = OPEN_POSITION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_FX_DESK_LIMIT_SUM.POSITION_IN_SECOND_CY
     *
     * @return the value of TRS_FX_DESK_LIMIT_SUM.POSITION_IN_SECOND_CY
     */
    public BigDecimal getPOSITION_IN_SECOND_CY() {
        return POSITION_IN_SECOND_CY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_FX_DESK_LIMIT_SUM.POSITION_IN_SECOND_CY
     *
     * @param POSITION_IN_SECOND_CY the value for TRS_FX_DESK_LIMIT_SUM.POSITION_IN_SECOND_CY
     */
    public void setPOSITION_IN_SECOND_CY(BigDecimal POSITION_IN_SECOND_CY) {
        this.POSITION_IN_SECOND_CY = POSITION_IN_SECOND_CY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_FX_DESK_LIMIT_SUM.OVERNIGHT_POSITION_USD
     *
     * @return the value of TRS_FX_DESK_LIMIT_SUM.OVERNIGHT_POSITION_USD
     */
    public BigDecimal getOVERNIGHT_POSITION_USD() {
        return OVERNIGHT_POSITION_USD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_FX_DESK_LIMIT_SUM.OVERNIGHT_POSITION_USD
     *
     * @param OVERNIGHT_POSITION_USD the value for TRS_FX_DESK_LIMIT_SUM.OVERNIGHT_POSITION_USD
     */
    public void setOVERNIGHT_POSITION_USD(BigDecimal OVERNIGHT_POSITION_USD) {
        this.OVERNIGHT_POSITION_USD = OVERNIGHT_POSITION_USD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_FX_DESK_LIMIT_SUM.LONG_AMOUNT
     *
     * @return the value of TRS_FX_DESK_LIMIT_SUM.LONG_AMOUNT
     */
    public BigDecimal getLONG_AMOUNT() {
        return LONG_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_FX_DESK_LIMIT_SUM.LONG_AMOUNT
     *
     * @param LONG_AMOUNT the value for TRS_FX_DESK_LIMIT_SUM.LONG_AMOUNT
     */
    public void setLONG_AMOUNT(BigDecimal LONG_AMOUNT) {
        this.LONG_AMOUNT = LONG_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_FX_DESK_LIMIT_SUM.SHORT_AMOUNT
     *
     * @return the value of TRS_FX_DESK_LIMIT_SUM.SHORT_AMOUNT
     */
    public BigDecimal getSHORT_AMOUNT() {
        return SHORT_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_FX_DESK_LIMIT_SUM.SHORT_AMOUNT
     *
     * @param SHORT_AMOUNT the value for TRS_FX_DESK_LIMIT_SUM.SHORT_AMOUNT
     */
    public void setSHORT_AMOUNT(BigDecimal SHORT_AMOUNT) {
        this.SHORT_AMOUNT = SHORT_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_FX_DESK_LIMIT_SUM.AVG_RATE
     *
     * @return the value of TRS_FX_DESK_LIMIT_SUM.AVG_RATE
     */
    public BigDecimal getAVG_RATE() {
        return AVG_RATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_FX_DESK_LIMIT_SUM.AVG_RATE
     *
     * @param AVG_RATE the value for TRS_FX_DESK_LIMIT_SUM.AVG_RATE
     */
    public void setAVG_RATE(BigDecimal AVG_RATE) {
        this.AVG_RATE = AVG_RATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_FX_DESK_LIMIT_SUM.EX_RATE_USD
     *
     * @return the value of TRS_FX_DESK_LIMIT_SUM.EX_RATE_USD
     */
    public BigDecimal getEX_RATE_USD() {
        return EX_RATE_USD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_FX_DESK_LIMIT_SUM.EX_RATE_USD
     *
     * @param EX_RATE_USD the value for TRS_FX_DESK_LIMIT_SUM.EX_RATE_USD
     */
    public void setEX_RATE_USD(BigDecimal EX_RATE_USD) {
        this.EX_RATE_USD = EX_RATE_USD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_FX_DESK_LIMIT_SUM.EX_RATE_BASE_CY
     *
     * @return the value of TRS_FX_DESK_LIMIT_SUM.EX_RATE_BASE_CY
     */
    public BigDecimal getEX_RATE_BASE_CY() {
        return EX_RATE_BASE_CY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_FX_DESK_LIMIT_SUM.EX_RATE_BASE_CY
     *
     * @param EX_RATE_BASE_CY the value for TRS_FX_DESK_LIMIT_SUM.EX_RATE_BASE_CY
     */
    public void setEX_RATE_BASE_CY(BigDecimal EX_RATE_BASE_CY) {
        this.EX_RATE_BASE_CY = EX_RATE_BASE_CY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_FX_DESK_LIMIT_SUM.MTM_RATE
     *
     * @return the value of TRS_FX_DESK_LIMIT_SUM.MTM_RATE
     */
    public BigDecimal getMTM_RATE() {
        return MTM_RATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_FX_DESK_LIMIT_SUM.MTM_RATE
     *
     * @param MTM_RATE the value for TRS_FX_DESK_LIMIT_SUM.MTM_RATE
     */
    public void setMTM_RATE(BigDecimal MTM_RATE) {
        this.MTM_RATE = MTM_RATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_FX_DESK_LIMIT_SUM.AVG_RATE_LONG
     *
     * @return the value of TRS_FX_DESK_LIMIT_SUM.AVG_RATE_LONG
     */
    public BigDecimal getAVG_RATE_LONG() {
        return AVG_RATE_LONG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_FX_DESK_LIMIT_SUM.AVG_RATE_LONG
     *
     * @param AVG_RATE_LONG the value for TRS_FX_DESK_LIMIT_SUM.AVG_RATE_LONG
     */
    public void setAVG_RATE_LONG(BigDecimal AVG_RATE_LONG) {
        this.AVG_RATE_LONG = AVG_RATE_LONG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_FX_DESK_LIMIT_SUM.AVG_RATE_SHORT
     *
     * @return the value of TRS_FX_DESK_LIMIT_SUM.AVG_RATE_SHORT
     */
    public BigDecimal getAVG_RATE_SHORT() {
        return AVG_RATE_SHORT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_FX_DESK_LIMIT_SUM.AVG_RATE_SHORT
     *
     * @param AVG_RATE_SHORT the value for TRS_FX_DESK_LIMIT_SUM.AVG_RATE_SHORT
     */
    public void setAVG_RATE_SHORT(BigDecimal AVG_RATE_SHORT) {
        this.AVG_RATE_SHORT = AVG_RATE_SHORT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_FX_DESK_LIMIT_SUM.DESK_LIMIT_BREACHED
     *
     * @return the value of TRS_FX_DESK_LIMIT_SUM.DESK_LIMIT_BREACHED
     */
    public String getDESK_LIMIT_BREACHED() {
        return DESK_LIMIT_BREACHED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_FX_DESK_LIMIT_SUM.DESK_LIMIT_BREACHED
     *
     * @param DESK_LIMIT_BREACHED the value for TRS_FX_DESK_LIMIT_SUM.DESK_LIMIT_BREACHED
     */
    public void setDESK_LIMIT_BREACHED(String DESK_LIMIT_BREACHED) {
        this.DESK_LIMIT_BREACHED = DESK_LIMIT_BREACHED == null ? null : DESK_LIMIT_BREACHED.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_FX_DESK_LIMIT_SUM.STOP_LOSS_LIMIT_BREACHED
     *
     * @return the value of TRS_FX_DESK_LIMIT_SUM.STOP_LOSS_LIMIT_BREACHED
     */
    public String getSTOP_LOSS_LIMIT_BREACHED() {
        return STOP_LOSS_LIMIT_BREACHED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_FX_DESK_LIMIT_SUM.STOP_LOSS_LIMIT_BREACHED
     *
     * @param STOP_LOSS_LIMIT_BREACHED the value for TRS_FX_DESK_LIMIT_SUM.STOP_LOSS_LIMIT_BREACHED
     */
    public void setSTOP_LOSS_LIMIT_BREACHED(String STOP_LOSS_LIMIT_BREACHED) {
        this.STOP_LOSS_LIMIT_BREACHED = STOP_LOSS_LIMIT_BREACHED == null ? null : STOP_LOSS_LIMIT_BREACHED.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_FX_DESK_LIMIT_SUM.REALIZED_GAIN
     *
     * @return the value of TRS_FX_DESK_LIMIT_SUM.REALIZED_GAIN
     */
    public BigDecimal getREALIZED_GAIN() {
        return REALIZED_GAIN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_FX_DESK_LIMIT_SUM.REALIZED_GAIN
     *
     * @param REALIZED_GAIN the value for TRS_FX_DESK_LIMIT_SUM.REALIZED_GAIN
     */
    public void setREALIZED_GAIN(BigDecimal REALIZED_GAIN) {
        this.REALIZED_GAIN = REALIZED_GAIN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_FX_DESK_LIMIT_SUM.UNREALIZED_GAIN
     *
     * @return the value of TRS_FX_DESK_LIMIT_SUM.UNREALIZED_GAIN
     */
    public BigDecimal getUNREALIZED_GAIN() {
        return UNREALIZED_GAIN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_FX_DESK_LIMIT_SUM.UNREALIZED_GAIN
     *
     * @param UNREALIZED_GAIN the value for TRS_FX_DESK_LIMIT_SUM.UNREALIZED_GAIN
     */
    public void setUNREALIZED_GAIN(BigDecimal UNREALIZED_GAIN) {
        this.UNREALIZED_GAIN = UNREALIZED_GAIN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_FX_DESK_LIMIT_SUM.OVERNIGHT_POSTN_LIMIT_AMT
     *
     * @return the value of TRS_FX_DESK_LIMIT_SUM.OVERNIGHT_POSTN_LIMIT_AMT
     */
    public BigDecimal getOVERNIGHT_POSTN_LIMIT_AMT() {
        return OVERNIGHT_POSTN_LIMIT_AMT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_FX_DESK_LIMIT_SUM.OVERNIGHT_POSTN_LIMIT_AMT
     *
     * @param OVERNIGHT_POSTN_LIMIT_AMT the value for TRS_FX_DESK_LIMIT_SUM.OVERNIGHT_POSTN_LIMIT_AMT
     */
    public void setOVERNIGHT_POSTN_LIMIT_AMT(BigDecimal OVERNIGHT_POSTN_LIMIT_AMT) {
        this.OVERNIGHT_POSTN_LIMIT_AMT = OVERNIGHT_POSTN_LIMIT_AMT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_FX_DESK_LIMIT_SUM.STOP_LOSS_LMT_DAILY_AMT
     *
     * @return the value of TRS_FX_DESK_LIMIT_SUM.STOP_LOSS_LMT_DAILY_AMT
     */
    public BigDecimal getSTOP_LOSS_LMT_DAILY_AMT() {
        return STOP_LOSS_LMT_DAILY_AMT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_FX_DESK_LIMIT_SUM.STOP_LOSS_LMT_DAILY_AMT
     *
     * @param STOP_LOSS_LMT_DAILY_AMT the value for TRS_FX_DESK_LIMIT_SUM.STOP_LOSS_LMT_DAILY_AMT
     */
    public void setSTOP_LOSS_LMT_DAILY_AMT(BigDecimal STOP_LOSS_LMT_DAILY_AMT) {
        this.STOP_LOSS_LMT_DAILY_AMT = STOP_LOSS_LMT_DAILY_AMT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_FX_DESK_LIMIT_SUM.STOP_LOSS_LMT_MONTHLY_AMT
     *
     * @return the value of TRS_FX_DESK_LIMIT_SUM.STOP_LOSS_LMT_MONTHLY_AMT
     */
    public BigDecimal getSTOP_LOSS_LMT_MONTHLY_AMT() {
        return STOP_LOSS_LMT_MONTHLY_AMT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_FX_DESK_LIMIT_SUM.STOP_LOSS_LMT_MONTHLY_AMT
     *
     * @param STOP_LOSS_LMT_MONTHLY_AMT the value for TRS_FX_DESK_LIMIT_SUM.STOP_LOSS_LMT_MONTHLY_AMT
     */
    public void setSTOP_LOSS_LMT_MONTHLY_AMT(BigDecimal STOP_LOSS_LMT_MONTHLY_AMT) {
        this.STOP_LOSS_LMT_MONTHLY_AMT = STOP_LOSS_LMT_MONTHLY_AMT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_FX_DESK_LIMIT_SUM.STOP_LOSS_LMT_YEARLY_AMT
     *
     * @return the value of TRS_FX_DESK_LIMIT_SUM.STOP_LOSS_LMT_YEARLY_AMT
     */
    public BigDecimal getSTOP_LOSS_LMT_YEARLY_AMT() {
        return STOP_LOSS_LMT_YEARLY_AMT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_FX_DESK_LIMIT_SUM.STOP_LOSS_LMT_YEARLY_AMT
     *
     * @param STOP_LOSS_LMT_YEARLY_AMT the value for TRS_FX_DESK_LIMIT_SUM.STOP_LOSS_LMT_YEARLY_AMT
     */
    public void setSTOP_LOSS_LMT_YEARLY_AMT(BigDecimal STOP_LOSS_LMT_YEARLY_AMT) {
        this.STOP_LOSS_LMT_YEARLY_AMT = STOP_LOSS_LMT_YEARLY_AMT;
    }
}