package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class TRS_DEFF_APPORT_TRX_DETVO extends TRS_DEFF_APPORT_TRX_DETVOKey {
    /**
     * This field corresponds to the database column TRS_DEFF_APPORT_TRX_DET.AMOUNT
     */
    private BigDecimal AMOUNT;

    /**
     * This field corresponds to the database column TRS_DEFF_APPORT_TRX_DET.LINE_NO
     */
    private BigDecimal LINE_NO;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_DEFF_APPORT_TRX_DET.AMOUNT
     *
     * @return the value of TRS_DEFF_APPORT_TRX_DET.AMOUNT
     */
    public BigDecimal getAMOUNT() {
        return AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_DEFF_APPORT_TRX_DET.AMOUNT
     *
     * @param AMOUNT the value for TRS_DEFF_APPORT_TRX_DET.AMOUNT
     */
    public void setAMOUNT(BigDecimal AMOUNT) {
        this.AMOUNT = AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_DEFF_APPORT_TRX_DET.LINE_NO
     *
     * @return the value of TRS_DEFF_APPORT_TRX_DET.LINE_NO
     */
    public BigDecimal getLINE_NO() {
        return LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_DEFF_APPORT_TRX_DET.LINE_NO
     *
     * @param LINE_NO the value for TRS_DEFF_APPORT_TRX_DET.LINE_NO
     */
    public void setLINE_NO(BigDecimal LINE_NO) {
        this.LINE_NO = LINE_NO;
    }
}