package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class TRS_VEND_INCENTIVE_CLASSVO extends TRS_VEND_INCENTIVE_CLASSVOKey {
    /**
     * This field corresponds to the database column TRS_VEND_INCENTIVE_CLASS.CLASS
     */
    private BigDecimal CLASS;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_VEND_INCENTIVE_CLASS.CLASS
     *
     * @return the value of TRS_VEND_INCENTIVE_CLASS.CLASS
     */
    public BigDecimal getCLASS() {
        return CLASS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_VEND_INCENTIVE_CLASS.CLASS
     *
     * @param CLASS the value for TRS_VEND_INCENTIVE_CLASS.CLASS
     */
    public void setCLASS(BigDecimal CLASS) {
        this.CLASS = CLASS;
    }
}