package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class TRS_DOCUMENT_MANAGEMENTVOKey extends BaseVO {
    /**
     * This field corresponds to the database column TRS_DOCUMENT_MANAGEMENT.BRANCH_CODE
     */
    private BigDecimal BRANCH_CODE;

    /**
     * This field corresponds to the database column TRS_DOCUMENT_MANAGEMENT.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column TRS_DOCUMENT_MANAGEMENT.DOCUMENT_CODE
     */
    private BigDecimal DOCUMENT_CODE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_DOCUMENT_MANAGEMENT.BRANCH_CODE
     *
     * @return the value of TRS_DOCUMENT_MANAGEMENT.BRANCH_CODE
     */
    public BigDecimal getBRANCH_CODE() {
        return BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_DOCUMENT_MANAGEMENT.BRANCH_CODE
     *
     * @param BRANCH_CODE the value for TRS_DOCUMENT_MANAGEMENT.BRANCH_CODE
     */
    public void setBRANCH_CODE(BigDecimal BRANCH_CODE) {
        this.BRANCH_CODE = BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_DOCUMENT_MANAGEMENT.COMP_CODE
     *
     * @return the value of TRS_DOCUMENT_MANAGEMENT.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_DOCUMENT_MANAGEMENT.COMP_CODE
     *
     * @param COMP_CODE the value for TRS_DOCUMENT_MANAGEMENT.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_DOCUMENT_MANAGEMENT.DOCUMENT_CODE
     *
     * @return the value of TRS_DOCUMENT_MANAGEMENT.DOCUMENT_CODE
     */
    public BigDecimal getDOCUMENT_CODE() {
        return DOCUMENT_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_DOCUMENT_MANAGEMENT.DOCUMENT_CODE
     *
     * @param DOCUMENT_CODE the value for TRS_DOCUMENT_MANAGEMENT.DOCUMENT_CODE
     */
    public void setDOCUMENT_CODE(BigDecimal DOCUMENT_CODE) {
        this.DOCUMENT_CODE = DOCUMENT_CODE;
    }
}