package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class TRS_FX_LINKED_DEALVO extends TRS_FX_LINKED_DEALVOKey {
    /**
     * This field corresponds to the database column TRS_FX_LINKED_DEAL.FX_TYPE
     */
    private String FX_TYPE;

    /**
     * This field corresponds to the database column TRS_FX_LINKED_DEAL.FX_DEAL_BRANCH
     */
    private BigDecimal FX_DEAL_BRANCH;

    /**
     * This field corresponds to the database column TRS_FX_LINKED_DEAL.FX_DEAL_NO
     */
    private BigDecimal FX_DEAL_NO;

    /**
     * This field corresponds to the database column TRS_FX_LINKED_DEAL.RATE
     */
    private BigDecimal RATE;

    /**
     * This field corresponds to the database column TRS_FX_LINKED_DEAL.DEALER_ID
     */
    private String DEALER_ID;

    /**
     * This field corresponds to the database column TRS_FX_LINKED_DEAL.UTILIZED_AMOUNT
     */
    private BigDecimal UTILIZED_AMOUNT;

    /**
     * This field corresponds to the database column TRS_FX_LINKED_DEAL.UTILIZED_AMOUNT_CV
     */
    private BigDecimal UTILIZED_AMOUNT_CV;

    /**
     * This field corresponds to the database column TRS_FX_LINKED_DEAL.CIF_NO
     */
    private BigDecimal CIF_NO;

    /**
     * This field corresponds to the database column TRS_FX_LINKED_DEAL.CROSS_MULTIDIV
     */
    private String CROSS_MULTIDIV;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_FX_LINKED_DEAL.FX_TYPE
     *
     * @return the value of TRS_FX_LINKED_DEAL.FX_TYPE
     */
    public String getFX_TYPE() {
        return FX_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_FX_LINKED_DEAL.FX_TYPE
     *
     * @param FX_TYPE the value for TRS_FX_LINKED_DEAL.FX_TYPE
     */
    public void setFX_TYPE(String FX_TYPE) {
        this.FX_TYPE = FX_TYPE == null ? null : FX_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_FX_LINKED_DEAL.FX_DEAL_BRANCH
     *
     * @return the value of TRS_FX_LINKED_DEAL.FX_DEAL_BRANCH
     */
    public BigDecimal getFX_DEAL_BRANCH() {
        return FX_DEAL_BRANCH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_FX_LINKED_DEAL.FX_DEAL_BRANCH
     *
     * @param FX_DEAL_BRANCH the value for TRS_FX_LINKED_DEAL.FX_DEAL_BRANCH
     */
    public void setFX_DEAL_BRANCH(BigDecimal FX_DEAL_BRANCH) {
        this.FX_DEAL_BRANCH = FX_DEAL_BRANCH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_FX_LINKED_DEAL.FX_DEAL_NO
     *
     * @return the value of TRS_FX_LINKED_DEAL.FX_DEAL_NO
     */
    public BigDecimal getFX_DEAL_NO() {
        return FX_DEAL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_FX_LINKED_DEAL.FX_DEAL_NO
     *
     * @param FX_DEAL_NO the value for TRS_FX_LINKED_DEAL.FX_DEAL_NO
     */
    public void setFX_DEAL_NO(BigDecimal FX_DEAL_NO) {
        this.FX_DEAL_NO = FX_DEAL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_FX_LINKED_DEAL.RATE
     *
     * @return the value of TRS_FX_LINKED_DEAL.RATE
     */
    public BigDecimal getRATE() {
        return RATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_FX_LINKED_DEAL.RATE
     *
     * @param RATE the value for TRS_FX_LINKED_DEAL.RATE
     */
    public void setRATE(BigDecimal RATE) {
        this.RATE = RATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_FX_LINKED_DEAL.DEALER_ID
     *
     * @return the value of TRS_FX_LINKED_DEAL.DEALER_ID
     */
    public String getDEALER_ID() {
        return DEALER_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_FX_LINKED_DEAL.DEALER_ID
     *
     * @param DEALER_ID the value for TRS_FX_LINKED_DEAL.DEALER_ID
     */
    public void setDEALER_ID(String DEALER_ID) {
        this.DEALER_ID = DEALER_ID == null ? null : DEALER_ID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_FX_LINKED_DEAL.UTILIZED_AMOUNT
     *
     * @return the value of TRS_FX_LINKED_DEAL.UTILIZED_AMOUNT
     */
    public BigDecimal getUTILIZED_AMOUNT() {
        return UTILIZED_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_FX_LINKED_DEAL.UTILIZED_AMOUNT
     *
     * @param UTILIZED_AMOUNT the value for TRS_FX_LINKED_DEAL.UTILIZED_AMOUNT
     */
    public void setUTILIZED_AMOUNT(BigDecimal UTILIZED_AMOUNT) {
        this.UTILIZED_AMOUNT = UTILIZED_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_FX_LINKED_DEAL.UTILIZED_AMOUNT_CV
     *
     * @return the value of TRS_FX_LINKED_DEAL.UTILIZED_AMOUNT_CV
     */
    public BigDecimal getUTILIZED_AMOUNT_CV() {
        return UTILIZED_AMOUNT_CV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_FX_LINKED_DEAL.UTILIZED_AMOUNT_CV
     *
     * @param UTILIZED_AMOUNT_CV the value for TRS_FX_LINKED_DEAL.UTILIZED_AMOUNT_CV
     */
    public void setUTILIZED_AMOUNT_CV(BigDecimal UTILIZED_AMOUNT_CV) {
        this.UTILIZED_AMOUNT_CV = UTILIZED_AMOUNT_CV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_FX_LINKED_DEAL.CIF_NO
     *
     * @return the value of TRS_FX_LINKED_DEAL.CIF_NO
     */
    public BigDecimal getCIF_NO() {
        return CIF_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_FX_LINKED_DEAL.CIF_NO
     *
     * @param CIF_NO the value for TRS_FX_LINKED_DEAL.CIF_NO
     */
    public void setCIF_NO(BigDecimal CIF_NO) {
        this.CIF_NO = CIF_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_FX_LINKED_DEAL.CROSS_MULTIDIV
     *
     * @return the value of TRS_FX_LINKED_DEAL.CROSS_MULTIDIV
     */
    public String getCROSS_MULTIDIV() {
        return CROSS_MULTIDIV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_FX_LINKED_DEAL.CROSS_MULTIDIV
     *
     * @param CROSS_MULTIDIV the value for TRS_FX_LINKED_DEAL.CROSS_MULTIDIV
     */
    public void setCROSS_MULTIDIV(String CROSS_MULTIDIV) {
        this.CROSS_MULTIDIV = CROSS_MULTIDIV == null ? null : CROSS_MULTIDIV.trim();
    }
}