package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class TRS_PROVISION_CIF_STATUSVO extends TRS_PROVISION_CIF_STATUSVOKey {
    /**
     * This field corresponds to the database column TRS_PROVISION_CIF_STATUS.CATEGORY_CODE
     */
    private BigDecimal CATEGORY_CODE;

    /**
     * This field corresponds to the database column TRS_PROVISION_CIF_STATUS.CIF_SUB_CLASS
     */
    private String CIF_SUB_CLASS;

    /**
     * This field corresponds to the database column TRS_PROVISION_CIF_STATUS.CIF_SUB_CLASS_RESET_FLAG
     */
    private String CIF_SUB_CLASS_RESET_FLAG;

    /**
     * This field corresponds to the database column TRS_PROVISION_CIF_STATUS.CATEGORY_CODE_2
     */
    private BigDecimal CATEGORY_CODE_2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROVISION_CIF_STATUS.CATEGORY_CODE
     *
     * @return the value of TRS_PROVISION_CIF_STATUS.CATEGORY_CODE
     */
    public BigDecimal getCATEGORY_CODE() {
        return CATEGORY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROVISION_CIF_STATUS.CATEGORY_CODE
     *
     * @param CATEGORY_CODE the value for TRS_PROVISION_CIF_STATUS.CATEGORY_CODE
     */
    public void setCATEGORY_CODE(BigDecimal CATEGORY_CODE) {
        this.CATEGORY_CODE = CATEGORY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROVISION_CIF_STATUS.CIF_SUB_CLASS
     *
     * @return the value of TRS_PROVISION_CIF_STATUS.CIF_SUB_CLASS
     */
    public String getCIF_SUB_CLASS() {
        return CIF_SUB_CLASS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROVISION_CIF_STATUS.CIF_SUB_CLASS
     *
     * @param CIF_SUB_CLASS the value for TRS_PROVISION_CIF_STATUS.CIF_SUB_CLASS
     */
    public void setCIF_SUB_CLASS(String CIF_SUB_CLASS) {
        this.CIF_SUB_CLASS = CIF_SUB_CLASS == null ? null : CIF_SUB_CLASS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROVISION_CIF_STATUS.CIF_SUB_CLASS_RESET_FLAG
     *
     * @return the value of TRS_PROVISION_CIF_STATUS.CIF_SUB_CLASS_RESET_FLAG
     */
    public String getCIF_SUB_CLASS_RESET_FLAG() {
        return CIF_SUB_CLASS_RESET_FLAG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROVISION_CIF_STATUS.CIF_SUB_CLASS_RESET_FLAG
     *
     * @param CIF_SUB_CLASS_RESET_FLAG the value for TRS_PROVISION_CIF_STATUS.CIF_SUB_CLASS_RESET_FLAG
     */
    public void setCIF_SUB_CLASS_RESET_FLAG(String CIF_SUB_CLASS_RESET_FLAG) {
        this.CIF_SUB_CLASS_RESET_FLAG = CIF_SUB_CLASS_RESET_FLAG == null ? null : CIF_SUB_CLASS_RESET_FLAG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROVISION_CIF_STATUS.CATEGORY_CODE_2
     *
     * @return the value of TRS_PROVISION_CIF_STATUS.CATEGORY_CODE_2
     */
    public BigDecimal getCATEGORY_CODE_2() {
        return CATEGORY_CODE_2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROVISION_CIF_STATUS.CATEGORY_CODE_2
     *
     * @param CATEGORY_CODE_2 the value for TRS_PROVISION_CIF_STATUS.CATEGORY_CODE_2
     */
    public void setCATEGORY_CODE_2(BigDecimal CATEGORY_CODE_2) {
        this.CATEGORY_CODE_2 = CATEGORY_CODE_2;
    }
}