package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class TRS_PROVISION_AMENDMENTSVO extends TRS_PROVISION_AMENDMENTSVOKey {
    /**
     * This field corresponds to the database column TRS_PROVISION_AMENDMENTS.TRX_DATE
     */
    private Date TRX_DATE;

    /**
     * This field corresponds to the database column TRS_PROVISION_AMENDMENTS.CIF_NO
     */
    private BigDecimal CIF_NO;

    /**
     * This field corresponds to the database column TRS_PROVISION_AMENDMENTS.STATUS
     */
    private String STATUS;

    /**
     * This field corresponds to the database column TRS_PROVISION_AMENDMENTS.CREATED_BY
     */
    private String CREATED_BY;

    /**
     * This field corresponds to the database column TRS_PROVISION_AMENDMENTS.DATE_CREATED
     */
    private Date DATE_CREATED;

    /**
     * This field corresponds to the database column TRS_PROVISION_AMENDMENTS.SERVER_DATE_CREATED
     */
    private Date SERVER_DATE_CREATED;

    /**
     * This field corresponds to the database column TRS_PROVISION_AMENDMENTS.MODIFIED_BY
     */
    private String MODIFIED_BY;

    /**
     * This field corresponds to the database column TRS_PROVISION_AMENDMENTS.DATE_MODIFIED
     */
    private Date DATE_MODIFIED;

    /**
     * This field corresponds to the database column TRS_PROVISION_AMENDMENTS.SERVER_DATE_MODIFIED
     */
    private Date SERVER_DATE_MODIFIED;

    /**
     * This field corresponds to the database column TRS_PROVISION_AMENDMENTS.DELETED_BY
     */
    private String DELETED_BY;

    /**
     * This field corresponds to the database column TRS_PROVISION_AMENDMENTS.DATE_DELETED
     */
    private Date DATE_DELETED;

    /**
     * This field corresponds to the database column TRS_PROVISION_AMENDMENTS.SERVER_DATE_DELETED
     */
    private Date SERVER_DATE_DELETED;

    /**
     * This field corresponds to the database column TRS_PROVISION_AMENDMENTS.APPROVED_BY
     */
    private String APPROVED_BY;

    /**
     * This field corresponds to the database column TRS_PROVISION_AMENDMENTS.DATE_APPROVED
     */
    private Date DATE_APPROVED;

    /**
     * This field corresponds to the database column TRS_PROVISION_AMENDMENTS.SERVER_DATE_APPROVED
     */
    private Date SERVER_DATE_APPROVED;

    /**
     * This field corresponds to the database column TRS_PROVISION_AMENDMENTS.REVERSED_BY
     */
    private String REVERSED_BY;

    /**
     * This field corresponds to the database column TRS_PROVISION_AMENDMENTS.DATE_REVERSED
     */
    private Date DATE_REVERSED;

    /**
     * This field corresponds to the database column TRS_PROVISION_AMENDMENTS.SERVER_DATE_REVERSED
     */
    private Date SERVER_DATE_REVERSED;

    /**
     * This field corresponds to the database column TRS_PROVISION_AMENDMENTS.REVERSAL_STATUS
     */
    private String REVERSAL_STATUS;

    /**
     * This field corresponds to the database column TRS_PROVISION_AMENDMENTS.REVERSAL_CREATED_BY
     */
    private String REVERSAL_CREATED_BY;

    /**
     * This field corresponds to the database column TRS_PROVISION_AMENDMENTS.REVERSAL_CREATED_DATE
     */
    private Date REVERSAL_CREATED_DATE;

    /**
     * This field corresponds to the database column TRS_PROVISION_AMENDMENTS.SERVER_REVERSAL_CREATED_DATE
     */
    private Date SERVER_REVERSAL_CREATED_DATE;

    /**
     * This field corresponds to the database column TRS_PROVISION_AMENDMENTS.REVERSAL_DELETED_BY
     */
    private String REVERSAL_DELETED_BY;

    /**
     * This field corresponds to the database column TRS_PROVISION_AMENDMENTS.REVERSAL_DELETED_DATE
     */
    private Date REVERSAL_DELETED_DATE;

    /**
     * This field corresponds to the database column TRS_PROVISION_AMENDMENTS.SERVER_REVERSAL_DELETED_DATE
     */
    private Date SERVER_REVERSAL_DELETED_DATE;

    /**
     * This field corresponds to the database column
     * TRS_PROVISION_AMENDMENTS.DATE_UPDATED
     */
    private Date DATE_UPDATED;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROVISION_AMENDMENTS.TRX_DATE
     *
     * @return the value of TRS_PROVISION_AMENDMENTS.TRX_DATE
     */
    public Date getTRX_DATE() {
        return TRX_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROVISION_AMENDMENTS.TRX_DATE
     *
     * @param TRX_DATE the value for TRS_PROVISION_AMENDMENTS.TRX_DATE
     */
    public void setTRX_DATE(Date TRX_DATE) {
        this.TRX_DATE = TRX_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROVISION_AMENDMENTS.CIF_NO
     *
     * @return the value of TRS_PROVISION_AMENDMENTS.CIF_NO
     */
    public BigDecimal getCIF_NO() {
        return CIF_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROVISION_AMENDMENTS.CIF_NO
     *
     * @param CIF_NO the value for TRS_PROVISION_AMENDMENTS.CIF_NO
     */
    public void setCIF_NO(BigDecimal CIF_NO) {
        this.CIF_NO = CIF_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROVISION_AMENDMENTS.STATUS
     *
     * @return the value of TRS_PROVISION_AMENDMENTS.STATUS
     */
    public String getSTATUS() {
        return STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROVISION_AMENDMENTS.STATUS
     *
     * @param STATUS the value for TRS_PROVISION_AMENDMENTS.STATUS
     */
    public void setSTATUS(String STATUS) {
        this.STATUS = STATUS == null ? null : STATUS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROVISION_AMENDMENTS.CREATED_BY
     *
     * @return the value of TRS_PROVISION_AMENDMENTS.CREATED_BY
     */
    public String getCREATED_BY() {
        return CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROVISION_AMENDMENTS.CREATED_BY
     *
     * @param CREATED_BY the value for TRS_PROVISION_AMENDMENTS.CREATED_BY
     */
    public void setCREATED_BY(String CREATED_BY) {
        this.CREATED_BY = CREATED_BY == null ? null : CREATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROVISION_AMENDMENTS.DATE_CREATED
     *
     * @return the value of TRS_PROVISION_AMENDMENTS.DATE_CREATED
     */
    public Date getDATE_CREATED() {
        return DATE_CREATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROVISION_AMENDMENTS.DATE_CREATED
     *
     * @param DATE_CREATED the value for TRS_PROVISION_AMENDMENTS.DATE_CREATED
     */
    public void setDATE_CREATED(Date DATE_CREATED) {
        this.DATE_CREATED = DATE_CREATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROVISION_AMENDMENTS.SERVER_DATE_CREATED
     *
     * @return the value of TRS_PROVISION_AMENDMENTS.SERVER_DATE_CREATED
     */
    public Date getSERVER_DATE_CREATED() {
        return SERVER_DATE_CREATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROVISION_AMENDMENTS.SERVER_DATE_CREATED
     *
     * @param SERVER_DATE_CREATED the value for TRS_PROVISION_AMENDMENTS.SERVER_DATE_CREATED
     */
    public void setSERVER_DATE_CREATED(Date SERVER_DATE_CREATED) {
        this.SERVER_DATE_CREATED = SERVER_DATE_CREATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROVISION_AMENDMENTS.MODIFIED_BY
     *
     * @return the value of TRS_PROVISION_AMENDMENTS.MODIFIED_BY
     */
    public String getMODIFIED_BY() {
        return MODIFIED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROVISION_AMENDMENTS.MODIFIED_BY
     *
     * @param MODIFIED_BY the value for TRS_PROVISION_AMENDMENTS.MODIFIED_BY
     */
    public void setMODIFIED_BY(String MODIFIED_BY) {
        this.MODIFIED_BY = MODIFIED_BY == null ? null : MODIFIED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROVISION_AMENDMENTS.DATE_MODIFIED
     *
     * @return the value of TRS_PROVISION_AMENDMENTS.DATE_MODIFIED
     */
    public Date getDATE_MODIFIED() {
        return DATE_MODIFIED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROVISION_AMENDMENTS.DATE_MODIFIED
     *
     * @param DATE_MODIFIED the value for TRS_PROVISION_AMENDMENTS.DATE_MODIFIED
     */
    public void setDATE_MODIFIED(Date DATE_MODIFIED) {
        this.DATE_MODIFIED = DATE_MODIFIED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROVISION_AMENDMENTS.SERVER_DATE_MODIFIED
     *
     * @return the value of TRS_PROVISION_AMENDMENTS.SERVER_DATE_MODIFIED
     */
    public Date getSERVER_DATE_MODIFIED() {
        return SERVER_DATE_MODIFIED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROVISION_AMENDMENTS.SERVER_DATE_MODIFIED
     *
     * @param SERVER_DATE_MODIFIED the value for TRS_PROVISION_AMENDMENTS.SERVER_DATE_MODIFIED
     */
    public void setSERVER_DATE_MODIFIED(Date SERVER_DATE_MODIFIED) {
        this.SERVER_DATE_MODIFIED = SERVER_DATE_MODIFIED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROVISION_AMENDMENTS.DELETED_BY
     *
     * @return the value of TRS_PROVISION_AMENDMENTS.DELETED_BY
     */
    public String getDELETED_BY() {
        return DELETED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROVISION_AMENDMENTS.DELETED_BY
     *
     * @param DELETED_BY the value for TRS_PROVISION_AMENDMENTS.DELETED_BY
     */
    public void setDELETED_BY(String DELETED_BY) {
        this.DELETED_BY = DELETED_BY == null ? null : DELETED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROVISION_AMENDMENTS.DATE_DELETED
     *
     * @return the value of TRS_PROVISION_AMENDMENTS.DATE_DELETED
     */
    public Date getDATE_DELETED() {
        return DATE_DELETED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROVISION_AMENDMENTS.DATE_DELETED
     *
     * @param DATE_DELETED the value for TRS_PROVISION_AMENDMENTS.DATE_DELETED
     */
    public void setDATE_DELETED(Date DATE_DELETED) {
        this.DATE_DELETED = DATE_DELETED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROVISION_AMENDMENTS.SERVER_DATE_DELETED
     *
     * @return the value of TRS_PROVISION_AMENDMENTS.SERVER_DATE_DELETED
     */
    public Date getSERVER_DATE_DELETED() {
        return SERVER_DATE_DELETED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROVISION_AMENDMENTS.SERVER_DATE_DELETED
     *
     * @param SERVER_DATE_DELETED the value for TRS_PROVISION_AMENDMENTS.SERVER_DATE_DELETED
     */
    public void setSERVER_DATE_DELETED(Date SERVER_DATE_DELETED) {
        this.SERVER_DATE_DELETED = SERVER_DATE_DELETED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROVISION_AMENDMENTS.APPROVED_BY
     *
     * @return the value of TRS_PROVISION_AMENDMENTS.APPROVED_BY
     */
    public String getAPPROVED_BY() {
        return APPROVED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROVISION_AMENDMENTS.APPROVED_BY
     *
     * @param APPROVED_BY the value for TRS_PROVISION_AMENDMENTS.APPROVED_BY
     */
    public void setAPPROVED_BY(String APPROVED_BY) {
        this.APPROVED_BY = APPROVED_BY == null ? null : APPROVED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROVISION_AMENDMENTS.DATE_APPROVED
     *
     * @return the value of TRS_PROVISION_AMENDMENTS.DATE_APPROVED
     */
    public Date getDATE_APPROVED() {
        return DATE_APPROVED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROVISION_AMENDMENTS.DATE_APPROVED
     *
     * @param DATE_APPROVED the value for TRS_PROVISION_AMENDMENTS.DATE_APPROVED
     */
    public void setDATE_APPROVED(Date DATE_APPROVED) {
        this.DATE_APPROVED = DATE_APPROVED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROVISION_AMENDMENTS.SERVER_DATE_APPROVED
     *
     * @return the value of TRS_PROVISION_AMENDMENTS.SERVER_DATE_APPROVED
     */
    public Date getSERVER_DATE_APPROVED() {
        return SERVER_DATE_APPROVED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROVISION_AMENDMENTS.SERVER_DATE_APPROVED
     *
     * @param SERVER_DATE_APPROVED the value for TRS_PROVISION_AMENDMENTS.SERVER_DATE_APPROVED
     */
    public void setSERVER_DATE_APPROVED(Date SERVER_DATE_APPROVED) {
        this.SERVER_DATE_APPROVED = SERVER_DATE_APPROVED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROVISION_AMENDMENTS.REVERSED_BY
     *
     * @return the value of TRS_PROVISION_AMENDMENTS.REVERSED_BY
     */
    public String getREVERSED_BY() {
        return REVERSED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROVISION_AMENDMENTS.REVERSED_BY
     *
     * @param REVERSED_BY the value for TRS_PROVISION_AMENDMENTS.REVERSED_BY
     */
    public void setREVERSED_BY(String REVERSED_BY) {
        this.REVERSED_BY = REVERSED_BY == null ? null : REVERSED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROVISION_AMENDMENTS.DATE_REVERSED
     *
     * @return the value of TRS_PROVISION_AMENDMENTS.DATE_REVERSED
     */
    public Date getDATE_REVERSED() {
        return DATE_REVERSED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROVISION_AMENDMENTS.DATE_REVERSED
     *
     * @param DATE_REVERSED the value for TRS_PROVISION_AMENDMENTS.DATE_REVERSED
     */
    public void setDATE_REVERSED(Date DATE_REVERSED) {
        this.DATE_REVERSED = DATE_REVERSED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROVISION_AMENDMENTS.SERVER_DATE_REVERSED
     *
     * @return the value of TRS_PROVISION_AMENDMENTS.SERVER_DATE_REVERSED
     */
    public Date getSERVER_DATE_REVERSED() {
        return SERVER_DATE_REVERSED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROVISION_AMENDMENTS.SERVER_DATE_REVERSED
     *
     * @param SERVER_DATE_REVERSED the value for TRS_PROVISION_AMENDMENTS.SERVER_DATE_REVERSED
     */
    public void setSERVER_DATE_REVERSED(Date SERVER_DATE_REVERSED) {
        this.SERVER_DATE_REVERSED = SERVER_DATE_REVERSED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROVISION_AMENDMENTS.REVERSAL_STATUS
     *
     * @return the value of TRS_PROVISION_AMENDMENTS.REVERSAL_STATUS
     */
    public String getREVERSAL_STATUS() {
        return REVERSAL_STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROVISION_AMENDMENTS.REVERSAL_STATUS
     *
     * @param REVERSAL_STATUS the value for TRS_PROVISION_AMENDMENTS.REVERSAL_STATUS
     */
    public void setREVERSAL_STATUS(String REVERSAL_STATUS) {
        this.REVERSAL_STATUS = REVERSAL_STATUS == null ? null : REVERSAL_STATUS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROVISION_AMENDMENTS.REVERSAL_CREATED_BY
     *
     * @return the value of TRS_PROVISION_AMENDMENTS.REVERSAL_CREATED_BY
     */
    public String getREVERSAL_CREATED_BY() {
        return REVERSAL_CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROVISION_AMENDMENTS.REVERSAL_CREATED_BY
     *
     * @param REVERSAL_CREATED_BY the value for TRS_PROVISION_AMENDMENTS.REVERSAL_CREATED_BY
     */
    public void setREVERSAL_CREATED_BY(String REVERSAL_CREATED_BY) {
        this.REVERSAL_CREATED_BY = REVERSAL_CREATED_BY == null ? null : REVERSAL_CREATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROVISION_AMENDMENTS.REVERSAL_CREATED_DATE
     *
     * @return the value of TRS_PROVISION_AMENDMENTS.REVERSAL_CREATED_DATE
     */
    public Date getREVERSAL_CREATED_DATE() {
        return REVERSAL_CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROVISION_AMENDMENTS.REVERSAL_CREATED_DATE
     *
     * @param REVERSAL_CREATED_DATE the value for TRS_PROVISION_AMENDMENTS.REVERSAL_CREATED_DATE
     */
    public void setREVERSAL_CREATED_DATE(Date REVERSAL_CREATED_DATE) {
        this.REVERSAL_CREATED_DATE = REVERSAL_CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROVISION_AMENDMENTS.SERVER_REVERSAL_CREATED_DATE
     *
     * @return the value of TRS_PROVISION_AMENDMENTS.SERVER_REVERSAL_CREATED_DATE
     */
    public Date getSERVER_REVERSAL_CREATED_DATE() {
        return SERVER_REVERSAL_CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROVISION_AMENDMENTS.SERVER_REVERSAL_CREATED_DATE
     *
     * @param SERVER_REVERSAL_CREATED_DATE the value for TRS_PROVISION_AMENDMENTS.SERVER_REVERSAL_CREATED_DATE
     */
    public void setSERVER_REVERSAL_CREATED_DATE(Date SERVER_REVERSAL_CREATED_DATE) {
        this.SERVER_REVERSAL_CREATED_DATE = SERVER_REVERSAL_CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROVISION_AMENDMENTS.REVERSAL_DELETED_BY
     *
     * @return the value of TRS_PROVISION_AMENDMENTS.REVERSAL_DELETED_BY
     */
    public String getREVERSAL_DELETED_BY() {
        return REVERSAL_DELETED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROVISION_AMENDMENTS.REVERSAL_DELETED_BY
     *
     * @param REVERSAL_DELETED_BY the value for TRS_PROVISION_AMENDMENTS.REVERSAL_DELETED_BY
     */
    public void setREVERSAL_DELETED_BY(String REVERSAL_DELETED_BY) {
        this.REVERSAL_DELETED_BY = REVERSAL_DELETED_BY == null ? null : REVERSAL_DELETED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROVISION_AMENDMENTS.REVERSAL_DELETED_DATE
     *
     * @return the value of TRS_PROVISION_AMENDMENTS.REVERSAL_DELETED_DATE
     */
    public Date getREVERSAL_DELETED_DATE() {
        return REVERSAL_DELETED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROVISION_AMENDMENTS.REVERSAL_DELETED_DATE
     *
     * @param REVERSAL_DELETED_DATE the value for TRS_PROVISION_AMENDMENTS.REVERSAL_DELETED_DATE
     */
    public void setREVERSAL_DELETED_DATE(Date REVERSAL_DELETED_DATE) {
        this.REVERSAL_DELETED_DATE = REVERSAL_DELETED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROVISION_AMENDMENTS.SERVER_REVERSAL_DELETED_DATE
     *
     * @return the value of TRS_PROVISION_AMENDMENTS.SERVER_REVERSAL_DELETED_DATE
     */
    public Date getSERVER_REVERSAL_DELETED_DATE() {
        return SERVER_REVERSAL_DELETED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROVISION_AMENDMENTS.SERVER_REVERSAL_DELETED_DATE
     *
     * @param SERVER_REVERSAL_DELETED_DATE the value for TRS_PROVISION_AMENDMENTS.SERVER_REVERSAL_DELETED_DATE
     */
    public void setSERVER_REVERSAL_DELETED_DATE(Date SERVER_REVERSAL_DELETED_DATE) {
        this.SERVER_REVERSAL_DELETED_DATE = SERVER_REVERSAL_DELETED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column TRS_PROVISION_AMENDMENTS.DATE_UPDATED
     *
     * @return the value of TRS_PROVISION_AMENDMENTS.DATE_UPDATED
     */
    public Date getDATE_UPDATED()
    {
	return DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column TRS_PROVISION_AMENDMENTS.DATE_UPDATED
     *
     * @param DATE_UPDATED the value for TRS_PROVISION_AMENDMENTS.DATE_UPDATED
     */
    public void setDATE_UPDATED(Date DATE_UPDATED)
    {
	this.DATE_UPDATED = DATE_UPDATED;
    }
}