package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class TRS_PROV_PRODUCTS_PROCESSVOKey extends BaseVO {
    /**
     * This field corresponds to the database column TRS_PROV_PRODUCTS_PROCESS.ACC_BRANCH
     */
    private BigDecimal ACC_BRANCH;

    /**
     * This field corresponds to the database column TRS_PROV_PRODUCTS_PROCESS.AC_NO
     */
    private String AC_NO;

    /**
     * This field corresponds to the database column TRS_PROV_PRODUCTS_PROCESS.BRANCH_CODE
     */
    private BigDecimal BRANCH_CODE;

    /**
     * This field corresponds to the database column TRS_PROV_PRODUCTS_PROCESS.CIF_SUB_NO
     */
    private BigDecimal CIF_SUB_NO;

    /**
     * This field corresponds to the database column TRS_PROV_PRODUCTS_PROCESS.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column TRS_PROV_PRODUCTS_PROCESS.CURRENCY_CODE
     */
    private BigDecimal CURRENCY_CODE;

    /**
     * This field corresponds to the database column TRS_PROV_PRODUCTS_PROCESS.GL_CODE
     */
    private BigDecimal GL_CODE;

    /**
     * This field corresponds to the database column TRS_PROV_PRODUCTS_PROCESS.PROCESS_NBR
     */
    private BigDecimal PROCESS_NBR;

    /**
     * This field corresponds to the database column TRS_PROV_PRODUCTS_PROCESS.SL_NO
     */
    private BigDecimal SL_NO;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROV_PRODUCTS_PROCESS.ACC_BRANCH
     *
     * @return the value of TRS_PROV_PRODUCTS_PROCESS.ACC_BRANCH
     */
    public BigDecimal getACC_BRANCH() {
        return ACC_BRANCH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROV_PRODUCTS_PROCESS.ACC_BRANCH
     *
     * @param ACC_BRANCH the value for TRS_PROV_PRODUCTS_PROCESS.ACC_BRANCH
     */
    public void setACC_BRANCH(BigDecimal ACC_BRANCH) {
        this.ACC_BRANCH = ACC_BRANCH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROV_PRODUCTS_PROCESS.AC_NO
     *
     * @return the value of TRS_PROV_PRODUCTS_PROCESS.AC_NO
     */
    public String getAC_NO() {
        return AC_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROV_PRODUCTS_PROCESS.AC_NO
     *
     * @param AC_NO the value for TRS_PROV_PRODUCTS_PROCESS.AC_NO
     */
    public void setAC_NO(String AC_NO) {
        this.AC_NO = AC_NO == null ? null : AC_NO.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROV_PRODUCTS_PROCESS.BRANCH_CODE
     *
     * @return the value of TRS_PROV_PRODUCTS_PROCESS.BRANCH_CODE
     */
    public BigDecimal getBRANCH_CODE() {
        return BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROV_PRODUCTS_PROCESS.BRANCH_CODE
     *
     * @param BRANCH_CODE the value for TRS_PROV_PRODUCTS_PROCESS.BRANCH_CODE
     */
    public void setBRANCH_CODE(BigDecimal BRANCH_CODE) {
        this.BRANCH_CODE = BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROV_PRODUCTS_PROCESS.CIF_SUB_NO
     *
     * @return the value of TRS_PROV_PRODUCTS_PROCESS.CIF_SUB_NO
     */
    public BigDecimal getCIF_SUB_NO() {
        return CIF_SUB_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROV_PRODUCTS_PROCESS.CIF_SUB_NO
     *
     * @param CIF_SUB_NO the value for TRS_PROV_PRODUCTS_PROCESS.CIF_SUB_NO
     */
    public void setCIF_SUB_NO(BigDecimal CIF_SUB_NO) {
        this.CIF_SUB_NO = CIF_SUB_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROV_PRODUCTS_PROCESS.COMP_CODE
     *
     * @return the value of TRS_PROV_PRODUCTS_PROCESS.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROV_PRODUCTS_PROCESS.COMP_CODE
     *
     * @param COMP_CODE the value for TRS_PROV_PRODUCTS_PROCESS.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROV_PRODUCTS_PROCESS.CURRENCY_CODE
     *
     * @return the value of TRS_PROV_PRODUCTS_PROCESS.CURRENCY_CODE
     */
    public BigDecimal getCURRENCY_CODE() {
        return CURRENCY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROV_PRODUCTS_PROCESS.CURRENCY_CODE
     *
     * @param CURRENCY_CODE the value for TRS_PROV_PRODUCTS_PROCESS.CURRENCY_CODE
     */
    public void setCURRENCY_CODE(BigDecimal CURRENCY_CODE) {
        this.CURRENCY_CODE = CURRENCY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROV_PRODUCTS_PROCESS.GL_CODE
     *
     * @return the value of TRS_PROV_PRODUCTS_PROCESS.GL_CODE
     */
    public BigDecimal getGL_CODE() {
        return GL_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROV_PRODUCTS_PROCESS.GL_CODE
     *
     * @param GL_CODE the value for TRS_PROV_PRODUCTS_PROCESS.GL_CODE
     */
    public void setGL_CODE(BigDecimal GL_CODE) {
        this.GL_CODE = GL_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROV_PRODUCTS_PROCESS.PROCESS_NBR
     *
     * @return the value of TRS_PROV_PRODUCTS_PROCESS.PROCESS_NBR
     */
    public BigDecimal getPROCESS_NBR() {
        return PROCESS_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROV_PRODUCTS_PROCESS.PROCESS_NBR
     *
     * @param PROCESS_NBR the value for TRS_PROV_PRODUCTS_PROCESS.PROCESS_NBR
     */
    public void setPROCESS_NBR(BigDecimal PROCESS_NBR) {
        this.PROCESS_NBR = PROCESS_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROV_PRODUCTS_PROCESS.SL_NO
     *
     * @return the value of TRS_PROV_PRODUCTS_PROCESS.SL_NO
     */
    public BigDecimal getSL_NO() {
        return SL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROV_PRODUCTS_PROCESS.SL_NO
     *
     * @param SL_NO the value for TRS_PROV_PRODUCTS_PROCESS.SL_NO
     */
    public void setSL_NO(BigDecimal SL_NO) {
        this.SL_NO = SL_NO;
    }
}