package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class TRS_TREASURY_LIMITVO extends TRS_TREASURY_LIMITVOKey {
    /**
     * This field corresponds to the database column TRS_TREASURY_LIMIT.ONE_OBLIGOR
     */
    private BigDecimal ONE_OBLIGOR;

    /**
     * This field corresponds to the database column TRS_TREASURY_LIMIT.TREASURY_LIMIT
     */
    private BigDecimal TREASURY_LIMIT;

    /**
     * This field corresponds to the database column TRS_TREASURY_LIMIT.LIMIT_UTILIZED
     */
    private BigDecimal LIMIT_UTILIZED;

    /**
     * This field corresponds to the database column TRS_TREASURY_LIMIT.RISK_LIMIT
     */
    private BigDecimal RISK_LIMIT;

    /**
     * This field corresponds to the database column TRS_TREASURY_LIMIT.STATUS
     */
    private String STATUS;

    /**
     * This field corresponds to the database column TRS_TREASURY_LIMIT.CREATED_BY
     */
    private String CREATED_BY;

    /**
     * This field corresponds to the database column TRS_TREASURY_LIMIT.MODIFIED_BY
     */
    private String MODIFIED_BY;

    /**
     * This field corresponds to the database column TRS_TREASURY_LIMIT.DATE_CREATED
     */
    private Date DATE_CREATED;

    /**
     * This field corresponds to the database column TRS_TREASURY_LIMIT.DATE_MODIFIED
     */
    private Date DATE_MODIFIED;

    /**
     * This field corresponds to the database column TRS_TREASURY_LIMIT.APPROVED_BY
     */
    private String APPROVED_BY;

    /**
     * This field corresponds to the database column TRS_TREASURY_LIMIT.DATE_APPROVED
     */
    private Date DATE_APPROVED;

    /**
     * This field corresponds to the database column TRS_TREASURY_LIMIT.RISK_APROVE_STATUS
     */
    private String RISK_APROVE_STATUS;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_TREASURY_LIMIT.ONE_OBLIGOR
     *
     * @return the value of TRS_TREASURY_LIMIT.ONE_OBLIGOR
     */
    public BigDecimal getONE_OBLIGOR() {
        return ONE_OBLIGOR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_TREASURY_LIMIT.ONE_OBLIGOR
     *
     * @param ONE_OBLIGOR the value for TRS_TREASURY_LIMIT.ONE_OBLIGOR
     */
    public void setONE_OBLIGOR(BigDecimal ONE_OBLIGOR) {
        this.ONE_OBLIGOR = ONE_OBLIGOR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_TREASURY_LIMIT.TREASURY_LIMIT
     *
     * @return the value of TRS_TREASURY_LIMIT.TREASURY_LIMIT
     */
    public BigDecimal getTREASURY_LIMIT() {
        return TREASURY_LIMIT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_TREASURY_LIMIT.TREASURY_LIMIT
     *
     * @param TREASURY_LIMIT the value for TRS_TREASURY_LIMIT.TREASURY_LIMIT
     */
    public void setTREASURY_LIMIT(BigDecimal TREASURY_LIMIT) {
        this.TREASURY_LIMIT = TREASURY_LIMIT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_TREASURY_LIMIT.LIMIT_UTILIZED
     *
     * @return the value of TRS_TREASURY_LIMIT.LIMIT_UTILIZED
     */
    public BigDecimal getLIMIT_UTILIZED() {
        return LIMIT_UTILIZED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_TREASURY_LIMIT.LIMIT_UTILIZED
     *
     * @param LIMIT_UTILIZED the value for TRS_TREASURY_LIMIT.LIMIT_UTILIZED
     */
    public void setLIMIT_UTILIZED(BigDecimal LIMIT_UTILIZED) {
        this.LIMIT_UTILIZED = LIMIT_UTILIZED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_TREASURY_LIMIT.RISK_LIMIT
     *
     * @return the value of TRS_TREASURY_LIMIT.RISK_LIMIT
     */
    public BigDecimal getRISK_LIMIT() {
        return RISK_LIMIT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_TREASURY_LIMIT.RISK_LIMIT
     *
     * @param RISK_LIMIT the value for TRS_TREASURY_LIMIT.RISK_LIMIT
     */
    public void setRISK_LIMIT(BigDecimal RISK_LIMIT) {
        this.RISK_LIMIT = RISK_LIMIT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_TREASURY_LIMIT.STATUS
     *
     * @return the value of TRS_TREASURY_LIMIT.STATUS
     */
    public String getSTATUS() {
        return STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_TREASURY_LIMIT.STATUS
     *
     * @param STATUS the value for TRS_TREASURY_LIMIT.STATUS
     */
    public void setSTATUS(String STATUS) {
        this.STATUS = STATUS == null ? null : STATUS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_TREASURY_LIMIT.CREATED_BY
     *
     * @return the value of TRS_TREASURY_LIMIT.CREATED_BY
     */
    public String getCREATED_BY() {
        return CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_TREASURY_LIMIT.CREATED_BY
     *
     * @param CREATED_BY the value for TRS_TREASURY_LIMIT.CREATED_BY
     */
    public void setCREATED_BY(String CREATED_BY) {
        this.CREATED_BY = CREATED_BY == null ? null : CREATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_TREASURY_LIMIT.MODIFIED_BY
     *
     * @return the value of TRS_TREASURY_LIMIT.MODIFIED_BY
     */
    public String getMODIFIED_BY() {
        return MODIFIED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_TREASURY_LIMIT.MODIFIED_BY
     *
     * @param MODIFIED_BY the value for TRS_TREASURY_LIMIT.MODIFIED_BY
     */
    public void setMODIFIED_BY(String MODIFIED_BY) {
        this.MODIFIED_BY = MODIFIED_BY == null ? null : MODIFIED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_TREASURY_LIMIT.DATE_CREATED
     *
     * @return the value of TRS_TREASURY_LIMIT.DATE_CREATED
     */
    public Date getDATE_CREATED() {
        return DATE_CREATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_TREASURY_LIMIT.DATE_CREATED
     *
     * @param DATE_CREATED the value for TRS_TREASURY_LIMIT.DATE_CREATED
     */
    public void setDATE_CREATED(Date DATE_CREATED) {
        this.DATE_CREATED = DATE_CREATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_TREASURY_LIMIT.DATE_MODIFIED
     *
     * @return the value of TRS_TREASURY_LIMIT.DATE_MODIFIED
     */
    public Date getDATE_MODIFIED() {
        return DATE_MODIFIED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_TREASURY_LIMIT.DATE_MODIFIED
     *
     * @param DATE_MODIFIED the value for TRS_TREASURY_LIMIT.DATE_MODIFIED
     */
    public void setDATE_MODIFIED(Date DATE_MODIFIED) {
        this.DATE_MODIFIED = DATE_MODIFIED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_TREASURY_LIMIT.APPROVED_BY
     *
     * @return the value of TRS_TREASURY_LIMIT.APPROVED_BY
     */
    public String getAPPROVED_BY() {
        return APPROVED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_TREASURY_LIMIT.APPROVED_BY
     *
     * @param APPROVED_BY the value for TRS_TREASURY_LIMIT.APPROVED_BY
     */
    public void setAPPROVED_BY(String APPROVED_BY) {
        this.APPROVED_BY = APPROVED_BY == null ? null : APPROVED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_TREASURY_LIMIT.DATE_APPROVED
     *
     * @return the value of TRS_TREASURY_LIMIT.DATE_APPROVED
     */
    public Date getDATE_APPROVED() {
        return DATE_APPROVED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_TREASURY_LIMIT.DATE_APPROVED
     *
     * @param DATE_APPROVED the value for TRS_TREASURY_LIMIT.DATE_APPROVED
     */
    public void setDATE_APPROVED(Date DATE_APPROVED) {
        this.DATE_APPROVED = DATE_APPROVED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_TREASURY_LIMIT.RISK_APROVE_STATUS
     *
     * @return the value of TRS_TREASURY_LIMIT.RISK_APROVE_STATUS
     */
    public String getRISK_APROVE_STATUS() {
        return RISK_APROVE_STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_TREASURY_LIMIT.RISK_APROVE_STATUS
     *
     * @param RISK_APROVE_STATUS the value for TRS_TREASURY_LIMIT.RISK_APROVE_STATUS
     */
    public void setRISK_APROVE_STATUS(String RISK_APROVE_STATUS) {
        this.RISK_APROVE_STATUS = RISK_APROVE_STATUS == null ? null : RISK_APROVE_STATUS.trim();
    }
}