package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class TRS_VEND_INCENTIVEVOKey extends BaseVO {
    /**
     * This field corresponds to the database column TRS_VEND_INCENTIVE.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column TRS_VEND_INCENTIVE.INCENTIVE_CODE
     */
    private BigDecimal INCENTIVE_CODE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_VEND_INCENTIVE.COMP_CODE
     *
     * @return the value of TRS_VEND_INCENTIVE.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_VEND_INCENTIVE.COMP_CODE
     *
     * @param COMP_CODE the value for TRS_VEND_INCENTIVE.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_VEND_INCENTIVE.INCENTIVE_CODE
     *
     * @return the value of TRS_VEND_INCENTIVE.INCENTIVE_CODE
     */
    public BigDecimal getINCENTIVE_CODE() {
        return INCENTIVE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_VEND_INCENTIVE.INCENTIVE_CODE
     *
     * @param INCENTIVE_CODE the value for TRS_VEND_INCENTIVE.INCENTIVE_CODE
     */
    public void setINCENTIVE_CODE(BigDecimal INCENTIVE_CODE) {
        this.INCENTIVE_CODE = INCENTIVE_CODE;
    }
}