package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class TRS_SUB_PURPOSEVOKey extends BaseVO {
    /**
     * This field corresponds to the database column TRS_SUB_PURPOSE.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column TRS_SUB_PURPOSE.SUB_PURPOSE_CODE
     */
    private BigDecimal SUB_PURPOSE_CODE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_SUB_PURPOSE.COMP_CODE
     *
     * @return the value of TRS_SUB_PURPOSE.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_SUB_PURPOSE.COMP_CODE
     *
     * @param COMP_CODE the value for TRS_SUB_PURPOSE.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_SUB_PURPOSE.SUB_PURPOSE_CODE
     *
     * @return the value of TRS_SUB_PURPOSE.SUB_PURPOSE_CODE
     */
    public BigDecimal getSUB_PURPOSE_CODE() {
        return SUB_PURPOSE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_SUB_PURPOSE.SUB_PURPOSE_CODE
     *
     * @param SUB_PURPOSE_CODE the value for TRS_SUB_PURPOSE.SUB_PURPOSE_CODE
     */
    public void setSUB_PURPOSE_CODE(BigDecimal SUB_PURPOSE_CODE) {
        this.SUB_PURPOSE_CODE = SUB_PURPOSE_CODE;
    }
}