package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;
import java.util.Date;

public class TRS_PROVISION_PROCESSVOKey extends BaseVO {
    /**
     * This field corresponds to the database column TRS_PROVISION_PROCESS.BRANCH_CODE
     */
    private BigDecimal BRANCH_CODE;

    /**
     * This field corresponds to the database column TRS_PROVISION_PROCESS.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column TRS_PROVISION_PROCESS.DEAL_NO
     */
    private BigDecimal DEAL_NO;

    /**
     * This field corresponds to the database column TRS_PROVISION_PROCESS.INSTALLMENT_DATE
     */
    private Date INSTALLMENT_DATE;

    /**
     * This field corresponds to the database column TRS_PROVISION_PROCESS.INSTALLMENT_NBR
     */
    private BigDecimal INSTALLMENT_NBR;

    /**
     * This field corresponds to the database column TRS_PROVISION_PROCESS.PLAN_NBR
     */
    private BigDecimal PLAN_NBR;

    /**
     * This field corresponds to the database column TRS_PROVISION_PROCESS.PLAN_SEQ
     */
    private BigDecimal PLAN_SEQ;

    /**
     * This field corresponds to the database column TRS_PROVISION_PROCESS.PROCESS_NBR
     */
    private BigDecimal PROCESS_NBR;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROVISION_PROCESS.BRANCH_CODE
     *
     * @return the value of TRS_PROVISION_PROCESS.BRANCH_CODE
     */
    public BigDecimal getBRANCH_CODE() {
        return BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROVISION_PROCESS.BRANCH_CODE
     *
     * @param BRANCH_CODE the value for TRS_PROVISION_PROCESS.BRANCH_CODE
     */
    public void setBRANCH_CODE(BigDecimal BRANCH_CODE) {
        this.BRANCH_CODE = BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROVISION_PROCESS.COMP_CODE
     *
     * @return the value of TRS_PROVISION_PROCESS.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROVISION_PROCESS.COMP_CODE
     *
     * @param COMP_CODE the value for TRS_PROVISION_PROCESS.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROVISION_PROCESS.DEAL_NO
     *
     * @return the value of TRS_PROVISION_PROCESS.DEAL_NO
     */
    public BigDecimal getDEAL_NO() {
        return DEAL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROVISION_PROCESS.DEAL_NO
     *
     * @param DEAL_NO the value for TRS_PROVISION_PROCESS.DEAL_NO
     */
    public void setDEAL_NO(BigDecimal DEAL_NO) {
        this.DEAL_NO = DEAL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROVISION_PROCESS.INSTALLMENT_DATE
     *
     * @return the value of TRS_PROVISION_PROCESS.INSTALLMENT_DATE
     */
    public Date getINSTALLMENT_DATE() {
        return INSTALLMENT_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROVISION_PROCESS.INSTALLMENT_DATE
     *
     * @param INSTALLMENT_DATE the value for TRS_PROVISION_PROCESS.INSTALLMENT_DATE
     */
    public void setINSTALLMENT_DATE(Date INSTALLMENT_DATE) {
        this.INSTALLMENT_DATE = INSTALLMENT_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROVISION_PROCESS.INSTALLMENT_NBR
     *
     * @return the value of TRS_PROVISION_PROCESS.INSTALLMENT_NBR
     */
    public BigDecimal getINSTALLMENT_NBR() {
        return INSTALLMENT_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROVISION_PROCESS.INSTALLMENT_NBR
     *
     * @param INSTALLMENT_NBR the value for TRS_PROVISION_PROCESS.INSTALLMENT_NBR
     */
    public void setINSTALLMENT_NBR(BigDecimal INSTALLMENT_NBR) {
        this.INSTALLMENT_NBR = INSTALLMENT_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROVISION_PROCESS.PLAN_NBR
     *
     * @return the value of TRS_PROVISION_PROCESS.PLAN_NBR
     */
    public BigDecimal getPLAN_NBR() {
        return PLAN_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROVISION_PROCESS.PLAN_NBR
     *
     * @param PLAN_NBR the value for TRS_PROVISION_PROCESS.PLAN_NBR
     */
    public void setPLAN_NBR(BigDecimal PLAN_NBR) {
        this.PLAN_NBR = PLAN_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROVISION_PROCESS.PLAN_SEQ
     *
     * @return the value of TRS_PROVISION_PROCESS.PLAN_SEQ
     */
    public BigDecimal getPLAN_SEQ() {
        return PLAN_SEQ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROVISION_PROCESS.PLAN_SEQ
     *
     * @param PLAN_SEQ the value for TRS_PROVISION_PROCESS.PLAN_SEQ
     */
    public void setPLAN_SEQ(BigDecimal PLAN_SEQ) {
        this.PLAN_SEQ = PLAN_SEQ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRS_PROVISION_PROCESS.PROCESS_NBR
     *
     * @return the value of TRS_PROVISION_PROCESS.PROCESS_NBR
     */
    public BigDecimal getPROCESS_NBR() {
        return PROCESS_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRS_PROVISION_PROCESS.PROCESS_NBR
     *
     * @param PROCESS_NBR the value for TRS_PROVISION_PROCESS.PROCESS_NBR
     */
    public void setPROCESS_NBR(BigDecimal PROCESS_NBR) {
        this.PROCESS_NBR = PROCESS_NBR;
    }
}