package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class TRSASSETVO extends TRSASSETVOKey {
    /**
     * This field corresponds to the database column TRSASSET.BRIEF_NAME_ENG
     */
    private String BRIEF_NAME_ENG;

    /**
     * This field corresponds to the database column TRSASSET.LONG_NAME_ENG
     */
    private String LONG_NAME_ENG;

    /**
     * This field corresponds to the database column TRSASSET.BRIEF_NAME_ARAB
     */
    private String BRIEF_NAME_ARAB;

    /**
     * This field corresponds to the database column TRSASSET.LONG_NAME_ARAB
     */
    private String LONG_NAME_ARAB;

    /**
     * This field corresponds to the database column TRSASSET.PURCHASE_AMOUNT
     */
    private BigDecimal PURCHASE_AMOUNT;

    /**
     * This field corresponds to the database column TRSASSET.PURCHASE_CY_CODE
     */
    private BigDecimal PURCHASE_CY_CODE;

    /**
     * This field corresponds to the database column TRSASSET.SALES_AMOUNT
     */
    private BigDecimal SALES_AMOUNT;

    /**
     * This field corresponds to the database column TRSASSET.SALES_CY_CODE
     */
    private BigDecimal SALES_CY_CODE;

    /**
     * This field corresponds to the database column TRSASSET.PURCHASE_CY_RATE
     */
    private BigDecimal PURCHASE_CY_RATE;

    /**
     * This field corresponds to the database column TRSASSET.PURCHASE_CY_UNIT
     */
    private BigDecimal PURCHASE_CY_UNIT;

    /**
     * This field corresponds to the database column TRSASSET.SALES_CY_RATE
     */
    private BigDecimal SALES_CY_RATE;

    /**
     * This field corresponds to the database column TRSASSET.SALES_CY_UNIT
     */
    private BigDecimal SALES_CY_UNIT;

    /**
     * This field corresponds to the database column TRSASSET.SALES_CY_MULT_DIV
     */
    private String SALES_CY_MULT_DIV;

    /**
     * This field corresponds to the database column TRSASSET.PURCHASE_CY_MULT_DIV
     */
    private String PURCHASE_CY_MULT_DIV;

    /**
     * This field corresponds to the database column TRSASSET.DEAL_NBR
     */
    private BigDecimal DEAL_NBR;

    /**
     * This field corresponds to the database column TRSASSET.ADD_NUMBER1
     */
    private BigDecimal ADD_NUMBER1;

    /**
     * This field corresponds to the database column TRSASSET.ADD_NUMBER2
     */
    private BigDecimal ADD_NUMBER2;

    /**
     * This field corresponds to the database column TRSASSET.ADD_NUMBER3
     */
    private BigDecimal ADD_NUMBER3;

    /**
     * This field corresponds to the database column TRSASSET.ADD_NUMBER4
     */
    private BigDecimal ADD_NUMBER4;

    /**
     * This field corresponds to the database column TRSASSET.ADD_NUMBER5
     */
    private BigDecimal ADD_NUMBER5;

    /**
     * This field corresponds to the database column TRSASSET.ADD_STRING1
     */
    private String ADD_STRING1;

    /**
     * This field corresponds to the database column TRSASSET.ADD_STRING2
     */
    private String ADD_STRING2;

    /**
     * This field corresponds to the database column TRSASSET.ADD_STRING3
     */
    private String ADD_STRING3;

    /**
     * This field corresponds to the database column TRSASSET.ADD_STRING4
     */
    private String ADD_STRING4;

    /**
     * This field corresponds to the database column TRSASSET.ADD_STRING5
     */
    private String ADD_STRING5;

    /**
     * This field corresponds to the database column TRSASSET.ADD_DATE1
     */
    private Date ADD_DATE1;

    /**
     * This field corresponds to the database column TRSASSET.ADD_DATE2
     */
    private Date ADD_DATE2;

    /**
     * This field corresponds to the database column TRSASSET.ADD_DATE3
     */
    private Date ADD_DATE3;

    /**
     * This field corresponds to the database column TRSASSET.ADD_DATE4
     */
    private Date ADD_DATE4;

    /**
     * This field corresponds to the database column TRSASSET.ADD_DATE5
     */
    private Date ADD_DATE5;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSASSET.BRIEF_NAME_ENG
     *
     * @return the value of TRSASSET.BRIEF_NAME_ENG
     */
    public String getBRIEF_NAME_ENG() {
        return BRIEF_NAME_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSASSET.BRIEF_NAME_ENG
     *
     * @param BRIEF_NAME_ENG the value for TRSASSET.BRIEF_NAME_ENG
     */
    public void setBRIEF_NAME_ENG(String BRIEF_NAME_ENG) {
        this.BRIEF_NAME_ENG = BRIEF_NAME_ENG == null ? null : BRIEF_NAME_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSASSET.LONG_NAME_ENG
     *
     * @return the value of TRSASSET.LONG_NAME_ENG
     */
    public String getLONG_NAME_ENG() {
        return LONG_NAME_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSASSET.LONG_NAME_ENG
     *
     * @param LONG_NAME_ENG the value for TRSASSET.LONG_NAME_ENG
     */
    public void setLONG_NAME_ENG(String LONG_NAME_ENG) {
        this.LONG_NAME_ENG = LONG_NAME_ENG == null ? null : LONG_NAME_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSASSET.BRIEF_NAME_ARAB
     *
     * @return the value of TRSASSET.BRIEF_NAME_ARAB
     */
    public String getBRIEF_NAME_ARAB() {
        return BRIEF_NAME_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSASSET.BRIEF_NAME_ARAB
     *
     * @param BRIEF_NAME_ARAB the value for TRSASSET.BRIEF_NAME_ARAB
     */
    public void setBRIEF_NAME_ARAB(String BRIEF_NAME_ARAB) {
        this.BRIEF_NAME_ARAB = BRIEF_NAME_ARAB == null ? null : BRIEF_NAME_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSASSET.LONG_NAME_ARAB
     *
     * @return the value of TRSASSET.LONG_NAME_ARAB
     */
    public String getLONG_NAME_ARAB() {
        return LONG_NAME_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSASSET.LONG_NAME_ARAB
     *
     * @param LONG_NAME_ARAB the value for TRSASSET.LONG_NAME_ARAB
     */
    public void setLONG_NAME_ARAB(String LONG_NAME_ARAB) {
        this.LONG_NAME_ARAB = LONG_NAME_ARAB == null ? null : LONG_NAME_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSASSET.PURCHASE_AMOUNT
     *
     * @return the value of TRSASSET.PURCHASE_AMOUNT
     */
    public BigDecimal getPURCHASE_AMOUNT() {
        return PURCHASE_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSASSET.PURCHASE_AMOUNT
     *
     * @param PURCHASE_AMOUNT the value for TRSASSET.PURCHASE_AMOUNT
     */
    public void setPURCHASE_AMOUNT(BigDecimal PURCHASE_AMOUNT) {
        this.PURCHASE_AMOUNT = PURCHASE_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSASSET.PURCHASE_CY_CODE
     *
     * @return the value of TRSASSET.PURCHASE_CY_CODE
     */
    public BigDecimal getPURCHASE_CY_CODE() {
        return PURCHASE_CY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSASSET.PURCHASE_CY_CODE
     *
     * @param PURCHASE_CY_CODE the value for TRSASSET.PURCHASE_CY_CODE
     */
    public void setPURCHASE_CY_CODE(BigDecimal PURCHASE_CY_CODE) {
        this.PURCHASE_CY_CODE = PURCHASE_CY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSASSET.SALES_AMOUNT
     *
     * @return the value of TRSASSET.SALES_AMOUNT
     */
    public BigDecimal getSALES_AMOUNT() {
        return SALES_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSASSET.SALES_AMOUNT
     *
     * @param SALES_AMOUNT the value for TRSASSET.SALES_AMOUNT
     */
    public void setSALES_AMOUNT(BigDecimal SALES_AMOUNT) {
        this.SALES_AMOUNT = SALES_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSASSET.SALES_CY_CODE
     *
     * @return the value of TRSASSET.SALES_CY_CODE
     */
    public BigDecimal getSALES_CY_CODE() {
        return SALES_CY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSASSET.SALES_CY_CODE
     *
     * @param SALES_CY_CODE the value for TRSASSET.SALES_CY_CODE
     */
    public void setSALES_CY_CODE(BigDecimal SALES_CY_CODE) {
        this.SALES_CY_CODE = SALES_CY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSASSET.PURCHASE_CY_RATE
     *
     * @return the value of TRSASSET.PURCHASE_CY_RATE
     */
    public BigDecimal getPURCHASE_CY_RATE() {
        return PURCHASE_CY_RATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSASSET.PURCHASE_CY_RATE
     *
     * @param PURCHASE_CY_RATE the value for TRSASSET.PURCHASE_CY_RATE
     */
    public void setPURCHASE_CY_RATE(BigDecimal PURCHASE_CY_RATE) {
        this.PURCHASE_CY_RATE = PURCHASE_CY_RATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSASSET.PURCHASE_CY_UNIT
     *
     * @return the value of TRSASSET.PURCHASE_CY_UNIT
     */
    public BigDecimal getPURCHASE_CY_UNIT() {
        return PURCHASE_CY_UNIT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSASSET.PURCHASE_CY_UNIT
     *
     * @param PURCHASE_CY_UNIT the value for TRSASSET.PURCHASE_CY_UNIT
     */
    public void setPURCHASE_CY_UNIT(BigDecimal PURCHASE_CY_UNIT) {
        this.PURCHASE_CY_UNIT = PURCHASE_CY_UNIT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSASSET.SALES_CY_RATE
     *
     * @return the value of TRSASSET.SALES_CY_RATE
     */
    public BigDecimal getSALES_CY_RATE() {
        return SALES_CY_RATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSASSET.SALES_CY_RATE
     *
     * @param SALES_CY_RATE the value for TRSASSET.SALES_CY_RATE
     */
    public void setSALES_CY_RATE(BigDecimal SALES_CY_RATE) {
        this.SALES_CY_RATE = SALES_CY_RATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSASSET.SALES_CY_UNIT
     *
     * @return the value of TRSASSET.SALES_CY_UNIT
     */
    public BigDecimal getSALES_CY_UNIT() {
        return SALES_CY_UNIT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSASSET.SALES_CY_UNIT
     *
     * @param SALES_CY_UNIT the value for TRSASSET.SALES_CY_UNIT
     */
    public void setSALES_CY_UNIT(BigDecimal SALES_CY_UNIT) {
        this.SALES_CY_UNIT = SALES_CY_UNIT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSASSET.SALES_CY_MULT_DIV
     *
     * @return the value of TRSASSET.SALES_CY_MULT_DIV
     */
    public String getSALES_CY_MULT_DIV() {
        return SALES_CY_MULT_DIV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSASSET.SALES_CY_MULT_DIV
     *
     * @param SALES_CY_MULT_DIV the value for TRSASSET.SALES_CY_MULT_DIV
     */
    public void setSALES_CY_MULT_DIV(String SALES_CY_MULT_DIV) {
        this.SALES_CY_MULT_DIV = SALES_CY_MULT_DIV == null ? null : SALES_CY_MULT_DIV.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSASSET.PURCHASE_CY_MULT_DIV
     *
     * @return the value of TRSASSET.PURCHASE_CY_MULT_DIV
     */
    public String getPURCHASE_CY_MULT_DIV() {
        return PURCHASE_CY_MULT_DIV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSASSET.PURCHASE_CY_MULT_DIV
     *
     * @param PURCHASE_CY_MULT_DIV the value for TRSASSET.PURCHASE_CY_MULT_DIV
     */
    public void setPURCHASE_CY_MULT_DIV(String PURCHASE_CY_MULT_DIV) {
        this.PURCHASE_CY_MULT_DIV = PURCHASE_CY_MULT_DIV == null ? null : PURCHASE_CY_MULT_DIV.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSASSET.DEAL_NBR
     *
     * @return the value of TRSASSET.DEAL_NBR
     */
    public BigDecimal getDEAL_NBR() {
        return DEAL_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSASSET.DEAL_NBR
     *
     * @param DEAL_NBR the value for TRSASSET.DEAL_NBR
     */
    public void setDEAL_NBR(BigDecimal DEAL_NBR) {
        this.DEAL_NBR = DEAL_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSASSET.ADD_NUMBER1
     *
     * @return the value of TRSASSET.ADD_NUMBER1
     */
    public BigDecimal getADD_NUMBER1() {
        return ADD_NUMBER1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSASSET.ADD_NUMBER1
     *
     * @param ADD_NUMBER1 the value for TRSASSET.ADD_NUMBER1
     */
    public void setADD_NUMBER1(BigDecimal ADD_NUMBER1) {
        this.ADD_NUMBER1 = ADD_NUMBER1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSASSET.ADD_NUMBER2
     *
     * @return the value of TRSASSET.ADD_NUMBER2
     */
    public BigDecimal getADD_NUMBER2() {
        return ADD_NUMBER2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSASSET.ADD_NUMBER2
     *
     * @param ADD_NUMBER2 the value for TRSASSET.ADD_NUMBER2
     */
    public void setADD_NUMBER2(BigDecimal ADD_NUMBER2) {
        this.ADD_NUMBER2 = ADD_NUMBER2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSASSET.ADD_NUMBER3
     *
     * @return the value of TRSASSET.ADD_NUMBER3
     */
    public BigDecimal getADD_NUMBER3() {
        return ADD_NUMBER3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSASSET.ADD_NUMBER3
     *
     * @param ADD_NUMBER3 the value for TRSASSET.ADD_NUMBER3
     */
    public void setADD_NUMBER3(BigDecimal ADD_NUMBER3) {
        this.ADD_NUMBER3 = ADD_NUMBER3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSASSET.ADD_NUMBER4
     *
     * @return the value of TRSASSET.ADD_NUMBER4
     */
    public BigDecimal getADD_NUMBER4() {
        return ADD_NUMBER4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSASSET.ADD_NUMBER4
     *
     * @param ADD_NUMBER4 the value for TRSASSET.ADD_NUMBER4
     */
    public void setADD_NUMBER4(BigDecimal ADD_NUMBER4) {
        this.ADD_NUMBER4 = ADD_NUMBER4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSASSET.ADD_NUMBER5
     *
     * @return the value of TRSASSET.ADD_NUMBER5
     */
    public BigDecimal getADD_NUMBER5() {
        return ADD_NUMBER5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSASSET.ADD_NUMBER5
     *
     * @param ADD_NUMBER5 the value for TRSASSET.ADD_NUMBER5
     */
    public void setADD_NUMBER5(BigDecimal ADD_NUMBER5) {
        this.ADD_NUMBER5 = ADD_NUMBER5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSASSET.ADD_STRING1
     *
     * @return the value of TRSASSET.ADD_STRING1
     */
    public String getADD_STRING1() {
        return ADD_STRING1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSASSET.ADD_STRING1
     *
     * @param ADD_STRING1 the value for TRSASSET.ADD_STRING1
     */
    public void setADD_STRING1(String ADD_STRING1) {
        this.ADD_STRING1 = ADD_STRING1 == null ? null : ADD_STRING1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSASSET.ADD_STRING2
     *
     * @return the value of TRSASSET.ADD_STRING2
     */
    public String getADD_STRING2() {
        return ADD_STRING2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSASSET.ADD_STRING2
     *
     * @param ADD_STRING2 the value for TRSASSET.ADD_STRING2
     */
    public void setADD_STRING2(String ADD_STRING2) {
        this.ADD_STRING2 = ADD_STRING2 == null ? null : ADD_STRING2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSASSET.ADD_STRING3
     *
     * @return the value of TRSASSET.ADD_STRING3
     */
    public String getADD_STRING3() {
        return ADD_STRING3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSASSET.ADD_STRING3
     *
     * @param ADD_STRING3 the value for TRSASSET.ADD_STRING3
     */
    public void setADD_STRING3(String ADD_STRING3) {
        this.ADD_STRING3 = ADD_STRING3 == null ? null : ADD_STRING3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSASSET.ADD_STRING4
     *
     * @return the value of TRSASSET.ADD_STRING4
     */
    public String getADD_STRING4() {
        return ADD_STRING4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSASSET.ADD_STRING4
     *
     * @param ADD_STRING4 the value for TRSASSET.ADD_STRING4
     */
    public void setADD_STRING4(String ADD_STRING4) {
        this.ADD_STRING4 = ADD_STRING4 == null ? null : ADD_STRING4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSASSET.ADD_STRING5
     *
     * @return the value of TRSASSET.ADD_STRING5
     */
    public String getADD_STRING5() {
        return ADD_STRING5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSASSET.ADD_STRING5
     *
     * @param ADD_STRING5 the value for TRSASSET.ADD_STRING5
     */
    public void setADD_STRING5(String ADD_STRING5) {
        this.ADD_STRING5 = ADD_STRING5 == null ? null : ADD_STRING5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSASSET.ADD_DATE1
     *
     * @return the value of TRSASSET.ADD_DATE1
     */
    public Date getADD_DATE1() {
        return ADD_DATE1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSASSET.ADD_DATE1
     *
     * @param ADD_DATE1 the value for TRSASSET.ADD_DATE1
     */
    public void setADD_DATE1(Date ADD_DATE1) {
        this.ADD_DATE1 = ADD_DATE1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSASSET.ADD_DATE2
     *
     * @return the value of TRSASSET.ADD_DATE2
     */
    public Date getADD_DATE2() {
        return ADD_DATE2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSASSET.ADD_DATE2
     *
     * @param ADD_DATE2 the value for TRSASSET.ADD_DATE2
     */
    public void setADD_DATE2(Date ADD_DATE2) {
        this.ADD_DATE2 = ADD_DATE2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSASSET.ADD_DATE3
     *
     * @return the value of TRSASSET.ADD_DATE3
     */
    public Date getADD_DATE3() {
        return ADD_DATE3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSASSET.ADD_DATE3
     *
     * @param ADD_DATE3 the value for TRSASSET.ADD_DATE3
     */
    public void setADD_DATE3(Date ADD_DATE3) {
        this.ADD_DATE3 = ADD_DATE3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSASSET.ADD_DATE4
     *
     * @return the value of TRSASSET.ADD_DATE4
     */
    public Date getADD_DATE4() {
        return ADD_DATE4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSASSET.ADD_DATE4
     *
     * @param ADD_DATE4 the value for TRSASSET.ADD_DATE4
     */
    public void setADD_DATE4(Date ADD_DATE4) {
        this.ADD_DATE4 = ADD_DATE4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSASSET.ADD_DATE5
     *
     * @return the value of TRSASSET.ADD_DATE5
     */
    public Date getADD_DATE5() {
        return ADD_DATE5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSASSET.ADD_DATE5
     *
     * @param ADD_DATE5 the value for TRSASSET.ADD_DATE5
     */
    public void setADD_DATE5(Date ADD_DATE5) {
        this.ADD_DATE5 = ADD_DATE5;
    }
}