package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class TRSADVANCE_INS_DEPRECIATIONVO extends TRSADVANCE_INS_DEPRECIATIONVOKey {
    /**
     * This field corresponds to the database column TRSADVANCE_INS_DEPRECIATION.DEPRECIATION_YEAR
     */
    private BigDecimal DEPRECIATION_YEAR;

    /**
     * This field corresponds to the database column TRSADVANCE_INS_DEPRECIATION.DEPRECIATION_RATE
     */
    private BigDecimal DEPRECIATION_RATE;

    /**
     * This field corresponds to the database column TRSADVANCE_INS_DEPRECIATION.INS_END_DATE
     */
    private Date INS_END_DATE;

    /**
     * This field corresponds to the database column TRSADVANCE_INS_DEPRECIATION.INS_START_DATE
     */
    private Date INS_START_DATE;

    /**
     * This field corresponds to the database column TRSADVANCE_INS_DEPRECIATION.TRACKER_AMOUNT
     */
    private BigDecimal TRACKER_AMOUNT;

    /**
     * This field corresponds to the database column TRSADVANCE_INS_DEPRECIATION.INSURANCE_COMP_CODE
     */
    private BigDecimal INSURANCE_COMP_CODE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSADVANCE_INS_DEPRECIATION.DEPRECIATION_YEAR
     *
     * @return the value of TRSADVANCE_INS_DEPRECIATION.DEPRECIATION_YEAR
     */
    public BigDecimal getDEPRECIATION_YEAR() {
        return DEPRECIATION_YEAR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSADVANCE_INS_DEPRECIATION.DEPRECIATION_YEAR
     *
     * @param DEPRECIATION_YEAR the value for TRSADVANCE_INS_DEPRECIATION.DEPRECIATION_YEAR
     */
    public void setDEPRECIATION_YEAR(BigDecimal DEPRECIATION_YEAR) {
        this.DEPRECIATION_YEAR = DEPRECIATION_YEAR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSADVANCE_INS_DEPRECIATION.DEPRECIATION_RATE
     *
     * @return the value of TRSADVANCE_INS_DEPRECIATION.DEPRECIATION_RATE
     */
    public BigDecimal getDEPRECIATION_RATE() {
        return DEPRECIATION_RATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSADVANCE_INS_DEPRECIATION.DEPRECIATION_RATE
     *
     * @param DEPRECIATION_RATE the value for TRSADVANCE_INS_DEPRECIATION.DEPRECIATION_RATE
     */
    public void setDEPRECIATION_RATE(BigDecimal DEPRECIATION_RATE) {
        this.DEPRECIATION_RATE = DEPRECIATION_RATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSADVANCE_INS_DEPRECIATION.INS_END_DATE
     *
     * @return the value of TRSADVANCE_INS_DEPRECIATION.INS_END_DATE
     */
    public Date getINS_END_DATE() {
        return INS_END_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSADVANCE_INS_DEPRECIATION.INS_END_DATE
     *
     * @param INS_END_DATE the value for TRSADVANCE_INS_DEPRECIATION.INS_END_DATE
     */
    public void setINS_END_DATE(Date INS_END_DATE) {
        this.INS_END_DATE = INS_END_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSADVANCE_INS_DEPRECIATION.INS_START_DATE
     *
     * @return the value of TRSADVANCE_INS_DEPRECIATION.INS_START_DATE
     */
    public Date getINS_START_DATE() {
        return INS_START_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSADVANCE_INS_DEPRECIATION.INS_START_DATE
     *
     * @param INS_START_DATE the value for TRSADVANCE_INS_DEPRECIATION.INS_START_DATE
     */
    public void setINS_START_DATE(Date INS_START_DATE) {
        this.INS_START_DATE = INS_START_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSADVANCE_INS_DEPRECIATION.TRACKER_AMOUNT
     *
     * @return the value of TRSADVANCE_INS_DEPRECIATION.TRACKER_AMOUNT
     */
    public BigDecimal getTRACKER_AMOUNT() {
        return TRACKER_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSADVANCE_INS_DEPRECIATION.TRACKER_AMOUNT
     *
     * @param TRACKER_AMOUNT the value for TRSADVANCE_INS_DEPRECIATION.TRACKER_AMOUNT
     */
    public void setTRACKER_AMOUNT(BigDecimal TRACKER_AMOUNT) {
        this.TRACKER_AMOUNT = TRACKER_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSADVANCE_INS_DEPRECIATION.INSURANCE_COMP_CODE
     *
     * @return the value of TRSADVANCE_INS_DEPRECIATION.INSURANCE_COMP_CODE
     */
    public BigDecimal getINSURANCE_COMP_CODE() {
        return INSURANCE_COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSADVANCE_INS_DEPRECIATION.INSURANCE_COMP_CODE
     *
     * @param INSURANCE_COMP_CODE the value for TRSADVANCE_INS_DEPRECIATION.INSURANCE_COMP_CODE
     */
    public void setINSURANCE_COMP_CODE(BigDecimal INSURANCE_COMP_CODE) {
        this.INSURANCE_COMP_CODE = INSURANCE_COMP_CODE;
    }
}