package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class TRSADVANCE_INS_CHARGES_DETVO extends TRSADVANCE_INS_CHARGES_DETVOKey {
    /**
     * This field corresponds to the database column TRSADVANCE_INS_CHARGES_DET.CHARGES_CODE
     */
    private BigDecimal CHARGES_CODE;

    /**
     * This field corresponds to the database column TRSADVANCE_INS_CHARGES_DET.CHARGES_INSFEE_AMOUNT
     */
    private BigDecimal CHARGES_INSFEE_AMOUNT;

    /**
     * This field corresponds to the database column TRSADVANCE_INS_CHARGES_DET.YEAR
     */
    private BigDecimal YEAR;

    /**
     * This field corresponds to the database column TRSADVANCE_INS_CHARGES_DET.NET_PREMIUM_YN
     */
    private String NET_PREMIUM_YN;

    /**
     * This field corresponds to the database column TRSADVANCE_INS_CHARGES_DET.NET_PREMIUM_PERC
     */
    private BigDecimal NET_PREMIUM_PERC;

    /**
     * This field corresponds to the database column TRSADVANCE_INS_CHARGES_DET.CHARGES_REVERSED_AMOUNT
     */
    private BigDecimal CHARGES_REVERSED_AMOUNT;

    /**
     * This field corresponds to the database column TRSADVANCE_INS_CHARGES_DET.INSURANCE_COMP_CODE
     */
    private BigDecimal INSURANCE_COMP_CODE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSADVANCE_INS_CHARGES_DET.CHARGES_CODE
     *
     * @return the value of TRSADVANCE_INS_CHARGES_DET.CHARGES_CODE
     */
    public BigDecimal getCHARGES_CODE() {
        return CHARGES_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSADVANCE_INS_CHARGES_DET.CHARGES_CODE
     *
     * @param CHARGES_CODE the value for TRSADVANCE_INS_CHARGES_DET.CHARGES_CODE
     */
    public void setCHARGES_CODE(BigDecimal CHARGES_CODE) {
        this.CHARGES_CODE = CHARGES_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSADVANCE_INS_CHARGES_DET.CHARGES_INSFEE_AMOUNT
     *
     * @return the value of TRSADVANCE_INS_CHARGES_DET.CHARGES_INSFEE_AMOUNT
     */
    public BigDecimal getCHARGES_INSFEE_AMOUNT() {
        return CHARGES_INSFEE_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSADVANCE_INS_CHARGES_DET.CHARGES_INSFEE_AMOUNT
     *
     * @param CHARGES_INSFEE_AMOUNT the value for TRSADVANCE_INS_CHARGES_DET.CHARGES_INSFEE_AMOUNT
     */
    public void setCHARGES_INSFEE_AMOUNT(BigDecimal CHARGES_INSFEE_AMOUNT) {
        this.CHARGES_INSFEE_AMOUNT = CHARGES_INSFEE_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSADVANCE_INS_CHARGES_DET.YEAR
     *
     * @return the value of TRSADVANCE_INS_CHARGES_DET.YEAR
     */
    public BigDecimal getYEAR() {
        return YEAR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSADVANCE_INS_CHARGES_DET.YEAR
     *
     * @param YEAR the value for TRSADVANCE_INS_CHARGES_DET.YEAR
     */
    public void setYEAR(BigDecimal YEAR) {
        this.YEAR = YEAR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSADVANCE_INS_CHARGES_DET.NET_PREMIUM_YN
     *
     * @return the value of TRSADVANCE_INS_CHARGES_DET.NET_PREMIUM_YN
     */
    public String getNET_PREMIUM_YN() {
        return NET_PREMIUM_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSADVANCE_INS_CHARGES_DET.NET_PREMIUM_YN
     *
     * @param NET_PREMIUM_YN the value for TRSADVANCE_INS_CHARGES_DET.NET_PREMIUM_YN
     */
    public void setNET_PREMIUM_YN(String NET_PREMIUM_YN) {
        this.NET_PREMIUM_YN = NET_PREMIUM_YN == null ? null : NET_PREMIUM_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSADVANCE_INS_CHARGES_DET.NET_PREMIUM_PERC
     *
     * @return the value of TRSADVANCE_INS_CHARGES_DET.NET_PREMIUM_PERC
     */
    public BigDecimal getNET_PREMIUM_PERC() {
        return NET_PREMIUM_PERC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSADVANCE_INS_CHARGES_DET.NET_PREMIUM_PERC
     *
     * @param NET_PREMIUM_PERC the value for TRSADVANCE_INS_CHARGES_DET.NET_PREMIUM_PERC
     */
    public void setNET_PREMIUM_PERC(BigDecimal NET_PREMIUM_PERC) {
        this.NET_PREMIUM_PERC = NET_PREMIUM_PERC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSADVANCE_INS_CHARGES_DET.CHARGES_REVERSED_AMOUNT
     *
     * @return the value of TRSADVANCE_INS_CHARGES_DET.CHARGES_REVERSED_AMOUNT
     */
    public BigDecimal getCHARGES_REVERSED_AMOUNT() {
        return CHARGES_REVERSED_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSADVANCE_INS_CHARGES_DET.CHARGES_REVERSED_AMOUNT
     *
     * @param CHARGES_REVERSED_AMOUNT the value for TRSADVANCE_INS_CHARGES_DET.CHARGES_REVERSED_AMOUNT
     */
    public void setCHARGES_REVERSED_AMOUNT(BigDecimal CHARGES_REVERSED_AMOUNT) {
        this.CHARGES_REVERSED_AMOUNT = CHARGES_REVERSED_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSADVANCE_INS_CHARGES_DET.INSURANCE_COMP_CODE
     *
     * @return the value of TRSADVANCE_INS_CHARGES_DET.INSURANCE_COMP_CODE
     */
    public BigDecimal getINSURANCE_COMP_CODE() {
        return INSURANCE_COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSADVANCE_INS_CHARGES_DET.INSURANCE_COMP_CODE
     *
     * @param INSURANCE_COMP_CODE the value for TRSADVANCE_INS_CHARGES_DET.INSURANCE_COMP_CODE
     */
    public void setINSURANCE_COMP_CODE(BigDecimal INSURANCE_COMP_CODE) {
        this.INSURANCE_COMP_CODE = INSURANCE_COMP_CODE;
    }
}