package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class TRSADVANCE_INS_DEPRECIATIONVOKey extends BaseVO {
    /**
     * This field corresponds to the database column TRSADVANCE_INS_DEPRECIATION.ADVANCE_INSURANCE_SERIAL_NO
     */
    private BigDecimal ADVANCE_INSURANCE_SERIAL_NO;

    /**
     * This field corresponds to the database column TRSADVANCE_INS_DEPRECIATION.BRANCH_CODE
     */
    private BigDecimal BRANCH_CODE;

    /**
     * This field corresponds to the database column TRSADVANCE_INS_DEPRECIATION.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column TRSADVANCE_INS_DEPRECIATION.LINE_NBR
     */

    private BigDecimal LINE_NBR;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSADVANCE_INS_DEPRECIATION.ADVANCE_INSURANCE_SERIAL_NO
     *
     * @return the value of TRSADVANCE_INS_DEPRECIATION.ADVANCE_INSURANCE_SERIAL_NO
     */
    public BigDecimal getADVANCE_INSURANCE_SERIAL_NO() {
        return ADVANCE_INSURANCE_SERIAL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSADVANCE_INS_DEPRECIATION.ADVANCE_INSURANCE_SERIAL_NO
     *
     * @param ADVANCE_INSURANCE_SERIAL_NO the value for TRSADVANCE_INS_DEPRECIATION.ADVANCE_INSURANCE_SERIAL_NO
     */
    public void setADVANCE_INSURANCE_SERIAL_NO(BigDecimal ADVANCE_INSURANCE_SERIAL_NO) {
        this.ADVANCE_INSURANCE_SERIAL_NO = ADVANCE_INSURANCE_SERIAL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSADVANCE_INS_DEPRECIATION.BRANCH_CODE
     *
     * @return the value of TRSADVANCE_INS_DEPRECIATION.BRANCH_CODE
     */
    public BigDecimal getBRANCH_CODE() {
        return BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSADVANCE_INS_DEPRECIATION.BRANCH_CODE
     *
     * @param BRANCH_CODE the value for TRSADVANCE_INS_DEPRECIATION.BRANCH_CODE
     */
    public void setBRANCH_CODE(BigDecimal BRANCH_CODE) {
        this.BRANCH_CODE = BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSADVANCE_INS_DEPRECIATION.COMP_CODE
     *
     * @return the value of TRSADVANCE_INS_DEPRECIATION.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSADVANCE_INS_DEPRECIATION.COMP_CODE
     *
     * @param COMP_CODE the value for TRSADVANCE_INS_DEPRECIATION.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSADVANCE_INS_DEPRECIATION.LINE_NBR
     *
     * @return the value of TRSADVANCE_INS_DEPRECIATION.LINE_NBR
     */
    public BigDecimal getLINE_NBR() {
        return LINE_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSADVANCE_INS_DEPRECIATION.LINE_NBR
     *
     * @param LINE_NBR the value for TRSADVANCE_INS_DEPRECIATION.LINE_NBR
     */
    public void setLINE_NBR(BigDecimal LINE_NBR) {
        this.LINE_NBR = LINE_NBR;
    }
}