package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;
import java.util.Date;

public class TRSCIFCOUNTRYLIMIT_TRX_DETVO extends BaseVO {
    /**
     * This field corresponds to the database column TRSCIFCOUNTRYLIMIT_TRX_DET.APP_NAME
     */
    private String APP_NAME;

    /**
     * This field corresponds to the database column TRSCIFCOUNTRYLIMIT_TRX_DET.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column TRSCIFCOUNTRYLIMIT_TRX_DET.COUNTRY
     */
    private BigDecimal COUNTRY;

    /**
     * This field corresponds to the database column TRSCIFCOUNTRYLIMIT_TRX_DET.LINE_NBR
     */
    private BigDecimal LINE_NBR;

    /**
     * This field corresponds to the database column TRSCIFCOUNTRYLIMIT_TRX_DET.TRS_BRANCH
     */
    private BigDecimal TRS_BRANCH;

    /**
     * This field corresponds to the database column TRSCIFCOUNTRYLIMIT_TRX_DET.TRS_NBR
     */
    private BigDecimal TRS_NBR;

    /**
     * This field corresponds to the database column TRSCIFCOUNTRYLIMIT_TRX_DET.TRS_TYPE
     */
    private String TRS_TYPE;

    /**
     * This field corresponds to the database column TRSCIFCOUNTRYLIMIT_TRX_DET.TRS_DATE
     */
    private Date TRS_DATE;

    /**
     * This field corresponds to the database column TRSCIFCOUNTRYLIMIT_TRX_DET.AMOUNT_IN_TRS_CY
     */
    private BigDecimal AMOUNT_IN_TRS_CY;

    /**
     * This field corresponds to the database column TRSCIFCOUNTRYLIMIT_TRX_DET.CROSS_RATE
     */
    private BigDecimal CROSS_RATE;

    /**
     * This field corresponds to the database column TRSCIFCOUNTRYLIMIT_TRX_DET.AMOUNT_IN_LIMIT_CY
     */
    private BigDecimal AMOUNT_IN_LIMIT_CY;

    /**
     * This field corresponds to the database column TRSCIFCOUNTRYLIMIT_TRX_DET.LIMIT_EXCEED_AMOUNT
     */
    private BigDecimal LIMIT_EXCEED_AMOUNT;

    /**
     * This field corresponds to the database column TRSCIFCOUNTRYLIMIT_TRX_DET.EXEMPTED_CIF_YN
     */
    private String EXEMPTED_CIF_YN;

    /**
     * This field corresponds to the database column TRSCIFCOUNTRYLIMIT_TRX_DET.SERVER_DATE
     */
    private Date SERVER_DATE;

    /**
     * This field corresponds to the database column TRSCIFCOUNTRYLIMIT_TRX_DET.ACTION_TYPE
     */
    private String ACTION_TYPE;

    /**
     * This field corresponds to the database column TRSCIFCOUNTRYLIMIT_TRX_DET.CIF_NO
     */
    private BigDecimal CIF_NO;

    /**
     * This field corresponds to the database column TRSCIFCOUNTRYLIMIT_TRX_DET.DEAL_NO
     */
    private BigDecimal DEAL_NO;

    /**
     * This field corresponds to the database column TRSCIFCOUNTRYLIMIT_TRX_DET.USER_ID
     */
    private String USER_ID;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCIFCOUNTRYLIMIT_TRX_DET.APP_NAME
     *
     * @return the value of TRSCIFCOUNTRYLIMIT_TRX_DET.APP_NAME
     */
    public String getAPP_NAME() {
        return APP_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCIFCOUNTRYLIMIT_TRX_DET.APP_NAME
     *
     * @param APP_NAME the value for TRSCIFCOUNTRYLIMIT_TRX_DET.APP_NAME
     */
    public void setAPP_NAME(String APP_NAME) {
        this.APP_NAME = APP_NAME == null ? null : APP_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCIFCOUNTRYLIMIT_TRX_DET.COMP_CODE
     *
     * @return the value of TRSCIFCOUNTRYLIMIT_TRX_DET.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCIFCOUNTRYLIMIT_TRX_DET.COMP_CODE
     *
     * @param COMP_CODE the value for TRSCIFCOUNTRYLIMIT_TRX_DET.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCIFCOUNTRYLIMIT_TRX_DET.COUNTRY
     *
     * @return the value of TRSCIFCOUNTRYLIMIT_TRX_DET.COUNTRY
     */
    public BigDecimal getCOUNTRY() {
        return COUNTRY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCIFCOUNTRYLIMIT_TRX_DET.COUNTRY
     *
     * @param COUNTRY the value for TRSCIFCOUNTRYLIMIT_TRX_DET.COUNTRY
     */
    public void setCOUNTRY(BigDecimal COUNTRY) {
        this.COUNTRY = COUNTRY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCIFCOUNTRYLIMIT_TRX_DET.LINE_NBR
     *
     * @return the value of TRSCIFCOUNTRYLIMIT_TRX_DET.LINE_NBR
     */
    public BigDecimal getLINE_NBR() {
        return LINE_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCIFCOUNTRYLIMIT_TRX_DET.LINE_NBR
     *
     * @param LINE_NBR the value for TRSCIFCOUNTRYLIMIT_TRX_DET.LINE_NBR
     */
    public void setLINE_NBR(BigDecimal LINE_NBR) {
        this.LINE_NBR = LINE_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCIFCOUNTRYLIMIT_TRX_DET.TRS_BRANCH
     *
     * @return the value of TRSCIFCOUNTRYLIMIT_TRX_DET.TRS_BRANCH
     */
    public BigDecimal getTRS_BRANCH() {
        return TRS_BRANCH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCIFCOUNTRYLIMIT_TRX_DET.TRS_BRANCH
     *
     * @param TRS_BRANCH the value for TRSCIFCOUNTRYLIMIT_TRX_DET.TRS_BRANCH
     */
    public void setTRS_BRANCH(BigDecimal TRS_BRANCH) {
        this.TRS_BRANCH = TRS_BRANCH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCIFCOUNTRYLIMIT_TRX_DET.TRS_NBR
     *
     * @return the value of TRSCIFCOUNTRYLIMIT_TRX_DET.TRS_NBR
     */
    public BigDecimal getTRS_NBR() {
        return TRS_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCIFCOUNTRYLIMIT_TRX_DET.TRS_NBR
     *
     * @param TRS_NBR the value for TRSCIFCOUNTRYLIMIT_TRX_DET.TRS_NBR
     */
    public void setTRS_NBR(BigDecimal TRS_NBR) {
        this.TRS_NBR = TRS_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCIFCOUNTRYLIMIT_TRX_DET.TRS_TYPE
     *
     * @return the value of TRSCIFCOUNTRYLIMIT_TRX_DET.TRS_TYPE
     */
    public String getTRS_TYPE() {
        return TRS_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCIFCOUNTRYLIMIT_TRX_DET.TRS_TYPE
     *
     * @param TRS_TYPE the value for TRSCIFCOUNTRYLIMIT_TRX_DET.TRS_TYPE
     */
    public void setTRS_TYPE(String TRS_TYPE) {
        this.TRS_TYPE = TRS_TYPE == null ? null : TRS_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCIFCOUNTRYLIMIT_TRX_DET.TRS_DATE
     *
     * @return the value of TRSCIFCOUNTRYLIMIT_TRX_DET.TRS_DATE
     */
    public Date getTRS_DATE() {
        return TRS_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCIFCOUNTRYLIMIT_TRX_DET.TRS_DATE
     *
     * @param TRS_DATE the value for TRSCIFCOUNTRYLIMIT_TRX_DET.TRS_DATE
     */
    public void setTRS_DATE(Date TRS_DATE) {
        this.TRS_DATE = TRS_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCIFCOUNTRYLIMIT_TRX_DET.AMOUNT_IN_TRS_CY
     *
     * @return the value of TRSCIFCOUNTRYLIMIT_TRX_DET.AMOUNT_IN_TRS_CY
     */
    public BigDecimal getAMOUNT_IN_TRS_CY() {
        return AMOUNT_IN_TRS_CY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCIFCOUNTRYLIMIT_TRX_DET.AMOUNT_IN_TRS_CY
     *
     * @param AMOUNT_IN_TRS_CY the value for TRSCIFCOUNTRYLIMIT_TRX_DET.AMOUNT_IN_TRS_CY
     */
    public void setAMOUNT_IN_TRS_CY(BigDecimal AMOUNT_IN_TRS_CY) {
        this.AMOUNT_IN_TRS_CY = AMOUNT_IN_TRS_CY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCIFCOUNTRYLIMIT_TRX_DET.CROSS_RATE
     *
     * @return the value of TRSCIFCOUNTRYLIMIT_TRX_DET.CROSS_RATE
     */
    public BigDecimal getCROSS_RATE() {
        return CROSS_RATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCIFCOUNTRYLIMIT_TRX_DET.CROSS_RATE
     *
     * @param CROSS_RATE the value for TRSCIFCOUNTRYLIMIT_TRX_DET.CROSS_RATE
     */
    public void setCROSS_RATE(BigDecimal CROSS_RATE) {
        this.CROSS_RATE = CROSS_RATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCIFCOUNTRYLIMIT_TRX_DET.AMOUNT_IN_LIMIT_CY
     *
     * @return the value of TRSCIFCOUNTRYLIMIT_TRX_DET.AMOUNT_IN_LIMIT_CY
     */
    public BigDecimal getAMOUNT_IN_LIMIT_CY() {
        return AMOUNT_IN_LIMIT_CY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCIFCOUNTRYLIMIT_TRX_DET.AMOUNT_IN_LIMIT_CY
     *
     * @param AMOUNT_IN_LIMIT_CY the value for TRSCIFCOUNTRYLIMIT_TRX_DET.AMOUNT_IN_LIMIT_CY
     */
    public void setAMOUNT_IN_LIMIT_CY(BigDecimal AMOUNT_IN_LIMIT_CY) {
        this.AMOUNT_IN_LIMIT_CY = AMOUNT_IN_LIMIT_CY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCIFCOUNTRYLIMIT_TRX_DET.LIMIT_EXCEED_AMOUNT
     *
     * @return the value of TRSCIFCOUNTRYLIMIT_TRX_DET.LIMIT_EXCEED_AMOUNT
     */
    public BigDecimal getLIMIT_EXCEED_AMOUNT() {
        return LIMIT_EXCEED_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCIFCOUNTRYLIMIT_TRX_DET.LIMIT_EXCEED_AMOUNT
     *
     * @param LIMIT_EXCEED_AMOUNT the value for TRSCIFCOUNTRYLIMIT_TRX_DET.LIMIT_EXCEED_AMOUNT
     */
    public void setLIMIT_EXCEED_AMOUNT(BigDecimal LIMIT_EXCEED_AMOUNT) {
        this.LIMIT_EXCEED_AMOUNT = LIMIT_EXCEED_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCIFCOUNTRYLIMIT_TRX_DET.EXEMPTED_CIF_YN
     *
     * @return the value of TRSCIFCOUNTRYLIMIT_TRX_DET.EXEMPTED_CIF_YN
     */
    public String getEXEMPTED_CIF_YN() {
        return EXEMPTED_CIF_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCIFCOUNTRYLIMIT_TRX_DET.EXEMPTED_CIF_YN
     *
     * @param EXEMPTED_CIF_YN the value for TRSCIFCOUNTRYLIMIT_TRX_DET.EXEMPTED_CIF_YN
     */
    public void setEXEMPTED_CIF_YN(String EXEMPTED_CIF_YN) {
        this.EXEMPTED_CIF_YN = EXEMPTED_CIF_YN == null ? null : EXEMPTED_CIF_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCIFCOUNTRYLIMIT_TRX_DET.SERVER_DATE
     *
     * @return the value of TRSCIFCOUNTRYLIMIT_TRX_DET.SERVER_DATE
     */
    public Date getSERVER_DATE() {
        return SERVER_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCIFCOUNTRYLIMIT_TRX_DET.SERVER_DATE
     *
     * @param SERVER_DATE the value for TRSCIFCOUNTRYLIMIT_TRX_DET.SERVER_DATE
     */
    public void setSERVER_DATE(Date SERVER_DATE) {
        this.SERVER_DATE = SERVER_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCIFCOUNTRYLIMIT_TRX_DET.ACTION_TYPE
     *
     * @return the value of TRSCIFCOUNTRYLIMIT_TRX_DET.ACTION_TYPE
     */
    public String getACTION_TYPE() {
        return ACTION_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCIFCOUNTRYLIMIT_TRX_DET.ACTION_TYPE
     *
     * @param ACTION_TYPE the value for TRSCIFCOUNTRYLIMIT_TRX_DET.ACTION_TYPE
     */
    public void setACTION_TYPE(String ACTION_TYPE) {
        this.ACTION_TYPE = ACTION_TYPE == null ? null : ACTION_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCIFCOUNTRYLIMIT_TRX_DET.CIF_NO
     *
     * @return the value of TRSCIFCOUNTRYLIMIT_TRX_DET.CIF_NO
     */
    public BigDecimal getCIF_NO() {
        return CIF_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCIFCOUNTRYLIMIT_TRX_DET.CIF_NO
     *
     * @param CIF_NO the value for TRSCIFCOUNTRYLIMIT_TRX_DET.CIF_NO
     */
    public void setCIF_NO(BigDecimal CIF_NO) {
        this.CIF_NO = CIF_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCIFCOUNTRYLIMIT_TRX_DET.DEAL_NO
     *
     * @return the value of TRSCIFCOUNTRYLIMIT_TRX_DET.DEAL_NO
     */
    public BigDecimal getDEAL_NO() {
        return DEAL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCIFCOUNTRYLIMIT_TRX_DET.DEAL_NO
     *
     * @param DEAL_NO the value for TRSCIFCOUNTRYLIMIT_TRX_DET.DEAL_NO
     */
    public void setDEAL_NO(BigDecimal DEAL_NO) {
        this.DEAL_NO = DEAL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCIFCOUNTRYLIMIT_TRX_DET.USER_ID
     *
     * @return the value of TRSCIFCOUNTRYLIMIT_TRX_DET.USER_ID
     */
    public String getUSER_ID() {
        return USER_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCIFCOUNTRYLIMIT_TRX_DET.USER_ID
     *
     * @param USER_ID the value for TRSCIFCOUNTRYLIMIT_TRX_DET.USER_ID
     */
    public void setUSER_ID(String USER_ID) {
        this.USER_ID = USER_ID == null ? null : USER_ID.trim();
    }
}