package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class TRSCLASS_PROVISION_ACCOUNTSVOKey extends BaseVO {
    /**
     * This field corresponds to the database column TRSCLASS_PROVISION_ACCOUNTS.CATEGORY_CODE
     */
    private BigDecimal CATEGORY_CODE;

    /**
     * This field corresponds to the database column TRSCLASS_PROVISION_ACCOUNTS.CLASS
     */
    private BigDecimal CLASS;

    /**
     * This field corresponds to the database column TRSCLASS_PROVISION_ACCOUNTS.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCLASS_PROVISION_ACCOUNTS.CATEGORY_CODE
     *
     * @return the value of TRSCLASS_PROVISION_ACCOUNTS.CATEGORY_CODE
     */
    public BigDecimal getCATEGORY_CODE() {
        return CATEGORY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCLASS_PROVISION_ACCOUNTS.CATEGORY_CODE
     *
     * @param CATEGORY_CODE the value for TRSCLASS_PROVISION_ACCOUNTS.CATEGORY_CODE
     */
    public void setCATEGORY_CODE(BigDecimal CATEGORY_CODE) {
        this.CATEGORY_CODE = CATEGORY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCLASS_PROVISION_ACCOUNTS.CLASS
     *
     * @return the value of TRSCLASS_PROVISION_ACCOUNTS.CLASS
     */
    public BigDecimal getCLASS() {
        return CLASS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCLASS_PROVISION_ACCOUNTS.CLASS
     *
     * @param CLASS the value for TRSCLASS_PROVISION_ACCOUNTS.CLASS
     */
    public void setCLASS(BigDecimal CLASS) {
        this.CLASS = CLASS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCLASS_PROVISION_ACCOUNTS.COMP_CODE
     *
     * @return the value of TRSCLASS_PROVISION_ACCOUNTS.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCLASS_PROVISION_ACCOUNTS.COMP_CODE
     *
     * @param COMP_CODE the value for TRSCLASS_PROVISION_ACCOUNTS.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }
}