package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class TRSCIFLIMIT_CHARGES_DETVO extends TRSCIFLIMIT_CHARGES_DETVOKey {
    /**
     * This field corresponds to the database column TRSCIFLIMIT_CHARGES_DET.CHARGE_LINK
     */
    private BigDecimal CHARGE_LINK;

    /**
     * This field corresponds to the database column TRSCIFLIMIT_CHARGES_DET.CHARGE_CODE
     */
    private BigDecimal CHARGE_CODE;

    /**
     * This field corresponds to the database column TRSCIFLIMIT_CHARGES_DET.ACC_BRANCH_CODE
     */
    private BigDecimal ACC_BRANCH_CODE;

    /**
     * This field corresponds to the database column TRSCIFLIMIT_CHARGES_DET.ACC_CY
     */
    private BigDecimal ACC_CY;

    /**
     * This field corresponds to the database column TRSCIFLIMIT_CHARGES_DET.ACC_GL
     */
    private BigDecimal ACC_GL;

    /**
     * This field corresponds to the database column TRSCIFLIMIT_CHARGES_DET.ACC_CIF
     */
    private BigDecimal ACC_CIF;

    /**
     * This field corresponds to the database column TRSCIFLIMIT_CHARGES_DET.ACC_SL
     */
    private BigDecimal ACC_SL;

    /**
     * This field corresponds to the database column TRSCIFLIMIT_CHARGES_DET.CHARGES_AMOUNT
     */
    private BigDecimal CHARGES_AMOUNT;

    /**
     * This field corresponds to the database column TRSCIFLIMIT_CHARGES_DET.ACCOUNT_POSTED_YN
     */
    private String ACCOUNT_POSTED_YN;

    /**
     * This field corresponds to the database column TRSCIFLIMIT_CHARGES_DET.COLLATERAL_NO
     */
    private BigDecimal COLLATERAL_NO;

    /**
     * This field corresponds to the database column TRSCIFLIMIT_CHARGES_DET.GROUP_ID
     */
    private BigDecimal GROUP_ID;

    /**
     * This field corresponds to the database column TRSCIFLIMIT_CHARGES_DET.CHARGES_FOR
     */
    private String CHARGES_FOR;

    /**
     * This field corresponds to the database column TRSCIFLIMIT_CHARGES_DET.CHARGES_REVERSED_AMOUNT
     */
    private BigDecimal CHARGES_REVERSED_AMOUNT;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCIFLIMIT_CHARGES_DET.CHARGE_LINK
     *
     * @return the value of TRSCIFLIMIT_CHARGES_DET.CHARGE_LINK
     */
    public BigDecimal getCHARGE_LINK() {
        return CHARGE_LINK;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCIFLIMIT_CHARGES_DET.CHARGE_LINK
     *
     * @param CHARGE_LINK the value for TRSCIFLIMIT_CHARGES_DET.CHARGE_LINK
     */
    public void setCHARGE_LINK(BigDecimal CHARGE_LINK) {
        this.CHARGE_LINK = CHARGE_LINK;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCIFLIMIT_CHARGES_DET.CHARGE_CODE
     *
     * @return the value of TRSCIFLIMIT_CHARGES_DET.CHARGE_CODE
     */
    public BigDecimal getCHARGE_CODE() {
        return CHARGE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCIFLIMIT_CHARGES_DET.CHARGE_CODE
     *
     * @param CHARGE_CODE the value for TRSCIFLIMIT_CHARGES_DET.CHARGE_CODE
     */
    public void setCHARGE_CODE(BigDecimal CHARGE_CODE) {
        this.CHARGE_CODE = CHARGE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCIFLIMIT_CHARGES_DET.ACC_BRANCH_CODE
     *
     * @return the value of TRSCIFLIMIT_CHARGES_DET.ACC_BRANCH_CODE
     */
    public BigDecimal getACC_BRANCH_CODE() {
        return ACC_BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCIFLIMIT_CHARGES_DET.ACC_BRANCH_CODE
     *
     * @param ACC_BRANCH_CODE the value for TRSCIFLIMIT_CHARGES_DET.ACC_BRANCH_CODE
     */
    public void setACC_BRANCH_CODE(BigDecimal ACC_BRANCH_CODE) {
        this.ACC_BRANCH_CODE = ACC_BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCIFLIMIT_CHARGES_DET.ACC_CY
     *
     * @return the value of TRSCIFLIMIT_CHARGES_DET.ACC_CY
     */
    public BigDecimal getACC_CY() {
        return ACC_CY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCIFLIMIT_CHARGES_DET.ACC_CY
     *
     * @param ACC_CY the value for TRSCIFLIMIT_CHARGES_DET.ACC_CY
     */
    public void setACC_CY(BigDecimal ACC_CY) {
        this.ACC_CY = ACC_CY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCIFLIMIT_CHARGES_DET.ACC_GL
     *
     * @return the value of TRSCIFLIMIT_CHARGES_DET.ACC_GL
     */
    public BigDecimal getACC_GL() {
        return ACC_GL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCIFLIMIT_CHARGES_DET.ACC_GL
     *
     * @param ACC_GL the value for TRSCIFLIMIT_CHARGES_DET.ACC_GL
     */
    public void setACC_GL(BigDecimal ACC_GL) {
        this.ACC_GL = ACC_GL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCIFLIMIT_CHARGES_DET.ACC_CIF
     *
     * @return the value of TRSCIFLIMIT_CHARGES_DET.ACC_CIF
     */
    public BigDecimal getACC_CIF() {
        return ACC_CIF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCIFLIMIT_CHARGES_DET.ACC_CIF
     *
     * @param ACC_CIF the value for TRSCIFLIMIT_CHARGES_DET.ACC_CIF
     */
    public void setACC_CIF(BigDecimal ACC_CIF) {
        this.ACC_CIF = ACC_CIF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCIFLIMIT_CHARGES_DET.ACC_SL
     *
     * @return the value of TRSCIFLIMIT_CHARGES_DET.ACC_SL
     */
    public BigDecimal getACC_SL() {
        return ACC_SL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCIFLIMIT_CHARGES_DET.ACC_SL
     *
     * @param ACC_SL the value for TRSCIFLIMIT_CHARGES_DET.ACC_SL
     */
    public void setACC_SL(BigDecimal ACC_SL) {
        this.ACC_SL = ACC_SL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCIFLIMIT_CHARGES_DET.CHARGES_AMOUNT
     *
     * @return the value of TRSCIFLIMIT_CHARGES_DET.CHARGES_AMOUNT
     */
    public BigDecimal getCHARGES_AMOUNT() {
        return CHARGES_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCIFLIMIT_CHARGES_DET.CHARGES_AMOUNT
     *
     * @param CHARGES_AMOUNT the value for TRSCIFLIMIT_CHARGES_DET.CHARGES_AMOUNT
     */
    public void setCHARGES_AMOUNT(BigDecimal CHARGES_AMOUNT) {
        this.CHARGES_AMOUNT = CHARGES_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCIFLIMIT_CHARGES_DET.ACCOUNT_POSTED_YN
     *
     * @return the value of TRSCIFLIMIT_CHARGES_DET.ACCOUNT_POSTED_YN
     */
    public String getACCOUNT_POSTED_YN() {
        return ACCOUNT_POSTED_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCIFLIMIT_CHARGES_DET.ACCOUNT_POSTED_YN
     *
     * @param ACCOUNT_POSTED_YN the value for TRSCIFLIMIT_CHARGES_DET.ACCOUNT_POSTED_YN
     */
    public void setACCOUNT_POSTED_YN(String ACCOUNT_POSTED_YN) {
        this.ACCOUNT_POSTED_YN = ACCOUNT_POSTED_YN == null ? null : ACCOUNT_POSTED_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCIFLIMIT_CHARGES_DET.COLLATERAL_NO
     *
     * @return the value of TRSCIFLIMIT_CHARGES_DET.COLLATERAL_NO
     */
    public BigDecimal getCOLLATERAL_NO() {
        return COLLATERAL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCIFLIMIT_CHARGES_DET.COLLATERAL_NO
     *
     * @param COLLATERAL_NO the value for TRSCIFLIMIT_CHARGES_DET.COLLATERAL_NO
     */
    public void setCOLLATERAL_NO(BigDecimal COLLATERAL_NO) {
        this.COLLATERAL_NO = COLLATERAL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCIFLIMIT_CHARGES_DET.GROUP_ID
     *
     * @return the value of TRSCIFLIMIT_CHARGES_DET.GROUP_ID
     */
    public BigDecimal getGROUP_ID() {
        return GROUP_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCIFLIMIT_CHARGES_DET.GROUP_ID
     *
     * @param GROUP_ID the value for TRSCIFLIMIT_CHARGES_DET.GROUP_ID
     */
    public void setGROUP_ID(BigDecimal GROUP_ID) {
        this.GROUP_ID = GROUP_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCIFLIMIT_CHARGES_DET.CHARGES_FOR
     *
     * @return the value of TRSCIFLIMIT_CHARGES_DET.CHARGES_FOR
     */
    public String getCHARGES_FOR() {
        return CHARGES_FOR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCIFLIMIT_CHARGES_DET.CHARGES_FOR
     *
     * @param CHARGES_FOR the value for TRSCIFLIMIT_CHARGES_DET.CHARGES_FOR
     */
    public void setCHARGES_FOR(String CHARGES_FOR) {
        this.CHARGES_FOR = CHARGES_FOR == null ? null : CHARGES_FOR.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCIFLIMIT_CHARGES_DET.CHARGES_REVERSED_AMOUNT
     *
     * @return the value of TRSCIFLIMIT_CHARGES_DET.CHARGES_REVERSED_AMOUNT
     */
    public BigDecimal getCHARGES_REVERSED_AMOUNT() {
        return CHARGES_REVERSED_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCIFLIMIT_CHARGES_DET.CHARGES_REVERSED_AMOUNT
     *
     * @param CHARGES_REVERSED_AMOUNT the value for TRSCIFLIMIT_CHARGES_DET.CHARGES_REVERSED_AMOUNT
     */
    public void setCHARGES_REVERSED_AMOUNT(BigDecimal CHARGES_REVERSED_AMOUNT) {
        this.CHARGES_REVERSED_AMOUNT = CHARGES_REVERSED_AMOUNT;
    }
}