package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class TRSCOLLATERALDET_DEAL_SWITCHVO extends TRSCOLLATERALDET_DEAL_SWITCHVOKey {
    /**
     * This field corresponds to the database column TRSCOLLATERALDET_DEAL_SWITCH.DEAL_NO
     */
    private BigDecimal DEAL_NO;

    /**
     * This field corresponds to the database column TRSCOLLATERALDET_DEAL_SWITCH.DEAL_ALLOCATED
     */
    private BigDecimal DEAL_ALLOCATED;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCOLLATERALDET_DEAL_SWITCH.DEAL_NO
     *
     * @return the value of TRSCOLLATERALDET_DEAL_SWITCH.DEAL_NO
     */
    public BigDecimal getDEAL_NO() {
        return DEAL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCOLLATERALDET_DEAL_SWITCH.DEAL_NO
     *
     * @param DEAL_NO the value for TRSCOLLATERALDET_DEAL_SWITCH.DEAL_NO
     */
    public void setDEAL_NO(BigDecimal DEAL_NO) {
        this.DEAL_NO = DEAL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCOLLATERALDET_DEAL_SWITCH.DEAL_ALLOCATED
     *
     * @return the value of TRSCOLLATERALDET_DEAL_SWITCH.DEAL_ALLOCATED
     */
    public BigDecimal getDEAL_ALLOCATED() {
        return DEAL_ALLOCATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCOLLATERALDET_DEAL_SWITCH.DEAL_ALLOCATED
     *
     * @param DEAL_ALLOCATED the value for TRSCOLLATERALDET_DEAL_SWITCH.DEAL_ALLOCATED
     */
    public void setDEAL_ALLOCATED(BigDecimal DEAL_ALLOCATED) {
        this.DEAL_ALLOCATED = DEAL_ALLOCATED;
    }
}