package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class TRSCOLLATERAL_LINKCHARGESVO extends BaseVO {
    /**
     * This field corresponds to the database column TRSCOLLATERAL_LINKCHARGES.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column TRSCOLLATERAL_LINKCHARGES.BRANCH
     */
    private BigDecimal BRANCH;

    /**
     * This field corresponds to the database column TRSCOLLATERAL_LINKCHARGES.FMSCOLLATERAL_CODE
     */
    private BigDecimal FMSCOLLATERAL_CODE;

    /**
     * This field corresponds to the database column TRSCOLLATERAL_LINKCHARGES.CHARGE_CODE
     */
    private BigDecimal CHARGE_CODE;

    /**
     * This field corresponds to the database column TRSCOLLATERAL_LINKCHARGES.LINE_NO
     */
    private BigDecimal LINE_NO;

    /**
     * This field corresponds to the database column TRSCOLLATERAL_LINKCHARGES.TRSACCOUNT_ENTRY
     */
    private String TRSACCOUNT_ENTRY;

    /**
     * This field corresponds to the database column TRSCOLLATERAL_LINKCHARGES.REFUND_PERC
     */
    private BigDecimal REFUND_PERC;

    /**
     * This field corresponds to the database column TRSCOLLATERAL_LINKCHARGES.REFUND_AMOUNT
     */
    private BigDecimal REFUND_AMOUNT;

    /**
     * This field corresponds to the database column TRSCOLLATERAL_LINKCHARGES.AMOUNT
     */
    private BigDecimal AMOUNT;

    /**
     * This field corresponds to the database column TRSCOLLATERAL_LINKCHARGES.PERCENTAGE
     */
    private BigDecimal PERCENTAGE;

    /**
     * This field corresponds to the database column TRSCOLLATERAL_LINKCHARGES.CHARGES_REVERSED_AMOUNT
     */
    private BigDecimal CHARGES_REVERSED_AMOUNT;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCOLLATERAL_LINKCHARGES.COMP_CODE
     *
     * @return the value of TRSCOLLATERAL_LINKCHARGES.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCOLLATERAL_LINKCHARGES.COMP_CODE
     *
     * @param COMP_CODE the value for TRSCOLLATERAL_LINKCHARGES.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCOLLATERAL_LINKCHARGES.BRANCH
     *
     * @return the value of TRSCOLLATERAL_LINKCHARGES.BRANCH
     */
    public BigDecimal getBRANCH() {
        return BRANCH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCOLLATERAL_LINKCHARGES.BRANCH
     *
     * @param BRANCH the value for TRSCOLLATERAL_LINKCHARGES.BRANCH
     */
    public void setBRANCH(BigDecimal BRANCH) {
        this.BRANCH = BRANCH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCOLLATERAL_LINKCHARGES.FMSCOLLATERAL_CODE
     *
     * @return the value of TRSCOLLATERAL_LINKCHARGES.FMSCOLLATERAL_CODE
     */
    public BigDecimal getFMSCOLLATERAL_CODE() {
        return FMSCOLLATERAL_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCOLLATERAL_LINKCHARGES.FMSCOLLATERAL_CODE
     *
     * @param FMSCOLLATERAL_CODE the value for TRSCOLLATERAL_LINKCHARGES.FMSCOLLATERAL_CODE
     */
    public void setFMSCOLLATERAL_CODE(BigDecimal FMSCOLLATERAL_CODE) {
        this.FMSCOLLATERAL_CODE = FMSCOLLATERAL_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCOLLATERAL_LINKCHARGES.CHARGE_CODE
     *
     * @return the value of TRSCOLLATERAL_LINKCHARGES.CHARGE_CODE
     */
    public BigDecimal getCHARGE_CODE() {
        return CHARGE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCOLLATERAL_LINKCHARGES.CHARGE_CODE
     *
     * @param CHARGE_CODE the value for TRSCOLLATERAL_LINKCHARGES.CHARGE_CODE
     */
    public void setCHARGE_CODE(BigDecimal CHARGE_CODE) {
        this.CHARGE_CODE = CHARGE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCOLLATERAL_LINKCHARGES.LINE_NO
     *
     * @return the value of TRSCOLLATERAL_LINKCHARGES.LINE_NO
     */
    public BigDecimal getLINE_NO() {
        return LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCOLLATERAL_LINKCHARGES.LINE_NO
     *
     * @param LINE_NO the value for TRSCOLLATERAL_LINKCHARGES.LINE_NO
     */
    public void setLINE_NO(BigDecimal LINE_NO) {
        this.LINE_NO = LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCOLLATERAL_LINKCHARGES.TRSACCOUNT_ENTRY
     *
     * @return the value of TRSCOLLATERAL_LINKCHARGES.TRSACCOUNT_ENTRY
     */
    public String getTRSACCOUNT_ENTRY() {
        return TRSACCOUNT_ENTRY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCOLLATERAL_LINKCHARGES.TRSACCOUNT_ENTRY
     *
     * @param TRSACCOUNT_ENTRY the value for TRSCOLLATERAL_LINKCHARGES.TRSACCOUNT_ENTRY
     */
    public void setTRSACCOUNT_ENTRY(String TRSACCOUNT_ENTRY) {
        this.TRSACCOUNT_ENTRY = TRSACCOUNT_ENTRY == null ? null : TRSACCOUNT_ENTRY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCOLLATERAL_LINKCHARGES.REFUND_PERC
     *
     * @return the value of TRSCOLLATERAL_LINKCHARGES.REFUND_PERC
     */
    public BigDecimal getREFUND_PERC() {
        return REFUND_PERC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCOLLATERAL_LINKCHARGES.REFUND_PERC
     *
     * @param REFUND_PERC the value for TRSCOLLATERAL_LINKCHARGES.REFUND_PERC
     */
    public void setREFUND_PERC(BigDecimal REFUND_PERC) {
        this.REFUND_PERC = REFUND_PERC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCOLLATERAL_LINKCHARGES.REFUND_AMOUNT
     *
     * @return the value of TRSCOLLATERAL_LINKCHARGES.REFUND_AMOUNT
     */
    public BigDecimal getREFUND_AMOUNT() {
        return REFUND_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCOLLATERAL_LINKCHARGES.REFUND_AMOUNT
     *
     * @param REFUND_AMOUNT the value for TRSCOLLATERAL_LINKCHARGES.REFUND_AMOUNT
     */
    public void setREFUND_AMOUNT(BigDecimal REFUND_AMOUNT) {
        this.REFUND_AMOUNT = REFUND_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCOLLATERAL_LINKCHARGES.AMOUNT
     *
     * @return the value of TRSCOLLATERAL_LINKCHARGES.AMOUNT
     */
    public BigDecimal getAMOUNT() {
        return AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCOLLATERAL_LINKCHARGES.AMOUNT
     *
     * @param AMOUNT the value for TRSCOLLATERAL_LINKCHARGES.AMOUNT
     */
    public void setAMOUNT(BigDecimal AMOUNT) {
        this.AMOUNT = AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCOLLATERAL_LINKCHARGES.PERCENTAGE
     *
     * @return the value of TRSCOLLATERAL_LINKCHARGES.PERCENTAGE
     */
    public BigDecimal getPERCENTAGE() {
        return PERCENTAGE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCOLLATERAL_LINKCHARGES.PERCENTAGE
     *
     * @param PERCENTAGE the value for TRSCOLLATERAL_LINKCHARGES.PERCENTAGE
     */
    public void setPERCENTAGE(BigDecimal PERCENTAGE) {
        this.PERCENTAGE = PERCENTAGE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCOLLATERAL_LINKCHARGES.CHARGES_REVERSED_AMOUNT
     *
     * @return the value of TRSCOLLATERAL_LINKCHARGES.CHARGES_REVERSED_AMOUNT
     */
    public BigDecimal getCHARGES_REVERSED_AMOUNT() {
        return CHARGES_REVERSED_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCOLLATERAL_LINKCHARGES.CHARGES_REVERSED_AMOUNT
     *
     * @param CHARGES_REVERSED_AMOUNT the value for TRSCOLLATERAL_LINKCHARGES.CHARGES_REVERSED_AMOUNT
     */
    public void setCHARGES_REVERSED_AMOUNT(BigDecimal CHARGES_REVERSED_AMOUNT) {
        this.CHARGES_REVERSED_AMOUNT = CHARGES_REVERSED_AMOUNT;
    }
}