package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;
import java.util.Date;

public class TRSCIFCOUNTRYLIMITVO extends BaseVO {
    /**
     * This field corresponds to the database column TRSCIFCOUNTRYLIMIT.BRANCH_CODE
     */
    private BigDecimal BRANCH_CODE;

    /**
     * This field corresponds to the database column TRSCIFCOUNTRYLIMIT.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column TRSCIFCOUNTRYLIMIT.COUNTRY
     */
    private BigDecimal COUNTRY;

    /**
     * This field corresponds to the database column TRSCIFCOUNTRYLIMIT.CURRENCY_CODE
     */
    private BigDecimal CURRENCY_CODE;

    /**
     * This field corresponds to the database column TRSCIFCOUNTRYLIMIT.LIMIT
     */
    private BigDecimal LIMIT;

    /**
     * This field corresponds to the database column TRSCIFCOUNTRYLIMIT.STATUS
     */
    private String STATUS;

    /**
     * This field corresponds to the database column TRSCIFCOUNTRYLIMIT.CREATED_BY
     */
    private String CREATED_BY;

    /**
     * This field corresponds to the database column TRSCIFCOUNTRYLIMIT.DATE_CREATED
     */
    private Date DATE_CREATED;

    /**
     * This field corresponds to the database column TRSCIFCOUNTRYLIMIT.MODIFIED_BY
     */
    private String MODIFIED_BY;

    /**
     * This field corresponds to the database column TRSCIFCOUNTRYLIMIT.DATE_MODIFIED
     */
    private Date DATE_MODIFIED;

    /**
     * This field corresponds to the database column TRSCIFCOUNTRYLIMIT.APPROVED1_BY
     */
    private String APPROVED1_BY;

    /**
     * This field corresponds to the database column TRSCIFCOUNTRYLIMIT.DATE_APPROVED1
     */
    private Date DATE_APPROVED1;

    /**
     * This field corresponds to the database column TRSCIFCOUNTRYLIMIT.APPROVED2_BY
     */
    private String APPROVED2_BY;

    /**
     * This field corresponds to the database column TRSCIFCOUNTRYLIMIT.DATE_APPROVED2
     */
    private Date DATE_APPROVED2;

    /**
     * This field corresponds to the database column TRSCIFCOUNTRYLIMIT.SUSPENDED_BY
     */
    private String SUSPENDED_BY;

    /**
     * This field corresponds to the database column TRSCIFCOUNTRYLIMIT.DATE_SUSPENDED
     */
    private Date DATE_SUSPENDED;

    /**
     * This field corresponds to the database column TRSCIFCOUNTRYLIMIT.REACTIVATED_BY
     */
    private String REACTIVATED_BY;

    /**
     * This field corresponds to the database column TRSCIFCOUNTRYLIMIT.DATE_REACTIVATED
     */
    private Date DATE_REACTIVATED;

    /**
     * This field corresponds to the database column TRSCIFCOUNTRYLIMIT.LIMIT_UTILIZATION
     */
    private BigDecimal LIMIT_UTILIZATION;

    /**
     * This field corresponds to the database column TRSCIFCOUNTRYLIMIT.EXPIRY_DATE
     */
    private Date EXPIRY_DATE;

    /**
     * This field corresponds to the database column TRSCIFCOUNTRYLIMIT.LIMIT_BY_COMPANY_YN
     */
    private String LIMIT_BY_COMPANY_YN;

    /**
     * This field corresponds to the database column TRSCIFCOUNTRYLIMIT.LIMIT_UTILIZED_ASSET
     */
    private BigDecimal LIMIT_UTILIZED_ASSET;

    /**
     * This field corresponds to the database column TRSCIFCOUNTRYLIMIT.LIMIT_UTILIZED_COLLATERAL
     */
    private BigDecimal LIMIT_UTILIZED_COLLATERAL;

    /**
     * This field corresponds to the database column TRSCIFCOUNTRYLIMIT.LIMIT_UTILIZED_IIS
     */
    private BigDecimal LIMIT_UTILIZED_IIS;

    /**
     * This field corresponds to the database column TRSCIFCOUNTRYLIMIT.LIMIT_UTILIZED_TFA
     */
    private BigDecimal LIMIT_UTILIZED_TFA;

    /**
     * This field corresponds to the database column TRSCIFCOUNTRYLIMIT.VALIDATION_MESSSAGE_TYPE
     */
    private String VALIDATION_MESSSAGE_TYPE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCIFCOUNTRYLIMIT.BRANCH_CODE
     *
     * @return the value of TRSCIFCOUNTRYLIMIT.BRANCH_CODE
     */
    public BigDecimal getBRANCH_CODE() {
        return BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCIFCOUNTRYLIMIT.BRANCH_CODE
     *
     * @param BRANCH_CODE the value for TRSCIFCOUNTRYLIMIT.BRANCH_CODE
     */
    public void setBRANCH_CODE(BigDecimal BRANCH_CODE) {
        this.BRANCH_CODE = BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCIFCOUNTRYLIMIT.COMP_CODE
     *
     * @return the value of TRSCIFCOUNTRYLIMIT.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCIFCOUNTRYLIMIT.COMP_CODE
     *
     * @param COMP_CODE the value for TRSCIFCOUNTRYLIMIT.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCIFCOUNTRYLIMIT.COUNTRY
     *
     * @return the value of TRSCIFCOUNTRYLIMIT.COUNTRY
     */
    public BigDecimal getCOUNTRY() {
        return COUNTRY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCIFCOUNTRYLIMIT.COUNTRY
     *
     * @param COUNTRY the value for TRSCIFCOUNTRYLIMIT.COUNTRY
     */
    public void setCOUNTRY(BigDecimal COUNTRY) {
        this.COUNTRY = COUNTRY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCIFCOUNTRYLIMIT.CURRENCY_CODE
     *
     * @return the value of TRSCIFCOUNTRYLIMIT.CURRENCY_CODE
     */
    public BigDecimal getCURRENCY_CODE() {
        return CURRENCY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCIFCOUNTRYLIMIT.CURRENCY_CODE
     *
     * @param CURRENCY_CODE the value for TRSCIFCOUNTRYLIMIT.CURRENCY_CODE
     */
    public void setCURRENCY_CODE(BigDecimal CURRENCY_CODE) {
        this.CURRENCY_CODE = CURRENCY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCIFCOUNTRYLIMIT.LIMIT
     *
     * @return the value of TRSCIFCOUNTRYLIMIT.LIMIT
     */
    public BigDecimal getLIMIT() {
        return LIMIT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCIFCOUNTRYLIMIT.LIMIT
     *
     * @param LIMIT the value for TRSCIFCOUNTRYLIMIT.LIMIT
     */
    public void setLIMIT(BigDecimal LIMIT) {
        this.LIMIT = LIMIT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCIFCOUNTRYLIMIT.STATUS
     *
     * @return the value of TRSCIFCOUNTRYLIMIT.STATUS
     */
    public String getSTATUS() {
        return STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCIFCOUNTRYLIMIT.STATUS
     *
     * @param STATUS the value for TRSCIFCOUNTRYLIMIT.STATUS
     */
    public void setSTATUS(String STATUS) {
        this.STATUS = STATUS == null ? null : STATUS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCIFCOUNTRYLIMIT.CREATED_BY
     *
     * @return the value of TRSCIFCOUNTRYLIMIT.CREATED_BY
     */
    public String getCREATED_BY() {
        return CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCIFCOUNTRYLIMIT.CREATED_BY
     *
     * @param CREATED_BY the value for TRSCIFCOUNTRYLIMIT.CREATED_BY
     */
    public void setCREATED_BY(String CREATED_BY) {
        this.CREATED_BY = CREATED_BY == null ? null : CREATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCIFCOUNTRYLIMIT.DATE_CREATED
     *
     * @return the value of TRSCIFCOUNTRYLIMIT.DATE_CREATED
     */
    public Date getDATE_CREATED() {
        return DATE_CREATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCIFCOUNTRYLIMIT.DATE_CREATED
     *
     * @param DATE_CREATED the value for TRSCIFCOUNTRYLIMIT.DATE_CREATED
     */
    public void setDATE_CREATED(Date DATE_CREATED) {
        this.DATE_CREATED = DATE_CREATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCIFCOUNTRYLIMIT.MODIFIED_BY
     *
     * @return the value of TRSCIFCOUNTRYLIMIT.MODIFIED_BY
     */
    public String getMODIFIED_BY() {
        return MODIFIED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCIFCOUNTRYLIMIT.MODIFIED_BY
     *
     * @param MODIFIED_BY the value for TRSCIFCOUNTRYLIMIT.MODIFIED_BY
     */
    public void setMODIFIED_BY(String MODIFIED_BY) {
        this.MODIFIED_BY = MODIFIED_BY == null ? null : MODIFIED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCIFCOUNTRYLIMIT.DATE_MODIFIED
     *
     * @return the value of TRSCIFCOUNTRYLIMIT.DATE_MODIFIED
     */
    public Date getDATE_MODIFIED() {
        return DATE_MODIFIED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCIFCOUNTRYLIMIT.DATE_MODIFIED
     *
     * @param DATE_MODIFIED the value for TRSCIFCOUNTRYLIMIT.DATE_MODIFIED
     */
    public void setDATE_MODIFIED(Date DATE_MODIFIED) {
        this.DATE_MODIFIED = DATE_MODIFIED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCIFCOUNTRYLIMIT.APPROVED1_BY
     *
     * @return the value of TRSCIFCOUNTRYLIMIT.APPROVED1_BY
     */
    public String getAPPROVED1_BY() {
        return APPROVED1_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCIFCOUNTRYLIMIT.APPROVED1_BY
     *
     * @param APPROVED1_BY the value for TRSCIFCOUNTRYLIMIT.APPROVED1_BY
     */
    public void setAPPROVED1_BY(String APPROVED1_BY) {
        this.APPROVED1_BY = APPROVED1_BY == null ? null : APPROVED1_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCIFCOUNTRYLIMIT.DATE_APPROVED1
     *
     * @return the value of TRSCIFCOUNTRYLIMIT.DATE_APPROVED1
     */
    public Date getDATE_APPROVED1() {
        return DATE_APPROVED1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCIFCOUNTRYLIMIT.DATE_APPROVED1
     *
     * @param DATE_APPROVED1 the value for TRSCIFCOUNTRYLIMIT.DATE_APPROVED1
     */
    public void setDATE_APPROVED1(Date DATE_APPROVED1) {
        this.DATE_APPROVED1 = DATE_APPROVED1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCIFCOUNTRYLIMIT.APPROVED2_BY
     *
     * @return the value of TRSCIFCOUNTRYLIMIT.APPROVED2_BY
     */
    public String getAPPROVED2_BY() {
        return APPROVED2_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCIFCOUNTRYLIMIT.APPROVED2_BY
     *
     * @param APPROVED2_BY the value for TRSCIFCOUNTRYLIMIT.APPROVED2_BY
     */
    public void setAPPROVED2_BY(String APPROVED2_BY) {
        this.APPROVED2_BY = APPROVED2_BY == null ? null : APPROVED2_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCIFCOUNTRYLIMIT.DATE_APPROVED2
     *
     * @return the value of TRSCIFCOUNTRYLIMIT.DATE_APPROVED2
     */
    public Date getDATE_APPROVED2() {
        return DATE_APPROVED2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCIFCOUNTRYLIMIT.DATE_APPROVED2
     *
     * @param DATE_APPROVED2 the value for TRSCIFCOUNTRYLIMIT.DATE_APPROVED2
     */
    public void setDATE_APPROVED2(Date DATE_APPROVED2) {
        this.DATE_APPROVED2 = DATE_APPROVED2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCIFCOUNTRYLIMIT.SUSPENDED_BY
     *
     * @return the value of TRSCIFCOUNTRYLIMIT.SUSPENDED_BY
     */
    public String getSUSPENDED_BY() {
        return SUSPENDED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCIFCOUNTRYLIMIT.SUSPENDED_BY
     *
     * @param SUSPENDED_BY the value for TRSCIFCOUNTRYLIMIT.SUSPENDED_BY
     */
    public void setSUSPENDED_BY(String SUSPENDED_BY) {
        this.SUSPENDED_BY = SUSPENDED_BY == null ? null : SUSPENDED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCIFCOUNTRYLIMIT.DATE_SUSPENDED
     *
     * @return the value of TRSCIFCOUNTRYLIMIT.DATE_SUSPENDED
     */
    public Date getDATE_SUSPENDED() {
        return DATE_SUSPENDED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCIFCOUNTRYLIMIT.DATE_SUSPENDED
     *
     * @param DATE_SUSPENDED the value for TRSCIFCOUNTRYLIMIT.DATE_SUSPENDED
     */
    public void setDATE_SUSPENDED(Date DATE_SUSPENDED) {
        this.DATE_SUSPENDED = DATE_SUSPENDED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCIFCOUNTRYLIMIT.REACTIVATED_BY
     *
     * @return the value of TRSCIFCOUNTRYLIMIT.REACTIVATED_BY
     */
    public String getREACTIVATED_BY() {
        return REACTIVATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCIFCOUNTRYLIMIT.REACTIVATED_BY
     *
     * @param REACTIVATED_BY the value for TRSCIFCOUNTRYLIMIT.REACTIVATED_BY
     */
    public void setREACTIVATED_BY(String REACTIVATED_BY) {
        this.REACTIVATED_BY = REACTIVATED_BY == null ? null : REACTIVATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCIFCOUNTRYLIMIT.DATE_REACTIVATED
     *
     * @return the value of TRSCIFCOUNTRYLIMIT.DATE_REACTIVATED
     */
    public Date getDATE_REACTIVATED() {
        return DATE_REACTIVATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCIFCOUNTRYLIMIT.DATE_REACTIVATED
     *
     * @param DATE_REACTIVATED the value for TRSCIFCOUNTRYLIMIT.DATE_REACTIVATED
     */
    public void setDATE_REACTIVATED(Date DATE_REACTIVATED) {
        this.DATE_REACTIVATED = DATE_REACTIVATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCIFCOUNTRYLIMIT.LIMIT_UTILIZATION
     *
     * @return the value of TRSCIFCOUNTRYLIMIT.LIMIT_UTILIZATION
     */
    public BigDecimal getLIMIT_UTILIZATION() {
        return LIMIT_UTILIZATION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCIFCOUNTRYLIMIT.LIMIT_UTILIZATION
     *
     * @param LIMIT_UTILIZATION the value for TRSCIFCOUNTRYLIMIT.LIMIT_UTILIZATION
     */
    public void setLIMIT_UTILIZATION(BigDecimal LIMIT_UTILIZATION) {
        this.LIMIT_UTILIZATION = LIMIT_UTILIZATION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCIFCOUNTRYLIMIT.EXPIRY_DATE
     *
     * @return the value of TRSCIFCOUNTRYLIMIT.EXPIRY_DATE
     */
    public Date getEXPIRY_DATE() {
        return EXPIRY_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCIFCOUNTRYLIMIT.EXPIRY_DATE
     *
     * @param EXPIRY_DATE the value for TRSCIFCOUNTRYLIMIT.EXPIRY_DATE
     */
    public void setEXPIRY_DATE(Date EXPIRY_DATE) {
        this.EXPIRY_DATE = EXPIRY_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCIFCOUNTRYLIMIT.LIMIT_BY_COMPANY_YN
     *
     * @return the value of TRSCIFCOUNTRYLIMIT.LIMIT_BY_COMPANY_YN
     */
    public String getLIMIT_BY_COMPANY_YN() {
        return LIMIT_BY_COMPANY_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCIFCOUNTRYLIMIT.LIMIT_BY_COMPANY_YN
     *
     * @param LIMIT_BY_COMPANY_YN the value for TRSCIFCOUNTRYLIMIT.LIMIT_BY_COMPANY_YN
     */
    public void setLIMIT_BY_COMPANY_YN(String LIMIT_BY_COMPANY_YN) {
        this.LIMIT_BY_COMPANY_YN = LIMIT_BY_COMPANY_YN == null ? null : LIMIT_BY_COMPANY_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCIFCOUNTRYLIMIT.LIMIT_UTILIZED_ASSET
     *
     * @return the value of TRSCIFCOUNTRYLIMIT.LIMIT_UTILIZED_ASSET
     */
    public BigDecimal getLIMIT_UTILIZED_ASSET() {
        return LIMIT_UTILIZED_ASSET;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCIFCOUNTRYLIMIT.LIMIT_UTILIZED_ASSET
     *
     * @param LIMIT_UTILIZED_ASSET the value for TRSCIFCOUNTRYLIMIT.LIMIT_UTILIZED_ASSET
     */
    public void setLIMIT_UTILIZED_ASSET(BigDecimal LIMIT_UTILIZED_ASSET) {
        this.LIMIT_UTILIZED_ASSET = LIMIT_UTILIZED_ASSET;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCIFCOUNTRYLIMIT.LIMIT_UTILIZED_COLLATERAL
     *
     * @return the value of TRSCIFCOUNTRYLIMIT.LIMIT_UTILIZED_COLLATERAL
     */
    public BigDecimal getLIMIT_UTILIZED_COLLATERAL() {
        return LIMIT_UTILIZED_COLLATERAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCIFCOUNTRYLIMIT.LIMIT_UTILIZED_COLLATERAL
     *
     * @param LIMIT_UTILIZED_COLLATERAL the value for TRSCIFCOUNTRYLIMIT.LIMIT_UTILIZED_COLLATERAL
     */
    public void setLIMIT_UTILIZED_COLLATERAL(BigDecimal LIMIT_UTILIZED_COLLATERAL) {
        this.LIMIT_UTILIZED_COLLATERAL = LIMIT_UTILIZED_COLLATERAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCIFCOUNTRYLIMIT.LIMIT_UTILIZED_IIS
     *
     * @return the value of TRSCIFCOUNTRYLIMIT.LIMIT_UTILIZED_IIS
     */
    public BigDecimal getLIMIT_UTILIZED_IIS() {
        return LIMIT_UTILIZED_IIS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCIFCOUNTRYLIMIT.LIMIT_UTILIZED_IIS
     *
     * @param LIMIT_UTILIZED_IIS the value for TRSCIFCOUNTRYLIMIT.LIMIT_UTILIZED_IIS
     */
    public void setLIMIT_UTILIZED_IIS(BigDecimal LIMIT_UTILIZED_IIS) {
        this.LIMIT_UTILIZED_IIS = LIMIT_UTILIZED_IIS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCIFCOUNTRYLIMIT.LIMIT_UTILIZED_TFA
     *
     * @return the value of TRSCIFCOUNTRYLIMIT.LIMIT_UTILIZED_TFA
     */
    public BigDecimal getLIMIT_UTILIZED_TFA() {
        return LIMIT_UTILIZED_TFA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCIFCOUNTRYLIMIT.LIMIT_UTILIZED_TFA
     *
     * @param LIMIT_UTILIZED_TFA the value for TRSCIFCOUNTRYLIMIT.LIMIT_UTILIZED_TFA
     */
    public void setLIMIT_UTILIZED_TFA(BigDecimal LIMIT_UTILIZED_TFA) {
        this.LIMIT_UTILIZED_TFA = LIMIT_UTILIZED_TFA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCIFCOUNTRYLIMIT.VALIDATION_MESSSAGE_TYPE
     *
     * @return the value of TRSCIFCOUNTRYLIMIT.VALIDATION_MESSSAGE_TYPE
     */
    public String getVALIDATION_MESSSAGE_TYPE() {
        return VALIDATION_MESSSAGE_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCIFCOUNTRYLIMIT.VALIDATION_MESSSAGE_TYPE
     *
     * @param VALIDATION_MESSSAGE_TYPE the value for TRSCIFCOUNTRYLIMIT.VALIDATION_MESSSAGE_TYPE
     */
    public void setVALIDATION_MESSSAGE_TYPE(String VALIDATION_MESSSAGE_TYPE) {
        this.VALIDATION_MESSSAGE_TYPE = VALIDATION_MESSSAGE_TYPE == null ? null : VALIDATION_MESSSAGE_TYPE.trim();
    }
}