package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class TRSCIFLMTDET_PLAN_CRITERIADETVO extends TRSCIFLMTDET_PLAN_CRITERIADETVOKey {
    /**
     * This field corresponds to the database column TRSCIFLMTDET_PLAN_CRITERIADET.PAYMENT_TYPE
     */
    private String PAYMENT_TYPE;

    /**
     * This field corresponds to the database column TRSCIFLMTDET_PLAN_CRITERIADET.PAYM_PERIODICITY
     */
    private String PAYM_PERIODICITY;

    /**
     * This field corresponds to the database column TRSCIFLMTDET_PLAN_CRITERIADET.PAYM_PERIOD_NBR
     */
    private BigDecimal PAYM_PERIOD_NBR;

    /**
     * This field corresponds to the database column TRSCIFLMTDET_PLAN_CRITERIADET.PAYM_PERIOD_POS
     */
    private String PAYM_PERIOD_POS;

    /**
     * This field corresponds to the database column TRSCIFLMTDET_PLAN_CRITERIADET.ACC_BR
     */
    private BigDecimal ACC_BR;

    /**
     * This field corresponds to the database column TRSCIFLMTDET_PLAN_CRITERIADET.ACC_CY
     */
    private BigDecimal ACC_CY;

    /**
     * This field corresponds to the database column TRSCIFLMTDET_PLAN_CRITERIADET.ACC_GL
     */
    private BigDecimal ACC_GL;

    /**
     * This field corresponds to the database column TRSCIFLMTDET_PLAN_CRITERIADET.ACC_CIF
     */
    private BigDecimal ACC_CIF;

    /**
     * This field corresponds to the database column TRSCIFLMTDET_PLAN_CRITERIADET.ACC_SL
     */
    private BigDecimal ACC_SL;

    /**
     * This field corresponds to the database column TRSCIFLMTDET_PLAN_CRITERIADET.COVERING_ACC_BR
     */
    private BigDecimal COVERING_ACC_BR;

    /**
     * This field corresponds to the database column TRSCIFLMTDET_PLAN_CRITERIADET.COVERING_ACC_CY
     */
    private BigDecimal COVERING_ACC_CY;

    /**
     * This field corresponds to the database column TRSCIFLMTDET_PLAN_CRITERIADET.COVERING_ACC_GL
     */
    private BigDecimal COVERING_ACC_GL;

    /**
     * This field corresponds to the database column TRSCIFLMTDET_PLAN_CRITERIADET.COVERING_ACC_CIF
     */
    private BigDecimal COVERING_ACC_CIF;

    /**
     * This field corresponds to the database column TRSCIFLMTDET_PLAN_CRITERIADET.COVERING_ACC_SL
     */
    private BigDecimal COVERING_ACC_SL;

    /**
     * This field corresponds to the database column TRSCIFLMTDET_PLAN_CRITERIADET.AUTO_CREATE_SETTLEMENT_YN
     */
    private String AUTO_CREATE_SETTLEMENT_YN;

    /**
     * This field corresponds to the database column TRSCIFLMTDET_PLAN_CRITERIADET.PAYM_DAY
     */
    private BigDecimal PAYM_DAY;

    /**
     * This field corresponds to the database column TRSCIFLMTDET_PLAN_CRITERIADET.INSTALLMENT_DATE_FROM
     */
    private Date INSTALLMENT_DATE_FROM;

    /**
     * This field corresponds to the database column TRSCIFLMTDET_PLAN_CRITERIADET.INSTALLMENT_DATE_TO
     */
    private Date INSTALLMENT_DATE_TO;

    /**
     * This field corresponds to the database column TRSCIFLMTDET_PLAN_CRITERIADET.AMOUNT
     */
    private BigDecimal AMOUNT;

    /**
     * This field corresponds to the database column TRSCIFLMTDET_PLAN_CRITERIADET.LIMIT_AVAILABLE_FROM
     */
    private Date LIMIT_AVAILABLE_FROM;

    /**
     * This field corresponds to the database column TRSCIFLMTDET_PLAN_CRITERIADET.LIMIT_AVAILABLE_TO
     */
    private Date LIMIT_AVAILABLE_TO;

    /**
     * This field corresponds to the database column TRSCIFLMTDET_PLAN_CRITERIADET.GRACE_PERIOD
     */
    private BigDecimal GRACE_PERIOD;

    /**
     * This field corresponds to the database column TRSCIFLMTDET_PLAN_CRITERIADET.PFT_DURING_UTILIZATION_PERIOD
     */
    private String PFT_DURING_UTILIZATION_PERIOD;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCIFLMTDET_PLAN_CRITERIADET.PAYMENT_TYPE
     *
     * @return the value of TRSCIFLMTDET_PLAN_CRITERIADET.PAYMENT_TYPE
     */
    public String getPAYMENT_TYPE() {
        return PAYMENT_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCIFLMTDET_PLAN_CRITERIADET.PAYMENT_TYPE
     *
     * @param PAYMENT_TYPE the value for TRSCIFLMTDET_PLAN_CRITERIADET.PAYMENT_TYPE
     */
    public void setPAYMENT_TYPE(String PAYMENT_TYPE) {
        this.PAYMENT_TYPE = PAYMENT_TYPE == null ? null : PAYMENT_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCIFLMTDET_PLAN_CRITERIADET.PAYM_PERIODICITY
     *
     * @return the value of TRSCIFLMTDET_PLAN_CRITERIADET.PAYM_PERIODICITY
     */
    public String getPAYM_PERIODICITY() {
        return PAYM_PERIODICITY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCIFLMTDET_PLAN_CRITERIADET.PAYM_PERIODICITY
     *
     * @param PAYM_PERIODICITY the value for TRSCIFLMTDET_PLAN_CRITERIADET.PAYM_PERIODICITY
     */
    public void setPAYM_PERIODICITY(String PAYM_PERIODICITY) {
        this.PAYM_PERIODICITY = PAYM_PERIODICITY == null ? null : PAYM_PERIODICITY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCIFLMTDET_PLAN_CRITERIADET.PAYM_PERIOD_NBR
     *
     * @return the value of TRSCIFLMTDET_PLAN_CRITERIADET.PAYM_PERIOD_NBR
     */
    public BigDecimal getPAYM_PERIOD_NBR() {
        return PAYM_PERIOD_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCIFLMTDET_PLAN_CRITERIADET.PAYM_PERIOD_NBR
     *
     * @param PAYM_PERIOD_NBR the value for TRSCIFLMTDET_PLAN_CRITERIADET.PAYM_PERIOD_NBR
     */
    public void setPAYM_PERIOD_NBR(BigDecimal PAYM_PERIOD_NBR) {
        this.PAYM_PERIOD_NBR = PAYM_PERIOD_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCIFLMTDET_PLAN_CRITERIADET.PAYM_PERIOD_POS
     *
     * @return the value of TRSCIFLMTDET_PLAN_CRITERIADET.PAYM_PERIOD_POS
     */
    public String getPAYM_PERIOD_POS() {
        return PAYM_PERIOD_POS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCIFLMTDET_PLAN_CRITERIADET.PAYM_PERIOD_POS
     *
     * @param PAYM_PERIOD_POS the value for TRSCIFLMTDET_PLAN_CRITERIADET.PAYM_PERIOD_POS
     */
    public void setPAYM_PERIOD_POS(String PAYM_PERIOD_POS) {
        this.PAYM_PERIOD_POS = PAYM_PERIOD_POS == null ? null : PAYM_PERIOD_POS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCIFLMTDET_PLAN_CRITERIADET.ACC_BR
     *
     * @return the value of TRSCIFLMTDET_PLAN_CRITERIADET.ACC_BR
     */
    public BigDecimal getACC_BR() {
        return ACC_BR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCIFLMTDET_PLAN_CRITERIADET.ACC_BR
     *
     * @param ACC_BR the value for TRSCIFLMTDET_PLAN_CRITERIADET.ACC_BR
     */
    public void setACC_BR(BigDecimal ACC_BR) {
        this.ACC_BR = ACC_BR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCIFLMTDET_PLAN_CRITERIADET.ACC_CY
     *
     * @return the value of TRSCIFLMTDET_PLAN_CRITERIADET.ACC_CY
     */
    public BigDecimal getACC_CY() {
        return ACC_CY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCIFLMTDET_PLAN_CRITERIADET.ACC_CY
     *
     * @param ACC_CY the value for TRSCIFLMTDET_PLAN_CRITERIADET.ACC_CY
     */
    public void setACC_CY(BigDecimal ACC_CY) {
        this.ACC_CY = ACC_CY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCIFLMTDET_PLAN_CRITERIADET.ACC_GL
     *
     * @return the value of TRSCIFLMTDET_PLAN_CRITERIADET.ACC_GL
     */
    public BigDecimal getACC_GL() {
        return ACC_GL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCIFLMTDET_PLAN_CRITERIADET.ACC_GL
     *
     * @param ACC_GL the value for TRSCIFLMTDET_PLAN_CRITERIADET.ACC_GL
     */
    public void setACC_GL(BigDecimal ACC_GL) {
        this.ACC_GL = ACC_GL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCIFLMTDET_PLAN_CRITERIADET.ACC_CIF
     *
     * @return the value of TRSCIFLMTDET_PLAN_CRITERIADET.ACC_CIF
     */
    public BigDecimal getACC_CIF() {
        return ACC_CIF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCIFLMTDET_PLAN_CRITERIADET.ACC_CIF
     *
     * @param ACC_CIF the value for TRSCIFLMTDET_PLAN_CRITERIADET.ACC_CIF
     */
    public void setACC_CIF(BigDecimal ACC_CIF) {
        this.ACC_CIF = ACC_CIF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCIFLMTDET_PLAN_CRITERIADET.ACC_SL
     *
     * @return the value of TRSCIFLMTDET_PLAN_CRITERIADET.ACC_SL
     */
    public BigDecimal getACC_SL() {
        return ACC_SL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCIFLMTDET_PLAN_CRITERIADET.ACC_SL
     *
     * @param ACC_SL the value for TRSCIFLMTDET_PLAN_CRITERIADET.ACC_SL
     */
    public void setACC_SL(BigDecimal ACC_SL) {
        this.ACC_SL = ACC_SL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCIFLMTDET_PLAN_CRITERIADET.COVERING_ACC_BR
     *
     * @return the value of TRSCIFLMTDET_PLAN_CRITERIADET.COVERING_ACC_BR
     */
    public BigDecimal getCOVERING_ACC_BR() {
        return COVERING_ACC_BR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCIFLMTDET_PLAN_CRITERIADET.COVERING_ACC_BR
     *
     * @param COVERING_ACC_BR the value for TRSCIFLMTDET_PLAN_CRITERIADET.COVERING_ACC_BR
     */
    public void setCOVERING_ACC_BR(BigDecimal COVERING_ACC_BR) {
        this.COVERING_ACC_BR = COVERING_ACC_BR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCIFLMTDET_PLAN_CRITERIADET.COVERING_ACC_CY
     *
     * @return the value of TRSCIFLMTDET_PLAN_CRITERIADET.COVERING_ACC_CY
     */
    public BigDecimal getCOVERING_ACC_CY() {
        return COVERING_ACC_CY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCIFLMTDET_PLAN_CRITERIADET.COVERING_ACC_CY
     *
     * @param COVERING_ACC_CY the value for TRSCIFLMTDET_PLAN_CRITERIADET.COVERING_ACC_CY
     */
    public void setCOVERING_ACC_CY(BigDecimal COVERING_ACC_CY) {
        this.COVERING_ACC_CY = COVERING_ACC_CY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCIFLMTDET_PLAN_CRITERIADET.COVERING_ACC_GL
     *
     * @return the value of TRSCIFLMTDET_PLAN_CRITERIADET.COVERING_ACC_GL
     */
    public BigDecimal getCOVERING_ACC_GL() {
        return COVERING_ACC_GL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCIFLMTDET_PLAN_CRITERIADET.COVERING_ACC_GL
     *
     * @param COVERING_ACC_GL the value for TRSCIFLMTDET_PLAN_CRITERIADET.COVERING_ACC_GL
     */
    public void setCOVERING_ACC_GL(BigDecimal COVERING_ACC_GL) {
        this.COVERING_ACC_GL = COVERING_ACC_GL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCIFLMTDET_PLAN_CRITERIADET.COVERING_ACC_CIF
     *
     * @return the value of TRSCIFLMTDET_PLAN_CRITERIADET.COVERING_ACC_CIF
     */
    public BigDecimal getCOVERING_ACC_CIF() {
        return COVERING_ACC_CIF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCIFLMTDET_PLAN_CRITERIADET.COVERING_ACC_CIF
     *
     * @param COVERING_ACC_CIF the value for TRSCIFLMTDET_PLAN_CRITERIADET.COVERING_ACC_CIF
     */
    public void setCOVERING_ACC_CIF(BigDecimal COVERING_ACC_CIF) {
        this.COVERING_ACC_CIF = COVERING_ACC_CIF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCIFLMTDET_PLAN_CRITERIADET.COVERING_ACC_SL
     *
     * @return the value of TRSCIFLMTDET_PLAN_CRITERIADET.COVERING_ACC_SL
     */
    public BigDecimal getCOVERING_ACC_SL() {
        return COVERING_ACC_SL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCIFLMTDET_PLAN_CRITERIADET.COVERING_ACC_SL
     *
     * @param COVERING_ACC_SL the value for TRSCIFLMTDET_PLAN_CRITERIADET.COVERING_ACC_SL
     */
    public void setCOVERING_ACC_SL(BigDecimal COVERING_ACC_SL) {
        this.COVERING_ACC_SL = COVERING_ACC_SL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCIFLMTDET_PLAN_CRITERIADET.AUTO_CREATE_SETTLEMENT_YN
     *
     * @return the value of TRSCIFLMTDET_PLAN_CRITERIADET.AUTO_CREATE_SETTLEMENT_YN
     */
    public String getAUTO_CREATE_SETTLEMENT_YN() {
        return AUTO_CREATE_SETTLEMENT_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCIFLMTDET_PLAN_CRITERIADET.AUTO_CREATE_SETTLEMENT_YN
     *
     * @param AUTO_CREATE_SETTLEMENT_YN the value for TRSCIFLMTDET_PLAN_CRITERIADET.AUTO_CREATE_SETTLEMENT_YN
     */
    public void setAUTO_CREATE_SETTLEMENT_YN(String AUTO_CREATE_SETTLEMENT_YN) {
        this.AUTO_CREATE_SETTLEMENT_YN = AUTO_CREATE_SETTLEMENT_YN == null ? null : AUTO_CREATE_SETTLEMENT_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCIFLMTDET_PLAN_CRITERIADET.PAYM_DAY
     *
     * @return the value of TRSCIFLMTDET_PLAN_CRITERIADET.PAYM_DAY
     */
    public BigDecimal getPAYM_DAY() {
        return PAYM_DAY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCIFLMTDET_PLAN_CRITERIADET.PAYM_DAY
     *
     * @param PAYM_DAY the value for TRSCIFLMTDET_PLAN_CRITERIADET.PAYM_DAY
     */
    public void setPAYM_DAY(BigDecimal PAYM_DAY) {
        this.PAYM_DAY = PAYM_DAY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCIFLMTDET_PLAN_CRITERIADET.INSTALLMENT_DATE_FROM
     *
     * @return the value of TRSCIFLMTDET_PLAN_CRITERIADET.INSTALLMENT_DATE_FROM
     */
    public Date getINSTALLMENT_DATE_FROM() {
        return INSTALLMENT_DATE_FROM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCIFLMTDET_PLAN_CRITERIADET.INSTALLMENT_DATE_FROM
     *
     * @param INSTALLMENT_DATE_FROM the value for TRSCIFLMTDET_PLAN_CRITERIADET.INSTALLMENT_DATE_FROM
     */
    public void setINSTALLMENT_DATE_FROM(Date INSTALLMENT_DATE_FROM) {
        this.INSTALLMENT_DATE_FROM = INSTALLMENT_DATE_FROM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCIFLMTDET_PLAN_CRITERIADET.INSTALLMENT_DATE_TO
     *
     * @return the value of TRSCIFLMTDET_PLAN_CRITERIADET.INSTALLMENT_DATE_TO
     */
    public Date getINSTALLMENT_DATE_TO() {
        return INSTALLMENT_DATE_TO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCIFLMTDET_PLAN_CRITERIADET.INSTALLMENT_DATE_TO
     *
     * @param INSTALLMENT_DATE_TO the value for TRSCIFLMTDET_PLAN_CRITERIADET.INSTALLMENT_DATE_TO
     */
    public void setINSTALLMENT_DATE_TO(Date INSTALLMENT_DATE_TO) {
        this.INSTALLMENT_DATE_TO = INSTALLMENT_DATE_TO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCIFLMTDET_PLAN_CRITERIADET.AMOUNT
     *
     * @return the value of TRSCIFLMTDET_PLAN_CRITERIADET.AMOUNT
     */
    public BigDecimal getAMOUNT() {
        return AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCIFLMTDET_PLAN_CRITERIADET.AMOUNT
     *
     * @param AMOUNT the value for TRSCIFLMTDET_PLAN_CRITERIADET.AMOUNT
     */
    public void setAMOUNT(BigDecimal AMOUNT) {
        this.AMOUNT = AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCIFLMTDET_PLAN_CRITERIADET.LIMIT_AVAILABLE_FROM
     *
     * @return the value of TRSCIFLMTDET_PLAN_CRITERIADET.LIMIT_AVAILABLE_FROM
     */
    public Date getLIMIT_AVAILABLE_FROM() {
        return LIMIT_AVAILABLE_FROM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCIFLMTDET_PLAN_CRITERIADET.LIMIT_AVAILABLE_FROM
     *
     * @param LIMIT_AVAILABLE_FROM the value for TRSCIFLMTDET_PLAN_CRITERIADET.LIMIT_AVAILABLE_FROM
     */
    public void setLIMIT_AVAILABLE_FROM(Date LIMIT_AVAILABLE_FROM) {
        this.LIMIT_AVAILABLE_FROM = LIMIT_AVAILABLE_FROM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCIFLMTDET_PLAN_CRITERIADET.LIMIT_AVAILABLE_TO
     *
     * @return the value of TRSCIFLMTDET_PLAN_CRITERIADET.LIMIT_AVAILABLE_TO
     */
    public Date getLIMIT_AVAILABLE_TO() {
        return LIMIT_AVAILABLE_TO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCIFLMTDET_PLAN_CRITERIADET.LIMIT_AVAILABLE_TO
     *
     * @param LIMIT_AVAILABLE_TO the value for TRSCIFLMTDET_PLAN_CRITERIADET.LIMIT_AVAILABLE_TO
     */
    public void setLIMIT_AVAILABLE_TO(Date LIMIT_AVAILABLE_TO) {
        this.LIMIT_AVAILABLE_TO = LIMIT_AVAILABLE_TO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCIFLMTDET_PLAN_CRITERIADET.GRACE_PERIOD
     *
     * @return the value of TRSCIFLMTDET_PLAN_CRITERIADET.GRACE_PERIOD
     */
    public BigDecimal getGRACE_PERIOD() {
        return GRACE_PERIOD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCIFLMTDET_PLAN_CRITERIADET.GRACE_PERIOD
     *
     * @param GRACE_PERIOD the value for TRSCIFLMTDET_PLAN_CRITERIADET.GRACE_PERIOD
     */
    public void setGRACE_PERIOD(BigDecimal GRACE_PERIOD) {
        this.GRACE_PERIOD = GRACE_PERIOD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCIFLMTDET_PLAN_CRITERIADET.PFT_DURING_UTILIZATION_PERIOD
     *
     * @return the value of TRSCIFLMTDET_PLAN_CRITERIADET.PFT_DURING_UTILIZATION_PERIOD
     */
    public String getPFT_DURING_UTILIZATION_PERIOD() {
        return PFT_DURING_UTILIZATION_PERIOD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCIFLMTDET_PLAN_CRITERIADET.PFT_DURING_UTILIZATION_PERIOD
     *
     * @param PFT_DURING_UTILIZATION_PERIOD the value for TRSCIFLMTDET_PLAN_CRITERIADET.PFT_DURING_UTILIZATION_PERIOD
     */
    public void setPFT_DURING_UTILIZATION_PERIOD(String PFT_DURING_UTILIZATION_PERIOD) {
        this.PFT_DURING_UTILIZATION_PERIOD = PFT_DURING_UTILIZATION_PERIOD == null ? null : PFT_DURING_UTILIZATION_PERIOD.trim();
    }
}