package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class TRSCIFLIMITDET_TRXVO extends TRSCIFLIMITDET_TRXVOKey {
    /**
     * This field corresponds to the database column TRSCIFLIMITDET_TRX.TRS_TYPE
     */
    private String TRS_TYPE;

    /**
     * This field corresponds to the database column TRSCIFLIMITDET_TRX.TRS_NO
     */
    private BigDecimal TRS_NO;

    /**
     * This field corresponds to the database column TRSCIFLIMITDET_TRX.TRADE_DATE
     */
    private Date TRADE_DATE;

    /**
     * This field corresponds to the database column TRSCIFLIMITDET_TRX.AMOUNT_TYPE
     */
    private String AMOUNT_TYPE;

    /**
     * This field corresponds to the database column TRSCIFLIMITDET_TRX.AMOUNT
     */
    private BigDecimal AMOUNT;

    /**
     * This field corresponds to the database column TRSCIFLIMITDET_TRX.SWAP_YN
     */
    private String SWAP_YN;

    /**
     * This field corresponds to the database column TRSCIFLIMITDET_TRX.LIMIT_EXCEED_AMOUNT
     */
    private BigDecimal LIMIT_EXCEED_AMOUNT;

    /**
     * This field corresponds to the database column TRSCIFLIMITDET_TRX.SERVER_DATE
     */
    private Date SERVER_DATE;

    /**
     * This field corresponds to the database column TRSCIFLIMITDET_TRX.AMOUNT_IN_DEAL_CY
     */
    private BigDecimal AMOUNT_IN_DEAL_CY;

    /**
     * This field corresponds to the database column TRSCIFLIMITDET_TRX.CHILD_CIF
     */
    private BigDecimal CHILD_CIF;

    /**
     * This field corresponds to the database column TRSCIFLIMITDET_TRX.REVALUATION_RATE
     */
    private BigDecimal REVALUATION_RATE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCIFLIMITDET_TRX.TRS_TYPE
     *
     * @return the value of TRSCIFLIMITDET_TRX.TRS_TYPE
     */
    public String getTRS_TYPE() {
        return TRS_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCIFLIMITDET_TRX.TRS_TYPE
     *
     * @param TRS_TYPE the value for TRSCIFLIMITDET_TRX.TRS_TYPE
     */
    public void setTRS_TYPE(String TRS_TYPE) {
        this.TRS_TYPE = TRS_TYPE == null ? null : TRS_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCIFLIMITDET_TRX.TRS_NO
     *
     * @return the value of TRSCIFLIMITDET_TRX.TRS_NO
     */
    public BigDecimal getTRS_NO() {
        return TRS_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCIFLIMITDET_TRX.TRS_NO
     *
     * @param TRS_NO the value for TRSCIFLIMITDET_TRX.TRS_NO
     */
    public void setTRS_NO(BigDecimal TRS_NO) {
        this.TRS_NO = TRS_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCIFLIMITDET_TRX.TRADE_DATE
     *
     * @return the value of TRSCIFLIMITDET_TRX.TRADE_DATE
     */
    public Date getTRADE_DATE() {
        return TRADE_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCIFLIMITDET_TRX.TRADE_DATE
     *
     * @param TRADE_DATE the value for TRSCIFLIMITDET_TRX.TRADE_DATE
     */
    public void setTRADE_DATE(Date TRADE_DATE) {
        this.TRADE_DATE = TRADE_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCIFLIMITDET_TRX.AMOUNT_TYPE
     *
     * @return the value of TRSCIFLIMITDET_TRX.AMOUNT_TYPE
     */
    public String getAMOUNT_TYPE() {
        return AMOUNT_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCIFLIMITDET_TRX.AMOUNT_TYPE
     *
     * @param AMOUNT_TYPE the value for TRSCIFLIMITDET_TRX.AMOUNT_TYPE
     */
    public void setAMOUNT_TYPE(String AMOUNT_TYPE) {
        this.AMOUNT_TYPE = AMOUNT_TYPE == null ? null : AMOUNT_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCIFLIMITDET_TRX.AMOUNT
     *
     * @return the value of TRSCIFLIMITDET_TRX.AMOUNT
     */
    public BigDecimal getAMOUNT() {
        return AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCIFLIMITDET_TRX.AMOUNT
     *
     * @param AMOUNT the value for TRSCIFLIMITDET_TRX.AMOUNT
     */
    public void setAMOUNT(BigDecimal AMOUNT) {
        this.AMOUNT = AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCIFLIMITDET_TRX.SWAP_YN
     *
     * @return the value of TRSCIFLIMITDET_TRX.SWAP_YN
     */
    public String getSWAP_YN() {
        return SWAP_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCIFLIMITDET_TRX.SWAP_YN
     *
     * @param SWAP_YN the value for TRSCIFLIMITDET_TRX.SWAP_YN
     */
    public void setSWAP_YN(String SWAP_YN) {
        this.SWAP_YN = SWAP_YN == null ? null : SWAP_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCIFLIMITDET_TRX.LIMIT_EXCEED_AMOUNT
     *
     * @return the value of TRSCIFLIMITDET_TRX.LIMIT_EXCEED_AMOUNT
     */
    public BigDecimal getLIMIT_EXCEED_AMOUNT() {
        return LIMIT_EXCEED_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCIFLIMITDET_TRX.LIMIT_EXCEED_AMOUNT
     *
     * @param LIMIT_EXCEED_AMOUNT the value for TRSCIFLIMITDET_TRX.LIMIT_EXCEED_AMOUNT
     */
    public void setLIMIT_EXCEED_AMOUNT(BigDecimal LIMIT_EXCEED_AMOUNT) {
        this.LIMIT_EXCEED_AMOUNT = LIMIT_EXCEED_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCIFLIMITDET_TRX.SERVER_DATE
     *
     * @return the value of TRSCIFLIMITDET_TRX.SERVER_DATE
     */
    public Date getSERVER_DATE() {
        return SERVER_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCIFLIMITDET_TRX.SERVER_DATE
     *
     * @param SERVER_DATE the value for TRSCIFLIMITDET_TRX.SERVER_DATE
     */
    public void setSERVER_DATE(Date SERVER_DATE) {
        this.SERVER_DATE = SERVER_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCIFLIMITDET_TRX.AMOUNT_IN_DEAL_CY
     *
     * @return the value of TRSCIFLIMITDET_TRX.AMOUNT_IN_DEAL_CY
     */
    public BigDecimal getAMOUNT_IN_DEAL_CY() {
        return AMOUNT_IN_DEAL_CY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCIFLIMITDET_TRX.AMOUNT_IN_DEAL_CY
     *
     * @param AMOUNT_IN_DEAL_CY the value for TRSCIFLIMITDET_TRX.AMOUNT_IN_DEAL_CY
     */
    public void setAMOUNT_IN_DEAL_CY(BigDecimal AMOUNT_IN_DEAL_CY) {
        this.AMOUNT_IN_DEAL_CY = AMOUNT_IN_DEAL_CY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCIFLIMITDET_TRX.CHILD_CIF
     *
     * @return the value of TRSCIFLIMITDET_TRX.CHILD_CIF
     */
    public BigDecimal getCHILD_CIF() {
        return CHILD_CIF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCIFLIMITDET_TRX.CHILD_CIF
     *
     * @param CHILD_CIF the value for TRSCIFLIMITDET_TRX.CHILD_CIF
     */
    public void setCHILD_CIF(BigDecimal CHILD_CIF) {
        this.CHILD_CIF = CHILD_CIF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCIFLIMITDET_TRX.REVALUATION_RATE
     *
     * @return the value of TRSCIFLIMITDET_TRX.REVALUATION_RATE
     */
    public BigDecimal getREVALUATION_RATE() {
        return REVALUATION_RATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCIFLIMITDET_TRX.REVALUATION_RATE
     *
     * @param REVALUATION_RATE the value for TRSCIFLIMITDET_TRX.REVALUATION_RATE
     */
    public void setREVALUATION_RATE(BigDecimal REVALUATION_RATE) {
        this.REVALUATION_RATE = REVALUATION_RATE;
    }
}