package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class TRSCONTRIB_BLOCK_HISTORYVO extends TRSCONTRIB_BLOCK_HISTORYVOKey {
    /**
     * This field corresponds to the database column TRSCONTRIB_BLOCK_HISTORY.CTS_TRS_NO
     */
    private BigDecimal CTS_TRS_NO;

    /**
     * This field corresponds to the database column TRSCONTRIB_BLOCK_HISTORY.TRSDET_LINE_NO
     */
    private BigDecimal TRSDET_LINE_NO;

    /**
     * This field corresponds to the database column TRSCONTRIB_BLOCK_HISTORY.TRS_TYPE
     */
    private String TRS_TYPE;

    /**
     * This field corresponds to the database column TRSCONTRIB_BLOCK_HISTORY.STATUS
     */
    private String STATUS;

    /**
     * This field corresponds to the database column TRSCONTRIB_BLOCK_HISTORY.VALUE_DATE
     */
    private Date VALUE_DATE;

    /**
     * This field corresponds to the database column TRSCONTRIB_BLOCK_HISTORY.SERVER_APPROVED_DATE
     */
    private Date SERVER_APPROVED_DATE;

    /**
     * This field corresponds to the database column TRSCONTRIB_BLOCK_HISTORY.SERVER_RVERSED_DATE
     */
    private Date SERVER_RVERSED_DATE;

    /**
     * This field corresponds to the database column TRSCONTRIB_BLOCK_HISTORY.ADD_STRING1
     */
    private String ADD_STRING1;

    /**
     * This field corresponds to the database column TRSCONTRIB_BLOCK_HISTORY.ADD_STRING2
     */
    private String ADD_STRING2;

    /**
     * This field corresponds to the database column TRSCONTRIB_BLOCK_HISTORY.USER_ID
     */
    private String USER_ID;

    /**
     * This field corresponds to the database column TRSCONTRIB_BLOCK_HISTORY.USER_AMENDED
     */
    private String USER_AMENDED;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCONTRIB_BLOCK_HISTORY.CTS_TRS_NO
     *
     * @return the value of TRSCONTRIB_BLOCK_HISTORY.CTS_TRS_NO
     */
    public BigDecimal getCTS_TRS_NO() {
        return CTS_TRS_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCONTRIB_BLOCK_HISTORY.CTS_TRS_NO
     *
     * @param CTS_TRS_NO the value for TRSCONTRIB_BLOCK_HISTORY.CTS_TRS_NO
     */
    public void setCTS_TRS_NO(BigDecimal CTS_TRS_NO) {
        this.CTS_TRS_NO = CTS_TRS_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCONTRIB_BLOCK_HISTORY.TRSDET_LINE_NO
     *
     * @return the value of TRSCONTRIB_BLOCK_HISTORY.TRSDET_LINE_NO
     */
    public BigDecimal getTRSDET_LINE_NO() {
        return TRSDET_LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCONTRIB_BLOCK_HISTORY.TRSDET_LINE_NO
     *
     * @param TRSDET_LINE_NO the value for TRSCONTRIB_BLOCK_HISTORY.TRSDET_LINE_NO
     */
    public void setTRSDET_LINE_NO(BigDecimal TRSDET_LINE_NO) {
        this.TRSDET_LINE_NO = TRSDET_LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCONTRIB_BLOCK_HISTORY.TRS_TYPE
     *
     * @return the value of TRSCONTRIB_BLOCK_HISTORY.TRS_TYPE
     */
    public String getTRS_TYPE() {
        return TRS_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCONTRIB_BLOCK_HISTORY.TRS_TYPE
     *
     * @param TRS_TYPE the value for TRSCONTRIB_BLOCK_HISTORY.TRS_TYPE
     */
    public void setTRS_TYPE(String TRS_TYPE) {
        this.TRS_TYPE = TRS_TYPE == null ? null : TRS_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCONTRIB_BLOCK_HISTORY.STATUS
     *
     * @return the value of TRSCONTRIB_BLOCK_HISTORY.STATUS
     */
    public String getSTATUS() {
        return STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCONTRIB_BLOCK_HISTORY.STATUS
     *
     * @param STATUS the value for TRSCONTRIB_BLOCK_HISTORY.STATUS
     */
    public void setSTATUS(String STATUS) {
        this.STATUS = STATUS == null ? null : STATUS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCONTRIB_BLOCK_HISTORY.VALUE_DATE
     *
     * @return the value of TRSCONTRIB_BLOCK_HISTORY.VALUE_DATE
     */
    public Date getVALUE_DATE() {
        return VALUE_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCONTRIB_BLOCK_HISTORY.VALUE_DATE
     *
     * @param VALUE_DATE the value for TRSCONTRIB_BLOCK_HISTORY.VALUE_DATE
     */
    public void setVALUE_DATE(Date VALUE_DATE) {
        this.VALUE_DATE = VALUE_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCONTRIB_BLOCK_HISTORY.SERVER_APPROVED_DATE
     *
     * @return the value of TRSCONTRIB_BLOCK_HISTORY.SERVER_APPROVED_DATE
     */
    public Date getSERVER_APPROVED_DATE() {
        return SERVER_APPROVED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCONTRIB_BLOCK_HISTORY.SERVER_APPROVED_DATE
     *
     * @param SERVER_APPROVED_DATE the value for TRSCONTRIB_BLOCK_HISTORY.SERVER_APPROVED_DATE
     */
    public void setSERVER_APPROVED_DATE(Date SERVER_APPROVED_DATE) {
        this.SERVER_APPROVED_DATE = SERVER_APPROVED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCONTRIB_BLOCK_HISTORY.SERVER_RVERSED_DATE
     *
     * @return the value of TRSCONTRIB_BLOCK_HISTORY.SERVER_RVERSED_DATE
     */
    public Date getSERVER_RVERSED_DATE() {
        return SERVER_RVERSED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCONTRIB_BLOCK_HISTORY.SERVER_RVERSED_DATE
     *
     * @param SERVER_RVERSED_DATE the value for TRSCONTRIB_BLOCK_HISTORY.SERVER_RVERSED_DATE
     */
    public void setSERVER_RVERSED_DATE(Date SERVER_RVERSED_DATE) {
        this.SERVER_RVERSED_DATE = SERVER_RVERSED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCONTRIB_BLOCK_HISTORY.ADD_STRING1
     *
     * @return the value of TRSCONTRIB_BLOCK_HISTORY.ADD_STRING1
     */
    public String getADD_STRING1() {
        return ADD_STRING1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCONTRIB_BLOCK_HISTORY.ADD_STRING1
     *
     * @param ADD_STRING1 the value for TRSCONTRIB_BLOCK_HISTORY.ADD_STRING1
     */
    public void setADD_STRING1(String ADD_STRING1) {
        this.ADD_STRING1 = ADD_STRING1 == null ? null : ADD_STRING1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCONTRIB_BLOCK_HISTORY.ADD_STRING2
     *
     * @return the value of TRSCONTRIB_BLOCK_HISTORY.ADD_STRING2
     */
    public String getADD_STRING2() {
        return ADD_STRING2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCONTRIB_BLOCK_HISTORY.ADD_STRING2
     *
     * @param ADD_STRING2 the value for TRSCONTRIB_BLOCK_HISTORY.ADD_STRING2
     */
    public void setADD_STRING2(String ADD_STRING2) {
        this.ADD_STRING2 = ADD_STRING2 == null ? null : ADD_STRING2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCONTRIB_BLOCK_HISTORY.USER_ID
     *
     * @return the value of TRSCONTRIB_BLOCK_HISTORY.USER_ID
     */
    public String getUSER_ID() {
        return USER_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCONTRIB_BLOCK_HISTORY.USER_ID
     *
     * @param USER_ID the value for TRSCONTRIB_BLOCK_HISTORY.USER_ID
     */
    public void setUSER_ID(String USER_ID) {
        this.USER_ID = USER_ID == null ? null : USER_ID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCONTRIB_BLOCK_HISTORY.USER_AMENDED
     *
     * @return the value of TRSCONTRIB_BLOCK_HISTORY.USER_AMENDED
     */
    public String getUSER_AMENDED() {
        return USER_AMENDED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCONTRIB_BLOCK_HISTORY.USER_AMENDED
     *
     * @param USER_AMENDED the value for TRSCONTRIB_BLOCK_HISTORY.USER_AMENDED
     */
    public void setUSER_AMENDED(String USER_AMENDED) {
        this.USER_AMENDED = USER_AMENDED == null ? null : USER_AMENDED.trim();
    }
}