package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class TRSCOMMITMENT_DETAILVO extends TRSCOMMITMENT_DETAILVOKey {
    /**
     * This field corresponds to the database column TRSCOMMITMENT_DETAIL.TRANSACTION_TYPE
     */
    private String TRANSACTION_TYPE;

    /**
     * This field corresponds to the database column TRSCOMMITMENT_DETAIL.TRANSACTION_STATUS
     */
    private String TRANSACTION_STATUS;

    /**
     * This field corresponds to the database column TRSCOMMITMENT_DETAIL.CIF_NO
     */
    private BigDecimal CIF_NO;

    /**
     * This field corresponds to the database column TRSCOMMITMENT_DETAIL.PRODUCT_TYPE
     */
    private BigDecimal PRODUCT_TYPE;

    /**
     * This field corresponds to the database column TRSCOMMITMENT_DETAIL.TRADE_DATE
     */
    private Date TRADE_DATE;

    /**
     * This field corresponds to the database column TRSCOMMITMENT_DETAIL.VALUE_DATE
     */
    private Date VALUE_DATE;

    /**
     * This field corresponds to the database column TRSCOMMITMENT_DETAIL.MATURITY_DATE
     */
    private Date MATURITY_DATE;

    /**
     * This field corresponds to the database column TRSCOMMITMENT_DETAIL.TRANSACTION_CURRENCY
     */
    private BigDecimal TRANSACTION_CURRENCY;

    /**
     * This field corresponds to the database column TRSCOMMITMENT_DETAIL.DEAL_AMOUNT
     */
    private BigDecimal DEAL_AMOUNT;

    /**
     * This field corresponds to the database column TRSCOMMITMENT_DETAIL.DEAL_AMOUNT_CV
     */
    private BigDecimal DEAL_AMOUNT_CV;

    /**
     * This field corresponds to the database column TRSCOMMITMENT_DETAIL.YIELD
     */
    private BigDecimal YIELD;

    /**
     * This field corresponds to the database column TRSCOMMITMENT_DETAIL.REFERENCE
     */
    private String REFERENCE;

    /**
     * This field corresponds to the database column TRSCOMMITMENT_DETAIL.APPROVE_YN
     */
    private String APPROVE_YN;

    /**
     * This field corresponds to the database column TRSCOMMITMENT_DETAIL.CANCEL_YN
     */
    private String CANCEL_YN;

    /**
     * This field corresponds to the database column TRSCOMMITMENT_DETAIL.CLEAR_YN
     */
    private String CLEAR_YN;

    /**
     * This field corresponds to the database column TRSCOMMITMENT_DETAIL.CREATED_BY
     */
    private String CREATED_BY;

    /**
     * This field corresponds to the database column TRSCOMMITMENT_DETAIL.MODIFIED_BY
     */
    private String MODIFIED_BY;

    /**
     * This field corresponds to the database column TRSCOMMITMENT_DETAIL.APPROVED_BY
     */
    private String APPROVED_BY;

    /**
     * This field corresponds to the database column TRSCOMMITMENT_DETAIL.DELETED_BY
     */
    private String DELETED_BY;

    /**
     * This field corresponds to the database column TRSCOMMITMENT_DETAIL.DATE_CREATED
     */
    private Date DATE_CREATED;

    /**
     * This field corresponds to the database column TRSCOMMITMENT_DETAIL.DATE_MODIFIED
     */
    private Date DATE_MODIFIED;

    /**
     * This field corresponds to the database column TRSCOMMITMENT_DETAIL.DATE_DELETED
     */
    private Date DATE_DELETED;

    /**
     * This field corresponds to the database column TRSCOMMITMENT_DETAIL.DATE_APPROVED
     */
    private Date DATE_APPROVED;

    /**
     * This field corresponds to the database column TRSCOMMITMENT_DETAIL.VERIFY_STATUS
     */
    private String VERIFY_STATUS;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCOMMITMENT_DETAIL.TRANSACTION_TYPE
     *
     * @return the value of TRSCOMMITMENT_DETAIL.TRANSACTION_TYPE
     */
    public String getTRANSACTION_TYPE() {
        return TRANSACTION_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCOMMITMENT_DETAIL.TRANSACTION_TYPE
     *
     * @param TRANSACTION_TYPE the value for TRSCOMMITMENT_DETAIL.TRANSACTION_TYPE
     */
    public void setTRANSACTION_TYPE(String TRANSACTION_TYPE) {
        this.TRANSACTION_TYPE = TRANSACTION_TYPE == null ? null : TRANSACTION_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCOMMITMENT_DETAIL.TRANSACTION_STATUS
     *
     * @return the value of TRSCOMMITMENT_DETAIL.TRANSACTION_STATUS
     */
    public String getTRANSACTION_STATUS() {
        return TRANSACTION_STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCOMMITMENT_DETAIL.TRANSACTION_STATUS
     *
     * @param TRANSACTION_STATUS the value for TRSCOMMITMENT_DETAIL.TRANSACTION_STATUS
     */
    public void setTRANSACTION_STATUS(String TRANSACTION_STATUS) {
        this.TRANSACTION_STATUS = TRANSACTION_STATUS == null ? null : TRANSACTION_STATUS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCOMMITMENT_DETAIL.CIF_NO
     *
     * @return the value of TRSCOMMITMENT_DETAIL.CIF_NO
     */
    public BigDecimal getCIF_NO() {
        return CIF_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCOMMITMENT_DETAIL.CIF_NO
     *
     * @param CIF_NO the value for TRSCOMMITMENT_DETAIL.CIF_NO
     */
    public void setCIF_NO(BigDecimal CIF_NO) {
        this.CIF_NO = CIF_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCOMMITMENT_DETAIL.PRODUCT_TYPE
     *
     * @return the value of TRSCOMMITMENT_DETAIL.PRODUCT_TYPE
     */
    public BigDecimal getPRODUCT_TYPE() {
        return PRODUCT_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCOMMITMENT_DETAIL.PRODUCT_TYPE
     *
     * @param PRODUCT_TYPE the value for TRSCOMMITMENT_DETAIL.PRODUCT_TYPE
     */
    public void setPRODUCT_TYPE(BigDecimal PRODUCT_TYPE) {
        this.PRODUCT_TYPE = PRODUCT_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCOMMITMENT_DETAIL.TRADE_DATE
     *
     * @return the value of TRSCOMMITMENT_DETAIL.TRADE_DATE
     */
    public Date getTRADE_DATE() {
        return TRADE_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCOMMITMENT_DETAIL.TRADE_DATE
     *
     * @param TRADE_DATE the value for TRSCOMMITMENT_DETAIL.TRADE_DATE
     */
    public void setTRADE_DATE(Date TRADE_DATE) {
        this.TRADE_DATE = TRADE_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCOMMITMENT_DETAIL.VALUE_DATE
     *
     * @return the value of TRSCOMMITMENT_DETAIL.VALUE_DATE
     */
    public Date getVALUE_DATE() {
        return VALUE_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCOMMITMENT_DETAIL.VALUE_DATE
     *
     * @param VALUE_DATE the value for TRSCOMMITMENT_DETAIL.VALUE_DATE
     */
    public void setVALUE_DATE(Date VALUE_DATE) {
        this.VALUE_DATE = VALUE_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCOMMITMENT_DETAIL.MATURITY_DATE
     *
     * @return the value of TRSCOMMITMENT_DETAIL.MATURITY_DATE
     */
    public Date getMATURITY_DATE() {
        return MATURITY_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCOMMITMENT_DETAIL.MATURITY_DATE
     *
     * @param MATURITY_DATE the value for TRSCOMMITMENT_DETAIL.MATURITY_DATE
     */
    public void setMATURITY_DATE(Date MATURITY_DATE) {
        this.MATURITY_DATE = MATURITY_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCOMMITMENT_DETAIL.TRANSACTION_CURRENCY
     *
     * @return the value of TRSCOMMITMENT_DETAIL.TRANSACTION_CURRENCY
     */
    public BigDecimal getTRANSACTION_CURRENCY() {
        return TRANSACTION_CURRENCY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCOMMITMENT_DETAIL.TRANSACTION_CURRENCY
     *
     * @param TRANSACTION_CURRENCY the value for TRSCOMMITMENT_DETAIL.TRANSACTION_CURRENCY
     */
    public void setTRANSACTION_CURRENCY(BigDecimal TRANSACTION_CURRENCY) {
        this.TRANSACTION_CURRENCY = TRANSACTION_CURRENCY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCOMMITMENT_DETAIL.DEAL_AMOUNT
     *
     * @return the value of TRSCOMMITMENT_DETAIL.DEAL_AMOUNT
     */
    public BigDecimal getDEAL_AMOUNT() {
        return DEAL_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCOMMITMENT_DETAIL.DEAL_AMOUNT
     *
     * @param DEAL_AMOUNT the value for TRSCOMMITMENT_DETAIL.DEAL_AMOUNT
     */
    public void setDEAL_AMOUNT(BigDecimal DEAL_AMOUNT) {
        this.DEAL_AMOUNT = DEAL_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCOMMITMENT_DETAIL.DEAL_AMOUNT_CV
     *
     * @return the value of TRSCOMMITMENT_DETAIL.DEAL_AMOUNT_CV
     */
    public BigDecimal getDEAL_AMOUNT_CV() {
        return DEAL_AMOUNT_CV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCOMMITMENT_DETAIL.DEAL_AMOUNT_CV
     *
     * @param DEAL_AMOUNT_CV the value for TRSCOMMITMENT_DETAIL.DEAL_AMOUNT_CV
     */
    public void setDEAL_AMOUNT_CV(BigDecimal DEAL_AMOUNT_CV) {
        this.DEAL_AMOUNT_CV = DEAL_AMOUNT_CV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCOMMITMENT_DETAIL.YIELD
     *
     * @return the value of TRSCOMMITMENT_DETAIL.YIELD
     */
    public BigDecimal getYIELD() {
        return YIELD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCOMMITMENT_DETAIL.YIELD
     *
     * @param YIELD the value for TRSCOMMITMENT_DETAIL.YIELD
     */
    public void setYIELD(BigDecimal YIELD) {
        this.YIELD = YIELD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCOMMITMENT_DETAIL.REFERENCE
     *
     * @return the value of TRSCOMMITMENT_DETAIL.REFERENCE
     */
    public String getREFERENCE() {
        return REFERENCE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCOMMITMENT_DETAIL.REFERENCE
     *
     * @param REFERENCE the value for TRSCOMMITMENT_DETAIL.REFERENCE
     */
    public void setREFERENCE(String REFERENCE) {
        this.REFERENCE = REFERENCE == null ? null : REFERENCE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCOMMITMENT_DETAIL.APPROVE_YN
     *
     * @return the value of TRSCOMMITMENT_DETAIL.APPROVE_YN
     */
    public String getAPPROVE_YN() {
        return APPROVE_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCOMMITMENT_DETAIL.APPROVE_YN
     *
     * @param APPROVE_YN the value for TRSCOMMITMENT_DETAIL.APPROVE_YN
     */
    public void setAPPROVE_YN(String APPROVE_YN) {
        this.APPROVE_YN = APPROVE_YN == null ? null : APPROVE_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCOMMITMENT_DETAIL.CANCEL_YN
     *
     * @return the value of TRSCOMMITMENT_DETAIL.CANCEL_YN
     */
    public String getCANCEL_YN() {
        return CANCEL_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCOMMITMENT_DETAIL.CANCEL_YN
     *
     * @param CANCEL_YN the value for TRSCOMMITMENT_DETAIL.CANCEL_YN
     */
    public void setCANCEL_YN(String CANCEL_YN) {
        this.CANCEL_YN = CANCEL_YN == null ? null : CANCEL_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCOMMITMENT_DETAIL.CLEAR_YN
     *
     * @return the value of TRSCOMMITMENT_DETAIL.CLEAR_YN
     */
    public String getCLEAR_YN() {
        return CLEAR_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCOMMITMENT_DETAIL.CLEAR_YN
     *
     * @param CLEAR_YN the value for TRSCOMMITMENT_DETAIL.CLEAR_YN
     */
    public void setCLEAR_YN(String CLEAR_YN) {
        this.CLEAR_YN = CLEAR_YN == null ? null : CLEAR_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCOMMITMENT_DETAIL.CREATED_BY
     *
     * @return the value of TRSCOMMITMENT_DETAIL.CREATED_BY
     */
    public String getCREATED_BY() {
        return CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCOMMITMENT_DETAIL.CREATED_BY
     *
     * @param CREATED_BY the value for TRSCOMMITMENT_DETAIL.CREATED_BY
     */
    public void setCREATED_BY(String CREATED_BY) {
        this.CREATED_BY = CREATED_BY == null ? null : CREATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCOMMITMENT_DETAIL.MODIFIED_BY
     *
     * @return the value of TRSCOMMITMENT_DETAIL.MODIFIED_BY
     */
    public String getMODIFIED_BY() {
        return MODIFIED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCOMMITMENT_DETAIL.MODIFIED_BY
     *
     * @param MODIFIED_BY the value for TRSCOMMITMENT_DETAIL.MODIFIED_BY
     */
    public void setMODIFIED_BY(String MODIFIED_BY) {
        this.MODIFIED_BY = MODIFIED_BY == null ? null : MODIFIED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCOMMITMENT_DETAIL.APPROVED_BY
     *
     * @return the value of TRSCOMMITMENT_DETAIL.APPROVED_BY
     */
    public String getAPPROVED_BY() {
        return APPROVED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCOMMITMENT_DETAIL.APPROVED_BY
     *
     * @param APPROVED_BY the value for TRSCOMMITMENT_DETAIL.APPROVED_BY
     */
    public void setAPPROVED_BY(String APPROVED_BY) {
        this.APPROVED_BY = APPROVED_BY == null ? null : APPROVED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCOMMITMENT_DETAIL.DELETED_BY
     *
     * @return the value of TRSCOMMITMENT_DETAIL.DELETED_BY
     */
    public String getDELETED_BY() {
        return DELETED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCOMMITMENT_DETAIL.DELETED_BY
     *
     * @param DELETED_BY the value for TRSCOMMITMENT_DETAIL.DELETED_BY
     */
    public void setDELETED_BY(String DELETED_BY) {
        this.DELETED_BY = DELETED_BY == null ? null : DELETED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCOMMITMENT_DETAIL.DATE_CREATED
     *
     * @return the value of TRSCOMMITMENT_DETAIL.DATE_CREATED
     */
    public Date getDATE_CREATED() {
        return DATE_CREATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCOMMITMENT_DETAIL.DATE_CREATED
     *
     * @param DATE_CREATED the value for TRSCOMMITMENT_DETAIL.DATE_CREATED
     */
    public void setDATE_CREATED(Date DATE_CREATED) {
        this.DATE_CREATED = DATE_CREATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCOMMITMENT_DETAIL.DATE_MODIFIED
     *
     * @return the value of TRSCOMMITMENT_DETAIL.DATE_MODIFIED
     */
    public Date getDATE_MODIFIED() {
        return DATE_MODIFIED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCOMMITMENT_DETAIL.DATE_MODIFIED
     *
     * @param DATE_MODIFIED the value for TRSCOMMITMENT_DETAIL.DATE_MODIFIED
     */
    public void setDATE_MODIFIED(Date DATE_MODIFIED) {
        this.DATE_MODIFIED = DATE_MODIFIED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCOMMITMENT_DETAIL.DATE_DELETED
     *
     * @return the value of TRSCOMMITMENT_DETAIL.DATE_DELETED
     */
    public Date getDATE_DELETED() {
        return DATE_DELETED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCOMMITMENT_DETAIL.DATE_DELETED
     *
     * @param DATE_DELETED the value for TRSCOMMITMENT_DETAIL.DATE_DELETED
     */
    public void setDATE_DELETED(Date DATE_DELETED) {
        this.DATE_DELETED = DATE_DELETED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCOMMITMENT_DETAIL.DATE_APPROVED
     *
     * @return the value of TRSCOMMITMENT_DETAIL.DATE_APPROVED
     */
    public Date getDATE_APPROVED() {
        return DATE_APPROVED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCOMMITMENT_DETAIL.DATE_APPROVED
     *
     * @param DATE_APPROVED the value for TRSCOMMITMENT_DETAIL.DATE_APPROVED
     */
    public void setDATE_APPROVED(Date DATE_APPROVED) {
        this.DATE_APPROVED = DATE_APPROVED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCOMMITMENT_DETAIL.VERIFY_STATUS
     *
     * @return the value of TRSCOMMITMENT_DETAIL.VERIFY_STATUS
     */
    public String getVERIFY_STATUS() {
        return VERIFY_STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCOMMITMENT_DETAIL.VERIFY_STATUS
     *
     * @param VERIFY_STATUS the value for TRSCOMMITMENT_DETAIL.VERIFY_STATUS
     */
    public void setVERIFY_STATUS(String VERIFY_STATUS) {
        this.VERIFY_STATUS = VERIFY_STATUS == null ? null : VERIFY_STATUS.trim();
    }
}