package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class TRSCIFLIMIT_CHILDVOKey extends BaseVO {
    /**
     * This field corresponds to the database column TRSCIFLIMIT_CHILD.BRANCH_CODE
     */
    private BigDecimal BRANCH_CODE;

    /**
     * This field corresponds to the database column TRSCIFLIMIT_CHILD.CIF
     */
    private BigDecimal CIF;

    /**
     * This field corresponds to the database column TRSCIFLIMIT_CHILD.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column TRSCIFLIMIT_CHILD.PARENT_CIF
     */
    private BigDecimal PARENT_CIF;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCIFLIMIT_CHILD.BRANCH_CODE
     *
     * @return the value of TRSCIFLIMIT_CHILD.BRANCH_CODE
     */
    public BigDecimal getBRANCH_CODE() {
        return BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCIFLIMIT_CHILD.BRANCH_CODE
     *
     * @param BRANCH_CODE the value for TRSCIFLIMIT_CHILD.BRANCH_CODE
     */
    public void setBRANCH_CODE(BigDecimal BRANCH_CODE) {
        this.BRANCH_CODE = BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCIFLIMIT_CHILD.CIF
     *
     * @return the value of TRSCIFLIMIT_CHILD.CIF
     */
    public BigDecimal getCIF() {
        return CIF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCIFLIMIT_CHILD.CIF
     *
     * @param CIF the value for TRSCIFLIMIT_CHILD.CIF
     */
    public void setCIF(BigDecimal CIF) {
        this.CIF = CIF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCIFLIMIT_CHILD.COMP_CODE
     *
     * @return the value of TRSCIFLIMIT_CHILD.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCIFLIMIT_CHILD.COMP_CODE
     *
     * @param COMP_CODE the value for TRSCIFLIMIT_CHILD.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCIFLIMIT_CHILD.PARENT_CIF
     *
     * @return the value of TRSCIFLIMIT_CHILD.PARENT_CIF
     */
    public BigDecimal getPARENT_CIF() {
        return PARENT_CIF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCIFLIMIT_CHILD.PARENT_CIF
     *
     * @param PARENT_CIF the value for TRSCIFLIMIT_CHILD.PARENT_CIF
     */
    public void setPARENT_CIF(BigDecimal PARENT_CIF) {
        this.PARENT_CIF = PARENT_CIF;
    }
}