package com.path.dbmaps.vo;

public class TRSCONTROLVO extends TRSCONTROLVOKey {
    /**
     * This field corresponds to the database column TRSCONTROL.CHANGE_MULTDIV
     */
    private String CHANGE_MULTDIV;

    /**
     * This field corresponds to the database column TRSCONTROL.USE_TRX_REF
     */
    private String USE_TRX_REF;

    /**
     * This field corresponds to the database column TRSCONTROL.CONSIDER_EXCH_RAT
     */
    private String CONSIDER_EXCH_RAT;

    /**
     * This field corresponds to the database column TRSCONTROL.CHECK_REF
     */
    private String CHECK_REF;

    /**
     * This field corresponds to the database column TRSCONTROL.ACROSS_BR
     */
    private String ACROSS_BR;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCONTROL.CHANGE_MULTDIV
     *
     * @return the value of TRSCONTROL.CHANGE_MULTDIV
     */
    public String getCHANGE_MULTDIV() {
        return CHANGE_MULTDIV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCONTROL.CHANGE_MULTDIV
     *
     * @param CHANGE_MULTDIV the value for TRSCONTROL.CHANGE_MULTDIV
     */
    public void setCHANGE_MULTDIV(String CHANGE_MULTDIV) {
        this.CHANGE_MULTDIV = CHANGE_MULTDIV == null ? null : CHANGE_MULTDIV.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCONTROL.USE_TRX_REF
     *
     * @return the value of TRSCONTROL.USE_TRX_REF
     */
    public String getUSE_TRX_REF() {
        return USE_TRX_REF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCONTROL.USE_TRX_REF
     *
     * @param USE_TRX_REF the value for TRSCONTROL.USE_TRX_REF
     */
    public void setUSE_TRX_REF(String USE_TRX_REF) {
        this.USE_TRX_REF = USE_TRX_REF == null ? null : USE_TRX_REF.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCONTROL.CONSIDER_EXCH_RAT
     *
     * @return the value of TRSCONTROL.CONSIDER_EXCH_RAT
     */
    public String getCONSIDER_EXCH_RAT() {
        return CONSIDER_EXCH_RAT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCONTROL.CONSIDER_EXCH_RAT
     *
     * @param CONSIDER_EXCH_RAT the value for TRSCONTROL.CONSIDER_EXCH_RAT
     */
    public void setCONSIDER_EXCH_RAT(String CONSIDER_EXCH_RAT) {
        this.CONSIDER_EXCH_RAT = CONSIDER_EXCH_RAT == null ? null : CONSIDER_EXCH_RAT.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCONTROL.CHECK_REF
     *
     * @return the value of TRSCONTROL.CHECK_REF
     */
    public String getCHECK_REF() {
        return CHECK_REF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCONTROL.CHECK_REF
     *
     * @param CHECK_REF the value for TRSCONTROL.CHECK_REF
     */
    public void setCHECK_REF(String CHECK_REF) {
        this.CHECK_REF = CHECK_REF == null ? null : CHECK_REF.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCONTROL.ACROSS_BR
     *
     * @return the value of TRSCONTROL.ACROSS_BR
     */
    public String getACROSS_BR() {
        return ACROSS_BR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCONTROL.ACROSS_BR
     *
     * @param ACROSS_BR the value for TRSCONTROL.ACROSS_BR
     */
    public void setACROSS_BR(String ACROSS_BR) {
        this.ACROSS_BR = ACROSS_BR == null ? null : ACROSS_BR.trim();
    }
}