package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class TRSCIFLIMITDET_DEAL_CYVOKey extends BaseVO {
    /**
     * This field corresponds to the database column TRSCIFLIMITDET_DEAL_CY.BRANCH
     */
    private BigDecimal BRANCH;

    /**
     * This field corresponds to the database column TRSCIFLIMITDET_DEAL_CY.CIF
     */
    private BigDecimal CIF;

    /**
     * This field corresponds to the database column TRSCIFLIMITDET_DEAL_CY.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column TRSCIFLIMITDET_DEAL_CY.LIMIT_SERIAL_NO
     */
    private BigDecimal LIMIT_SERIAL_NO;

    /**
     * This field corresponds to the database column TRSCIFLIMITDET_DEAL_CY.LINE_NO
     */
    private BigDecimal LINE_NO;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCIFLIMITDET_DEAL_CY.BRANCH
     *
     * @return the value of TRSCIFLIMITDET_DEAL_CY.BRANCH
     */
    public BigDecimal getBRANCH() {
        return BRANCH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCIFLIMITDET_DEAL_CY.BRANCH
     *
     * @param BRANCH the value for TRSCIFLIMITDET_DEAL_CY.BRANCH
     */
    public void setBRANCH(BigDecimal BRANCH) {
        this.BRANCH = BRANCH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCIFLIMITDET_DEAL_CY.CIF
     *
     * @return the value of TRSCIFLIMITDET_DEAL_CY.CIF
     */
    public BigDecimal getCIF() {
        return CIF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCIFLIMITDET_DEAL_CY.CIF
     *
     * @param CIF the value for TRSCIFLIMITDET_DEAL_CY.CIF
     */
    public void setCIF(BigDecimal CIF) {
        this.CIF = CIF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCIFLIMITDET_DEAL_CY.COMP_CODE
     *
     * @return the value of TRSCIFLIMITDET_DEAL_CY.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCIFLIMITDET_DEAL_CY.COMP_CODE
     *
     * @param COMP_CODE the value for TRSCIFLIMITDET_DEAL_CY.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCIFLIMITDET_DEAL_CY.LIMIT_SERIAL_NO
     *
     * @return the value of TRSCIFLIMITDET_DEAL_CY.LIMIT_SERIAL_NO
     */
    public BigDecimal getLIMIT_SERIAL_NO() {
        return LIMIT_SERIAL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCIFLIMITDET_DEAL_CY.LIMIT_SERIAL_NO
     *
     * @param LIMIT_SERIAL_NO the value for TRSCIFLIMITDET_DEAL_CY.LIMIT_SERIAL_NO
     */
    public void setLIMIT_SERIAL_NO(BigDecimal LIMIT_SERIAL_NO) {
        this.LIMIT_SERIAL_NO = LIMIT_SERIAL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCIFLIMITDET_DEAL_CY.LINE_NO
     *
     * @return the value of TRSCIFLIMITDET_DEAL_CY.LINE_NO
     */
    public BigDecimal getLINE_NO() {
        return LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCIFLIMITDET_DEAL_CY.LINE_NO
     *
     * @param LINE_NO the value for TRSCIFLIMITDET_DEAL_CY.LINE_NO
     */
    public void setLINE_NO(BigDecimal LINE_NO) {
        this.LINE_NO = LINE_NO;
    }
}