package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class TRSCLASS_NOSTRO_ACCOUNTSVO extends TRSCLASS_NOSTRO_ACCOUNTSVOKey {
    /**
     * This field corresponds to the database column TRSCLASS_NOSTRO_ACCOUNTS.ACC_BRANCH
     */
    private BigDecimal ACC_BRANCH;

    /**
     * This field corresponds to the database column TRSCLASS_NOSTRO_ACCOUNTS.ACC_CURRENCY
     */
    private BigDecimal ACC_CURRENCY;

    /**
     * This field corresponds to the database column TRSCLASS_NOSTRO_ACCOUNTS.ACC_GL_CODE
     */
    private BigDecimal ACC_GL_CODE;

    /**
     * This field corresponds to the database column TRSCLASS_NOSTRO_ACCOUNTS.ACC_CIF_SUB_NO
     */
    private BigDecimal ACC_CIF_SUB_NO;

    /**
     * This field corresponds to the database column TRSCLASS_NOSTRO_ACCOUNTS.ACC_SL_NO
     */
    private BigDecimal ACC_SL_NO;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCLASS_NOSTRO_ACCOUNTS.ACC_BRANCH
     *
     * @return the value of TRSCLASS_NOSTRO_ACCOUNTS.ACC_BRANCH
     */
    public BigDecimal getACC_BRANCH() {
        return ACC_BRANCH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCLASS_NOSTRO_ACCOUNTS.ACC_BRANCH
     *
     * @param ACC_BRANCH the value for TRSCLASS_NOSTRO_ACCOUNTS.ACC_BRANCH
     */
    public void setACC_BRANCH(BigDecimal ACC_BRANCH) {
        this.ACC_BRANCH = ACC_BRANCH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCLASS_NOSTRO_ACCOUNTS.ACC_CURRENCY
     *
     * @return the value of TRSCLASS_NOSTRO_ACCOUNTS.ACC_CURRENCY
     */
    public BigDecimal getACC_CURRENCY() {
        return ACC_CURRENCY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCLASS_NOSTRO_ACCOUNTS.ACC_CURRENCY
     *
     * @param ACC_CURRENCY the value for TRSCLASS_NOSTRO_ACCOUNTS.ACC_CURRENCY
     */
    public void setACC_CURRENCY(BigDecimal ACC_CURRENCY) {
        this.ACC_CURRENCY = ACC_CURRENCY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCLASS_NOSTRO_ACCOUNTS.ACC_GL_CODE
     *
     * @return the value of TRSCLASS_NOSTRO_ACCOUNTS.ACC_GL_CODE
     */
    public BigDecimal getACC_GL_CODE() {
        return ACC_GL_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCLASS_NOSTRO_ACCOUNTS.ACC_GL_CODE
     *
     * @param ACC_GL_CODE the value for TRSCLASS_NOSTRO_ACCOUNTS.ACC_GL_CODE
     */
    public void setACC_GL_CODE(BigDecimal ACC_GL_CODE) {
        this.ACC_GL_CODE = ACC_GL_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCLASS_NOSTRO_ACCOUNTS.ACC_CIF_SUB_NO
     *
     * @return the value of TRSCLASS_NOSTRO_ACCOUNTS.ACC_CIF_SUB_NO
     */
    public BigDecimal getACC_CIF_SUB_NO() {
        return ACC_CIF_SUB_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCLASS_NOSTRO_ACCOUNTS.ACC_CIF_SUB_NO
     *
     * @param ACC_CIF_SUB_NO the value for TRSCLASS_NOSTRO_ACCOUNTS.ACC_CIF_SUB_NO
     */
    public void setACC_CIF_SUB_NO(BigDecimal ACC_CIF_SUB_NO) {
        this.ACC_CIF_SUB_NO = ACC_CIF_SUB_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSCLASS_NOSTRO_ACCOUNTS.ACC_SL_NO
     *
     * @return the value of TRSCLASS_NOSTRO_ACCOUNTS.ACC_SL_NO
     */
    public BigDecimal getACC_SL_NO() {
        return ACC_SL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSCLASS_NOSTRO_ACCOUNTS.ACC_SL_NO
     *
     * @param ACC_SL_NO the value for TRSCLASS_NOSTRO_ACCOUNTS.ACC_SL_NO
     */
    public void setACC_SL_NO(BigDecimal ACC_SL_NO) {
        this.ACC_SL_NO = ACC_SL_NO;
    }
}