package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class TRSDEAL_SETTLEMENT_CHARGE_DETVOKey extends BaseVO {
    /**
     * This field corresponds to the database column TRSDEAL_SETTLEMENT_CHARGE_DET.BRANCH_CODE
     */
    private BigDecimal BRANCH_CODE;

    /**
     * This field corresponds to the database column TRSDEAL_SETTLEMENT_CHARGE_DET.CHARGE_LINE_NO
     */
    private BigDecimal CHARGE_LINE_NO;

    /**
     * This field corresponds to the database column TRSDEAL_SETTLEMENT_CHARGE_DET.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column TRSDEAL_SETTLEMENT_CHARGE_DET.PLAN_LINE_NO
     */
    private BigDecimal PLAN_LINE_NO;

    /**
     * This field corresponds to the database column TRSDEAL_SETTLEMENT_CHARGE_DET.PLAN_NBR
     */
    private BigDecimal PLAN_NBR;

    /**
     * This field corresponds to the database column TRSDEAL_SETTLEMENT_CHARGE_DET.PLAN_SEQ
     */
    private BigDecimal PLAN_SEQ;

    /**
     * This field corresponds to the database column TRSDEAL_SETTLEMENT_CHARGE_DET.SERIAL_NO
     */
    private BigDecimal SERIAL_NO;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_SETTLEMENT_CHARGE_DET.BRANCH_CODE
     *
     * @return the value of TRSDEAL_SETTLEMENT_CHARGE_DET.BRANCH_CODE
     */
    public BigDecimal getBRANCH_CODE() {
        return BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_SETTLEMENT_CHARGE_DET.BRANCH_CODE
     *
     * @param BRANCH_CODE the value for TRSDEAL_SETTLEMENT_CHARGE_DET.BRANCH_CODE
     */
    public void setBRANCH_CODE(BigDecimal BRANCH_CODE) {
        this.BRANCH_CODE = BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_SETTLEMENT_CHARGE_DET.CHARGE_LINE_NO
     *
     * @return the value of TRSDEAL_SETTLEMENT_CHARGE_DET.CHARGE_LINE_NO
     */
    public BigDecimal getCHARGE_LINE_NO() {
        return CHARGE_LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_SETTLEMENT_CHARGE_DET.CHARGE_LINE_NO
     *
     * @param CHARGE_LINE_NO the value for TRSDEAL_SETTLEMENT_CHARGE_DET.CHARGE_LINE_NO
     */
    public void setCHARGE_LINE_NO(BigDecimal CHARGE_LINE_NO) {
        this.CHARGE_LINE_NO = CHARGE_LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_SETTLEMENT_CHARGE_DET.COMP_CODE
     *
     * @return the value of TRSDEAL_SETTLEMENT_CHARGE_DET.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_SETTLEMENT_CHARGE_DET.COMP_CODE
     *
     * @param COMP_CODE the value for TRSDEAL_SETTLEMENT_CHARGE_DET.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_SETTLEMENT_CHARGE_DET.PLAN_LINE_NO
     *
     * @return the value of TRSDEAL_SETTLEMENT_CHARGE_DET.PLAN_LINE_NO
     */
    public BigDecimal getPLAN_LINE_NO() {
        return PLAN_LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_SETTLEMENT_CHARGE_DET.PLAN_LINE_NO
     *
     * @param PLAN_LINE_NO the value for TRSDEAL_SETTLEMENT_CHARGE_DET.PLAN_LINE_NO
     */
    public void setPLAN_LINE_NO(BigDecimal PLAN_LINE_NO) {
        this.PLAN_LINE_NO = PLAN_LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_SETTLEMENT_CHARGE_DET.PLAN_NBR
     *
     * @return the value of TRSDEAL_SETTLEMENT_CHARGE_DET.PLAN_NBR
     */
    public BigDecimal getPLAN_NBR() {
        return PLAN_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_SETTLEMENT_CHARGE_DET.PLAN_NBR
     *
     * @param PLAN_NBR the value for TRSDEAL_SETTLEMENT_CHARGE_DET.PLAN_NBR
     */
    public void setPLAN_NBR(BigDecimal PLAN_NBR) {
        this.PLAN_NBR = PLAN_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_SETTLEMENT_CHARGE_DET.PLAN_SEQ
     *
     * @return the value of TRSDEAL_SETTLEMENT_CHARGE_DET.PLAN_SEQ
     */
    public BigDecimal getPLAN_SEQ() {
        return PLAN_SEQ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_SETTLEMENT_CHARGE_DET.PLAN_SEQ
     *
     * @param PLAN_SEQ the value for TRSDEAL_SETTLEMENT_CHARGE_DET.PLAN_SEQ
     */
    public void setPLAN_SEQ(BigDecimal PLAN_SEQ) {
        this.PLAN_SEQ = PLAN_SEQ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_SETTLEMENT_CHARGE_DET.SERIAL_NO
     *
     * @return the value of TRSDEAL_SETTLEMENT_CHARGE_DET.SERIAL_NO
     */
    public BigDecimal getSERIAL_NO() {
        return SERIAL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_SETTLEMENT_CHARGE_DET.SERIAL_NO
     *
     * @param SERIAL_NO the value for TRSDEAL_SETTLEMENT_CHARGE_DET.SERIAL_NO
     */
    public void setSERIAL_NO(BigDecimal SERIAL_NO) {
        this.SERIAL_NO = SERIAL_NO;
    }
}