package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class TRSDEAL_LINKED_DOCUMENTVO extends TRSDEAL_LINKED_DOCUMENTVOKey {
    /**
     * This field corresponds to the database column TRSDEAL_LINKED_DOCUMENT.CURRENCY_CODE
     */
    private BigDecimal CURRENCY_CODE;

    /**
     * This field corresponds to the database column TRSDEAL_LINKED_DOCUMENT.AMOUNT
     */
    private BigDecimal AMOUNT;

    /**
     * This field corresponds to the database column TRSDEAL_LINKED_DOCUMENT.AVAILABLE_AMOUNT
     */
    private BigDecimal AVAILABLE_AMOUNT;

    /**
     * This field corresponds to the database column TRSDEAL_LINKED_DOCUMENT.ALLOCATED_AMOUNT
     */
    private BigDecimal ALLOCATED_AMOUNT;

    /**
     * This field corresponds to the database column TRSDEAL_LINKED_DOCUMENT.LOAN_REF_NO
     */
    private String LOAN_REF_NO;

    /**
     * This field corresponds to the database column TRSDEAL_LINKED_DOCUMENT.DP_DATE
     */
    private Date DP_DATE;

    /**
     * This field corresponds to the database column TRSDEAL_LINKED_DOCUMENT.EXPORT_DOCUMENT_YN
     */
    private String EXPORT_DOCUMENT_YN;

    /**
     * This field corresponds to the database column TRSDEAL_LINKED_DOCUMENT.EXPORT_LODGMENT_TRX_REF
     */
    private String EXPORT_LODGMENT_TRX_REF;

    /**
     * This field corresponds to the database column TRSDEAL_LINKED_DOCUMENT.CREATED_BY
     */
    private String CREATED_BY;

    /**
     * This field corresponds to the database column TRSDEAL_LINKED_DOCUMENT.CREATED_DATE
     */
    private Date CREATED_DATE;

    /**
     * This field corresponds to the database column TRSDEAL_LINKED_DOCUMENT.MODIFIED_BY
     */
    private String MODIFIED_BY;

    /**
     * This field corresponds to the database column TRSDEAL_LINKED_DOCUMENT.MODIFIED_DATE
     */
    private Date MODIFIED_DATE;

    /**
     * This field corresponds to the database column TRSDEAL_LINKED_DOCUMENT.DOCUMENT_NAME
     */
    private String DOCUMENT_NAME;

    /**
     * This field corresponds to the database column TRSDEAL_LINKED_DOCUMENT.ALLOCATED_CV_AMOUNT
     */
    private BigDecimal ALLOCATED_CV_AMOUNT;

    /**
     * This field corresponds to the database column TRSDEAL_LINKED_DOCUMENT.ALLOCATED_FC_AMOUNT
     */
    private BigDecimal ALLOCATED_FC_AMOUNT;

    /**
     * This field corresponds to the database column TRSDEAL_LINKED_DOCUMENT.AVAILABLE_CV_AMOUNT
     */
    private BigDecimal AVAILABLE_CV_AMOUNT;

    /**
     * This field corresponds to the database column TRSDEAL_LINKED_DOCUMENT.AVAILABLE_FC_AMOUNT
     */
    private BigDecimal AVAILABLE_FC_AMOUNT;

    /**
     * This field corresponds to the database column TRSDEAL_LINKED_DOCUMENT.EXCHANGE_RATE
     */
    private BigDecimal EXCHANGE_RATE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_LINKED_DOCUMENT.CURRENCY_CODE
     *
     * @return the value of TRSDEAL_LINKED_DOCUMENT.CURRENCY_CODE
     */
    public BigDecimal getCURRENCY_CODE() {
        return CURRENCY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_LINKED_DOCUMENT.CURRENCY_CODE
     *
     * @param CURRENCY_CODE the value for TRSDEAL_LINKED_DOCUMENT.CURRENCY_CODE
     */
    public void setCURRENCY_CODE(BigDecimal CURRENCY_CODE) {
        this.CURRENCY_CODE = CURRENCY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_LINKED_DOCUMENT.AMOUNT
     *
     * @return the value of TRSDEAL_LINKED_DOCUMENT.AMOUNT
     */
    public BigDecimal getAMOUNT() {
        return AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_LINKED_DOCUMENT.AMOUNT
     *
     * @param AMOUNT the value for TRSDEAL_LINKED_DOCUMENT.AMOUNT
     */
    public void setAMOUNT(BigDecimal AMOUNT) {
        this.AMOUNT = AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_LINKED_DOCUMENT.AVAILABLE_AMOUNT
     *
     * @return the value of TRSDEAL_LINKED_DOCUMENT.AVAILABLE_AMOUNT
     */
    public BigDecimal getAVAILABLE_AMOUNT() {
        return AVAILABLE_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_LINKED_DOCUMENT.AVAILABLE_AMOUNT
     *
     * @param AVAILABLE_AMOUNT the value for TRSDEAL_LINKED_DOCUMENT.AVAILABLE_AMOUNT
     */
    public void setAVAILABLE_AMOUNT(BigDecimal AVAILABLE_AMOUNT) {
        this.AVAILABLE_AMOUNT = AVAILABLE_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_LINKED_DOCUMENT.ALLOCATED_AMOUNT
     *
     * @return the value of TRSDEAL_LINKED_DOCUMENT.ALLOCATED_AMOUNT
     */
    public BigDecimal getALLOCATED_AMOUNT() {
        return ALLOCATED_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_LINKED_DOCUMENT.ALLOCATED_AMOUNT
     *
     * @param ALLOCATED_AMOUNT the value for TRSDEAL_LINKED_DOCUMENT.ALLOCATED_AMOUNT
     */
    public void setALLOCATED_AMOUNT(BigDecimal ALLOCATED_AMOUNT) {
        this.ALLOCATED_AMOUNT = ALLOCATED_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_LINKED_DOCUMENT.LOAN_REF_NO
     *
     * @return the value of TRSDEAL_LINKED_DOCUMENT.LOAN_REF_NO
     */
    public String getLOAN_REF_NO() {
        return LOAN_REF_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_LINKED_DOCUMENT.LOAN_REF_NO
     *
     * @param LOAN_REF_NO the value for TRSDEAL_LINKED_DOCUMENT.LOAN_REF_NO
     */
    public void setLOAN_REF_NO(String LOAN_REF_NO) {
        this.LOAN_REF_NO = LOAN_REF_NO == null ? null : LOAN_REF_NO.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_LINKED_DOCUMENT.DP_DATE
     *
     * @return the value of TRSDEAL_LINKED_DOCUMENT.DP_DATE
     */
    public Date getDP_DATE() {
        return DP_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_LINKED_DOCUMENT.DP_DATE
     *
     * @param DP_DATE the value for TRSDEAL_LINKED_DOCUMENT.DP_DATE
     */
    public void setDP_DATE(Date DP_DATE) {
        this.DP_DATE = DP_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_LINKED_DOCUMENT.EXPORT_DOCUMENT_YN
     *
     * @return the value of TRSDEAL_LINKED_DOCUMENT.EXPORT_DOCUMENT_YN
     */
    public String getEXPORT_DOCUMENT_YN() {
        return EXPORT_DOCUMENT_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_LINKED_DOCUMENT.EXPORT_DOCUMENT_YN
     *
     * @param EXPORT_DOCUMENT_YN the value for TRSDEAL_LINKED_DOCUMENT.EXPORT_DOCUMENT_YN
     */
    public void setEXPORT_DOCUMENT_YN(String EXPORT_DOCUMENT_YN) {
        this.EXPORT_DOCUMENT_YN = EXPORT_DOCUMENT_YN == null ? null : EXPORT_DOCUMENT_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_LINKED_DOCUMENT.EXPORT_LODGMENT_TRX_REF
     *
     * @return the value of TRSDEAL_LINKED_DOCUMENT.EXPORT_LODGMENT_TRX_REF
     */
    public String getEXPORT_LODGMENT_TRX_REF() {
        return EXPORT_LODGMENT_TRX_REF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_LINKED_DOCUMENT.EXPORT_LODGMENT_TRX_REF
     *
     * @param EXPORT_LODGMENT_TRX_REF the value for TRSDEAL_LINKED_DOCUMENT.EXPORT_LODGMENT_TRX_REF
     */
    public void setEXPORT_LODGMENT_TRX_REF(String EXPORT_LODGMENT_TRX_REF) {
        this.EXPORT_LODGMENT_TRX_REF = EXPORT_LODGMENT_TRX_REF == null ? null : EXPORT_LODGMENT_TRX_REF.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_LINKED_DOCUMENT.CREATED_BY
     *
     * @return the value of TRSDEAL_LINKED_DOCUMENT.CREATED_BY
     */
    public String getCREATED_BY() {
        return CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_LINKED_DOCUMENT.CREATED_BY
     *
     * @param CREATED_BY the value for TRSDEAL_LINKED_DOCUMENT.CREATED_BY
     */
    public void setCREATED_BY(String CREATED_BY) {
        this.CREATED_BY = CREATED_BY == null ? null : CREATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_LINKED_DOCUMENT.CREATED_DATE
     *
     * @return the value of TRSDEAL_LINKED_DOCUMENT.CREATED_DATE
     */
    public Date getCREATED_DATE() {
        return CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_LINKED_DOCUMENT.CREATED_DATE
     *
     * @param CREATED_DATE the value for TRSDEAL_LINKED_DOCUMENT.CREATED_DATE
     */
    public void setCREATED_DATE(Date CREATED_DATE) {
        this.CREATED_DATE = CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_LINKED_DOCUMENT.MODIFIED_BY
     *
     * @return the value of TRSDEAL_LINKED_DOCUMENT.MODIFIED_BY
     */
    public String getMODIFIED_BY() {
        return MODIFIED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_LINKED_DOCUMENT.MODIFIED_BY
     *
     * @param MODIFIED_BY the value for TRSDEAL_LINKED_DOCUMENT.MODIFIED_BY
     */
    public void setMODIFIED_BY(String MODIFIED_BY) {
        this.MODIFIED_BY = MODIFIED_BY == null ? null : MODIFIED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_LINKED_DOCUMENT.MODIFIED_DATE
     *
     * @return the value of TRSDEAL_LINKED_DOCUMENT.MODIFIED_DATE
     */
    public Date getMODIFIED_DATE() {
        return MODIFIED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_LINKED_DOCUMENT.MODIFIED_DATE
     *
     * @param MODIFIED_DATE the value for TRSDEAL_LINKED_DOCUMENT.MODIFIED_DATE
     */
    public void setMODIFIED_DATE(Date MODIFIED_DATE) {
        this.MODIFIED_DATE = MODIFIED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_LINKED_DOCUMENT.DOCUMENT_NAME
     *
     * @return the value of TRSDEAL_LINKED_DOCUMENT.DOCUMENT_NAME
     */
    public String getDOCUMENT_NAME() {
        return DOCUMENT_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_LINKED_DOCUMENT.DOCUMENT_NAME
     *
     * @param DOCUMENT_NAME the value for TRSDEAL_LINKED_DOCUMENT.DOCUMENT_NAME
     */
    public void setDOCUMENT_NAME(String DOCUMENT_NAME) {
        this.DOCUMENT_NAME = DOCUMENT_NAME == null ? null : DOCUMENT_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_LINKED_DOCUMENT.ALLOCATED_CV_AMOUNT
     *
     * @return the value of TRSDEAL_LINKED_DOCUMENT.ALLOCATED_CV_AMOUNT
     */
    public BigDecimal getALLOCATED_CV_AMOUNT() {
        return ALLOCATED_CV_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_LINKED_DOCUMENT.ALLOCATED_CV_AMOUNT
     *
     * @param ALLOCATED_CV_AMOUNT the value for TRSDEAL_LINKED_DOCUMENT.ALLOCATED_CV_AMOUNT
     */
    public void setALLOCATED_CV_AMOUNT(BigDecimal ALLOCATED_CV_AMOUNT) {
        this.ALLOCATED_CV_AMOUNT = ALLOCATED_CV_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_LINKED_DOCUMENT.ALLOCATED_FC_AMOUNT
     *
     * @return the value of TRSDEAL_LINKED_DOCUMENT.ALLOCATED_FC_AMOUNT
     */
    public BigDecimal getALLOCATED_FC_AMOUNT() {
        return ALLOCATED_FC_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_LINKED_DOCUMENT.ALLOCATED_FC_AMOUNT
     *
     * @param ALLOCATED_FC_AMOUNT the value for TRSDEAL_LINKED_DOCUMENT.ALLOCATED_FC_AMOUNT
     */
    public void setALLOCATED_FC_AMOUNT(BigDecimal ALLOCATED_FC_AMOUNT) {
        this.ALLOCATED_FC_AMOUNT = ALLOCATED_FC_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_LINKED_DOCUMENT.AVAILABLE_CV_AMOUNT
     *
     * @return the value of TRSDEAL_LINKED_DOCUMENT.AVAILABLE_CV_AMOUNT
     */
    public BigDecimal getAVAILABLE_CV_AMOUNT() {
        return AVAILABLE_CV_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_LINKED_DOCUMENT.AVAILABLE_CV_AMOUNT
     *
     * @param AVAILABLE_CV_AMOUNT the value for TRSDEAL_LINKED_DOCUMENT.AVAILABLE_CV_AMOUNT
     */
    public void setAVAILABLE_CV_AMOUNT(BigDecimal AVAILABLE_CV_AMOUNT) {
        this.AVAILABLE_CV_AMOUNT = AVAILABLE_CV_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_LINKED_DOCUMENT.AVAILABLE_FC_AMOUNT
     *
     * @return the value of TRSDEAL_LINKED_DOCUMENT.AVAILABLE_FC_AMOUNT
     */
    public BigDecimal getAVAILABLE_FC_AMOUNT() {
        return AVAILABLE_FC_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_LINKED_DOCUMENT.AVAILABLE_FC_AMOUNT
     *
     * @param AVAILABLE_FC_AMOUNT the value for TRSDEAL_LINKED_DOCUMENT.AVAILABLE_FC_AMOUNT
     */
    public void setAVAILABLE_FC_AMOUNT(BigDecimal AVAILABLE_FC_AMOUNT) {
        this.AVAILABLE_FC_AMOUNT = AVAILABLE_FC_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_LINKED_DOCUMENT.EXCHANGE_RATE
     *
     * @return the value of TRSDEAL_LINKED_DOCUMENT.EXCHANGE_RATE
     */
    public BigDecimal getEXCHANGE_RATE() {
        return EXCHANGE_RATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_LINKED_DOCUMENT.EXCHANGE_RATE
     *
     * @param EXCHANGE_RATE the value for TRSDEAL_LINKED_DOCUMENT.EXCHANGE_RATE
     */
    public void setEXCHANGE_RATE(BigDecimal EXCHANGE_RATE) {
        this.EXCHANGE_RATE = EXCHANGE_RATE;
    }
}