package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class TRSDEAL_CHANNEL_STATUSVOKey extends BaseVO {
    /**
     * This field corresponds to the database column TRSDEAL_CHANNEL_STATUS.BRANCH_CODE
     */
    private BigDecimal BRANCH_CODE;

    /**
     * This field corresponds to the database column TRSDEAL_CHANNEL_STATUS.CHANNEL_ID
     */
    private String CHANNEL_ID;

    /**
     * This field corresponds to the database column TRSDEAL_CHANNEL_STATUS.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column TRSDEAL_CHANNEL_STATUS.DEAL_NO
     */
    private BigDecimal DEAL_NO;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_CHANNEL_STATUS.BRANCH_CODE
     *
     * @return the value of TRSDEAL_CHANNEL_STATUS.BRANCH_CODE
     */
    public BigDecimal getBRANCH_CODE() {
        return BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_CHANNEL_STATUS.BRANCH_CODE
     *
     * @param BRANCH_CODE the value for TRSDEAL_CHANNEL_STATUS.BRANCH_CODE
     */
    public void setBRANCH_CODE(BigDecimal BRANCH_CODE) {
        this.BRANCH_CODE = BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_CHANNEL_STATUS.CHANNEL_ID
     *
     * @return the value of TRSDEAL_CHANNEL_STATUS.CHANNEL_ID
     */
    public String getCHANNEL_ID() {
        return CHANNEL_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_CHANNEL_STATUS.CHANNEL_ID
     *
     * @param CHANNEL_ID the value for TRSDEAL_CHANNEL_STATUS.CHANNEL_ID
     */
    public void setCHANNEL_ID(String CHANNEL_ID) {
        this.CHANNEL_ID = CHANNEL_ID == null ? null : CHANNEL_ID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_CHANNEL_STATUS.COMP_CODE
     *
     * @return the value of TRSDEAL_CHANNEL_STATUS.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_CHANNEL_STATUS.COMP_CODE
     *
     * @param COMP_CODE the value for TRSDEAL_CHANNEL_STATUS.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_CHANNEL_STATUS.DEAL_NO
     *
     * @return the value of TRSDEAL_CHANNEL_STATUS.DEAL_NO
     */
    public BigDecimal getDEAL_NO() {
        return DEAL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_CHANNEL_STATUS.DEAL_NO
     *
     * @param DEAL_NO the value for TRSDEAL_CHANNEL_STATUS.DEAL_NO
     */
    public void setDEAL_NO(BigDecimal DEAL_NO) {
        this.DEAL_NO = DEAL_NO;
    }
}