package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class TRSDEAL3VO extends TRSDEAL3VOKey {
    /**
     * This field corresponds to the database column TRSDEAL3.SCHEDULE_DESC
     */
    private String SCHEDULE_DESC;

    /**
     * This field corresponds to the database column TRSDEAL3.VALUE_DATE
     */
    private Date VALUE_DATE;

    /**
     * This field corresponds to the database column TRSDEAL3.PERCENTAGE
     */
    private BigDecimal PERCENTAGE;

    /**
     * This field corresponds to the database column TRSDEAL3.AMOUNT
     */
    private BigDecimal AMOUNT;

    /**
     * This field corresponds to the database column TRSDEAL3.SCHEDULE_REF
     */
    private String SCHEDULE_REF;

    /**
     * This field corresponds to the database column TRSDEAL3.PAID_IND
     */
    private String PAID_IND;

    /**
     * This field corresponds to the database column TRSDEAL3.YIELD
     */
    private BigDecimal YIELD;

    /**
     * This field corresponds to the database column TRSDEAL3.ORIGINAL_YIELD
     */
    private BigDecimal ORIGINAL_YIELD;

    /**
     * This field corresponds to the database column TRSDEAL3.ORIGINAL_VALUE_DATE
     */
    private Date ORIGINAL_VALUE_DATE;

    /**
     * This field corresponds to the database column TRSDEAL3.ORIGINAL_AMOUNT
     */
    private BigDecimal ORIGINAL_AMOUNT;

    /**
     * This field corresponds to the database column TRSDEAL3.END_OF_PROJECT_PERIOD
     */
    private Date END_OF_PROJECT_PERIOD;

    /**
     * This field corresponds to the database column TRSDEAL3.AMENDMENT_NO
     */
    private BigDecimal AMENDMENT_NO;

    /**
     * This field corresponds to the database column TRSDEAL3.END_OF_DISBURSEMENT_PERIOD
     */
    private Date END_OF_DISBURSEMENT_PERIOD;

    /**
     * This field corresponds to the database column TRSDEAL3.MARGIN_RATE
     */
    private BigDecimal MARGIN_RATE;

    /**
     * This field corresponds to the database column TRSDEAL3.LIBOR_RATE
     */
    private BigDecimal LIBOR_RATE;

    /**
     * This field corresponds to the database column TRSDEAL3.RATE_PERIODICITY
     */
    private BigDecimal RATE_PERIODICITY;

    /**
     * This field corresponds to the database column TRSDEAL3.RATE_PERIODICITY_TYPE
     */
    private String RATE_PERIODICITY_TYPE;

    /**
     * This field corresponds to the database column TRSDEAL3.NEXT_RATE_REV_DATE
     */
    private Date NEXT_RATE_REV_DATE;

    /**
     * This field corresponds to the database column TRSDEAL3.RATE_REV_DATE
     */
    private Date RATE_REV_DATE;

    /**
     * This field corresponds to the database column TRSDEAL3.DISBURSEMENT_NO
     */
    private BigDecimal DISBURSEMENT_NO;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL3.SCHEDULE_DESC
     *
     * @return the value of TRSDEAL3.SCHEDULE_DESC
     */
    public String getSCHEDULE_DESC() {
        return SCHEDULE_DESC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL3.SCHEDULE_DESC
     *
     * @param SCHEDULE_DESC the value for TRSDEAL3.SCHEDULE_DESC
     */
    public void setSCHEDULE_DESC(String SCHEDULE_DESC) {
        this.SCHEDULE_DESC = SCHEDULE_DESC == null ? null : SCHEDULE_DESC.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL3.VALUE_DATE
     *
     * @return the value of TRSDEAL3.VALUE_DATE
     */
    public Date getVALUE_DATE() {
        return VALUE_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL3.VALUE_DATE
     *
     * @param VALUE_DATE the value for TRSDEAL3.VALUE_DATE
     */
    public void setVALUE_DATE(Date VALUE_DATE) {
        this.VALUE_DATE = VALUE_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL3.PERCENTAGE
     *
     * @return the value of TRSDEAL3.PERCENTAGE
     */
    public BigDecimal getPERCENTAGE() {
        return PERCENTAGE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL3.PERCENTAGE
     *
     * @param PERCENTAGE the value for TRSDEAL3.PERCENTAGE
     */
    public void setPERCENTAGE(BigDecimal PERCENTAGE) {
        this.PERCENTAGE = PERCENTAGE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL3.AMOUNT
     *
     * @return the value of TRSDEAL3.AMOUNT
     */
    public BigDecimal getAMOUNT() {
        return AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL3.AMOUNT
     *
     * @param AMOUNT the value for TRSDEAL3.AMOUNT
     */
    public void setAMOUNT(BigDecimal AMOUNT) {
        this.AMOUNT = AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL3.SCHEDULE_REF
     *
     * @return the value of TRSDEAL3.SCHEDULE_REF
     */
    public String getSCHEDULE_REF() {
        return SCHEDULE_REF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL3.SCHEDULE_REF
     *
     * @param SCHEDULE_REF the value for TRSDEAL3.SCHEDULE_REF
     */
    public void setSCHEDULE_REF(String SCHEDULE_REF) {
        this.SCHEDULE_REF = SCHEDULE_REF == null ? null : SCHEDULE_REF.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL3.PAID_IND
     *
     * @return the value of TRSDEAL3.PAID_IND
     */
    public String getPAID_IND() {
        return PAID_IND;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL3.PAID_IND
     *
     * @param PAID_IND the value for TRSDEAL3.PAID_IND
     */
    public void setPAID_IND(String PAID_IND) {
        this.PAID_IND = PAID_IND == null ? null : PAID_IND.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL3.YIELD
     *
     * @return the value of TRSDEAL3.YIELD
     */
    public BigDecimal getYIELD() {
        return YIELD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL3.YIELD
     *
     * @param YIELD the value for TRSDEAL3.YIELD
     */
    public void setYIELD(BigDecimal YIELD) {
        this.YIELD = YIELD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL3.ORIGINAL_YIELD
     *
     * @return the value of TRSDEAL3.ORIGINAL_YIELD
     */
    public BigDecimal getORIGINAL_YIELD() {
        return ORIGINAL_YIELD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL3.ORIGINAL_YIELD
     *
     * @param ORIGINAL_YIELD the value for TRSDEAL3.ORIGINAL_YIELD
     */
    public void setORIGINAL_YIELD(BigDecimal ORIGINAL_YIELD) {
        this.ORIGINAL_YIELD = ORIGINAL_YIELD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL3.ORIGINAL_VALUE_DATE
     *
     * @return the value of TRSDEAL3.ORIGINAL_VALUE_DATE
     */
    public Date getORIGINAL_VALUE_DATE() {
        return ORIGINAL_VALUE_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL3.ORIGINAL_VALUE_DATE
     *
     * @param ORIGINAL_VALUE_DATE the value for TRSDEAL3.ORIGINAL_VALUE_DATE
     */
    public void setORIGINAL_VALUE_DATE(Date ORIGINAL_VALUE_DATE) {
        this.ORIGINAL_VALUE_DATE = ORIGINAL_VALUE_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL3.ORIGINAL_AMOUNT
     *
     * @return the value of TRSDEAL3.ORIGINAL_AMOUNT
     */
    public BigDecimal getORIGINAL_AMOUNT() {
        return ORIGINAL_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL3.ORIGINAL_AMOUNT
     *
     * @param ORIGINAL_AMOUNT the value for TRSDEAL3.ORIGINAL_AMOUNT
     */
    public void setORIGINAL_AMOUNT(BigDecimal ORIGINAL_AMOUNT) {
        this.ORIGINAL_AMOUNT = ORIGINAL_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL3.END_OF_PROJECT_PERIOD
     *
     * @return the value of TRSDEAL3.END_OF_PROJECT_PERIOD
     */
    public Date getEND_OF_PROJECT_PERIOD() {
        return END_OF_PROJECT_PERIOD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL3.END_OF_PROJECT_PERIOD
     *
     * @param END_OF_PROJECT_PERIOD the value for TRSDEAL3.END_OF_PROJECT_PERIOD
     */
    public void setEND_OF_PROJECT_PERIOD(Date END_OF_PROJECT_PERIOD) {
        this.END_OF_PROJECT_PERIOD = END_OF_PROJECT_PERIOD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL3.AMENDMENT_NO
     *
     * @return the value of TRSDEAL3.AMENDMENT_NO
     */
    public BigDecimal getAMENDMENT_NO() {
        return AMENDMENT_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL3.AMENDMENT_NO
     *
     * @param AMENDMENT_NO the value for TRSDEAL3.AMENDMENT_NO
     */
    public void setAMENDMENT_NO(BigDecimal AMENDMENT_NO) {
        this.AMENDMENT_NO = AMENDMENT_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL3.END_OF_DISBURSEMENT_PERIOD
     *
     * @return the value of TRSDEAL3.END_OF_DISBURSEMENT_PERIOD
     */
    public Date getEND_OF_DISBURSEMENT_PERIOD() {
        return END_OF_DISBURSEMENT_PERIOD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL3.END_OF_DISBURSEMENT_PERIOD
     *
     * @param END_OF_DISBURSEMENT_PERIOD the value for TRSDEAL3.END_OF_DISBURSEMENT_PERIOD
     */
    public void setEND_OF_DISBURSEMENT_PERIOD(Date END_OF_DISBURSEMENT_PERIOD) {
        this.END_OF_DISBURSEMENT_PERIOD = END_OF_DISBURSEMENT_PERIOD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL3.MARGIN_RATE
     *
     * @return the value of TRSDEAL3.MARGIN_RATE
     */
    public BigDecimal getMARGIN_RATE() {
        return MARGIN_RATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL3.MARGIN_RATE
     *
     * @param MARGIN_RATE the value for TRSDEAL3.MARGIN_RATE
     */
    public void setMARGIN_RATE(BigDecimal MARGIN_RATE) {
        this.MARGIN_RATE = MARGIN_RATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL3.LIBOR_RATE
     *
     * @return the value of TRSDEAL3.LIBOR_RATE
     */
    public BigDecimal getLIBOR_RATE() {
        return LIBOR_RATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL3.LIBOR_RATE
     *
     * @param LIBOR_RATE the value for TRSDEAL3.LIBOR_RATE
     */
    public void setLIBOR_RATE(BigDecimal LIBOR_RATE) {
        this.LIBOR_RATE = LIBOR_RATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL3.RATE_PERIODICITY
     *
     * @return the value of TRSDEAL3.RATE_PERIODICITY
     */
    public BigDecimal getRATE_PERIODICITY() {
        return RATE_PERIODICITY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL3.RATE_PERIODICITY
     *
     * @param RATE_PERIODICITY the value for TRSDEAL3.RATE_PERIODICITY
     */
    public void setRATE_PERIODICITY(BigDecimal RATE_PERIODICITY) {
        this.RATE_PERIODICITY = RATE_PERIODICITY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL3.RATE_PERIODICITY_TYPE
     *
     * @return the value of TRSDEAL3.RATE_PERIODICITY_TYPE
     */
    public String getRATE_PERIODICITY_TYPE() {
        return RATE_PERIODICITY_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL3.RATE_PERIODICITY_TYPE
     *
     * @param RATE_PERIODICITY_TYPE the value for TRSDEAL3.RATE_PERIODICITY_TYPE
     */
    public void setRATE_PERIODICITY_TYPE(String RATE_PERIODICITY_TYPE) {
        this.RATE_PERIODICITY_TYPE = RATE_PERIODICITY_TYPE == null ? null : RATE_PERIODICITY_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL3.NEXT_RATE_REV_DATE
     *
     * @return the value of TRSDEAL3.NEXT_RATE_REV_DATE
     */
    public Date getNEXT_RATE_REV_DATE() {
        return NEXT_RATE_REV_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL3.NEXT_RATE_REV_DATE
     *
     * @param NEXT_RATE_REV_DATE the value for TRSDEAL3.NEXT_RATE_REV_DATE
     */
    public void setNEXT_RATE_REV_DATE(Date NEXT_RATE_REV_DATE) {
        this.NEXT_RATE_REV_DATE = NEXT_RATE_REV_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL3.RATE_REV_DATE
     *
     * @return the value of TRSDEAL3.RATE_REV_DATE
     */
    public Date getRATE_REV_DATE() {
        return RATE_REV_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL3.RATE_REV_DATE
     *
     * @param RATE_REV_DATE the value for TRSDEAL3.RATE_REV_DATE
     */
    public void setRATE_REV_DATE(Date RATE_REV_DATE) {
        this.RATE_REV_DATE = RATE_REV_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL3.DISBURSEMENT_NO
     *
     * @return the value of TRSDEAL3.DISBURSEMENT_NO
     */
    public BigDecimal getDISBURSEMENT_NO() {
        return DISBURSEMENT_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL3.DISBURSEMENT_NO
     *
     * @param DISBURSEMENT_NO the value for TRSDEAL3.DISBURSEMENT_NO
     */
    public void setDISBURSEMENT_NO(BigDecimal DISBURSEMENT_NO) {
        this.DISBURSEMENT_NO = DISBURSEMENT_NO;
    }
}