package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class TRSDEAL_SD_DETAILS_HISTORYVO extends TRSDEAL_SD_DETAILS_HISTORYVOKey {
    /**
     * This field corresponds to the database column TRSDEAL_SD_DETAILS_HISTORY.AMOUNT
     */
    private BigDecimal AMOUNT;

    /**
     * This field corresponds to the database column TRSDEAL_SD_DETAILS_HISTORY.AMENDED_AMOUNT
     */
    private BigDecimal AMENDED_AMOUNT;

    /**
     * This field corresponds to the database column TRSDEAL_SD_DETAILS_HISTORY.AMENDMENT_REASON
     */
    private String AMENDMENT_REASON;

    /**
     * This field corresponds to the database column TRSDEAL_SD_DETAILS_HISTORY.CREATED_BY
     */
    private String CREATED_BY;

    /**
     * This field corresponds to the database column TRSDEAL_SD_DETAILS_HISTORY.SERVER_CREATED_DATE
     */
    private Date SERVER_CREATED_DATE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_SD_DETAILS_HISTORY.AMOUNT
     *
     * @return the value of TRSDEAL_SD_DETAILS_HISTORY.AMOUNT
     */
    public BigDecimal getAMOUNT() {
        return AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_SD_DETAILS_HISTORY.AMOUNT
     *
     * @param AMOUNT the value for TRSDEAL_SD_DETAILS_HISTORY.AMOUNT
     */
    public void setAMOUNT(BigDecimal AMOUNT) {
        this.AMOUNT = AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_SD_DETAILS_HISTORY.AMENDED_AMOUNT
     *
     * @return the value of TRSDEAL_SD_DETAILS_HISTORY.AMENDED_AMOUNT
     */
    public BigDecimal getAMENDED_AMOUNT() {
        return AMENDED_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_SD_DETAILS_HISTORY.AMENDED_AMOUNT
     *
     * @param AMENDED_AMOUNT the value for TRSDEAL_SD_DETAILS_HISTORY.AMENDED_AMOUNT
     */
    public void setAMENDED_AMOUNT(BigDecimal AMENDED_AMOUNT) {
        this.AMENDED_AMOUNT = AMENDED_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_SD_DETAILS_HISTORY.AMENDMENT_REASON
     *
     * @return the value of TRSDEAL_SD_DETAILS_HISTORY.AMENDMENT_REASON
     */
    public String getAMENDMENT_REASON() {
        return AMENDMENT_REASON;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_SD_DETAILS_HISTORY.AMENDMENT_REASON
     *
     * @param AMENDMENT_REASON the value for TRSDEAL_SD_DETAILS_HISTORY.AMENDMENT_REASON
     */
    public void setAMENDMENT_REASON(String AMENDMENT_REASON) {
        this.AMENDMENT_REASON = AMENDMENT_REASON == null ? null : AMENDMENT_REASON.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_SD_DETAILS_HISTORY.CREATED_BY
     *
     * @return the value of TRSDEAL_SD_DETAILS_HISTORY.CREATED_BY
     */
    public String getCREATED_BY() {
        return CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_SD_DETAILS_HISTORY.CREATED_BY
     *
     * @param CREATED_BY the value for TRSDEAL_SD_DETAILS_HISTORY.CREATED_BY
     */
    public void setCREATED_BY(String CREATED_BY) {
        this.CREATED_BY = CREATED_BY == null ? null : CREATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_SD_DETAILS_HISTORY.SERVER_CREATED_DATE
     *
     * @return the value of TRSDEAL_SD_DETAILS_HISTORY.SERVER_CREATED_DATE
     */
    public Date getSERVER_CREATED_DATE() {
        return SERVER_CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_SD_DETAILS_HISTORY.SERVER_CREATED_DATE
     *
     * @param SERVER_CREATED_DATE the value for TRSDEAL_SD_DETAILS_HISTORY.SERVER_CREATED_DATE
     */
    public void setSERVER_CREATED_DATE(Date SERVER_CREATED_DATE) {
        this.SERVER_CREATED_DATE = SERVER_CREATED_DATE;
    }
}