package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class TRSDEAL_SETTLEMENT_CHARGE_DETVO extends TRSDEAL_SETTLEMENT_CHARGE_DETVOKey {
    /**
     * This field corresponds to the database column TRSDEAL_SETTLEMENT_CHARGE_DET.CHARGE_CODE
     */
    private BigDecimal CHARGE_CODE;

    /**
     * This field corresponds to the database column TRSDEAL_SETTLEMENT_CHARGE_DET.CHARGE_AMOUNT
     */
    private BigDecimal CHARGE_AMOUNT;

    /**
     * This field corresponds to the database column TRSDEAL_SETTLEMENT_CHARGE_DET.CHARGE_AMOUNT_SETTLED
     */
    private BigDecimal CHARGE_AMOUNT_SETTLED;

    /**
     * This field corresponds to the database column TRSDEAL_SETTLEMENT_CHARGE_DET.VAT_AMOUNT
     */
    private BigDecimal VAT_AMOUNT;

    /**
     * This field corresponds to the database column TRSDEAL_SETTLEMENT_CHARGE_DET.VAT_AMOUNT_SETTLED
     */
    private BigDecimal VAT_AMOUNT_SETTLED;

    /**
     * This field corresponds to the database column TRSDEAL_SETTLEMENT_CHARGE_DET.DUE_DATE
     */
    private Date DUE_DATE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_SETTLEMENT_CHARGE_DET.CHARGE_CODE
     *
     * @return the value of TRSDEAL_SETTLEMENT_CHARGE_DET.CHARGE_CODE
     */
    public BigDecimal getCHARGE_CODE() {
        return CHARGE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_SETTLEMENT_CHARGE_DET.CHARGE_CODE
     *
     * @param CHARGE_CODE the value for TRSDEAL_SETTLEMENT_CHARGE_DET.CHARGE_CODE
     */
    public void setCHARGE_CODE(BigDecimal CHARGE_CODE) {
        this.CHARGE_CODE = CHARGE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_SETTLEMENT_CHARGE_DET.CHARGE_AMOUNT
     *
     * @return the value of TRSDEAL_SETTLEMENT_CHARGE_DET.CHARGE_AMOUNT
     */
    public BigDecimal getCHARGE_AMOUNT() {
        return CHARGE_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_SETTLEMENT_CHARGE_DET.CHARGE_AMOUNT
     *
     * @param CHARGE_AMOUNT the value for TRSDEAL_SETTLEMENT_CHARGE_DET.CHARGE_AMOUNT
     */
    public void setCHARGE_AMOUNT(BigDecimal CHARGE_AMOUNT) {
        this.CHARGE_AMOUNT = CHARGE_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_SETTLEMENT_CHARGE_DET.CHARGE_AMOUNT_SETTLED
     *
     * @return the value of TRSDEAL_SETTLEMENT_CHARGE_DET.CHARGE_AMOUNT_SETTLED
     */
    public BigDecimal getCHARGE_AMOUNT_SETTLED() {
        return CHARGE_AMOUNT_SETTLED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_SETTLEMENT_CHARGE_DET.CHARGE_AMOUNT_SETTLED
     *
     * @param CHARGE_AMOUNT_SETTLED the value for TRSDEAL_SETTLEMENT_CHARGE_DET.CHARGE_AMOUNT_SETTLED
     */
    public void setCHARGE_AMOUNT_SETTLED(BigDecimal CHARGE_AMOUNT_SETTLED) {
        this.CHARGE_AMOUNT_SETTLED = CHARGE_AMOUNT_SETTLED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_SETTLEMENT_CHARGE_DET.VAT_AMOUNT
     *
     * @return the value of TRSDEAL_SETTLEMENT_CHARGE_DET.VAT_AMOUNT
     */
    public BigDecimal getVAT_AMOUNT() {
        return VAT_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_SETTLEMENT_CHARGE_DET.VAT_AMOUNT
     *
     * @param VAT_AMOUNT the value for TRSDEAL_SETTLEMENT_CHARGE_DET.VAT_AMOUNT
     */
    public void setVAT_AMOUNT(BigDecimal VAT_AMOUNT) {
        this.VAT_AMOUNT = VAT_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_SETTLEMENT_CHARGE_DET.VAT_AMOUNT_SETTLED
     *
     * @return the value of TRSDEAL_SETTLEMENT_CHARGE_DET.VAT_AMOUNT_SETTLED
     */
    public BigDecimal getVAT_AMOUNT_SETTLED() {
        return VAT_AMOUNT_SETTLED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_SETTLEMENT_CHARGE_DET.VAT_AMOUNT_SETTLED
     *
     * @param VAT_AMOUNT_SETTLED the value for TRSDEAL_SETTLEMENT_CHARGE_DET.VAT_AMOUNT_SETTLED
     */
    public void setVAT_AMOUNT_SETTLED(BigDecimal VAT_AMOUNT_SETTLED) {
        this.VAT_AMOUNT_SETTLED = VAT_AMOUNT_SETTLED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_SETTLEMENT_CHARGE_DET.DUE_DATE
     *
     * @return the value of TRSDEAL_SETTLEMENT_CHARGE_DET.DUE_DATE
     */
    public Date getDUE_DATE() {
        return DUE_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_SETTLEMENT_CHARGE_DET.DUE_DATE
     *
     * @param DUE_DATE the value for TRSDEAL_SETTLEMENT_CHARGE_DET.DUE_DATE
     */
    public void setDUE_DATE(Date DUE_DATE) {
        this.DUE_DATE = DUE_DATE;
    }
}