package com.path.dbmaps.vo;

import java.util.Date;

public class TRSDEAL_CHANNEL_STATUSVO extends TRSDEAL_CHANNEL_STATUSVOKey {
    /**
     * This field corresponds to the database column TRSDEAL_CHANNEL_STATUS.CHANNEL_STATUS
     */
    private String CHANNEL_STATUS;

    /**
     * This field corresponds to the database column TRSDEAL_CHANNEL_STATUS.BLOCK_REASON
     */
    private String BLOCK_REASON;

    /**
     * This field corresponds to the database column TRSDEAL_CHANNEL_STATUS.BLOCKED_DATE
     */
    private Date BLOCKED_DATE;

    /**
     * This field corresponds to the database column TRSDEAL_CHANNEL_STATUS.UNBLOCKED_DATE
     */
    private Date UNBLOCKED_DATE;

    /**
     * This field corresponds to the database column TRSDEAL_CHANNEL_STATUS.BLOCKED_REF
     */
    private String BLOCKED_REF;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_CHANNEL_STATUS.CHANNEL_STATUS
     *
     * @return the value of TRSDEAL_CHANNEL_STATUS.CHANNEL_STATUS
     */
    public String getCHANNEL_STATUS() {
        return CHANNEL_STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_CHANNEL_STATUS.CHANNEL_STATUS
     *
     * @param CHANNEL_STATUS the value for TRSDEAL_CHANNEL_STATUS.CHANNEL_STATUS
     */
    public void setCHANNEL_STATUS(String CHANNEL_STATUS) {
        this.CHANNEL_STATUS = CHANNEL_STATUS == null ? null : CHANNEL_STATUS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_CHANNEL_STATUS.BLOCK_REASON
     *
     * @return the value of TRSDEAL_CHANNEL_STATUS.BLOCK_REASON
     */
    public String getBLOCK_REASON() {
        return BLOCK_REASON;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_CHANNEL_STATUS.BLOCK_REASON
     *
     * @param BLOCK_REASON the value for TRSDEAL_CHANNEL_STATUS.BLOCK_REASON
     */
    public void setBLOCK_REASON(String BLOCK_REASON) {
        this.BLOCK_REASON = BLOCK_REASON == null ? null : BLOCK_REASON.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_CHANNEL_STATUS.BLOCKED_DATE
     *
     * @return the value of TRSDEAL_CHANNEL_STATUS.BLOCKED_DATE
     */
    public Date getBLOCKED_DATE() {
        return BLOCKED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_CHANNEL_STATUS.BLOCKED_DATE
     *
     * @param BLOCKED_DATE the value for TRSDEAL_CHANNEL_STATUS.BLOCKED_DATE
     */
    public void setBLOCKED_DATE(Date BLOCKED_DATE) {
        this.BLOCKED_DATE = BLOCKED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_CHANNEL_STATUS.UNBLOCKED_DATE
     *
     * @return the value of TRSDEAL_CHANNEL_STATUS.UNBLOCKED_DATE
     */
    public Date getUNBLOCKED_DATE() {
        return UNBLOCKED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_CHANNEL_STATUS.UNBLOCKED_DATE
     *
     * @param UNBLOCKED_DATE the value for TRSDEAL_CHANNEL_STATUS.UNBLOCKED_DATE
     */
    public void setUNBLOCKED_DATE(Date UNBLOCKED_DATE) {
        this.UNBLOCKED_DATE = UNBLOCKED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_CHANNEL_STATUS.BLOCKED_REF
     *
     * @return the value of TRSDEAL_CHANNEL_STATUS.BLOCKED_REF
     */
    public String getBLOCKED_REF() {
        return BLOCKED_REF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_CHANNEL_STATUS.BLOCKED_REF
     *
     * @param BLOCKED_REF the value for TRSDEAL_CHANNEL_STATUS.BLOCKED_REF
     */
    public void setBLOCKED_REF(String BLOCKED_REF) {
        this.BLOCKED_REF = BLOCKED_REF == null ? null : BLOCKED_REF.trim();
    }
}