package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class TRSDEAL_CHARGE_ACCRUAL_PROCESSVOKey extends BaseVO {
    /**
     * This field corresponds to the database column TRSDEAL_CHARGE_ACCRUAL_PROCESS.BRANCH_CODE
     */
    private BigDecimal BRANCH_CODE;

    /**
     * This field corresponds to the database column TRSDEAL_CHARGE_ACCRUAL_PROCESS.CHARGE_CODE
     */
    private BigDecimal CHARGE_CODE;

    /**
     * This field corresponds to the database column TRSDEAL_CHARGE_ACCRUAL_PROCESS.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column TRSDEAL_CHARGE_ACCRUAL_PROCESS.DEAL_NO
     */
    private BigDecimal DEAL_NO;

    /**
     * This field corresponds to the database column TRSDEAL_CHARGE_ACCRUAL_PROCESS.PROCESS_NBR
     */
    private BigDecimal PROCESS_NBR;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_CHARGE_ACCRUAL_PROCESS.BRANCH_CODE
     *
     * @return the value of TRSDEAL_CHARGE_ACCRUAL_PROCESS.BRANCH_CODE
     */
    public BigDecimal getBRANCH_CODE() {
        return BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_CHARGE_ACCRUAL_PROCESS.BRANCH_CODE
     *
     * @param BRANCH_CODE the value for TRSDEAL_CHARGE_ACCRUAL_PROCESS.BRANCH_CODE
     */
    public void setBRANCH_CODE(BigDecimal BRANCH_CODE) {
        this.BRANCH_CODE = BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_CHARGE_ACCRUAL_PROCESS.CHARGE_CODE
     *
     * @return the value of TRSDEAL_CHARGE_ACCRUAL_PROCESS.CHARGE_CODE
     */
    public BigDecimal getCHARGE_CODE() {
        return CHARGE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_CHARGE_ACCRUAL_PROCESS.CHARGE_CODE
     *
     * @param CHARGE_CODE the value for TRSDEAL_CHARGE_ACCRUAL_PROCESS.CHARGE_CODE
     */
    public void setCHARGE_CODE(BigDecimal CHARGE_CODE) {
        this.CHARGE_CODE = CHARGE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_CHARGE_ACCRUAL_PROCESS.COMP_CODE
     *
     * @return the value of TRSDEAL_CHARGE_ACCRUAL_PROCESS.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_CHARGE_ACCRUAL_PROCESS.COMP_CODE
     *
     * @param COMP_CODE the value for TRSDEAL_CHARGE_ACCRUAL_PROCESS.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_CHARGE_ACCRUAL_PROCESS.DEAL_NO
     *
     * @return the value of TRSDEAL_CHARGE_ACCRUAL_PROCESS.DEAL_NO
     */
    public BigDecimal getDEAL_NO() {
        return DEAL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_CHARGE_ACCRUAL_PROCESS.DEAL_NO
     *
     * @param DEAL_NO the value for TRSDEAL_CHARGE_ACCRUAL_PROCESS.DEAL_NO
     */
    public void setDEAL_NO(BigDecimal DEAL_NO) {
        this.DEAL_NO = DEAL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_CHARGE_ACCRUAL_PROCESS.PROCESS_NBR
     *
     * @return the value of TRSDEAL_CHARGE_ACCRUAL_PROCESS.PROCESS_NBR
     */
    public BigDecimal getPROCESS_NBR() {
        return PROCESS_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_CHARGE_ACCRUAL_PROCESS.PROCESS_NBR
     *
     * @param PROCESS_NBR the value for TRSDEAL_CHARGE_ACCRUAL_PROCESS.PROCESS_NBR
     */
    public void setPROCESS_NBR(BigDecimal PROCESS_NBR) {
        this.PROCESS_NBR = PROCESS_NBR;
    }
}