package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class TRSDEAL_ALLOCATED_LIMITVOKey extends BaseVO {
    /**
     * This field corresponds to the database column TRSDEAL_ALLOCATED_LIMIT.BRANCH_CODE
     */
    private BigDecimal BRANCH_CODE;

    /**
     * This field corresponds to the database column TRSDEAL_ALLOCATED_LIMIT.CLASS
     */
    private BigDecimal CLASS;

    /**
     * This field corresponds to the database column TRSDEAL_ALLOCATED_LIMIT.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column TRSDEAL_ALLOCATED_LIMIT.CURRENCY_CODE
     */
    private BigDecimal CURRENCY_CODE;

    /**
     * This field corresponds to the database column TRSDEAL_ALLOCATED_LIMIT.DISBURSEMENT_FLAG
     */
    private String DISBURSEMENT_FLAG;

    /**
     * This field corresponds to the database column TRSDEAL_ALLOCATED_LIMIT.DISBURSEMENT_NO
     */
    private BigDecimal DISBURSEMENT_NO;

    /**
     * This field corresponds to the database column TRSDEAL_ALLOCATED_LIMIT.PARTY_NO
     */
    private BigDecimal PARTY_NO;

    /**
     * This field corresponds to the database column TRSDEAL_ALLOCATED_LIMIT.PARTY_TYPE
     */
    private String PARTY_TYPE;

    /**
     * This field corresponds to the database column TRSDEAL_ALLOCATED_LIMIT.SERIAL_NO
     */
    private BigDecimal SERIAL_NO;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_ALLOCATED_LIMIT.BRANCH_CODE
     *
     * @return the value of TRSDEAL_ALLOCATED_LIMIT.BRANCH_CODE
     */
    public BigDecimal getBRANCH_CODE() {
        return BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_ALLOCATED_LIMIT.BRANCH_CODE
     *
     * @param BRANCH_CODE the value for TRSDEAL_ALLOCATED_LIMIT.BRANCH_CODE
     */
    public void setBRANCH_CODE(BigDecimal BRANCH_CODE) {
        this.BRANCH_CODE = BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_ALLOCATED_LIMIT.CLASS
     *
     * @return the value of TRSDEAL_ALLOCATED_LIMIT.CLASS
     */
    public BigDecimal getCLASS() {
        return CLASS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_ALLOCATED_LIMIT.CLASS
     *
     * @param CLASS the value for TRSDEAL_ALLOCATED_LIMIT.CLASS
     */
    public void setCLASS(BigDecimal CLASS) {
        this.CLASS = CLASS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_ALLOCATED_LIMIT.COMP_CODE
     *
     * @return the value of TRSDEAL_ALLOCATED_LIMIT.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_ALLOCATED_LIMIT.COMP_CODE
     *
     * @param COMP_CODE the value for TRSDEAL_ALLOCATED_LIMIT.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_ALLOCATED_LIMIT.CURRENCY_CODE
     *
     * @return the value of TRSDEAL_ALLOCATED_LIMIT.CURRENCY_CODE
     */
    public BigDecimal getCURRENCY_CODE() {
        return CURRENCY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_ALLOCATED_LIMIT.CURRENCY_CODE
     *
     * @param CURRENCY_CODE the value for TRSDEAL_ALLOCATED_LIMIT.CURRENCY_CODE
     */
    public void setCURRENCY_CODE(BigDecimal CURRENCY_CODE) {
        this.CURRENCY_CODE = CURRENCY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_ALLOCATED_LIMIT.DISBURSEMENT_FLAG
     *
     * @return the value of TRSDEAL_ALLOCATED_LIMIT.DISBURSEMENT_FLAG
     */
    public String getDISBURSEMENT_FLAG() {
        return DISBURSEMENT_FLAG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_ALLOCATED_LIMIT.DISBURSEMENT_FLAG
     *
     * @param DISBURSEMENT_FLAG the value for TRSDEAL_ALLOCATED_LIMIT.DISBURSEMENT_FLAG
     */
    public void setDISBURSEMENT_FLAG(String DISBURSEMENT_FLAG) {
        this.DISBURSEMENT_FLAG = DISBURSEMENT_FLAG == null ? null : DISBURSEMENT_FLAG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_ALLOCATED_LIMIT.DISBURSEMENT_NO
     *
     * @return the value of TRSDEAL_ALLOCATED_LIMIT.DISBURSEMENT_NO
     */
    public BigDecimal getDISBURSEMENT_NO() {
        return DISBURSEMENT_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_ALLOCATED_LIMIT.DISBURSEMENT_NO
     *
     * @param DISBURSEMENT_NO the value for TRSDEAL_ALLOCATED_LIMIT.DISBURSEMENT_NO
     */
    public void setDISBURSEMENT_NO(BigDecimal DISBURSEMENT_NO) {
        this.DISBURSEMENT_NO = DISBURSEMENT_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_ALLOCATED_LIMIT.PARTY_NO
     *
     * @return the value of TRSDEAL_ALLOCATED_LIMIT.PARTY_NO
     */
    public BigDecimal getPARTY_NO() {
        return PARTY_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_ALLOCATED_LIMIT.PARTY_NO
     *
     * @param PARTY_NO the value for TRSDEAL_ALLOCATED_LIMIT.PARTY_NO
     */
    public void setPARTY_NO(BigDecimal PARTY_NO) {
        this.PARTY_NO = PARTY_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_ALLOCATED_LIMIT.PARTY_TYPE
     *
     * @return the value of TRSDEAL_ALLOCATED_LIMIT.PARTY_TYPE
     */
    public String getPARTY_TYPE() {
        return PARTY_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_ALLOCATED_LIMIT.PARTY_TYPE
     *
     * @param PARTY_TYPE the value for TRSDEAL_ALLOCATED_LIMIT.PARTY_TYPE
     */
    public void setPARTY_TYPE(String PARTY_TYPE) {
        this.PARTY_TYPE = PARTY_TYPE == null ? null : PARTY_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_ALLOCATED_LIMIT.SERIAL_NO
     *
     * @return the value of TRSDEAL_ALLOCATED_LIMIT.SERIAL_NO
     */
    public BigDecimal getSERIAL_NO() {
        return SERIAL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_ALLOCATED_LIMIT.SERIAL_NO
     *
     * @param SERIAL_NO the value for TRSDEAL_ALLOCATED_LIMIT.SERIAL_NO
     */
    public void setSERIAL_NO(BigDecimal SERIAL_NO) {
        this.SERIAL_NO = SERIAL_NO;
    }
}