package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class TRSDEAL_MULTIPLE_TRADE_DEALSVOKey extends BaseVO {
    /**
     * This field corresponds to the database column TRSDEAL_MULTIPLE_TRADE_DEALS.BRANCH_CODE
     */
    private BigDecimal BRANCH_CODE;

    /**
     * This field corresponds to the database column TRSDEAL_MULTIPLE_TRADE_DEALS.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column TRSDEAL_MULTIPLE_TRADE_DEALS.SERIAL_NO
     */
    private BigDecimal SERIAL_NO;

    /**
     * This field corresponds to the database column TRSDEAL_MULTIPLE_TRADE_DEALS.TRADE_REF_NO
     */
    private BigDecimal TRADE_REF_NO;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_MULTIPLE_TRADE_DEALS.BRANCH_CODE
     *
     * @return the value of TRSDEAL_MULTIPLE_TRADE_DEALS.BRANCH_CODE
     */
    public BigDecimal getBRANCH_CODE() {
        return BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_MULTIPLE_TRADE_DEALS.BRANCH_CODE
     *
     * @param BRANCH_CODE the value for TRSDEAL_MULTIPLE_TRADE_DEALS.BRANCH_CODE
     */
    public void setBRANCH_CODE(BigDecimal BRANCH_CODE) {
        this.BRANCH_CODE = BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_MULTIPLE_TRADE_DEALS.COMP_CODE
     *
     * @return the value of TRSDEAL_MULTIPLE_TRADE_DEALS.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_MULTIPLE_TRADE_DEALS.COMP_CODE
     *
     * @param COMP_CODE the value for TRSDEAL_MULTIPLE_TRADE_DEALS.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_MULTIPLE_TRADE_DEALS.SERIAL_NO
     *
     * @return the value of TRSDEAL_MULTIPLE_TRADE_DEALS.SERIAL_NO
     */
    public BigDecimal getSERIAL_NO() {
        return SERIAL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_MULTIPLE_TRADE_DEALS.SERIAL_NO
     *
     * @param SERIAL_NO the value for TRSDEAL_MULTIPLE_TRADE_DEALS.SERIAL_NO
     */
    public void setSERIAL_NO(BigDecimal SERIAL_NO) {
        this.SERIAL_NO = SERIAL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_MULTIPLE_TRADE_DEALS.TRADE_REF_NO
     *
     * @return the value of TRSDEAL_MULTIPLE_TRADE_DEALS.TRADE_REF_NO
     */
    public BigDecimal getTRADE_REF_NO() {
        return TRADE_REF_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_MULTIPLE_TRADE_DEALS.TRADE_REF_NO
     *
     * @param TRADE_REF_NO the value for TRSDEAL_MULTIPLE_TRADE_DEALS.TRADE_REF_NO
     */
    public void setTRADE_REF_NO(BigDecimal TRADE_REF_NO) {
        this.TRADE_REF_NO = TRADE_REF_NO;
    }
}