package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class TRSDEAL_ADDITIONAL_INFOVO extends TRSDEAL_ADDITIONAL_INFOVOKey {
    /**
     * This field corresponds to the database column TRSDEAL_ADDITIONAL_INFO.PROPERTY_INSURED_AMT
     */
    private BigDecimal PROPERTY_INSURED_AMT;

    /**
     * This field corresponds to the database column TRSDEAL_ADDITIONAL_INFO.PROPERTY_PREMIUM_AMT
     */
    private BigDecimal PROPERTY_PREMIUM_AMT;

    /**
     * This field corresponds to the database column TRSDEAL_ADDITIONAL_INFO.PROPERTY_RATE
     */
    private BigDecimal PROPERTY_RATE;

    /**
     * This field corresponds to the database column TRSDEAL_ADDITIONAL_INFO.PROPERTY_MONTHLY_DEDUCTION
     */
    private BigDecimal PROPERTY_MONTHLY_DEDUCTION;

    /**
     * This field corresponds to the database column TRSDEAL_ADDITIONAL_INFO.PROPERTY_INSURANCE_DATE
     */
    private Date PROPERTY_INSURANCE_DATE;

    /**
     * This field corresponds to the database column TRSDEAL_ADDITIONAL_INFO.PROPERTY_RENEWAL_MONTH
     */
    private BigDecimal PROPERTY_RENEWAL_MONTH;

    /**
     * This field corresponds to the database column TRSDEAL_ADDITIONAL_INFO.PROPERTY_ADDRESS
     */
    private String PROPERTY_ADDRESS;

    /**
     * This field corresponds to the database column TRSDEAL_ADDITIONAL_INFO.PROPERTY_REMAINING_TENURE
     */
    private BigDecimal PROPERTY_REMAINING_TENURE;

    /**
     * This field corresponds to the database column TRSDEAL_ADDITIONAL_INFO.LIFE_INSURED_AMT
     */
    private BigDecimal LIFE_INSURED_AMT;

    /**
     * This field corresponds to the database column TRSDEAL_ADDITIONAL_INFO.LIFE_PREMIUM_AMT
     */
    private BigDecimal LIFE_PREMIUM_AMT;

    /**
     * This field corresponds to the database column TRSDEAL_ADDITIONAL_INFO.LIFE_RATE
     */
    private BigDecimal LIFE_RATE;

    /**
     * This field corresponds to the database column TRSDEAL_ADDITIONAL_INFO.LIFE_MONTHLY_DEDUCTION
     */
    private BigDecimal LIFE_MONTHLY_DEDUCTION;

    /**
     * This field corresponds to the database column TRSDEAL_ADDITIONAL_INFO.LIFE_TENURE
     */
    private BigDecimal LIFE_TENURE;

    /**
     * This field corresponds to the database column TRSDEAL_ADDITIONAL_INFO.LIFE_MODE_PREMIUM
     */
    private String LIFE_MODE_PREMIUM;

    /**
     * This field corresponds to the database column TRSDEAL_ADDITIONAL_INFO.LIFE_ISSUANCE_DATE
     */
    private Date LIFE_ISSUANCE_DATE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_ADDITIONAL_INFO.PROPERTY_INSURED_AMT
     *
     * @return the value of TRSDEAL_ADDITIONAL_INFO.PROPERTY_INSURED_AMT
     */
    public BigDecimal getPROPERTY_INSURED_AMT() {
        return PROPERTY_INSURED_AMT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_ADDITIONAL_INFO.PROPERTY_INSURED_AMT
     *
     * @param PROPERTY_INSURED_AMT the value for TRSDEAL_ADDITIONAL_INFO.PROPERTY_INSURED_AMT
     */
    public void setPROPERTY_INSURED_AMT(BigDecimal PROPERTY_INSURED_AMT) {
        this.PROPERTY_INSURED_AMT = PROPERTY_INSURED_AMT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_ADDITIONAL_INFO.PROPERTY_PREMIUM_AMT
     *
     * @return the value of TRSDEAL_ADDITIONAL_INFO.PROPERTY_PREMIUM_AMT
     */
    public BigDecimal getPROPERTY_PREMIUM_AMT() {
        return PROPERTY_PREMIUM_AMT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_ADDITIONAL_INFO.PROPERTY_PREMIUM_AMT
     *
     * @param PROPERTY_PREMIUM_AMT the value for TRSDEAL_ADDITIONAL_INFO.PROPERTY_PREMIUM_AMT
     */
    public void setPROPERTY_PREMIUM_AMT(BigDecimal PROPERTY_PREMIUM_AMT) {
        this.PROPERTY_PREMIUM_AMT = PROPERTY_PREMIUM_AMT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_ADDITIONAL_INFO.PROPERTY_RATE
     *
     * @return the value of TRSDEAL_ADDITIONAL_INFO.PROPERTY_RATE
     */
    public BigDecimal getPROPERTY_RATE() {
        return PROPERTY_RATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_ADDITIONAL_INFO.PROPERTY_RATE
     *
     * @param PROPERTY_RATE the value for TRSDEAL_ADDITIONAL_INFO.PROPERTY_RATE
     */
    public void setPROPERTY_RATE(BigDecimal PROPERTY_RATE) {
        this.PROPERTY_RATE = PROPERTY_RATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_ADDITIONAL_INFO.PROPERTY_MONTHLY_DEDUCTION
     *
     * @return the value of TRSDEAL_ADDITIONAL_INFO.PROPERTY_MONTHLY_DEDUCTION
     */
    public BigDecimal getPROPERTY_MONTHLY_DEDUCTION() {
        return PROPERTY_MONTHLY_DEDUCTION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_ADDITIONAL_INFO.PROPERTY_MONTHLY_DEDUCTION
     *
     * @param PROPERTY_MONTHLY_DEDUCTION the value for TRSDEAL_ADDITIONAL_INFO.PROPERTY_MONTHLY_DEDUCTION
     */
    public void setPROPERTY_MONTHLY_DEDUCTION(BigDecimal PROPERTY_MONTHLY_DEDUCTION) {
        this.PROPERTY_MONTHLY_DEDUCTION = PROPERTY_MONTHLY_DEDUCTION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_ADDITIONAL_INFO.PROPERTY_INSURANCE_DATE
     *
     * @return the value of TRSDEAL_ADDITIONAL_INFO.PROPERTY_INSURANCE_DATE
     */
    public Date getPROPERTY_INSURANCE_DATE() {
        return PROPERTY_INSURANCE_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_ADDITIONAL_INFO.PROPERTY_INSURANCE_DATE
     *
     * @param PROPERTY_INSURANCE_DATE the value for TRSDEAL_ADDITIONAL_INFO.PROPERTY_INSURANCE_DATE
     */
    public void setPROPERTY_INSURANCE_DATE(Date PROPERTY_INSURANCE_DATE) {
        this.PROPERTY_INSURANCE_DATE = PROPERTY_INSURANCE_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_ADDITIONAL_INFO.PROPERTY_RENEWAL_MONTH
     *
     * @return the value of TRSDEAL_ADDITIONAL_INFO.PROPERTY_RENEWAL_MONTH
     */
    public BigDecimal getPROPERTY_RENEWAL_MONTH() {
        return PROPERTY_RENEWAL_MONTH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_ADDITIONAL_INFO.PROPERTY_RENEWAL_MONTH
     *
     * @param PROPERTY_RENEWAL_MONTH the value for TRSDEAL_ADDITIONAL_INFO.PROPERTY_RENEWAL_MONTH
     */
    public void setPROPERTY_RENEWAL_MONTH(BigDecimal PROPERTY_RENEWAL_MONTH) {
        this.PROPERTY_RENEWAL_MONTH = PROPERTY_RENEWAL_MONTH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_ADDITIONAL_INFO.PROPERTY_ADDRESS
     *
     * @return the value of TRSDEAL_ADDITIONAL_INFO.PROPERTY_ADDRESS
     */
    public String getPROPERTY_ADDRESS() {
        return PROPERTY_ADDRESS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_ADDITIONAL_INFO.PROPERTY_ADDRESS
     *
     * @param PROPERTY_ADDRESS the value for TRSDEAL_ADDITIONAL_INFO.PROPERTY_ADDRESS
     */
    public void setPROPERTY_ADDRESS(String PROPERTY_ADDRESS) {
        this.PROPERTY_ADDRESS = PROPERTY_ADDRESS == null ? null : PROPERTY_ADDRESS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_ADDITIONAL_INFO.PROPERTY_REMAINING_TENURE
     *
     * @return the value of TRSDEAL_ADDITIONAL_INFO.PROPERTY_REMAINING_TENURE
     */
    public BigDecimal getPROPERTY_REMAINING_TENURE() {
        return PROPERTY_REMAINING_TENURE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_ADDITIONAL_INFO.PROPERTY_REMAINING_TENURE
     *
     * @param PROPERTY_REMAINING_TENURE the value for TRSDEAL_ADDITIONAL_INFO.PROPERTY_REMAINING_TENURE
     */
    public void setPROPERTY_REMAINING_TENURE(BigDecimal PROPERTY_REMAINING_TENURE) {
        this.PROPERTY_REMAINING_TENURE = PROPERTY_REMAINING_TENURE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_ADDITIONAL_INFO.LIFE_INSURED_AMT
     *
     * @return the value of TRSDEAL_ADDITIONAL_INFO.LIFE_INSURED_AMT
     */
    public BigDecimal getLIFE_INSURED_AMT() {
        return LIFE_INSURED_AMT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_ADDITIONAL_INFO.LIFE_INSURED_AMT
     *
     * @param LIFE_INSURED_AMT the value for TRSDEAL_ADDITIONAL_INFO.LIFE_INSURED_AMT
     */
    public void setLIFE_INSURED_AMT(BigDecimal LIFE_INSURED_AMT) {
        this.LIFE_INSURED_AMT = LIFE_INSURED_AMT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_ADDITIONAL_INFO.LIFE_PREMIUM_AMT
     *
     * @return the value of TRSDEAL_ADDITIONAL_INFO.LIFE_PREMIUM_AMT
     */
    public BigDecimal getLIFE_PREMIUM_AMT() {
        return LIFE_PREMIUM_AMT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_ADDITIONAL_INFO.LIFE_PREMIUM_AMT
     *
     * @param LIFE_PREMIUM_AMT the value for TRSDEAL_ADDITIONAL_INFO.LIFE_PREMIUM_AMT
     */
    public void setLIFE_PREMIUM_AMT(BigDecimal LIFE_PREMIUM_AMT) {
        this.LIFE_PREMIUM_AMT = LIFE_PREMIUM_AMT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_ADDITIONAL_INFO.LIFE_RATE
     *
     * @return the value of TRSDEAL_ADDITIONAL_INFO.LIFE_RATE
     */
    public BigDecimal getLIFE_RATE() {
        return LIFE_RATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_ADDITIONAL_INFO.LIFE_RATE
     *
     * @param LIFE_RATE the value for TRSDEAL_ADDITIONAL_INFO.LIFE_RATE
     */
    public void setLIFE_RATE(BigDecimal LIFE_RATE) {
        this.LIFE_RATE = LIFE_RATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_ADDITIONAL_INFO.LIFE_MONTHLY_DEDUCTION
     *
     * @return the value of TRSDEAL_ADDITIONAL_INFO.LIFE_MONTHLY_DEDUCTION
     */
    public BigDecimal getLIFE_MONTHLY_DEDUCTION() {
        return LIFE_MONTHLY_DEDUCTION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_ADDITIONAL_INFO.LIFE_MONTHLY_DEDUCTION
     *
     * @param LIFE_MONTHLY_DEDUCTION the value for TRSDEAL_ADDITIONAL_INFO.LIFE_MONTHLY_DEDUCTION
     */
    public void setLIFE_MONTHLY_DEDUCTION(BigDecimal LIFE_MONTHLY_DEDUCTION) {
        this.LIFE_MONTHLY_DEDUCTION = LIFE_MONTHLY_DEDUCTION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_ADDITIONAL_INFO.LIFE_TENURE
     *
     * @return the value of TRSDEAL_ADDITIONAL_INFO.LIFE_TENURE
     */
    public BigDecimal getLIFE_TENURE() {
        return LIFE_TENURE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_ADDITIONAL_INFO.LIFE_TENURE
     *
     * @param LIFE_TENURE the value for TRSDEAL_ADDITIONAL_INFO.LIFE_TENURE
     */
    public void setLIFE_TENURE(BigDecimal LIFE_TENURE) {
        this.LIFE_TENURE = LIFE_TENURE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_ADDITIONAL_INFO.LIFE_MODE_PREMIUM
     *
     * @return the value of TRSDEAL_ADDITIONAL_INFO.LIFE_MODE_PREMIUM
     */
    public String getLIFE_MODE_PREMIUM() {
        return LIFE_MODE_PREMIUM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_ADDITIONAL_INFO.LIFE_MODE_PREMIUM
     *
     * @param LIFE_MODE_PREMIUM the value for TRSDEAL_ADDITIONAL_INFO.LIFE_MODE_PREMIUM
     */
    public void setLIFE_MODE_PREMIUM(String LIFE_MODE_PREMIUM) {
        this.LIFE_MODE_PREMIUM = LIFE_MODE_PREMIUM == null ? null : LIFE_MODE_PREMIUM.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSDEAL_ADDITIONAL_INFO.LIFE_ISSUANCE_DATE
     *
     * @return the value of TRSDEAL_ADDITIONAL_INFO.LIFE_ISSUANCE_DATE
     */
    public Date getLIFE_ISSUANCE_DATE() {
        return LIFE_ISSUANCE_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSDEAL_ADDITIONAL_INFO.LIFE_ISSUANCE_DATE
     *
     * @param LIFE_ISSUANCE_DATE the value for TRSDEAL_ADDITIONAL_INFO.LIFE_ISSUANCE_DATE
     */
    public void setLIFE_ISSUANCE_DATE(Date LIFE_ISSUANCE_DATE) {
        this.LIFE_ISSUANCE_DATE = LIFE_ISSUANCE_DATE;
    }
}