package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class TRSEXPREVVO extends TRSEXPREVVOKey {
    /**
     * This field corresponds to the database column TRSEXPREV.TYPE
     */
    private String TYPE;

    /**
     * This field corresponds to the database column TRSEXPREV.BRIEF_NAME_ENG
     */
    private String BRIEF_NAME_ENG;

    /**
     * This field corresponds to the database column TRSEXPREV.LONG_NAME_ENG
     */
    private String LONG_NAME_ENG;

    /**
     * This field corresponds to the database column TRSEXPREV.BRIEF_NAME_ARAB
     */
    private String BRIEF_NAME_ARAB;

    /**
     * This field corresponds to the database column TRSEXPREV.LONG_NAME_ARAB
     */
    private String LONG_NAME_ARAB;

    /**
     * This field corresponds to the database column TRSEXPREV.DR_ACC_BRANCH
     */
    private BigDecimal DR_ACC_BRANCH;

    /**
     * This field corresponds to the database column TRSEXPREV.DR_ACC_CURRENCY
     */
    private BigDecimal DR_ACC_CURRENCY;

    /**
     * This field corresponds to the database column TRSEXPREV.DR_ACC_GL
     */
    private BigDecimal DR_ACC_GL;

    /**
     * This field corresponds to the database column TRSEXPREV.DR_ACC_CIF_SUB_NO
     */
    private BigDecimal DR_ACC_CIF_SUB_NO;

    /**
     * This field corresponds to the database column TRSEXPREV.DR_ACC_SL_NO
     */
    private BigDecimal DR_ACC_SL_NO;

    /**
     * This field corresponds to the database column TRSEXPREV.CR_ACC_BRANCH
     */
    private BigDecimal CR_ACC_BRANCH;

    /**
     * This field corresponds to the database column TRSEXPREV.CR_ACC_CURRENCY
     */
    private BigDecimal CR_ACC_CURRENCY;

    /**
     * This field corresponds to the database column TRSEXPREV.CR_ACC_GL
     */
    private BigDecimal CR_ACC_GL;

    /**
     * This field corresponds to the database column TRSEXPREV.CR_ACC_CIF_SUB_NO
     */
    private BigDecimal CR_ACC_CIF_SUB_NO;

    /**
     * This field corresponds to the database column TRSEXPREV.CR_ACC_SL_NO
     */
    private BigDecimal CR_ACC_SL_NO;

    /**
     * This field corresponds to the database column TRSEXPREV.CLI_DR_ACC_CURRENCY
     */
    private BigDecimal CLI_DR_ACC_CURRENCY;

    /**
     * This field corresponds to the database column TRSEXPREV.CLI_DR_ACC_GL
     */
    private BigDecimal CLI_DR_ACC_GL;

    /**
     * This field corresponds to the database column TRSEXPREV.CLI_DR_ACC_CIF_SUB_NO
     */
    private BigDecimal CLI_DR_ACC_CIF_SUB_NO;

    /**
     * This field corresponds to the database column TRSEXPREV.CLI_DR_ACC_SL_NO
     */
    private BigDecimal CLI_DR_ACC_SL_NO;

    /**
     * This field corresponds to the database column TRSEXPREV.CLI_CR_ACC_CURRENCY
     */
    private BigDecimal CLI_CR_ACC_CURRENCY;

    /**
     * This field corresponds to the database column TRSEXPREV.CLI_CR_ACC_GL
     */
    private BigDecimal CLI_CR_ACC_GL;

    /**
     * This field corresponds to the database column TRSEXPREV.CLI_CR_ACC_CIF_SUB_NO
     */
    private BigDecimal CLI_CR_ACC_CIF_SUB_NO;

    /**
     * This field corresponds to the database column TRSEXPREV.CLI_CR_ACC_SL_NO
     */
    private BigDecimal CLI_CR_ACC_SL_NO;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSEXPREV.TYPE
     *
     * @return the value of TRSEXPREV.TYPE
     */
    public String getTYPE() {
        return TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSEXPREV.TYPE
     *
     * @param TYPE the value for TRSEXPREV.TYPE
     */
    public void setTYPE(String TYPE) {
        this.TYPE = TYPE == null ? null : TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSEXPREV.BRIEF_NAME_ENG
     *
     * @return the value of TRSEXPREV.BRIEF_NAME_ENG
     */
    public String getBRIEF_NAME_ENG() {
        return BRIEF_NAME_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSEXPREV.BRIEF_NAME_ENG
     *
     * @param BRIEF_NAME_ENG the value for TRSEXPREV.BRIEF_NAME_ENG
     */
    public void setBRIEF_NAME_ENG(String BRIEF_NAME_ENG) {
        this.BRIEF_NAME_ENG = BRIEF_NAME_ENG == null ? null : BRIEF_NAME_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSEXPREV.LONG_NAME_ENG
     *
     * @return the value of TRSEXPREV.LONG_NAME_ENG
     */
    public String getLONG_NAME_ENG() {
        return LONG_NAME_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSEXPREV.LONG_NAME_ENG
     *
     * @param LONG_NAME_ENG the value for TRSEXPREV.LONG_NAME_ENG
     */
    public void setLONG_NAME_ENG(String LONG_NAME_ENG) {
        this.LONG_NAME_ENG = LONG_NAME_ENG == null ? null : LONG_NAME_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSEXPREV.BRIEF_NAME_ARAB
     *
     * @return the value of TRSEXPREV.BRIEF_NAME_ARAB
     */
    public String getBRIEF_NAME_ARAB() {
        return BRIEF_NAME_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSEXPREV.BRIEF_NAME_ARAB
     *
     * @param BRIEF_NAME_ARAB the value for TRSEXPREV.BRIEF_NAME_ARAB
     */
    public void setBRIEF_NAME_ARAB(String BRIEF_NAME_ARAB) {
        this.BRIEF_NAME_ARAB = BRIEF_NAME_ARAB == null ? null : BRIEF_NAME_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSEXPREV.LONG_NAME_ARAB
     *
     * @return the value of TRSEXPREV.LONG_NAME_ARAB
     */
    public String getLONG_NAME_ARAB() {
        return LONG_NAME_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSEXPREV.LONG_NAME_ARAB
     *
     * @param LONG_NAME_ARAB the value for TRSEXPREV.LONG_NAME_ARAB
     */
    public void setLONG_NAME_ARAB(String LONG_NAME_ARAB) {
        this.LONG_NAME_ARAB = LONG_NAME_ARAB == null ? null : LONG_NAME_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSEXPREV.DR_ACC_BRANCH
     *
     * @return the value of TRSEXPREV.DR_ACC_BRANCH
     */
    public BigDecimal getDR_ACC_BRANCH() {
        return DR_ACC_BRANCH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSEXPREV.DR_ACC_BRANCH
     *
     * @param DR_ACC_BRANCH the value for TRSEXPREV.DR_ACC_BRANCH
     */
    public void setDR_ACC_BRANCH(BigDecimal DR_ACC_BRANCH) {
        this.DR_ACC_BRANCH = DR_ACC_BRANCH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSEXPREV.DR_ACC_CURRENCY
     *
     * @return the value of TRSEXPREV.DR_ACC_CURRENCY
     */
    public BigDecimal getDR_ACC_CURRENCY() {
        return DR_ACC_CURRENCY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSEXPREV.DR_ACC_CURRENCY
     *
     * @param DR_ACC_CURRENCY the value for TRSEXPREV.DR_ACC_CURRENCY
     */
    public void setDR_ACC_CURRENCY(BigDecimal DR_ACC_CURRENCY) {
        this.DR_ACC_CURRENCY = DR_ACC_CURRENCY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSEXPREV.DR_ACC_GL
     *
     * @return the value of TRSEXPREV.DR_ACC_GL
     */
    public BigDecimal getDR_ACC_GL() {
        return DR_ACC_GL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSEXPREV.DR_ACC_GL
     *
     * @param DR_ACC_GL the value for TRSEXPREV.DR_ACC_GL
     */
    public void setDR_ACC_GL(BigDecimal DR_ACC_GL) {
        this.DR_ACC_GL = DR_ACC_GL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSEXPREV.DR_ACC_CIF_SUB_NO
     *
     * @return the value of TRSEXPREV.DR_ACC_CIF_SUB_NO
     */
    public BigDecimal getDR_ACC_CIF_SUB_NO() {
        return DR_ACC_CIF_SUB_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSEXPREV.DR_ACC_CIF_SUB_NO
     *
     * @param DR_ACC_CIF_SUB_NO the value for TRSEXPREV.DR_ACC_CIF_SUB_NO
     */
    public void setDR_ACC_CIF_SUB_NO(BigDecimal DR_ACC_CIF_SUB_NO) {
        this.DR_ACC_CIF_SUB_NO = DR_ACC_CIF_SUB_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSEXPREV.DR_ACC_SL_NO
     *
     * @return the value of TRSEXPREV.DR_ACC_SL_NO
     */
    public BigDecimal getDR_ACC_SL_NO() {
        return DR_ACC_SL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSEXPREV.DR_ACC_SL_NO
     *
     * @param DR_ACC_SL_NO the value for TRSEXPREV.DR_ACC_SL_NO
     */
    public void setDR_ACC_SL_NO(BigDecimal DR_ACC_SL_NO) {
        this.DR_ACC_SL_NO = DR_ACC_SL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSEXPREV.CR_ACC_BRANCH
     *
     * @return the value of TRSEXPREV.CR_ACC_BRANCH
     */
    public BigDecimal getCR_ACC_BRANCH() {
        return CR_ACC_BRANCH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSEXPREV.CR_ACC_BRANCH
     *
     * @param CR_ACC_BRANCH the value for TRSEXPREV.CR_ACC_BRANCH
     */
    public void setCR_ACC_BRANCH(BigDecimal CR_ACC_BRANCH) {
        this.CR_ACC_BRANCH = CR_ACC_BRANCH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSEXPREV.CR_ACC_CURRENCY
     *
     * @return the value of TRSEXPREV.CR_ACC_CURRENCY
     */
    public BigDecimal getCR_ACC_CURRENCY() {
        return CR_ACC_CURRENCY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSEXPREV.CR_ACC_CURRENCY
     *
     * @param CR_ACC_CURRENCY the value for TRSEXPREV.CR_ACC_CURRENCY
     */
    public void setCR_ACC_CURRENCY(BigDecimal CR_ACC_CURRENCY) {
        this.CR_ACC_CURRENCY = CR_ACC_CURRENCY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSEXPREV.CR_ACC_GL
     *
     * @return the value of TRSEXPREV.CR_ACC_GL
     */
    public BigDecimal getCR_ACC_GL() {
        return CR_ACC_GL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSEXPREV.CR_ACC_GL
     *
     * @param CR_ACC_GL the value for TRSEXPREV.CR_ACC_GL
     */
    public void setCR_ACC_GL(BigDecimal CR_ACC_GL) {
        this.CR_ACC_GL = CR_ACC_GL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSEXPREV.CR_ACC_CIF_SUB_NO
     *
     * @return the value of TRSEXPREV.CR_ACC_CIF_SUB_NO
     */
    public BigDecimal getCR_ACC_CIF_SUB_NO() {
        return CR_ACC_CIF_SUB_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSEXPREV.CR_ACC_CIF_SUB_NO
     *
     * @param CR_ACC_CIF_SUB_NO the value for TRSEXPREV.CR_ACC_CIF_SUB_NO
     */
    public void setCR_ACC_CIF_SUB_NO(BigDecimal CR_ACC_CIF_SUB_NO) {
        this.CR_ACC_CIF_SUB_NO = CR_ACC_CIF_SUB_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSEXPREV.CR_ACC_SL_NO
     *
     * @return the value of TRSEXPREV.CR_ACC_SL_NO
     */
    public BigDecimal getCR_ACC_SL_NO() {
        return CR_ACC_SL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSEXPREV.CR_ACC_SL_NO
     *
     * @param CR_ACC_SL_NO the value for TRSEXPREV.CR_ACC_SL_NO
     */
    public void setCR_ACC_SL_NO(BigDecimal CR_ACC_SL_NO) {
        this.CR_ACC_SL_NO = CR_ACC_SL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSEXPREV.CLI_DR_ACC_CURRENCY
     *
     * @return the value of TRSEXPREV.CLI_DR_ACC_CURRENCY
     */
    public BigDecimal getCLI_DR_ACC_CURRENCY() {
        return CLI_DR_ACC_CURRENCY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSEXPREV.CLI_DR_ACC_CURRENCY
     *
     * @param CLI_DR_ACC_CURRENCY the value for TRSEXPREV.CLI_DR_ACC_CURRENCY
     */
    public void setCLI_DR_ACC_CURRENCY(BigDecimal CLI_DR_ACC_CURRENCY) {
        this.CLI_DR_ACC_CURRENCY = CLI_DR_ACC_CURRENCY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSEXPREV.CLI_DR_ACC_GL
     *
     * @return the value of TRSEXPREV.CLI_DR_ACC_GL
     */
    public BigDecimal getCLI_DR_ACC_GL() {
        return CLI_DR_ACC_GL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSEXPREV.CLI_DR_ACC_GL
     *
     * @param CLI_DR_ACC_GL the value for TRSEXPREV.CLI_DR_ACC_GL
     */
    public void setCLI_DR_ACC_GL(BigDecimal CLI_DR_ACC_GL) {
        this.CLI_DR_ACC_GL = CLI_DR_ACC_GL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSEXPREV.CLI_DR_ACC_CIF_SUB_NO
     *
     * @return the value of TRSEXPREV.CLI_DR_ACC_CIF_SUB_NO
     */
    public BigDecimal getCLI_DR_ACC_CIF_SUB_NO() {
        return CLI_DR_ACC_CIF_SUB_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSEXPREV.CLI_DR_ACC_CIF_SUB_NO
     *
     * @param CLI_DR_ACC_CIF_SUB_NO the value for TRSEXPREV.CLI_DR_ACC_CIF_SUB_NO
     */
    public void setCLI_DR_ACC_CIF_SUB_NO(BigDecimal CLI_DR_ACC_CIF_SUB_NO) {
        this.CLI_DR_ACC_CIF_SUB_NO = CLI_DR_ACC_CIF_SUB_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSEXPREV.CLI_DR_ACC_SL_NO
     *
     * @return the value of TRSEXPREV.CLI_DR_ACC_SL_NO
     */
    public BigDecimal getCLI_DR_ACC_SL_NO() {
        return CLI_DR_ACC_SL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSEXPREV.CLI_DR_ACC_SL_NO
     *
     * @param CLI_DR_ACC_SL_NO the value for TRSEXPREV.CLI_DR_ACC_SL_NO
     */
    public void setCLI_DR_ACC_SL_NO(BigDecimal CLI_DR_ACC_SL_NO) {
        this.CLI_DR_ACC_SL_NO = CLI_DR_ACC_SL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSEXPREV.CLI_CR_ACC_CURRENCY
     *
     * @return the value of TRSEXPREV.CLI_CR_ACC_CURRENCY
     */
    public BigDecimal getCLI_CR_ACC_CURRENCY() {
        return CLI_CR_ACC_CURRENCY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSEXPREV.CLI_CR_ACC_CURRENCY
     *
     * @param CLI_CR_ACC_CURRENCY the value for TRSEXPREV.CLI_CR_ACC_CURRENCY
     */
    public void setCLI_CR_ACC_CURRENCY(BigDecimal CLI_CR_ACC_CURRENCY) {
        this.CLI_CR_ACC_CURRENCY = CLI_CR_ACC_CURRENCY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSEXPREV.CLI_CR_ACC_GL
     *
     * @return the value of TRSEXPREV.CLI_CR_ACC_GL
     */
    public BigDecimal getCLI_CR_ACC_GL() {
        return CLI_CR_ACC_GL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSEXPREV.CLI_CR_ACC_GL
     *
     * @param CLI_CR_ACC_GL the value for TRSEXPREV.CLI_CR_ACC_GL
     */
    public void setCLI_CR_ACC_GL(BigDecimal CLI_CR_ACC_GL) {
        this.CLI_CR_ACC_GL = CLI_CR_ACC_GL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSEXPREV.CLI_CR_ACC_CIF_SUB_NO
     *
     * @return the value of TRSEXPREV.CLI_CR_ACC_CIF_SUB_NO
     */
    public BigDecimal getCLI_CR_ACC_CIF_SUB_NO() {
        return CLI_CR_ACC_CIF_SUB_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSEXPREV.CLI_CR_ACC_CIF_SUB_NO
     *
     * @param CLI_CR_ACC_CIF_SUB_NO the value for TRSEXPREV.CLI_CR_ACC_CIF_SUB_NO
     */
    public void setCLI_CR_ACC_CIF_SUB_NO(BigDecimal CLI_CR_ACC_CIF_SUB_NO) {
        this.CLI_CR_ACC_CIF_SUB_NO = CLI_CR_ACC_CIF_SUB_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSEXPREV.CLI_CR_ACC_SL_NO
     *
     * @return the value of TRSEXPREV.CLI_CR_ACC_SL_NO
     */
    public BigDecimal getCLI_CR_ACC_SL_NO() {
        return CLI_CR_ACC_SL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSEXPREV.CLI_CR_ACC_SL_NO
     *
     * @param CLI_CR_ACC_SL_NO the value for TRSEXPREV.CLI_CR_ACC_SL_NO
     */
    public void setCLI_CR_ACC_SL_NO(BigDecimal CLI_CR_ACC_SL_NO) {
        this.CLI_CR_ACC_SL_NO = CLI_CR_ACC_SL_NO;
    }
}