package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class TRSFOREX_BASE_CYVOKey extends BaseVO {
    /**
     * This field corresponds to the database column TRSFOREX_BASE_CY.BASE_CY
     */
    private BigDecimal BASE_CY;

    /**
     * This field corresponds to the database column TRSFOREX_BASE_CY.BOUGHT_CY
     */
    private BigDecimal BOUGHT_CY;

    /**
     * This field corresponds to the database column TRSFOREX_BASE_CY.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column TRSFOREX_BASE_CY.SOLD_CY
     */
    private BigDecimal SOLD_CY;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSFOREX_BASE_CY.BASE_CY
     *
     * @return the value of TRSFOREX_BASE_CY.BASE_CY
     */
    public BigDecimal getBASE_CY() {
        return BASE_CY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSFOREX_BASE_CY.BASE_CY
     *
     * @param BASE_CY the value for TRSFOREX_BASE_CY.BASE_CY
     */
    public void setBASE_CY(BigDecimal BASE_CY) {
        this.BASE_CY = BASE_CY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSFOREX_BASE_CY.BOUGHT_CY
     *
     * @return the value of TRSFOREX_BASE_CY.BOUGHT_CY
     */
    public BigDecimal getBOUGHT_CY() {
        return BOUGHT_CY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSFOREX_BASE_CY.BOUGHT_CY
     *
     * @param BOUGHT_CY the value for TRSFOREX_BASE_CY.BOUGHT_CY
     */
    public void setBOUGHT_CY(BigDecimal BOUGHT_CY) {
        this.BOUGHT_CY = BOUGHT_CY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSFOREX_BASE_CY.COMP_CODE
     *
     * @return the value of TRSFOREX_BASE_CY.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSFOREX_BASE_CY.COMP_CODE
     *
     * @param COMP_CODE the value for TRSFOREX_BASE_CY.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSFOREX_BASE_CY.SOLD_CY
     *
     * @return the value of TRSFOREX_BASE_CY.SOLD_CY
     */
    public BigDecimal getSOLD_CY() {
        return SOLD_CY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSFOREX_BASE_CY.SOLD_CY
     *
     * @param SOLD_CY the value for TRSFOREX_BASE_CY.SOLD_CY
     */
    public void setSOLD_CY(BigDecimal SOLD_CY) {
        this.SOLD_CY = SOLD_CY;
    }
}