package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class TRSHIJRI_CALENDARVO extends TRSHIJRI_CALENDARVOKey {
    /**
     * This field corresponds to the database column TRSHIJRI_CALENDAR.NO_OF_DAYS
     */
    private BigDecimal NO_OF_DAYS;

    /**
     * This field corresponds to the database column TRSHIJRI_CALENDAR.CREATED_BY
     */
    private String CREATED_BY;

    /**
     * This field corresponds to the database column TRSHIJRI_CALENDAR.DATE_CREATED
     */
    private Date DATE_CREATED;

    /**
     * This field corresponds to the database column TRSHIJRI_CALENDAR.STATUS
     */
    private String STATUS;

    /**
     * This field corresponds to the database column TRSHIJRI_CALENDAR.APPROVED_BY
     */
    private String APPROVED_BY;

    /**
     * This field corresponds to the database column TRSHIJRI_CALENDAR.MODIFIED_BY
     */
    private String MODIFIED_BY;

    /**
     * This field corresponds to the database column TRSHIJRI_CALENDAR.DATE_MODIFIED
     */
    private Date DATE_MODIFIED;

    /**
     * This field corresponds to the database column TRSHIJRI_CALENDAR.DATE_DELETED
     */
    private Date DATE_DELETED;

    /**
     * This field corresponds to the database column TRSHIJRI_CALENDAR.DATE_APPROVED
     */
    private Date DATE_APPROVED;

    /**
     * This field corresponds to the database column TRSHIJRI_CALENDAR.DELETED_BY
     */
    private String DELETED_BY;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSHIJRI_CALENDAR.NO_OF_DAYS
     *
     * @return the value of TRSHIJRI_CALENDAR.NO_OF_DAYS
     */
    public BigDecimal getNO_OF_DAYS() {
        return NO_OF_DAYS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSHIJRI_CALENDAR.NO_OF_DAYS
     *
     * @param NO_OF_DAYS the value for TRSHIJRI_CALENDAR.NO_OF_DAYS
     */
    public void setNO_OF_DAYS(BigDecimal NO_OF_DAYS) {
        this.NO_OF_DAYS = NO_OF_DAYS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSHIJRI_CALENDAR.CREATED_BY
     *
     * @return the value of TRSHIJRI_CALENDAR.CREATED_BY
     */
    public String getCREATED_BY() {
        return CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSHIJRI_CALENDAR.CREATED_BY
     *
     * @param CREATED_BY the value for TRSHIJRI_CALENDAR.CREATED_BY
     */
    public void setCREATED_BY(String CREATED_BY) {
        this.CREATED_BY = CREATED_BY == null ? null : CREATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSHIJRI_CALENDAR.DATE_CREATED
     *
     * @return the value of TRSHIJRI_CALENDAR.DATE_CREATED
     */
    public Date getDATE_CREATED() {
        return DATE_CREATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSHIJRI_CALENDAR.DATE_CREATED
     *
     * @param DATE_CREATED the value for TRSHIJRI_CALENDAR.DATE_CREATED
     */
    public void setDATE_CREATED(Date DATE_CREATED) {
        this.DATE_CREATED = DATE_CREATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSHIJRI_CALENDAR.STATUS
     *
     * @return the value of TRSHIJRI_CALENDAR.STATUS
     */
    public String getSTATUS() {
        return STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSHIJRI_CALENDAR.STATUS
     *
     * @param STATUS the value for TRSHIJRI_CALENDAR.STATUS
     */
    public void setSTATUS(String STATUS) {
        this.STATUS = STATUS == null ? null : STATUS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSHIJRI_CALENDAR.APPROVED_BY
     *
     * @return the value of TRSHIJRI_CALENDAR.APPROVED_BY
     */
    public String getAPPROVED_BY() {
        return APPROVED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSHIJRI_CALENDAR.APPROVED_BY
     *
     * @param APPROVED_BY the value for TRSHIJRI_CALENDAR.APPROVED_BY
     */
    public void setAPPROVED_BY(String APPROVED_BY) {
        this.APPROVED_BY = APPROVED_BY == null ? null : APPROVED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSHIJRI_CALENDAR.MODIFIED_BY
     *
     * @return the value of TRSHIJRI_CALENDAR.MODIFIED_BY
     */
    public String getMODIFIED_BY() {
        return MODIFIED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSHIJRI_CALENDAR.MODIFIED_BY
     *
     * @param MODIFIED_BY the value for TRSHIJRI_CALENDAR.MODIFIED_BY
     */
    public void setMODIFIED_BY(String MODIFIED_BY) {
        this.MODIFIED_BY = MODIFIED_BY == null ? null : MODIFIED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSHIJRI_CALENDAR.DATE_MODIFIED
     *
     * @return the value of TRSHIJRI_CALENDAR.DATE_MODIFIED
     */
    public Date getDATE_MODIFIED() {
        return DATE_MODIFIED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSHIJRI_CALENDAR.DATE_MODIFIED
     *
     * @param DATE_MODIFIED the value for TRSHIJRI_CALENDAR.DATE_MODIFIED
     */
    public void setDATE_MODIFIED(Date DATE_MODIFIED) {
        this.DATE_MODIFIED = DATE_MODIFIED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSHIJRI_CALENDAR.DATE_DELETED
     *
     * @return the value of TRSHIJRI_CALENDAR.DATE_DELETED
     */
    public Date getDATE_DELETED() {
        return DATE_DELETED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSHIJRI_CALENDAR.DATE_DELETED
     *
     * @param DATE_DELETED the value for TRSHIJRI_CALENDAR.DATE_DELETED
     */
    public void setDATE_DELETED(Date DATE_DELETED) {
        this.DATE_DELETED = DATE_DELETED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSHIJRI_CALENDAR.DATE_APPROVED
     *
     * @return the value of TRSHIJRI_CALENDAR.DATE_APPROVED
     */
    public Date getDATE_APPROVED() {
        return DATE_APPROVED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSHIJRI_CALENDAR.DATE_APPROVED
     *
     * @param DATE_APPROVED the value for TRSHIJRI_CALENDAR.DATE_APPROVED
     */
    public void setDATE_APPROVED(Date DATE_APPROVED) {
        this.DATE_APPROVED = DATE_APPROVED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSHIJRI_CALENDAR.DELETED_BY
     *
     * @return the value of TRSHIJRI_CALENDAR.DELETED_BY
     */
    public String getDELETED_BY() {
        return DELETED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSHIJRI_CALENDAR.DELETED_BY
     *
     * @param DELETED_BY the value for TRSHIJRI_CALENDAR.DELETED_BY
     */
    public void setDELETED_BY(String DELETED_BY) {
        this.DELETED_BY = DELETED_BY == null ? null : DELETED_BY.trim();
    }
}