package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class TRSINSURANCE_DEAL_DETVO extends TRSINSURANCE_DEAL_DETVOKey {
    /**
     * This field corresponds to the database column TRSINSURANCE_DEAL_DET.DEAL_NO
     */
    private BigDecimal DEAL_NO;

    /**
     * This field corresponds to the database column TRSINSURANCE_DEAL_DET.LINE_NO
     */
    private BigDecimal LINE_NO;

    /**
     * This field corresponds to the database column TRSINSURANCE_DEAL_DET.INSURANCE_CODE
     */
    private BigDecimal INSURANCE_CODE;

    /**
     * This field corresponds to the database column TRSINSURANCE_DEAL_DET.DATE_FROM
     */
    private Date DATE_FROM;

    /**
     * This field corresponds to the database column TRSINSURANCE_DEAL_DET.DATE_TO
     */
    private Date DATE_TO;

    /**
     * This field corresponds to the database column TRSINSURANCE_DEAL_DET.INSURANCE_TYPE
     */
    private BigDecimal INSURANCE_TYPE;

    /**
     * This field corresponds to the database column TRSINSURANCE_DEAL_DET.PREMIUM_CY
     */
    private BigDecimal PREMIUM_CY;

    /**
     * This field corresponds to the database column TRSINSURANCE_DEAL_DET.PREMIUM_AMT
     */
    private BigDecimal PREMIUM_AMT;

    /**
     * This field corresponds to the database column TRSINSURANCE_DEAL_DET.PREMIUM_AMT_REMAINING
     */
    private BigDecimal PREMIUM_AMT_REMAINING;

    /**
     * This field corresponds to the database column TRSINSURANCE_DEAL_DET.AMENDMENT_TYPE
     */
    private String AMENDMENT_TYPE;

    /**
     * This field corresponds to the database column TRSINSURANCE_DEAL_DET.LAST_ACCRUED_DATE
     */
    private Date LAST_ACCRUED_DATE;

    /**
     * This field corresponds to the database column TRSINSURANCE_DEAL_DET.ACCRUED_AMOUNT
     */
    private BigDecimal ACCRUED_AMOUNT;

    /**
     * This field corresponds to the database column TRSINSURANCE_DEAL_DET.AMOUNT_AMENDED
     */
    private BigDecimal AMOUNT_AMENDED;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSINSURANCE_DEAL_DET.DEAL_NO
     *
     * @return the value of TRSINSURANCE_DEAL_DET.DEAL_NO
     */
    public BigDecimal getDEAL_NO() {
        return DEAL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSINSURANCE_DEAL_DET.DEAL_NO
     *
     * @param DEAL_NO the value for TRSINSURANCE_DEAL_DET.DEAL_NO
     */
    public void setDEAL_NO(BigDecimal DEAL_NO) {
        this.DEAL_NO = DEAL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSINSURANCE_DEAL_DET.LINE_NO
     *
     * @return the value of TRSINSURANCE_DEAL_DET.LINE_NO
     */
    public BigDecimal getLINE_NO() {
        return LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSINSURANCE_DEAL_DET.LINE_NO
     *
     * @param LINE_NO the value for TRSINSURANCE_DEAL_DET.LINE_NO
     */
    public void setLINE_NO(BigDecimal LINE_NO) {
        this.LINE_NO = LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSINSURANCE_DEAL_DET.INSURANCE_CODE
     *
     * @return the value of TRSINSURANCE_DEAL_DET.INSURANCE_CODE
     */
    public BigDecimal getINSURANCE_CODE() {
        return INSURANCE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSINSURANCE_DEAL_DET.INSURANCE_CODE
     *
     * @param INSURANCE_CODE the value for TRSINSURANCE_DEAL_DET.INSURANCE_CODE
     */
    public void setINSURANCE_CODE(BigDecimal INSURANCE_CODE) {
        this.INSURANCE_CODE = INSURANCE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSINSURANCE_DEAL_DET.DATE_FROM
     *
     * @return the value of TRSINSURANCE_DEAL_DET.DATE_FROM
     */
    public Date getDATE_FROM() {
        return DATE_FROM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSINSURANCE_DEAL_DET.DATE_FROM
     *
     * @param DATE_FROM the value for TRSINSURANCE_DEAL_DET.DATE_FROM
     */
    public void setDATE_FROM(Date DATE_FROM) {
        this.DATE_FROM = DATE_FROM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSINSURANCE_DEAL_DET.DATE_TO
     *
     * @return the value of TRSINSURANCE_DEAL_DET.DATE_TO
     */
    public Date getDATE_TO() {
        return DATE_TO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSINSURANCE_DEAL_DET.DATE_TO
     *
     * @param DATE_TO the value for TRSINSURANCE_DEAL_DET.DATE_TO
     */
    public void setDATE_TO(Date DATE_TO) {
        this.DATE_TO = DATE_TO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSINSURANCE_DEAL_DET.INSURANCE_TYPE
     *
     * @return the value of TRSINSURANCE_DEAL_DET.INSURANCE_TYPE
     */
    public BigDecimal getINSURANCE_TYPE() {
        return INSURANCE_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSINSURANCE_DEAL_DET.INSURANCE_TYPE
     *
     * @param INSURANCE_TYPE the value for TRSINSURANCE_DEAL_DET.INSURANCE_TYPE
     */
    public void setINSURANCE_TYPE(BigDecimal INSURANCE_TYPE) {
        this.INSURANCE_TYPE = INSURANCE_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSINSURANCE_DEAL_DET.PREMIUM_CY
     *
     * @return the value of TRSINSURANCE_DEAL_DET.PREMIUM_CY
     */
    public BigDecimal getPREMIUM_CY() {
        return PREMIUM_CY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSINSURANCE_DEAL_DET.PREMIUM_CY
     *
     * @param PREMIUM_CY the value for TRSINSURANCE_DEAL_DET.PREMIUM_CY
     */
    public void setPREMIUM_CY(BigDecimal PREMIUM_CY) {
        this.PREMIUM_CY = PREMIUM_CY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSINSURANCE_DEAL_DET.PREMIUM_AMT
     *
     * @return the value of TRSINSURANCE_DEAL_DET.PREMIUM_AMT
     */
    public BigDecimal getPREMIUM_AMT() {
        return PREMIUM_AMT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSINSURANCE_DEAL_DET.PREMIUM_AMT
     *
     * @param PREMIUM_AMT the value for TRSINSURANCE_DEAL_DET.PREMIUM_AMT
     */
    public void setPREMIUM_AMT(BigDecimal PREMIUM_AMT) {
        this.PREMIUM_AMT = PREMIUM_AMT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSINSURANCE_DEAL_DET.PREMIUM_AMT_REMAINING
     *
     * @return the value of TRSINSURANCE_DEAL_DET.PREMIUM_AMT_REMAINING
     */
    public BigDecimal getPREMIUM_AMT_REMAINING() {
        return PREMIUM_AMT_REMAINING;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSINSURANCE_DEAL_DET.PREMIUM_AMT_REMAINING
     *
     * @param PREMIUM_AMT_REMAINING the value for TRSINSURANCE_DEAL_DET.PREMIUM_AMT_REMAINING
     */
    public void setPREMIUM_AMT_REMAINING(BigDecimal PREMIUM_AMT_REMAINING) {
        this.PREMIUM_AMT_REMAINING = PREMIUM_AMT_REMAINING;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSINSURANCE_DEAL_DET.AMENDMENT_TYPE
     *
     * @return the value of TRSINSURANCE_DEAL_DET.AMENDMENT_TYPE
     */
    public String getAMENDMENT_TYPE() {
        return AMENDMENT_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSINSURANCE_DEAL_DET.AMENDMENT_TYPE
     *
     * @param AMENDMENT_TYPE the value for TRSINSURANCE_DEAL_DET.AMENDMENT_TYPE
     */
    public void setAMENDMENT_TYPE(String AMENDMENT_TYPE) {
        this.AMENDMENT_TYPE = AMENDMENT_TYPE == null ? null : AMENDMENT_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSINSURANCE_DEAL_DET.LAST_ACCRUED_DATE
     *
     * @return the value of TRSINSURANCE_DEAL_DET.LAST_ACCRUED_DATE
     */
    public Date getLAST_ACCRUED_DATE() {
        return LAST_ACCRUED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSINSURANCE_DEAL_DET.LAST_ACCRUED_DATE
     *
     * @param LAST_ACCRUED_DATE the value for TRSINSURANCE_DEAL_DET.LAST_ACCRUED_DATE
     */
    public void setLAST_ACCRUED_DATE(Date LAST_ACCRUED_DATE) {
        this.LAST_ACCRUED_DATE = LAST_ACCRUED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSINSURANCE_DEAL_DET.ACCRUED_AMOUNT
     *
     * @return the value of TRSINSURANCE_DEAL_DET.ACCRUED_AMOUNT
     */
    public BigDecimal getACCRUED_AMOUNT() {
        return ACCRUED_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSINSURANCE_DEAL_DET.ACCRUED_AMOUNT
     *
     * @param ACCRUED_AMOUNT the value for TRSINSURANCE_DEAL_DET.ACCRUED_AMOUNT
     */
    public void setACCRUED_AMOUNT(BigDecimal ACCRUED_AMOUNT) {
        this.ACCRUED_AMOUNT = ACCRUED_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSINSURANCE_DEAL_DET.AMOUNT_AMENDED
     *
     * @return the value of TRSINSURANCE_DEAL_DET.AMOUNT_AMENDED
     */
    public BigDecimal getAMOUNT_AMENDED() {
        return AMOUNT_AMENDED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSINSURANCE_DEAL_DET.AMOUNT_AMENDED
     *
     * @param AMOUNT_AMENDED the value for TRSINSURANCE_DEAL_DET.AMOUNT_AMENDED
     */
    public void setAMOUNT_AMENDED(BigDecimal AMOUNT_AMENDED) {
        this.AMOUNT_AMENDED = AMOUNT_AMENDED;
    }
}