package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class TRSINSURANCE_COMPANIES_DETVOKey extends BaseVO {
    /**
     * This field corresponds to the database column TRSINSURANCE_COMPANIES_DET.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column TRSINSURANCE_COMPANIES_DET.INSURANCE_CODE
     */
    private BigDecimal INSURANCE_CODE;

    /**
     * This field corresponds to the database column TRSINSURANCE_COMPANIES_DET.INSURANCE_TYPE
     */
    private BigDecimal INSURANCE_TYPE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSINSURANCE_COMPANIES_DET.COMP_CODE
     *
     * @return the value of TRSINSURANCE_COMPANIES_DET.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSINSURANCE_COMPANIES_DET.COMP_CODE
     *
     * @param COMP_CODE the value for TRSINSURANCE_COMPANIES_DET.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSINSURANCE_COMPANIES_DET.INSURANCE_CODE
     *
     * @return the value of TRSINSURANCE_COMPANIES_DET.INSURANCE_CODE
     */
    public BigDecimal getINSURANCE_CODE() {
        return INSURANCE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSINSURANCE_COMPANIES_DET.INSURANCE_CODE
     *
     * @param INSURANCE_CODE the value for TRSINSURANCE_COMPANIES_DET.INSURANCE_CODE
     */
    public void setINSURANCE_CODE(BigDecimal INSURANCE_CODE) {
        this.INSURANCE_CODE = INSURANCE_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSINSURANCE_COMPANIES_DET.INSURANCE_TYPE
     *
     * @return the value of TRSINSURANCE_COMPANIES_DET.INSURANCE_TYPE
     */
    public BigDecimal getINSURANCE_TYPE() {
        return INSURANCE_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSINSURANCE_COMPANIES_DET.INSURANCE_TYPE
     *
     * @param INSURANCE_TYPE the value for TRSINSURANCE_COMPANIES_DET.INSURANCE_TYPE
     */
    public void setINSURANCE_TYPE(BigDecimal INSURANCE_TYPE) {
        this.INSURANCE_TYPE = INSURANCE_TYPE;
    }
}