package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class TRSOBLIGORLIMITDETVO extends TRSOBLIGORLIMITDETVOKey {
    /**
     * This field corresponds to the database column TRSOBLIGORLIMITDET.TO_DATE
     */
    private Date TO_DATE;

    /**
     * This field corresponds to the database column TRSOBLIGORLIMITDET.GLOBAL_LIMIT
     */
    private BigDecimal GLOBAL_LIMIT;

    /**
     * This field corresponds to the database column TRSOBLIGORLIMITDET.LIMIT_COMPANY
     */
    private BigDecimal LIMIT_COMPANY;

    /**
     * This field corresponds to the database column TRSOBLIGORLIMITDET.LIMIT_CLIENTS
     */
    private BigDecimal LIMIT_CLIENTS;

    /**
     * This field corresponds to the database column TRSOBLIGORLIMITDET.ENABLE_SWAP
     */
    private BigDecimal ENABLE_SWAP;

    /**
     * This field corresponds to the database column TRSOBLIGORLIMITDET.RISK_RATIO
     */
    private BigDecimal RISK_RATIO;

    /**
     * This field corresponds to the database column TRSOBLIGORLIMITDET.GLOBAL_LIMIT_UTILIZED
     */
    private BigDecimal GLOBAL_LIMIT_UTILIZED;

    /**
     * This field corresponds to the database column TRSOBLIGORLIMITDET.DATE_UPDATED
     */
    private Date DATE_UPDATED;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSOBLIGORLIMITDET.TO_DATE
     *
     * @return the value of TRSOBLIGORLIMITDET.TO_DATE
     */
    public Date getTO_DATE() {
        return TO_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSOBLIGORLIMITDET.TO_DATE
     *
     * @param TO_DATE the value for TRSOBLIGORLIMITDET.TO_DATE
     */
    public void setTO_DATE(Date TO_DATE) {
        this.TO_DATE = TO_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSOBLIGORLIMITDET.GLOBAL_LIMIT
     *
     * @return the value of TRSOBLIGORLIMITDET.GLOBAL_LIMIT
     */
    public BigDecimal getGLOBAL_LIMIT() {
        return GLOBAL_LIMIT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSOBLIGORLIMITDET.GLOBAL_LIMIT
     *
     * @param GLOBAL_LIMIT the value for TRSOBLIGORLIMITDET.GLOBAL_LIMIT
     */
    public void setGLOBAL_LIMIT(BigDecimal GLOBAL_LIMIT) {
        this.GLOBAL_LIMIT = GLOBAL_LIMIT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSOBLIGORLIMITDET.LIMIT_COMPANY
     *
     * @return the value of TRSOBLIGORLIMITDET.LIMIT_COMPANY
     */
    public BigDecimal getLIMIT_COMPANY() {
        return LIMIT_COMPANY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSOBLIGORLIMITDET.LIMIT_COMPANY
     *
     * @param LIMIT_COMPANY the value for TRSOBLIGORLIMITDET.LIMIT_COMPANY
     */
    public void setLIMIT_COMPANY(BigDecimal LIMIT_COMPANY) {
        this.LIMIT_COMPANY = LIMIT_COMPANY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSOBLIGORLIMITDET.LIMIT_CLIENTS
     *
     * @return the value of TRSOBLIGORLIMITDET.LIMIT_CLIENTS
     */
    public BigDecimal getLIMIT_CLIENTS() {
        return LIMIT_CLIENTS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSOBLIGORLIMITDET.LIMIT_CLIENTS
     *
     * @param LIMIT_CLIENTS the value for TRSOBLIGORLIMITDET.LIMIT_CLIENTS
     */
    public void setLIMIT_CLIENTS(BigDecimal LIMIT_CLIENTS) {
        this.LIMIT_CLIENTS = LIMIT_CLIENTS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSOBLIGORLIMITDET.ENABLE_SWAP
     *
     * @return the value of TRSOBLIGORLIMITDET.ENABLE_SWAP
     */
    public BigDecimal getENABLE_SWAP() {
        return ENABLE_SWAP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSOBLIGORLIMITDET.ENABLE_SWAP
     *
     * @param ENABLE_SWAP the value for TRSOBLIGORLIMITDET.ENABLE_SWAP
     */
    public void setENABLE_SWAP(BigDecimal ENABLE_SWAP) {
        this.ENABLE_SWAP = ENABLE_SWAP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSOBLIGORLIMITDET.RISK_RATIO
     *
     * @return the value of TRSOBLIGORLIMITDET.RISK_RATIO
     */
    public BigDecimal getRISK_RATIO() {
        return RISK_RATIO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSOBLIGORLIMITDET.RISK_RATIO
     *
     * @param RISK_RATIO the value for TRSOBLIGORLIMITDET.RISK_RATIO
     */
    public void setRISK_RATIO(BigDecimal RISK_RATIO) {
        this.RISK_RATIO = RISK_RATIO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSOBLIGORLIMITDET.GLOBAL_LIMIT_UTILIZED
     *
     * @return the value of TRSOBLIGORLIMITDET.GLOBAL_LIMIT_UTILIZED
     */
    public BigDecimal getGLOBAL_LIMIT_UTILIZED() {
        return GLOBAL_LIMIT_UTILIZED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSOBLIGORLIMITDET.GLOBAL_LIMIT_UTILIZED
     *
     * @param GLOBAL_LIMIT_UTILIZED the value for TRSOBLIGORLIMITDET.GLOBAL_LIMIT_UTILIZED
     */
    public void setGLOBAL_LIMIT_UTILIZED(BigDecimal GLOBAL_LIMIT_UTILIZED) {
        this.GLOBAL_LIMIT_UTILIZED = GLOBAL_LIMIT_UTILIZED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSOBLIGORLIMITDET.DATE_UPDATED
     *
     * @return the value of TRSOBLIGORLIMITDET.DATE_UPDATED
     */
    public Date getDATE_UPDATED() {
        return DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSOBLIGORLIMITDET.DATE_UPDATED
     *
     * @param DATE_UPDATED the value for TRSOBLIGORLIMITDET.DATE_UPDATED
     */
    public void setDATE_UPDATED(Date DATE_UPDATED) {
        this.DATE_UPDATED = DATE_UPDATED;
    }
}