package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;
import java.util.Date;

public class TRSPAYPLANDET_CALC_PRINT_TMPVO extends BaseVO {
    /**
     * This field corresponds to the database column TRSPAYPLANDET_CALC_PRINT_TMP.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column TRSPAYPLANDET_CALC_PRINT_TMP.BRANCH
     */
    private BigDecimal BRANCH;

    /**
     * This field corresponds to the database column TRSPAYPLANDET_CALC_PRINT_TMP.SERIAL_NO
     */
    private BigDecimal SERIAL_NO;

    /**
     * This field corresponds to the database column TRSPAYPLANDET_CALC_PRINT_TMP.CIF_NO
     */
    private BigDecimal CIF_NO;

    /**
     * This field corresponds to the database column TRSPAYPLANDET_CALC_PRINT_TMP.COMMENCEMENT_DATE
     */
    private Date COMMENCEMENT_DATE;

    /**
     * This field corresponds to the database column TRSPAYPLANDET_CALC_PRINT_TMP.PLAN_NBR
     */
    private BigDecimal PLAN_NBR;

    /**
     * This field corresponds to the database column TRSPAYPLANDET_CALC_PRINT_TMP.PLAN_SEQ
     */
    private BigDecimal PLAN_SEQ;

    /**
     * This field corresponds to the database column TRSPAYPLANDET_CALC_PRINT_TMP.LINE_NBR
     */
    private BigDecimal LINE_NBR;

    /**
     * This field corresponds to the database column TRSPAYPLANDET_CALC_PRINT_TMP.VALUE_DATE
     */
    private Date VALUE_DATE;

    /**
     * This field corresponds to the database column TRSPAYPLANDET_CALC_PRINT_TMP.AMOUNT
     */
    private BigDecimal AMOUNT;

    /**
     * This field corresponds to the database column TRSPAYPLANDET_CALC_PRINT_TMP.TO_DATE
     */
    private Date TO_DATE;

    /**
     * This field corresponds to the database column TRSPAYPLANDET_CALC_PRINT_TMP.FROM_DATE
     */
    private Date FROM_DATE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPAYPLANDET_CALC_PRINT_TMP.COMP_CODE
     *
     * @return the value of TRSPAYPLANDET_CALC_PRINT_TMP.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPAYPLANDET_CALC_PRINT_TMP.COMP_CODE
     *
     * @param COMP_CODE the value for TRSPAYPLANDET_CALC_PRINT_TMP.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPAYPLANDET_CALC_PRINT_TMP.BRANCH
     *
     * @return the value of TRSPAYPLANDET_CALC_PRINT_TMP.BRANCH
     */
    public BigDecimal getBRANCH() {
        return BRANCH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPAYPLANDET_CALC_PRINT_TMP.BRANCH
     *
     * @param BRANCH the value for TRSPAYPLANDET_CALC_PRINT_TMP.BRANCH
     */
    public void setBRANCH(BigDecimal BRANCH) {
        this.BRANCH = BRANCH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPAYPLANDET_CALC_PRINT_TMP.SERIAL_NO
     *
     * @return the value of TRSPAYPLANDET_CALC_PRINT_TMP.SERIAL_NO
     */
    public BigDecimal getSERIAL_NO() {
        return SERIAL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPAYPLANDET_CALC_PRINT_TMP.SERIAL_NO
     *
     * @param SERIAL_NO the value for TRSPAYPLANDET_CALC_PRINT_TMP.SERIAL_NO
     */
    public void setSERIAL_NO(BigDecimal SERIAL_NO) {
        this.SERIAL_NO = SERIAL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPAYPLANDET_CALC_PRINT_TMP.CIF_NO
     *
     * @return the value of TRSPAYPLANDET_CALC_PRINT_TMP.CIF_NO
     */
    public BigDecimal getCIF_NO() {
        return CIF_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPAYPLANDET_CALC_PRINT_TMP.CIF_NO
     *
     * @param CIF_NO the value for TRSPAYPLANDET_CALC_PRINT_TMP.CIF_NO
     */
    public void setCIF_NO(BigDecimal CIF_NO) {
        this.CIF_NO = CIF_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPAYPLANDET_CALC_PRINT_TMP.COMMENCEMENT_DATE
     *
     * @return the value of TRSPAYPLANDET_CALC_PRINT_TMP.COMMENCEMENT_DATE
     */
    public Date getCOMMENCEMENT_DATE() {
        return COMMENCEMENT_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPAYPLANDET_CALC_PRINT_TMP.COMMENCEMENT_DATE
     *
     * @param COMMENCEMENT_DATE the value for TRSPAYPLANDET_CALC_PRINT_TMP.COMMENCEMENT_DATE
     */
    public void setCOMMENCEMENT_DATE(Date COMMENCEMENT_DATE) {
        this.COMMENCEMENT_DATE = COMMENCEMENT_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPAYPLANDET_CALC_PRINT_TMP.PLAN_NBR
     *
     * @return the value of TRSPAYPLANDET_CALC_PRINT_TMP.PLAN_NBR
     */
    public BigDecimal getPLAN_NBR() {
        return PLAN_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPAYPLANDET_CALC_PRINT_TMP.PLAN_NBR
     *
     * @param PLAN_NBR the value for TRSPAYPLANDET_CALC_PRINT_TMP.PLAN_NBR
     */
    public void setPLAN_NBR(BigDecimal PLAN_NBR) {
        this.PLAN_NBR = PLAN_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPAYPLANDET_CALC_PRINT_TMP.PLAN_SEQ
     *
     * @return the value of TRSPAYPLANDET_CALC_PRINT_TMP.PLAN_SEQ
     */
    public BigDecimal getPLAN_SEQ() {
        return PLAN_SEQ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPAYPLANDET_CALC_PRINT_TMP.PLAN_SEQ
     *
     * @param PLAN_SEQ the value for TRSPAYPLANDET_CALC_PRINT_TMP.PLAN_SEQ
     */
    public void setPLAN_SEQ(BigDecimal PLAN_SEQ) {
        this.PLAN_SEQ = PLAN_SEQ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPAYPLANDET_CALC_PRINT_TMP.LINE_NBR
     *
     * @return the value of TRSPAYPLANDET_CALC_PRINT_TMP.LINE_NBR
     */
    public BigDecimal getLINE_NBR() {
        return LINE_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPAYPLANDET_CALC_PRINT_TMP.LINE_NBR
     *
     * @param LINE_NBR the value for TRSPAYPLANDET_CALC_PRINT_TMP.LINE_NBR
     */
    public void setLINE_NBR(BigDecimal LINE_NBR) {
        this.LINE_NBR = LINE_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPAYPLANDET_CALC_PRINT_TMP.VALUE_DATE
     *
     * @return the value of TRSPAYPLANDET_CALC_PRINT_TMP.VALUE_DATE
     */
    public Date getVALUE_DATE() {
        return VALUE_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPAYPLANDET_CALC_PRINT_TMP.VALUE_DATE
     *
     * @param VALUE_DATE the value for TRSPAYPLANDET_CALC_PRINT_TMP.VALUE_DATE
     */
    public void setVALUE_DATE(Date VALUE_DATE) {
        this.VALUE_DATE = VALUE_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPAYPLANDET_CALC_PRINT_TMP.AMOUNT
     *
     * @return the value of TRSPAYPLANDET_CALC_PRINT_TMP.AMOUNT
     */
    public BigDecimal getAMOUNT() {
        return AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPAYPLANDET_CALC_PRINT_TMP.AMOUNT
     *
     * @param AMOUNT the value for TRSPAYPLANDET_CALC_PRINT_TMP.AMOUNT
     */
    public void setAMOUNT(BigDecimal AMOUNT) {
        this.AMOUNT = AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPAYPLANDET_CALC_PRINT_TMP.TO_DATE
     *
     * @return the value of TRSPAYPLANDET_CALC_PRINT_TMP.TO_DATE
     */
    public Date getTO_DATE() {
        return TO_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPAYPLANDET_CALC_PRINT_TMP.TO_DATE
     *
     * @param TO_DATE the value for TRSPAYPLANDET_CALC_PRINT_TMP.TO_DATE
     */
    public void setTO_DATE(Date TO_DATE) {
        this.TO_DATE = TO_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPAYPLANDET_CALC_PRINT_TMP.FROM_DATE
     *
     * @return the value of TRSPAYPLANDET_CALC_PRINT_TMP.FROM_DATE
     */
    public Date getFROM_DATE() {
        return FROM_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPAYPLANDET_CALC_PRINT_TMP.FROM_DATE
     *
     * @param FROM_DATE the value for TRSPAYPLANDET_CALC_PRINT_TMP.FROM_DATE
     */
    public void setFROM_DATE(Date FROM_DATE) {
        this.FROM_DATE = FROM_DATE;
    }
}