package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class TRSPAYPLANDET_TEMPVOKey extends BaseVO {
    /**
     * This field corresponds to the database column TRSPAYPLANDET_TEMP.BRANCH
     */
    private BigDecimal BRANCH;

    /**
     * This field corresponds to the database column TRSPAYPLANDET_TEMP.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column TRSPAYPLANDET_TEMP.LINE_NBR
     */
    private BigDecimal LINE_NBR;

    /**
     * This field corresponds to the database column TRSPAYPLANDET_TEMP.PLAN_NBR
     */
    private BigDecimal PLAN_NBR;

    /**
     * This field corresponds to the database column TRSPAYPLANDET_TEMP.PLAN_SEQ
     */
    private BigDecimal PLAN_SEQ;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPAYPLANDET_TEMP.BRANCH
     *
     * @return the value of TRSPAYPLANDET_TEMP.BRANCH
     */
    public BigDecimal getBRANCH() {
        return BRANCH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPAYPLANDET_TEMP.BRANCH
     *
     * @param BRANCH the value for TRSPAYPLANDET_TEMP.BRANCH
     */
    public void setBRANCH(BigDecimal BRANCH) {
        this.BRANCH = BRANCH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPAYPLANDET_TEMP.COMP_CODE
     *
     * @return the value of TRSPAYPLANDET_TEMP.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPAYPLANDET_TEMP.COMP_CODE
     *
     * @param COMP_CODE the value for TRSPAYPLANDET_TEMP.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPAYPLANDET_TEMP.LINE_NBR
     *
     * @return the value of TRSPAYPLANDET_TEMP.LINE_NBR
     */
    public BigDecimal getLINE_NBR() {
        return LINE_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPAYPLANDET_TEMP.LINE_NBR
     *
     * @param LINE_NBR the value for TRSPAYPLANDET_TEMP.LINE_NBR
     */
    public void setLINE_NBR(BigDecimal LINE_NBR) {
        this.LINE_NBR = LINE_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPAYPLANDET_TEMP.PLAN_NBR
     *
     * @return the value of TRSPAYPLANDET_TEMP.PLAN_NBR
     */
    public BigDecimal getPLAN_NBR() {
        return PLAN_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPAYPLANDET_TEMP.PLAN_NBR
     *
     * @param PLAN_NBR the value for TRSPAYPLANDET_TEMP.PLAN_NBR
     */
    public void setPLAN_NBR(BigDecimal PLAN_NBR) {
        this.PLAN_NBR = PLAN_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPAYPLANDET_TEMP.PLAN_SEQ
     *
     * @return the value of TRSPAYPLANDET_TEMP.PLAN_SEQ
     */
    public BigDecimal getPLAN_SEQ() {
        return PLAN_SEQ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPAYPLANDET_TEMP.PLAN_SEQ
     *
     * @param PLAN_SEQ the value for TRSPAYPLANDET_TEMP.PLAN_SEQ
     */
    public void setPLAN_SEQ(BigDecimal PLAN_SEQ) {
        this.PLAN_SEQ = PLAN_SEQ;
    }
}