package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class TRSPAYPLAN_NIDC_DET_CALCVO extends TRSPAYPLAN_NIDC_DET_CALCVOKey {
    /**
     * This field corresponds to the database column TRSPAYPLAN_NIDC_DET_CALC.CERTIFICATE_NO
     */
    private BigDecimal CERTIFICATE_NO;

    /**
     * This field corresponds to the database column TRSPAYPLAN_NIDC_DET_CALC.TENOR_PERIODICITY_NBR
     */
    private BigDecimal TENOR_PERIODICITY_NBR;

    /**
     * This field corresponds to the database column TRSPAYPLAN_NIDC_DET_CALC.TENOR_PERIODICITY_TYPE
     */
    private String TENOR_PERIODICITY_TYPE;

    /**
     * This field corresponds to the database column TRSPAYPLAN_NIDC_DET_CALC.NOMINAL_AMOUNT
     */
    private BigDecimal NOMINAL_AMOUNT;

    /**
     * This field corresponds to the database column TRSPAYPLAN_NIDC_DET_CALC.PROFIT_RATE
     */
    private BigDecimal PROFIT_RATE;

    /**
     * This field corresponds to the database column TRSPAYPLAN_NIDC_DET_CALC.PRICE
     */
    private BigDecimal PRICE;

    /**
     * This field corresponds to the database column TRSPAYPLAN_NIDC_DET_CALC.PROCEED_AMOUNT
     */
    private BigDecimal PROCEED_AMOUNT;

    /**
     * This field corresponds to the database column TRSPAYPLAN_NIDC_DET_CALC.EXPENSES
     */
    private BigDecimal EXPENSES;

    /**
     * This field corresponds to the database column TRSPAYPLAN_NIDC_DET_CALC.NIDC_HOLDER_CIF
     */
    private BigDecimal NIDC_HOLDER_CIF;

    /**
     * This field corresponds to the database column TRSPAYPLAN_NIDC_DET_CALC.SETTLED_YN
     */
    private String SETTLED_YN;

    /**
     * This field corresponds to the database column TRSPAYPLAN_NIDC_DET_CALC.ACCRUED_PROFIT
     */
    private BigDecimal ACCRUED_PROFIT;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPAYPLAN_NIDC_DET_CALC.CERTIFICATE_NO
     *
     * @return the value of TRSPAYPLAN_NIDC_DET_CALC.CERTIFICATE_NO
     */
    public BigDecimal getCERTIFICATE_NO() {
        return CERTIFICATE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPAYPLAN_NIDC_DET_CALC.CERTIFICATE_NO
     *
     * @param CERTIFICATE_NO the value for TRSPAYPLAN_NIDC_DET_CALC.CERTIFICATE_NO
     */
    public void setCERTIFICATE_NO(BigDecimal CERTIFICATE_NO) {
        this.CERTIFICATE_NO = CERTIFICATE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPAYPLAN_NIDC_DET_CALC.TENOR_PERIODICITY_NBR
     *
     * @return the value of TRSPAYPLAN_NIDC_DET_CALC.TENOR_PERIODICITY_NBR
     */
    public BigDecimal getTENOR_PERIODICITY_NBR() {
        return TENOR_PERIODICITY_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPAYPLAN_NIDC_DET_CALC.TENOR_PERIODICITY_NBR
     *
     * @param TENOR_PERIODICITY_NBR the value for TRSPAYPLAN_NIDC_DET_CALC.TENOR_PERIODICITY_NBR
     */
    public void setTENOR_PERIODICITY_NBR(BigDecimal TENOR_PERIODICITY_NBR) {
        this.TENOR_PERIODICITY_NBR = TENOR_PERIODICITY_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPAYPLAN_NIDC_DET_CALC.TENOR_PERIODICITY_TYPE
     *
     * @return the value of TRSPAYPLAN_NIDC_DET_CALC.TENOR_PERIODICITY_TYPE
     */
    public String getTENOR_PERIODICITY_TYPE() {
        return TENOR_PERIODICITY_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPAYPLAN_NIDC_DET_CALC.TENOR_PERIODICITY_TYPE
     *
     * @param TENOR_PERIODICITY_TYPE the value for TRSPAYPLAN_NIDC_DET_CALC.TENOR_PERIODICITY_TYPE
     */
    public void setTENOR_PERIODICITY_TYPE(String TENOR_PERIODICITY_TYPE) {
        this.TENOR_PERIODICITY_TYPE = TENOR_PERIODICITY_TYPE == null ? null : TENOR_PERIODICITY_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPAYPLAN_NIDC_DET_CALC.NOMINAL_AMOUNT
     *
     * @return the value of TRSPAYPLAN_NIDC_DET_CALC.NOMINAL_AMOUNT
     */
    public BigDecimal getNOMINAL_AMOUNT() {
        return NOMINAL_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPAYPLAN_NIDC_DET_CALC.NOMINAL_AMOUNT
     *
     * @param NOMINAL_AMOUNT the value for TRSPAYPLAN_NIDC_DET_CALC.NOMINAL_AMOUNT
     */
    public void setNOMINAL_AMOUNT(BigDecimal NOMINAL_AMOUNT) {
        this.NOMINAL_AMOUNT = NOMINAL_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPAYPLAN_NIDC_DET_CALC.PROFIT_RATE
     *
     * @return the value of TRSPAYPLAN_NIDC_DET_CALC.PROFIT_RATE
     */
    public BigDecimal getPROFIT_RATE() {
        return PROFIT_RATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPAYPLAN_NIDC_DET_CALC.PROFIT_RATE
     *
     * @param PROFIT_RATE the value for TRSPAYPLAN_NIDC_DET_CALC.PROFIT_RATE
     */
    public void setPROFIT_RATE(BigDecimal PROFIT_RATE) {
        this.PROFIT_RATE = PROFIT_RATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPAYPLAN_NIDC_DET_CALC.PRICE
     *
     * @return the value of TRSPAYPLAN_NIDC_DET_CALC.PRICE
     */
    public BigDecimal getPRICE() {
        return PRICE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPAYPLAN_NIDC_DET_CALC.PRICE
     *
     * @param PRICE the value for TRSPAYPLAN_NIDC_DET_CALC.PRICE
     */
    public void setPRICE(BigDecimal PRICE) {
        this.PRICE = PRICE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPAYPLAN_NIDC_DET_CALC.PROCEED_AMOUNT
     *
     * @return the value of TRSPAYPLAN_NIDC_DET_CALC.PROCEED_AMOUNT
     */
    public BigDecimal getPROCEED_AMOUNT() {
        return PROCEED_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPAYPLAN_NIDC_DET_CALC.PROCEED_AMOUNT
     *
     * @param PROCEED_AMOUNT the value for TRSPAYPLAN_NIDC_DET_CALC.PROCEED_AMOUNT
     */
    public void setPROCEED_AMOUNT(BigDecimal PROCEED_AMOUNT) {
        this.PROCEED_AMOUNT = PROCEED_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPAYPLAN_NIDC_DET_CALC.EXPENSES
     *
     * @return the value of TRSPAYPLAN_NIDC_DET_CALC.EXPENSES
     */
    public BigDecimal getEXPENSES() {
        return EXPENSES;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPAYPLAN_NIDC_DET_CALC.EXPENSES
     *
     * @param EXPENSES the value for TRSPAYPLAN_NIDC_DET_CALC.EXPENSES
     */
    public void setEXPENSES(BigDecimal EXPENSES) {
        this.EXPENSES = EXPENSES;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPAYPLAN_NIDC_DET_CALC.NIDC_HOLDER_CIF
     *
     * @return the value of TRSPAYPLAN_NIDC_DET_CALC.NIDC_HOLDER_CIF
     */
    public BigDecimal getNIDC_HOLDER_CIF() {
        return NIDC_HOLDER_CIF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPAYPLAN_NIDC_DET_CALC.NIDC_HOLDER_CIF
     *
     * @param NIDC_HOLDER_CIF the value for TRSPAYPLAN_NIDC_DET_CALC.NIDC_HOLDER_CIF
     */
    public void setNIDC_HOLDER_CIF(BigDecimal NIDC_HOLDER_CIF) {
        this.NIDC_HOLDER_CIF = NIDC_HOLDER_CIF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPAYPLAN_NIDC_DET_CALC.SETTLED_YN
     *
     * @return the value of TRSPAYPLAN_NIDC_DET_CALC.SETTLED_YN
     */
    public String getSETTLED_YN() {
        return SETTLED_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPAYPLAN_NIDC_DET_CALC.SETTLED_YN
     *
     * @param SETTLED_YN the value for TRSPAYPLAN_NIDC_DET_CALC.SETTLED_YN
     */
    public void setSETTLED_YN(String SETTLED_YN) {
        this.SETTLED_YN = SETTLED_YN == null ? null : SETTLED_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPAYPLAN_NIDC_DET_CALC.ACCRUED_PROFIT
     *
     * @return the value of TRSPAYPLAN_NIDC_DET_CALC.ACCRUED_PROFIT
     */
    public BigDecimal getACCRUED_PROFIT() {
        return ACCRUED_PROFIT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPAYPLAN_NIDC_DET_CALC.ACCRUED_PROFIT
     *
     * @param ACCRUED_PROFIT the value for TRSPAYPLAN_NIDC_DET_CALC.ACCRUED_PROFIT
     */
    public void setACCRUED_PROFIT(BigDecimal ACCRUED_PROFIT) {
        this.ACCRUED_PROFIT = ACCRUED_PROFIT;
    }
}