package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class TRSPENALTYDETVOKey extends BaseVO {
    /**
     * This field corresponds to the database column TRSPENALTYDET.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column TRSPENALTYDET.LINE_NO
     */
    private BigDecimal LINE_NO;

    /**
     * This field corresponds to the database column TRSPENALTYDET.PENALTY_CODE
     */
    private BigDecimal PENALTY_CODE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPENALTYDET.COMP_CODE
     *
     * @return the value of TRSPENALTYDET.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPENALTYDET.COMP_CODE
     *
     * @param COMP_CODE the value for TRSPENALTYDET.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPENALTYDET.LINE_NO
     *
     * @return the value of TRSPENALTYDET.LINE_NO
     */
    public BigDecimal getLINE_NO() {
        return LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPENALTYDET.LINE_NO
     *
     * @param LINE_NO the value for TRSPENALTYDET.LINE_NO
     */
    public void setLINE_NO(BigDecimal LINE_NO) {
        this.LINE_NO = LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPENALTYDET.PENALTY_CODE
     *
     * @return the value of TRSPENALTYDET.PENALTY_CODE
     */
    public BigDecimal getPENALTY_CODE() {
        return PENALTY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPENALTYDET.PENALTY_CODE
     *
     * @param PENALTY_CODE the value for TRSPENALTYDET.PENALTY_CODE
     */
    public void setPENALTY_CODE(BigDecimal PENALTY_CODE) {
        this.PENALTY_CODE = PENALTY_CODE;
    }
}