package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class TRSPENALTYVO extends TRSPENALTYVOKey {
    /**
     * This field corresponds to the database column TRSPENALTY.BRIEF_NAME_ENG
     */
    private String BRIEF_NAME_ENG;

    /**
     * This field corresponds to the database column TRSPENALTY.LONG_NAME_ENG
     */
    private String LONG_NAME_ENG;

    /**
     * This field corresponds to the database column TRSPENALTY.BRIEF_NAME_ARAB
     */
    private String BRIEF_NAME_ARAB;

    /**
     * This field corresponds to the database column TRSPENALTY.LONG_NAME_ARAB
     */
    private String LONG_NAME_ARAB;

    /**
     * This field corresponds to the database column TRSPENALTY.PENALTY_TYPE
     */
    private String PENALTY_TYPE;

    /**
     * This field corresponds to the database column TRSPENALTY.PENALTY_TYPE_AFTER_MATURITY
     */
    private String PENALTY_TYPE_AFTER_MATURITY;

    /**
     * This field corresponds to the database column TRSPENALTY.MINIMUM_AMOUNT
     */
    private BigDecimal MINIMUM_AMOUNT;

    /**
     * This field corresponds to the database column TRSPENALTY.CHARGES_CODE
     */
    private BigDecimal CHARGES_CODE;

    /**
     * This field corresponds to the database column TRSPENALTY.COLLECT_PENALTY_AT
     */
    private String COLLECT_PENALTY_AT;

    /**
     * This field corresponds to the database column TRSPENALTY.PERC_ACTL_PERIOD_AFT_MAT_YN
     */
    private String PERC_ACTL_PERIOD_AFT_MAT_YN;

    /**
     * This field corresponds to the database column TRSPENALTY.PENALTY_CALC_BASED_ON
     */
    private BigDecimal PENALTY_CALC_BASED_ON;

    /**
     * This field corresponds to the database column TRSPENALTY.PER_INSTANCE_AMOUNT
     */
    private BigDecimal PER_INSTANCE_AMOUNT;

    /**
     * This field corresponds to the database column TRSPENALTY.PER_INSTANCE_TYPE
     */
    private String PER_INSTANCE_TYPE;

    /**
     * This field corresponds to the database column TRSPENALTY.PER_INSTANCE_NUMBER
     */
    private BigDecimal PER_INSTANCE_NUMBER;

    /**
     * This field corresponds to the database column TRSPENALTY.CALC_PENLTY_FRM_DISB_VAL_DT_YN
     */
    private String CALC_PENLTY_FRM_DISB_VAL_DT_YN;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPENALTY.BRIEF_NAME_ENG
     *
     * @return the value of TRSPENALTY.BRIEF_NAME_ENG
     */
    public String getBRIEF_NAME_ENG() {
        return BRIEF_NAME_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPENALTY.BRIEF_NAME_ENG
     *
     * @param BRIEF_NAME_ENG the value for TRSPENALTY.BRIEF_NAME_ENG
     */
    public void setBRIEF_NAME_ENG(String BRIEF_NAME_ENG) {
        this.BRIEF_NAME_ENG = BRIEF_NAME_ENG == null ? null : BRIEF_NAME_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPENALTY.LONG_NAME_ENG
     *
     * @return the value of TRSPENALTY.LONG_NAME_ENG
     */
    public String getLONG_NAME_ENG() {
        return LONG_NAME_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPENALTY.LONG_NAME_ENG
     *
     * @param LONG_NAME_ENG the value for TRSPENALTY.LONG_NAME_ENG
     */
    public void setLONG_NAME_ENG(String LONG_NAME_ENG) {
        this.LONG_NAME_ENG = LONG_NAME_ENG == null ? null : LONG_NAME_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPENALTY.BRIEF_NAME_ARAB
     *
     * @return the value of TRSPENALTY.BRIEF_NAME_ARAB
     */
    public String getBRIEF_NAME_ARAB() {
        return BRIEF_NAME_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPENALTY.BRIEF_NAME_ARAB
     *
     * @param BRIEF_NAME_ARAB the value for TRSPENALTY.BRIEF_NAME_ARAB
     */
    public void setBRIEF_NAME_ARAB(String BRIEF_NAME_ARAB) {
        this.BRIEF_NAME_ARAB = BRIEF_NAME_ARAB == null ? null : BRIEF_NAME_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPENALTY.LONG_NAME_ARAB
     *
     * @return the value of TRSPENALTY.LONG_NAME_ARAB
     */
    public String getLONG_NAME_ARAB() {
        return LONG_NAME_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPENALTY.LONG_NAME_ARAB
     *
     * @param LONG_NAME_ARAB the value for TRSPENALTY.LONG_NAME_ARAB
     */
    public void setLONG_NAME_ARAB(String LONG_NAME_ARAB) {
        this.LONG_NAME_ARAB = LONG_NAME_ARAB == null ? null : LONG_NAME_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPENALTY.PENALTY_TYPE
     *
     * @return the value of TRSPENALTY.PENALTY_TYPE
     */
    public String getPENALTY_TYPE() {
        return PENALTY_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPENALTY.PENALTY_TYPE
     *
     * @param PENALTY_TYPE the value for TRSPENALTY.PENALTY_TYPE
     */
    public void setPENALTY_TYPE(String PENALTY_TYPE) {
        this.PENALTY_TYPE = PENALTY_TYPE == null ? null : PENALTY_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPENALTY.PENALTY_TYPE_AFTER_MATURITY
     *
     * @return the value of TRSPENALTY.PENALTY_TYPE_AFTER_MATURITY
     */
    public String getPENALTY_TYPE_AFTER_MATURITY() {
        return PENALTY_TYPE_AFTER_MATURITY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPENALTY.PENALTY_TYPE_AFTER_MATURITY
     *
     * @param PENALTY_TYPE_AFTER_MATURITY the value for TRSPENALTY.PENALTY_TYPE_AFTER_MATURITY
     */
    public void setPENALTY_TYPE_AFTER_MATURITY(String PENALTY_TYPE_AFTER_MATURITY) {
        this.PENALTY_TYPE_AFTER_MATURITY = PENALTY_TYPE_AFTER_MATURITY == null ? null : PENALTY_TYPE_AFTER_MATURITY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPENALTY.MINIMUM_AMOUNT
     *
     * @return the value of TRSPENALTY.MINIMUM_AMOUNT
     */
    public BigDecimal getMINIMUM_AMOUNT() {
        return MINIMUM_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPENALTY.MINIMUM_AMOUNT
     *
     * @param MINIMUM_AMOUNT the value for TRSPENALTY.MINIMUM_AMOUNT
     */
    public void setMINIMUM_AMOUNT(BigDecimal MINIMUM_AMOUNT) {
        this.MINIMUM_AMOUNT = MINIMUM_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPENALTY.CHARGES_CODE
     *
     * @return the value of TRSPENALTY.CHARGES_CODE
     */
    public BigDecimal getCHARGES_CODE() {
        return CHARGES_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPENALTY.CHARGES_CODE
     *
     * @param CHARGES_CODE the value for TRSPENALTY.CHARGES_CODE
     */
    public void setCHARGES_CODE(BigDecimal CHARGES_CODE) {
        this.CHARGES_CODE = CHARGES_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPENALTY.COLLECT_PENALTY_AT
     *
     * @return the value of TRSPENALTY.COLLECT_PENALTY_AT
     */
    public String getCOLLECT_PENALTY_AT() {
        return COLLECT_PENALTY_AT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPENALTY.COLLECT_PENALTY_AT
     *
     * @param COLLECT_PENALTY_AT the value for TRSPENALTY.COLLECT_PENALTY_AT
     */
    public void setCOLLECT_PENALTY_AT(String COLLECT_PENALTY_AT) {
        this.COLLECT_PENALTY_AT = COLLECT_PENALTY_AT == null ? null : COLLECT_PENALTY_AT.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPENALTY.PERC_ACTL_PERIOD_AFT_MAT_YN
     *
     * @return the value of TRSPENALTY.PERC_ACTL_PERIOD_AFT_MAT_YN
     */
    public String getPERC_ACTL_PERIOD_AFT_MAT_YN() {
        return PERC_ACTL_PERIOD_AFT_MAT_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPENALTY.PERC_ACTL_PERIOD_AFT_MAT_YN
     *
     * @param PERC_ACTL_PERIOD_AFT_MAT_YN the value for TRSPENALTY.PERC_ACTL_PERIOD_AFT_MAT_YN
     */
    public void setPERC_ACTL_PERIOD_AFT_MAT_YN(String PERC_ACTL_PERIOD_AFT_MAT_YN) {
        this.PERC_ACTL_PERIOD_AFT_MAT_YN = PERC_ACTL_PERIOD_AFT_MAT_YN == null ? null : PERC_ACTL_PERIOD_AFT_MAT_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPENALTY.PENALTY_CALC_BASED_ON
     *
     * @return the value of TRSPENALTY.PENALTY_CALC_BASED_ON
     */
    public BigDecimal getPENALTY_CALC_BASED_ON() {
        return PENALTY_CALC_BASED_ON;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPENALTY.PENALTY_CALC_BASED_ON
     *
     * @param PENALTY_CALC_BASED_ON the value for TRSPENALTY.PENALTY_CALC_BASED_ON
     */
    public void setPENALTY_CALC_BASED_ON(BigDecimal PENALTY_CALC_BASED_ON) {
        this.PENALTY_CALC_BASED_ON = PENALTY_CALC_BASED_ON;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPENALTY.PER_INSTANCE_AMOUNT
     *
     * @return the value of TRSPENALTY.PER_INSTANCE_AMOUNT
     */
    public BigDecimal getPER_INSTANCE_AMOUNT() {
        return PER_INSTANCE_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPENALTY.PER_INSTANCE_AMOUNT
     *
     * @param PER_INSTANCE_AMOUNT the value for TRSPENALTY.PER_INSTANCE_AMOUNT
     */
    public void setPER_INSTANCE_AMOUNT(BigDecimal PER_INSTANCE_AMOUNT) {
        this.PER_INSTANCE_AMOUNT = PER_INSTANCE_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPENALTY.PER_INSTANCE_TYPE
     *
     * @return the value of TRSPENALTY.PER_INSTANCE_TYPE
     */
    public String getPER_INSTANCE_TYPE() {
        return PER_INSTANCE_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPENALTY.PER_INSTANCE_TYPE
     *
     * @param PER_INSTANCE_TYPE the value for TRSPENALTY.PER_INSTANCE_TYPE
     */
    public void setPER_INSTANCE_TYPE(String PER_INSTANCE_TYPE) {
        this.PER_INSTANCE_TYPE = PER_INSTANCE_TYPE == null ? null : PER_INSTANCE_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPENALTY.PER_INSTANCE_NUMBER
     *
     * @return the value of TRSPENALTY.PER_INSTANCE_NUMBER
     */
    public BigDecimal getPER_INSTANCE_NUMBER() {
        return PER_INSTANCE_NUMBER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPENALTY.PER_INSTANCE_NUMBER
     *
     * @param PER_INSTANCE_NUMBER the value for TRSPENALTY.PER_INSTANCE_NUMBER
     */
    public void setPER_INSTANCE_NUMBER(BigDecimal PER_INSTANCE_NUMBER) {
        this.PER_INSTANCE_NUMBER = PER_INSTANCE_NUMBER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPENALTY.CALC_PENLTY_FRM_DISB_VAL_DT_YN
     *
     * @return the value of TRSPENALTY.CALC_PENLTY_FRM_DISB_VAL_DT_YN
     */
    public String getCALC_PENLTY_FRM_DISB_VAL_DT_YN() {
        return CALC_PENLTY_FRM_DISB_VAL_DT_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPENALTY.CALC_PENLTY_FRM_DISB_VAL_DT_YN
     *
     * @param CALC_PENLTY_FRM_DISB_VAL_DT_YN the value for TRSPENALTY.CALC_PENLTY_FRM_DISB_VAL_DT_YN
     */
    public void setCALC_PENLTY_FRM_DISB_VAL_DT_YN(String CALC_PENLTY_FRM_DISB_VAL_DT_YN) {
        this.CALC_PENLTY_FRM_DISB_VAL_DT_YN = CALC_PENLTY_FRM_DISB_VAL_DT_YN == null ? null : CALC_PENLTY_FRM_DISB_VAL_DT_YN.trim();
    }
}