package com.path.dbmaps.vo;

import java.util.Date;

public class TRSPAYPLAN_NIDC_COUPON_PYMVO extends TRSPAYPLAN_NIDC_COUPON_PYMVOKey {
    /**
     * This field corresponds to the database column TRSPAYPLAN_NIDC_COUPON_PYM.COUPON_PAYMENT_DATE
     */
    private Date COUPON_PAYMENT_DATE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPAYPLAN_NIDC_COUPON_PYM.COUPON_PAYMENT_DATE
     *
     * @return the value of TRSPAYPLAN_NIDC_COUPON_PYM.COUPON_PAYMENT_DATE
     */
    public Date getCOUPON_PAYMENT_DATE() {
        return COUPON_PAYMENT_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPAYPLAN_NIDC_COUPON_PYM.COUPON_PAYMENT_DATE
     *
     * @param COUPON_PAYMENT_DATE the value for TRSPAYPLAN_NIDC_COUPON_PYM.COUPON_PAYMENT_DATE
     */
    public void setCOUPON_PAYMENT_DATE(Date COUPON_PAYMENT_DATE) {
        this.COUPON_PAYMENT_DATE = COUPON_PAYMENT_DATE;
    }
}