package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class TRSPROFITDETVOKey extends BaseVO {
    /**
     * This field corresponds to the database column TRSPROFITDET.BRANCH
     */
    private BigDecimal BRANCH;

    /**
     * This field corresponds to the database column TRSPROFITDET.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column TRSPROFITDET.LINE_NBR
     */
    private BigDecimal LINE_NBR;

    /**
     * This field corresponds to the database column TRSPROFITDET.PROFIT_NBR
     */
    private BigDecimal PROFIT_NBR;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPROFITDET.BRANCH
     *
     * @return the value of TRSPROFITDET.BRANCH
     */
    public BigDecimal getBRANCH() {
        return BRANCH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPROFITDET.BRANCH
     *
     * @param BRANCH the value for TRSPROFITDET.BRANCH
     */
    public void setBRANCH(BigDecimal BRANCH) {
        this.BRANCH = BRANCH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPROFITDET.COMP_CODE
     *
     * @return the value of TRSPROFITDET.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPROFITDET.COMP_CODE
     *
     * @param COMP_CODE the value for TRSPROFITDET.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPROFITDET.LINE_NBR
     *
     * @return the value of TRSPROFITDET.LINE_NBR
     */
    public BigDecimal getLINE_NBR() {
        return LINE_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPROFITDET.LINE_NBR
     *
     * @param LINE_NBR the value for TRSPROFITDET.LINE_NBR
     */
    public void setLINE_NBR(BigDecimal LINE_NBR) {
        this.LINE_NBR = LINE_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPROFITDET.PROFIT_NBR
     *
     * @return the value of TRSPROFITDET.PROFIT_NBR
     */
    public BigDecimal getPROFIT_NBR() {
        return PROFIT_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPROFITDET.PROFIT_NBR
     *
     * @param PROFIT_NBR the value for TRSPROFITDET.PROFIT_NBR
     */
    public void setPROFIT_NBR(BigDecimal PROFIT_NBR) {
        this.PROFIT_NBR = PROFIT_NBR;
    }
}