package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class TRSPAYPLAN_CALCULATORVOKey extends BaseVO {
    /**
     * This field corresponds to the database column TRSPAYPLAN_CALCULATOR.BRANCH
     */
    private BigDecimal BRANCH;

    /**
     * This field corresponds to the database column TRSPAYPLAN_CALCULATOR.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column TRSPAYPLAN_CALCULATOR.REF_NBR
     */
    private BigDecimal REF_NBR;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPAYPLAN_CALCULATOR.BRANCH
     *
     * @return the value of TRSPAYPLAN_CALCULATOR.BRANCH
     */
    public BigDecimal getBRANCH() {
        return BRANCH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPAYPLAN_CALCULATOR.BRANCH
     *
     * @param BRANCH the value for TRSPAYPLAN_CALCULATOR.BRANCH
     */
    public void setBRANCH(BigDecimal BRANCH) {
        this.BRANCH = BRANCH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPAYPLAN_CALCULATOR.COMP_CODE
     *
     * @return the value of TRSPAYPLAN_CALCULATOR.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPAYPLAN_CALCULATOR.COMP_CODE
     *
     * @param COMP_CODE the value for TRSPAYPLAN_CALCULATOR.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPAYPLAN_CALCULATOR.REF_NBR
     *
     * @return the value of TRSPAYPLAN_CALCULATOR.REF_NBR
     */
    public BigDecimal getREF_NBR() {
        return REF_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPAYPLAN_CALCULATOR.REF_NBR
     *
     * @param REF_NBR the value for TRSPAYPLAN_CALCULATOR.REF_NBR
     */
    public void setREF_NBR(BigDecimal REF_NBR) {
        this.REF_NBR = REF_NBR;
    }
}