package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class TRSPRODUCT_TYPEVO extends TRSPRODUCT_TYPEVOKey {
    /**
     * This field corresponds to the database column TRSPRODUCT_TYPE.BRIEF_DESC_ENG
     */
    private String BRIEF_DESC_ENG;

    /**
     * This field corresponds to the database column TRSPRODUCT_TYPE.BRIEF_DESC_ARAB
     */
    private String BRIEF_DESC_ARAB;

    /**
     * This field corresponds to the database column TRSPRODUCT_TYPE.LONG_DESC_ENG
     */
    private String LONG_DESC_ENG;

    /**
     * This field corresponds to the database column TRSPRODUCT_TYPE.LONG_DESC_ARAB
     */
    private String LONG_DESC_ARAB;

    /**
     * This field corresponds to the database column TRSPRODUCT_TYPE.LIMIT_FACTOR
     */
    private BigDecimal LIMIT_FACTOR;

    /**
     * This field corresponds to the database column TRSPRODUCT_TYPE.FUNDED_DEAL
     */
    private String FUNDED_DEAL;

    /**
     * This field corresponds to the database column TRSPRODUCT_TYPE.LINK_TRADE_DEAL
     */
    private BigDecimal LINK_TRADE_DEAL;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPRODUCT_TYPE.BRIEF_DESC_ENG
     *
     * @return the value of TRSPRODUCT_TYPE.BRIEF_DESC_ENG
     */
    public String getBRIEF_DESC_ENG() {
        return BRIEF_DESC_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPRODUCT_TYPE.BRIEF_DESC_ENG
     *
     * @param BRIEF_DESC_ENG the value for TRSPRODUCT_TYPE.BRIEF_DESC_ENG
     */
    public void setBRIEF_DESC_ENG(String BRIEF_DESC_ENG) {
        this.BRIEF_DESC_ENG = BRIEF_DESC_ENG == null ? null : BRIEF_DESC_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPRODUCT_TYPE.BRIEF_DESC_ARAB
     *
     * @return the value of TRSPRODUCT_TYPE.BRIEF_DESC_ARAB
     */
    public String getBRIEF_DESC_ARAB() {
        return BRIEF_DESC_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPRODUCT_TYPE.BRIEF_DESC_ARAB
     *
     * @param BRIEF_DESC_ARAB the value for TRSPRODUCT_TYPE.BRIEF_DESC_ARAB
     */
    public void setBRIEF_DESC_ARAB(String BRIEF_DESC_ARAB) {
        this.BRIEF_DESC_ARAB = BRIEF_DESC_ARAB == null ? null : BRIEF_DESC_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPRODUCT_TYPE.LONG_DESC_ENG
     *
     * @return the value of TRSPRODUCT_TYPE.LONG_DESC_ENG
     */
    public String getLONG_DESC_ENG() {
        return LONG_DESC_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPRODUCT_TYPE.LONG_DESC_ENG
     *
     * @param LONG_DESC_ENG the value for TRSPRODUCT_TYPE.LONG_DESC_ENG
     */
    public void setLONG_DESC_ENG(String LONG_DESC_ENG) {
        this.LONG_DESC_ENG = LONG_DESC_ENG == null ? null : LONG_DESC_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPRODUCT_TYPE.LONG_DESC_ARAB
     *
     * @return the value of TRSPRODUCT_TYPE.LONG_DESC_ARAB
     */
    public String getLONG_DESC_ARAB() {
        return LONG_DESC_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPRODUCT_TYPE.LONG_DESC_ARAB
     *
     * @param LONG_DESC_ARAB the value for TRSPRODUCT_TYPE.LONG_DESC_ARAB
     */
    public void setLONG_DESC_ARAB(String LONG_DESC_ARAB) {
        this.LONG_DESC_ARAB = LONG_DESC_ARAB == null ? null : LONG_DESC_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPRODUCT_TYPE.LIMIT_FACTOR
     *
     * @return the value of TRSPRODUCT_TYPE.LIMIT_FACTOR
     */
    public BigDecimal getLIMIT_FACTOR() {
        return LIMIT_FACTOR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPRODUCT_TYPE.LIMIT_FACTOR
     *
     * @param LIMIT_FACTOR the value for TRSPRODUCT_TYPE.LIMIT_FACTOR
     */
    public void setLIMIT_FACTOR(BigDecimal LIMIT_FACTOR) {
        this.LIMIT_FACTOR = LIMIT_FACTOR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPRODUCT_TYPE.FUNDED_DEAL
     *
     * @return the value of TRSPRODUCT_TYPE.FUNDED_DEAL
     */
    public String getFUNDED_DEAL() {
        return FUNDED_DEAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPRODUCT_TYPE.FUNDED_DEAL
     *
     * @param FUNDED_DEAL the value for TRSPRODUCT_TYPE.FUNDED_DEAL
     */
    public void setFUNDED_DEAL(String FUNDED_DEAL) {
        this.FUNDED_DEAL = FUNDED_DEAL == null ? null : FUNDED_DEAL.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPRODUCT_TYPE.LINK_TRADE_DEAL
     *
     * @return the value of TRSPRODUCT_TYPE.LINK_TRADE_DEAL
     */
    public BigDecimal getLINK_TRADE_DEAL() {
        return LINK_TRADE_DEAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPRODUCT_TYPE.LINK_TRADE_DEAL
     *
     * @param LINK_TRADE_DEAL the value for TRSPRODUCT_TYPE.LINK_TRADE_DEAL
     */
    public void setLINK_TRADE_DEAL(BigDecimal LINK_TRADE_DEAL) {
        this.LINK_TRADE_DEAL = LINK_TRADE_DEAL;
    }
}