package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class TRSPAYPLANTMPLTVO extends TRSPAYPLANTMPLTVOKey {
    /**
     * This field corresponds to the database column TRSPAYPLANTMPLT.BRIEF_NAME_ENG
     */
    private String BRIEF_NAME_ENG;

    /**
     * This field corresponds to the database column TRSPAYPLANTMPLT.BRIEF_NAME_ARAB
     */
    private String BRIEF_NAME_ARAB;

    /**
     * This field corresponds to the database column TRSPAYPLANTMPLT.LONG_NAME_ENG
     */
    private String LONG_NAME_ENG;

    /**
     * This field corresponds to the database column TRSPAYPLANTMPLT.LONG_NAME_ARAB
     */
    private String LONG_NAME_ARAB;

    /**
     * This field corresponds to the database column TRSPAYPLANTMPLT.SETTLEMENT_TYPE
     */
    private String SETTLEMENT_TYPE;

    /**
     * This field corresponds to the database column TRSPAYPLANTMPLT.PROFIT_CALCULATION_METHOD
     */
    private String PROFIT_CALCULATION_METHOD;

    /**
     * This field corresponds to the database column TRSPAYPLANTMPLT.PRINCIPAL_LAST
     */
    private String PRINCIPAL_LAST;

    /**
     * This field corresponds to the database column TRSPAYPLANTMPLT.PROMISSORY_NOTES
     */
    private BigDecimal PROMISSORY_NOTES;

    /**
     * This field corresponds to the database column TRSPAYPLANTMPLT.PROMISSORY_NOTES_OPTION
     */
    private String PROMISSORY_NOTES_OPTION;

    /**
     * This field corresponds to the database column TRSPAYPLANTMPLT.NO_OF_PAYMENTS
     */
    private BigDecimal NO_OF_PAYMENTS;

    /**
     * This field corresponds to the database column TRSPAYPLANTMPLT.AMT_PER_PAYMENT
     */
    private BigDecimal AMT_PER_PAYMENT;

    /**
     * This field corresponds to the database column TRSPAYPLANTMPLT.ROUNDING_FACTOR
     */
    private BigDecimal ROUNDING_FACTOR;

    /**
     * This field corresponds to the database column TRSPAYPLANTMPLT.PAY_RES_AMT
     */
    private String PAY_RES_AMT;

    /**
     * This field corresponds to the database column TRSPAYPLANTMPLT.PAYM_PERIODICITY
     */
    private String PAYM_PERIODICITY;

    /**
     * This field corresponds to the database column TRSPAYPLANTMPLT.PAYM_PERIOD_NBR
     */
    private BigDecimal PAYM_PERIOD_NBR;

    /**
     * This field corresponds to the database column TRSPAYPLANTMPLT.PAYM_PERIOD_POS
     */
    private String PAYM_PERIOD_POS;

    /**
     * This field corresponds to the database column TRSPAYPLANTMPLT.BALLOON_PAYMENT
     */
    private BigDecimal BALLOON_PAYMENT;

    /**
     * This field corresponds to the database column TRSPAYPLANTMPLT.BALLOON_AMT
     */
    private BigDecimal BALLOON_AMT;

    /**
     * This field corresponds to the database column TRSPAYPLANTMPLT.NO_OF_BALLOONS
     */
    private BigDecimal NO_OF_BALLOONS;

    /**
     * This field corresponds to the database column TRSPAYPLANTMPLT.GRACE_PERIOD_OPTION
     */
    private BigDecimal GRACE_PERIOD_OPTION;

    /**
     * This field corresponds to the database column TRSPAYPLANTMPLT.GRACE_PERIOD
     */
    private BigDecimal GRACE_PERIOD;

    /**
     * This field corresponds to the database column TRSPAYPLANTMPLT.GRACE_PERIODICITY
     */
    private String GRACE_PERIODICITY;

    /**
     * This field corresponds to the database column TRSPAYPLANTMPLT.PROFIT_DIST_METHOD
     */
    private String PROFIT_DIST_METHOD;

    /**
     * This field corresponds to the database column TRSPAYPLANTMPLT.SETT_PRINCIPAL_YR_MIN_PERC
     */
    private BigDecimal SETT_PRINCIPAL_YR_MIN_PERC;

    /**
     * This field corresponds to the database column TRSPAYPLANTMPLT.SETT_PRINCIPAL_YR_MAX_PERC
     */
    private BigDecimal SETT_PRINCIPAL_YR_MAX_PERC;

    /**
     * This field corresponds to the database column TRSPAYPLANTMPLT.SETT_PRINCIPAL_YR_EXCEED_CRT
     */
    private String SETT_PRINCIPAL_YR_EXCEED_CRT;

    /**
     * This field corresponds to the database column TRSPAYPLANTMPLT.SETT_PRINCIPAL_YR_EXCEED_APPV
     */
    private String SETT_PRINCIPAL_YR_EXCEED_APPV;

    /**
     * This field corresponds to the database column TRSPAYPLANTMPLT.SET_LAST_INST_ON_MAT_DTE_IFNOT
     */
    private String SET_LAST_INST_ON_MAT_DTE_IFNOT;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPAYPLANTMPLT.BRIEF_NAME_ENG
     *
     * @return the value of TRSPAYPLANTMPLT.BRIEF_NAME_ENG
     */
    public String getBRIEF_NAME_ENG() {
        return BRIEF_NAME_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPAYPLANTMPLT.BRIEF_NAME_ENG
     *
     * @param BRIEF_NAME_ENG the value for TRSPAYPLANTMPLT.BRIEF_NAME_ENG
     */
    public void setBRIEF_NAME_ENG(String BRIEF_NAME_ENG) {
        this.BRIEF_NAME_ENG = BRIEF_NAME_ENG == null ? null : BRIEF_NAME_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPAYPLANTMPLT.BRIEF_NAME_ARAB
     *
     * @return the value of TRSPAYPLANTMPLT.BRIEF_NAME_ARAB
     */
    public String getBRIEF_NAME_ARAB() {
        return BRIEF_NAME_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPAYPLANTMPLT.BRIEF_NAME_ARAB
     *
     * @param BRIEF_NAME_ARAB the value for TRSPAYPLANTMPLT.BRIEF_NAME_ARAB
     */
    public void setBRIEF_NAME_ARAB(String BRIEF_NAME_ARAB) {
        this.BRIEF_NAME_ARAB = BRIEF_NAME_ARAB == null ? null : BRIEF_NAME_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPAYPLANTMPLT.LONG_NAME_ENG
     *
     * @return the value of TRSPAYPLANTMPLT.LONG_NAME_ENG
     */
    public String getLONG_NAME_ENG() {
        return LONG_NAME_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPAYPLANTMPLT.LONG_NAME_ENG
     *
     * @param LONG_NAME_ENG the value for TRSPAYPLANTMPLT.LONG_NAME_ENG
     */
    public void setLONG_NAME_ENG(String LONG_NAME_ENG) {
        this.LONG_NAME_ENG = LONG_NAME_ENG == null ? null : LONG_NAME_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPAYPLANTMPLT.LONG_NAME_ARAB
     *
     * @return the value of TRSPAYPLANTMPLT.LONG_NAME_ARAB
     */
    public String getLONG_NAME_ARAB() {
        return LONG_NAME_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPAYPLANTMPLT.LONG_NAME_ARAB
     *
     * @param LONG_NAME_ARAB the value for TRSPAYPLANTMPLT.LONG_NAME_ARAB
     */
    public void setLONG_NAME_ARAB(String LONG_NAME_ARAB) {
        this.LONG_NAME_ARAB = LONG_NAME_ARAB == null ? null : LONG_NAME_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPAYPLANTMPLT.SETTLEMENT_TYPE
     *
     * @return the value of TRSPAYPLANTMPLT.SETTLEMENT_TYPE
     */
    public String getSETTLEMENT_TYPE() {
        return SETTLEMENT_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPAYPLANTMPLT.SETTLEMENT_TYPE
     *
     * @param SETTLEMENT_TYPE the value for TRSPAYPLANTMPLT.SETTLEMENT_TYPE
     */
    public void setSETTLEMENT_TYPE(String SETTLEMENT_TYPE) {
        this.SETTLEMENT_TYPE = SETTLEMENT_TYPE == null ? null : SETTLEMENT_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPAYPLANTMPLT.PROFIT_CALCULATION_METHOD
     *
     * @return the value of TRSPAYPLANTMPLT.PROFIT_CALCULATION_METHOD
     */
    public String getPROFIT_CALCULATION_METHOD() {
        return PROFIT_CALCULATION_METHOD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPAYPLANTMPLT.PROFIT_CALCULATION_METHOD
     *
     * @param PROFIT_CALCULATION_METHOD the value for TRSPAYPLANTMPLT.PROFIT_CALCULATION_METHOD
     */
    public void setPROFIT_CALCULATION_METHOD(String PROFIT_CALCULATION_METHOD) {
        this.PROFIT_CALCULATION_METHOD = PROFIT_CALCULATION_METHOD == null ? null : PROFIT_CALCULATION_METHOD.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPAYPLANTMPLT.PRINCIPAL_LAST
     *
     * @return the value of TRSPAYPLANTMPLT.PRINCIPAL_LAST
     */
    public String getPRINCIPAL_LAST() {
        return PRINCIPAL_LAST;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPAYPLANTMPLT.PRINCIPAL_LAST
     *
     * @param PRINCIPAL_LAST the value for TRSPAYPLANTMPLT.PRINCIPAL_LAST
     */
    public void setPRINCIPAL_LAST(String PRINCIPAL_LAST) {
        this.PRINCIPAL_LAST = PRINCIPAL_LAST == null ? null : PRINCIPAL_LAST.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPAYPLANTMPLT.PROMISSORY_NOTES
     *
     * @return the value of TRSPAYPLANTMPLT.PROMISSORY_NOTES
     */
    public BigDecimal getPROMISSORY_NOTES() {
        return PROMISSORY_NOTES;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPAYPLANTMPLT.PROMISSORY_NOTES
     *
     * @param PROMISSORY_NOTES the value for TRSPAYPLANTMPLT.PROMISSORY_NOTES
     */
    public void setPROMISSORY_NOTES(BigDecimal PROMISSORY_NOTES) {
        this.PROMISSORY_NOTES = PROMISSORY_NOTES;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPAYPLANTMPLT.PROMISSORY_NOTES_OPTION
     *
     * @return the value of TRSPAYPLANTMPLT.PROMISSORY_NOTES_OPTION
     */
    public String getPROMISSORY_NOTES_OPTION() {
        return PROMISSORY_NOTES_OPTION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPAYPLANTMPLT.PROMISSORY_NOTES_OPTION
     *
     * @param PROMISSORY_NOTES_OPTION the value for TRSPAYPLANTMPLT.PROMISSORY_NOTES_OPTION
     */
    public void setPROMISSORY_NOTES_OPTION(String PROMISSORY_NOTES_OPTION) {
        this.PROMISSORY_NOTES_OPTION = PROMISSORY_NOTES_OPTION == null ? null : PROMISSORY_NOTES_OPTION.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPAYPLANTMPLT.NO_OF_PAYMENTS
     *
     * @return the value of TRSPAYPLANTMPLT.NO_OF_PAYMENTS
     */
    public BigDecimal getNO_OF_PAYMENTS() {
        return NO_OF_PAYMENTS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPAYPLANTMPLT.NO_OF_PAYMENTS
     *
     * @param NO_OF_PAYMENTS the value for TRSPAYPLANTMPLT.NO_OF_PAYMENTS
     */
    public void setNO_OF_PAYMENTS(BigDecimal NO_OF_PAYMENTS) {
        this.NO_OF_PAYMENTS = NO_OF_PAYMENTS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPAYPLANTMPLT.AMT_PER_PAYMENT
     *
     * @return the value of TRSPAYPLANTMPLT.AMT_PER_PAYMENT
     */
    public BigDecimal getAMT_PER_PAYMENT() {
        return AMT_PER_PAYMENT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPAYPLANTMPLT.AMT_PER_PAYMENT
     *
     * @param AMT_PER_PAYMENT the value for TRSPAYPLANTMPLT.AMT_PER_PAYMENT
     */
    public void setAMT_PER_PAYMENT(BigDecimal AMT_PER_PAYMENT) {
        this.AMT_PER_PAYMENT = AMT_PER_PAYMENT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPAYPLANTMPLT.ROUNDING_FACTOR
     *
     * @return the value of TRSPAYPLANTMPLT.ROUNDING_FACTOR
     */
    public BigDecimal getROUNDING_FACTOR() {
        return ROUNDING_FACTOR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPAYPLANTMPLT.ROUNDING_FACTOR
     *
     * @param ROUNDING_FACTOR the value for TRSPAYPLANTMPLT.ROUNDING_FACTOR
     */
    public void setROUNDING_FACTOR(BigDecimal ROUNDING_FACTOR) {
        this.ROUNDING_FACTOR = ROUNDING_FACTOR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPAYPLANTMPLT.PAY_RES_AMT
     *
     * @return the value of TRSPAYPLANTMPLT.PAY_RES_AMT
     */
    public String getPAY_RES_AMT() {
        return PAY_RES_AMT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPAYPLANTMPLT.PAY_RES_AMT
     *
     * @param PAY_RES_AMT the value for TRSPAYPLANTMPLT.PAY_RES_AMT
     */
    public void setPAY_RES_AMT(String PAY_RES_AMT) {
        this.PAY_RES_AMT = PAY_RES_AMT == null ? null : PAY_RES_AMT.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPAYPLANTMPLT.PAYM_PERIODICITY
     *
     * @return the value of TRSPAYPLANTMPLT.PAYM_PERIODICITY
     */
    public String getPAYM_PERIODICITY() {
        return PAYM_PERIODICITY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPAYPLANTMPLT.PAYM_PERIODICITY
     *
     * @param PAYM_PERIODICITY the value for TRSPAYPLANTMPLT.PAYM_PERIODICITY
     */
    public void setPAYM_PERIODICITY(String PAYM_PERIODICITY) {
        this.PAYM_PERIODICITY = PAYM_PERIODICITY == null ? null : PAYM_PERIODICITY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPAYPLANTMPLT.PAYM_PERIOD_NBR
     *
     * @return the value of TRSPAYPLANTMPLT.PAYM_PERIOD_NBR
     */
    public BigDecimal getPAYM_PERIOD_NBR() {
        return PAYM_PERIOD_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPAYPLANTMPLT.PAYM_PERIOD_NBR
     *
     * @param PAYM_PERIOD_NBR the value for TRSPAYPLANTMPLT.PAYM_PERIOD_NBR
     */
    public void setPAYM_PERIOD_NBR(BigDecimal PAYM_PERIOD_NBR) {
        this.PAYM_PERIOD_NBR = PAYM_PERIOD_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPAYPLANTMPLT.PAYM_PERIOD_POS
     *
     * @return the value of TRSPAYPLANTMPLT.PAYM_PERIOD_POS
     */
    public String getPAYM_PERIOD_POS() {
        return PAYM_PERIOD_POS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPAYPLANTMPLT.PAYM_PERIOD_POS
     *
     * @param PAYM_PERIOD_POS the value for TRSPAYPLANTMPLT.PAYM_PERIOD_POS
     */
    public void setPAYM_PERIOD_POS(String PAYM_PERIOD_POS) {
        this.PAYM_PERIOD_POS = PAYM_PERIOD_POS == null ? null : PAYM_PERIOD_POS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPAYPLANTMPLT.BALLOON_PAYMENT
     *
     * @return the value of TRSPAYPLANTMPLT.BALLOON_PAYMENT
     */
    public BigDecimal getBALLOON_PAYMENT() {
        return BALLOON_PAYMENT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPAYPLANTMPLT.BALLOON_PAYMENT
     *
     * @param BALLOON_PAYMENT the value for TRSPAYPLANTMPLT.BALLOON_PAYMENT
     */
    public void setBALLOON_PAYMENT(BigDecimal BALLOON_PAYMENT) {
        this.BALLOON_PAYMENT = BALLOON_PAYMENT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPAYPLANTMPLT.BALLOON_AMT
     *
     * @return the value of TRSPAYPLANTMPLT.BALLOON_AMT
     */
    public BigDecimal getBALLOON_AMT() {
        return BALLOON_AMT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPAYPLANTMPLT.BALLOON_AMT
     *
     * @param BALLOON_AMT the value for TRSPAYPLANTMPLT.BALLOON_AMT
     */
    public void setBALLOON_AMT(BigDecimal BALLOON_AMT) {
        this.BALLOON_AMT = BALLOON_AMT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPAYPLANTMPLT.NO_OF_BALLOONS
     *
     * @return the value of TRSPAYPLANTMPLT.NO_OF_BALLOONS
     */
    public BigDecimal getNO_OF_BALLOONS() {
        return NO_OF_BALLOONS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPAYPLANTMPLT.NO_OF_BALLOONS
     *
     * @param NO_OF_BALLOONS the value for TRSPAYPLANTMPLT.NO_OF_BALLOONS
     */
    public void setNO_OF_BALLOONS(BigDecimal NO_OF_BALLOONS) {
        this.NO_OF_BALLOONS = NO_OF_BALLOONS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPAYPLANTMPLT.GRACE_PERIOD_OPTION
     *
     * @return the value of TRSPAYPLANTMPLT.GRACE_PERIOD_OPTION
     */
    public BigDecimal getGRACE_PERIOD_OPTION() {
        return GRACE_PERIOD_OPTION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPAYPLANTMPLT.GRACE_PERIOD_OPTION
     *
     * @param GRACE_PERIOD_OPTION the value for TRSPAYPLANTMPLT.GRACE_PERIOD_OPTION
     */
    public void setGRACE_PERIOD_OPTION(BigDecimal GRACE_PERIOD_OPTION) {
        this.GRACE_PERIOD_OPTION = GRACE_PERIOD_OPTION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPAYPLANTMPLT.GRACE_PERIOD
     *
     * @return the value of TRSPAYPLANTMPLT.GRACE_PERIOD
     */
    public BigDecimal getGRACE_PERIOD() {
        return GRACE_PERIOD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPAYPLANTMPLT.GRACE_PERIOD
     *
     * @param GRACE_PERIOD the value for TRSPAYPLANTMPLT.GRACE_PERIOD
     */
    public void setGRACE_PERIOD(BigDecimal GRACE_PERIOD) {
        this.GRACE_PERIOD = GRACE_PERIOD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPAYPLANTMPLT.GRACE_PERIODICITY
     *
     * @return the value of TRSPAYPLANTMPLT.GRACE_PERIODICITY
     */
    public String getGRACE_PERIODICITY() {
        return GRACE_PERIODICITY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPAYPLANTMPLT.GRACE_PERIODICITY
     *
     * @param GRACE_PERIODICITY the value for TRSPAYPLANTMPLT.GRACE_PERIODICITY
     */
    public void setGRACE_PERIODICITY(String GRACE_PERIODICITY) {
        this.GRACE_PERIODICITY = GRACE_PERIODICITY == null ? null : GRACE_PERIODICITY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPAYPLANTMPLT.PROFIT_DIST_METHOD
     *
     * @return the value of TRSPAYPLANTMPLT.PROFIT_DIST_METHOD
     */
    public String getPROFIT_DIST_METHOD() {
        return PROFIT_DIST_METHOD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPAYPLANTMPLT.PROFIT_DIST_METHOD
     *
     * @param PROFIT_DIST_METHOD the value for TRSPAYPLANTMPLT.PROFIT_DIST_METHOD
     */
    public void setPROFIT_DIST_METHOD(String PROFIT_DIST_METHOD) {
        this.PROFIT_DIST_METHOD = PROFIT_DIST_METHOD == null ? null : PROFIT_DIST_METHOD.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPAYPLANTMPLT.SETT_PRINCIPAL_YR_MIN_PERC
     *
     * @return the value of TRSPAYPLANTMPLT.SETT_PRINCIPAL_YR_MIN_PERC
     */
    public BigDecimal getSETT_PRINCIPAL_YR_MIN_PERC() {
        return SETT_PRINCIPAL_YR_MIN_PERC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPAYPLANTMPLT.SETT_PRINCIPAL_YR_MIN_PERC
     *
     * @param SETT_PRINCIPAL_YR_MIN_PERC the value for TRSPAYPLANTMPLT.SETT_PRINCIPAL_YR_MIN_PERC
     */
    public void setSETT_PRINCIPAL_YR_MIN_PERC(BigDecimal SETT_PRINCIPAL_YR_MIN_PERC) {
        this.SETT_PRINCIPAL_YR_MIN_PERC = SETT_PRINCIPAL_YR_MIN_PERC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPAYPLANTMPLT.SETT_PRINCIPAL_YR_MAX_PERC
     *
     * @return the value of TRSPAYPLANTMPLT.SETT_PRINCIPAL_YR_MAX_PERC
     */
    public BigDecimal getSETT_PRINCIPAL_YR_MAX_PERC() {
        return SETT_PRINCIPAL_YR_MAX_PERC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPAYPLANTMPLT.SETT_PRINCIPAL_YR_MAX_PERC
     *
     * @param SETT_PRINCIPAL_YR_MAX_PERC the value for TRSPAYPLANTMPLT.SETT_PRINCIPAL_YR_MAX_PERC
     */
    public void setSETT_PRINCIPAL_YR_MAX_PERC(BigDecimal SETT_PRINCIPAL_YR_MAX_PERC) {
        this.SETT_PRINCIPAL_YR_MAX_PERC = SETT_PRINCIPAL_YR_MAX_PERC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPAYPLANTMPLT.SETT_PRINCIPAL_YR_EXCEED_CRT
     *
     * @return the value of TRSPAYPLANTMPLT.SETT_PRINCIPAL_YR_EXCEED_CRT
     */
    public String getSETT_PRINCIPAL_YR_EXCEED_CRT() {
        return SETT_PRINCIPAL_YR_EXCEED_CRT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPAYPLANTMPLT.SETT_PRINCIPAL_YR_EXCEED_CRT
     *
     * @param SETT_PRINCIPAL_YR_EXCEED_CRT the value for TRSPAYPLANTMPLT.SETT_PRINCIPAL_YR_EXCEED_CRT
     */
    public void setSETT_PRINCIPAL_YR_EXCEED_CRT(String SETT_PRINCIPAL_YR_EXCEED_CRT) {
        this.SETT_PRINCIPAL_YR_EXCEED_CRT = SETT_PRINCIPAL_YR_EXCEED_CRT == null ? null : SETT_PRINCIPAL_YR_EXCEED_CRT.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPAYPLANTMPLT.SETT_PRINCIPAL_YR_EXCEED_APPV
     *
     * @return the value of TRSPAYPLANTMPLT.SETT_PRINCIPAL_YR_EXCEED_APPV
     */
    public String getSETT_PRINCIPAL_YR_EXCEED_APPV() {
        return SETT_PRINCIPAL_YR_EXCEED_APPV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPAYPLANTMPLT.SETT_PRINCIPAL_YR_EXCEED_APPV
     *
     * @param SETT_PRINCIPAL_YR_EXCEED_APPV the value for TRSPAYPLANTMPLT.SETT_PRINCIPAL_YR_EXCEED_APPV
     */
    public void setSETT_PRINCIPAL_YR_EXCEED_APPV(String SETT_PRINCIPAL_YR_EXCEED_APPV) {
        this.SETT_PRINCIPAL_YR_EXCEED_APPV = SETT_PRINCIPAL_YR_EXCEED_APPV == null ? null : SETT_PRINCIPAL_YR_EXCEED_APPV.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSPAYPLANTMPLT.SET_LAST_INST_ON_MAT_DTE_IFNOT
     *
     * @return the value of TRSPAYPLANTMPLT.SET_LAST_INST_ON_MAT_DTE_IFNOT
     */
    public String getSET_LAST_INST_ON_MAT_DTE_IFNOT() {
        return SET_LAST_INST_ON_MAT_DTE_IFNOT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSPAYPLANTMPLT.SET_LAST_INST_ON_MAT_DTE_IFNOT
     *
     * @param SET_LAST_INST_ON_MAT_DTE_IFNOT the value for TRSPAYPLANTMPLT.SET_LAST_INST_ON_MAT_DTE_IFNOT
     */
    public void setSET_LAST_INST_ON_MAT_DTE_IFNOT(String SET_LAST_INST_ON_MAT_DTE_IFNOT) {
        this.SET_LAST_INST_ON_MAT_DTE_IFNOT = SET_LAST_INST_ON_MAT_DTE_IFNOT == null ? null : SET_LAST_INST_ON_MAT_DTE_IFNOT.trim();
    }
}