package com.path.dbmaps.vo;

import java.util.Date;

public class TRSROSTERVO extends TRSROSTERVOKey {
    /**
     * This field corresponds to the database column TRSROSTER.BRIEF_NAME_ENG
     */
    private String BRIEF_NAME_ENG;

    /**
     * This field corresponds to the database column TRSROSTER.LONG_NAME_ENG
     */
    private String LONG_NAME_ENG;

    /**
     * This field corresponds to the database column TRSROSTER.BRIEF_NAME_ARAB
     */
    private String BRIEF_NAME_ARAB;

    /**
     * This field corresponds to the database column TRSROSTER.LONG_NAME_ARAB
     */
    private String LONG_NAME_ARAB;

    /**
     * This field corresponds to the database column TRSROSTER.CREATED_BY
     */
    private String CREATED_BY;

    /**
     * This field corresponds to the database column TRSROSTER.DATE_CREATED
     */
    private Date DATE_CREATED;

    /**
     * This field corresponds to the database column TRSROSTER.MODIFIED_BY
     */
    private String MODIFIED_BY;

    /**
     * This field corresponds to the database column TRSROSTER.DATE_MODIFIED
     */
    private Date DATE_MODIFIED;

    /**
     * This field corresponds to the database column TRSROSTER.ALLOW_EDIT_DEFAULTED_YIELD
     */
    private String ALLOW_EDIT_DEFAULTED_YIELD;

    /**
     * This field corresponds to the database column TRSROSTER.ALLOW_EDIT_YIELD_OUTSIDE_RANGE
     */
    private String ALLOW_EDIT_YIELD_OUTSIDE_RANGE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSROSTER.BRIEF_NAME_ENG
     *
     * @return the value of TRSROSTER.BRIEF_NAME_ENG
     */
    public String getBRIEF_NAME_ENG() {
        return BRIEF_NAME_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSROSTER.BRIEF_NAME_ENG
     *
     * @param BRIEF_NAME_ENG the value for TRSROSTER.BRIEF_NAME_ENG
     */
    public void setBRIEF_NAME_ENG(String BRIEF_NAME_ENG) {
        this.BRIEF_NAME_ENG = BRIEF_NAME_ENG == null ? null : BRIEF_NAME_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSROSTER.LONG_NAME_ENG
     *
     * @return the value of TRSROSTER.LONG_NAME_ENG
     */
    public String getLONG_NAME_ENG() {
        return LONG_NAME_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSROSTER.LONG_NAME_ENG
     *
     * @param LONG_NAME_ENG the value for TRSROSTER.LONG_NAME_ENG
     */
    public void setLONG_NAME_ENG(String LONG_NAME_ENG) {
        this.LONG_NAME_ENG = LONG_NAME_ENG == null ? null : LONG_NAME_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSROSTER.BRIEF_NAME_ARAB
     *
     * @return the value of TRSROSTER.BRIEF_NAME_ARAB
     */
    public String getBRIEF_NAME_ARAB() {
        return BRIEF_NAME_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSROSTER.BRIEF_NAME_ARAB
     *
     * @param BRIEF_NAME_ARAB the value for TRSROSTER.BRIEF_NAME_ARAB
     */
    public void setBRIEF_NAME_ARAB(String BRIEF_NAME_ARAB) {
        this.BRIEF_NAME_ARAB = BRIEF_NAME_ARAB == null ? null : BRIEF_NAME_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSROSTER.LONG_NAME_ARAB
     *
     * @return the value of TRSROSTER.LONG_NAME_ARAB
     */
    public String getLONG_NAME_ARAB() {
        return LONG_NAME_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSROSTER.LONG_NAME_ARAB
     *
     * @param LONG_NAME_ARAB the value for TRSROSTER.LONG_NAME_ARAB
     */
    public void setLONG_NAME_ARAB(String LONG_NAME_ARAB) {
        this.LONG_NAME_ARAB = LONG_NAME_ARAB == null ? null : LONG_NAME_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSROSTER.CREATED_BY
     *
     * @return the value of TRSROSTER.CREATED_BY
     */
    public String getCREATED_BY() {
        return CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSROSTER.CREATED_BY
     *
     * @param CREATED_BY the value for TRSROSTER.CREATED_BY
     */
    public void setCREATED_BY(String CREATED_BY) {
        this.CREATED_BY = CREATED_BY == null ? null : CREATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSROSTER.DATE_CREATED
     *
     * @return the value of TRSROSTER.DATE_CREATED
     */
    public Date getDATE_CREATED() {
        return DATE_CREATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSROSTER.DATE_CREATED
     *
     * @param DATE_CREATED the value for TRSROSTER.DATE_CREATED
     */
    public void setDATE_CREATED(Date DATE_CREATED) {
        this.DATE_CREATED = DATE_CREATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSROSTER.MODIFIED_BY
     *
     * @return the value of TRSROSTER.MODIFIED_BY
     */
    public String getMODIFIED_BY() {
        return MODIFIED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSROSTER.MODIFIED_BY
     *
     * @param MODIFIED_BY the value for TRSROSTER.MODIFIED_BY
     */
    public void setMODIFIED_BY(String MODIFIED_BY) {
        this.MODIFIED_BY = MODIFIED_BY == null ? null : MODIFIED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSROSTER.DATE_MODIFIED
     *
     * @return the value of TRSROSTER.DATE_MODIFIED
     */
    public Date getDATE_MODIFIED() {
        return DATE_MODIFIED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSROSTER.DATE_MODIFIED
     *
     * @param DATE_MODIFIED the value for TRSROSTER.DATE_MODIFIED
     */
    public void setDATE_MODIFIED(Date DATE_MODIFIED) {
        this.DATE_MODIFIED = DATE_MODIFIED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSROSTER.ALLOW_EDIT_DEFAULTED_YIELD
     *
     * @return the value of TRSROSTER.ALLOW_EDIT_DEFAULTED_YIELD
     */
    public String getALLOW_EDIT_DEFAULTED_YIELD() {
        return ALLOW_EDIT_DEFAULTED_YIELD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSROSTER.ALLOW_EDIT_DEFAULTED_YIELD
     *
     * @param ALLOW_EDIT_DEFAULTED_YIELD the value for TRSROSTER.ALLOW_EDIT_DEFAULTED_YIELD
     */
    public void setALLOW_EDIT_DEFAULTED_YIELD(String ALLOW_EDIT_DEFAULTED_YIELD) {
        this.ALLOW_EDIT_DEFAULTED_YIELD = ALLOW_EDIT_DEFAULTED_YIELD == null ? null : ALLOW_EDIT_DEFAULTED_YIELD.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSROSTER.ALLOW_EDIT_YIELD_OUTSIDE_RANGE
     *
     * @return the value of TRSROSTER.ALLOW_EDIT_YIELD_OUTSIDE_RANGE
     */
    public String getALLOW_EDIT_YIELD_OUTSIDE_RANGE() {
        return ALLOW_EDIT_YIELD_OUTSIDE_RANGE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSROSTER.ALLOW_EDIT_YIELD_OUTSIDE_RANGE
     *
     * @param ALLOW_EDIT_YIELD_OUTSIDE_RANGE the value for TRSROSTER.ALLOW_EDIT_YIELD_OUTSIDE_RANGE
     */
    public void setALLOW_EDIT_YIELD_OUTSIDE_RANGE(String ALLOW_EDIT_YIELD_OUTSIDE_RANGE) {
        this.ALLOW_EDIT_YIELD_OUTSIDE_RANGE = ALLOW_EDIT_YIELD_OUTSIDE_RANGE == null ? null : ALLOW_EDIT_YIELD_OUTSIDE_RANGE.trim();
    }
}