package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class TRSROSTER_REGISTER_DETVOKey extends BaseVO {
    /**
     * This field corresponds to the database column TRSROSTER_REGISTER_DET.BRANCH_CODE
     */
    private BigDecimal BRANCH_CODE;

    /**
     * This field corresponds to the database column TRSROSTER_REGISTER_DET.CODE
     */
    private BigDecimal CODE;

    /**
     * This field corresponds to the database column TRSROSTER_REGISTER_DET.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column TRSROSTER_REGISTER_DET.ENTITY_TYPE
     */
    private String ENTITY_TYPE;

    /**
     * This field corresponds to the database column TRSROSTER_REGISTER_DET.LINE_NO
     */
    private BigDecimal LINE_NO;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSROSTER_REGISTER_DET.BRANCH_CODE
     *
     * @return the value of TRSROSTER_REGISTER_DET.BRANCH_CODE
     */
    public BigDecimal getBRANCH_CODE() {
        return BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSROSTER_REGISTER_DET.BRANCH_CODE
     *
     * @param BRANCH_CODE the value for TRSROSTER_REGISTER_DET.BRANCH_CODE
     */
    public void setBRANCH_CODE(BigDecimal BRANCH_CODE) {
        this.BRANCH_CODE = BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSROSTER_REGISTER_DET.CODE
     *
     * @return the value of TRSROSTER_REGISTER_DET.CODE
     */
    public BigDecimal getCODE() {
        return CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSROSTER_REGISTER_DET.CODE
     *
     * @param CODE the value for TRSROSTER_REGISTER_DET.CODE
     */
    public void setCODE(BigDecimal CODE) {
        this.CODE = CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSROSTER_REGISTER_DET.COMP_CODE
     *
     * @return the value of TRSROSTER_REGISTER_DET.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSROSTER_REGISTER_DET.COMP_CODE
     *
     * @param COMP_CODE the value for TRSROSTER_REGISTER_DET.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSROSTER_REGISTER_DET.ENTITY_TYPE
     *
     * @return the value of TRSROSTER_REGISTER_DET.ENTITY_TYPE
     */
    public String getENTITY_TYPE() {
        return ENTITY_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSROSTER_REGISTER_DET.ENTITY_TYPE
     *
     * @param ENTITY_TYPE the value for TRSROSTER_REGISTER_DET.ENTITY_TYPE
     */
    public void setENTITY_TYPE(String ENTITY_TYPE) {
        this.ENTITY_TYPE = ENTITY_TYPE == null ? null : ENTITY_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSROSTER_REGISTER_DET.LINE_NO
     *
     * @return the value of TRSROSTER_REGISTER_DET.LINE_NO
     */
    public BigDecimal getLINE_NO() {
        return LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSROSTER_REGISTER_DET.LINE_NO
     *
     * @param LINE_NO the value for TRSROSTER_REGISTER_DET.LINE_NO
     */
    public void setLINE_NO(BigDecimal LINE_NO) {
        this.LINE_NO = LINE_NO;
    }
}