package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class TRSSETLMT_NIDCVO extends TRSSETLMT_NIDCVOKey {
    /**
     * This field corresponds to the database column TRSSETLMT_NIDC.DEAL_NO
     */
    private BigDecimal DEAL_NO;

    /**
     * This field corresponds to the database column TRSSETLMT_NIDC.FACE_VALUE
     */
    private BigDecimal FACE_VALUE;

    /**
     * This field corresponds to the database column TRSSETLMT_NIDC.NO_OF_CERTIFICATE
     */
    private BigDecimal NO_OF_CERTIFICATE;

    /**
     * This field corresponds to the database column TRSSETLMT_NIDC.ISSUE_AT_TYPE
     */
    private String ISSUE_AT_TYPE;

    /**
     * This field corresponds to the database column TRSSETLMT_NIDC.COUPON_PAYMENT_TYPE
     */
    private String COUPON_PAYMENT_TYPE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSSETLMT_NIDC.DEAL_NO
     *
     * @return the value of TRSSETLMT_NIDC.DEAL_NO
     */
    public BigDecimal getDEAL_NO() {
        return DEAL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSSETLMT_NIDC.DEAL_NO
     *
     * @param DEAL_NO the value for TRSSETLMT_NIDC.DEAL_NO
     */
    public void setDEAL_NO(BigDecimal DEAL_NO) {
        this.DEAL_NO = DEAL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSSETLMT_NIDC.FACE_VALUE
     *
     * @return the value of TRSSETLMT_NIDC.FACE_VALUE
     */
    public BigDecimal getFACE_VALUE() {
        return FACE_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSSETLMT_NIDC.FACE_VALUE
     *
     * @param FACE_VALUE the value for TRSSETLMT_NIDC.FACE_VALUE
     */
    public void setFACE_VALUE(BigDecimal FACE_VALUE) {
        this.FACE_VALUE = FACE_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSSETLMT_NIDC.NO_OF_CERTIFICATE
     *
     * @return the value of TRSSETLMT_NIDC.NO_OF_CERTIFICATE
     */
    public BigDecimal getNO_OF_CERTIFICATE() {
        return NO_OF_CERTIFICATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSSETLMT_NIDC.NO_OF_CERTIFICATE
     *
     * @param NO_OF_CERTIFICATE the value for TRSSETLMT_NIDC.NO_OF_CERTIFICATE
     */
    public void setNO_OF_CERTIFICATE(BigDecimal NO_OF_CERTIFICATE) {
        this.NO_OF_CERTIFICATE = NO_OF_CERTIFICATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSSETLMT_NIDC.ISSUE_AT_TYPE
     *
     * @return the value of TRSSETLMT_NIDC.ISSUE_AT_TYPE
     */
    public String getISSUE_AT_TYPE() {
        return ISSUE_AT_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSSETLMT_NIDC.ISSUE_AT_TYPE
     *
     * @param ISSUE_AT_TYPE the value for TRSSETLMT_NIDC.ISSUE_AT_TYPE
     */
    public void setISSUE_AT_TYPE(String ISSUE_AT_TYPE) {
        this.ISSUE_AT_TYPE = ISSUE_AT_TYPE == null ? null : ISSUE_AT_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSSETLMT_NIDC.COUPON_PAYMENT_TYPE
     *
     * @return the value of TRSSETLMT_NIDC.COUPON_PAYMENT_TYPE
     */
    public String getCOUPON_PAYMENT_TYPE() {
        return COUPON_PAYMENT_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSSETLMT_NIDC.COUPON_PAYMENT_TYPE
     *
     * @param COUPON_PAYMENT_TYPE the value for TRSSETLMT_NIDC.COUPON_PAYMENT_TYPE
     */
    public void setCOUPON_PAYMENT_TYPE(String COUPON_PAYMENT_TYPE) {
        this.COUPON_PAYMENT_TYPE = COUPON_PAYMENT_TYPE == null ? null : COUPON_PAYMENT_TYPE.trim();
    }
}