package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class TRSSETLMT_EXTENDEDVO extends TRSSETLMT_EXTENDEDVOKey {
    /**
     * This field corresponds to the database column TRSSETLMT_EXTENDED.SWITCH_DEAL_TYPE
     */
    private BigDecimal SWITCH_DEAL_TYPE;

    /**
     * This field corresponds to the database column TRSSETLMT_EXTENDED.INCLUDE_CURRENT_INSTALLMENT_YN
     */
    private String INCLUDE_CURRENT_INSTALLMENT_YN;

    /**
     * This field corresponds to the database column TRSSETLMT_EXTENDED.PAST_DUE_AMOUNT_SWITCHING
     */
    private BigDecimal PAST_DUE_AMOUNT_SWITCHING;

    /**
     * This field corresponds to the database column TRSSETLMT_EXTENDED.PRINCIPAL_OUTSTANDING
     */
    private BigDecimal PRINCIPAL_OUTSTANDING;

    /**
     * This field corresponds to the database column TRSSETLMT_EXTENDED.INCIDENTAL_CHARGE_COLLECTED
     */
    private BigDecimal INCIDENTAL_CHARGE_COLLECTED;

    /**
     * This field corresponds to the database column TRSSETLMT_EXTENDED.INCIDENTAL_CHARGE_DUE
     */
    private BigDecimal INCIDENTAL_CHARGE_DUE;

    /**
     * This field corresponds to the database column TRSSETLMT_EXTENDED.REPOSSESSION_TYPE
     */
    private BigDecimal REPOSSESSION_TYPE;

    /**
     * This field corresponds to the database column TRSSETLMT_EXTENDED.ADVANCE_USUFRUCT
     */
    private BigDecimal ADVANCE_USUFRUCT;

    /**
     * This field corresponds to the database column TRSSETLMT_EXTENDED.REIMBURSE_ADVANCE_USUFRUCT
     */
    private BigDecimal REIMBURSE_ADVANCE_USUFRUCT;

    /**
     * This field corresponds to the database column TRSSETLMT_EXTENDED.COLLECTED_INSURANCE_CHARGES
     */
    private BigDecimal COLLECTED_INSURANCE_CHARGES;

    /**
     * This field corresponds to the database column TRSSETLMT_EXTENDED.SECURITY_DEPOSIT
     */
    private BigDecimal SECURITY_DEPOSIT;

    /**
     * This field corresponds to the database column TRSSETLMT_EXTENDED.OUTSTANDING_INSURANCE_CHARGES
     */
    private BigDecimal OUTSTANDING_INSURANCE_CHARGES;

    /**
     * This field corresponds to the database column TRSSETLMT_EXTENDED.ASSET_MATURITY_ACTION
     */
    private String ASSET_MATURITY_ACTION;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSSETLMT_EXTENDED.SWITCH_DEAL_TYPE
     *
     * @return the value of TRSSETLMT_EXTENDED.SWITCH_DEAL_TYPE
     */
    public BigDecimal getSWITCH_DEAL_TYPE() {
        return SWITCH_DEAL_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSSETLMT_EXTENDED.SWITCH_DEAL_TYPE
     *
     * @param SWITCH_DEAL_TYPE the value for TRSSETLMT_EXTENDED.SWITCH_DEAL_TYPE
     */
    public void setSWITCH_DEAL_TYPE(BigDecimal SWITCH_DEAL_TYPE) {
        this.SWITCH_DEAL_TYPE = SWITCH_DEAL_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSSETLMT_EXTENDED.INCLUDE_CURRENT_INSTALLMENT_YN
     *
     * @return the value of TRSSETLMT_EXTENDED.INCLUDE_CURRENT_INSTALLMENT_YN
     */
    public String getINCLUDE_CURRENT_INSTALLMENT_YN() {
        return INCLUDE_CURRENT_INSTALLMENT_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSSETLMT_EXTENDED.INCLUDE_CURRENT_INSTALLMENT_YN
     *
     * @param INCLUDE_CURRENT_INSTALLMENT_YN the value for TRSSETLMT_EXTENDED.INCLUDE_CURRENT_INSTALLMENT_YN
     */
    public void setINCLUDE_CURRENT_INSTALLMENT_YN(String INCLUDE_CURRENT_INSTALLMENT_YN) {
        this.INCLUDE_CURRENT_INSTALLMENT_YN = INCLUDE_CURRENT_INSTALLMENT_YN == null ? null : INCLUDE_CURRENT_INSTALLMENT_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSSETLMT_EXTENDED.PAST_DUE_AMOUNT_SWITCHING
     *
     * @return the value of TRSSETLMT_EXTENDED.PAST_DUE_AMOUNT_SWITCHING
     */
    public BigDecimal getPAST_DUE_AMOUNT_SWITCHING() {
        return PAST_DUE_AMOUNT_SWITCHING;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSSETLMT_EXTENDED.PAST_DUE_AMOUNT_SWITCHING
     *
     * @param PAST_DUE_AMOUNT_SWITCHING the value for TRSSETLMT_EXTENDED.PAST_DUE_AMOUNT_SWITCHING
     */
    public void setPAST_DUE_AMOUNT_SWITCHING(BigDecimal PAST_DUE_AMOUNT_SWITCHING) {
        this.PAST_DUE_AMOUNT_SWITCHING = PAST_DUE_AMOUNT_SWITCHING;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSSETLMT_EXTENDED.PRINCIPAL_OUTSTANDING
     *
     * @return the value of TRSSETLMT_EXTENDED.PRINCIPAL_OUTSTANDING
     */
    public BigDecimal getPRINCIPAL_OUTSTANDING() {
        return PRINCIPAL_OUTSTANDING;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSSETLMT_EXTENDED.PRINCIPAL_OUTSTANDING
     *
     * @param PRINCIPAL_OUTSTANDING the value for TRSSETLMT_EXTENDED.PRINCIPAL_OUTSTANDING
     */
    public void setPRINCIPAL_OUTSTANDING(BigDecimal PRINCIPAL_OUTSTANDING) {
        this.PRINCIPAL_OUTSTANDING = PRINCIPAL_OUTSTANDING;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSSETLMT_EXTENDED.INCIDENTAL_CHARGE_COLLECTED
     *
     * @return the value of TRSSETLMT_EXTENDED.INCIDENTAL_CHARGE_COLLECTED
     */
    public BigDecimal getINCIDENTAL_CHARGE_COLLECTED() {
        return INCIDENTAL_CHARGE_COLLECTED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSSETLMT_EXTENDED.INCIDENTAL_CHARGE_COLLECTED
     *
     * @param INCIDENTAL_CHARGE_COLLECTED the value for TRSSETLMT_EXTENDED.INCIDENTAL_CHARGE_COLLECTED
     */
    public void setINCIDENTAL_CHARGE_COLLECTED(BigDecimal INCIDENTAL_CHARGE_COLLECTED) {
        this.INCIDENTAL_CHARGE_COLLECTED = INCIDENTAL_CHARGE_COLLECTED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSSETLMT_EXTENDED.INCIDENTAL_CHARGE_DUE
     *
     * @return the value of TRSSETLMT_EXTENDED.INCIDENTAL_CHARGE_DUE
     */
    public BigDecimal getINCIDENTAL_CHARGE_DUE() {
        return INCIDENTAL_CHARGE_DUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSSETLMT_EXTENDED.INCIDENTAL_CHARGE_DUE
     *
     * @param INCIDENTAL_CHARGE_DUE the value for TRSSETLMT_EXTENDED.INCIDENTAL_CHARGE_DUE
     */
    public void setINCIDENTAL_CHARGE_DUE(BigDecimal INCIDENTAL_CHARGE_DUE) {
        this.INCIDENTAL_CHARGE_DUE = INCIDENTAL_CHARGE_DUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSSETLMT_EXTENDED.REPOSSESSION_TYPE
     *
     * @return the value of TRSSETLMT_EXTENDED.REPOSSESSION_TYPE
     */
    public BigDecimal getREPOSSESSION_TYPE() {
        return REPOSSESSION_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSSETLMT_EXTENDED.REPOSSESSION_TYPE
     *
     * @param REPOSSESSION_TYPE the value for TRSSETLMT_EXTENDED.REPOSSESSION_TYPE
     */
    public void setREPOSSESSION_TYPE(BigDecimal REPOSSESSION_TYPE) {
        this.REPOSSESSION_TYPE = REPOSSESSION_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSSETLMT_EXTENDED.ADVANCE_USUFRUCT
     *
     * @return the value of TRSSETLMT_EXTENDED.ADVANCE_USUFRUCT
     */
    public BigDecimal getADVANCE_USUFRUCT() {
        return ADVANCE_USUFRUCT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSSETLMT_EXTENDED.ADVANCE_USUFRUCT
     *
     * @param ADVANCE_USUFRUCT the value for TRSSETLMT_EXTENDED.ADVANCE_USUFRUCT
     */
    public void setADVANCE_USUFRUCT(BigDecimal ADVANCE_USUFRUCT) {
        this.ADVANCE_USUFRUCT = ADVANCE_USUFRUCT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSSETLMT_EXTENDED.REIMBURSE_ADVANCE_USUFRUCT
     *
     * @return the value of TRSSETLMT_EXTENDED.REIMBURSE_ADVANCE_USUFRUCT
     */
    public BigDecimal getREIMBURSE_ADVANCE_USUFRUCT() {
        return REIMBURSE_ADVANCE_USUFRUCT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSSETLMT_EXTENDED.REIMBURSE_ADVANCE_USUFRUCT
     *
     * @param REIMBURSE_ADVANCE_USUFRUCT the value for TRSSETLMT_EXTENDED.REIMBURSE_ADVANCE_USUFRUCT
     */
    public void setREIMBURSE_ADVANCE_USUFRUCT(BigDecimal REIMBURSE_ADVANCE_USUFRUCT) {
        this.REIMBURSE_ADVANCE_USUFRUCT = REIMBURSE_ADVANCE_USUFRUCT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSSETLMT_EXTENDED.COLLECTED_INSURANCE_CHARGES
     *
     * @return the value of TRSSETLMT_EXTENDED.COLLECTED_INSURANCE_CHARGES
     */
    public BigDecimal getCOLLECTED_INSURANCE_CHARGES() {
        return COLLECTED_INSURANCE_CHARGES;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSSETLMT_EXTENDED.COLLECTED_INSURANCE_CHARGES
     *
     * @param COLLECTED_INSURANCE_CHARGES the value for TRSSETLMT_EXTENDED.COLLECTED_INSURANCE_CHARGES
     */
    public void setCOLLECTED_INSURANCE_CHARGES(BigDecimal COLLECTED_INSURANCE_CHARGES) {
        this.COLLECTED_INSURANCE_CHARGES = COLLECTED_INSURANCE_CHARGES;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSSETLMT_EXTENDED.SECURITY_DEPOSIT
     *
     * @return the value of TRSSETLMT_EXTENDED.SECURITY_DEPOSIT
     */
    public BigDecimal getSECURITY_DEPOSIT() {
        return SECURITY_DEPOSIT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSSETLMT_EXTENDED.SECURITY_DEPOSIT
     *
     * @param SECURITY_DEPOSIT the value for TRSSETLMT_EXTENDED.SECURITY_DEPOSIT
     */
    public void setSECURITY_DEPOSIT(BigDecimal SECURITY_DEPOSIT) {
        this.SECURITY_DEPOSIT = SECURITY_DEPOSIT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSSETLMT_EXTENDED.OUTSTANDING_INSURANCE_CHARGES
     *
     * @return the value of TRSSETLMT_EXTENDED.OUTSTANDING_INSURANCE_CHARGES
     */
    public BigDecimal getOUTSTANDING_INSURANCE_CHARGES() {
        return OUTSTANDING_INSURANCE_CHARGES;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSSETLMT_EXTENDED.OUTSTANDING_INSURANCE_CHARGES
     *
     * @param OUTSTANDING_INSURANCE_CHARGES the value for TRSSETLMT_EXTENDED.OUTSTANDING_INSURANCE_CHARGES
     */
    public void setOUTSTANDING_INSURANCE_CHARGES(BigDecimal OUTSTANDING_INSURANCE_CHARGES) {
        this.OUTSTANDING_INSURANCE_CHARGES = OUTSTANDING_INSURANCE_CHARGES;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSSETLMT_EXTENDED.ASSET_MATURITY_ACTION
     *
     * @return the value of TRSSETLMT_EXTENDED.ASSET_MATURITY_ACTION
     */
    public String getASSET_MATURITY_ACTION() {
        return ASSET_MATURITY_ACTION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSSETLMT_EXTENDED.ASSET_MATURITY_ACTION
     *
     * @param ASSET_MATURITY_ACTION the value for TRSSETLMT_EXTENDED.ASSET_MATURITY_ACTION
     */
    public void setASSET_MATURITY_ACTION(String ASSET_MATURITY_ACTION) {
        this.ASSET_MATURITY_ACTION = ASSET_MATURITY_ACTION == null ? null : ASSET_MATURITY_ACTION.trim();
    }
}