package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class TRSSETLMTPROCESSVO extends TRSSETLMTPROCESSVOKey {
    /**
     * This field corresponds to the database column TRSSETLMTPROCESS.PROCESS_DATE
     */
    private Date PROCESS_DATE;

    /**
     * This field corresponds to the database column TRSSETLMTPROCESS.PROCESSED_BY
     */
    private String PROCESSED_BY;

    /**
     * This field corresponds to the database column TRSSETLMTPROCESS.SERVER_DATE_START
     */
    private Date SERVER_DATE_START;

    /**
     * This field corresponds to the database column TRSSETLMTPROCESS.SERVER_DATE_END
     */
    private Date SERVER_DATE_END;

    /**
     * This field corresponds to the database column TRSSETLMTPROCESS.CIF_NO
     */
    private BigDecimal CIF_NO;

    /**
     * This field corresponds to the database column TRSSETLMTPROCESS.CALL_TYPE
     */
    private BigDecimal CALL_TYPE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSSETLMTPROCESS.PROCESS_DATE
     *
     * @return the value of TRSSETLMTPROCESS.PROCESS_DATE
     */
    public Date getPROCESS_DATE() {
        return PROCESS_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSSETLMTPROCESS.PROCESS_DATE
     *
     * @param PROCESS_DATE the value for TRSSETLMTPROCESS.PROCESS_DATE
     */
    public void setPROCESS_DATE(Date PROCESS_DATE) {
        this.PROCESS_DATE = PROCESS_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSSETLMTPROCESS.PROCESSED_BY
     *
     * @return the value of TRSSETLMTPROCESS.PROCESSED_BY
     */
    public String getPROCESSED_BY() {
        return PROCESSED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSSETLMTPROCESS.PROCESSED_BY
     *
     * @param PROCESSED_BY the value for TRSSETLMTPROCESS.PROCESSED_BY
     */
    public void setPROCESSED_BY(String PROCESSED_BY) {
        this.PROCESSED_BY = PROCESSED_BY == null ? null : PROCESSED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSSETLMTPROCESS.SERVER_DATE_START
     *
     * @return the value of TRSSETLMTPROCESS.SERVER_DATE_START
     */
    public Date getSERVER_DATE_START() {
        return SERVER_DATE_START;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSSETLMTPROCESS.SERVER_DATE_START
     *
     * @param SERVER_DATE_START the value for TRSSETLMTPROCESS.SERVER_DATE_START
     */
    public void setSERVER_DATE_START(Date SERVER_DATE_START) {
        this.SERVER_DATE_START = SERVER_DATE_START;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSSETLMTPROCESS.SERVER_DATE_END
     *
     * @return the value of TRSSETLMTPROCESS.SERVER_DATE_END
     */
    public Date getSERVER_DATE_END() {
        return SERVER_DATE_END;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSSETLMTPROCESS.SERVER_DATE_END
     *
     * @param SERVER_DATE_END the value for TRSSETLMTPROCESS.SERVER_DATE_END
     */
    public void setSERVER_DATE_END(Date SERVER_DATE_END) {
        this.SERVER_DATE_END = SERVER_DATE_END;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSSETLMTPROCESS.CIF_NO
     *
     * @return the value of TRSSETLMTPROCESS.CIF_NO
     */
    public BigDecimal getCIF_NO() {
        return CIF_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSSETLMTPROCESS.CIF_NO
     *
     * @param CIF_NO the value for TRSSETLMTPROCESS.CIF_NO
     */
    public void setCIF_NO(BigDecimal CIF_NO) {
        this.CIF_NO = CIF_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSSETLMTPROCESS.CALL_TYPE
     *
     * @return the value of TRSSETLMTPROCESS.CALL_TYPE
     */
    public BigDecimal getCALL_TYPE() {
        return CALL_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSSETLMTPROCESS.CALL_TYPE
     *
     * @param CALL_TYPE the value for TRSSETLMTPROCESS.CALL_TYPE
     */
    public void setCALL_TYPE(BigDecimal CALL_TYPE) {
        this.CALL_TYPE = CALL_TYPE;
    }
}