package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;
import java.util.Date;

public class TRSSETLMTBLOCKINGVOKey extends BaseVO {
    /**
     * This field corresponds to the database column TRSSETLMTBLOCKING.ACTION_TYPE
     */
    private String ACTION_TYPE;

    /**
     * This field corresponds to the database column TRSSETLMTBLOCKING.BRANCH_CODE
     */
    private BigDecimal BRANCH_CODE;

    /**
     * This field corresponds to the database column TRSSETLMTBLOCKING.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column TRSSETLMTBLOCKING.COUNTER_PARTY
     */
    private BigDecimal COUNTER_PARTY;

    /**
     * This field corresponds to the database column TRSSETLMTBLOCKING.DEAL_NO
     */
    private BigDecimal DEAL_NO;

    /**
     * This field corresponds to the database column TRSSETLMTBLOCKING.INSTALLMENT_DATE
     */
    private Date INSTALLMENT_DATE;

    /**
     * This field corresponds to the database column TRSSETLMTBLOCKING.PLAN_NBR
     */
    private BigDecimal PLAN_NBR;

    /**
     * This field corresponds to the database column TRSSETLMTBLOCKING.PLAN_SEQ
     */
    private BigDecimal PLAN_SEQ;

    /**
     * This field corresponds to the database column TRSSETLMTBLOCKING.PROCESS_CODE
     */
    private BigDecimal PROCESS_CODE;

    /**
     * This field corresponds to the database column TRSSETLMTBLOCKING.PROCESS_DATE
     */
    private Date PROCESS_DATE;

    /**
     * This field corresponds to the database column TRSSETLMTBLOCKING.TRIAL_NBR
     */
    private BigDecimal TRIAL_NBR;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSSETLMTBLOCKING.ACTION_TYPE
     *
     * @return the value of TRSSETLMTBLOCKING.ACTION_TYPE
     */
    public String getACTION_TYPE() {
        return ACTION_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSSETLMTBLOCKING.ACTION_TYPE
     *
     * @param ACTION_TYPE the value for TRSSETLMTBLOCKING.ACTION_TYPE
     */
    public void setACTION_TYPE(String ACTION_TYPE) {
        this.ACTION_TYPE = ACTION_TYPE == null ? null : ACTION_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSSETLMTBLOCKING.BRANCH_CODE
     *
     * @return the value of TRSSETLMTBLOCKING.BRANCH_CODE
     */
    public BigDecimal getBRANCH_CODE() {
        return BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSSETLMTBLOCKING.BRANCH_CODE
     *
     * @param BRANCH_CODE the value for TRSSETLMTBLOCKING.BRANCH_CODE
     */
    public void setBRANCH_CODE(BigDecimal BRANCH_CODE) {
        this.BRANCH_CODE = BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSSETLMTBLOCKING.COMP_CODE
     *
     * @return the value of TRSSETLMTBLOCKING.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSSETLMTBLOCKING.COMP_CODE
     *
     * @param COMP_CODE the value for TRSSETLMTBLOCKING.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSSETLMTBLOCKING.COUNTER_PARTY
     *
     * @return the value of TRSSETLMTBLOCKING.COUNTER_PARTY
     */
    public BigDecimal getCOUNTER_PARTY() {
        return COUNTER_PARTY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSSETLMTBLOCKING.COUNTER_PARTY
     *
     * @param COUNTER_PARTY the value for TRSSETLMTBLOCKING.COUNTER_PARTY
     */
    public void setCOUNTER_PARTY(BigDecimal COUNTER_PARTY) {
        this.COUNTER_PARTY = COUNTER_PARTY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSSETLMTBLOCKING.DEAL_NO
     *
     * @return the value of TRSSETLMTBLOCKING.DEAL_NO
     */
    public BigDecimal getDEAL_NO() {
        return DEAL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSSETLMTBLOCKING.DEAL_NO
     *
     * @param DEAL_NO the value for TRSSETLMTBLOCKING.DEAL_NO
     */
    public void setDEAL_NO(BigDecimal DEAL_NO) {
        this.DEAL_NO = DEAL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSSETLMTBLOCKING.INSTALLMENT_DATE
     *
     * @return the value of TRSSETLMTBLOCKING.INSTALLMENT_DATE
     */
    public Date getINSTALLMENT_DATE() {
        return INSTALLMENT_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSSETLMTBLOCKING.INSTALLMENT_DATE
     *
     * @param INSTALLMENT_DATE the value for TRSSETLMTBLOCKING.INSTALLMENT_DATE
     */
    public void setINSTALLMENT_DATE(Date INSTALLMENT_DATE) {
        this.INSTALLMENT_DATE = INSTALLMENT_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSSETLMTBLOCKING.PLAN_NBR
     *
     * @return the value of TRSSETLMTBLOCKING.PLAN_NBR
     */
    public BigDecimal getPLAN_NBR() {
        return PLAN_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSSETLMTBLOCKING.PLAN_NBR
     *
     * @param PLAN_NBR the value for TRSSETLMTBLOCKING.PLAN_NBR
     */
    public void setPLAN_NBR(BigDecimal PLAN_NBR) {
        this.PLAN_NBR = PLAN_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSSETLMTBLOCKING.PLAN_SEQ
     *
     * @return the value of TRSSETLMTBLOCKING.PLAN_SEQ
     */
    public BigDecimal getPLAN_SEQ() {
        return PLAN_SEQ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSSETLMTBLOCKING.PLAN_SEQ
     *
     * @param PLAN_SEQ the value for TRSSETLMTBLOCKING.PLAN_SEQ
     */
    public void setPLAN_SEQ(BigDecimal PLAN_SEQ) {
        this.PLAN_SEQ = PLAN_SEQ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSSETLMTBLOCKING.PROCESS_CODE
     *
     * @return the value of TRSSETLMTBLOCKING.PROCESS_CODE
     */
    public BigDecimal getPROCESS_CODE() {
        return PROCESS_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSSETLMTBLOCKING.PROCESS_CODE
     *
     * @param PROCESS_CODE the value for TRSSETLMTBLOCKING.PROCESS_CODE
     */
    public void setPROCESS_CODE(BigDecimal PROCESS_CODE) {
        this.PROCESS_CODE = PROCESS_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSSETLMTBLOCKING.PROCESS_DATE
     *
     * @return the value of TRSSETLMTBLOCKING.PROCESS_DATE
     */
    public Date getPROCESS_DATE() {
        return PROCESS_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSSETLMTBLOCKING.PROCESS_DATE
     *
     * @param PROCESS_DATE the value for TRSSETLMTBLOCKING.PROCESS_DATE
     */
    public void setPROCESS_DATE(Date PROCESS_DATE) {
        this.PROCESS_DATE = PROCESS_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSSETLMTBLOCKING.TRIAL_NBR
     *
     * @return the value of TRSSETLMTBLOCKING.TRIAL_NBR
     */
    public BigDecimal getTRIAL_NBR() {
        return TRIAL_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSSETLMTBLOCKING.TRIAL_NBR
     *
     * @param TRIAL_NBR the value for TRSSETLMTBLOCKING.TRIAL_NBR
     */
    public void setTRIAL_NBR(BigDecimal TRIAL_NBR) {
        this.TRIAL_NBR = TRIAL_NBR;
    }
}