package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class TRSSETLROUNDVO extends BaseVO {
    /**
     * This field corresponds to the database column TRSSETLROUND.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column TRSSETLROUND.BRANCH
     */
    private BigDecimal BRANCH;

    /**
     * This field corresponds to the database column TRSSETLROUND.TRX_TYPE
     */
    private String TRX_TYPE;

    /**
     * This field corresponds to the database column TRSSETLROUND.TRX_NBR
     */
    private BigDecimal TRX_NBR;

    /**
     * This field corresponds to the database column TRSSETLROUND.TRX_LINE
     */
    private BigDecimal TRX_LINE;

    /**
     * This field corresponds to the database column TRSSETLROUND.ACC_REFERENCE
     */
    private String ACC_REFERENCE;

    /**
     * This field corresponds to the database column TRSSETLROUND.TRX_SIGN
     */
    private String TRX_SIGN;

    /**
     * This field corresponds to the database column TRSSETLROUND.BS_CONTRA
     */
    private String BS_CONTRA;

    /**
     * This field corresponds to the database column TRSSETLROUND.ACC_CY
     */
    private BigDecimal ACC_CY;

    /**
     * This field corresponds to the database column TRSSETLROUND.ACC_GL
     */
    private BigDecimal ACC_GL;

    /**
     * This field corresponds to the database column TRSSETLROUND.ACC_CIF
     */
    private BigDecimal ACC_CIF;

    /**
     * This field corresponds to the database column TRSSETLROUND.ACC_SL
     */
    private BigDecimal ACC_SL;

    /**
     * This field corresponds to the database column TRSSETLROUND.ACTUAL_TOTAL
     */
    private BigDecimal ACTUAL_TOTAL;

    /**
     * This field corresponds to the database column TRSSETLROUND.EXPECTED_TOTAL
     */
    private BigDecimal EXPECTED_TOTAL;

    /**
     * This field corresponds to the database column TRSSETLROUND.LINE_NBR
     */
    private BigDecimal LINE_NBR;

    /**
     * This field corresponds to the database column TRSSETLROUND.ACTUAL_TOTAL_CV
     */
    private BigDecimal ACTUAL_TOTAL_CV;

    /**
     * This field corresponds to the database column TRSSETLROUND.EXPECTED_TOTAL_CV
     */
    private BigDecimal EXPECTED_TOTAL_CV;

    /**
     * This field corresponds to the database column TRSSETLROUND.BEFORE_REMAINING
     */
    private BigDecimal BEFORE_REMAINING;

    /**
     * This field corresponds to the database column TRSSETLROUND.BEFORE_REMAINING_CV
     */
    private BigDecimal BEFORE_REMAINING_CV;

    /**
     * This field corresponds to the database column TRSSETLROUND.ACTUAL_TOTAL_2
     */
    private BigDecimal ACTUAL_TOTAL_2;

    /**
     * This field corresponds to the database column TRSSETLROUND.ACTUAL_TOTAL_CV_2
     */
    private BigDecimal ACTUAL_TOTAL_CV_2;

    /**
     * This field corresponds to the database column TRSSETLROUND.TRSDET_LINE_NO
     */
    private BigDecimal TRSDET_LINE_NO;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSSETLROUND.COMP_CODE
     *
     * @return the value of TRSSETLROUND.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSSETLROUND.COMP_CODE
     *
     * @param COMP_CODE the value for TRSSETLROUND.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSSETLROUND.BRANCH
     *
     * @return the value of TRSSETLROUND.BRANCH
     */
    public BigDecimal getBRANCH() {
        return BRANCH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSSETLROUND.BRANCH
     *
     * @param BRANCH the value for TRSSETLROUND.BRANCH
     */
    public void setBRANCH(BigDecimal BRANCH) {
        this.BRANCH = BRANCH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSSETLROUND.TRX_TYPE
     *
     * @return the value of TRSSETLROUND.TRX_TYPE
     */
    public String getTRX_TYPE() {
        return TRX_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSSETLROUND.TRX_TYPE
     *
     * @param TRX_TYPE the value for TRSSETLROUND.TRX_TYPE
     */
    public void setTRX_TYPE(String TRX_TYPE) {
        this.TRX_TYPE = TRX_TYPE == null ? null : TRX_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSSETLROUND.TRX_NBR
     *
     * @return the value of TRSSETLROUND.TRX_NBR
     */
    public BigDecimal getTRX_NBR() {
        return TRX_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSSETLROUND.TRX_NBR
     *
     * @param TRX_NBR the value for TRSSETLROUND.TRX_NBR
     */
    public void setTRX_NBR(BigDecimal TRX_NBR) {
        this.TRX_NBR = TRX_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSSETLROUND.TRX_LINE
     *
     * @return the value of TRSSETLROUND.TRX_LINE
     */
    public BigDecimal getTRX_LINE() {
        return TRX_LINE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSSETLROUND.TRX_LINE
     *
     * @param TRX_LINE the value for TRSSETLROUND.TRX_LINE
     */
    public void setTRX_LINE(BigDecimal TRX_LINE) {
        this.TRX_LINE = TRX_LINE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSSETLROUND.ACC_REFERENCE
     *
     * @return the value of TRSSETLROUND.ACC_REFERENCE
     */
    public String getACC_REFERENCE() {
        return ACC_REFERENCE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSSETLROUND.ACC_REFERENCE
     *
     * @param ACC_REFERENCE the value for TRSSETLROUND.ACC_REFERENCE
     */
    public void setACC_REFERENCE(String ACC_REFERENCE) {
        this.ACC_REFERENCE = ACC_REFERENCE == null ? null : ACC_REFERENCE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSSETLROUND.TRX_SIGN
     *
     * @return the value of TRSSETLROUND.TRX_SIGN
     */
    public String getTRX_SIGN() {
        return TRX_SIGN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSSETLROUND.TRX_SIGN
     *
     * @param TRX_SIGN the value for TRSSETLROUND.TRX_SIGN
     */
    public void setTRX_SIGN(String TRX_SIGN) {
        this.TRX_SIGN = TRX_SIGN == null ? null : TRX_SIGN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSSETLROUND.BS_CONTRA
     *
     * @return the value of TRSSETLROUND.BS_CONTRA
     */
    public String getBS_CONTRA() {
        return BS_CONTRA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSSETLROUND.BS_CONTRA
     *
     * @param BS_CONTRA the value for TRSSETLROUND.BS_CONTRA
     */
    public void setBS_CONTRA(String BS_CONTRA) {
        this.BS_CONTRA = BS_CONTRA == null ? null : BS_CONTRA.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSSETLROUND.ACC_CY
     *
     * @return the value of TRSSETLROUND.ACC_CY
     */
    public BigDecimal getACC_CY() {
        return ACC_CY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSSETLROUND.ACC_CY
     *
     * @param ACC_CY the value for TRSSETLROUND.ACC_CY
     */
    public void setACC_CY(BigDecimal ACC_CY) {
        this.ACC_CY = ACC_CY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSSETLROUND.ACC_GL
     *
     * @return the value of TRSSETLROUND.ACC_GL
     */
    public BigDecimal getACC_GL() {
        return ACC_GL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSSETLROUND.ACC_GL
     *
     * @param ACC_GL the value for TRSSETLROUND.ACC_GL
     */
    public void setACC_GL(BigDecimal ACC_GL) {
        this.ACC_GL = ACC_GL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSSETLROUND.ACC_CIF
     *
     * @return the value of TRSSETLROUND.ACC_CIF
     */
    public BigDecimal getACC_CIF() {
        return ACC_CIF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSSETLROUND.ACC_CIF
     *
     * @param ACC_CIF the value for TRSSETLROUND.ACC_CIF
     */
    public void setACC_CIF(BigDecimal ACC_CIF) {
        this.ACC_CIF = ACC_CIF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSSETLROUND.ACC_SL
     *
     * @return the value of TRSSETLROUND.ACC_SL
     */
    public BigDecimal getACC_SL() {
        return ACC_SL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSSETLROUND.ACC_SL
     *
     * @param ACC_SL the value for TRSSETLROUND.ACC_SL
     */
    public void setACC_SL(BigDecimal ACC_SL) {
        this.ACC_SL = ACC_SL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSSETLROUND.ACTUAL_TOTAL
     *
     * @return the value of TRSSETLROUND.ACTUAL_TOTAL
     */
    public BigDecimal getACTUAL_TOTAL() {
        return ACTUAL_TOTAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSSETLROUND.ACTUAL_TOTAL
     *
     * @param ACTUAL_TOTAL the value for TRSSETLROUND.ACTUAL_TOTAL
     */
    public void setACTUAL_TOTAL(BigDecimal ACTUAL_TOTAL) {
        this.ACTUAL_TOTAL = ACTUAL_TOTAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSSETLROUND.EXPECTED_TOTAL
     *
     * @return the value of TRSSETLROUND.EXPECTED_TOTAL
     */
    public BigDecimal getEXPECTED_TOTAL() {
        return EXPECTED_TOTAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSSETLROUND.EXPECTED_TOTAL
     *
     * @param EXPECTED_TOTAL the value for TRSSETLROUND.EXPECTED_TOTAL
     */
    public void setEXPECTED_TOTAL(BigDecimal EXPECTED_TOTAL) {
        this.EXPECTED_TOTAL = EXPECTED_TOTAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSSETLROUND.LINE_NBR
     *
     * @return the value of TRSSETLROUND.LINE_NBR
     */
    public BigDecimal getLINE_NBR() {
        return LINE_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSSETLROUND.LINE_NBR
     *
     * @param LINE_NBR the value for TRSSETLROUND.LINE_NBR
     */
    public void setLINE_NBR(BigDecimal LINE_NBR) {
        this.LINE_NBR = LINE_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSSETLROUND.ACTUAL_TOTAL_CV
     *
     * @return the value of TRSSETLROUND.ACTUAL_TOTAL_CV
     */
    public BigDecimal getACTUAL_TOTAL_CV() {
        return ACTUAL_TOTAL_CV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSSETLROUND.ACTUAL_TOTAL_CV
     *
     * @param ACTUAL_TOTAL_CV the value for TRSSETLROUND.ACTUAL_TOTAL_CV
     */
    public void setACTUAL_TOTAL_CV(BigDecimal ACTUAL_TOTAL_CV) {
        this.ACTUAL_TOTAL_CV = ACTUAL_TOTAL_CV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSSETLROUND.EXPECTED_TOTAL_CV
     *
     * @return the value of TRSSETLROUND.EXPECTED_TOTAL_CV
     */
    public BigDecimal getEXPECTED_TOTAL_CV() {
        return EXPECTED_TOTAL_CV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSSETLROUND.EXPECTED_TOTAL_CV
     *
     * @param EXPECTED_TOTAL_CV the value for TRSSETLROUND.EXPECTED_TOTAL_CV
     */
    public void setEXPECTED_TOTAL_CV(BigDecimal EXPECTED_TOTAL_CV) {
        this.EXPECTED_TOTAL_CV = EXPECTED_TOTAL_CV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSSETLROUND.BEFORE_REMAINING
     *
     * @return the value of TRSSETLROUND.BEFORE_REMAINING
     */
    public BigDecimal getBEFORE_REMAINING() {
        return BEFORE_REMAINING;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSSETLROUND.BEFORE_REMAINING
     *
     * @param BEFORE_REMAINING the value for TRSSETLROUND.BEFORE_REMAINING
     */
    public void setBEFORE_REMAINING(BigDecimal BEFORE_REMAINING) {
        this.BEFORE_REMAINING = BEFORE_REMAINING;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSSETLROUND.BEFORE_REMAINING_CV
     *
     * @return the value of TRSSETLROUND.BEFORE_REMAINING_CV
     */
    public BigDecimal getBEFORE_REMAINING_CV() {
        return BEFORE_REMAINING_CV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSSETLROUND.BEFORE_REMAINING_CV
     *
     * @param BEFORE_REMAINING_CV the value for TRSSETLROUND.BEFORE_REMAINING_CV
     */
    public void setBEFORE_REMAINING_CV(BigDecimal BEFORE_REMAINING_CV) {
        this.BEFORE_REMAINING_CV = BEFORE_REMAINING_CV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSSETLROUND.ACTUAL_TOTAL_2
     *
     * @return the value of TRSSETLROUND.ACTUAL_TOTAL_2
     */
    public BigDecimal getACTUAL_TOTAL_2() {
        return ACTUAL_TOTAL_2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSSETLROUND.ACTUAL_TOTAL_2
     *
     * @param ACTUAL_TOTAL_2 the value for TRSSETLROUND.ACTUAL_TOTAL_2
     */
    public void setACTUAL_TOTAL_2(BigDecimal ACTUAL_TOTAL_2) {
        this.ACTUAL_TOTAL_2 = ACTUAL_TOTAL_2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSSETLROUND.ACTUAL_TOTAL_CV_2
     *
     * @return the value of TRSSETLROUND.ACTUAL_TOTAL_CV_2
     */
    public BigDecimal getACTUAL_TOTAL_CV_2() {
        return ACTUAL_TOTAL_CV_2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSSETLROUND.ACTUAL_TOTAL_CV_2
     *
     * @param ACTUAL_TOTAL_CV_2 the value for TRSSETLROUND.ACTUAL_TOTAL_CV_2
     */
    public void setACTUAL_TOTAL_CV_2(BigDecimal ACTUAL_TOTAL_CV_2) {
        this.ACTUAL_TOTAL_CV_2 = ACTUAL_TOTAL_CV_2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSSETLROUND.TRSDET_LINE_NO
     *
     * @return the value of TRSSETLROUND.TRSDET_LINE_NO
     */
    public BigDecimal getTRSDET_LINE_NO() {
        return TRSDET_LINE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSSETLROUND.TRSDET_LINE_NO
     *
     * @param TRSDET_LINE_NO the value for TRSSETLROUND.TRSDET_LINE_NO
     */
    public void setTRSDET_LINE_NO(BigDecimal TRSDET_LINE_NO) {
        this.TRSDET_LINE_NO = TRSDET_LINE_NO;
    }
}