package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class TRSSETTLPOLICY_PRIORVOKey extends BaseVO {
    /**
     * This field corresponds to the database column TRSSETTLPOLICY_PRIOR.BRANCH_CODE
     */
    private BigDecimal BRANCH_CODE;

    /**
     * This field corresponds to the database column TRSSETTLPOLICY_PRIOR.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column TRSSETTLPOLICY_PRIOR.SP_NO
     */
    private BigDecimal SP_NO;

    /**
     * This field corresponds to the database column TRSSETTLPOLICY_PRIOR.SP_PRIORITY
     */
    private BigDecimal SP_PRIORITY;

    /**
     * This field corresponds to the database column TRSSETTLPOLICY_PRIOR.TYPE_PRIORITY
     */
    private String TYPE_PRIORITY;

    /**
     * This field corresponds to the database column TRSSETTLPOLICY_PRIOR.TYPE_SPEC
     */
    private String TYPE_SPEC;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSSETTLPOLICY_PRIOR.BRANCH_CODE
     *
     * @return the value of TRSSETTLPOLICY_PRIOR.BRANCH_CODE
     */
    public BigDecimal getBRANCH_CODE() {
        return BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSSETTLPOLICY_PRIOR.BRANCH_CODE
     *
     * @param BRANCH_CODE the value for TRSSETTLPOLICY_PRIOR.BRANCH_CODE
     */
    public void setBRANCH_CODE(BigDecimal BRANCH_CODE) {
        this.BRANCH_CODE = BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSSETTLPOLICY_PRIOR.COMP_CODE
     *
     * @return the value of TRSSETTLPOLICY_PRIOR.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSSETTLPOLICY_PRIOR.COMP_CODE
     *
     * @param COMP_CODE the value for TRSSETTLPOLICY_PRIOR.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSSETTLPOLICY_PRIOR.SP_NO
     *
     * @return the value of TRSSETTLPOLICY_PRIOR.SP_NO
     */
    public BigDecimal getSP_NO() {
        return SP_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSSETTLPOLICY_PRIOR.SP_NO
     *
     * @param SP_NO the value for TRSSETTLPOLICY_PRIOR.SP_NO
     */
    public void setSP_NO(BigDecimal SP_NO) {
        this.SP_NO = SP_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSSETTLPOLICY_PRIOR.SP_PRIORITY
     *
     * @return the value of TRSSETTLPOLICY_PRIOR.SP_PRIORITY
     */
    public BigDecimal getSP_PRIORITY() {
        return SP_PRIORITY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSSETTLPOLICY_PRIOR.SP_PRIORITY
     *
     * @param SP_PRIORITY the value for TRSSETTLPOLICY_PRIOR.SP_PRIORITY
     */
    public void setSP_PRIORITY(BigDecimal SP_PRIORITY) {
        this.SP_PRIORITY = SP_PRIORITY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSSETTLPOLICY_PRIOR.TYPE_PRIORITY
     *
     * @return the value of TRSSETTLPOLICY_PRIOR.TYPE_PRIORITY
     */
    public String getTYPE_PRIORITY() {
        return TYPE_PRIORITY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSSETTLPOLICY_PRIOR.TYPE_PRIORITY
     *
     * @param TYPE_PRIORITY the value for TRSSETTLPOLICY_PRIOR.TYPE_PRIORITY
     */
    public void setTYPE_PRIORITY(String TYPE_PRIORITY) {
        this.TYPE_PRIORITY = TYPE_PRIORITY == null ? null : TYPE_PRIORITY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSSETTLPOLICY_PRIOR.TYPE_SPEC
     *
     * @return the value of TRSSETTLPOLICY_PRIOR.TYPE_SPEC
     */
    public String getTYPE_SPEC() {
        return TYPE_SPEC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSSETTLPOLICY_PRIOR.TYPE_SPEC
     *
     * @param TYPE_SPEC the value for TRSSETTLPOLICY_PRIOR.TYPE_SPEC
     */
    public void setTYPE_SPEC(String TYPE_SPEC) {
        this.TYPE_SPEC = TYPE_SPEC == null ? null : TYPE_SPEC.trim();
    }
}