package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class TRSTRACKVO extends TRSTRACKVOKey {
    /**
     * This field corresponds to the database column TRSTRACK.CLASS
     */
    private BigDecimal CLASS;

    /**
     * This field corresponds to the database column TRSTRACK.CATEGORY
     */
    private BigDecimal CATEGORY;

    /**
     * This field corresponds to the database column TRSTRACK.TRS_DEAL_SERIAL_NO
     */
    private BigDecimal TRS_DEAL_SERIAL_NO;

    /**
     * This field corresponds to the database column TRSTRACK.TOTAL_EXPENSE
     */
    private BigDecimal TOTAL_EXPENSE;

    /**
     * This field corresponds to the database column TRSTRACK.TOTAL_REVENUE
     */
    private BigDecimal TOTAL_REVENUE;

    /**
     * This field corresponds to the database column TRSTRACK.TOTAL_PAYMENT
     */
    private BigDecimal TOTAL_PAYMENT;

    /**
     * This field corresponds to the database column TRSTRACK.STATUS
     */
    private String STATUS;

    /**
     * This field corresponds to the database column TRSTRACK.TRACK_DATE
     */
    private Date TRACK_DATE;

    /**
     * This field corresponds to the database column TRSTRACK.CREATED_BY
     */
    private String CREATED_BY;

    /**
     * This field corresponds to the database column TRSTRACK.APPROVED_BY
     */
    private String APPROVED_BY;

    /**
     * This field corresponds to the database column TRSTRACK.REVERSED_BY
     */
    private String REVERSED_BY;

    /**
     * This field corresponds to the database column TRSTRACK.DELETED_BY
     */
    private String DELETED_BY;

    /**
     * This field corresponds to the database column TRSTRACK.DATE_DELETED
     */
    private Date DATE_DELETED;

    /**
     * This field corresponds to the database column TRSTRACK.DATE_APPROVED
     */
    private Date DATE_APPROVED;

    /**
     * This field corresponds to the database column TRSTRACK.DATE_REVERSED
     */
    private Date DATE_REVERSED;

    /**
     * This field corresponds to the database column TRSTRACK.MODIFIED_BY
     */
    private String MODIFIED_BY;

    /**
     * This field corresponds to the database column TRSTRACK.DATE_MODIFIED
     */
    private Date DATE_MODIFIED;

    /**
     * This field corresponds to the database column TRSTRACK.SERVER_CREATED_DATE
     */
    private Date SERVER_CREATED_DATE;

    /**
     * This field corresponds to the database column TRSTRACK.SERVER_APPROVED_DATE
     */
    private Date SERVER_APPROVED_DATE;

    /**
     * This field corresponds to the database column TRSTRACK.SERVER_REVERSED_DATE
     */
    private Date SERVER_REVERSED_DATE;

    /**
     * This field corresponds to the database column TRSTRACK.TRACK_TYPE
     */
    private String TRACK_TYPE;

    /**
     * This field corresponds to the database column TRSTRACK.REVERSAL_STATUS
     */
    private String REVERSAL_STATUS;

    /**
     * This field corresponds to the database column TRSTRACK.REVERSAL_CREATED_BY
     */
    private String REVERSAL_CREATED_BY;

    /**
     * This field corresponds to the database column TRSTRACK.REVERSAL_CREATED_DATE
     */
    private Date REVERSAL_CREATED_DATE;

    /**
     * This field corresponds to the database column TRSTRACK.SERVER_REVERSAL_CREATED_DATE
     */
    private Date SERVER_REVERSAL_CREATED_DATE;

    /**
     * This field corresponds to the database column TRSTRACK.REVERSAL_DELETED_BY
     */
    private String REVERSAL_DELETED_BY;

    /**
     * This field corresponds to the database column TRSTRACK.REVERSAL_DELETED_DATE
     */
    private Date REVERSAL_DELETED_DATE;

    /**
     * This field corresponds to the database column TRSTRACK.SERVER_REVERSAL_DELETED_DATE
     */
    private Date SERVER_REVERSAL_DELETED_DATE;

    /**
     * This field corresponds to the database column TRSTRACK.DATE_UPDATED
     */
    private Date DATE_UPDATED;

    /**
     * This field corresponds to the database column TRSTRACK.MUSHARAKA_PROFIT
     */
    private BigDecimal MUSHARAKA_PROFIT;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSTRACK.CLASS
     *
     * @return the value of TRSTRACK.CLASS
     */
    public BigDecimal getCLASS() {
        return CLASS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSTRACK.CLASS
     *
     * @param CLASS the value for TRSTRACK.CLASS
     */
    public void setCLASS(BigDecimal CLASS) {
        this.CLASS = CLASS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSTRACK.CATEGORY
     *
     * @return the value of TRSTRACK.CATEGORY
     */
    public BigDecimal getCATEGORY() {
        return CATEGORY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSTRACK.CATEGORY
     *
     * @param CATEGORY the value for TRSTRACK.CATEGORY
     */
    public void setCATEGORY(BigDecimal CATEGORY) {
        this.CATEGORY = CATEGORY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSTRACK.TRS_DEAL_SERIAL_NO
     *
     * @return the value of TRSTRACK.TRS_DEAL_SERIAL_NO
     */
    public BigDecimal getTRS_DEAL_SERIAL_NO() {
        return TRS_DEAL_SERIAL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSTRACK.TRS_DEAL_SERIAL_NO
     *
     * @param TRS_DEAL_SERIAL_NO the value for TRSTRACK.TRS_DEAL_SERIAL_NO
     */
    public void setTRS_DEAL_SERIAL_NO(BigDecimal TRS_DEAL_SERIAL_NO) {
        this.TRS_DEAL_SERIAL_NO = TRS_DEAL_SERIAL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSTRACK.TOTAL_EXPENSE
     *
     * @return the value of TRSTRACK.TOTAL_EXPENSE
     */
    public BigDecimal getTOTAL_EXPENSE() {
        return TOTAL_EXPENSE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSTRACK.TOTAL_EXPENSE
     *
     * @param TOTAL_EXPENSE the value for TRSTRACK.TOTAL_EXPENSE
     */
    public void setTOTAL_EXPENSE(BigDecimal TOTAL_EXPENSE) {
        this.TOTAL_EXPENSE = TOTAL_EXPENSE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSTRACK.TOTAL_REVENUE
     *
     * @return the value of TRSTRACK.TOTAL_REVENUE
     */
    public BigDecimal getTOTAL_REVENUE() {
        return TOTAL_REVENUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSTRACK.TOTAL_REVENUE
     *
     * @param TOTAL_REVENUE the value for TRSTRACK.TOTAL_REVENUE
     */
    public void setTOTAL_REVENUE(BigDecimal TOTAL_REVENUE) {
        this.TOTAL_REVENUE = TOTAL_REVENUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSTRACK.TOTAL_PAYMENT
     *
     * @return the value of TRSTRACK.TOTAL_PAYMENT
     */
    public BigDecimal getTOTAL_PAYMENT() {
        return TOTAL_PAYMENT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSTRACK.TOTAL_PAYMENT
     *
     * @param TOTAL_PAYMENT the value for TRSTRACK.TOTAL_PAYMENT
     */
    public void setTOTAL_PAYMENT(BigDecimal TOTAL_PAYMENT) {
        this.TOTAL_PAYMENT = TOTAL_PAYMENT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSTRACK.STATUS
     *
     * @return the value of TRSTRACK.STATUS
     */
    public String getSTATUS() {
        return STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSTRACK.STATUS
     *
     * @param STATUS the value for TRSTRACK.STATUS
     */
    public void setSTATUS(String STATUS) {
        this.STATUS = STATUS == null ? null : STATUS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSTRACK.TRACK_DATE
     *
     * @return the value of TRSTRACK.TRACK_DATE
     */
    public Date getTRACK_DATE() {
        return TRACK_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSTRACK.TRACK_DATE
     *
     * @param TRACK_DATE the value for TRSTRACK.TRACK_DATE
     */
    public void setTRACK_DATE(Date TRACK_DATE) {
        this.TRACK_DATE = TRACK_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSTRACK.CREATED_BY
     *
     * @return the value of TRSTRACK.CREATED_BY
     */
    public String getCREATED_BY() {
        return CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSTRACK.CREATED_BY
     *
     * @param CREATED_BY the value for TRSTRACK.CREATED_BY
     */
    public void setCREATED_BY(String CREATED_BY) {
        this.CREATED_BY = CREATED_BY == null ? null : CREATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSTRACK.APPROVED_BY
     *
     * @return the value of TRSTRACK.APPROVED_BY
     */
    public String getAPPROVED_BY() {
        return APPROVED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSTRACK.APPROVED_BY
     *
     * @param APPROVED_BY the value for TRSTRACK.APPROVED_BY
     */
    public void setAPPROVED_BY(String APPROVED_BY) {
        this.APPROVED_BY = APPROVED_BY == null ? null : APPROVED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSTRACK.REVERSED_BY
     *
     * @return the value of TRSTRACK.REVERSED_BY
     */
    public String getREVERSED_BY() {
        return REVERSED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSTRACK.REVERSED_BY
     *
     * @param REVERSED_BY the value for TRSTRACK.REVERSED_BY
     */
    public void setREVERSED_BY(String REVERSED_BY) {
        this.REVERSED_BY = REVERSED_BY == null ? null : REVERSED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSTRACK.DELETED_BY
     *
     * @return the value of TRSTRACK.DELETED_BY
     */
    public String getDELETED_BY() {
        return DELETED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSTRACK.DELETED_BY
     *
     * @param DELETED_BY the value for TRSTRACK.DELETED_BY
     */
    public void setDELETED_BY(String DELETED_BY) {
        this.DELETED_BY = DELETED_BY == null ? null : DELETED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSTRACK.DATE_DELETED
     *
     * @return the value of TRSTRACK.DATE_DELETED
     */
    public Date getDATE_DELETED() {
        return DATE_DELETED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSTRACK.DATE_DELETED
     *
     * @param DATE_DELETED the value for TRSTRACK.DATE_DELETED
     */
    public void setDATE_DELETED(Date DATE_DELETED) {
        this.DATE_DELETED = DATE_DELETED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSTRACK.DATE_APPROVED
     *
     * @return the value of TRSTRACK.DATE_APPROVED
     */
    public Date getDATE_APPROVED() {
        return DATE_APPROVED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSTRACK.DATE_APPROVED
     *
     * @param DATE_APPROVED the value for TRSTRACK.DATE_APPROVED
     */
    public void setDATE_APPROVED(Date DATE_APPROVED) {
        this.DATE_APPROVED = DATE_APPROVED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSTRACK.DATE_REVERSED
     *
     * @return the value of TRSTRACK.DATE_REVERSED
     */
    public Date getDATE_REVERSED() {
        return DATE_REVERSED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSTRACK.DATE_REVERSED
     *
     * @param DATE_REVERSED the value for TRSTRACK.DATE_REVERSED
     */
    public void setDATE_REVERSED(Date DATE_REVERSED) {
        this.DATE_REVERSED = DATE_REVERSED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSTRACK.MODIFIED_BY
     *
     * @return the value of TRSTRACK.MODIFIED_BY
     */
    public String getMODIFIED_BY() {
        return MODIFIED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSTRACK.MODIFIED_BY
     *
     * @param MODIFIED_BY the value for TRSTRACK.MODIFIED_BY
     */
    public void setMODIFIED_BY(String MODIFIED_BY) {
        this.MODIFIED_BY = MODIFIED_BY == null ? null : MODIFIED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSTRACK.DATE_MODIFIED
     *
     * @return the value of TRSTRACK.DATE_MODIFIED
     */
    public Date getDATE_MODIFIED() {
        return DATE_MODIFIED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSTRACK.DATE_MODIFIED
     *
     * @param DATE_MODIFIED the value for TRSTRACK.DATE_MODIFIED
     */
    public void setDATE_MODIFIED(Date DATE_MODIFIED) {
        this.DATE_MODIFIED = DATE_MODIFIED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSTRACK.SERVER_CREATED_DATE
     *
     * @return the value of TRSTRACK.SERVER_CREATED_DATE
     */
    public Date getSERVER_CREATED_DATE() {
        return SERVER_CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSTRACK.SERVER_CREATED_DATE
     *
     * @param SERVER_CREATED_DATE the value for TRSTRACK.SERVER_CREATED_DATE
     */
    public void setSERVER_CREATED_DATE(Date SERVER_CREATED_DATE) {
        this.SERVER_CREATED_DATE = SERVER_CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSTRACK.SERVER_APPROVED_DATE
     *
     * @return the value of TRSTRACK.SERVER_APPROVED_DATE
     */
    public Date getSERVER_APPROVED_DATE() {
        return SERVER_APPROVED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSTRACK.SERVER_APPROVED_DATE
     *
     * @param SERVER_APPROVED_DATE the value for TRSTRACK.SERVER_APPROVED_DATE
     */
    public void setSERVER_APPROVED_DATE(Date SERVER_APPROVED_DATE) {
        this.SERVER_APPROVED_DATE = SERVER_APPROVED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSTRACK.SERVER_REVERSED_DATE
     *
     * @return the value of TRSTRACK.SERVER_REVERSED_DATE
     */
    public Date getSERVER_REVERSED_DATE() {
        return SERVER_REVERSED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSTRACK.SERVER_REVERSED_DATE
     *
     * @param SERVER_REVERSED_DATE the value for TRSTRACK.SERVER_REVERSED_DATE
     */
    public void setSERVER_REVERSED_DATE(Date SERVER_REVERSED_DATE) {
        this.SERVER_REVERSED_DATE = SERVER_REVERSED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSTRACK.TRACK_TYPE
     *
     * @return the value of TRSTRACK.TRACK_TYPE
     */
    public String getTRACK_TYPE() {
        return TRACK_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSTRACK.TRACK_TYPE
     *
     * @param TRACK_TYPE the value for TRSTRACK.TRACK_TYPE
     */
    public void setTRACK_TYPE(String TRACK_TYPE) {
        this.TRACK_TYPE = TRACK_TYPE == null ? null : TRACK_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSTRACK.REVERSAL_STATUS
     *
     * @return the value of TRSTRACK.REVERSAL_STATUS
     */
    public String getREVERSAL_STATUS() {
        return REVERSAL_STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSTRACK.REVERSAL_STATUS
     *
     * @param REVERSAL_STATUS the value for TRSTRACK.REVERSAL_STATUS
     */
    public void setREVERSAL_STATUS(String REVERSAL_STATUS) {
        this.REVERSAL_STATUS = REVERSAL_STATUS == null ? null : REVERSAL_STATUS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSTRACK.REVERSAL_CREATED_BY
     *
     * @return the value of TRSTRACK.REVERSAL_CREATED_BY
     */
    public String getREVERSAL_CREATED_BY() {
        return REVERSAL_CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSTRACK.REVERSAL_CREATED_BY
     *
     * @param REVERSAL_CREATED_BY the value for TRSTRACK.REVERSAL_CREATED_BY
     */
    public void setREVERSAL_CREATED_BY(String REVERSAL_CREATED_BY) {
        this.REVERSAL_CREATED_BY = REVERSAL_CREATED_BY == null ? null : REVERSAL_CREATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSTRACK.REVERSAL_CREATED_DATE
     *
     * @return the value of TRSTRACK.REVERSAL_CREATED_DATE
     */
    public Date getREVERSAL_CREATED_DATE() {
        return REVERSAL_CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSTRACK.REVERSAL_CREATED_DATE
     *
     * @param REVERSAL_CREATED_DATE the value for TRSTRACK.REVERSAL_CREATED_DATE
     */
    public void setREVERSAL_CREATED_DATE(Date REVERSAL_CREATED_DATE) {
        this.REVERSAL_CREATED_DATE = REVERSAL_CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSTRACK.SERVER_REVERSAL_CREATED_DATE
     *
     * @return the value of TRSTRACK.SERVER_REVERSAL_CREATED_DATE
     */
    public Date getSERVER_REVERSAL_CREATED_DATE() {
        return SERVER_REVERSAL_CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSTRACK.SERVER_REVERSAL_CREATED_DATE
     *
     * @param SERVER_REVERSAL_CREATED_DATE the value for TRSTRACK.SERVER_REVERSAL_CREATED_DATE
     */
    public void setSERVER_REVERSAL_CREATED_DATE(Date SERVER_REVERSAL_CREATED_DATE) {
        this.SERVER_REVERSAL_CREATED_DATE = SERVER_REVERSAL_CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSTRACK.REVERSAL_DELETED_BY
     *
     * @return the value of TRSTRACK.REVERSAL_DELETED_BY
     */
    public String getREVERSAL_DELETED_BY() {
        return REVERSAL_DELETED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSTRACK.REVERSAL_DELETED_BY
     *
     * @param REVERSAL_DELETED_BY the value for TRSTRACK.REVERSAL_DELETED_BY
     */
    public void setREVERSAL_DELETED_BY(String REVERSAL_DELETED_BY) {
        this.REVERSAL_DELETED_BY = REVERSAL_DELETED_BY == null ? null : REVERSAL_DELETED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSTRACK.REVERSAL_DELETED_DATE
     *
     * @return the value of TRSTRACK.REVERSAL_DELETED_DATE
     */
    public Date getREVERSAL_DELETED_DATE() {
        return REVERSAL_DELETED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSTRACK.REVERSAL_DELETED_DATE
     *
     * @param REVERSAL_DELETED_DATE the value for TRSTRACK.REVERSAL_DELETED_DATE
     */
    public void setREVERSAL_DELETED_DATE(Date REVERSAL_DELETED_DATE) {
        this.REVERSAL_DELETED_DATE = REVERSAL_DELETED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSTRACK.SERVER_REVERSAL_DELETED_DATE
     *
     * @return the value of TRSTRACK.SERVER_REVERSAL_DELETED_DATE
     */
    public Date getSERVER_REVERSAL_DELETED_DATE() {
        return SERVER_REVERSAL_DELETED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSTRACK.SERVER_REVERSAL_DELETED_DATE
     *
     * @param SERVER_REVERSAL_DELETED_DATE the value for TRSTRACK.SERVER_REVERSAL_DELETED_DATE
     */
    public void setSERVER_REVERSAL_DELETED_DATE(Date SERVER_REVERSAL_DELETED_DATE) {
        this.SERVER_REVERSAL_DELETED_DATE = SERVER_REVERSAL_DELETED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSTRACK.DATE_UPDATED
     *
     * @return the value of TRSTRACK.DATE_UPDATED
     */
    public Date getDATE_UPDATED() {
        return DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSTRACK.DATE_UPDATED
     *
     * @param DATE_UPDATED the value for TRSTRACK.DATE_UPDATED
     */
    public void setDATE_UPDATED(Date DATE_UPDATED) {
        this.DATE_UPDATED = DATE_UPDATED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSTRACK.MUSHARAKA_PROFIT
     *
     * @return the value of TRSTRACK.MUSHARAKA_PROFIT
     */
    public BigDecimal getMUSHARAKA_PROFIT() {
        return MUSHARAKA_PROFIT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSTRACK.MUSHARAKA_PROFIT
     *
     * @param MUSHARAKA_PROFIT the value for TRSTRACK.MUSHARAKA_PROFIT
     */
    public void setMUSHARAKA_PROFIT(BigDecimal MUSHARAKA_PROFIT) {
        this.MUSHARAKA_PROFIT = MUSHARAKA_PROFIT;
    }
}