package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class TRSTYPE_ADD_FIELDS_VALUEVO extends TRSTYPE_ADD_FIELDS_VALUEVOKey {
    /**
     * This field corresponds to the database column TRSTYPE_ADD_FIELDS_VALUE.COLUMN_NAME
     */
    private String COLUMN_NAME;
    
    /**
     * This field corresponds to the database column TRSTYPE_ADD_FIELDS_VALUE.LENGTH
     */
    private BigDecimal LENGTH;
    
    /**
     * This field corresponds to the database column TRSTYPE_ADD_FIELDS_VALUE.LENGTH
     */
    private String TYPE;
    
    /**
     * This field corresponds to the database column TRSTYPE_ADD_FIELDS_VALUE.VALUE
     */
    private String VALUE;
    
    /**
     * This field corresponds to the database column TRSTYPE_ADD_FIELDS_VALUE.VALUE
     */
    private BigDecimal TRX_TYPE;

    /**
     * This field corresponds to the database column TRSTYPE_ADD_FIELDS_VALUE.VALUE
     */
    private BigDecimal CURRENCY_CODE;


    /**
     * This field corresponds to the database column TRSTYPE_ADD_FIELDS_VALUE.MANDATORY_YN
     */
    private String MANDATORY_YN;

    /**
     * This field corresponds to the database column TRSTYPE_ADD_FIELDS_VALUE.CREATED_BY
     */
    private String CREATED_BY;

    /**
     * This field corresponds to the database column TRSTYPE_ADD_FIELDS_VALUE.CREATED_DATE
     */
    private Date CREATED_DATE;

    /**
     * This field corresponds to the database column TRSTYPE_ADD_FIELDS_VALUE.MODIFIED_BY
     */
    private String MODIFIED_BY;

    /**
     * This field corresponds to the database column TRSTYPE_ADD_FIELDS_VALUE.MODIFIED_DATE
     */
    private Date MODIFIED_DATE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSTYPE_ADD_FIELDS_VALUE.COLUMN_NAME
     *
     * @return the value of TRSTYPE_ADD_FIELDS_VALUE.COLUMN_NAME
     */
    public String getCOLUMN_NAME() {
        return COLUMN_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSTYPE_ADD_FIELDS_VALUE.COLUMN_NAME
     *
     * @param COLUMN_NAME the value for TRSTYPE_ADD_FIELDS_VALUE.COLUMN_NAME
     */
    public void setCOLUMN_NAME(String COLUMN_NAME) {
        this.COLUMN_NAME = COLUMN_NAME == null ? null : COLUMN_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSTYPE_ADD_FIELDS_VALUE.VALUE
     *
     * @return the value of TRSTYPE_ADD_FIELDS_VALUE.VALUE
     */
    public String getVALUE() {
        return VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSTYPE_ADD_FIELDS_VALUE.VALUE
     *
     * @param VALUE the value for TRSTYPE_ADD_FIELDS_VALUE.VALUE
     */
    public void setVALUE(String VALUE) {
        this.VALUE = VALUE == null ? null : VALUE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSTYPE_ADD_FIELDS_VALUE.MANDATORY_YN
     *
     * @return the value of TRSTYPE_ADD_FIELDS_VALUE.MANDATORY_YN
     */
    public String getMANDATORY_YN() {
        return MANDATORY_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSTYPE_ADD_FIELDS_VALUE.MANDATORY_YN
     *
     * @param MANDATORY_YN the value for TRSTYPE_ADD_FIELDS_VALUE.MANDATORY_YN
     */
    public void setMANDATORY_YN(String MANDATORY_YN) {
        this.MANDATORY_YN = MANDATORY_YN == null ? null : MANDATORY_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSTYPE_ADD_FIELDS_VALUE.CREATED_BY
     *
     * @return the value of TRSTYPE_ADD_FIELDS_VALUE.CREATED_BY
     */
    public String getCREATED_BY() {
        return CREATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSTYPE_ADD_FIELDS_VALUE.CREATED_BY
     *
     * @param CREATED_BY the value for TRSTYPE_ADD_FIELDS_VALUE.CREATED_BY
     */
    public void setCREATED_BY(String CREATED_BY) {
        this.CREATED_BY = CREATED_BY == null ? null : CREATED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSTYPE_ADD_FIELDS_VALUE.CREATED_DATE
     *
     * @return the value of TRSTYPE_ADD_FIELDS_VALUE.CREATED_DATE
     */
    public Date getCREATED_DATE() {
        return CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSTYPE_ADD_FIELDS_VALUE.CREATED_DATE
     *
     * @param CREATED_DATE the value for TRSTYPE_ADD_FIELDS_VALUE.CREATED_DATE
     */
    public void setCREATED_DATE(Date CREATED_DATE) {
        this.CREATED_DATE = CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSTYPE_ADD_FIELDS_VALUE.MODIFIED_BY
     *
     * @return the value of TRSTYPE_ADD_FIELDS_VALUE.MODIFIED_BY
     */
    public String getMODIFIED_BY() {
        return MODIFIED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSTYPE_ADD_FIELDS_VALUE.MODIFIED_BY
     *
     * @param MODIFIED_BY the value for TRSTYPE_ADD_FIELDS_VALUE.MODIFIED_BY
     */
    public void setMODIFIED_BY(String MODIFIED_BY) {
        this.MODIFIED_BY = MODIFIED_BY == null ? null : MODIFIED_BY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSTYPE_ADD_FIELDS_VALUE.MODIFIED_DATE
     *
     * @return the value of TRSTYPE_ADD_FIELDS_VALUE.MODIFIED_DATE
     */
    public Date getMODIFIED_DATE() {
        return MODIFIED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSTYPE_ADD_FIELDS_VALUE.MODIFIED_DATE
     *
     * @param MODIFIED_DATE the value for TRSTYPE_ADD_FIELDS_VALUE.MODIFIED_DATE
     */
    public void setMODIFIED_DATE(Date MODIFIED_DATE) {
        this.MODIFIED_DATE = MODIFIED_DATE;
    }

    public BigDecimal getTRX_TYPE()
    {
        return TRX_TYPE;
    }

    public void setTRX_TYPE(BigDecimal tRX_TYPE)
    {
        TRX_TYPE = tRX_TYPE;
    }

    public BigDecimal getCURRENCY_CODE()
    {
        return CURRENCY_CODE;
    }

    public void setCURRENCY_CODE(BigDecimal cURRENCY_CODE)
    {
        CURRENCY_CODE = cURRENCY_CODE;
    }

    public BigDecimal getLENGTH()
    {
        return LENGTH;
    }

    public void setLENGTH(BigDecimal lENGTH)
    {
        LENGTH = lENGTH;
    }

    public String getTYPE()
    {
        return TYPE;
    }

    public void setTYPE(String tYPE)
    {
        TYPE = tYPE;
    }
}