package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class TRSTRACK_CHARGESVOKey extends BaseVO {
    /**
     * This field corresponds to the database column TRSTRACK_CHARGES.BRANCH_CODE
     */
    private BigDecimal BRANCH_CODE;

    /**
     * This field corresponds to the database column TRSTRACK_CHARGES.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column TRSTRACK_CHARGES.LINE_NBR
     */
    private BigDecimal LINE_NBR;

    /**
     * This field corresponds to the database column TRSTRACK_CHARGES.TRACK_NBR
     */
    private BigDecimal TRACK_NBR;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSTRACK_CHARGES.BRANCH_CODE
     *
     * @return the value of TRSTRACK_CHARGES.BRANCH_CODE
     */
    public BigDecimal getBRANCH_CODE() {
        return BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSTRACK_CHARGES.BRANCH_CODE
     *
     * @param BRANCH_CODE the value for TRSTRACK_CHARGES.BRANCH_CODE
     */
    public void setBRANCH_CODE(BigDecimal BRANCH_CODE) {
        this.BRANCH_CODE = BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSTRACK_CHARGES.COMP_CODE
     *
     * @return the value of TRSTRACK_CHARGES.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSTRACK_CHARGES.COMP_CODE
     *
     * @param COMP_CODE the value for TRSTRACK_CHARGES.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSTRACK_CHARGES.LINE_NBR
     *
     * @return the value of TRSTRACK_CHARGES.LINE_NBR
     */
    public BigDecimal getLINE_NBR() {
        return LINE_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSTRACK_CHARGES.LINE_NBR
     *
     * @param LINE_NBR the value for TRSTRACK_CHARGES.LINE_NBR
     */
    public void setLINE_NBR(BigDecimal LINE_NBR) {
        this.LINE_NBR = LINE_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSTRACK_CHARGES.TRACK_NBR
     *
     * @return the value of TRSTRACK_CHARGES.TRACK_NBR
     */
    public BigDecimal getTRACK_NBR() {
        return TRACK_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSTRACK_CHARGES.TRACK_NBR
     *
     * @param TRACK_NBR the value for TRSTRACK_CHARGES.TRACK_NBR
     */
    public void setTRACK_NBR(BigDecimal TRACK_NBR) {
        this.TRACK_NBR = TRACK_NBR;
    }
}