package com.path.dbmaps.vo;

import java.math.BigDecimal;

public class TRSTRDE_BULK_ACCOUNTSVO extends TRSTRDE_BULK_ACCOUNTSVOKey {
    /**
     * This field corresponds to the database column TRSTRDE_BULK_ACCOUNTS.ACC_BRANCH_CODE
     */
    private BigDecimal ACC_BRANCH_CODE;

    /**
     * This field corresponds to the database column TRSTRDE_BULK_ACCOUNTS.ACC_CY_CODE
     */
    private BigDecimal ACC_CY_CODE;

    /**
     * This field corresponds to the database column TRSTRDE_BULK_ACCOUNTS.ACC_GL_CODE
     */
    private BigDecimal ACC_GL_CODE;

    /**
     * This field corresponds to the database column TRSTRDE_BULK_ACCOUNTS.ACC_CIF_CODE
     */
    private BigDecimal ACC_CIF_CODE;

    /**
     * This field corresponds to the database column TRSTRDE_BULK_ACCOUNTS.ACC_SL_NO
     */
    private BigDecimal ACC_SL_NO;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSTRDE_BULK_ACCOUNTS.ACC_BRANCH_CODE
     *
     * @return the value of TRSTRDE_BULK_ACCOUNTS.ACC_BRANCH_CODE
     */
    public BigDecimal getACC_BRANCH_CODE() {
        return ACC_BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSTRDE_BULK_ACCOUNTS.ACC_BRANCH_CODE
     *
     * @param ACC_BRANCH_CODE the value for TRSTRDE_BULK_ACCOUNTS.ACC_BRANCH_CODE
     */
    public void setACC_BRANCH_CODE(BigDecimal ACC_BRANCH_CODE) {
        this.ACC_BRANCH_CODE = ACC_BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSTRDE_BULK_ACCOUNTS.ACC_CY_CODE
     *
     * @return the value of TRSTRDE_BULK_ACCOUNTS.ACC_CY_CODE
     */
    public BigDecimal getACC_CY_CODE() {
        return ACC_CY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSTRDE_BULK_ACCOUNTS.ACC_CY_CODE
     *
     * @param ACC_CY_CODE the value for TRSTRDE_BULK_ACCOUNTS.ACC_CY_CODE
     */
    public void setACC_CY_CODE(BigDecimal ACC_CY_CODE) {
        this.ACC_CY_CODE = ACC_CY_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSTRDE_BULK_ACCOUNTS.ACC_GL_CODE
     *
     * @return the value of TRSTRDE_BULK_ACCOUNTS.ACC_GL_CODE
     */
    public BigDecimal getACC_GL_CODE() {
        return ACC_GL_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSTRDE_BULK_ACCOUNTS.ACC_GL_CODE
     *
     * @param ACC_GL_CODE the value for TRSTRDE_BULK_ACCOUNTS.ACC_GL_CODE
     */
    public void setACC_GL_CODE(BigDecimal ACC_GL_CODE) {
        this.ACC_GL_CODE = ACC_GL_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSTRDE_BULK_ACCOUNTS.ACC_CIF_CODE
     *
     * @return the value of TRSTRDE_BULK_ACCOUNTS.ACC_CIF_CODE
     */
    public BigDecimal getACC_CIF_CODE() {
        return ACC_CIF_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSTRDE_BULK_ACCOUNTS.ACC_CIF_CODE
     *
     * @param ACC_CIF_CODE the value for TRSTRDE_BULK_ACCOUNTS.ACC_CIF_CODE
     */
    public void setACC_CIF_CODE(BigDecimal ACC_CIF_CODE) {
        this.ACC_CIF_CODE = ACC_CIF_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSTRDE_BULK_ACCOUNTS.ACC_SL_NO
     *
     * @return the value of TRSTRDE_BULK_ACCOUNTS.ACC_SL_NO
     */
    public BigDecimal getACC_SL_NO() {
        return ACC_SL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSTRDE_BULK_ACCOUNTS.ACC_SL_NO
     *
     * @param ACC_SL_NO the value for TRSTRDE_BULK_ACCOUNTS.ACC_SL_NO
     */
    public void setACC_SL_NO(BigDecimal ACC_SL_NO) {
        this.ACC_SL_NO = ACC_SL_NO;
    }
}