package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class TRSUSRLIMITDETVOKey extends BaseVO {
    /**
     * This field corresponds to the database column TRSUSRLIMITDET.BRANCH_CODE
     */
    private BigDecimal BRANCH_CODE;

    /**
     * This field corresponds to the database column TRSUSRLIMITDET.CLASS
     */
    private BigDecimal CLASS;

    /**
     * This field corresponds to the database column TRSUSRLIMITDET.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column TRSUSRLIMITDET.CURRENCY
     */
    private BigDecimal CURRENCY;

    /**
     * This field corresponds to the database column TRSUSRLIMITDET.USER_ID
     */
    private String USER_ID;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSUSRLIMITDET.BRANCH_CODE
     *
     * @return the value of TRSUSRLIMITDET.BRANCH_CODE
     */
    public BigDecimal getBRANCH_CODE() {
        return BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSUSRLIMITDET.BRANCH_CODE
     *
     * @param BRANCH_CODE the value for TRSUSRLIMITDET.BRANCH_CODE
     */
    public void setBRANCH_CODE(BigDecimal BRANCH_CODE) {
        this.BRANCH_CODE = BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSUSRLIMITDET.CLASS
     *
     * @return the value of TRSUSRLIMITDET.CLASS
     */
    public BigDecimal getCLASS() {
        return CLASS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSUSRLIMITDET.CLASS
     *
     * @param CLASS the value for TRSUSRLIMITDET.CLASS
     */
    public void setCLASS(BigDecimal CLASS) {
        this.CLASS = CLASS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSUSRLIMITDET.COMP_CODE
     *
     * @return the value of TRSUSRLIMITDET.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSUSRLIMITDET.COMP_CODE
     *
     * @param COMP_CODE the value for TRSUSRLIMITDET.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSUSRLIMITDET.CURRENCY
     *
     * @return the value of TRSUSRLIMITDET.CURRENCY
     */
    public BigDecimal getCURRENCY() {
        return CURRENCY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSUSRLIMITDET.CURRENCY
     *
     * @param CURRENCY the value for TRSUSRLIMITDET.CURRENCY
     */
    public void setCURRENCY(BigDecimal CURRENCY) {
        this.CURRENCY = CURRENCY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSUSRLIMITDET.USER_ID
     *
     * @return the value of TRSUSRLIMITDET.USER_ID
     */
    public String getUSER_ID() {
        return USER_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSUSRLIMITDET.USER_ID
     *
     * @param USER_ID the value for TRSUSRLIMITDET.USER_ID
     */
    public void setUSER_ID(String USER_ID) {
        this.USER_ID = USER_ID == null ? null : USER_ID.trim();
    }
}