package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class TRSVATVOKey extends BaseVO {
    /**
     * This field corresponds to the database column TRSVAT.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column TRSVAT.VAT_CODE
     */
    private BigDecimal VAT_CODE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSVAT.COMP_CODE
     *
     * @return the value of TRSVAT.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSVAT.COMP_CODE
     *
     * @param COMP_CODE the value for TRSVAT.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRSVAT.VAT_CODE
     *
     * @return the value of TRSVAT.VAT_CODE
     */
    public BigDecimal getVAT_CODE() {
        return VAT_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRSVAT.VAT_CODE
     *
     * @param VAT_CODE the value for TRSVAT.VAT_CODE
     */
    public void setVAT_CODE(BigDecimal VAT_CODE) {
        this.VAT_CODE = VAT_CODE;
    }
}