package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;
import java.util.Date;

public class UN_MAINVO extends BaseVO {
    /**
     * This field corresponds to the database column UN_MAIN.ENT_NUM
     */
    private BigDecimal ENT_NUM;

    /**
     * This field corresponds to the database column UN_MAIN.NAME1
     */
    private String NAME1;

    /**
     * This field corresponds to the database column UN_MAIN.NAME2
     */
    private String NAME2;

    /**
     * This field corresponds to the database column UN_MAIN.NAME3
     */
    private String NAME3;

    /**
     * This field corresponds to the database column UN_MAIN.NAME4
     */
    private String NAME4;

    /**
     * This field corresponds to the database column UN_MAIN.TITLE
     */
    private String TITLE;

    /**
     * This field corresponds to the database column UN_MAIN.DESIGNATION
     */
    private String DESIGNATION;

    /**
     * This field corresponds to the database column UN_MAIN.DOB
     */
    private String DOB;

    /**
     * This field corresponds to the database column UN_MAIN.POB
     */
    private String POB;

    /**
     * This field corresponds to the database column UN_MAIN.GOOD_AKA
     */
    private String GOOD_AKA;

    /**
     * This field corresponds to the database column UN_MAIN.LOW_AKA
     */
    private String LOW_AKA;

    /**
     * This field corresponds to the database column UN_MAIN.AKA
     */
    private String AKA;

    /**
     * This field corresponds to the database column UN_MAIN.FKA
     */
    private String FKA;

    /**
     * This field corresponds to the database column UN_MAIN.NATIONALITY
     */
    private String NATIONALITY;

    /**
     * This field corresponds to the database column UN_MAIN.PASSPORT_NO
     */
    private String PASSPORT_NO;

    /**
     * This field corresponds to the database column UN_MAIN.NAT_ID_NO
     */
    private String NAT_ID_NO;

    /**
     * This field corresponds to the database column UN_MAIN.ADDRESS
     */
    private String ADDRESS;

    /**
     * This field corresponds to the database column UN_MAIN.LISTED_ON
     */
    private String LISTED_ON;

    /**
     * This field corresponds to the database column UN_MAIN.OTHER_INFOS
     */
    private String OTHER_INFOS;

    /**
     * This field corresponds to the database column UN_MAIN.REC_STATUS
     */
    private String REC_STATUS;

    /**
     * This field corresponds to the database column UN_MAIN.MODIF_DATE
     */
    private Date MODIF_DATE;

    /**
     * This field corresponds to the database column UN_MAIN.SOUNDEX_NAME
     */
    private String SOUNDEX_NAME;

    /**
     * This field corresponds to the database column UN_MAIN.DOWNLOAD_DATE
     */
    private Date DOWNLOAD_DATE;

    /**
     * This field corresponds to the database column UN_MAIN.USER_ID
     */
    private String USER_ID;

    /**
     * This field corresponds to the database column UN_MAIN.UN_TYPE
     */
    private String UN_TYPE;

    /**
     * This field corresponds to the database column UN_MAIN.DOWNLOAD_TIME
     */
    private String DOWNLOAD_TIME;

    /**
     * This field corresponds to the database column UN_MAIN.ADD_TEXT1
     */
    private String ADD_TEXT1;

    /**
     * This field corresponds to the database column UN_MAIN.ADD_TEXT2
     */
    private String ADD_TEXT2;

    /**
     * This field corresponds to the database column UN_MAIN.FILE_NAME
     */
    private String FILE_NAME;

    /**
     * This field corresponds to the database column UN_MAIN.NAME_ARAB
     */
    private String NAME_ARAB;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UN_MAIN.ENT_NUM
     *
     * @return the value of UN_MAIN.ENT_NUM
     */
    public BigDecimal getENT_NUM() {
        return ENT_NUM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UN_MAIN.ENT_NUM
     *
     * @param ENT_NUM the value for UN_MAIN.ENT_NUM
     */
    public void setENT_NUM(BigDecimal ENT_NUM) {
        this.ENT_NUM = ENT_NUM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UN_MAIN.NAME1
     *
     * @return the value of UN_MAIN.NAME1
     */
    public String getNAME1() {
        return NAME1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UN_MAIN.NAME1
     *
     * @param NAME1 the value for UN_MAIN.NAME1
     */
    public void setNAME1(String NAME1) {
        this.NAME1 = NAME1 == null ? null : NAME1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UN_MAIN.NAME2
     *
     * @return the value of UN_MAIN.NAME2
     */
    public String getNAME2() {
        return NAME2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UN_MAIN.NAME2
     *
     * @param NAME2 the value for UN_MAIN.NAME2
     */
    public void setNAME2(String NAME2) {
        this.NAME2 = NAME2 == null ? null : NAME2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UN_MAIN.NAME3
     *
     * @return the value of UN_MAIN.NAME3
     */
    public String getNAME3() {
        return NAME3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UN_MAIN.NAME3
     *
     * @param NAME3 the value for UN_MAIN.NAME3
     */
    public void setNAME3(String NAME3) {
        this.NAME3 = NAME3 == null ? null : NAME3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UN_MAIN.NAME4
     *
     * @return the value of UN_MAIN.NAME4
     */
    public String getNAME4() {
        return NAME4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UN_MAIN.NAME4
     *
     * @param NAME4 the value for UN_MAIN.NAME4
     */
    public void setNAME4(String NAME4) {
        this.NAME4 = NAME4 == null ? null : NAME4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UN_MAIN.TITLE
     *
     * @return the value of UN_MAIN.TITLE
     */
    public String getTITLE() {
        return TITLE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UN_MAIN.TITLE
     *
     * @param TITLE the value for UN_MAIN.TITLE
     */
    public void setTITLE(String TITLE) {
        this.TITLE = TITLE == null ? null : TITLE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UN_MAIN.DESIGNATION
     *
     * @return the value of UN_MAIN.DESIGNATION
     */
    public String getDESIGNATION() {
        return DESIGNATION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UN_MAIN.DESIGNATION
     *
     * @param DESIGNATION the value for UN_MAIN.DESIGNATION
     */
    public void setDESIGNATION(String DESIGNATION) {
        this.DESIGNATION = DESIGNATION == null ? null : DESIGNATION.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UN_MAIN.DOB
     *
     * @return the value of UN_MAIN.DOB
     */
    public String getDOB() {
        return DOB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UN_MAIN.DOB
     *
     * @param DOB the value for UN_MAIN.DOB
     */
    public void setDOB(String DOB) {
        this.DOB = DOB == null ? null : DOB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UN_MAIN.POB
     *
     * @return the value of UN_MAIN.POB
     */
    public String getPOB() {
        return POB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UN_MAIN.POB
     *
     * @param POB the value for UN_MAIN.POB
     */
    public void setPOB(String POB) {
        this.POB = POB == null ? null : POB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UN_MAIN.GOOD_AKA
     *
     * @return the value of UN_MAIN.GOOD_AKA
     */
    public String getGOOD_AKA() {
        return GOOD_AKA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UN_MAIN.GOOD_AKA
     *
     * @param GOOD_AKA the value for UN_MAIN.GOOD_AKA
     */
    public void setGOOD_AKA(String GOOD_AKA) {
        this.GOOD_AKA = GOOD_AKA == null ? null : GOOD_AKA.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UN_MAIN.LOW_AKA
     *
     * @return the value of UN_MAIN.LOW_AKA
     */
    public String getLOW_AKA() {
        return LOW_AKA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UN_MAIN.LOW_AKA
     *
     * @param LOW_AKA the value for UN_MAIN.LOW_AKA
     */
    public void setLOW_AKA(String LOW_AKA) {
        this.LOW_AKA = LOW_AKA == null ? null : LOW_AKA.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UN_MAIN.AKA
     *
     * @return the value of UN_MAIN.AKA
     */
    public String getAKA() {
        return AKA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UN_MAIN.AKA
     *
     * @param AKA the value for UN_MAIN.AKA
     */
    public void setAKA(String AKA) {
        this.AKA = AKA == null ? null : AKA.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UN_MAIN.FKA
     *
     * @return the value of UN_MAIN.FKA
     */
    public String getFKA() {
        return FKA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UN_MAIN.FKA
     *
     * @param FKA the value for UN_MAIN.FKA
     */
    public void setFKA(String FKA) {
        this.FKA = FKA == null ? null : FKA.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UN_MAIN.NATIONALITY
     *
     * @return the value of UN_MAIN.NATIONALITY
     */
    public String getNATIONALITY() {
        return NATIONALITY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UN_MAIN.NATIONALITY
     *
     * @param NATIONALITY the value for UN_MAIN.NATIONALITY
     */
    public void setNATIONALITY(String NATIONALITY) {
        this.NATIONALITY = NATIONALITY == null ? null : NATIONALITY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UN_MAIN.PASSPORT_NO
     *
     * @return the value of UN_MAIN.PASSPORT_NO
     */
    public String getPASSPORT_NO() {
        return PASSPORT_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UN_MAIN.PASSPORT_NO
     *
     * @param PASSPORT_NO the value for UN_MAIN.PASSPORT_NO
     */
    public void setPASSPORT_NO(String PASSPORT_NO) {
        this.PASSPORT_NO = PASSPORT_NO == null ? null : PASSPORT_NO.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UN_MAIN.NAT_ID_NO
     *
     * @return the value of UN_MAIN.NAT_ID_NO
     */
    public String getNAT_ID_NO() {
        return NAT_ID_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UN_MAIN.NAT_ID_NO
     *
     * @param NAT_ID_NO the value for UN_MAIN.NAT_ID_NO
     */
    public void setNAT_ID_NO(String NAT_ID_NO) {
        this.NAT_ID_NO = NAT_ID_NO == null ? null : NAT_ID_NO.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UN_MAIN.ADDRESS
     *
     * @return the value of UN_MAIN.ADDRESS
     */
    public String getADDRESS() {
        return ADDRESS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UN_MAIN.ADDRESS
     *
     * @param ADDRESS the value for UN_MAIN.ADDRESS
     */
    public void setADDRESS(String ADDRESS) {
        this.ADDRESS = ADDRESS == null ? null : ADDRESS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UN_MAIN.LISTED_ON
     *
     * @return the value of UN_MAIN.LISTED_ON
     */
    public String getLISTED_ON() {
        return LISTED_ON;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UN_MAIN.LISTED_ON
     *
     * @param LISTED_ON the value for UN_MAIN.LISTED_ON
     */
    public void setLISTED_ON(String LISTED_ON) {
        this.LISTED_ON = LISTED_ON == null ? null : LISTED_ON.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UN_MAIN.OTHER_INFOS
     *
     * @return the value of UN_MAIN.OTHER_INFOS
     */
    public String getOTHER_INFOS() {
        return OTHER_INFOS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UN_MAIN.OTHER_INFOS
     *
     * @param OTHER_INFOS the value for UN_MAIN.OTHER_INFOS
     */
    public void setOTHER_INFOS(String OTHER_INFOS) {
        this.OTHER_INFOS = OTHER_INFOS == null ? null : OTHER_INFOS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UN_MAIN.REC_STATUS
     *
     * @return the value of UN_MAIN.REC_STATUS
     */
    public String getREC_STATUS() {
        return REC_STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UN_MAIN.REC_STATUS
     *
     * @param REC_STATUS the value for UN_MAIN.REC_STATUS
     */
    public void setREC_STATUS(String REC_STATUS) {
        this.REC_STATUS = REC_STATUS == null ? null : REC_STATUS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UN_MAIN.MODIF_DATE
     *
     * @return the value of UN_MAIN.MODIF_DATE
     */
    public Date getMODIF_DATE() {
        return MODIF_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UN_MAIN.MODIF_DATE
     *
     * @param MODIF_DATE the value for UN_MAIN.MODIF_DATE
     */
    public void setMODIF_DATE(Date MODIF_DATE) {
        this.MODIF_DATE = MODIF_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UN_MAIN.SOUNDEX_NAME
     *
     * @return the value of UN_MAIN.SOUNDEX_NAME
     */
    public String getSOUNDEX_NAME() {
        return SOUNDEX_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UN_MAIN.SOUNDEX_NAME
     *
     * @param SOUNDEX_NAME the value for UN_MAIN.SOUNDEX_NAME
     */
    public void setSOUNDEX_NAME(String SOUNDEX_NAME) {
        this.SOUNDEX_NAME = SOUNDEX_NAME == null ? null : SOUNDEX_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UN_MAIN.DOWNLOAD_DATE
     *
     * @return the value of UN_MAIN.DOWNLOAD_DATE
     */
    public Date getDOWNLOAD_DATE() {
        return DOWNLOAD_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UN_MAIN.DOWNLOAD_DATE
     *
     * @param DOWNLOAD_DATE the value for UN_MAIN.DOWNLOAD_DATE
     */
    public void setDOWNLOAD_DATE(Date DOWNLOAD_DATE) {
        this.DOWNLOAD_DATE = DOWNLOAD_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UN_MAIN.USER_ID
     *
     * @return the value of UN_MAIN.USER_ID
     */
    public String getUSER_ID() {
        return USER_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UN_MAIN.USER_ID
     *
     * @param USER_ID the value for UN_MAIN.USER_ID
     */
    public void setUSER_ID(String USER_ID) {
        this.USER_ID = USER_ID == null ? null : USER_ID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UN_MAIN.UN_TYPE
     *
     * @return the value of UN_MAIN.UN_TYPE
     */
    public String getUN_TYPE() {
        return UN_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UN_MAIN.UN_TYPE
     *
     * @param UN_TYPE the value for UN_MAIN.UN_TYPE
     */
    public void setUN_TYPE(String UN_TYPE) {
        this.UN_TYPE = UN_TYPE == null ? null : UN_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UN_MAIN.DOWNLOAD_TIME
     *
     * @return the value of UN_MAIN.DOWNLOAD_TIME
     */
    public String getDOWNLOAD_TIME() {
        return DOWNLOAD_TIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UN_MAIN.DOWNLOAD_TIME
     *
     * @param DOWNLOAD_TIME the value for UN_MAIN.DOWNLOAD_TIME
     */
    public void setDOWNLOAD_TIME(String DOWNLOAD_TIME) {
        this.DOWNLOAD_TIME = DOWNLOAD_TIME == null ? null : DOWNLOAD_TIME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UN_MAIN.ADD_TEXT1
     *
     * @return the value of UN_MAIN.ADD_TEXT1
     */
    public String getADD_TEXT1() {
        return ADD_TEXT1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UN_MAIN.ADD_TEXT1
     *
     * @param ADD_TEXT1 the value for UN_MAIN.ADD_TEXT1
     */
    public void setADD_TEXT1(String ADD_TEXT1) {
        this.ADD_TEXT1 = ADD_TEXT1 == null ? null : ADD_TEXT1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UN_MAIN.ADD_TEXT2
     *
     * @return the value of UN_MAIN.ADD_TEXT2
     */
    public String getADD_TEXT2() {
        return ADD_TEXT2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UN_MAIN.ADD_TEXT2
     *
     * @param ADD_TEXT2 the value for UN_MAIN.ADD_TEXT2
     */
    public void setADD_TEXT2(String ADD_TEXT2) {
        this.ADD_TEXT2 = ADD_TEXT2 == null ? null : ADD_TEXT2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UN_MAIN.FILE_NAME
     *
     * @return the value of UN_MAIN.FILE_NAME
     */
    public String getFILE_NAME() {
        return FILE_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UN_MAIN.FILE_NAME
     *
     * @param FILE_NAME the value for UN_MAIN.FILE_NAME
     */
    public void setFILE_NAME(String FILE_NAME) {
        this.FILE_NAME = FILE_NAME == null ? null : FILE_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UN_MAIN.NAME_ARAB
     *
     * @return the value of UN_MAIN.NAME_ARAB
     */
    public String getNAME_ARAB() {
        return NAME_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UN_MAIN.NAME_ARAB
     *
     * @param NAME_ARAB the value for UN_MAIN.NAME_ARAB
     */
    public void setNAME_ARAB(String NAME_ARAB) {
        this.NAME_ARAB = NAME_ARAB == null ? null : NAME_ARAB.trim();
    }
}