package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;

public class USER_PORTLETSVOKey extends BaseVO {
    /**
     * This field corresponds to the database column USER_PORTLETS.LAYOUT
     */
    private String LAYOUT;

    /**
     * This field corresponds to the database column USER_PORTLETS.PORTLET_CODE
     */
    private String PORTLET_CODE;

    /**
     * This field corresponds to the database column USER_PORTLETS.USER_ID
     */
    private String USER_ID;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_PORTLETS.LAYOUT
     *
     * @return the value of USER_PORTLETS.LAYOUT
     */
    public String getLAYOUT() {
        return LAYOUT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_PORTLETS.LAYOUT
     *
     * @param LAYOUT the value for USER_PORTLETS.LAYOUT
     */
    public void setLAYOUT(String LAYOUT) {
        this.LAYOUT = LAYOUT == null ? null : LAYOUT.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_PORTLETS.PORTLET_CODE
     *
     * @return the value of USER_PORTLETS.PORTLET_CODE
     */
    public String getPORTLET_CODE() {
        return PORTLET_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_PORTLETS.PORTLET_CODE
     *
     * @param PORTLET_CODE the value for USER_PORTLETS.PORTLET_CODE
     */
    public void setPORTLET_CODE(String PORTLET_CODE) {
        this.PORTLET_CODE = PORTLET_CODE == null ? null : PORTLET_CODE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_PORTLETS.USER_ID
     *
     * @return the value of USER_PORTLETS.USER_ID
     */
    public String getUSER_ID() {
        return USER_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_PORTLETS.USER_ID
     *
     * @param USER_ID the value for USER_PORTLETS.USER_ID
     */
    public void setUSER_ID(String USER_ID) {
        this.USER_ID = USER_ID == null ? null : USER_ID.trim();
    }
}