package com.path.dbmaps.vo;

import java.math.BigDecimal;
import java.util.Date;

public class USR_SHIFTS_TEMPLATEVO extends USR_SHIFTS_TEMPLATEVOKey {
    /**
     * This field corresponds to the database column USR_SHIFTS_TEMPLATE.BRIEF_NAME_ENG
     */
    private String BRIEF_NAME_ENG;

    /**
     * This field corresponds to the database column USR_SHIFTS_TEMPLATE.BRIEF_NAME_ARAB
     */
    private String BRIEF_NAME_ARAB;

    /**
     * This field corresponds to the database column USR_SHIFTS_TEMPLATE.LONG_NAME_ENG
     */
    private String LONG_NAME_ENG;

    /**
     * This field corresponds to the database column USR_SHIFTS_TEMPLATE.LONG_NAME_ARAB
     */
    private String LONG_NAME_ARAB;

    /**
     * This field corresponds to the database column USR_SHIFTS_TEMPLATE.USER_ID
     */
    private String USER_ID;

    /**
     * This field corresponds to the database column USR_SHIFTS_TEMPLATE.DAY_OF_WEEK
     */
    private BigDecimal DAY_OF_WEEK;

    /**
     * This field corresponds to the database column USR_SHIFTS_TEMPLATE.FROM_TIME
     */
    private Date FROM_TIME;

    /**
     * This field corresponds to the database column USR_SHIFTS_TEMPLATE.TO_TIME
     */
    private Date TO_TIME;

    /**
     * This field corresponds to the database column USR_SHIFTS_TEMPLATE.GROUP_FLAG
     */
    private String GROUP_FLAG;

    /**
     * This field corresponds to the database column USR_SHIFTS_TEMPLATE.USER_FLAG
     */
    private String USER_FLAG;

    /**
     * This field corresponds to the database column USR_SHIFTS_TEMPLATE.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column USR_SHIFTS_TEMPLATE.BRANCH_CODE
     */
    private BigDecimal BRANCH_CODE;
    
    private Date DATE_UPDATED;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USR_SHIFTS_TEMPLATE.BRIEF_NAME_ENG
     *
     * @return the value of USR_SHIFTS_TEMPLATE.BRIEF_NAME_ENG
     */
    public String getBRIEF_NAME_ENG() {
        return BRIEF_NAME_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USR_SHIFTS_TEMPLATE.BRIEF_NAME_ENG
     *
     * @param BRIEF_NAME_ENG the value for USR_SHIFTS_TEMPLATE.BRIEF_NAME_ENG
     */
    public void setBRIEF_NAME_ENG(String BRIEF_NAME_ENG) {
        this.BRIEF_NAME_ENG = BRIEF_NAME_ENG == null ? null : BRIEF_NAME_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USR_SHIFTS_TEMPLATE.BRIEF_NAME_ARAB
     *
     * @return the value of USR_SHIFTS_TEMPLATE.BRIEF_NAME_ARAB
     */
    public String getBRIEF_NAME_ARAB() {
        return BRIEF_NAME_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USR_SHIFTS_TEMPLATE.BRIEF_NAME_ARAB
     *
     * @param BRIEF_NAME_ARAB the value for USR_SHIFTS_TEMPLATE.BRIEF_NAME_ARAB
     */
    public void setBRIEF_NAME_ARAB(String BRIEF_NAME_ARAB) {
        this.BRIEF_NAME_ARAB = BRIEF_NAME_ARAB == null ? null : BRIEF_NAME_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USR_SHIFTS_TEMPLATE.LONG_NAME_ENG
     *
     * @return the value of USR_SHIFTS_TEMPLATE.LONG_NAME_ENG
     */
    public String getLONG_NAME_ENG() {
        return LONG_NAME_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USR_SHIFTS_TEMPLATE.LONG_NAME_ENG
     *
     * @param LONG_NAME_ENG the value for USR_SHIFTS_TEMPLATE.LONG_NAME_ENG
     */
    public void setLONG_NAME_ENG(String LONG_NAME_ENG) {
        this.LONG_NAME_ENG = LONG_NAME_ENG == null ? null : LONG_NAME_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USR_SHIFTS_TEMPLATE.LONG_NAME_ARAB
     *
     * @return the value of USR_SHIFTS_TEMPLATE.LONG_NAME_ARAB
     */
    public String getLONG_NAME_ARAB() {
        return LONG_NAME_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USR_SHIFTS_TEMPLATE.LONG_NAME_ARAB
     *
     * @param LONG_NAME_ARAB the value for USR_SHIFTS_TEMPLATE.LONG_NAME_ARAB
     */
    public void setLONG_NAME_ARAB(String LONG_NAME_ARAB) {
        this.LONG_NAME_ARAB = LONG_NAME_ARAB == null ? null : LONG_NAME_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USR_SHIFTS_TEMPLATE.USER_ID
     *
     * @return the value of USR_SHIFTS_TEMPLATE.USER_ID
     */
    public String getUSER_ID() {
        return USER_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USR_SHIFTS_TEMPLATE.USER_ID
     *
     * @param USER_ID the value for USR_SHIFTS_TEMPLATE.USER_ID
     */
    public void setUSER_ID(String USER_ID) {
        this.USER_ID = USER_ID == null ? null : USER_ID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USR_SHIFTS_TEMPLATE.DAY_OF_WEEK
     *
     * @return the value of USR_SHIFTS_TEMPLATE.DAY_OF_WEEK
     */
    public BigDecimal getDAY_OF_WEEK() {
        return DAY_OF_WEEK;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USR_SHIFTS_TEMPLATE.DAY_OF_WEEK
     *
     * @param DAY_OF_WEEK the value for USR_SHIFTS_TEMPLATE.DAY_OF_WEEK
     */
    public void setDAY_OF_WEEK(BigDecimal DAY_OF_WEEK) {
        this.DAY_OF_WEEK = DAY_OF_WEEK;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USR_SHIFTS_TEMPLATE.FROM_TIME
     *
     * @return the value of USR_SHIFTS_TEMPLATE.FROM_TIME
     */
    public Date getFROM_TIME() {
        return FROM_TIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USR_SHIFTS_TEMPLATE.FROM_TIME
     *
     * @param FROM_TIME the value for USR_SHIFTS_TEMPLATE.FROM_TIME
     */
    public void setFROM_TIME(Date FROM_TIME) {
        this.FROM_TIME = FROM_TIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USR_SHIFTS_TEMPLATE.TO_TIME
     *
     * @return the value of USR_SHIFTS_TEMPLATE.TO_TIME
     */
    public Date getTO_TIME() {
        return TO_TIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USR_SHIFTS_TEMPLATE.TO_TIME
     *
     * @param TO_TIME the value for USR_SHIFTS_TEMPLATE.TO_TIME
     */
    public void setTO_TIME(Date TO_TIME) {
        this.TO_TIME = TO_TIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USR_SHIFTS_TEMPLATE.GROUP_FLAG
     *
     * @return the value of USR_SHIFTS_TEMPLATE.GROUP_FLAG
     */
    public String getGROUP_FLAG() {
        return GROUP_FLAG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USR_SHIFTS_TEMPLATE.GROUP_FLAG
     *
     * @param GROUP_FLAG the value for USR_SHIFTS_TEMPLATE.GROUP_FLAG
     */
    public void setGROUP_FLAG(String GROUP_FLAG) {
        this.GROUP_FLAG = GROUP_FLAG == null ? null : GROUP_FLAG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USR_SHIFTS_TEMPLATE.USER_FLAG
     *
     * @return the value of USR_SHIFTS_TEMPLATE.USER_FLAG
     */
    public String getUSER_FLAG() {
        return USER_FLAG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USR_SHIFTS_TEMPLATE.USER_FLAG
     *
     * @param USER_FLAG the value for USR_SHIFTS_TEMPLATE.USER_FLAG
     */
    public void setUSER_FLAG(String USER_FLAG) {
        this.USER_FLAG = USER_FLAG == null ? null : USER_FLAG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USR_SHIFTS_TEMPLATE.COMP_CODE
     *
     * @return the value of USR_SHIFTS_TEMPLATE.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USR_SHIFTS_TEMPLATE.COMP_CODE
     *
     * @param COMP_CODE the value for USR_SHIFTS_TEMPLATE.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USR_SHIFTS_TEMPLATE.BRANCH_CODE
     *
     * @return the value of USR_SHIFTS_TEMPLATE.BRANCH_CODE
     */
    public BigDecimal getBRANCH_CODE() {
        return BRANCH_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USR_SHIFTS_TEMPLATE.BRANCH_CODE
     *
     * @param BRANCH_CODE the value for USR_SHIFTS_TEMPLATE.BRANCH_CODE
     */
    public void setBRANCH_CODE(BigDecimal BRANCH_CODE) {
        this.BRANCH_CODE = BRANCH_CODE;
    }

		
		public Date getDATE_UPDATED()
		{
			return DATE_UPDATED;
		}

		
		public void setDATE_UPDATED(Date dATE_UPDATED)
		{
			DATE_UPDATED = dATE_UPDATED;
		}
}