package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;

public class USR_SNOOZE_ALERTVOKey extends BaseVO {
    /**
     * This field corresponds to the database column USR_SNOOZE_ALERT.APP_NAME
     */
    private String APP_NAME;

    /**
     * This field corresponds to the database column USR_SNOOZE_ALERT.USER_ID
     */
    private String USER_ID;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USR_SNOOZE_ALERT.APP_NAME
     *
     * @return the value of USR_SNOOZE_ALERT.APP_NAME
     */
    public String getAPP_NAME() {
        return APP_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USR_SNOOZE_ALERT.APP_NAME
     *
     * @param APP_NAME the value for USR_SNOOZE_ALERT.APP_NAME
     */
    public void setAPP_NAME(String APP_NAME) {
        this.APP_NAME = APP_NAME == null ? null : APP_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USR_SNOOZE_ALERT.USER_ID
     *
     * @return the value of USR_SNOOZE_ALERT.USER_ID
     */
    public String getUSER_ID() {
        return USER_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USR_SNOOZE_ALERT.USER_ID
     *
     * @param USER_ID the value for USR_SNOOZE_ALERT.USER_ID
     */
    public void setUSER_ID(String USER_ID) {
        this.USER_ID = USER_ID == null ? null : USER_ID.trim();
    }
}