package com.path.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class V_DRAWDOWN_CLASSVO extends BaseVO {
    /**
     * This field corresponds to the database column V_DRAWDOWN_CLASS.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column V_DRAWDOWN_CLASS.BRANCH
     */
    private BigDecimal BRANCH;

    /**
     * This field corresponds to the database column V_DRAWDOWN_CLASS.CODE
     */
    private BigDecimal CODE;

    /**
     * This field corresponds to the database column V_DRAWDOWN_CLASS.LINE_NBR
     */
    private BigDecimal LINE_NBR;

    /**
     * This field corresponds to the database column V_DRAWDOWN_CLASS.CLASS
     */
    private BigDecimal CLASS;

    /**
     * This field corresponds to the database column V_DRAWDOWN_CLASS.CATEGORY
     */
    private BigDecimal CATEGORY;

    /**
     * This field corresponds to the database column V_DRAWDOWN_CLASS.FACILITY_VALUE
     */
    private BigDecimal FACILITY_VALUE;

    /**
     * This field corresponds to the database column V_DRAWDOWN_CLASS.GENERAL_FACILITY_TYPE
     */
    private String GENERAL_FACILITY_TYPE;

    /**
     * This field corresponds to the database column V_DRAWDOWN_CLASS.BRIEF_NAME_ENG
     */
    private String BRIEF_NAME_ENG;

    /**
     * This field corresponds to the database column V_DRAWDOWN_CLASS.BRIEF_NAME_ARAB
     */
    private String BRIEF_NAME_ARAB;

    /**
     * This field corresponds to the database column V_DRAWDOWN_CLASS.DECIMAL_POINTS
     */
    private BigDecimal DECIMAL_POINTS;

    /**
     * This field corresponds to the database column V_DRAWDOWN_CLASS.DEAL_YIELD
     */
    private BigDecimal DEAL_YIELD;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_DRAWDOWN_CLASS.COMP_CODE
     *
     * @return the value of V_DRAWDOWN_CLASS.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_DRAWDOWN_CLASS.COMP_CODE
     *
     * @param COMP_CODE the value for V_DRAWDOWN_CLASS.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_DRAWDOWN_CLASS.BRANCH
     *
     * @return the value of V_DRAWDOWN_CLASS.BRANCH
     */
    public BigDecimal getBRANCH() {
        return BRANCH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_DRAWDOWN_CLASS.BRANCH
     *
     * @param BRANCH the value for V_DRAWDOWN_CLASS.BRANCH
     */
    public void setBRANCH(BigDecimal BRANCH) {
        this.BRANCH = BRANCH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_DRAWDOWN_CLASS.CODE
     *
     * @return the value of V_DRAWDOWN_CLASS.CODE
     */
    public BigDecimal getCODE() {
        return CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_DRAWDOWN_CLASS.CODE
     *
     * @param CODE the value for V_DRAWDOWN_CLASS.CODE
     */
    public void setCODE(BigDecimal CODE) {
        this.CODE = CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_DRAWDOWN_CLASS.LINE_NBR
     *
     * @return the value of V_DRAWDOWN_CLASS.LINE_NBR
     */
    public BigDecimal getLINE_NBR() {
        return LINE_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_DRAWDOWN_CLASS.LINE_NBR
     *
     * @param LINE_NBR the value for V_DRAWDOWN_CLASS.LINE_NBR
     */
    public void setLINE_NBR(BigDecimal LINE_NBR) {
        this.LINE_NBR = LINE_NBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_DRAWDOWN_CLASS.CLASS
     *
     * @return the value of V_DRAWDOWN_CLASS.CLASS
     */
    public BigDecimal getCLASS() {
        return CLASS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_DRAWDOWN_CLASS.CLASS
     *
     * @param CLASS the value for V_DRAWDOWN_CLASS.CLASS
     */
    public void setCLASS(BigDecimal CLASS) {
        this.CLASS = CLASS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_DRAWDOWN_CLASS.CATEGORY
     *
     * @return the value of V_DRAWDOWN_CLASS.CATEGORY
     */
    public BigDecimal getCATEGORY() {
        return CATEGORY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_DRAWDOWN_CLASS.CATEGORY
     *
     * @param CATEGORY the value for V_DRAWDOWN_CLASS.CATEGORY
     */
    public void setCATEGORY(BigDecimal CATEGORY) {
        this.CATEGORY = CATEGORY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_DRAWDOWN_CLASS.FACILITY_VALUE
     *
     * @return the value of V_DRAWDOWN_CLASS.FACILITY_VALUE
     */
    public BigDecimal getFACILITY_VALUE() {
        return FACILITY_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_DRAWDOWN_CLASS.FACILITY_VALUE
     *
     * @param FACILITY_VALUE the value for V_DRAWDOWN_CLASS.FACILITY_VALUE
     */
    public void setFACILITY_VALUE(BigDecimal FACILITY_VALUE) {
        this.FACILITY_VALUE = FACILITY_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_DRAWDOWN_CLASS.GENERAL_FACILITY_TYPE
     *
     * @return the value of V_DRAWDOWN_CLASS.GENERAL_FACILITY_TYPE
     */
    public String getGENERAL_FACILITY_TYPE() {
        return GENERAL_FACILITY_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_DRAWDOWN_CLASS.GENERAL_FACILITY_TYPE
     *
     * @param GENERAL_FACILITY_TYPE the value for V_DRAWDOWN_CLASS.GENERAL_FACILITY_TYPE
     */
    public void setGENERAL_FACILITY_TYPE(String GENERAL_FACILITY_TYPE) {
        this.GENERAL_FACILITY_TYPE = GENERAL_FACILITY_TYPE == null ? null : GENERAL_FACILITY_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_DRAWDOWN_CLASS.BRIEF_NAME_ENG
     *
     * @return the value of V_DRAWDOWN_CLASS.BRIEF_NAME_ENG
     */
    public String getBRIEF_NAME_ENG() {
        return BRIEF_NAME_ENG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_DRAWDOWN_CLASS.BRIEF_NAME_ENG
     *
     * @param BRIEF_NAME_ENG the value for V_DRAWDOWN_CLASS.BRIEF_NAME_ENG
     */
    public void setBRIEF_NAME_ENG(String BRIEF_NAME_ENG) {
        this.BRIEF_NAME_ENG = BRIEF_NAME_ENG == null ? null : BRIEF_NAME_ENG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_DRAWDOWN_CLASS.BRIEF_NAME_ARAB
     *
     * @return the value of V_DRAWDOWN_CLASS.BRIEF_NAME_ARAB
     */
    public String getBRIEF_NAME_ARAB() {
        return BRIEF_NAME_ARAB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_DRAWDOWN_CLASS.BRIEF_NAME_ARAB
     *
     * @param BRIEF_NAME_ARAB the value for V_DRAWDOWN_CLASS.BRIEF_NAME_ARAB
     */
    public void setBRIEF_NAME_ARAB(String BRIEF_NAME_ARAB) {
        this.BRIEF_NAME_ARAB = BRIEF_NAME_ARAB == null ? null : BRIEF_NAME_ARAB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_DRAWDOWN_CLASS.DECIMAL_POINTS
     *
     * @return the value of V_DRAWDOWN_CLASS.DECIMAL_POINTS
     */
    public BigDecimal getDECIMAL_POINTS() {
        return DECIMAL_POINTS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_DRAWDOWN_CLASS.DECIMAL_POINTS
     *
     * @param DECIMAL_POINTS the value for V_DRAWDOWN_CLASS.DECIMAL_POINTS
     */
    public void setDECIMAL_POINTS(BigDecimal DECIMAL_POINTS) {
        this.DECIMAL_POINTS = DECIMAL_POINTS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column V_DRAWDOWN_CLASS.DEAL_YIELD
     *
     * @return the value of V_DRAWDOWN_CLASS.DEAL_YIELD
     */
    public BigDecimal getDEAL_YIELD() {
        return DEAL_YIELD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column V_DRAWDOWN_CLASS.DEAL_YIELD
     *
     * @param DEAL_YIELD the value for V_DRAWDOWN_CLASS.DEAL_YIELD
     */
    public void setDEAL_YIELD(BigDecimal DEAL_YIELD) {
        this.DEAL_YIELD = DEAL_YIELD;
    }
}